:icons: font
:toc:
:toc-title: İDARİ YARGILAMA

== İDARİ DAVA

İdari dava türleri şunlardır:

.. İdarî işlemler hakkında yetki, şekil, sebep, konu ve maksat yönlerinden biri
ile hukuka aykırı olduklarından dolayı iptalleri için menfaatleri ihlâl
edilenler tarafından açılan *iptal davaları*,
+
İptal davası idari muameleleri hukuk aleminden kaldırmanın aracıdır.
.. İdari eylem ve işlemlerden dolayı kişisel hakları doğrudan muhtel olanlar
tarafından açılan *tam yargı davaları*,
+
TIP: Tam yargı davasının konusu maddi alemde ortaya çıkan bir zararın tazmini
veya iptal davası dışında kalan her türlü taleptir.
.. Tahkim yolu öngörülen imtiyaz şartlaşma ve sözleşmelerinden doğan
uyuşmazlıklar hariç, kamu hizmetlerinden birinin yürütülmesi için yapılan her
türlü idari sözleşmelerden dolayı taraflar arasında çıkan uyuşmazlıklara
ilişkin davalar.
+
TIP: Bir görüşe göre burada sözleşme davasından söz edilmektedir. Diğer bir
görüşe göre ise burada üçüncü bir dava türü değil idari sözleşmelerden ötürü
hem iptal davası hem de tam yargı davası açılabileceği işaret edilmektedir.

CAUTION: *İdari işlem* ve *idari sözleşmeye* karşı iptal davası veya tam yargı
davası açılabilir. *İdari eyleme* karşı ise ancak tam yargı davası açılabilir.

== İDARİ İŞLEM, İDARİ EYLEM, İDARİ SÖZLEŞME

*İdari işlem*, idarenin yaptığı tek taraflı hukuki işlemdir. Yürütülebilmesi için
karşı tarafın rızasına ihtiyaç yoktur. İdari işlemin dava konusu edilebilmesi
için _kesin_ ve _yürütülebilir_ nitelikte olması gerekir.

*İdari eylem*, idarenin bir şeyi yapması veya yapmaması sonucunda ortaya çıkan
maddi olaydır. İdari eylem sayılabilmesi için kökeninde bir işlem bulunmaması
gerekir.

*İdari sözleşme*, idareye sözleşmede tek taraflı olarak değişiklik yetkisi
veren sözleşmelerdir. İdari sözleşmenin konusu bir kamu faaliyetinin görülmesi
veya bir kamu malının işletilmesidir.

== GÖREV

=== DANIŞTAY

Danıştay en üst derece mahkemesi ve temyiz merciidir. Danıştay bir davada
görevliyse aynı zamanda yetkilidir. Kanunda öngörülen bazı hallerde ilk derece
mahkemesi olarak görev yapar.

=== BÖLGE İDARE MAHKEMELERİ

Bölge idare mahkemelerinin ilk derece mahkemesi olarak görevli olduğu bir
uyuşmazlık tipi olmasa da çeşitli itirazların ilk derece olarak bölge idare
mahkemesine gitmesi söz konusudur. Örneğin memurların yargılanmasına karşı
itiraz.

Danıştay ilk derece mahkemesi olarak:

.. Bakanlar Kurulu kararlarına
.. Başbakanlık, bakanlıklar ve diğer kamu kurum ve kuruluşlarının
müsteşarlarıyla ilgili müşterek kararnamelere,
.. Bakanlıklar ile kamu kuruluşları veya kamu kurumu niteliğindeki meslek
kuruluşlarınca çıkarılan ve ülke çapında uygulanacak düzenleyici işlemlere,
.. Danıştay İdari Dairesince veya İdari İşler Kurulunca verilen kararlar
üzerine uygulanan eylem ve işlemlere,
.. Birden çok idare veya vergi mahkemesinin yetki alanına giren işlere,
.. Danıştay Yüksek Disiplin Kurulu kararları ile bu Kurulun görev alanı ile
ilgili Danıştay Başkanlığı işlemlerine,

Karşı açılacak iptal ve tam yargı davaları ile tahkim yolu öngörülmeyen kamu
hizmetleri ile ilgili imtiyaz şartlaşma ve sözleşmelerinden doğan idari
davaları karara bağlar.

Danıştay, belediyeler i le il özel idarelerinin seçimle gelen organlarının
organlık sıfatlarını kaybetmeleri hakkındaki istemleri inceler ve karara
bağlar.

=== VERGİ MAHKEMELERİ

Vergi mahkemeleri:

.. Genel bütçeye, il özel idareleri, belediye ve köylere ait vergi, resim ve
harçlar ile benzeri mali yükümler ve bunların zam ve cezaları ile tarifelere
ilişkin davaları,
.. (a) bendindeki konularda 6183 sayılı Amme Alacaklarının Tahsil Usulü
Hakkında Kanunun uygulanmasına ilişkin davaları,
.. Diğer kanunlarla verilen işleri,

Çözümler.

=== İDARE MAHKEMELERİ

Danıştay, bölge idare mahkemesi veya vergi mahkemesinin görev alanına girmeyen
uyuşmazlıklarda görevli mahkeme idare mahkemesidir.

== YETKİ

=== GENEL YETKİ

Göreve ilişkin hükümler saklı kalmak şartıyla bu Kanunda veya özel kanunlarda
yetkili idare mahkemesinin gösterilmemiş olması halinde, yetkili idare
mahkemesi, dava konusu olan idari işlemi veya idari sözleşmeyi yapan idari
merciin bulunduğu yerdeki idare mahkemesidir.

=== KAMU GÖREVLİLERİ İLE İLGİLİ DAVALARDA YETKİ

Kamu görevlilerinin atanması ve nakilleri ile ilgili davalarda yetkili mahkeme,
kamu görevlilerinin yeni veya eski görev yeri idare mahkemesidir.

Kamu görevlilerinin görevlerine son verilmesi, emekli edilmeleri veya görevden
uzaklaştırılmaları ile ilgili davalarda yetkili mahkeme, kamu görevlisinin son
görev yaptığı yer idare mahkemesidir.

Kamu görevlilerinin görevle ilişkisinin kesilmesi sonucunu doğurmayan disiplin
cezaları ile ilerleme, yükselme, sicil, intibak ve diğer özlük ve parasal
hakları ve mahalli idarelerin organları ile bu organların üyelerinin geçici bir
tedbir olarak görevden uzaklaştırılmalarıyla ilgili davalarda yetkili mahkeme
ilgilinin görevli bulunduğu yer idare mahkemesidir.

Özel kanunlardaki hükümler saklı kalmak kaydıyla, hâkim ve savcıların mali ve
sosyal haklarına ve sicillerine ilişkin konularla, müfettiş hal kâğıtları- na
karşı açacakları ve idare mahkemelerinin görevine giren davalarda yetkili
mahkeme, hâkim veya savcının görev yaptığı yerin idari yargı yetkisi yönünden
bağlı olduğu bölge idare mahkemesine en yakın bölge idare mahkemesinin
bulunduğu yer idare mahkemesidir.

=== TAŞINMAZ MALLARA İLİŞKİN DAVALARDA YETKİ

İmar, kamulaştırma, yıkım, işgal, tahsis, ruhsat ve iskan gibi taşınmaz
mallarla ilgili mevzuatın uygulanmasında veya bunlara bağlı her türlü haklara
veya kamu mallarına ilişkin idari davalarda yetkili mahkeme taşınmaz malların
bulunduğu yer idare mahkemesidir.

Köy, belediye ve özel idareleri ilgilendiren mevzuatın uygulanmasına ilişkin
davalarla sınır uyuşmazlıklarında yetkili mahkeme, mülki idari birimin, köy,
belediye veya mahallenin bulunduğu yahut yeni bağlandığı yer idare
mahkemesidir.

=== TAM YARGI DAVALARINDA YETKİ

İdari sözleşmelerden doğanlar dışında kalan tam yargı davalarında yetkili
mahkeme, sırasıyla:

.. Zararı doğuran idari uyuşmazlığı çözümlemeye yetkili,
.. Zarar, bayındırlık ve ulaştırma gibi bir hizmetten veya idarenin herhangi
bir eyleminden doğmuş ise, hizmetin görüldüğü veya eylemin yapıldığı yer,
.. Diğer hallerde davacının ikametgahının bulunduğu yer.

İdari mahkemesidir.

=== VERGİ UYUŞMAZLIKLARINDA YETKİ

Bu Kanununa göre vergi uyuşmazlıklarında yetkili mahkeme:

.. Uyuşmazlık konusu vergi, resim, harç ve benzeri mali yükümleri tarh ve
tahakkuk ettiren, zam ve cezaları kesen,
.. Gümrük Kanununa göre alınması gereken vergilerle Vergi Usul Kanunu ğereğince
şikayet yoluyla vergi düzeltme taleplerinin reddine ilişkin işlemlerde; vergi,
resim, harç ve benzeri mali yükümleri tarh ve tahakkuk ettiren,
.. Amme Alacaklarının Tahsil Usulu Kanunun uygulanmasında, ödeme emrini
düzenleyen,
.. Diğer uyuşmazlıklarda dava konusu işlemi yapan,

Dairenin bulunduğu yerdeki vergi mahkemesidir.

== BAĞLANTILI DAVALAR

Aynı maddi veya hukuki sebepten doğan ya da biri hakkında verilecek
hüküm,diğerini etkileyecek nitelikte olan davalar bağlantılı davalardır.

. İdare mahkemesi, vergi mahkemesi veya Danıştaya veya birden fazla idare veya
vergi mahkemelerine açılmış bulunan davalarda bağlantının varlığına taraflardan
birinin isteği üzerine veya doğrudan doğruya mahkemece karar verilir.
. Bağlantılı davalardan birinin Danıştayda bulunması halinde dava dosyası
Danıştaya gönderilir.
. Bağlantılı davalar, değişik bölge idare mahkemesinin yargı çevrelerindeki
mahkemelerde bulunduğu takdirde dosyalar Danıştaya gönderilir.
. Bağlantılı davalar aynı bölge idare mahkemesinin yargı çerçevesindeki
mahkemelerde bulunduğu takdirde dosyalar o yer bölge idare mahkemesine
gönderilir.

Bu davalar aynı mahkemede görülecek ama *birleştirilmeyecektir*. Mahkeme iki
dosya hakkında da ayrı ayrı karar verecektir.

CAUTION: Adli yargıdaki bir dava ile idari yargıdaki bir dava hiçbir zaman aynı
mahkemede toplanamaz. Sadece birbirlerini bekletici mesele sayabilirler.

== HMK İLE VUK'UN UYGULANACAĞI HALLER

Kanunda hüküm bulunmayan hususlarda; hakimin davaya bakmaktan memnuiyeti ve
reddi, ehliyet, üçüncü şahısların davaya katılması, davanın ihbarı, tarafların
vekilleri, feragat ve kabul, teminat, mukabil dava, bilirkişi, keşif,
delillerin tespiti, yargılama giderleri, adli yardım hallerinde ve duruşma
sırasında tarafların mahkemenin sukünunu ve inzibatını bozacak hareketlerine
karşı yapılacak işlemler ile elektronik işlemlerde Hukuk Usulü Muhakemeleri
Kanunu hükümleri uygunlanır. Ancak, davanın ihbarı Danıştay, mahkeme veya hakim
tarafından re'sen yapılır.

Bilirkişiler, bilirkişilik bölge kurulları tarafından hazırlanan listelerden
seçilir ve bilirkişiler hakkında Bilirkişilik Kanunu ve 12/1/2011 tarihli ve
6100 sayılı Hukuk Muhakemeleri Kanununun ilgili hükümleri uygulanır.

Bu Kanun ve yukarıdaki fıkra uyarınca Hukuk Usulü Muhakemeleri Kanununa atıfta
bulunulan haller saklı kalmak üzere, vergi uyuşmazlıklarının çözümünde Vergi
Usul Kanununun ilgili hükümleri uygulanır.

== DAVANIN AÇILMASI

İdari davalar, Danıştay, idare mahkemesi ve vergi mahkemesi başkanlıklarına
hitaben yazılmış imzalı dilekçelerle açılır.

Dilekçelerde;

. Tarafların ve varsa vekillerinin veya temsilcilerinin ad ve soyadları veya
unvanları ve adresleri ile gerçek kişilere ait Türkiye Cumhuriyeti kimlik
numarası,
. Davanın konu ve sebepleri ile dayandığı deliller,
. Davaya konu olan idari işlemin yazılı bildirim tarihi,
. Vergi, resim, harç, benzeri mali yükümler ve bunların zam ve cezalarına
ilişkin davalarla tam yargı davalarında uyuşmazlık konusu miktar,
. Vergi davalarında davanın ilgili bulunduğu verginin veya vergi cezasının
nevi ve yılı, tebliğ edilen ihbarnamenin tarihi ve numarası ve varsa mükellef
hesap numarası,

Gösterilir.

Dava konusu kararın ve belgelerin asılları veya örnekleri dava dilekçesine
eklenir. Dilekçeler ile bunlara ekli evrakın örnekleri karşı taraf sayısından
bir fazla olur.

Dilekçeler ve savunmalar ile davalara ilişkin her türlü evrak, Danıştay veya
ait olduğu mahkeme başkanlıklarına veya bunlara gönderilmek üzere idare veya
vergi mahkemesi başkanlıklarına, idare veya vergi mahkemesi bulunmayan yerlerde
büyükşehir belediyesi sınırları içerisinde kalıp kalmadığına bakılmaksızın
asliye hukuk hakimliklerine veya yabancı memleketlerde Türk konsolosluklarına
verilebilir.

NOTE: Dilekçenin verilmesiye dava açılmış olur.

Her idari işlem aleyhine ayrı ayrı dava açılır. Ancak, aralarında maddi veya
hukuki yönden bağlılık yada sebep-sonuç ilişkisi bulunan birden fazla işleme
karşı bir dilekçe ile de dava açılabilir.

Birden fazla şahsın müşterek dilekçe ile dava açabilmesi için davacıların hak
veya menfaatlerinde iştirak bulunması ve davaya yol açan maddi olay veya hukuki
sebeplerin aynı olması gerekir.

Dilekçeler, Danıştayda daire başkanının görevlendireceği bir tetkik hakimi,
idare ve vergi mahkemelerinde ise mahkeme başkanı veya görevlendireceği bir üye
tarafından:

.. Görev ve yetki,
.. İdari merci tecavüzü,
.. Ehliyet,
.. İdari davaya konu olacak kesin ve yürütülmesi gereken bir işlem olup
olmadığı,
.. Süre aşımı,
.. Husumet,
.. 3 ve 5 inci maddelere uygun olup olmadıkları,

Yönlerinden sırasıyla incelenir.

Dilekçeler bu yönlerden kanuna aykırı görülürse durum; görevli daire veya
mahkemeye bir rapor ile bildirilir. Tek hakimle çözümlenecek dava dilek- çeleri
için rapor düzenlenmez ve 15 inci madde hükümleri ilgili hakim tarafından
uygulanır. 3 üncü fıkraya göre yapılacak inceleme ve bu fıkra ile 5 inci
fıkraya göre yapılacak işlemler dilek- çenin alındığı tarihten itibaren en geç
onbeş gün içinde sonuçlandırılır.

İlk incelemeyi yapanlar, bu noktalardan kanuna aykırılık görmezler veya daire
veya mahkeme tarafından ilk inceleme raporu yerinde görülmezse, tebligat işlemi
yapılır.

Yukarıdaki hususların ilk incelemeden sonra tespit edilmesi halinde de davanın
her safhasında 15 nci madde hükmü uygulanır.

Danıştay veya idare ve vergi mahkemelerince yukarıdaki maddenin 3 üncü
fıkrasında yazılı hususlarda kanuna aykırılık görülürse, 14 üncü maddenin;

.. 3/a bendine göre adli ve askeri yargının görevli olduğu konularda açılan
davaların reddine; idari yargının görevli olduğu konularda ise görevli veya
yetkili olmayan mahkemeye açılan davanın görev veya yetki yönünden reddedilerek
dava dosyasının görevli veya yetkili mahkemeye gönderilmesine,
.. 3/c, 3/d ve 3/e bentlerinde yazılı hallerde davanın reddine,
.. 3/f bendine göre, davanın hasım gösterilmeden veya yanlış hasım gösterilerek
açılması halinde, dava dilekçesinin tespit edilecek gerçek hasma tebliğine,
.. 3/g bendinde yazılı halde otuzgün içinde 3 ve 5 inci maddelere uygun şekilde
yeniden düzenlenmek veya noksanları tamamlanmak yahut (c) bendinde yazılı
hallerde, ehliyetli olan şahsın avukat olmayan vekili tarafından dava açılmış
ise otuzgün içinde bizzat veya bir avukat vasıtasıyla dava açılmak üzere
dilekçelerin reddine,
.. 3/b bendinde yazılı halde dilekçelerin görevli idare merciine tevdiine,

Karar verilir.

== İDARİ YARGIDA TARAFLAR

=== DAVACI

İdari yargıda davacı olabilmek için *medeni yargıdaki şartlara ek olarak* bazı
şartlar aranmaktadır. İptal davası açabilmek için bir *menfaatin ihlali*
aranmaktadır. Tam yargı davası açabilmek için ise *kişisel hakkın doğrudan
muhtel olması* şartı aranmıştır.

Her iki dava türü bakımından da dava konusu işlemle davacı arasında belirli bir
ilginin varlığı aranmaktadır. Bu ilgi *kişisel*, *güncel* ve *meşru* olmalıdır.

İptal davasında gerçek kişiler ve özel hukuk tüzel kişileri yanında kamu tüzel
kişileri de davacı olabilir. Kamu tüzel kişisi bir başka kamu tüzel kişisine
karşı aralarında hiyerarşi veya vesayet yoksa dava açabilir.

[NOTE]
====
*Kamu tüzel kişiliği olmayan bir idari makamın bir tüzel kişiliğe dava açması
mümkün mü?*

Tüzel kişiliği olmayan bir idari makam kanunla kendisine verilmiş bir görevin
ifası kapsamında dava açabilir.
====

Tam yargı davasında davacı olmak için *hakkın doğrudan ihlali* aranmaktadır.

=== DAVALI

Tam yargı davasında davalının tüzel kişiliği olması şarttır.

İptal davasında davalı olmak için tüzel kişiliğin varlığı şart değildir. Dava
işlemi yapılan makama açılır.

TIP: Danıştay'ın uygulamasına göre davalı sıfatı aynı hiyerarşideki hukuk
müşavirliği olan ilk makama verilmektedir.

Davalı dilekçede bulunması zorunlu bir unsur değildir. Hasım gösterilmez veya
yanlış gösterilirse bile mahkeme hasım düzeltme kararı verecek ve gerçek hasma
tebliğ edecektir.

NOTE: Özel hukuk tüzel kişileri de kamusal güç kullanabildiği durumda idari
yargıda davalı olabilir. Ancak özel hukuk tüzel kişileri kamu hizmeti görürken
bunu idarenin denetimi ve gözetimi altında yapar. Dolayısıyla idarede özel
hukuk tüzel kişisi ile birlikte davalı olacaktır.

TIP: İdare adına faaliyet gösteren özel hukuk tüzel kişilerinin özel hukuk
sözleşmeleriyle üçüncü kişilerle olan ilişkilerinden doğan uyuşmazlıkların adli
yargının alanına girer. Kamusal statüleri, talepleri, faaliyetten yararlanma
talepleri nedeniyle üçüncü kişilerin kamu hizmeti gören özel hukuk tüzel
kişileriyle olan uyuşmazlıkları ise idari yargının alanına girer.

== DAVA AÇMA SÜRELERİ

=== GENEL ESASLAR

Süreler, tebliğ, yayın veya ilan tarihini izleyen günden itibaren işlemeye
başlar.

NOTE: Dava açmak için tebligatın yapılmasını beklemek zorunlu değildir.
Danıştay'ın görüşü bu yöndedir.

Tatil günleri sürelere dahildir. Şu kadarki, sürenin son günü tatil gününe
rastlarsa, süre tatil gününü izleyen çalışma gününün bitimine kadar uzar.

Sürelerin bitmesi çalışmaya ara verme zamanına (adli tatil) rastlarsa bu
süreler, ara vermenin sona erdiği günü izleyen tarihten itibaren yedi gün
uzamış sayılır.

=== GENEL DAVA SÜRESİ

Dava açma süresi, özel kanunlarında ayrı süre gösterilmeyen hallerde Danıştayda
ve *idare mahkemelerinde altmış* ve vergi mahkemelerinde otuz gündür.

Bu süreler;

.. *İdari uyuşmazlıklarda; yazılı bildirimin yapıldığı*,
.. Vergi, resim ve harçlar ile benzeri mali yükümler ve bunların zam ve
cezalarından doğan uyuşmazlıklarda: Tahakkuku tahsile bağlı olan vergilerde
tahsilatın; tebliğ yapılan hallerde veya tebliğ yerine geçen işlemlerde
tebliğin; tevkif yoluyla alınan vergilerde istihkak sahiplerine ödemenin;
tescile bağlı vergilerde tescilin yapıldığı ve idarenin dava açması gereken
konularda ise ilgili merci veya komisyon kararının idareye geldiği;

Tarihi izleyen günden başlar.

TIP: Kural olarak işleme ilişkin idare tarafından yapılan tebligatta dava açma
süresinin de belirtilmesi gerekir. Eğer özel dava açma süresi belirtilmemişse
Danıştay'a göre bu özel süre içerisinde açılamaması halinde genel dava
süresinde açılan davaların kabul edilmesi gerekir.

Adresleri belli olmayanlara özel kanunlarındaki hükümlere göre ilan yoluyla
bildirim yapılan hallerde, özel kanununda aksine bir hüküm bulunmadıkça süre,
son ilan tarihini izleyen günden itibaren onbeş gün sonra işlemeye başlar.

İlanı gereken düzenleyici işlemlerde dava süresi, ilan tarihini izleyen günden
itibaren başlar. Ancak bu işlemlerin uygulanması üzerine ilgililer, düzenleyici
işlem veya uygulanan işlem yahut her ikisi aleyhine birden dava açabilirler.
Düzenleyici işlemin iptal edilmemiş olması bu düzenlemeye dayalı işlemin
iptaline engel olmaz.

Uygulama işlemi özel hukuk alanında olan bir işlem ise idari yargıda dava
edilemeyecektir. Ancak özel hukuktaki uygulama işleminin dayanağı olan
düzenleyici işlem idari yargıda dava edilebilecektir.

Süreklilik arz eden bir ihlal varsa süreye tabi olmaksızın dava açılabilir.
Yoklukla batıl işlemler de süreye tabi olmadan dava edilebilir.

=== GÖREVLİ OLMAYAN YERLERE BAŞVURMA

Çözümlenmesi Danıştayın, idare ve vergi mahkemelerinin görevlerine girdiği
halde, adli ve askeri yargı yerlerine açılmış bulunan davaların görev
noktasından reddi halinde, bu husustaki kararların kesinleşmesini izleyen
günden itibaren otuz gün içinde görevli mahkemede dava açılabilir. Görevsiz
yargı merciine başvurma tarihi, Danıştaya, idare ve vergi mahkemelerine
başvurma tarihi olarak kabul edilir.

Adli veya askeri yargı yerlerine açılan ve görevsizlik sebebiyle reddedilen
davalarda, görevsizlik kararının kesinleşmesinden sonra yukarıda yazılı otuz
günlük süre geçirilmiş olsa dahi, idari dava açılması için öngörülen süre henüz
dolmamış ise bu süre içinde idari dava açılabilir.

=== İDAREYE BAŞVURU

İlgililer, haklarında idari davaya konu olabilecek bir işlem veya eylemin
yapılması için idari makamlara başvurabilirler.

Altmış gün içinde bir cevap verilmezse istek reddedilmiş sayılır.

İlgililer altmış günün bittiği tarihten itibaren dava açma süresi içinde,
konusuna göre Danıştaya, idare ve vergi mahkemelerine dava açabilirler.

Altmış günlük süre içinde idarece verilen cevap kesin değilse ilgili bu cevabı,
isteminin reddi sayarak dava açabileceği gibi, kesin cevabı da bekleyebilir. Bu
takdirde dava açma süresi işlemez. Ancak, bekleme süresi başvuru tarihinden
itibaren altı ayı geçemez.

Dava açılmaması veya davanın süreden reddi hallerinde, altmış günlük sürenin
bitmesinden sonra yetkili idari makamlarca cevap verilirse, cevabın tebliğinden
itibaren altmış gün içinde dava açabilirler.

=== ÜST MAKAMLARA BAŞVURMA

İlgililer tarafından idari dava açılmadan önce, idari işlemin kaldırılması,
geri alınması değiştirilmesi veya yeni bir işlem yapılması üst makamdan, üst
makam yoksa işlemi yapmış olan makamdan, idari dava açma süresi içinde
istenebilir. Bu başvurma, işlemeye başlamış olan idari dava açma süresini
durdurur.

Altmış gün içinde bir cevap verilmezse istek reddedilmiş sayılır.

İsteğin reddedilmesi veya reddedilmiş sayılması halinde dava açma süresi
yeniden işlemeye başlar ve başvurma tarihine kadar geçmiş süre de hesaba
katılır.

=== İPTAL VE TAM YARGI DAVALARINDA SÜRE

İlgililer haklarını ihlal eden bir idari işlem dolayısıyla Danıştaya ve idare
ve vergi mahkemelerine doğrudan doğruya tam yargı davası veya iptal ve tam
yargı davalarını birlikte açabilecekleri gibi ilk önce iptal davası açarak bu
davanın karara bağlanması üzerine, bu husustaki kararın veya kanun yollarına
başvurulması halinde verilecek kararın tebliği veya bir işlemin icrası
sebebiyle doğan zararlardan dolayı icra tarihinden itibaren dava süresi içinde
tam yargı davası açabilirler. Bu halde de ilgililerin İYUK 11 nci madde
uyarınca idareye başvurma hakları saklıdır.

. Bir işlemden dolayı hakkı ihlal edilen kişi işlemin tebliğinden itibaren
altmış günlük dava süresi içinde doğrudan doğruya tam yargı davası
açabilecektir.
. Kişi isterse dava süresi içinde iptal ve tam yargı davasını birlikte
açabilecektir.
. Kişi önce iptal davası açıp bunun karara bağlanması üzerine tam yargı davası
açabilecektir.

.. İptal davasına ilişkin ilk derece mahkemesi kararının tebliğinden sonraki
dava açma süresi içinde tam yargı davası açılabilir.
.. Karşı taraf kanun yoluna başvurmuş ise kararın kesinleşmesinden sonra dava
açma süresi içinde tam yargı davası açılabilir.
+
NOTE: İdare kanun yoluna başvuru süresinden sonra başvurmuş ise üst mahkeme
tarafından usulen reddedileceğinden kararın kesinleşme tarihi ilk derece
mahkemesinin kararı verdiği tarih olacaktır. Kişi idarenin kanun yoluna
başvurusu üzerine kararın kesinleşmesini beklemeyi tercih edip bu şekilde dava
açma süresini kaçırsa da kanun yolunun reddinden itibaren dava açma süresi
tanınmalıdır. Kişinin idarenin usulüne uygun kanun yolu başvurusu yapıp
yapmadığını denetleme görevi kişiye yüklenmemelidir.
+
IMPORTANT: Kişinin kanun yoluna başvurması tam yargı davası açma süresini
durdurmaz.

. Zararın işlemin icrası ile birlikte ortaya çıktığı durumlarda dava açma
süresi geçmiş olsa bile işlemin icra tarihinden itibaren dava açma süresi
içinde tam yargı davası açılabilir.

=== İDARİ EYLEMLERDEN DOĞAN DAVALARDA SÜRE

İdari eylemlerden hakları ihlal edilmiş olanların idari dava açmadan önce, bu
eylemleri *yazılı bildirim üzerine veya başka süretle öğrendikleri tarihten
itibaren bir yıl ve her halde eylem tarihinden itibaren beş yıl* içinde ilgili
idareye başvurarak haklarının yerine getirilmesini istemeleri gereklidir.

Bu *isteklerin kısmen veya tamamen reddi halinde, bu konudaki işlemin tebliğini
izleyen günden itibaren* veya *istek hakkında altmış gün içinde cevap verilmediği
takdirde bu sürenin bittiği tarihten itibaren*, dava süresi içinde dava
açılabilir.

Görevli olmayan adli ve askeri yargı mercilerine *açılan tam yargı davasının
görev yönünden reddi halinde* sonradan idari yargı mercilerine açılacak
davalarda, yukarıda öngörülen *idareye başvurma şartı aranmaz*.

== İDARİ İŞLEMİN İPTALİ

=== YETKİ SAKATLIĞI

Yetki bir işlemin kim tarafından yapıldığını bulmaya yönelik bir unsurdur.
Sakat olup olmadığını anlamak için yapan makam ile aslında yapması gereken
makam karşılaştırılmalıdır.

İdare hukukunda yetkisizlik asıldır. Kime yetki verildiği mutlaka mevzuata
dayalı olmalıdır, mevzuatta yoksa yetkisizlik söz konusudur ve işlem sakattır.

IMPORTANT: Bir usul çerçevesinde bir makamın görüşü alınması ve karara
katılması gerekıyorsa o usule uyulmaması usul sakatlığı değil yetki sakatlığı
doğurur.

Yetki unsuru bakımından sakat işlem, işlemi yetkili makam da yapsa sonuç
değişmeyecek idiyse bile iptal edilecektir.

Yetkili makamın sonradan işleme icazet vermesi geçerli değildir. İşlemin
yapıldığı andaki hukuka uygunluğu esas alınır.

TIP: İmar ve özellikle kıyılarla ilgili konularda Danıştay, icazeti yetki
bakımından sakat bir işlemi hukuka uygun hale getiren bir müessese olarak
tanımıştır.

=== USUL SAKATLIĞI

Usul işlem yapılırken izlenmesi gereken prosedürdür. Usul sakatlığı ikiye
ayrılır: Esasa etkili usul sakatlığı, esasa etkili olmayan usul sakatlığı. Bir
işlem ancak esasa etkili usul sakatlığı sebebiyle iptal edilebilir.

=== MAKSAT UNSURU SAKATLIĞI

Bir yetki usulüne göre kullanılmasına rağmen kullanılma amacı yetkinin tanınma
amacı değil de siyasi bir amaç veya zarar verme amacı ise maksat sakatlığı söz
konusudur.

=== SEBEP VE KONU UNSURU SAKATLIĞI

İdarenin yaptığı işlemler bir sebebe dayalı olmak zorundadır. İşlem tesis
edilirken sebep gösterilmek zorunda değildir ancak sebebe dayalı yapılması
gerekir.

Sebep sakatlığı iki türlü ortaya çıkabilir: Hukuki sebep sakatlığı ve maddi
sebep sakatlığı.

İdare mevzuatta öngörülmemiş bir sebebe dayanırsa hukuki sebep sakatlığı ortaya
çıkar. İşlemin sebebi olarak esas alınan maddi unsur gerçekleşmemiş ise maddi
sebep sakatlığı söz konusudur.

Konu sakatlığı, hukuki sebep sakatlığı sonucunda ortaya çıkabileceği gibi
mevzuatta olmayan bir işlem tesis edilmesi halinde de söz konusu olabilir.

== İDARENİN SORUMLULUĞU

İdare hukuku tekniği bakımından devlet denildiğinde anlaşılması gereken merkezi
idaredir. Ancak devlet geniş anlamda yasama, yürütme ve yargı faaliyetleridir.

İdari işlemler sonucunda bir birey zarar görmüş ise bu zararların tazmini için
tam yargı davası açabilecektir.

İdarenin sorumluluğu ya kusur sorumluluğu ya da kusursuz sorumluluktur.

Kusur sorumluluğu için idarenin bir hizmet kusurunun olması gerekir. Hizmet
kusuru; hizmetin geç işlemesi, kötü işlemesi veya hiç işlememesidir.

Mücbir sebep, üçüncü kişinin kusuru veya birlikte kusur hali varsa idarenin
kusur sorumluluğu belli oranda azalır veya kaldırılır.

NOTE: Danıştay son zamanlarda idare tarafından yapılan bir işlem hukuka aykırı
ise bunu hizmet kusuru olarak yorumlamaktadır. Dolayısıyla bunlardan doğan
zararlardan da idarenin sorumluluğu söz konusudur.

İdarenin kusursuz sorumluluk hallerinden ilki **risk esası**dır. İdarenin bazı
tehlikeli faaliyetleri sonucu ne kadar tedbir alınmış olursa olunsun bir zarar
ortaya çıkmışsa idarenin sorumluluğu söz konusu olacaktır.

Diğer bir kusursuz sorumluluk hali **fedakarlığın denkleştirilmesi veya kamu
külfetleri karşısında eşitlik ilkesi**dir. İdarenin kamu yararı için yürüttüğü
faaliyetler sonucunda birtakım üçüncü kişilerin zararı söz konusu olmuşsa
idarenin bunu tazmin etmesi gerekir.

Son kusursuz sorumluluk hali ise **sosyal risk**tir. Toplum içinde yaşamaktan
kaynaklanan birtakım risklerden (terör, toplumsal eylemler) kaynaklanan
zararlar söz konusu olduğunda bu zarardan idarenin sorumlu olacağı kabul
edilmektedir. Sosyal risk ilkesine dayanmak için idarenin zararın meydana
gelmemesi için gerekli tüm tedbirleri almış olması gerekir.

Kamu görevlilerinin, zorunlu askerliğini yapan kişilerin bu görevlerini
yürütürken uğradıkları zararlardan da idare sorumludur.

Genel yaklaşıma göre yasama organının yasama faaliyetlerinden dolayı devletin
sorumluluğu doğmaz. Aynı şekilde yargı organının yargılama faaliyetlerinden
dolayı da devletin sorumluluğu söz konusu değildir.

NOTE: Yasama ve yargı organlarının kendı faaliyetleri dışında idari
faaliyetleri söz konusu olduğunda bundan doğan zararlardan devletin sorumluluğu
söz konusu olabilecektir.

== RE'SEN ARAŞTIRMA İLKESİ

Danıştay, bölge idare mahkemeleri ile idare ve vergi mahkemeleri, bakmakta
oldukları davalara ait her türlü incelemeyi kendiliğinden yapar.

Re'sen araştırma ilkesi bir yetki olduğu kadar yükümlülüktür. Taraflar ileri
sürme bile maddi veya hukuki gerçeğin ortaya çıkması için gerekli olan
işlemlerin yapılması mahkemenin yükümlülüğüdür. Bu yükümlülüğün yerine
getirilmemesi bozma sebebidir.

NOTE: Genel kabul, dava türleri arasında aryrım yapılmaksızın re'sen araştırma
ilkesinin kabul edilmesidir.

Mahkeme, usul kurallarını kendiliğinden denetleyecektir. Maddi ve hukuki olayın
belirlenmesi için kendiliğinden araştırma yapacaktır. Aynı zamanda hukuki
nitelendirmeyi de kendisi yapacaktır.

CAUTION: Re'sen araştırma ilkesine rağmen mahkeme, dava konusu edilmemiş bir
maddi vakıayı incelemeyecektir. *Ancak, ilk bakışta hayatın olağan akışına
aykırı olduğu anlaşılabilecek maddi vakıalar, taraflar arasındaki ihtilafa konu
olmasa dahi re'sen araştırılabilir.*

Mahkemeler belirlenen süre içinde lüzum gördükleri evrakın gönderilmesini ve
her türlü bilgilerin verilmesini taraflardan ve ilgili diğer yerlerden
isteyebilirler. Bu husustaki kararların, ilgililerce, süresi içinde yerine
getirilmesi mecburidir. Haklı sebeplerin bulunması halinde bu süre, bir defaya
mahsus olmak üzere uzatılabilir.

NOTE: İdarenin susma hakkı söz konusu değildir. Ancak kişiler bakımından susma
hakkının kabul edilmesi gerekir. AİHM'in de bu yönde kararları vardır.

Ancak, istenen bilgi ve belgeler Devletin güvenliğine veya yüksek menfaatlerine
veya Devletin güvenliği ve yüksek menfaatleriyle birlikte yabancı devletlere de
ilişkin ise, Başbakan veya ilgili bakan, gerekçesini bildirmek suretiyle, söz
konusu bilgi ve belgeleri vermeyebilir. Verilmeyen bilgi ve belgelere
dayanılarak ileri sürülen savunmaya göre karar verilemez.

Her kurumun kendi faaliyetleri bakımından gizli tuttuğu bilgi ve belgeler
olabilir. Ancak idarenin kendi işleyişi bakımından birtakım bilgi ve belgeleri
gizli olarak tasnif etmesi mahkemeyi bağlamaz. Kanun koyucu ancak devlet sırrı
niteliğinde olan belgeleri korumuştur.

Dilekçeler ve savunmalarla birlikte verilmeyen belgeler, bunların vaktinde
ibraz edilmelerine imkan bulunmadığına mahkemece kanaat getirilirse, kabul ve
diğer tarafa tebliğ edilir. Bu belgeler duruşmada ibraz edilir ve diğer taraf
cevabını hemen verebileceğini beyan eder veya cevap vermeye lüzum görmezse,
ayrıca tebliğ edilmez.

== HASIM DÜZELTME

Hasım düzeltmenin gerekip gerekmediği davanın esasına girilmeden ilk incelemede
çözülmesi gereken bir konudur. Fakat daha sonra farkedilmiş veya sonradan hasım
düzeltme gerekmiş ise davanın esasına girildikten sonra da karar verilebilir.

== TARAF DEĞİŞİKLİĞİ

Dava esnasında ölüm veya herhangi bir sebeple tarafların kişilik veya
niteliğinde değişiklik olursa, davayı takip hakkı kendisine geçenin
başvurmasına kadar; gerçek kişilerden olan tarafın ölümü halinde, idarenin
mirasçılar aleyhine takibi yenilemesine kadar dosyanın işlemden kaldırılmasına
ilgili mahkemece karar verilir. Dört ay içinde yenileme dilekçesi verilmemiş
ise, varsa yürütmenin durdurulması kararı kendiliğinden hükümsüz kalır.

Yalnız öleni ilgilendiren davalara ait dilekçeler iptal edilir.

Davacının gösterdiği adrese tebligat yapılamaması halinde, yeni adresin
bildirilmesine kadar dava dosyası işlemden kaldırılır ve varsa yürütmenin
durdurulması kararı kendiliğinden hükümsüz kalır. Dosyanın işlemden
kaldırıldığı tarihten başlayarak bir yıl içinde yeni adres bildirilmek
suretiyle yeniden işleme konulması istenmediği takdirde, davanın açılmamış
sayılmasına karar verilir.

Dosyaların işlemden kaldırılmasına ve davanın açılmamış sayılmasına dair
kararlar diğer tarafa tebliğ edilir.

== DAVANIN KONUSU

*Konu*, davanın tipini ve genişletilebilecek alanını belirleyen kısımdır.
Davanın konusu ile sonuç kısmının birbirleriyle bağlantılı olması
gerekmektedir.

Dava konusu olarak hangi işlem gösterilmişse, bu daha sonradan genişletilemez.

İptal davasında dava konusu hi tereddüde yol açmayacak şekilde belirlenmelidir.
Bu genelde işlemin tarihi ve sayısı belirtilerek yapılır. İşlem tebliğ
edilmemiş ise idareye başvuru yapılıp bir nüshası alınmalıdır. Bu da mümkün
değilse dava konusu edilen işlem hiç tereddüde yol açmayacak şekilde tarif
edilmelidir.

Tam yargı davasında ise istenen tazminat miktarı net bir şekilde
belirtilmelidir.

Tam yargı davalarında dava dilekçesinde belirtilen miktar, süre veya diğer usul
kuralları gözetilmeksizin nihai karar verilinceye kadar, harcı ödenmek
suretiyle bir defaya mahsus olmak üzere artırılabilir ve miktarın artırılmasına
ilişkin dilekçe otuz gün içinde cevap verilmek üzere karşı tarafa tebliğ
edilir.

NOTE: Eğer tazminat miktarı ancak mahkemenin incelemesi sonucu hesaplanabilecek
nitelikte ise olay ve hesaplanılabilir unsurlar yazılarak ıslaha gerek olmadan
istenebilir.

== YÜRÜTMENİN DURDURULMASI

Yürütmenin durdurulması iptal davasına ilişkin bir müessesedir. İdarenin
işlemlerinin hukuka uygunluğu karinesi gereği iptal davası açıldığında işlemin
yürütülmesi kendiliğinden durmaz. İşlemin yürütülmesinin durdurulması için bunun
talep edilmesi gerekir. Yürütmenin durdurulması işlemi iptal etmeye, hukuka
aykırı kılmaya yönelik bir müessese değildir.

Yürütmenin durdurulması iptal davasının açılmasından sonuçlanmasına kadar talep edilebilir.

Danıştay ve idari mahkemeler, idari işlemin uygulanması halinde *telafisi güç
veya imkansız zararların doğması* ve *idari işlemin açıkça hukuka aykırı olması*
şartlarının birlikte gerçekleşmesi durumunda, davalı idarenin savunması
alındıktan veya savunma süresi geçtikten sonra gerekçe göstererek yürütmenin
durdurulmasına karar verebilirler.

Yürütmenin durdurulması İYUK 27'de düzenlenmiştir. İYUK 27'ye göre yürütmenin
durdurulmasına karar verilebilmesi için iki şart gerçekleşmelidir:

. İşlemin yürütülmesi durdurulmazsa dava sonucunda verilecek kararın uygulanması
imkansızlaşacak olmalıdır.
. İlk bakışta hukuka aykırılık kanaati veren hususlar bulunmalıdır.

*Uygulanmakla etkisi tükenecek olan idari işlemlerin yürütülmesi, savunma
alındıktan sonra yeniden karar verilmek üzere, idarenin savunması alınmaksızın
da durdurulabilir.*

NOTE: _Kürsüye göre_ uygulanmakla etkisi tükenecek olan işlemlerin, dava
süresince yürütmesinin durdurulması kararı verilinceye kadar durdurulmasında
telafisi güç veya imkansız zarar ve açıkça hukuka aykırılık şartlarının
aranmaması gerekir. Ancak bu kararın ardından idarenin savunması alındıktan
sonra gerçek yürütmeyi durdurma kararı verilmesinde bu iki şart aranır.

CAUTION: Kamu görevlileri hakkında tesis edilen atama, naklen atama, görev ve
unvan değişikliği, geçici veya sürekli görevlendirmelere ilişkin idari işlemler,
uygulanmakla etkisi tükenecek olan idari işlemlerden sayılmaz.

Yürütmenin durdurulması kararlarında idari işlemin hangi gerekçelerle hukuka
açıkça aykırı olduğu ve işlemin uygulanması halinde doğacak telafisi güç veya
imkansız zararların neler olduğunun belirtilmesi zorunludur.

IMPORTANT: *Sadece* ilgili kanun hükmünün iptali istemiyle Anayasa Mahkemesine
başvurulduğu gerekçesiyle yürütmenin durdurulması kararı verilemez.

Dava dilekçesi ve eklerinden yürütmenin durdurulması isteminin yerinde olmadığı
anlaşılırsa, davalı idarenin savunması alınmaksızın istem reddedilebilir.

TIP: Vergi uyuşmazlıklarında davanın açılmasıyla yürütmenin duracağı
düzenlenmiştir. Ancak dava açan kişi kötüniyetli davranır ve açtığı davayı
takipsiz bırakırsa tahsilat işlemi kaldığı yerden devam eder. Kişi takipsiz
bıraktığı dosyanın işlemden kaldırılmasına sebep olur ve daha sonra yenileme
işlemi yaparsa yürütme kendiliğinden durmayacak ancak yürütmeyi durdurma talep
edilebilecektir.

Esasında yürütmeyi durdurma talebinin reddi veya kabulü bir ara karardır. Kural
olarak nihai karar verilmeden ara kararlara başka mahkeme bakamaz. Ancak
yürütmenin durdurulması kararının önemi gereği buna bir istisna getirilmiştir.

Yürütmenin durdurulması istemleri hakkında verilen kararlar;

* Danıştay dava dairelerince verilmişse konusuna göre İdari veya Vergi Dava
Daireleri Kurullarına,
* Bölge idare mahkemesi tarafından verilmişse en yakın bölge idare mahkemesine,
* İdare ve vergi mahkemeleri ile tek hakim tarafından verilen kararlara karşı
bölge idare mahkemesine,

kararın tebliğini izleyen günden itibaren *7 gün içinde* bir defaya mahsus olmak
üzere itiraz edilebilir. İtiraz edilen merciler, dosyanın kendisine gelişinden
itibaren yedi gün içinde karar vermek zorundadır. *İtiraz üzerine verilen
kararlar kesindir*.

NOTE: Danıştay'ın istikrarlı uygulaması uyarınca, iptal kararı verilse ne sonuç
doğuracak idiyse, yürütmeyi durdurma kararı da kişiyi geçici olarak o haldeki
duruma ulaştırıp, orada dondurur. Zira yürütmeyi durdurma işlemin doğuracağı
telafisi güç zararlara engel olmak içindir.

TIP: Yürütmeyi durdurma kararı, kişiye belirli bir statüye girmek bakımından
imkan sağlamışsa, yürütmeyi durdurmanın kaldırılması bu statüyü etkilemez.
Ancak, kişi statüye yürütmeyi durdurma kararı ile girmişse, yürütmeyi
durdurmanın kaldırılması ile statüden çıkar.

İlk derece mahkemesince iptal davasının reddi halinde kanun yoluna başvurulmuşsa
burada da yürütmenin durdurulması talep edilebilir. Kanun yolunda dosya önüne
gelen mahkemenin yürütmenin durdurulmasına karar verebilmesi için İYUK 27'de
sayılan iki şartın gerçekleşmesi gerekir. Ancak burada yürütmenin durdurulması
ile ilgili karara karşı bir itiraz mekanizması yoktur.

Kural olarak ilk derece mahkemesi kararları, kanun yolundan çıkacak sonuç
beklenmeksizin uygulanmak zorundadır. Ancak davalı idare, iptalle sonuçlanan
davalarda kanun yoluna başvurarak *mahkeme kararının yürütülmesinin
durdurulmasını* talep edebilir. Bunun için İYUK 27'deki şartlar aranmaz. Bu
karara karşı da bir itiraz mekanizması yoktur.

== DURUŞMA

İdari yargıda kural olarak, dosya üzerinden ve duruşmasız yargılama yapılır.
Duruşma ancak belirli şartların varlığı halinde yapılır.

Danıştay ile idare ve vergi mahkemelerinde açılan *iptal* ve *yirmibeşbin Türk
Lirasını aşan tam yargı davaları* ile tarh edilen vergi, resim ve harçlarla
benzeri mali yükümler ve bunların zam ve cezaları toplamı yirmibeşbin Türk
Lirasını aşan vergi davalarında, *taraflardan birinin isteği üzerine duruşma
yapılır*.

Temyiz ve istinaflarda duruşma yapılması *tarafların istemine* ve *Danıştay
veya ilgili bölge idare mahkemesi kararına* bağlıdır.

Duruşma talebi, dava dilekçesi ile cevap ve savunmalarda yapılabilir.

NOTE: Danıştay, mahkeme ve hakim tarafların istemine bağlı olmaksızın
kendiliğinden duruşma yapılmasına karar verebilir.

Tarafların talebine rağmen duruşma yapılmaması bir usul sakatlığı olarak kanun
yolu aşamasında ileri sürülebilir ve bozma sebebi teşkil eder.

Duruşma yapıldıktan sonra *en geç onbeş gün içinde karar verilir*. Bu bir
düzenleyici süredir.

== İSPAT VE DELİL

İdari yargıda mahkemenin re'sen araştırma yetkisi, delilleri toplama ve
değerlendirme görevini de kapsamaktadır. Taraflar ileri sürmemiş olsa bile
ilgili kişi ve kuruluşlardan bilgi ve belge isteme, araştırma yapma, keşif
yapma gibi yöntemlere mahkeme kendiliğinden başvurabilecektir.

HMK'da delillerin sunulması belirli bir zamanla sınırlıdır. Ancak idari yargıda
böyle bir şey yoktur. Temyiz aşamasında dahi yeni delil ibraz edilebilir.

İdari yargıda delil serbestisi geçerli olduğu için kural olarak kanunen yasak
olmayan her türlü delil ile ispat faaliyeti yürütülebilir.

=== DELİL TÜRLERİ

==== TANIK

İdari yargıda tanık dinleme müessesesi yoktur. Yazılılık ilkesi prensibi gereği
tanık dinletilemez. Danıştay, kategorik olarak tüm davalar bakımından tanık
beyanlarını reddetmektedir. Hatta keşif esnasında tanık dinlenmesine dahi izin
vermemektedir.

==== İKRAR

İkrar, bir vakıanın karşı taraf tarafından kabul edilmesidir. Re'sen araştırma
ilkesi, taraflardan birinin ikrar ettiği bir vakıayı mahkemenin tekrar
araştırmasını gerekli kılmaz. Hayatın olağan akışına aykırı olmayan olgular,
ikrar edilmişse mahkeme tarafından tekrar araştırılmayacaktır.

NOTE: _Kürsüye göre_ idarenin ikrardan kaçınması hukuk devletine aykırılık
teşkil edecektir.

==== BİLİRKİŞİ

Hakimlik mesleğinin dışında bilgi gerektiren teknik konular bakımından
bilirkişiye başvurulabilir.

Hem denetlenemez olması sebebiyle hem de tarafların hakimin teknik bilgisi
konusunda aksini ispat edebilme imkanı tanınmadığı için, her tür teknik
meselede, hakimin bilgi sahibi olması halinde dahi bilirkişiye gidilmelidir.

=== DELİL TESPİTİ

Dava açılmadan önceki delil tespiti bakımından HMK hükümleri uygulanır.

Taraflar, idari dava açıkldıktan sonra bu davalara ilişkin delillerin
tespitini ancak davaya bakan Danıştay, idare ve vergi mahkemelerinden
isteyebilirler.

Davaya bakan Danıştay, idare ve vergi mahkemeleri istemi uygun gördüğü takdirde
üyelerden birini bu işle görevlendirebileceği gibi, tespitin mahalli idari veya
adli yargı mercilerince yapılmasına da karar verebilir.

Delillerin tespiti istemi, ivedilikle karara bağlanır.

TIP: Noter tespitleri delil tespiti sayılmaz. Delil tespitinin bir mahkemece
yapılması gerekir. *Ancak noterler tarafından kanuna uygun olarak yapılan
tespitler mahkemeler için delil niteliğinde olacaktır.*

== DAVAYA MÜDAHALE

İYUK'ta davaya müdahale konusunda bir düzenleme yapılmamış ve HMK'ya atıfta
bulunulmuştur. Dolayısıyla davaya müdahale bakımından HMK hükümleri uygulama
alanı bulacaktır.

HMK'da iki tür müdahale vardır:

. *Asli müdahale:* Taraflar arasında görülmekte olan davadaki uyuşmazlık konusu
üzerinde hak iddia eden üçüncü kişinin davanın taraflarına dava açmasıdır.
. *Fer'i müdahale:* Üçüncü kişinin, davayı kazanmasında menfaati bulunan
tarafın yanında davaya katılarak ona yardımcı olmasıdır.

NOTE: Doktrinde çoğunluk görüşü asli müdahalenin idari yargıda mümkün
olmadığını savunmaktadır. Bundan sonra müdahale deyince fer'i müdahale
kastedilecektir.

== DAVAYA SON VEREN TARAF İŞLEMLERİ

Davaya son veren taraf işlemleri; *kabul*, *sulh* ve **feragat**tir. Bu
işlemler için de İYUK, HMK'ya atıfta bulunmuştur.

*Kabul*, davalı tarafından yapılabilen bir işlemdir. Davacı tarafından ileri
sürülen hukuki ve maddi olgunun gerçek olduğunun davalı tarafından kabul
edilmesidir.

*İdari işlemin geri alınması*, bir işlemin idare tarafından geçmişe dönük
olarak bütün sonuçlarıyla birlikte ortadan kaldırılmasıdır. *İdari işlemin
kaldırılması* ise işlemin idare tarafından ileriye dönük olarak ortadan
kaldırılmasıdır.

CAUTION: Dava açma süresi geçtikten sonra özellikle kişiler lehine sonuç
doğuran işlemler geri alınamaz. Çünkü ya kazanılmış hak doğurur ya da müesses
durum oluşturur.

Geri alma ve kaldırma her zaman kabul anlamına gelmez. Ancak geri alma ve
kaldırma ile birlikte dava konusuz kalabilir ve mahkeme bu sebeple davayı
sonlandırabilir. Davanın konusuz kalması sebebiyle sonlandırılması ile kabul
ile sona ermesi arasında fark vardır. Kabul ile açılan davanın haklı olduğu
kabul edilmiş olur.

Kabul beyanının idarede yetkili bir kimse tarafından yapılması gerekir. Kabul
beyanında bulunabilecek yetkili makam, KHK'de gösterilen usul ile belirlenir.

== HAKİMİN YASAKLILIK VE REDDİ

Tek hakimle görülen davalarda hakimin redi istemi, reddedilen hakimin
katılmadığı idare veya vergi mahkemesince incelenir.

İtiraz üzerine veya doğrudan davaya bakmakta olan bölge idare mahkemesi ile
idare ve vergi mahkemesi başkan ve üyelerinin reddi istemi, reddedilen başkan
ve üyenin katılmadığı bölge idare, idare ve vergi mahkemesince incelenir.

İdare ve vergi mahkemelerinde reddedilen başkan ve üye birden çok ise istem
bölge idare mahkemesince incelenir. Bölge idare mahkemelerinde reddedilen
başkan ve üye birden çok ise istem Danıştayca incelenir.

Danıştayca ve bu mahkemelerce ret istemleri yerinde görülürse işin esası
hakkında da karar verilir.

Hakimin çekinme hallerinde de bu hükümler uygulanır.

== ISLAH

Tam yargı davalarında dava dilekçesinde belirtilen miktar, süre veya diğer usul
kuralları gözetilmeksizin *nihai karar verilinceye kadar*, harcı ödenmek
suretiyle *bir defaya mahsus* olmak üzere artırılabilir.

== İVEDİ YARGILAMA USULÜ

İvedi yargılama usulü aşağıda sayılan işlemleren doğan uyuşmazlıklar hakkında
uygulanır:

.. İhaleden yasaklama kararı hariç *ihale işlemleri*
.. Acele kamulaştırma işlemleri
.. Özelleştirme Yüksek Kurulu kararları
.. Turizmi Teşvik Kanunu uyarınca yapılan satış, tahsis ve kiralama işlemleri
.. Çevre Kanunu uyarınca, idari yaptırım kararları hariç çevresel etki
değerlendirmesi sonucu alınan kararlar
.. Afet Riski Altındaki Alanların Dönüştürülmesi Hakkında Kanun (kentsel
dönüşüm) uyarınca alınan Bakanlar Kurulu kararları

İvedi yargılama usulünde:

* Dava süresi *otuz* gündür.
* İdari işleme itiraz kurumu (IYUK 11) uygulanmaz.
* Yedi gün içinde ilk inceleme yapılır ve dava dilekçesi ile ekleri tebliğe
çıkarılır.
* Savunma süresi dava dilekçesinin tebliğinden itibaren on beş gün olup, bu
süre bir defaya mahsus olmak üzere en fazla on beş gün uzatılabilir.
Savunmanın verilmesi veya savunma verme süresinin geçmesiyle dosya tekemmül
etmiş sayılır.
* Taraflar birer tane dilekçe verir.
* Yürütmenin durdurulması talebine ilişkin olarak verilecek kararlara itiraz
edilemez.
* Dava dosyanın tekemmülünden itibaren en geç bir ay içinde karara bağlanır.
Ara karar verilmesi, keşif, bilirkişi incelemesi ya da duruşma yapılması gibi
işlemler ivedilikle sonuçlandırılır.
* Verilen nihai kararlara karşı tebliğ tarihinden itibaren on beş gün içinde
temyiz yoluna başvurulabilir. *İstinaf yolu kapalıdır*.
* Temyiz dilekçeleri üç gün içinde incelenir.
* Temyiz dilekçelerine cevap verme süresi on beş gündür.
* Danıştay evrak üzerinde yaptığı inceleme sonunda, maddi vakıalar hakkında
edinilen bilgiyi yeterli görürse veya temyiz sadece hukuki noktalara ilişkin
ise yahut temyiz olunan karardaki maddi yanlışlıkların düzeltilmesi mümkün ise
işin esası hakkında karar verir. Aksi halde gerekli inceleme ve tahkikatı
kendisi yaparak esas hakkında yeniden karar verir. Ancak, ilk inceleme üzerine
verilen kararlara karşı yapılan temyizi haklı bulduğu hallerde kararı bozmakla
birlikte dosyayı geri gönderir. Temyiz üzerine verilen kararlar kesindir.
* Temyiz istemi en geç iki ay içinde karara bağlanır. Karar en geç bir ay
içinde tebliğe çıkarılır.

== MERKEZİ VE ORTAK SINAVLARA İLİŞKİN YARGILAMA USULÜ

Milli Eğitim Bakanlığı ile Ölçme, Seçme ve Yerleştirme Merkezi tarafından
yapılan merkezi ve ortak sınavlar, bu sınavlara ilişkin iş ve işlemler ile
sınav sonuçları hakkında açılan davalara ilişkin yargılama usulünde:

* Dava açma süresi on gündür.
* İdari işleme itiraz kurumu (IYUK 11) uygulanmaz.
* Yedi gün içinde ilk inceleme yapılır ve dava dilekçesi ile ekleri tebliğe
* Savunma süresi dava dilekçesinin tebliğinden itibaren üç gün olup, bu
süre bir defaya mahsus olmak üzere en fazla üç gün uzatılabilir. Savunmanın
verilmesi veya savunma verme süresinin geçmesiyle dosya tekemmül etmiş sayılır.
* Yürütmenin durdurulması talebine ilişkin olarak verilecek kararlara itiraz
edilemez.
* Dava dosyanın tekemmülünden itibaren en geç on beş gün içinde karara
bağlanır. Ara karar verilmesi, keşif, bilirkişi incelemesi ya da duruşma
yapılması gibi işlemler ivedilikle sonuçlandırılır.
* Verilen nihai kararlara karşı tebliğ tarihinden itibaren beş gün içinde
temyiz yoluna başvurulabilir. *İstinaf yolu kapalıdır*.
* Temyiz dilekçeleri üç gün içinde incelenir.
* Temyiz dilekçelerine cevap verme süresi beş gündür.
* Danıştay evrak üzerinde yaptığı inceleme sonunda, maddi vakıalar hakkında
edinilen bilgiyi yeterli görürse veya temyiz sadece hukuki noktalara ilişkin
ise yahut temyiz olunan karardaki maddi yanlışlıkların düzeltilmesi mümkün ise
işin esası hakkında karar verir. Aksi halde gerekli inceleme ve tahkikatı
kendisi yaparak esas hakkında yeniden karar verir. Ancak, ilk inceleme üzerine
verilen kararlara karşı yapılan temyizi haklı bulduğu hallerde kararı bozmakla
birlikte dosyayı geri gönderir. Temyiz üzerine verilen kararlar kesindir.
* Temyiz istemi en geç on beş gün içinde karara bağlanır. Karar en geç yedi gün
içinde tebliğe çıkarılır.

Milli Eğitim Bakanlığı ile Ölçme, Seçme ve Yerleştirme Merkezi tarafından
yapılan merkezi ve ortak sınavlar, bu sınavlara ilişkin iş ve işlemler ile
sınav sonuçları hakkında açılan davalarda verilen yürütmenin durdurulması ve
iptal kararları, söz konusu sınava katılan kişilerin lehine sonuç doğuracak
şekilde uygulanır.

== YARGI KARARLARININ UYGULANMASI

İptal kararları geçmişe etkilidir. İşlem hiç yapılmamış gibi, hukuk aleminde
hiç varlık kazanmamış gibi hukuki sonuç ortaya çıkarır. Örneği görevden alınan
bir memurun açtığı dava sonucunda görevden alma işlemine ilişkin iptal kararı
verilirse memur hiç görevden alınmamış gibi işlem yapılması, tüm özlük hakları
ve ücret haklarının verilmesi gerekir.

Yeni bir yönetmelik yapıldığında veya bir yönetmeliğin hükmü değiştiğinde
idarenin aynı anda tecelli eden iki iradesi vardır. İlk iradesi mevcut
yönetmeliği değiştirme iradesi, ikinci iradesi ise yeni bir düzenleme yapma
iradesidir. İptal kararı ile birlikte idarenin bu iki iradesinin de hukuka
aykırı olduğu kabul edilmektedir. *Bu nedenle imar planları hariç düzenleyici
işlemler iptal edildiğinde eski hükümlerinin tekrar devreye girmesi Danıştay
tarafından kabul edilmektedir*. İmar planı iptal edildiğinde ise o alan plansız
bir alana dönüşür ve Plansız Alanlar Yönetmeliği hükümlerine tabi olur.

TIP: Danıştay'ın genel uygulamasına göre bir imar planı iptal edildiğinde inşaatlar
durur. Ancak inşaatların durması, inşaatların hukuka aykırı hale gelmesi
anlamına gelmez. Zira bu inşaatlar yapılırken yürürlükte olan imar planına
yapılmıştır. Danıştay bu durumda inşaatın devamına izin verilmeyeceğini ve yeni
bir imar planı yapılmasının bekleneceğini söylemektedir. Yeni imar planına göre
inşaatın muhafazası mümkün değilse bitmiş kısım kamulaştırılıp yıkılacaktır.

Bazı iptal kararları kendiliğinden sonuç doğurur, idarenin herhangi bir işlem
yapmasına gerek kalmaz. Bazı iptal kararının sonucunda ise idare, işlemdeki
sakatlık sebebini ortadan kaldırmak suretiyle aynı işlemi yeniden tesis
edebilir. Bazı iptal kararlarında ise iptal kararının yerine getirilmesi için
idarenin birtakım işlemler tesis etmesi gerekir.

Danıştay, bölge idare mahkemeleri, idare ve vergi mahkemelerinin *esasa* ve
*yürütmenin durdurulmasına* ilişkin kararlarının icaplarına göre idare,
gecikmeksizin *işlem tesis etmeye* veya *eylemde bulunmaya* mecburdur. Bu süre
hiçbir şekilde *kararın idareye tebliğinden başlayarak otuz günü geçemez*.

NOTE: Önemli olan yargı kararının 30 gün içinde uygulanması değildir. Önemli
olan kararın yerine getirilmesi için gereken işlemleri 30 gün içinde
başlanmasıdır.

Konusu belli bir miktar paranın ödenmesini gerektiren davalarda hükmedilen
miktar ile her türlü davalarda hükmedilen vekalet ücreti ve yargılama
giderleri, davacının veya vekilinin davalı idareye yazılı şekilde bildireceği
banka hesap numarasına, bu bildirim tarihinden itibaren 30 gün içerisinde
yatırılır. Bu süre içerisinde yatırılmaması halinde ilamlı icraya başvurulur.

Danıştay, bölge idare mahkemeleri, idare ve vergi mahkemeleri kararlarına göre
işlem tesis edilmeyen veya eylemde bulunulmayan hallerde idare aleyhine
Danıştay ve ilgili idari mahkemede maddi ve manevi tazminat davası açılabilir.

CAUTION: Tazminat davası sonucunda idarenin tazminat ödemeye mahkum edilmesi
kararın uygulanmayacağı anlamına gelmez.

Yargı kararının uygulanmasında bir hukuki imkansızlık söz konusu olabilir.
Ancak, *yargı kararının uygulanmasında hukuki imkansızlık bulunması iptal
edilen işlem nedeniyle uğranılan zararların tazminini engellemez.*

NOTE: Yargı kararının muvazaalı uygulanması da uygulanmaması anlamına gelir.

[TIP]
====
Yargı kararının uygulanması için idareye yapılan başvuru İYUK 10
başvurusudur.

.Madde 10 – İdari makamların sükutu
****
1. İlgililer, haklarında idari davaya konu olabilecek bir işlem veya eylemin
yapılması için idari makamlara başvurabilirler.

2. Altmış gün içinde bir cevap verilmezse istek reddedilmiş sayılır. İlgililer
altmış günün bittiği tarihten itibaren dava açma süresi içinde, konusuna
göre Danıştaya, idare ve vergi mahkemelerine dava açabilirler. Altmış günlük
süre içinde idarece verilen cevap kesin değilse ilgili bu cevabı,isteminin
reddi sayarak dava açabileceği gibi, kesin cevabı da bekleyebilir. Bu takdirde
dava açma süresi işlemez. Ancak, bekleme süresi başvuru tarihinden itibaren
altı ayı geçemez. Dava açılmaması veya davanın süreden reddi hallerinde, altmış
günlük sürenin bitmesinden sonra yetkili idari makamlarca cevap verilirse,
cevabın tebliğinden itibaren altmış gün içinde dava açabilirler.
****
====

Yargı kararlarının uygulanmaması veya gereği gibi uygulanmaması sebebiyle
uğranılan zararlar tam yargı davasına konu edilebilir.

İdareye yapılan başvuru sonucu yargı kararının uygulanmaması ayrıca kamu
görevlilerinin hukuki, cezai ve disiplin sorumluluğunu doğurur. Yargı
kararının uygulanmaması görevi ihmal suçu kapsamına girmektedir.

Yargı kararının uygulanmaması sebebiyle açılacak tam yargı davası bakımından
kanunda bir süre öngörülmemiştir. Danıştay'ın da yerleşik bir görüşü yoktur.
*Kürsüye göre* burada söz konusu olmamalıdır, zira devam eden bir hak ihlali
söz konusudur.

IMPORTANT: Yargı kararının uygulanmaması sebebiyle tam yargı davası açılması ve
bu dava sonucunda idarenin tazminata mahkum edilmesi yargı kararının
uygulanmayabileceği anlamına gelmez. İdare yargı kararını her halükarda
uygulamak zorundadır.

== KANUN YOLLARI

=== İSTİNAF

İstinaf, ilk derece mahkemesi kararlarının usul ve esas yönünden hukuka
uygunluğunun incelendiği ve bir hukuka aykırılık söz konusu ise ilk derece
mahkemesinin işlevinin üstlenilerek esas hakkında karar verildiği kanun
yoludur.

İdare ve vergi mahkemelerinin kararlarına karşı, başka kanunlarda farklı bir
kanun yolu görülmüş olsa dahi, mahkemenin bulunduğu yargı çevresindeki bölge
idare mahkemesine, *kararın tebliğinden itibaren otuz gün içinde* istinaf
yoluna başvurulabilir.

*Konusu beş bin Türk lirasını geçmeyen* vergi davaları, tam yargı davaları ve
idari işlemlere karşı açılan iptal davaları hakkında idare ve vergi
mahkemelerince verilen kararlar kesin olup, bunlara karşı istinaf yoluna
başvurulamaz.

CAUTION: İstinaf yolunun açık olup olmadığı değerlendirilirken ilk derece
mahkemesinin hükmettiği miktara değil, davacının talep ettiği miktara bakılır.

İstinaf, temyizin şekil ve usullerine tabidir. İstinaf başvurusuna konu olacak
kararlara karşı yapılan kanun yolu başvurularında dilekçelerdeki hitap ve
istekle bağlı kalınmaksızın dosyalar bölge idare mahkemesine gönderilir.

NOTE: İstinaf başvurusu ilk derece mahkemesine yapılır. Örneğin İstanbul 1.
İdare Mahkemesi kararına karşı istinafa başvuruluyorsa dilekçede "_İstanbul
Bölge İdare Mahkemesine sunulmak üzere_" yazmalıdır. İstinafa tabi bir karara
karşı temyiz dilekçesi yazılmış olsa bile ilk derece mahkemesi bunu bölge idare
mahkemesine gönderir.

İstinaf yoluna başvurabilmek için davanın tarafının kanun yoluna başvurmada
hukuki yararı olmalıdır.

Bölge idare mahkemesi, yaptığı inceleme sonunda ilk derece mahkemesi kararını
hukuka uygun bulursa istinaf başvurusunun reddine karar verir. Karardaki maddi
yanlışlıkların düzeltilmesi mümkün ise gerekli düzeltmeyi yaparak aynı kararı
verir.

Bölge idare mahkemesi, ilk derece mahkemesi kararını hukuka uygun bulmadığı
takdirde istinaf başvurusunun kabulü ile ilk derece mahkemesi kararının
kaldırılmasına karar verir. Bu halde bölge idare mahkemesi işin esası
hakkında yeniden bir karar verir.

Bölge idare mahkemesi, *ilk inceleme üzerine verilen kararlara karşı* yapılan
istinaf başvurusunu haklı bulduğu, davaya görevsiz veya yetkisiz mahkeme
yahut reddedilmiş veya yasaklanmış hakim tarafından bakılmış olması
hallerinde, istinaf başvurusunun kabülü ile ilk derece mahkemesi
kararının kaldırılmasına karar vererek dosyayı ilgili mahkemeye gönderir. Bölge
idare mahkemesinin bu fıkra uyarınca verilen kararları kesindir.

NOTE: İlk inceleme, ilk derece mahkemesinin yetki, görev, dava ehliyeti, süre
bakımından yaptığı incelemedir.

İvedi yargılama usulüne tabi olan davalarda istinaf yoluna başvurulamaz.

TIP: Danıştay'ın ilk derece mahkemesi olarak verdiği kararlara karşı istinafa
değil temyize gidilir. Bu başvurular Danıştay'ın başka bir dairesi tarafından
incelenir.

=== TEMYİZ

Danıştay dava dairelerinin nihai kararları ile bölge idare mahkemelerinin
aşağıda sayılan davalar hakkında verdikleri kararlar, başka kanunlarda aksine
hüküm bulunsa dahi Danıştayda, *kararın tebliğinden itibaten otuz gün içinde*
temyiz edilebilir:

.. *Düzenleyici işlemlere karşı açılan iptal davaları*
.. Konusu *yüz bin Türk lirasını aşan* vergi davaları, tam yargı davaları ve
idari işlemler hakkında açılan davalar
.. Belli bir meslekten, kamu görevinden veya öğrencilik *statüsünden çıkarılma
sonucunu doğuran işlemlere karşı açılan iptal davaları*
.. Belli bir ticari faaliyetin icrasını süresi veya otuz gün yahut daha uzun
süreyle engelleyen işlemlere karşı açılan iptal davaları
.. Müşterek kararnameyle yapılan atama, naklen atama ve görevden alma işlemleri
ile daire başkanı ve daha üst düzey kamu görevlilerinin atama, naklen atama ve
görevden alma işlemleri hakkında açılan iptal davaları
.. *İmar planları*, parselasyon işlemlerinden kaynaklanan davalar

NOTE: Danıştay'ın ilk derece mahkemesi olarak verdiği kararlar bakımından her
zaman temyize gidilebilir.

Temyiz istemleri Danıştay Başkanlığına hitaben yazılmış dilekçeler ile yapılır.

TIP: Temyiz istemi de ilk derece mahkemesine dilekçe vermek suretiyle yapılır.
Bu sebeple İstanbul 1. İdare Mahkemesinin kararına karşı istinafa
başvurulduktan sonra İstanbul Bölge İdare Mahkemesinin kararına karşı temyize
başvurulurken "_Danıştay Başkanlığına sunulmak üzere, İstanbul Bölge İdare
Mahkemesi Başkanlığına gönderilmek üzere İstanbul 1. İdare Mahkemesi
Başkanlığına hitaben_" yazılacaktır.

Temyiz dilekçelerinin İYUK 3'te yer alan esaslara göre düzenlenmesi gereklidir.
Düzenlenmemiş ise eksikliklerin onbeş gün içinde tamamlatılması hususu, kararı
veren Danıştay veya bölge idare mahkemesince ilgiliye tebliğ olunur. Bu sürede
eksiklikler tamamlanmazsa temyiz isteminde bulunulmamış sayılmasına Danıştay ve
bölge idare mahkemesince karar verilir.

Temyiz dilekçesi karşı tarafa tebliğ edilir. Karşı taraf tebliğ tarihini
izleyen otuz gün içinde cevap verebilir. Cevap veren, kararı süresinde temyiz
etmemiş olsa bile düzenleyeceği dilekçesinde, temyiz isteminde bulunabilir. Bu
takdirde bu dilekçeler temyiz dilekçesi yerine geçer.

*Yürütmenin durdurulması isteği bulunan temyiz dilekçeleri, karşı tarafa tebliğ
edilmeden dosya ile birlikte, yürütmenin durdurulması istemi hakkında karar
verilmek üzere* kararı veren bölge idare mahkemesince Danıştay Başkanlığına,
Danıştayın ilk derece mahkemesi olarak baktığı davalarda, görevli dairece
konusuna göre İdari veya Vergi Dava Daireleri Kuruluna gönderilir.  Danıştayda
görevli daire veya kurul tarafından yürütmenin durdurulması istemi hakkında
karar verildikten sonra tebligat bu daire veya kurulca yapılarak dosya tekemmül
ettirilir.

Temyiz dilekçesi verilirken gerekli harç ve giderlerin tamamının ödenmemiş
olması halinde kararı veren; merci tarafından verilecek yedi günlük süre
içerisinde tamamlanması, aksi halde temyizden vazgeçilmiş sayılacağı hususu
temyiz edene yazılı olarak bildirilir. Verilen süre içinde harç ve giderler
tamamlanmadığı takdirde, ilgili merci, kararın temyiz edilmemiş sayılmasına
karar verir.

Temyizin kanuni süre geçtikten sonra yapılması veya kesin bir karar hakkında
olması halinde de kararı veren merci, temyiz isteminin reddine karar verir.
İlgili merciin bu kararları ile temyiz isteminde bulunulmamış sayılmasına
ilişkin kararlarına karşı, tebliğ tarihini izleyen günden itibaren yedi gün
içinde temyiz yoluna başvurulabilir.

Temyiz incelemesi sonunda Danıştay;

.. Kararı hukuka uygun bulursa onar. Kararın sonucu hukuka uygun olmakla
birlikte gösterilen gerekçeyi doğru bulmaz veya eksik bulursa, kararı,
gerekçesini değiştirerek onar.
.. Kararda yeniden yargılama yapılmasına ihtiyaç duyulmayan maddi hatalar ile
düzeltilmesi mümkün eksiklik veya yanlışlıklar varsa kararı düzelterek onar.

Temyiz incelemesi sonunda Danıştay;

.. Görev ve yetki dışında bir işe bakılmış olması,
.. Hukuka aykırı karar verilmesi,
.. Usul hükümlerinin uygulanmasında kararı etkileyebilecek nitelikte hata veya
eksikliklerin bulunması,

sebeplerinden dolayı incelenen kararı bozar.

Kararların kısmen onanması ve kısmen bozulması hâllerinde kesinleşen kısım
Danıştay kararında belirtilir.

Temyiz incelemesi sonucunda verilen karar, dosyayla birlikte kararı veren
mercie gönderilir. Ancak Danıştay ilgili dairesinin onamaya ilişkin kararları,
dosyayla birlikte kararı veren ilk derece mahkemesine, kararın bir örneği de
bölge idare mahkemesine gönderilir. Bu kararlar, dosyanın geldiği tarihten
itibaren yedi gün içinde taraflara tebliğe çıkarılır.

Temyiz incelemesi sonucunda verilen bozma kararı üzerine ilgili merci, dosyayı
öncelikle inceler ve varsa gerekli tahkik işlemlerini tamamlayarak yeniden
karar verir.

Bölge idare mahkemesi, Danıştayca verilen bozma kararına uyabileceği gibi
kararında ısrar da edebilir.

Danıştayın bozma kararına uyulduğu takdirde, bu kararın temyiz incelemesi,
bozma kararına uygunlukla sınırlı olarak yapılır.

Bölge idare mahkemesi, bozmaya uymayarak kararında ısrar ederse, ısrar
kararının temyizi hâlinde, talep, konusuna göre Danıştay İdari veya Vergi Dava
Daireleri Kurulunca incelenir ve karara bağlanır. Danıştay İdari ve Vergi Dava
Daireleri Kurulları kararlarına uyulması zorunludur.

=== İSTİNAF VE TEMYİZDE YÜRÜTMENİN DURDURULMASI

Kanun yolu aşamasında yürütmenin durdurulması talebi iki şekilde söz konusu
olabilir:

. İlk derece mahkemesi kararının yürütmesinin durdurulması
. Dava konusu edilen işlemin yürütmesinin durdurulması

Temyiz veya istinaf yoluna başvurulmuş olması, hakim, mahkeme veya Danıştay
kararlarının yürütülmesini durdurmaz. Ancak, bu kararların teminat karşılığında
yürütülmesinin durdurulmasına temyiz istemini incelemeye yetkili Danıştay dava
dairesi, kurulu veya istinaf başvurusunu incelemeye yetkili bölge idare
mahkemesince karar verilebilir.

Davanın reddine ilişkin kararlara karşı temyiz ya da istinaf yoluna
başvurulması halinde, dava konusu işlem hakkında yürütmenin durdurulması kararı
verilebilmesi 27 nci maddede öngörülen koşulun varlığına bağlıdır.

Temyiz ve istinaf incelemesi sırasında yürütmenin durdurulması istemleri
hakkında verilen kararlar kesindir.

IMPORTANT: Bölge idare mahkemelerince istinaf aşamasında verilmiş yürütmenin
durdurulması kararlarına karşı başka bir yargı merciine başvurulamaz.

Kararın bozulması, kararın yürütülmesini kendiliğinden durdurur.

[CAUTION]
====
İşlem, idare mahkemesi tarafından iptal kararı verilerek hukuk aleminden
kaldırıldıktan sonra Danıştay bu iptal kararını bozarsa, buradaki bozma işlemin
yürütmesini durdurmaz tam tersine işlemi yürürlüğe sokar. Bu nedenle "_Kararın
bozulması, kararın yürütülmesini kendiliğinden durdurur._" hükmü (İYUK 52/5)
uygulama alanı bulmaz.

İlk derece mahkemesi iptal talebini reddetmişse işlem hala yürürlüktedir.
Danıştay iptal talebinin reddi kararını bozarsa İYUK 52/5 devreye girer ve
bozma kararı, işlemin yürütülmesini kendiliğinden durdurur.
====

=== KANUN YARARINA TEMYİZ

*İdare ve vergi mahkemeleri ile bölge idare mahkemelerinin kesin olarak verdiği
kararlar* ile *istinaf veya temyiz incelemesinden geçmeden kesinleşmiş bulunan
kararlardan* niteliği bakımından yürürlükteki hukuka aykırı bir sonucu ifade
edenler, ilgili bakanlıkların göstereceği lüzum üzerine veya kendiliğinden
Başsavcı tarafından kanun yararına temyiz olunabilir.

Temyiz isteği yerinde görüldüğü takdirde karar, kanun yararına bozulur. Bu
bozma kararı, daha önce kesinleşmiş olan merci kararının hukuki sonuçlarını
kaldırmaz.

Bozma kararının bir örneği ilgili bakanlığa gönderilir ve Resmi Gazete'de
yayımlanır.

=== YARGILAMANIN YENİLENMESİ

Danıştay ile bölge idare, idare ve vergi mahkemelerinden verilen kararlar
hakkında, aşağıda yazılı sebepler dolayısıyla yargılamanın yenilenmesi
istenebilir.

.. Zorlayıcı sebepler dolayısıyla veya lehine karar verilen tarafın eyleminden
doğan bir sebeple elde edilemeyen bir belgenin kararın verilmesinden sonra ele
geçirilmiş olması,
.. Karara esas olarak alınan belgenin, sahteliğine hükmedilmiş veya sahte
olduğu mahkeme veya resmi bir makam huzurunda ikrar olunmuş veya sahtelik
hakkındaki hüküm karardan evvel verilmiş olup da, yargılamanın yenilenmesini
isteyen kimsenin karar zamanında bundan haberi bulunmamış olması,
.. Karara esas olarak alınan bir ilam hükmünün, kesinleşen bir mahkeme
kararıyla bozularak ortadan kalkması,
.. Bilirkişinin kasıtla gerçeğe aykırı beyanda bulunduğunun mahkeme kararıyla
belirlenmesi,
.. Lehine karar verilen tarafın, karara etkisi olan bir hile kullanmış olması,
.. Vekil veya kanuni temsilci olmayan kimseler ile davanın görülüp karara
bağlanmış bulunması,
.. Çekinmeye mecbur olan başkan, üye veya hakimin katılmasıyla karar verilmiş
olması,
.. Tarafları, konusu ve sebebi aynı olan bir dava hakkında verilen karara aykırı
yeni bir kararın verilmesine neden olabilecek kanuni bir dayanak yokken, aynı
mahkeme yahut başka bir mahkeme tarafından önceki ilamın hükmüne aykırı bir
karar verilmiş bulunması.
..  Hükmün, İnsan Haklarını ve Ana Hürriyetleri Korumaya Dair Sözleşmenin veya
eki protokollerin ihlâli suretiyle verildiğinin, Avrupa İnsan Hakları
Mahkemesinin kesinleşmiş kararıyla tespit edilmiş olması.

Yargılamanın yenilenmesi istekleri esas kararı vermiş olan mahkemece karara
bağlanır.

Yargılamanın yenilenmesi süresi, (h) bendinde yazılı sebep için on yıl, (i)
bendinde yazılı sebep için Avrupa İnsan Hakları Mahkemesi kararının
kesinleştiği tarihten itibaren bir yıl ve diğer sebepler için altmış gündür. Bu
süreler,dayanılan sebebin istemde bulunan yönünden gerçekleştiği tarihi izleyen
günden başlatılarak hesaplanır.
