:icons: font
:toc:
:toc-title: İDARİ YARGILAMA

== İDARİ DAVA

İdari dava türleri şunlardır:

.. İdarî işlemler hakkında yetki, şekil, sebep, konu ve maksat yönlerinden biri
ile hukuka aykırı olduklarından dolayı iptalleri için menfaatleri ihlâl
edilenler tarafından açılan *iptal davaları*,
+
İptal davası idari muameleleri hukuk aleminden kaldırmanın aracıdır.
.. İdari eylem ve işlemlerden dolayı kişisel hakları doğrudan muhtel olanlar
tarafından açılan *tam yargı davaları*,
+
TIP: Tam yargı davasının konusu maddi alemde ortaya çıkan bir zararın tazmini
veya iptal davası dışında kalan her türlü taleptir.
.. Tahkim yolu öngörülen imtiyaz şartlaşma ve sözleşmelerinden doğan
uyuşmazlıklar hariç, kamu hizmetlerinden birinin yürütülmesi için yapılan her
türlü idari sözleşmelerden dolayı taraflar arasında çıkan uyuşmazlıklara
ilişkin davalar.
+
TIP: Bir görüşe göre burada sözleşme davasından söz edilmektedir. Diğer bir
görüşe göre ise burada üçüncü bir dava türü değil idari sözleşmelerden ötürü
hem iptal davası hem de tam yargı davası açılabileceği işaret edilmektedir.

CAUTION: *İdari işlem* ve *idari sözleşmeye* karşı iptal davası veya tam yargı
davası açılabilir. *İdari eyleme* karşı ise ancak tam yargı davası açılabilir.

== İDARİ İŞLEM, İDARİ EYLEM, İDARİ SÖZLEŞME

*İdari işlem*, idarenin yaptığı tek taraflı hukuki işlemdir. Yürütülebilmesi için
karşı tarafın rızasına ihtiyaç yoktur. İdari işlemin dava konusu edilebilmesi
için _kesin_ ve _yürütülebilir_ nitelikte olması gerekir.

*İdari eylem*, idarenin bir şeyi yapması veya yapmaması sonucunda ortaya çıkan
maddi olaydır. İdari eylem sayılabilmesi için kökeninde bir işlem bulunmaması
gerekir.

*İdari sözleşme*, idareye sözleşmede tek taraflı olarak değişiklik yetkisi
veren sözleşmelerdir. İdari sözleşmenin konusu bir kamu faaliyetinin görülmesi
veya bir kamu malının işletilmesidir.

== GÖREV

=== DANIŞTAY

Danıştay en üst derece mahkemesi ve temyiz merciidir. Danıştay bir davada
görevliyse aynı zamanda yetkilidir. Kanunda öngörülen bazı hallerde ilk derece
mahkemesi olarak görev yapar.

=== BÖLGE İDARE MAHKEMELERİ

Bölge idare mahkemelerinin ilk derece mahkemesi olarak görevli olduğu bir
uyuşmazlık tipi olmasa da çeşitli itirazların ilk derece olarak bölge idare
mahkemesine gitmesi söz konusudur. Örneğin memurların yargılanmasına karşı
itiraz.

Danıştay ilk derece mahkemesi olarak:

.. Bakanlar Kurulu kararlarına
.. Başbakanlık, bakanlıklar ve diğer kamu kurum ve kuruluşlarının
müsteşarlarıyla ilgili müşterek kararnamelere,
.. Bakanlıklar ile kamu kuruluşları veya kamu kurumu niteliğindeki meslek
kuruluşlarınca çıkarılan ve ülke çapında uygulanacak düzenleyici işlemlere,
.. Danıştay İdari Dairesince veya İdari İşler Kurulunca verilen kararlar
üzerine uygulanan eylem ve işlemlere,
.. Birden çok idare veya vergi mahkemesinin yetki alanına giren işlere,
.. Danıştay Yüksek Disiplin Kurulu kararları ile bu Kurulun görev alanı ile
ilgili Danıştay Başkanlığı işlemlerine,

Karşı açılacak iptal ve tam yargı davaları ile tahkim yolu öngörülmeyen kamu
hizmetleri ile ilgili imtiyaz şartlaşma ve sözleşmelerinden doğan idari
davaları karara bağlar.

Danıştay, belediyeler i le il özel idarelerinin seçimle gelen organlarının
organlık sıfatlarını kaybetmeleri hakkındaki istemleri inceler ve karara
bağlar.

=== VERGİ MAHKEMELERİ

Vergi mahkemeleri:

.. Genel bütçeye, il özel idareleri, belediye ve köylere ait vergi, resim ve
harçlar ile benzeri mali yükümler ve bunların zam ve cezaları ile tarifelere
ilişkin davaları,
.. (a) bendindeki konularda 6183 sayılı Amme Alacaklarının Tahsil Usulü
Hakkında Kanunun uygulanmasına ilişkin davaları,
.. Diğer kanunlarla verilen işleri,

Çözümler.

=== İDARE MAHKEMELERİ

Danıştay, bölge idare mahkemesi veya vergi mahkemesinin görev alanına girmeyen
uyuşmazlıklarda görevli mahkeme idare mahkemesidir.

== YETKİ

=== GENEL YETKİ

Göreve ilişkin hükümler saklı kalmak şartıyla bu Kanunda veya özel kanunlarda
yetkili idare mahkemesinin gösterilmemiş olması halinde, yetkili idare
mahkemesi, dava konusu olan idari işlemi veya idari sözleşmeyi yapan idari
merciin bulunduğu yerdeki idare mahkemesidir.

=== KAMU GÖREVLİLERİ İLE İLGİLİ DAVALARDA YETKİ

Kamu görevlilerinin atanması ve nakilleri ile ilgili davalarda yetkili mahkeme,
kamu görevlilerinin yeni veya eski görev yeri idare mahkemesidir.

Kamu görevlilerinin görevlerine son verilmesi, emekli edilmeleri veya görevden
uzaklaştırılmaları ile ilgili davalarda yetkili mahkeme, kamu görevlisinin son
görev yaptığı yer idare mahkemesidir.

Kamu görevlilerinin görevle ilişkisinin kesilmesi sonucunu doğurmayan disiplin
cezaları ile ilerleme, yükselme, sicil, intibak ve diğer özlük ve parasal
hakları ve mahalli idarelerin organları ile bu organların üyelerinin geçici bir
tedbir olarak görevden uzaklaştırılmalarıyla ilgili davalarda yetkili mahkeme
ilgilinin görevli bulunduğu yer idare mahkemesidir.

Özel kanunlardaki hükümler saklı kalmak kaydıyla, hâkim ve savcıların mali ve
sosyal haklarına ve sicillerine ilişkin konularla, müfettiş hal kâğıtları- na
karşı açacakları ve idare mahkemelerinin görevine giren davalarda yetkili
mahkeme, hâkim veya savcının görev yaptığı yerin idari yargı yetkisi yönünden
bağlı olduğu bölge idare mahkemesine en yakın bölge idare mahkemesinin
bulunduğu yer idare mahkemesidir.

=== TAŞINMAZ MALLARA İLİŞKİN DAVALARDA YETKİ

İmar, kamulaştırma, yıkım, işgal, tahsis, ruhsat ve iskan gibi taşınmaz
mallarla ilgili mevzuatın uygulanmasında veya bunlara bağlı her türlü haklara
veya kamu mallarına ilişkin idari davalarda yetkili mahkeme taşınmaz malların
bulunduğu yer idare mahkemesidir.

Köy, belediye ve özel idareleri ilgilendiren mevzuatın uygulanmasına ilişkin
davalarla sınır uyuşmazlıklarında yetkili mahkeme, mülki idari birimin, köy,
belediye veya mahallenin bulunduğu yahut yeni bağlandığı yer idare
mahkemesidir.

=== TAM YARGI DAVALARINDA YETKİ

İdari sözleşmelerden doğanlar dışında kalan tam yargı davalarında yetkili
mahkeme, sırasıyla:

.. Zararı doğuran idari uyuşmazlığı çözümlemeye yetkili,
.. Zarar, bayındırlık ve ulaştırma gibi bir hizmetten veya idarenin herhangi
bir eyleminden doğmuş ise, hizmetin görüldüğü veya eylemin yapıldığı yer,
.. Diğer hallerde davacının ikametgahının bulunduğu yer.

İdari mahkemesidir.

=== VERGİ UYUŞMAZLIKLARINDA YETKİ

Bu Kanununa göre vergi uyuşmazlıklarında yetkili mahkeme:

.. Uyuşmazlık konusu vergi, resim, harç ve benzeri mali yükümleri tarh ve
tahakkuk ettiren, zam ve cezaları kesen,
.. Gümrük Kanununa göre alınması gereken vergilerle Vergi Usul Kanunu ğereğince
şikayet yoluyla vergi düzeltme taleplerinin reddine ilişkin işlemlerde; vergi,
resim, harç ve benzeri mali yükümleri tarh ve tahakkuk ettiren,
.. Amme Alacaklarının Tahsil Usulu Kanunun uygulanmasında, ödeme emrini
düzenleyen,
.. Diğer uyuşmazlıklarda dava konusu işlemi yapan,

Dairenin bulunduğu yerdeki vergi mahkemesidir.

== BAĞLANTILI DAVALAR

Aynı maddi veya hukuki sebepten doğan ya da biri hakkında verilecek
hüküm,diğerini etkileyecek nitelikte olan davalar bağlantılı davalardır.

. İdare mahkemesi, vergi mahkemesi veya Danıştaya veya birden fazla idare veya
vergi mahkemelerine açılmış bulunan davalarda bağlantının varlığına taraflardan
birinin isteği üzerine veya doğrudan doğruya mahkemece karar verilir.
. Bağlantılı davalardan birinin Danıştayda bulunması halinde dava dosyası
Danıştaya gönderilir.
. Bağlantılı davalar, değişik bölge idare mahkemesinin yargı çevrelerindeki
mahkemelerde bulunduğu takdirde dosyalar Danıştaya gönderilir.
. Bağlantılı davalar aynı bölge idare mahkemesinin yargı çerçevesindeki
mahkemelerde bulunduğu takdirde dosyalar o yer bölge idare mahkemesine
gönderilir.

Bu davalar aynı mahkemede görülecek ama *birleştirilmeyecektir*. Mahkeme iki
dosya hakkında da ayrı ayrı karar verecektir.

CAUTION: Adli yargıdaki bir dava ile idari yargıdaki bir dava hiçbir zaman aynı
mahkemede toplanamaz. Sadece birbirlerini bekletici mesele sayabilirler.

== HMK İLE VUK'UN UYGULANACAĞI HALLER

Kanunda hüküm bulunmayan hususlarda; hakimin davaya bakmaktan memnuiyeti ve
reddi, ehliyet, üçüncü şahısların davaya katılması, davanın ihbarı, tarafların
vekilleri, feragat ve kabul, teminat, mukabil dava, bilirkişi, keşif,
delillerin tespiti, yargılama giderleri, adli yardım hallerinde ve duruşma
sırasında tarafların mahkemenin sukünunu ve inzibatını bozacak hareketlerine
karşı yapılacak işlemler ile elektronik işlemlerde Hukuk Usulü Muhakemeleri
Kanunu hükümleri uygunlanır. Ancak, davanın ihbarı Danıştay, mahkeme veya hakim
tarafından re'sen yapılır.

Bilirkişiler, bilirkişilik bölge kurulları tarafından hazırlanan listelerden
seçilir ve bilirkişiler hakkında Bilirkişilik Kanunu ve 12/1/2011 tarihli ve
6100 sayılı Hukuk Muhakemeleri Kanununun ilgili hükümleri uygulanır.

Bu Kanun ve yukarıdaki fıkra uyarınca Hukuk Usulü Muhakemeleri Kanununa atıfta
bulunulan haller saklı kalmak üzere, vergi uyuşmazlıklarının çözümünde Vergi
Usul Kanununun ilgili hükümleri uygulanır.

== DAVANIN AÇILMASI

İdari davalar, Danıştay, idare mahkemesi ve vergi mahkemesi başkanlıklarına
hitaben yazılmış imzalı dilekçelerle açılır.

Dilekçelerde;

. Tarafların ve varsa vekillerinin veya temsilcilerinin ad ve soyadları veya
unvanları ve adresleri ile gerçek kişilere ait Türkiye Cumhuriyeti kimlik
numarası,
. Davanın konu ve sebepleri ile dayandığı deliller,
. Davaya konu olan idari işlemin yazılı bildirim tarihi,
. Vergi, resim, harç, benzeri mali yükümler ve bunların zam ve cezalarına
ilişkin davalarla tam yargı davalarında uyuşmazlık konusu miktar,
. Vergi davalarında davanın ilgili bulunduğu verginin veya vergi cezasının
nevi ve yılı, tebliğ edilen ihbarnamenin tarihi ve numarası ve varsa mükellef
hesap numarası,

Gösterilir.

Dava konusu kararın ve belgelerin asılları veya örnekleri dava dilekçesine
eklenir. Dilekçeler ile bunlara ekli evrakın örnekleri karşı taraf sayısından
bir fazla olur.

Dilekçeler ve savunmalar ile davalara ilişkin her türlü evrak, Danıştay veya
ait olduğu mahkeme başkanlıklarına veya bunlara gönderilmek üzere idare veya
vergi mahkemesi başkanlıklarına, idare veya vergi mahkemesi bulunmayan yerlerde
büyükşehir belediyesi sınırları içerisinde kalıp kalmadığına bakılmaksızın
asliye hukuk hakimliklerine veya yabancı memleketlerde Türk konsolosluklarına
verilebilir.

NOTE: Dilekçenin verilmesiye dava açılmış olur.

Her idari işlem aleyhine ayrı ayrı dava açılır. Ancak, aralarında maddi veya
hukuki yönden bağlılık yada sebep-sonuç ilişkisi bulunan birden fazla işleme
karşı bir dilekçe ile de dava açılabilir.

Birden fazla şahsın müşterek dilekçe ile dava açabilmesi için davacıların hak
veya menfaatlerinde iştirak bulunması ve davaya yol açan maddi olay veya hukuki
sebeplerin aynı olması gerekir.

Dilekçeler, Danıştayda daire başkanının görevlendireceği bir tetkik hakimi,
idare ve vergi mahkemelerinde ise mahkeme başkanı veya görevlendireceği bir üye
tarafından:

.. Görev ve yetki,
.. İdari merci tecavüzü,
.. Ehliyet,
.. İdari davaya konu olacak kesin ve yürütülmesi gereken bir işlem olup
olmadığı,
.. Süre aşımı,
.. Husumet,
.. 3 ve 5 inci maddelere uygun olup olmadıkları,

Yönlerinden sırasıyla incelenir.

Dilekçeler bu yönlerden kanuna aykırı görülürse durum; görevli daire veya
mahkemeye bir rapor ile bildirilir. Tek hakimle çözümlenecek dava dilek- çeleri
için rapor düzenlenmez ve 15 inci madde hükümleri ilgili hakim tarafından
uygulanır. 3 üncü fıkraya göre yapılacak inceleme ve bu fıkra ile 5 inci
fıkraya göre yapılacak işlemler dilek- çenin alındığı tarihten itibaren en geç
onbeş gün içinde sonuçlandırılır.

İlk incelemeyi yapanlar, bu noktalardan kanuna aykırılık görmezler veya daire
veya mahkeme tarafından ilk inceleme raporu yerinde görülmezse, tebligat işlemi
yapılır.

Yukarıdaki hususların ilk incelemeden sonra tespit edilmesi halinde de davanın
her safhasında 15 nci madde hükmü uygulanır.

Danıştay veya idare ve vergi mahkemelerince yukarıdaki maddenin 3 üncü
fıkrasında yazılı hususlarda kanuna aykırılık görülürse, 14 üncü maddenin;

.. 3/a bendine göre adli ve askeri yargının görevli olduğu konularda açılan
davaların reddine; idari yargının görevli olduğu konularda ise görevli veya
yetkili olmayan mahkemeye açılan davanın görev veya yetki yönünden reddedilerek
dava dosyasının görevli veya yetkili mahkemeye gönderilmesine,
.. 3/c, 3/d ve 3/e bentlerinde yazılı hallerde davanın reddine,
.. 3/f bendine göre, davanın hasım gösterilmeden veya yanlış hasım gösterilerek
açılması halinde, dava dilekçesinin tespit edilecek gerçek hasma tebliğine,
.. 3/g bendinde yazılı halde otuzgün içinde 3 ve 5 inci maddelere uygun şekilde
yeniden düzenlenmek veya noksanları tamamlanmak yahut (c) bendinde yazılı
hallerde, ehliyetli olan şahsın avukat olmayan vekili tarafından dava açılmış
ise otuzgün içinde bizzat veya bir avukat vasıtasıyla dava açılmak üzere
dilekçelerin reddine,
.. 3/b bendinde yazılı halde dilekçelerin görevli idare merciine tevdiine,

Karar verilir.

== İDARİ YARGIDA TARAFLAR

=== DAVACI

İdari yargıda davacı olabilmek için *medeni yargıdaki şartlara ek olarak* bazı
şartlar aranmaktadır. İptal davası açabilmek için bir *menfaatin ihlali*
aranmaktadır. Tam yargı davası açabilmek için ise *kişisel hakkın doğrudan
muhtel olması* şartı aranmıştır.

Her iki dava türü bakımından da dava konusu işlemle davacı arasında belirli bir
ilginin varlığı aranmaktadır. Bu ilgi *kişisel*, *güncel* ve *meşru* olmalıdır.

İptal davasında gerçek kişiler ve özel hukuk tüzel kişileri yanında kamu tüzel
kişileri de davacı olabilir. Kamu tüzel kişisi bir başka kamu tüzel kişisine
karşı aralarında hiyerarşi veya vesayet yoksa dava açabilir.

[NOTE]
====
*Kamu tüzel kişiliği olmayan bir idari makamın bir tüzel kişiliğe dava açması
mümkün mü?*

Tüzel kişiliği olmayan bir idari makam kanunla kendisine verilmiş bir görevin
ifası kapsamında dava açabilir.
====

Tam yargı davasında davacı olmak için *hakkın doğrudan ihlali* aranmaktadır.

=== DAVALI

Tam yargı davasında davalının tüzel kişiliği olması şarttır.

İptal davasında davalı olmak için tüzel kişiliğin varlığı şart değildir. Dava
işlemi yapılan makama açılır.

TIP: Danıştay'ın uygulamasına göre davalı sıfatı aynı hiyerarşideki hukuk
müşavirliği olan ilk makama verilmektedir.

Davalı dilekçede bulunması zorunlu bir unsur değildir. Hasım gösterilmez veya
yanlış gösterilirse bile mahkeme hasım düzeltme kararı verecek ve gerçek hasma
tebliğ edecektir.

NOTE: Özel hukuk tüzel kişileri de kamusal güç kullanabildiği durumda idari
yargıda davalı olabilir. Ancak özel hukuk tüzel kişileri kamu hizmeti görürken
bunu idarenin denetimi ve gözetimi altında yapar. Dolayısıyla idarede özel
hukuk tüzel kişisi ile birlikte davalı olacaktır.

TIP: İdare adına faaliyet gösteren özel hukuk tüzel kişilerinin özel hukuk
sözleşmeleriyle üçüncü kişilerle olan ilişkilerinden doğan uyuşmazlıkların adli
yargının alanına girer. Kamusal statüleri, talepleri, faaliyetten yararlanma
talepleri nedeniyle üçüncü kişilerin kamu hizmeti gören özel hukuk tüzel
kişileriyle olan uyuşmazlıkları ise idari yargının alanına girer.

== DAVA AÇMA SÜRELERİ

=== GENEL ESASLAR

Süreler, tebliğ, yayın veya ilan tarihini izleyen günden itibaren işlemeye
başlar.

NOTE: Dava açmak için tebligatın yapılmasını beklemek zorunlu değildir.
Danıştay'ın görüşü bu yöndedir.

Tatil günleri sürelere dahildir. Şu kadarki, sürenin son günü tatil gününe
rastlarsa, süre tatil gününü izleyen çalışma gününün bitimine kadar uzar.

Sürelerin bitmesi çalışmaya ara verme zamanına (adli tatil) rastlarsa bu
süreler, ara vermenin sona erdiği günü izleyen tarihten itibaren yedi gün
uzamış sayılır.

=== GENEL DAVA SÜRESİ

Dava açma süresi, özel kanunlarında ayrı süre gösterilmeyen hallerde Danıştayda
ve *idare mahkemelerinde altmış* ve vergi mahkemelerinde otuz gündür.

Bu süreler;

.. *İdari uyuşmazlıklarda; yazılı bildirimin yapıldığı*,
.. Vergi, resim ve harçlar ile benzeri mali yükümler ve bunların zam ve
cezalarından doğan uyuşmazlıklarda: Tahakkuku tahsile bağlı olan vergilerde
tahsilatın; tebliğ yapılan hallerde veya tebliğ yerine geçen işlemlerde
tebliğin; tevkif yoluyla alınan vergilerde istihkak sahiplerine ödemenin;
tescile bağlı vergilerde tescilin yapıldığı ve idarenin dava açması gereken
konularda ise ilgili merci veya komisyon kararının idareye geldiği;

Tarihi izleyen günden başlar.

TIP: Kural olarak işleme ilişkin idare tarafından yapılan tebligatta dava açma
süresinin de belirtilmesi gerekir. Eğer özel dava açma süresi belirtilmemişse
Danıştay'a göre bu özel süre içerisinde açılamaması halinde genel dava
süresinde açılan davaların kabul edilmesi gerekir.

Adresleri belli olmayanlara özel kanunlarındaki hükümlere göre ilan yoluyla
bildirim yapılan hallerde, özel kanununda aksine bir hüküm bulunmadıkça süre,
son ilan tarihini izleyen günden itibaren onbeş gün sonra işlemeye başlar.

İlanı gereken düzenleyici işlemlerde dava süresi, ilan tarihini izleyen günden
itibaren başlar. Ancak bu işlemlerin uygulanması üzerine ilgililer, düzenleyici
işlem veya uygulanan işlem yahut her ikisi aleyhine birden dava açabilirler.
Düzenleyici işlemin iptal edilmemiş olması bu düzenlemeye dayalı işlemin
iptaline engel olmaz.

Uygulama işlemi özel hukuk alanında olan bir işlem ise idari yargıda dava
edilemeyecektir. Ancak özel hukuktaki uygulama işleminin dayanağı olan
düzenleyici işlem idari yargıda dava edilebilecektir.

Süreklilik arz eden bir ihlal varsa süreye tabi olmaksızın dava açılabilir.
Yoklukla batıl işlemler de süreye tabi olmadan dava edilebilir.

=== GÖREVLİ OLMAYAN YERLERE BAŞVURMA

Çözümlenmesi Danıştayın, idare ve vergi mahkemelerinin görevlerine girdiği
halde, adli ve askeri yargı yerlerine açılmış bulunan davaların görev
noktasından reddi halinde, bu husustaki kararların kesinleşmesini izleyen
günden itibaren otuz gün içinde görevli mahkemede dava açılabilir. Görevsiz
yargı merciine başvurma tarihi, Danıştaya, idare ve vergi mahkemelerine
başvurma tarihi olarak kabul edilir.

Adli veya askeri yargı yerlerine açılan ve görevsizlik sebebiyle reddedilen
davalarda, görevsizlik kararının kesinleşmesinden sonra yukarıda yazılı otuz
günlük süre geçirilmiş olsa dahi, idari dava açılması için öngörülen süre henüz
dolmamış ise bu süre içinde idari dava açılabilir.

=== İDAREYE BAŞVURU

İlgililer, haklarında idari davaya konu olabilecek bir işlem veya eylemin
yapılması için idari makamlara başvurabilirler.

Altmış gün içinde bir cevap verilmezse istek reddedilmiş sayılır.

İlgililer altmış günün bittiği tarihten itibaren dava açma süresi içinde,
konusuna göre Danıştaya, idare ve vergi mahkemelerine dava açabilirler.

Altmış günlük süre içinde idarece verilen cevap kesin değilse ilgili bu cevabı,
isteminin reddi sayarak dava açabileceği gibi, kesin cevabı da bekleyebilir. Bu
takdirde dava açma süresi işlemez. Ancak, bekleme süresi başvuru tarihinden
itibaren altı ayı geçemez.

Dava açılmaması veya davanın süreden reddi hallerinde, altmış günlük sürenin
bitmesinden sonra yetkili idari makamlarca cevap verilirse, cevabın tebliğinden
itibaren altmış gün içinde dava açabilirler.

=== ÜST MAKAMLARA BAŞVURMA

İlgililer tarafından idari dava açılmadan önce, idari işlemin kaldırılması,
geri alınması değiştirilmesi veya yeni bir işlem yapılması üst makamdan, üst
makam yoksa işlemi yapmış olan makamdan, idari dava açma süresi içinde
istenebilir. Bu başvurma, işlemeye başlamış olan idari dava açma süresini
durdurur.

Altmış gün içinde bir cevap verilmezse istek reddedilmiş sayılır.

İsteğin reddedilmesi veya reddedilmiş sayılması halinde dava açma süresi
yeniden işlemeye başlar ve başvurma tarihine kadar geçmiş süre de hesaba
katılır.

=== İPTAL VE TAM YARGI DAVALARINDA SÜRE

İlgililer haklarını ihlal eden bir idari işlem dolayısıyla Danıştaya ve idare
ve vergi mahkemelerine doğrudan doğruya tam yargı davası veya iptal ve tam
yargı davalarını birlikte açabilecekleri gibi ilk önce iptal davası açarak bu
davanın karara bağlanması üzerine, bu husustaki kararın veya kanun yollarına
başvurulması halinde verilecek kararın tebliği veya bir işlemin icrası
sebebiyle doğan zararlardan dolayı icra tarihinden itibaren dava süresi içinde
tam yargı davası açabilirler. Bu halde de ilgililerin İYUK 11 nci madde
uyarınca idareye başvurma hakları saklıdır.

. Bir işlemden dolayı hakkı ihlal edilen kişi işlemin tebliğinden itibaren
altmış günlük dava süresi içinde doğrudan doğruya tam yargı davası
açabilecektir.
. Kişi isterse dava süresi içinde iptal ve tam yargı davasını birlikte
açabilecektir.
. Kişi önce iptal davası açıp bunun karara bağlanması üzerine tam yargı davası
açabilecektir.

.. İptal davasına ilişkin ilk derece mahkemesi kararının tebliğinden sonraki
dava açma süresi içinde tam yargı davası açılabilir.
.. Karşı taraf kanun yoluna başvurmuş ise kararın kesinleşmesinden sonra dava
açma süresi içinde tam yargı davası açılabilir.
+
NOTE: İdare kanun yoluna başvuru süresinden sonra başvurmuş ise üst mahkeme
tarafından usulen reddedileceğinden kararın kesinleşme tarihi ilk derece
mahkemesinin kararı verdiği tarih olacaktır. Kişi idarenin kanun yoluna
başvurusu üzerine kararın kesinleşmesini beklemeyi tercih edip bu şekilde dava
açma süresini kaçırsa da kanun yolunun reddinden itibaren dava açma süresi
tanınmalıdır. Kişinin idarenin usulüne uygun kanun yolu başvurusu yapıp
yapmadığını denetleme görevi kişiye yüklenmemelidir.
+
IMPORTANT: Kişinin kanun yoluna başvurması tam yargı davası açma süresini
durdurmaz.

. Zararın işlemin icrası ile birlikte ortaya çıktığı durumlarda dava açma
süresi geçmiş olsa bile işlemin icra tarihinden itibaren dava açma süresi
içinde tam yargı davası açılabilir.

=== İDARİ EYLEMLERDEN DOĞAN DAVALARDA SÜRE

İdari eylemlerden hakları ihlal edilmiş olanların idari dava açmadan önce, bu
eylemleri *yazılı bildirim üzerine veya başka süretle öğrendikleri tarihten
itibaren bir yıl ve her halde eylem tarihinden itibaren beş yıl* içinde ilgili
idareye başvurarak haklarının yerine getirilmesini istemeleri gereklidir.

Bu *isteklerin kısmen veya tamamen reddi halinde, bu konudaki işlemin tebliğini
izleyen günden itibaren* veya *istek hakkında altmış gün içinde cevap verilmediği
takdirde bu sürenin bittiği tarihten itibaren*, dava süresi içinde dava
açılabilir.

Görevli olmayan adli ve askeri yargı mercilerine *açılan tam yargı davasının
görev yönünden reddi halinde* sonradan idari yargı mercilerine açılacak
davalarda, yukarıda öngörülen *idareye başvurma şartı aranmaz*.

== İDARİ İŞLEMİN İPTALİ

=== YETKİ SAKATLIĞI

Yetki bir işlemin kim tarafından yapıldığını bulmaya yönelik bir unsurdur.
Sakat olup olmadığını anlamak için yapan makam ile aslında yapması gereken
makam karşılaştırılmalıdır.

İdare hukukunda yetkisizlik asıldır. Kime yetki verildiği mutlaka mevzuata
dayalı olmalıdır, mevzuatta yoksa yetkisizlik söz konusudur ve işlem sakattır.

IMPORTANT: Bir usul çerçevesinde bir makamın görüşü alınması ve karara
katılması gerekıyorsa o usule uyulmaması usul sakatlığı değil yetki sakatlığı
doğurur.

Yetki unsuru bakımından sakat işlem, işlemi yetkili makam da yapsa sonuç
değişmeyecek idiyse bile iptal edilecektir.

Yetkili makamın sonradan işleme icazet vermesi geçerli değildir. İşlemin
yapıldığı andaki hukuka uygunluğu esas alınır.

TIP: İmar ve özellikle kıyılarla ilgili konularda Danıştay, icazeti yetki
bakımından sakat bir işlemi hukuka uygun hale getiren bir müessese olarak
tanımıştır.

=== USUL SAKATLIĞI

Usul işlem yapılırken izlenmesi gereken prosedürdür. Usul sakatlığı ikiye
ayrılır: Esasa etkili usul sakatlığı, esasa etkili olmayan usul sakatlığı. Bir
işlem ancak esasa etkili usul sakatlığı sebebiyle iptal edilebilir.

=== MAKSAT UNSURU SAKATLIĞI

Bir yetki usulüne göre kullanılmasına rağmen kullanılma amacı yetkinin tanınma
amacı değil de siyasi bir amaç veya zarar verme amacı ise maksat sakatlığı söz
konusudur.

=== SEBEP VE KONU UNSURU SAKATLIĞI

İdarenin yaptığı işlemler bir sebebe dayalı olmak zorundadır. İşlem tesis
edilirken sebep gösterilmek zorunda değildir ancak sebebe dayalı yapılması
gerekir.

Sebep sakatlığı iki türlü ortaya çıkabilir: Hukuki sebep sakatlığı ve maddi
sebep sakatlığı.

İdare mevzuatta öngörülmemiş bir sebebe dayanırsa hukuki sebep sakatlığı ortaya
çıkar. İşlemin sebebi olarak esas alınan maddi unsur gerçekleşmemiş ise maddi
sebep sakatlığı söz konusudur.

Konu sakatlığı, hukuki sebep sakatlığı sonucunda ortaya çıkabileceği gibi
mevzuatta olmayan bir işlem tesis edilmesi halinde de söz konusu olabilir.

== İDARENİN SORUMLULUĞU

İdare hukuku tekniği bakımından devlet denildiğinde anlaşılması gereken merkezi
idaredir. Ancak devlet geniş anlamda yasama, yürütme ve yargı faaliyetleridir.

İdari işlemler sonucunda bir birey zarar görmüş ise bu zararların tazmini için
tam yargı davası açabilecektir.

İdarenin sorumluluğu ya kusur sorumluluğu ya da kusursuz sorumluluktur.

Kusur sorumluluğu için idarenin bir hizmet kusurunun olması gerekir. Hizmet
kusuru; hizmetin geç işlemesi, kötü işlemesi veya hiç işlememesidir.

Mücbir sebep, üçüncü kişinin kusuru veya birlikte kusur hali varsa idarenin
kusur sorumluluğu belli oranda azalır veya kaldırılır.

NOTE: Danıştay son zamanlarda idare tarafından yapılan bir işlem hukuka aykırı
ise bunu hizmet kusuru olarak yorumlamaktadır. Dolayısıyla bunlardan doğan
zararlardan da idarenin sorumluluğu söz konusudur.

İdarenin kusursuz sorumluluk hallerinden ilki **risk esası**dır. İdarenin bazı
tehlikeli faaliyetleri sonucu ne kadar tedbir alınmış olursa olunsun bir zarar
ortaya çıkmışsa idarenin sorumluluğu söz konusu olacaktır.

Diğer bir kusursuz sorumluluk hali **fedakarlığın denkleştirilmesi veya kamu
külfetleri karşısında eşitlik ilkesi**dir. İdarenin kamu yararı için yürüttüğü
faaliyetler sonucunda birtakım üçüncü kişilerin zararı söz konusu olmuşsa
idarenin bunu tazmin etmesi gerekir.

Son kusursuz sorumluluk hali ise **sosyal risk**tir. Toplum içinde yaşamaktan
kaynaklanan birtakım risklerden (terör, toplumsal eylemler) kaynaklanan
zararlar söz konusu olduğunda bu zarardan idarenin sorumlu olacağı kabul
edilmektedir. Sosyal risk ilkesine dayanmak için idarenin zararın meydana
gelmemesi için gerekli tüm tedbirleri almış olması gerekir.

Kamu görevlilerinin, zorunlu askerliğini yapan kişilerin bu görevlerini
yürütürken uğradıkları zararlardan da idare sorumludur.

Genel yaklaşıma göre yasama organının yasama faaliyetlerinden dolayı devletin
sorumluluğu doğmaz. Aynı şekilde yargı organının yargılama faaliyetlerinden
dolayı da devletin sorumluluğu söz konusu değildir.

NOTE: Yasama ve yargı organlarının kendı faaliyetleri dışında idari
faaliyetleri söz konusu olduğunda bundan doğan zararlardan devletin sorumluluğu
söz konusu olabilecektir.
