:toc:
:toc-title: SOSYAL GÜVENLİK HUKUKU
:icons: font

== SOSYAL SİGORTA

*Sigortalı*, kısa veya uzun vadeli sigorta kolları bakımından adına prim
ödenmesi gereken veya kendi adına prim ödemesi gereken kişidir.

=== STATÜLER

* *4-A*

. İş sözleşmesi uyarınca bir ya da daha fazla işveren tarafından çalıştırılan
işçiler
. İşçi sendikaları ve konfederasyonları ile sendika şubelerinin başkanlıklarına
ve yönetim kuruluna seçilenler
. Bir ya da daha fazla işveren tarafından çalıştırılan güzel sanat kolları
çalışanları
. Düşünürler, yazarlar
. Mütekabiliyet esasına dayalı olarak uluslararası sosyal güvenlik sözleşmesi
yapılmış ülke uyruğunda olanlar hariç olmak üzere yabancı uyruklu kişilerden iş
sözleşmesiyle çalışanlar
. Genelevde çalışan kadınlar
. Çiftçi Mallarının Korunması Hakkında Kanun uyarınca çalıştırılan koruma
bekçileri
. Ev hizmetlerinde çalışan ve çalışma saatine göre hesaplanan çalışma gün ve
sayısı 10 gün ve daha fazla olan kişiler

* *4-B*

. Ticari kazanç veya serbest meslek kazancı nedeniyle gerçek veya basit usulde
gelir vergisi mükellefi olanlar
. Gelir vergisinden muaf olup da esnaf ve sanatkar siciline kayıt olanlar
. Şirket ortakları
. Tarımsal faaliyette bulunanlar
. Köy ve mahalle muhtarları

* *4-C*: Kamu kurum ve kuruluşlarında çalışanlar

== BİLDİRİM

Bir işveren bir işyeri kurmuşsa, kural olarak bu işyerini en geç sigortalı
çalıştırmaya başladığı tarihe kadar kaydettirmesi gerekir.

TIP: İşyeri miras yoluyla intikal etmişse 3 aylık bir süre öngörülmüştür.

4-A'lılar çalıştırılmaya başlanmadan önce kuruma bildirilmelidir. Dolayısıyla
işverenin işçiyi çalıştırmaya başlamadan en geç bir gün önce bildirmesi
gerekir. Bunun üç istisnası vardır:

. İnşaat, balıkçılık ve tarım işyerlerinde işe başlatılacak sigortalılar için
çalışmaya başlatıldığı gün de sigorta bildirimi yapılabilir.
. Yabancı ülkeye sefer yapan ulaşım araçlarına sefer esnasında alınarak
çalıştırılan kişilerin çalışmaya başladıkları tarihten itibaren 1 ay içerisinde
bildirilmesi gerekir.
. Sosyal güvenlik kurumuna ilk defa işyeri bildirimi yapılacak işyerlerinde
tescil tarihinden itibaren 1 ay boyunca işe başlatılan işçiler bu sürenin
sonunda bildirilebilir.

Çalışmaya başlanılan tarihten itibaren bir ay içerisinde işçi de kendi
sigortalılık bildirimini yapabilir. Sigortalının kendisini bildirmesi bir
yükümlülük değil, haktır. İşveren bakımından ise bu bir yükümlülüktür.

Sigortalılığın sona ermesinin de bildirilmesi gerekir. Bunun süresi iş
sözleşmesinin sona erdiği tarihten itibaren 10 gündür.

Sigortalıların kuruma bildirilmemeleri durumunda bir dava açarak
çalışmışlıklarını kanıtlama imkanı vardır. Hizmet tespit davası ya da sigortalı
hizmetlerin hükmen tespiti davası açılır. Bu davanın açılması için aşağıdaki
koşulların varlığı gerekir:

.. Fiili çalışma söz konusu olmalıdır.
.. Sigortalının çalışmasının bildirilmemiş olması gerekir.
.. 5 yıllık hak düşürücü sürenin geçirilmemiş olması gerekir. Hak düşürücü
sürenin başlangıcı iş ilişkisinin bitimi değil yılın son günüdür. Örneğin iş
ilişkisi 1 Mart 2017'de bitmişse süre 31 Aralık 2017'den itibaren işlemeye
başlar.

== PRİM

Prim, prime esas kazanç denilen bir tutar üzerinden alınır. Yasanın öngördüğü
esaslar çerçevesinde belirlenen prime esas kazanç tutarı işçinin prim matrahını
oluşturur. Prim oranları bu tutar üzerinden hesaplanarak her ay belirlenir.
Prime esas kazancın alt sınırı brüt asgari ücrettir, üst sınırı ise bunun 7.5
katıdır.

Her ay sigortalının prime esas kazancı üzerinden altı tür prim ödenir:

. *Kısa vadeli sigorta fonları primi:* Oranı, prime esas kazancın %2'sidir.
Tamamen işveren tarafından ödenir.
. *Uzun vadeli sigorta primi:* Oranı, prime esas kazancın %20'sidir.
. *Genel sağlık sigortası primi:* Oranı, prime esas kazancın %12.5'i dir.
. *İşsizlik sigortası primi:* Oranı, prime esas kazancın %4'üdür. %1 işçi,
%1 devlet, %2 işveren tarafından ödenir.
. *Sosyal güvenlik destek primi:* Oranı, prime esas kazancın %32'sidir. Bunun
%30'u sabit, %2'si iş kazası ve meslek hastalığı içindir.
. *İsteğe bağlı sigorta:* İsteğe bağlı sigorta, sosyal güvenlik sistemine dahil
olmayan kişilerin kendi primlerini ödemek suretiyle çalışmadan emekli
olmalarını sağlayan özel bir sigorta türüdür. Bu kişilerin prime esas kazancı
olmadığından alt ve üst sınır arasında bir tercihte bulunarak ödeme yaparlar.

IMPORTANT: Prim ödeme yükümlüsü işverendir. Yukarıdaki primler arasında
işçinin cebinden çıkan pay da vardır ama bu durumda dahi ödemeyi işçi yapmaz.
İşveren, işçinin bordrosunu düzenlerken kesinti yapılacak sigorta prim
oranlarını da keser ve kendisi öder.

== SOSYAL SİGORTA TÜRLERİ

=== İŞ KAZASI VE MESLEK HASTALIĞI

==== İŞ KAZASI

*İş kazası*, sigortalının işverenin otoritesi altında bulunduğu bir sırada
gördüğü iş veya işin bir gereği dolayısıyla aniden ve dıştan meydana gelen bir
etkenle sigortalıyı bedenen ya da ruhen zarara uğratan olaydır.

NOTE: İş kazası ve meslek hastalığı hükümleri 4-A ve 4-B'lilere uygulanır.
4-C'liler iş kazası ve meslek hastalığı hükümlerine tabi değildir. 4-C'liler
vazife malüllüğü adı verilen başka bir sosyal güvenceden yararlanır.

Sigortalının işyerinde bulunduğu sırada uğradığı kazalar iş kazasıdır.
Sigortalının bu sırada çalışıyor olması şart değildir.

İşveren tarafından yürütülmekte olan iş nedeniyle meydana gelen kazalar da iş
kazasıdır. İşyeri sınırları içerisinde gerçekleşmesi şart değildir.

Bir işverene bağlı olarak çalışan sigortalının görevli olarak işyeri dışında
başka bir yere gönderilmesi nedeniyle asıl işini yapmaksızın geçen zamanlarda
meydana gelen kazalar da iş kazasıdır.

4-A kapsamında emziren kadın sigortalının çocuğuna süt vermek için ayrılan
zamanlarda (çocuk 1 yaşına gelene kadar günde 1.5 saat) bir kaza meydana
gelirse bu da iş kazası sayılacaktır.

Sigortalının işveren hesabına bir taşıtla işin yapıldığı yere girişleri ve
çıkışlarında meydana gelen kazalar da iş kazasıdır. Bu durumda sigortalının
aracın içinde olması gerekir.

==== MESLEK HASTALIĞI

Sigortalının çalıştığı veya yaptığı işin niteliğinden dolayı tekrarlanan bir
sebeple veya işin yürürlük şartları ile uğradığı geçici veya sürekli hastalık,
bedensel veya ruhsal engellilik hallerine *meslek hastalığı* denir.

CAUTION: Meslek hastalığının iş kazasından farkı mutlaka yapılan işle ilgili
olma zorunluluğudur.

Hastalığın yönetmelikte yer alması ve belirli sürede meydana gelmesi gerekir.
Ancak, meslek hastalığı listesinde yer almasa bile mesleğin gereklerinden
kaynaklanan bir hastalığın kanıtlanmasıyla da meslek hastalığı hükümlerinin
işletilmesi mümkündür.

Hastalığın kurul sağlık raporu ile saptanması şarttır.

==== BİLDİRİM

İş kazası meydana geldiğinde ya da meslek hastalığının ortaya çıktığı tespit
edildiğinde öncelikli olarak kolluk kuvvetlerine bildirimde bulunulur ve SGK'ya
3 gün içerisinde bildirilir.

==== YAPILACAK YARDIMLAR

* *Sigortalı hayatta kalırsa kendisine*

. _Geçici iş göremezlik ödeneği_
. _Sürekli iş göremezlik ödeneği_

* *Sigortalı ölürse hak sahiplerine*

. _Eş, çocuklar, anne ve babaya ölüm geliri_
. _Kız çocuklarına evlenme ödeneği_
. _Cenaze ödeneği_

==== SGK'NIN RÜCU HAKKI

SGK, sigortalıya veya hak sahiplerine yaptığı yardımları iş kazasının veya
meslek hastalığının meydana gelmesinde kusuru olan kişilere rücu edebilir.

İş kazası ve meslek hastalığı, *işverenin kastı* veya *sigortalıların sağlığını
koruma ve iş güvenliği mevzuatına aykırı bir hareketi* sonucu meydana gelmişse,
Kurumca sigortalıya veya hak sahiplerine kanun gereğince yapılan veya ileride
yapılması gereken ödemeler ile bağlanan gelirin başladığı tarihteki ilk peşin
sermaye değeri toplamı, sigortalı veya hak sahiplerinin işverenden
isteyebilecekleri tutarlarla sınırlı olmak üzere, Kurumca *işverene
ödettirilir.* İşverenin sorumluluğunun tespitinde kaçınılmazlık ilkesi dikkate
alınır.

İş kazasının, kanunda belirtilen sürede işveren tarafından Kuruma
bildirilmemesi halinde, bildirim tarihine kadar geçen süre için sigortalıya
ödenecek geçici iş göremezlik ödeneği, Kurumca işverenden tahsil edilir.

Çalışma mevzuatında sağlık raporu alınması gerektiği belirtilen işlerde, böyle
bir rapora dayanılmaksızın veya eldeki rapora aykırı olarak bünyece elverişli
olmadığı işte çalıştırılan sigortalının, bu işe girmeden önce var olduğu tespit
edilen veya bünyece elverişli olmadığı işte çalıştırılması sonucu meydana gelen
hastalığı nedeniyle, Kurumca sigortalıya ödenen geçici iş göremezlik ödeneği
işverene ödettirilir.

İş kazası, meslek hastalığı ve hastalık, *üçüncü bir kişinin kusuru nedeniyle
meydana gelmişse*, sigortalıya ve hak sahiplerine yapılan veya ileride
yapılması gereken ödemeler ile bağlanan gelirin başladığı tarihteki ilk peşin
sermaye değerinin *yarısı*, zarara sebep olan üçüncü kişilere ve şayet kusuru
varsa bunları çalıştıranlara rücu edilir.

Sigortalı çalıştırmaya başlandığının süresi içnde sigortalı işe giriş
bildirgesi ile Kuruma bildirilmemesi halinde, bildirgenin sonradan verildiği
veya sigortalı çalıştırıldığının Kurumca tespit edildiği tarihten önce meydana
gelen iş kazası ve meslek hastalığı sonucu ilgililerin gelir ve ödenekleri
Kurumca ödenir. Bu durumda, Kurumca yapılan ve ileride yapılması gereken her
türlü masrafların tutarı ile gelir bağlanırsa bu gelirin başladığı tarihteki
ilk peşin sermaye değeri tutarı, işverenin kusuru aranmaksızın işverene
ödettirilir.

=== HASTALIK SİGORTASI

Hastalık sigortası sonucunda yalnızca geçici iş göremezlik ödeneği yardımı
yapılır. Bunun şartları:

. Hastalık meydana gelmelidir. 4-A ve 4-B'lilerin iş kazası ve meslek hastalığı
dışında kalan ve iş göremezliğe neden olan rahatsızları hastalık sayılır.
. Hastalık nedeniyle oluşan geçici iş göremezlik durumunun iki günden fazla
sürmesi gerekir.
+
NOTE: İş kazası ve meslek hastalığı sigortası kapsamında verilen iş göremezlik
ödeneği ilk günden başlar. Kazanın meydana geldiği gün için dahi geçici iş
göremezlik ödeneği ödenir. Hastalıkta ise ödeme üçüncü günden başlar.
. Hastalık sebebiyle ortaya çıkan geçici iş göremezlik tarihinden önceki bir
yıl içerisinde 90 günlük kısa vadeli sigorta primlerinin bildirilmiş olması
gerekir.
. Kuruma başvurmak gerekir.

=== ANALIK SİGORTASI

Analık sigortası kapsamında yapılacak iki yardım vardır:

. Geçici iş göremezlik ödeneği
. Emzirme ödeneği

Analık sigortası kapsamında yardımdan yararlanma hakkına sahip dört kişi
vardır:

. Anne olan sigortalı
. Sigortalı erkeğin sigortalı olmayan eşi
. Kendi çalışmalarından dolayı gelir ya da aylık almakta olan kadın
. Kendi çalışmalarından dolayı gelir ya da aylık almakta olan erkeğin sigortalı
olmayan eşi

Gebeliğin başladığı tarihten itibaren analık başlar ve doğumdan sonraki izin
süresinin sonuna kadar devam eder. Doğumdan sonra izin süresi tekil
gebeliklerde 8 hafta, çoğul gebeliklerde 10 haftadır.

Geçici iş göremezlik ödeneği için aranan şartlar:

. Bu yardım sadece sigortalı kadın için geçerlidir. Zira bu yardımın sebebi
analık sebebiyle kadının çalışma hayatından uzaklaşmasıdır.
. Doğumun gerçekleştiği tarihten itibaren geriye doğru bir yıllık süre
içerisinde 90 günlük kısa vadeli sigorta kolları priminin bildirilmiş olması
gerekir.
. Kuruma başvurmak gerekir.

Emzirme ödeneği için aranan şartlar:

. Doğumun gerçekleştiği tarihten itibaren geriye doğru bir yıllık süre
içerisinde 120 günlük kısa vadeli sigorta kolları priminin bildirilmiş olması
gerekir.
. Kuruma başvurmak gerekir.

NOTE: Sigortalılık niteliğinin yitirildiği tarihten itibaren 300 gün içinde
doğum meydana gelmiş ve doğumdan itibaren geriye doğru 15 aylık zaman dilimi
içerisinde 120 günlük kısa vadeli sigorta primi bildirilmiş ise bu kişiler de
analık hükümlerinden yararlanabilir.
