:icons: font
:toc:
:toc-title: İCRA İFLAS

== İCRA TEŞKİLATI

. İcra Dairesi
. İcra Mahkemesi
. Bölge Adliye Mahkemesi
. Yargıtay'ın icra ve iflas işleri ile görevli daireleri

=== İCRA DAİRESİ

Neredeyse bütün icra takiplerinin başlaması bir icra dairesine başvurulması
suretiyle gerçekleşir. İcra daireleri hemen her ilçede kurulur ve o ilçenin
adıyla anılır (örn. Sarıyer 1. İcra Dairesi). _Her asliye mahkemesinin yargı
çevresinde yeteri kadar icra dairesi bulunur._

==== İCRA MEMURLARI

İcra takibi icra dairesinde icra memuruna başvurulmak suretiyle başlatılır.
İcra takibi talebini alan icra memuru borçluya bir ödeme emri gönderir.

İcra memuru, yargı çevresi içinde görev yaptığı icra mahkemesinin emir ve
talimatını almaz. Gerektiği takdirde kolluk kuvvetlerinden faydalanabilir.

İcra ve iflas daireleri yaptıkları işlemleri ve kendilerine gelen talep ve
beyanları tutanağa kaydederler. Aksi ispat edilinceye kadar bu tutanaklar doğru
kabul edilir (İİK 8).

İcra ve iflas dairelerince yapılacak her türlü icra ve iflas iş ve işlemlerinde
Ulusal Yargı Ağı Bilişim Sistemi kullanılır; her türlü veri, bilgi, belge ve
karar, Ulusal Yargı Ağı Bilişim Sistemi vasıtasıyla işlenir, kaydedilir ve
saklanır.

Usulüne göre güvenli elektronik imza ile oluşturulan elektronik veriler senet
hükmündedir. Güvenli elektronik imza, elle atılan imza ile aynı ispat gücünü
haizdir. Güvenli elektronik imza, kanunlarda güvenli elektronik imza ile
yapılamayacağı açıkça belirtilmiş olan işlemler dışında, elle atılan imza
yerine kullanılabilir (İİK 8/a).

WARNING: Elektronik ortamda yapılan işlemlerde süre gün sonunda biter.

İcra ve iflas işlerine bakan memur

. Kendisinin,
. Karı veya kocasının, nişanlısının yahut kan ve sıhri usul ve füruunun veya
üçüncü derece dahil olmak üzere bu dereceye kadar olan kan ve sıhri civar
hısımlarının,
. Kanuni mümessili veya vekili yahut müstahdemi bulunduğu bir şahsın,
Menfaati olan işleri göremeyip derhal icra mahkemesine haber vermeye mecburdur.

İcra mahkemesi müracaatı yerinde görürse o işi diğer bir memura, bulunmıyan
yerlerde katiplerinden birine verir (İİK 10).

Tetkik vazifesini gören hakimler ve icra ve iflas memurları, dairelerince takip
edilmekte olan bir alacak veya satılmakta bulunan bir şey hakkında kiminle
olursa olsun kendileri veya başkaları hesaplarına bir akit yapamazlar.
Yaparlarsa hükümsüzdür (İİK 11).

NOTE: Tetkik mercii İcra Mahkemesidir.

İcra ve İflas Dairesi görevlilerinin kusurlarından doğan tazminat davaları,
ancak idare aleyhine açılabilir. Devletin, zararın meydana gelmesinde kusuru
bulunan görevlilere rücu hakkı saklıdır.Bu davalara asliye mahkemelerinde
bakılır (İİK 5).

İcra dairesine tevdi veya bu dairece tahsil olunan veya muhafaza altına alınan
paraların,ilgili memur tarafından zimmete geçirilmesi halinde, zimmete
geçirilen miktar, cezai takibat sonucu beklenmeden ve tazmin yolunda bir hükme
hacet kalmaksızın hazine tarafından derhal icra veznesine yatırılır. Devletin
asıl sorumlulara rücu hakkı saklıdır (İİK 6).

İcra ve iflâs dairelerinin muamelelerine karşı yapılan şikâyetlerle itirazların
incelenmesi icra mahkemesi hâkimi yahut kanun gereğince bu görev kendisine
verilmiş olan hâkim tarafından yapılır. İş durumunun gerekli kıldığı yerlerde
Hâkimler ve Savcılar Yüksek Kurulunun olumlu görüşü ile Adalet Bakanlığınca
icra mahkemesinin birden fazla dairesi kurulabilir. Bu durumda icra mahkemesi
daireleri numaralandırılır. İcra mahkemesinin birden fazla dairesi bulunan
yerlerde iş dağılımı ve buna ilişkin esaslar, Hâkimler ve Savcılar Yüksek
Kurulunca belirlenir. Her icra mahkemesi hâkimi, kendisine Adlî Yargı Adalet
Komisyonu Başkanlığınca dönüşümlü olarak bağlanan icra ve iflâs dairelerinin
muamelelerine yönelik şikâyetleri ve itirazları inceler, bu dairelerin gözetim
ve denetimlerini yapar, idarî işlerine bakar. İcra yetkisini haiz sulh
mahkemelerinin muamelelerine karşı vuku bulacak şikayet ve itirazların icra
mahkemesi o mahkemenin hakimidir (İİK 4).

İcra ve iflâs daireleri, 4 üncü maddedeki esaslara göre icra mahkemesi
hâkiminin daimî gözetimi ve denetimi altındadır. Bu daireler Cumhuriyet
savcıları ve adalet müfettişleri vasıtası ile denetime tabi tutulur. Cumhuriyet
savcıları bu daireleri yılda en az bir defa denetlerler (İİK 13).

=== İCRA MAHKEMELERİ

* *Basit yargılama usulüne* göre karar verirler.
* Kural olarak icra takibi sırasında ortaya çıkan sorunlarla ilgilenir.
İstisnai olarak ceza mahkemesi gibi bazı cezalara da hükmedebilir.
* Tek hakimlidir.
* *Verdikleri kararlar kural olarak kesin hüküm teşkil etmez*.
* Kararlarına karşı istinaf yoluna başvurulabilir ancak istinaf sınırı diğer
hukuk mahkemelerine göre daha yüksektir.

== ŞİKAYET

Şikayet, icra ve iflas memurlarının yapmış oldukları kanuna aykırı işlemlerin
düzeltilmesi amacıyla düzenlenmiş bir müessesedir.

IMPORTANT: Şikayet dava değildir!

Şikayet icra memurunun bağlı olduğu icra mahkemesine yöneltilir. İcra mahkemesi
hakimi dilerse işlemi yapmış olan icra memurunu davet ederek dinler ancak
çağırmak zorunda değildir. Takibin karşı tarafı da bu şikayet konusu işlemin
iptalinden etkileneceği için dilerse hakim onu da dinleyebilir.

İşlem aşağıdaki sebeplerle şikayet konusu yapılabilir:

. *İşlemin kanuna uygun olmaması*
. *İşlemin olaya uygun olmaması*: Kanunun icra memuruna takdir yetkisi tanıdığı
durumlarda takdir yetkisinin olaya uygun kullanılmaması
. *Bir hakkın yerine getirilmemesi*
. *Bir hakkın sebepsiz sürüncemede bırakılması*

Şikayet eden icra takibinin tarafı olmak zorunda değildir. Kanun hukuki yararı
olmak şartıyla bütün üçüncü kişilerin şikayet yoluna başvurabileceğini
söylemektedir.

Şikayet işlemin öğrenilmesinden itibaren *yedi gün* içinde yapılmalıdır. Ancak
_kamu düzenine aykırılık_ ve _bir hakkın yerine getirilmemesi_ veya _sebepsiz
sürüncemede bırakılması_ halinde şikayet süreye bağlı değildir.

NOTE: Şikayet bir hata sonucu icra mahkemesine değil de icra dairesine yapılmış
ise süre korunmayacaktır.

Şikayet yazılı veya sözlü olarak yapılabilir.

Şikayet, icra mahkemesince karar verilmedikçe icrayı durdurmaz.

İcra mahkemesi işlemin kanuna aykırı olduğunu tespit ederse işlemi iptal ederek
icra memurundan kanuna uygun işlem yapmasını ister. İcra memurları icra
mahkemelerinin emir ve talimatı altında olmasalar bile şikayet üzerine verilen
kararlar emirdir ve buna uyulmak zorundadır.

CAUTION: İcra mahkemesi hiçbir şekilde icra mahkemesi hakimi icra memurunun
yerine geçip işlem yapmaz. Ancak kanunun saydığı istisnai hallerde düzelterek
onama kararı verebilir.

Şikayet hakkında karar veren icra mahkemesinin kararlarına karşı istinaf yoluna
başvurulabilir.

== TATİL VE TALİK HALLERİ

=== TATİLLER

Güneşin batmasından bir saat sonra ile güneşin doğmasından bir saat önceye
kadarki devrede (Gece vakti) ve tatil günlerinde takip muameleleri yapılamaz.
Ancak, gece iş görülen yerlerde gece vakti hasılat haczi mümkündür.

Tatil günlerinde haciz ve tebligat yapılabileceği gibi muhafaza tedbirleri de
alınabilir.

Borçlunun mal kaçırdığı anlaşılırsa gece vakti dahi haciz yapılması caizdir.

=== TALİK HALLERİ

. *Borçlunun ailesinden birinin ölümü halinde*: Karısı yahut kocası ve kan ve
sıhriyet itibariyle usul veya füruundan birisi ölen bir borçlu aleyhindeki
takip, ölüm günü ile beraber üç gün için talik olunur.
. *Terekenin borçlarında*: Terekenin borçlarından dolayı ölüm günü ile beraber
üç gün içinde takip geri bırakılır. Mirasçı mirası kabul veya reddetmemişse bu
hususta Kanunu Medenide muayyen müddetler geçinceye kadar takip geri kalır.
. *Tutukluluk ve hükümlülük halinde*: Mümessili olmıyan bir tutuklu veya
hükümlü aleyhine takipte, mümessil tayini vesayet makamına ait olmadıkça, icra
memuru bir mümessil tayin etmesi için kendisine münasip bir mühlet verir ve
takibi bu sürenin bitmesine bırakır. Bu mühlet içinde temsilci tayin edip icra
dairesine bildirmiyen tutuklu veya hükümlü hakkında takibe devam olunur. Mal
kaçırılması ihtimali olan hallerde bu mühlet içinde de haciz yapılabilir.
. *Askerlik halinde*: Askerlik hizmetinin devamı müddetince erler, onbaşılar ve
kıta çavuşları (Uzman veya uzatmalı çavuş ve onbaşılar hariç) aleyhine takipte,
icra memuru, bir mümessil tayin etmesi için kendisine münasip bir mühlet verir
ve takibi bu sürenin bitmesine bırakır. Bu müddet içinde temsilci tayin edip
icra dairesine bildirmiyenler hakkında takibe devam olunur. Mal kaçırılması
ihtimali olan hallerde bu mühlet içinde de haciz yapılabilir.
. *Borçlunun ağır hastalığı halinde*: Takip borçlunun mümessil tayin edemiyecek
derecede ağır hastalığı halinde muayyen bir zaman için icra memurluğunca talik
olunabilir. Ağır hastalığın resmi belge ile tahakkuku lazımdır. Mal kaçırılması
ihtimali olan hallerde hastalığın devamı sırasında da haciz yapılabilir.

NOTE: Takip talikleri esnasında müddetlerin cerayanı durmaz. Müddetin nihayeti
bir talik gününe rastlarsa müddet talikin bitiminden sonra bir gün daha
uzatlır.

== İCRA TAKİBİ

=== TAKİBİN TARAFLARI

İcra takibinin tarafları; alacaklı ve borçludur.

Takibi yapan kendisini alacaklı olarak gösterecektir. Maddi hukuk bakımından
alacaklı olup olmadığı araştırılmaz. Aleyhine takip yapılan kişi de borçludur.
Yine maddi hukuk bakımından borçlu sıfatını taşıyıp taşımadığı araştırılmaz.

Takibi başlatabilmek veya aleyhine takip başlatılabilmesi için hem alacaklının
hem de borçlunun hak ehliyetine sahip olması gerekir. Hak ehliyetinin usul
hukukundaki görünümü taraf ehliyetidir. Taraf ehliyeti icra memurunun
kendiliğinden gözetmesi gereken bir husustur. Taraf ehliyeti eksik ise icra
memuru takibi başlatmayacaktır.

=== TAKİBİN KONUSU

Genel haciz yoluyla takip para ve teminat alacakları için söz konusudur.

TIP: Para alacağı TL dışında bir para birimi üzerindense alacaklı bir seçim
hakkına sahiptir. Yabancı para borcunu dilerse vade tarihindeki dilerse fiili
ödeme tarihindeki kur üzerinden isteyebilir.

=== TAKİP TALEBİ

Takip talebi icra dairesine yazılı veya sözlü olarak ya da elektronik ortamda
yapılır.

Talepte şunlar gösterilir:

. Alacaklının ve varsa kanuni temsilcisinin ve vekilinin adı, soyadı; alacaklı
veya vekili adına ödemenin yapılacağı banka adı ile hesap bilgileri; varsa
Türkiye Cumhuriyeti kimlik numarası veya vergi kimlik numarası; şöhret ve
yerleşim yeri; alacaklı yabancı memlekette oturuyorsa Türkiye’de göstereceği
yerleşim yeri (Yerleşim yeri gösteremezse icra dairesinin bulunduğu yer
yerleşim yeri sayılır.);
. Borçlunun ve varsa kanuni temsilcisinin adı, soyadı, alacaklı tarafından
biliniyorsa Türkiye Cumhuriyeti kimlik numarası veya vergi kimlik numarası,
şöhret ve yerleşim yeri; Bir terekeye karşı yapılan taleplerde kendilerine
tebligat yapılacak mirasçıların adı, soyadı, biliniyorsa Türkiye Cumhuriyeti
kimlik numarası veya vergi kimlik numarası, şöhret ve yerleşim yerleri;
. Alacağın veya istenen teminatın Türk parasıyla tutarı ve faizli alacaklarda
faizin miktarı ile işlemeye başladığı gün, alacak veya teminat yabancı para ise
alacağın hangi tarihteki kur üzerinden talep edildiği ve faizi;
. Senet, senet yoksa borcun sebebi;
. Takip yollarından hangisinin seçildiği;

Alacak belgeye dayanmakta ise, belgenin aslının veya alacaklı yahut mümessili
tarafından tasdik edilmiş, borçlu sayısından bir fazla örneğinin takip talebi
anında icra dairesine tevdii mecburidir.

Alacaklıya takip talebinde bulunduğuna ve verdiği belgelere, talep ve takip
masraflarına dair bedava ve pulsuz bir makbuz verilir.

Yabancı para alacaklısı takip yaparken takip talebinde alacağını Türk parasına
çevirmek zorundadır. Bu çeviri takip tarihindeki Merkez Bankası efektif satış
kuru esas alınarak yapılır. Buna rağmen alacaklının para alacağını fiili ödeme
tarihindeki kur üzerinden ya da vade tarihindeki kur üzerinde talep etmesi de
mümkündür. Ancak bunun takip talebinde özellikle belirtilmiş olması gerekir.

Takip masrafları *borçluya* aittir. Takip talebinde bulunan alacaklıdan *maktu
başvurma harcı*, *nispi peşin harç*, *ödeme emrinin tebliği için gerekli
masraflar* ve borçlunun İİK 62'ye göre itirazı halinde bu *itirazın alacaklıya
tebliği için gerekli masraflar* peşinen alınır. Alacaklı ilk ödenen paradan
masraflarını alabilir.

=== TAKİBİN SONUÇLARI

. İcra müdürü ödeme emri düzenleyip borçlu veya borçlulara gönderir.
. Alacaklıya icra dairesi tarafından kendiliğinden takip talebinde bulunduğuna
ve belgelere ve takip giderlerine ilişkin bedava ve pulsuz bir belge verilir.
. Takip talebi ile zamanaşımı kesilir. Takip dolayısı ile yapılan her işlemle
tekrar kesilir.
. Borçlu o ana kadar düşmemişse ödeme emrinin tebliği ile temerrüde düşer.

NOTE: Alacaklı, yaptığı icra takibinden vazgeçip takip talebini geri alabilir.
Bunun için borçlunun rızasına ihtiyaç yoktur.

== ÖDEME EMRİ

İcra müdürü takip talebinin bu Kanunda öngörülen şartları içerdiğine karar
verirse ödeme emri düzenler. Talebin kabul edilmemesi halinde verilen karar
tutanağa yazılır.

Emir:

. Alacaklının veya vekilinin banka hesap numarası hariç olmak üzere, 58 inci
maddeye göre takip talebine yazılması lazım gelen kayıtları,
. Borcun ve masrafların yedi gün içinde icra dairesine ait ödeme emrinde yazılı
olan banka hesabına ödenmesi, borç, teminat verilmesi mükellefiyeti ise
teminatın bu süre içinde gösterilmesi ihtarını,
. Takibin dayandığı senet altındaki imza kendisine ait değilse yine bu yedi gün
içinde bu cihetin ayrıca ve açıkça bildirilmesi; aksi halde icra takibinde
senedin kendisinden sadır sayılacağı,
+
Senet altındaki imzayı reddettiği takdirde icra mahkemesi önünde yapılacak
duruşmada hazır bulunması; buna uymazsa vakı itirazın muvakkaten kaldırılmasına
karar verileceği,
+
Borcun tamamına veya bir kısmına yahut alacaklının takibat icrası hakkına dair
bir itirazı varsa bunu da aynı süre içinde beyan etmesi,
+
İhtarını,
. Senet veya borca itirazını bildirmediği takdirde yukarda yazılı yedi günlük
süre içinde 74 üncü maddeye göre mal beyanında bulunması ve bulunmazsa hapisle
tazyik olunacağı; mal beyanında bulunmaz veya hakikate aykırı beyanda bulunursa
ayrıca hapisle cezalandırılacağı ihtarını,
. Borç ödenmez veya itiraz olunmazsa cebri icraya devam edileceği beyanını,
+
İhtiva eder.

Ödeme emri iki nüsha olarak düzenlenir. Bir nüshası borçluya gönderilir, diğeri
icra dosyasına konulur. Alacaklı isterse kendisine ayrıca tasdikli bir nüsha
verilir. Nüshalar arasında fark bulunduğu takdirde borçludaki muteber sayılır.

Ödeme emri borçluya takip talebinden itibaren nihayet 3 gün içinde tebliğe
gönderilir. Takip belgeye dayanıyorsa, belgenin tasdikli bir örneği ödeme
emrine bağlanır.

Müşterek borçlular aynı zamanda takip ediliyorlarsa hepsinin veya bir kısmının
bir mümessil tarafından temsil edilmeleri hali müstesna olmak üzere her birine
ayrı ayrı ödeme emri tebliğ edilmek lazımdır.

== İTİRAZ

İtiraz etmek istiyen borçlu, itirazını, ödeme emrinin tebliği tarihinden
itibaren yedi gün içinde dilekçe ile veya sözlü olarak icra dairesine
bildirmeye mecburdur.

İtiraz, takibi yapan icra dairesinden başka bir icra dairesine yapıldığı
takdirde bu daire gereken masrafı itirazla birlikte alarak itirazı derhal
yetkili icra dairesine gönderir; alınmayan masraftan memur şahsen sorumludur.

Takibe itiraz edildiği, 59 uncu maddeye göre alacaklının yatırdığı avanstan
karşılanmak suretiyle üç gün içinde bir muhtıra ile alacaklıya tebliğ edilir.

Borçlu veya vekili, dava ve takip işlemlerine esas olmak üzere borçluya ait
yurt içinde bir adresi itirazla birlikte bildirmek zorundadır. Adresini
değiştiren borçlu yurt içinde yeni adres bildirmediği ve tebliğ memurunca yurt
içinde yeni adresi tespit edilemediği takdirde, takip talebinde gösterilen
adrese çıkarılacak tebligat borçlunun kendisine yapılmış sayılır.

Borcun bir kısmına itiraz eden borçlunun o kısman cihet ve miktarını açıkca
göstermesi lazımdır. Aksi takdirde itiraz edilmemiş sayılır.

Borçlu takibin müstenidi olan senet altındaki imzayı reddediyorsa, bunu
itirazında ayrıca ve açıkça beyan etmelidir. Aksi takdirde icra takibi
yönünden senetteki imzayı kabul etmiş sayılır.

İtiraz eden borçlu, itirazın kaldırılması duruşmasında, alacaklının dayandığı
senet metninden anlaşılanlar dışında, itiraz sebeplerini değiştiremez ve
genişletemez.

Borçlu kusuru olmaksızın bir mani sebebiyle müddeti içinde itiraz edememiş ise
paraya çevirme muamelesi bitinceye kadar itiraz edebilir.

Ancak borçlu, maniin kalktığı günden itibaren üç gün içinde, mazeretini gösterir
delillerle birlikte itiraz ve sebeplerini ve müstenidatını bildirmeye ve
mütaakıp fıkra için yapılacak duruşmaya taallük eden harç ve masrafları ödemeye
mecburdur. İtiraz üzerine icra mahkemesi ancak gecikme sebebinin mahiyetine ve
hadisenin özelliklerine göre takibin tatilini tensip edebilir.

İcra mahkemesi, tetkikatını evrak üzerinde yapar. Lüzumu halinde iki tarafı
hemen davetle mazeretin kabule şayan olup olmadığına karar verir. Duruşmaya
karar verilmemesi halinde borçludan alınan masraflar kendisine iade olunur.
Mazeretin kabulü halinde icra takibi durur. Aynı celsede alacaklı itirazın
kaldırılmasını sözlü olarak da istiyebilir. Bu takdirde tahkikata devam
olunarak gerekli karar verilir.

Daha önce borçlunun mallarına haciz konulmuşsa mazeretin kabulü kararının
tefhim veya tebliği tarihinden itibaren alacaklı yedi gün içinde, icra
mahkemesinden itirazın kaldırılmasını istemez veya aynı süre içinde 67 nci
maddeye göre mahkemeye başvurmazsa haciz kalkar.

Müddeti içinde yapılan itiraz takibi durdurur. İtiraz müddetinde değilse
alacaklının talebi üzerine icra memuru takip muamelelerine alacağın tamamı için
devam eder. Borçlu, borcun yalnız bir kısmına itirazda bulunmuşsa takibe, kabul
ettiği miktar için devam olunur.

Takip talebine itiraz edilen alacaklı, itirazın tebliği tarihinden itibaren bir
sene içinde mahkemeye başvurarak, genel hükümler dairesinde alacağının
varlığını ispat suretiyle itirazın iptalini dava edebilir.

Talebine itiraz edilen alacaklının takibi, imzası ikrar veya noterlikçe tasdik
edilen borç ikrarını içeren bir senede yahut resmî dairelerin veya yetkili
makamların yetkileri dahilinde ve usulüne göre verdikleri bir makbuz veya
belgeye müstenitse, alacaklı itirazın kendisine tebliği tarihinden itibaren
altı ay içinde itirazın kaldırılmasını isteyebilir. Bu süre içerisinde itirazın
kaldırılması istenilmediği takdirde yeniden ilâmsız takip yapılamaz.

=== İTİRAZIN İPTALİ DAVASI

İtiraz sonucunda duran takibe devam edebilmek için alacaklının başvurabileceği
yollardan biri *itirazın iptali* davasıdır. Bu dava genel mahkemede genel
hükümlere göre açılır.

[TIP]
====
İtirazın iptali davasının eda davasından farkı; eda davası sonunda alınan
hükme dayanılarak ilamlı icra takibi yapılabilir, ancak itirazın iptali
davasında verilen karara dayanarak sadece duran takibin devamı sağlanabilir.
Duran takibe devam edilmesi ilamlı takip değil, başlatılmış ilamsız takibin
devamıdır.

Davacı, davayı açarken itirazın iptali davasını doğru bir şekilde ifade etmeli
ve talep sonucunu doğru yazmalıdır. Neticede hakim talep ile bağlıdır, başka
bir şeye karar veremez. Başta eda davası olarak açılıp sonradan durmuş takibin
devamına karar verilmesi istenirse iddianın değiştirilmesi ve genişletilmesi
yasağı gündeme gelecektir.
====

İtirazın iptali davası genel hükümlere göre açılır ve incelenir. Alacaklı genel
hükümlere göre alacağını ispat yükü altındadır. Dava konusunun değerine göre
senetle ispat mecburiyeti vs. gündeme gelebilir.

İtirazın iptali davası itirazın tebliğ tarihinden itibaren *bir sene*
içerisinde açılmalıdır. Bu bir seneliik süre hak düşürücüdür. Bir senelik
sürenin geçmesi üzerine ancak genel mahkemelerde eda davası açılıp, alınacak
karar ile birlikte ilamlı icra takibi yapılabilir.

Bu davada borçlunun itirazının haksızlığına karar verilirse borçlu; takibinde
haksız ve kötü niyetli görülürse alacaklı; diğer tarafın talebi üzerine iki
tarafın durumuna, davanın ve hükmolunan şeyin tahammülüne göre, red veya
hükmolunan meblağın yüzde yirmisinden aşağı olmamak üzere, uygun bir tazminatla
mahkum edilir.

Alacaklının aleyhine tazminata hükmedilebilmesi için haksız ve kötü niyetli
olması aranırken, borçlunun tazminat ile sorumlu olması için haksız çıkması
yeterlidir.

NOTE: %20 tazminatın alacaklı veya borçlu aleyhine hükmedilebilmesi için talep
zorunludur. Talep olmadan mahkeme kendiliğinden böyle bir tazminata hükmedemez.

Borçlu aleyhine hükmedilen tazminata *inkar tazminatı*, alacaklı aleyhine
hükmedilen tazminata *kötüniyet tazminatı* denir.

TIP: Yargıtay'a göre borçlunun aleyhine inkar tazminatına hükmedilebilmesi için
itiraz ettiği borcun likit, yani kararlaştırılmış ve bilinen olması gerekir.
Eğer itiraz edilen borç, yargılamanın sonunda tespti gereken bir miktar ise
herhangi bir şekilde inkar tazminatına hükmedilemez.

IMPORTANT: İtirazın iptali davası ancak genel mahkemelerde açılabilir. İcra
mahkemesinde açılırsa görevsizlik kararı verilecektir.

İtirazın iptali davası sonunda verilen hüküm maddi anlamda kesin hüküm teşkil
eder. Alacaklı veya borçlubu davayo tekrar açamaz.

İtirazın iptali davası kabul edildiği takdirde borçlu, eğer daha önceden
bulunmamışsa, mahkeme kararının kendisine tefhim veya tebliğinden itibaren üç
gün içinde mal beyanında bulunmak zorundadır.

=== İTİRAZIN KESİN KALDIRILMASI

"_Talebine itiraz edilen alacaklının takibi, imzası ikrar veya noterlikçe
tasdik edilen borç ikrarını içeren bir senede yahut resmî dairelerin veya
yetkili makamların yetkileri dahilinde ve usulüne göre verdikleri bir makbuz
veya belgeye müstenitse, alacaklı itirazın kendisine tebliği tarihinden
itibaren altı ay içinde itirazın kaldırılmasını isteyebilir. Bu süre içerisinde
itirazın kaldırılması istenilmediği takdirde yeniden ilâmsız takip yapılamaz._"

Alacaklı aşağıdaki belgelerden birini göstermek şartıyla icra mahkemesinden
itirazın kesin olarak kaldırılmasını isteyebilir.

. *İmzası ikrar edilmiş senet*
. *İmzası noterlikçe onaylanmış senet*
. *Resmi dairelerin ve yetkili makamların yetkileri dahilinde usulüne uygun
verdikleri belgeler*

İtirazın kesin kaldırılması itirazdan itibaren altı ay içinde istenebilir.
İtirazın kesin kaldırılması talebi reddedilirse itirazdan itibaren bir yıl
içinde itirazın iptali davası açılabilir. Zira icra mahkemesinin verdiği karar
kesin değildir.

"_Borçlunun gösterdiği belge altındaki imza alacaklı tarafından inkar edilirse
hakim, 68/a maddesinde yazılı usule göre yaptığı inceleme neticesinde imzanın
alacaklıya ait olduğuna kanaat getirdiği takdirde alacaklının itirazın
kaldırılması talebini reddeder ve alacaklıyı sözü edilen belgenin taalluk
ettiği değer veya miktarın yüzde onu oranında para cezasına mahkum eder.
Alacaklı genel mahkemede dava açarsa bu para cezasının infazı dava sonuna kadar
tehir olunur ve alacaklı bu davada alacağını ve imzanın kendisine ait
olmadığını ispat ederse bu ceza kalkar._"

"_Tatbika medar imza mevcutsa bununla, yoksa borçluya yazdıracağı yazı ve
attıracağı imza ile yapılacak mükayese ve incelemelerden veya diğer delil ve
karinelerden icra mahkemesi, reddedilen imzanın borçluya aidiyetine kanaat
getirirse itirazın muvakkaten kaldırılmasına karar verir. Hakim lüzum görürse,
oturumun bir defadan fazla talikine meydan vermiyecek surette, bilirkişi
incelemesi de yaptırabilir._" (İİK 68/a fıkra 3)

CAUTION: İnkar tazminatı alacaklıya ödenirken para cezası devlete ödenir.

Alacaklı duruşmada bizzat bulunmayıp da imza vekili tarafından reddolunduğu
takdirde vekil mütaakıp oturumda müvekkilini imza tatbikatı için hazır
bulundurmaya veya masraflarını vererek davetiye tebliğ ettirmeye mecburdur.
Kabule değer mazereti olmadan gelmiyen alacaklı borçlunun dayandığı belgede
yazılı miktar hakkındaki itirazın kaldırılması talebinden vazgeçmiş sayılır.

İtirazın kaldırılması talebinin esasa ilişkin nedenlerle kabulü hâlinde borçlu,
talebin aynı nedenlerle reddi hâlinde ise alacaklı, diğer tarafın talebi
üzerine yüzde yirmiden aşağı olmamak üzere tazminata mahkûm edilir. Borçlu,
menfi tespit ve istirdat davası açarsa, yahut alacaklı genel mahkemede dava
açarsa, hükmolunan tazminatın tahsili dava sonuna kadar tehir olunur ve dava
lehine sonuçlanan taraf için, daha önce hükmedilmiş olan tazminat kalkar.

=== İTİRAZIN GEÇİCİ KALDIRILMASI

Takibin dayandığı senet hususî olup, imza itiraz sırasında borçlu tarafından
reddedilmişse, alacaklı itirazın kendisine tebliği tarihinden itibaren altı ay
içinde itirazın geçici olarak kaldırılmasını isteyebilir.

IMPORTANT: Alacaklının takip talebinde dayandığı senet, imzası noter tarafından
onaylı bir senet ise buradaki imza inkar edilemez, ancak sahtelik davası
açılabilir. İtirazın geçici kaldırılması ancak adi senet için söz konusu olur.

Senet altındaki imzayı reddeden borçlu takibi yapan icra dairesinin yetki
çevresi içinde ise, itirazın kaldırılması için icra mahkemesi önünde yapılacak
duruşmada, mazeretini daha önce bildirip tevsik etmediği takdirde, bizzat
bulunmaya mecburdur. İcra dairesinin yetki çevresi dışında ödeme emri tebliğ
edilen borçlu, istinabe yolu ile isticvabına karar verilmesi halinde, aynı
mecburiyete tabidir.

Tatbika medar imza mevcutsa bununla, yoksa borçluya yazdıracağı yazı ve
attıracağı imza ile yapılacak mükayese ve incelemelerden veya diğer delil ve
karinelerden icra mahkemesi, reddedilen imzanın borçluya aidiyetine kanaat
getirirse itirazın muvakkaten kaldırılmasına karar verir. Hakim lüzum görürse,
oturumun bir defadan fazla talikine meydan vermiyecek surette, bilirkişi
incelemesi de yaptırabilir.

Yapılacak duruşmada, borçlunun hazır bulunmaması halinde icra mahkemesince
başka bir cihet tetkik edilmeksizin itirazın muvakkaten kaldırılmasına ve
borçlunun sözü edilen senede dayanan takip konusu alacağın yüzde onu oranında
para cezasına mahkumiyetine karar verilir. Duruşmaya gelmeyen borçlunun
itirazının muvakkaten kaldırılmasına ve hakkında para cezasına karar
verilebilmesi için keyfiyetin davetiyeye yazılması şarttır.

İcra hakimi, imzanın borçluya aidiyetine karar verdiği takdirde borçluyu sözü
edilen senede dayanan takip konusuna alacağın yüzde onu oranında para cezasına
mahkum eder. Borçlu, borçtan kurtulma, menfi tespit veya istirdat davası
açarsa, bu para cezasının infazı dava sonuna kadar tehir olunur ve borçlu
açtığı davayı kazanırsa bu ceza kalkar.

Borçlu inkar ettiği imzayı, itirazın kaldırılması duruşmasında ve en geç
alacaklının senedin aslını ibraz ettiği celsede kabul ederse, hakkında para
cezası hükmolunmaz ve kendisine yargılama giderleri yükletilmez. Şu kadar ki,
kötü niyetle takibe sebebiyet ver en borçlu yargılama giderleri ile mülzem
olur. Senedin aslı takip talebi anında icra dairesine tevdi edilmiş ise, icra
dairesinin yetki çevresi içinde ödeme emri tebliğ edilen borçlu hakkında bu
fıkra hükmü uygulanmaz.

İtirazın muvakkaten kaldırılması talebinin kabulü halinde borçlu, bu talebin
reddi halinde ise alacaklı, diğer tarafın talebi üzerine yüzde yirmiden aşağı
olmamak üzere tazminata mahkum edilir. Borçlu, borçtan kurtulma, menfi tespit
veya istirdat davası açarsa, yahut alacaklı genel mahkemede dava açarsa
hükmolunan tazminatın tahsili dava sonuna kadar tehir olunur ve dava lehine
sonuçlanan taraf için, daha önce hükmedilmiş olan tazminat kalkar.

İtirazın muvakkaten kaldırılmasına karar verilir ve ödeme emrindeki müddet
geçmiş bulunursa alacaklının talebi ile borçlunun malları üzerine muvakkat
haciz konur.

== BORÇLUNUN AÇABİLECEĞİ DAVALAR

=== BORÇTAN KURTULMA DAVASI

İtirazın muvakkaten kaldırılması kararının tefhim veya tebliğinden itibaren
yedi gün içinde borçlu, takibin yapıldığı mahal veya alacaklının yerleşim yeri
mahkemesinde borçtan kurtulma davası açabilir. Bu davanın dinlenebilmesi için
borçlunun dava konusu alacağın yüzde 15 ini ilk duruşma gününe kadar mahkeme
veznesine nakden depo etmesi veya mahkemece kabul edilecek aynı değerde esham
ve tahvilat veya banka teminat mektubu tevdi etmesi şarttır. Aksi takdirde dava
reddolunur.

NOTE: Borçtan kurtulma davasının özel dava şartı dava konusu alacağın %15'i
oranında teminat yatırılmasıdır. %15'lik teminat yatırılmadığı takdirde bu dava
yalnızca menfi tespit davasıdır.

NOTE: Borçlu menfi tespit davasını önceden açmış ise, itirazın geçici kaldırılması
kararından sonra bu davayı %15 teminat yatırmak suretiyle borçtan kurtulma
davasına dönüştürebilir.

Borçlu yukarda yazılı müddet içinde dava etmez veya davası reddolunursa
itirazın kaldırılması kararı ve varsa muvakkat haciz kesinleşir.

Davanın reddi hakkındaki karara karşı istinaf yoluna başvuran borçlu, ayrıca 36
ncı madde hükümlerini yerine getirmek şartiyle, icra dairesinden mühlet
istiyebilir.

Borçtan kurtulma davasında haksız çıkan taraf, dava veya hükmolunan şeyin yüzde
yirmisinden aşağı olmamak üzere münasip bir tazminatla mahkum edilir.

=== MENFİ TESPİT DAVASI

Borçlu, icra takibinden önce veya takip sırasında borçlu bulunmadığını ispat
için menfi tesbit davası açabilir.

TIP: Tespit davalarının eda davalarından en önemli farkı; eda davalarında
hukuki yararın ayrıca ispatı gerekli değilken, tespit davalarında davacının
davayı açmaktan hukuki yararı olduğunu ispat etmesinin gerekmesidir.

İcra takibinden önce açılan menfi tesbit davasına bakan mahkeme, talep üzerine
alacağın yüzde onbeşinden aşağı olmamak üzere gösterilecek teminat mukabilinde,
icra takibinin durdurulması hakkında ihtiyati tedbir kararı verebilir.

İcra takibinden sonra açılan menfi tesbit davasında ihtiyati tedbir yolu ile
takibin durdurulmasına karar verilemez.  Ancak, borçlu gecikmeden doğan
zararları karşılamak ve alacağın yüzde onbeşinden aşağı olmamak üzere
göstereceği teminat karşılığında, mahkemeden ihtiyati tedbir yoluyle icra
veznesindeki paranın alacaklıya verilmemesini istiyebilir.

TIP: Kanunda takipten sonra açılan menfi tespit davasının takibi durdurmayacağı
söyleniyorsa da Yargıtay, borçlunun borcun tamamını ve ek olarak %15'ini
teminat göstermesi halinde takibin durdurulacağını içtihat etmiştir. Böylece
borçlu dava konusu alacağın %115'ini teminat göstermek suretiyle takibi
durdurabilir.

Dava alacaklı lehine neticelenirse ihtiyati tedbir kararı kalkar. Buna dair
hükmün kesinleşmesi halinde alacaklı ihtiyati tedbir dolayısıyla alacağını geç
almış bulunmaktan doğan zararlarını gösterilen teminattan alır. Alacaklının
uğradığı zarar aynı davada takdir olunarak karara bağlanır. Bu zarar herhalde
yüzde yirmiden aşağı tayin edilemez.

Dava borçlu lehine hükme bağlanırsa derhal takip durur. İlamın kesinleşmesi
üzerine münderecatına göre ve ayrıca hükme hacet kalmadan icra kısmen veya
tamamen eski hale iade edilir. Borçluyu menfi tespit davası açmaya zorlayan
takibin haksız ve kötü niyetli olduğu anlaşılırşa, talebi üzerine, borçlunun
dava sebebi ile uğradığı zararın da alacaklıdan tahsiline karar verilir. Takdir
edilecek zarar, haksızlığı anlaşılan takip konusu alacağın yüzde yirmisinden
aşağı olamaz.

=== İSTİRDAT DAVASI

Borçlu, menfi tesbit davası zımmında tedbir kararı almamış ve borç da ödenmiş
olursa, davaya istirdat davası olarak devam edilir.

Takibe itiraz etmemiş veya itirazının kaldırılmış olması yüzünden borçlu
olmadığı bir parayı tamamen ödemek mecburiyetinde kalan şahıs, ödediği tarihten
itibaren bir sene içinde, umumi hükümler dairesinde mahkemeye başvurarak
paranın geriye alınmasını istiyebilir.

İstirdat davasının şartları:

. *Borç olmayan paranın ödenmiş olması*
. *Paranın icra takibi sırasında ödenmiş olması*
. *Paranın cebri icra tehdidi altında ödenmiş olması*
. *Davanın borcun ödenmesinden itibaren bir sene içinde açılmış olması*

TIP: Bir yıllık süre geçirilirse bile genel hükümlere göre borcun ödenmesinden
itibaren 2 yıl içinde sebepsiz zenginleşme davası açılabilir.

Dava kesin hüküm teşkil eder ama dava sonunda inkar tazminatına hükmedilmez.
İstirdat davasının sonunda tazminata hükmedilmesi söz konusu değildir. Ancak
menfi tespit davası açılmış, bu davada tedbir kararı alınmıl ve bu davanın
sonunda istirdat davası kazanılmış ise borçlu lehine tazminata karar
verilecektir.

Menfi tesbit ve istirdat davaları, takibi yapan icra dairesinin bulunduğu yer
mahkemesinde açılabileceği gibi, davalının yerleşim yeri mahkemesinde de
açılabilir.

Davacı istirdat davasında yalnız paranın verilmesi lazım gelmediğini ispata
mecburdur.

== İCRA TAKİBİNİN İPTALİ VE ERTELENMESİ

=== İTFA

Borçlu takibin kesinleşmesinden sonraki evrede borcu ve ferilerini alacaklıya
öder ve ödediğini noterden tasdikli veya imzası ikrar edilmiş bir belge ile
ispat ederse takibin iptalini icra mahkemesinden her zaman isteyebilir.

Takibin iptali, icra takibinin yapıldığı yerdeki icra mahkemesinden istenir.
Takibin kesinleşmesinden paraların paylaştırılmasına kadar takibin iptali
istenebilir.

=== SÜRE VERİLMESİ

Takibe konu alacağın ödenmesi için alacaklı borçluya süre verebilir. Süre
verilmesi durumunda takibin ertelenmesi için üç şart aranacaktır:

. *Alacaklı tarafından borçluya, borcu ifa için süre verilmiş olmalıdır.*
. *Süre takibin kesinleşmesinden sonra verilmiş olmalıdır.*
. *Borçluya süre verildiği, alacaklı tarafından verilen ve imzası noterlikçe
onaylı veya imzası alacaklı tarafından ikrar edilmiş senetle ispat
edilmelidir.*

Taraflar erteleme konusunda uzlaştıktan sonra alacaklı takibe devam etmeye
kalkışırsa borçlu takibin ertelendiğini ve takibe devam edilmemesi gerektiğini
ileri sürerek icra mahkemesinde dava açabilir.

=== ZAMANAŞIMI

İcra takibinin kesinleşmesinden sonra alacağın zamanaşımına uğraması halinde
borçlu her zaman icra mahkemesine başvurarak takibin geri bırakılmasını
isteyebilir.

Takibin kesinleşmesinden sonra alacağın zamanaşımına uğradığı itirazı süreye
tabi değildir. Buna karşılık zamanaşımı takibin kesinleşmesinden önce dolmuşsa,
zamanaşımı itirazı ödeme emrine itiraz süresi içinde ileri sürülmelidir.

Borçlunun alacağın zamanaşımına uğradığını ispat için özel bir belge sunmasına
gerek yoktur. Hakim dosya üzerinden gerekli incelemeyi yapacaktır. Her takip
işlemi zamanaşımını kestiğinden yapılan son takip işleminin tarihine
bakacaktır.

Eğer alacaklı zamanaşımının durduğunu veya kesildiğini iddia ediyorsa, bunu
ancak resmi belgelerle veya imzası borçlu tarafından ikrar edilen belge ile
ispat edilebilir.

Borçlunun takibin kesinleşmesinden sonra zamanaşımı itirazını ileri sürmesi
halinde İİK 33/a hükmü uygulanır.

"_İlamın zamanaşımına uğradığı veya zamanaşımının kesildiği veya tatile
uğradığı iddiaları icra mahkemesi tarafından resmi vesikalara müsteniden
incelenerek icranın geri bırakılmasına veya devamına karar verilir._

_Alacaklı, icranın geri bırakılması kararının kesinleştiğinin kendisine
tebliğinden sonra, zamanaşımının vakı olmadığını ispat sadedinde ve 7 gün
içinde umumi mahkemelerde dava açabilir. Aksi takdirde icrası istenen ilamın
zamanaşımına uğradığı hususu kesin hüküm teşkil eder._

_İcranın devamına karar verilmesi halinde 33 üncü maddenin son fıkrası burada da
uygulanır._" (İİK 33/a)

"_Borçlu olmadığı parayı ödemek mecburiyetinde kalan borçlunun 72 nci madde
mucibince istirdat davası açarak paranın geriye verilmesini istemek hakkı
saklıdır._" (İİK 33/son)

== MAL BEYANI

*Mal beyanı*, borçlunun gerek kendisinde ve gerek üçüncü şahıslar yedinde
bulunan mal ve alacak ve haklarında borcuna yetecek miktarın nevi ve mahiyet ve
vasıflarını ve her türlü kazanç ve gelirlerini ve yaşayış tarzına göre geçim
membalarını ve buna nazaran borcunu ne suretle ödeyebileceğini yazı ile veya
şifahen icra dairesine bildirmesidir

Borçlu ödeme emrine 7 gün içerisinde itiraz etmediği takdirde mal beyanında
bulunmak zorundadır. Eğer mal beyanında bulunmazsa hapisle tazyik edileceği
ihtar edilir.

İtirazının iptaline veya kat'i veya muvakkat surette kaldırılmasına karar
verilen borçlu, bu kararın kendisine tebliğinden itibaren üç gün içinde
yukarıdaki maddede gösterildiği üzere beyanda bulunmaya mecburdur.

Mal beyanında bulunmıyan borçlu, alacaklının talebi üzerine beyanda bulununcaya
kadar icra mahkemesi hakimi tarafından bir defaya mahsus olmak üzere hapisle
tazyik olunur. Ancak bu hapis üç ayı geçemez.

İcra dairesine vakı olan beyanda malı olmadığını bildirmiş veya borcuna yetecek
mal göstermemiş yahut beyandan imtina etmiş olan borçlu sonradan kazandığı
malları ve kazancında ve gelirinde vukua gelen tezayütleri yedi gün içinde
mezkür daireye taahhütlü mektupla veya şifahi olarak bildirmeğe mecburdur.

"_Bu Kanuna göre istenen beyanı, hakikate aykırı surette yapan kimse,
alacaklının şikâyeti üzerine, üç aydan bir yıla kadar hapis cezası ile
cezalandırılır._

_Hakkında aciz vesikası alınmış borçlu, asgari ücretin üstünde bir geçim
sürdürdüğü, aciz vesikası hamili alacaklının alacağının aciz vesikasına
bağlanmasından en geç beş sene içinde müracaatı üzerine sabit olursa, asgari
ücretin üstünde kalan gelirlerinden icra mahkemesinin dörtte birden az olmamak
üzere tespit edeceği kısmını icra mahkemesi kararının kesinleşmesinden itibaren
en geç bir ay içinde ve aciz vesikasındaki borcun ödenmesine kadar her ay icra
dairesine yatırmaya mecburdur. Bu mükellefiyeti yerine getirmeyen borçlu
hakkında bir yıla kadar tazyik hapsine karar verilir. Hapsin tatbikine
başlandıktan sonra borçlu borcun tamamını veya o tarihe kadar icra veznesine
yatırmak zorunda olduğu meblağı öderse tahliye edilir; ödemelerini tekrar
keserse, hakkında tazyik hapsine yeniden karar verilir. Ancak, bir borçtan
dolayı tazyik hapsinin süresi bir yılı geçemez._"

== HACİZ

Ödeme emrindeki müddet geçtikten ve borçlu itiraz etmiş ise itirazı
kaldırıldıktan sonra mal beyanını beklemeksizin alacaklı haciz konmasını
isteyebilir.

Haciz istemek hakkı, ödeme emrinin tebliği tarihinden itibaren bir sene
geçmekle düşer. İtiraz veya dava halinde bunların vukuundan hükmün
katileşmesine kadar veya alacaklıyla borçlunun icra dairesinde taksit
sözleşmeleri yapmaları halinde taksit sözleşmesinin ihlaline kadar geçen zaman
hesaba katılmaz.

Haciz talebi kanuni müddet içinde yapılmaz veya geri alındıktan sonra bu müddet
içinde yenilenmezse dosya muameleden kaldırılır. Yeniden haciz istemek,
alacaklı tarafından vukubulan yenileme talebinin borçluya tebliğine
mütevakkıftır. İlama müstenit olmayan takiplerde yenileme talebi üzerine
yeniden harc alınır. Yenileme masraf ve harcları borçluya tahmil edilmez.

İcra dairesi talepten nihayet üç gün içinde haczi yapar.

Haczolunacak mallar başka yerde ise haciz yapılmasını malların bulunduğu yerin
icra dairesine hemen yazar. Bu halde hacizle ilgili şikayetler, istinabe olunan
icra dairesinin tabi bulunduğu icra mahkemesince çözümlenir. Resmî sicile
kayıtlı malların haczi, takibin yapıldığı icra dairesince, kaydına işletilmek
suretiyle doğrudan da yapılabilir.

Borçlu haciz sırasında malın bulunduğu yerde bulunmaz ve hemen bulundurulması
mümkün olmazsa haciz, gıyabında yapılır.

Talep vukuunda borçlu kilitli yerleri ve dolapları açmağa vesair eşyayı
göstermeğe mecburdur. Bu yerler icabında zorla açtırılır.

Haczi yapan memur, borçlunun üzerinde para, kıymetli evrak, altın veya gümüş
veya diğer kıymetli şeyleri sakladığını anlar ve borçlu bunları vermekten
kaçınırsa, borçlunun şahsına karşı kuvvet istimal edilebilir.

Taşınır bir malı haciz için mahallinde bir tutanak tutulur. Tutanakta alacaklı
ve borçlunun isim ve şöhretleri, alacağın miktarı, haczin hangi gün ve saatte
yapıldığı, haczedilen mallar ve takdir edilen kıymetleri ve varsa üçüncü
şahısların iddiaları yazılır ve haczi icra eden memur tarafından imza edilir.

Haczi kabil mallar kafi gelmezse veya hiç bulunmazsa bu hal tutanağa
kaydolunur. Haczi kabil mal bulunmazsa haciz tutanağı 143 üncü maddedeki aciz
vesikası hükmündedir.  İcraca takdir edilen kıymete göre haczi kabil malların
kifayetsizliği anlaşıldığı surette dahi tutanak muvakkat aciz vesikası yerine
geçerek alacaklıya 277 nci maddede yazılı hakları verir.

Tutanak tutulurken alacaklı, borçlu veya namlarına Tebligat Kanunu hükümlerine
göre tebellüğe yetkili kimse bulunmazsa, bulunmayan alacaklı veya borçlu üç gün
içinde tutanağı tetkik ve diyeceği varsa söylemesi için icra dairesine davet
olunur. Kanunen ilavesi gereken müddetler mahfuzdur. Haciz sırasında borçlu
veya alacaklı adına Tebligat Kanunu hükümlerine göre tebellüğe yetkili kimse
bulunduğu takdirde haciz tutanağının bir örneği bulunan şahsa verilir. Borçluya
veya alacaklıya ayrıca haber verilmez.

NOTE: Hacizden sonra icra memuru haczedilen malların satışını kendiliğinden
yapamaz. Satış için alcaklının taleptu bulunması gerekir.

=== HACİZ TÜRLERİ

* *Geçici haciz:* İtirazın geçici kaldırılmasından sonra yapılan hacizdir.
* *İhtiyati haciz:* Daha takip başlamadan, dava açılmadan önce borçlunun
malvarlığını elden çıkarmasını önlemek amacıyla yapılan hacizdir.
* *Kesin haciz*

** *Tamamlama haczi:* Satış tutarı bütün alacakları ödemiye yetmezse icra
memuru kendiliğinden yeni hacizler yaparak haczi tamamlar; ancak bu suretle
haczolunan mallar üzerinde sonra gelen derecelerin evvelce koydurdukları
hacizler varsa bu hacizlerin doğurduğu haklara halel gelmez. Yeniden haczedilen
mallar ayrıca satış talebine hacet kalmaksızın ve mümkün olduğu kadar çabuk
satılır.
** *İlave haciz:* İştirak halinde icra dairesi müracaat üzerine aynı derecedeki
alacaklıların bütün alacaklarına yetecek nispette ilave suretiyle hacizler
yapar.

=== HACZEDİLEMEYEN MAL VE HAKLAR

Aşağıdaki şeyler haczolunamaz:

. Devlet malları ile mahsus kanunlarında haczi caiz olmadığı gösterilen mallar,
. Ekonomik faaliyeti, sermayesinden ziyade bedenî çalışmasına dayanan borçlunun
mesleğini sürdürebilmesi için gerekli olan her türlü eşya,
. Para, kıymetli evrak, altın, gümüş, değerli taş, antika veya süs eşyası gibi
kıymetli şeyler hariç olmak üzere, borçlu ve aynı çatı altında yaşayan aile
bireyleri için lüzumlu eşya; aynı amaçla kullanılan eşyanın birden fazla olması
durumunda bunlardan biri,
. Borçlu çiftçi ise kendisinin ve ailesinin geçimi için zaruri olan arazi ve
çift hayvanları ve nakil vasıtaları ve diğer eklenti ve ziraat aletleri;
değilse, sanat ve mesleki için lüzumlu olan alat ve edevat ve kitapları ve
arabacı, kayıkçı, hamal gibi küçük nakliye erbabının geçimlerini temin eden
nakil vasıtaları,
. Borçlu ve ailesinin idareleri için lüzumlu ise borçlunun tercih edeceği bir
süt veren mandası veya ineği veyahut üç keçi veya koyunu ve bunların üç aylık
yem ve yataklıkları,
. Borçlunun ve ailesinin iki aylık yiyecek ve yakacakları ve borçlu çiftçi ise
gelecek mahsül için lazım olan tohumluğu,
. Borçlu bağ, bahçe veya meyva veya sebze yetiştiricisi ise kendisinin ve
ailesinin geçimi için zaruri olan bağ bahçe ve bu sanat için lüzumlu bulunan
alat ve edevat,
+
Geçimi hayvan yetiştirmeye münhasır olan borçlunun kendisi ve ailesinin
maişetleri için zaruri olan miktarı ve bu hayvanların üç aylık yem ve
yataklıkları,
. Borçlar Kanununun 510 uncu maddesi mucibince haczolunmamak üzere tesis
edilmiş olan kaydı hayatla iratlar,
. Memleketin ordu ve zabıta hizmetlerinde malül olanlara bağlanan emeklilik
maaşları ile bu hizmetlerden birinin ifası sebebiyle ailelerine bağlanan
maaşlar ve ordunun hava ve denizaltı mensuplarına verilen uçuş ve dalış
tazminat ve ikramiyeleri,
+
Askeri malüllerle, şehit yetimlerine verilen terfi zammı ve 1485 numaralı kanun
hükmüne göre verilen inhisar beyiye hisseleri,
. Bir muavenet sandığı veya cemiyeti tarafından hastalık, zaruret ve ölüm
gibi hallerde bağlanan maaşlar, ı11. Vücut veya sıhhat üzerine ika edilen
zararlar için tazminat olarak mutazarrırın kendisine veya ailesine toptan veya
irat şeklinde verilen veya verilmesi lazım gelen paralar,
. Borçlunun haline münasip evi,
+
NOTE: Borçlunun haline münasip evi, oturmakta olduğu evdir. Borçlu yalı
dairesinde oturuyorsa tek evi bu olsa bile bu hayatına devam ettirmek için
gerekenin çok üstünde olduğu için o evin satılıp, ev alınacak bir miktar
paranın borçluya verilmesi gerekir.
. Öğrenci bursları.

Medeni Kanunun 807 nci maddesi hükmü saklıdır. 2, 3, 4, 5, 7 ve 12 numaralı
bendlerdeki istisna, borcun bu eşya bedelinden doğmaması haline munhasırdır.

(2), (4), (7) ve (12) numaralı bentlerde sayılan malların kıymetinin fazla
olması durumunda, bedelinden haline münasip bir kısmı, ihtiyacını
karşılayabilmesi amacıyla borçluya bırakılmak üzere haczedilerek satılır.

İcra memuru, haczi talep edilen mal veya hakların haczinin caiz olup olmadığını
değerlendirir ve talebin kabulüne veya reddine karar verir.

Maaşlar, tahsisat ve her nevi ücretler, intifa hakları ve hasılatı, ilama
müstenit olmayan nafakalar, tekaüt maaşları, sigortalar veya tekaüt sandıkları
tarafından tahsis edilen iratlar, borçlu ve ailesinin geçinmeleri için icra
memurunca lüzumlu olarak takdir edilen miktar tenzil edildikten sonra
haczolunabilir. Ancak haczolunacak miktar bunların dörtte birinden az olamaz.
Birden fazla haciz var ise sıraya konur. Sırada önde olan haczin kesintisi
bitmedikçe sonraki haciz için kesintiye geçilemez.

Yukarıda yazılı mal ve hakların haczolunabileceğine dair önceden yapılan
anlaşmalar muteber değildir.

NOTE: Haczedilmezliklere ilişkin şikayet Yargıtay'a göre süresizdir.

=== HACİZDE TERTİP

Haciz yapılırken belirli bir sıraya uyulması gerekir. Buna *hacizde tertip*
denir.

Haczi koyan memur borçlu ile alacaklının menfaatlerini mümkün olduğu kadar
telif etmekle mükelleftir.

Borçlunun kendi yedinde veya üçüncü şahısta olan taşınır mallariyle
taşınmazlarından ve alacak ve haklarından alacaklının ana, faiz ve masraflar da
dahil olmak üzere bütün alacaklarına yetecek miktarı haczolunur.

Borçlu yahut borçlu ile birlikte malı elinde bulunduran şahıslar, taşınır mal
üzerinde üçüncü bir şahsın mülkiyet veya rehin hakkı gibi sınırlı bir ayni
hakkının bulunması veya taşınır malın üçüncü şahıs tarafından haczedilmiş
olması halinde bu hususu haciz yapan memura beyan etmek ve beyanının haciz
tutanağına geçerilmesini talep etmek, haczi yapan memur da borçluyu yahut
borçlu ile birlikte malı elinde bulunduran şahısları bu beyana davet etmek
zorundadır. Bu tür mallar ile üçüncü şahıs tarafından ihtiyaten haciz veya
istihkak iddia edilmiş bulunan malların haczi en sonraya bırakılır.

. *Öncelikle çekişmesiz mallar haczedilir.*

.. _Öncelikle muhafaza ve satılması en kolay ve yokluğu borçlu için en az yük
teşkil edecek taşınır mallar haczedilir._
.. _Daha sonra taşınmazlar haczedilir._

. *Çekişmesiz mallardan sonra, alacaklının alacağına yetecek kadar haciz
yapılamışsa çekişmeli mallar haczedilir.* Çekişmeli mallar haczedilirken bu
durum haciz tutanağına yazılır.

=== TAŞINIRLARIN HACZİ

Haczolunan paraları, banknotları, hamiline ait senetleri, poliçeler ve sair
cirosu kabil senetler ile altın, gümüş ve diğer kıymetli şeyleri icra dairesi
muhafaza eder.

Diğer taşınır mallar, masrafı peşinen alacaklıdan alınarak muhafaza altına
alınır. Alacaklı muvafakat ederse, istenildiği zaman verilmek şartıyla,
muvakkaten borçlu yedinde veya üçüncü şahıs nezdinde bırakılabilir. Üçüncü
şahsın elinde bulunan taşınır mallar haczedildiğinde, üçüncü şahsın kabulü
hâlinde üçüncü şahsa yediemin olarak bırakılır. Mallar satış mahalline
getirilmediği takdirde muhafaza altına alınabilir veya yediemin değişikliği
yapılabilir.

Türkiye’nin taraf olduğu uluslararası andlaşma hükümleri saklı kalmak kaydıyla,
yabancı devlet başkanı, parlamento başkanı, hükümet başkanı veya hükümet
üyelerini taşıyan ulaşım araçları, bu kişiler Türkiye’de bulundukları sürece,
muhafaza altına alınamaz ve yediemine bırakılamaz.

İcra dairesi üçüncü bir şahsa rehnedilmiş olan malları da muhafaza altına
alabilir. Ticari işletme rehni kapsamındaki taşınırlar ise icra dairesince
satılmalarına karar verilmesinden sonra muhafaza altına alınabilir. Bu mallar
paraya çevrilmediği takdirde geri verilir.

=== ANONİM ŞİRKET PAYININ HACZİ

Anonim şirketlerde paylar için pay senedi veya pay ilmühaberi çıkarılmamışsa,
borçlunun şirketteki payı icra dairesi tarafından şirkete tebliğ olunarak
haczedilir. Bu haczin şirket pay defterine işlenmesi zorunludur; ancak haciz,
şirket pay defterine işlenmemiş olsa bile şirkete tebliğ tarihinde yapılmış
sayılır. Haciz, icra dairesi tarafından tescil edilmek üzere Ticaret Siciline
bildirilir. Bu durumda haczedilen payların devri, alacaklının haklarını ihlâl
ettiği oranda batıldır. Haczedilen payların satışı, taşınır malların satışı
usulüne tâbidir.

=== HAKLARIN HACZİ

Bir intıfa hakkı veya taksim edilmemiş bir miras veya bir şirket yahut iştirak
halinde tasarruf edilen bir mal hissesi haczedilirse icra dairesi, yerleşim
yerleri bilinen ilgili üçüncü şahıslara keyfiyeti ihbar eder. Bu suretle
borçlunun muayyen bir taşınmazdaki tasfiye sonundaki hissesi haczedilmiş olursa
icra memuru haciz şerhinin taşınmazın kaydına işlenmesi için tapu sicil
muhafızlığına tebligat yapar.

Borçlunun reddetmediği miras veya başka bir sebeple iktisap eyleyip henüz
tapuya veya gemi siciline tescil ettirmediği mülkiyet veya diğer aynı hakların
borçlu namına tescili alacaklı tarafından istenebilir. Bu talep üzerine icra
dairesi alacaklının bu muameleyi takip edebileceğini tapu veya gemi sicili
dairesine ve icabında mahkemeye bildirir.

Borçlunun zilyed bulunduğu bir taşınmaz üzerindeki fevkalade zamanaşımı ile
iktisabını istemek hakkının haczedilmesi halinde, icra dairesi zilyedliğin
başkasına devrine mani olacak tedbirleri alır ve alacaklıya bir ay içinde
taşınmazın borçlusu adına tescili için dava açması yetkisini verir. Mahkemenin
tescil kararı ile taşınmaz bu alacaklı lehine mahcuz sayılır.

Alacaklının bu sebeple yapacağı kanuni masraflar ayrıca takip ve hükme hacet
kalmaksızın dairece borçludan tahsil olunur.

=== BORÇLUNUN ÜÇÜNCÜ KİŞİLERDEKİ MAL VE ALACAKLARININ HACZİ

Hamiline ait olmıyan veya cirosu kabil bir senetle müstenit bulunmıyan alacak
veya sair bir talep hakkı veya borçlunun üçüncü şahıs elindeki taşınır bir malı
haczedilirse icra memuru; borçlu olan hakiki veya hükmi şahsa bundan böyle
borcunu ancak icra dairesine ödiyebileceğini ve takip borçlusuna yapılan
ödemenin muteber olmadığını veya malı elinde bulunduran üçüncü şahsa bundan
böyle taşınır malı ancak icra dairesine teslim edebileceğini, malı takip
borçlusuna vermemesini, aksi takdirde malın bedelini icra dairesine ödemek
zorunda kalacağını bildirir (Haciz ihbarnamesi).Bu haciz ihbarnamesinde, ayrıca
2, 3 ve 4 üncü fıkra hükümleri de üçüncü şahsa bildirilir.

Üçüncü şahıs; borcu olmadığı veya malın yedinde bulunmadığı veya haciz
ihbarnamesinin tebliğinden önce borç ödenmiş veya mal istihlak edilmiş veya
kusuru olmaksızın telef olmuş veya malın borçluya ait olmadığı veya malın
kendisine rehnedilmiş olduğu veya alacak borçluya veya emrettiği yere verilmiş
olduğu gibi bir iddiada ise, keyfiyeti, haciz ihbarnamesinin kendisine
tebliğinden itibaren yedi gün içinde icra dairesine yazılı veya sözlü olarak
bildirmeye mecburdur.

Üçüncü şahıs, haciz ihbarnamesinin kendisine tebliğinden itibaren yedi gün
içinde itiraz etmezse, mal yedinde veya borç zimmetinde sayılır ve kendisine
gönderilen haciz ihbarnamesine süresinde itiraz etmediği, bu nedenle de malın
yedinde veya borcun zimmetinde sayıldığı ikinci bir ihbarname ile bildirilir.
Bu ikinci ihbarnamede ayrıca, üçüncü şahsın ihbarnamenin kendisine tebliğinden
itibaren yedi gün içinde yukarıda belirtilen sebeplerle itirazda bulunması,
itirazda bulunmadığı takdirde zimmetinde sayılan borcu icra dairesine ödemesi
veya yedinde sayılan malı icra dairesine teslim etmesi istenir.

İkinci ihbarnameye süresi içinde itiraz etmeyen ve zimmetinde sayılan borcu
icra dairesine ödemeyen veya yedinde sayılan malı icra dairesine teslim etmeyen
üçüncü şahsa onbeş gün içinde parayı icra dairesine ödemesi veya yedinde
sayılan malı teslim etmesi yahut bu süre içinde menfi tespit davası açması,
aksi takdirde zimmetinde sayılan borcu ödemeye veya yedinde sayılan malı
teslime zorlanacağı bildirilir.

Bu bildirimi alan üçüncü şahıs, icra takibinin yapıldığı veya yerleşim yerinin
bulunduğu yer mahkemesinde süresi içinde menfi tespit davası açtığına dair
belgeyi bildirimin yapıldığı tarihten itibaren yirmi gün içinde ilgili icra
dairesine teslim ettiği takdirde, hakkında yürütülen cebri icra işlemleri menfi
tespit davası sonunda verilen kararın kesinleşmesine kadar durur. Bu süre
içinde 106 ncı maddede belirtilen süreler işlemez. Bu davada üçüncü şahıs,
takip borçlusuna borçlu olmadığını veya malın takip borçlusuna ait olmadığını
ispat etmeye mecburdur.

Üçüncü şahıs açtığı bu davayı kaybederse, mahkemece, dava konusu şeyin yüzde
yirmisinden aşağı olmamak üzere bir tazminata mahkûm edilir.

Üçüncü şahıs, haciz ihbarnamesine müddeti içinde itiraz ederse, alacaklı,
üçüncü şahsın verdiği cevabın aksini icra mahkemesinde ispat ederek üçüncü
şahsın 338 inci maddenin 1 inci fıkrası hükmüne göre cezalandırılmasını ve
ayrıca tazminata mahküm edilmesini istiyebilir. İcra mahkemesi, tazminat
hakkındaki davayı genel hükümlere göre halleder.

Üçüncü şahıs, kusuru olmaksızın bir mani sebebiyle müddeti içinde haciz
ihbarnamesine itiraz etmediği takdirde 65 inci madde hükmü uygulanır. Her hâlde
üçüncü şahıs, borçlu ile kötü niyetli alacaklıya karşı dava açarak ödemek
zorunda kaldığı paranın veya teslim ettiği malın iadesini isteyebilir.

Malın teslimi mümkün olmazsa, alacaklı icra mahkemesine müracaatla değerini
üçüncü şahsa ödetmek hakkını haizdir.

Haciz ihbarnamesi, borçlunun hak ve alacaklarının bulunabileceği bir tüzel
kişinin veya müessesenin şubesine veya tüm şubelerini kapsayacak şekilde
merkezine tebliğ edilir. Haciz ihbarnamesinin tebliğ edildiği merkez, tüm
şubeleri veya birimlerini kapsayacak şekilde beyanda bulunmakla yükümlüdür.

=== HACZE ADİ İŞTİRAK

İlk haciz üzerine satılan malın tutarı vezneye girinciye kadar aynı derecede
hacze iştirak edebilecek alacaklılar:

. İlk haciz ilamsız takibe müstenitse takip talebinden ve ilama istinat
ediyorsa dava ikamesinden mukaddem yapılmış bir takip üzerine alınan aciz
vesikasına,
. Yukarıdaki fıkrada yazılı tarihlerden önce açılmış bir dava üzerine alınan
ilama,
. Aynı tarihlerden mukaddem tarihli resmi veya tarih ve imzası tasdikli bir
senede,
. Aynı tarihlerden mukaddem tarihli resmi dairelerin veya yetkili makamların
yetkileri dahilinde ve usulüne göre verdikleri makbuz veya vesikaya

istinat eden alacaklılardır.

Bunların haricindeki alacaklılar ancak, evvelki dereceden artacak bedeller için
hacze iştirak edebilirler.

Bu suretle iştirak halinde icra dairesi müracaat üzerine aynı derecedeki
alacaklıların bütün alacaklarına yetecek nispette ilave suretiyle hacizler
yapar.

CAUTION: Ücret haczinde iştirak olmaz.

Hacze adi iştirakin şartları:

. *Takip yapmış olma*
. *Öncelik*
. *Belge ile ispat*

TIP: Hacze iştirak edilip edilemeyceğinin anlaşılması için ilk haciz uygulayan
alacaklının takip tarihine bakılması gerekir. Eğer ilamlı takip söz konusu ise
dava açtığı tarih esas alınır. Kişinin alacağı bu tarihten önce doğmuş ve yine
bu tarihten önce bir takip başlatılmışsa hacze iştirak edebilir.

Kişinin hacze iştirak talebi reddedilirse şikayet yoluna başvurabilir.

=== HACZE İMTİYAZLI İŞTİRAK

Borçlunun eşi ve çocukları ve vasi veya kayyımı olduğu şahıslar evlenme,
velayet veya vesayetten mütevellit alacaklar için önce icrası lazım gelen takip
merasimine lüzum olmaksızın ilk haciz üzerine satılan malın tutarı vezneye
girinceye kadar aynı derecede hacze iştirak edebilirler. Şu kadar ki bu hak
ancak haciz, vesayetin veya velayetin veya evliliğin devamı esnasında veya
zevalini takip eden sene içinde yapıldığı takdirde istimal olunabilir.

Bir dava veya takibin devam ettiği müddet hesaba katılmaz.

Borçlunun reşit çocukları Medeni Kanunun 321 inci maddesine müstenit
alacaklarından dolayı önce icrası lazım gelen takip merasimine hacet
kalmaksızın her zaman aynı derecede hacze iştirak edebilirler.

Sulh mahkemesi dahi küçükler, vesayet altında bulunanlar veya kendilerine
kayyım tayin edilmiş olanlar namına aynı suretle hacze iştirak edebilirler.

İcra dairesi iştirak taleplerini borçlu ve alacaklılara bildirir.Onlara, itiraz
etmeleri için yedi günlük bir mühlet verir. İtiraz halinde iştirak talebinde
bulunan kimsenin hacze iştiraki muvakkaten kabul olunur ve yedi gün içinde dava
açması lüzumu bildirilir. Bu süre içinde dava açmazsa iştirak hakkı düşer.
Açılacak davaya basit yargılama usulüne göre bakılır.

Nafaka ilamına istinat eden alacaklı önce takip merasiminin icrasına lüzum
olmaksızın her zaman aynı derecede hacze iştirak edebilir. Kötü niyet hali
müstesnadır.

TIP: Nafaka çok yüksekse diğer alacaklılar hacze iştirak edilmesine karşı
koyabilir.

=== HACİZDE İSTİHKAK

Bir taşınır malı elinde bulunduran kimse onun maliki sayılır. Borçlu ile üçüncü
şahısların taşınır malı birlikte ellerinde bulundurmaları halinde dahi mal
borçlu elinde addolunur. Birlikte oturulan yerlerdeki mallardan mahiyetleri
itibariyle kadın, erkek ve çocuklara aidiyetleri açıkça anlaşılanlar veya örf
ve adet, sanat, meslek veya meşgale icabı olanlar bunların farz olunur. Bu
karinenin aksini ispat külfeti iddia eden kişiye düşer.

İstihkak davacısı malı ne suretle iktisap ettiğini ve borçlunun elinde
bulunmasını gerektiren hukuki ve fiili sebep ve hadiseleri göstermek ve bunları
ispat etmekle mükelleftir.

Borçlu, elinde bulunan bir malı başkasının mülkü veya rehni olarak gösterdiği
yahut üçüncü bir şahıs tarafından o mal üzerinde mülkiyet veya rehin hakkı
iddia edildiği takdirde, icra dairesi bunu haciz ve icra tutanaklarına geçirir
ve keyfiyeti iki tarafa bildirir.

İcra dairesi aynı zamanda istihkak iddiasına karşı itirazları olup olmadığını
bildirmek üzere alacaklı ve borçluya üç günlük mühlet verir. Sükütları halinde
istihkak iddiasını kabul etmiş sayılırlar.

Malın haczini öğrenmiş olan borçlu veya üçüncü şahıs, öğrenme tarihinden
itibaren yedi gün içinde istihkak iddiasında bulunmadığı takdirde, aynı takipte
bu iddiayı ileri sürmek hakkını kaybeder. İstihkak iddiasının yapıldığı veya
istihkak davasının açıldığı tarihte istihkak müddeisi ile birlikte oturan
kimseler yahut bu şahısların iş ortakları, iddianın yapıldığı tarihte veya
istihkak davası 97 nci maddenin 9 uncu fıkrası gereğince açılmışsa davanın
açıldığı tarihte malın haczini öğrenmiş sayılırlar.

İstihkak iddiasına karşı alacaklı veya borçlu tarafından itiraz edilirse, icra
memuru dosyayı hemen icra mahkemesine verir. İcra Mahkemesi, dosya üzerinde
veya lüzum görürse ilgilileri davet ederek mürafaa ile yapacağı inceleme
neticesinde varacağı kanaate göre takibin devamına veya talikine karar verir.

NOTE: Takibin taliki sadece üzerinde istihkak iddiası bulunan mal için
geçerlidir.

İstihkak davasının sırf satışı geri bırakmak gayesiyle kötüye kullanıldığını
kabul etmek için ciddi sebepler bulunduğu takdirde icra mahkemesi takibin
talikı talebini reddeder.

Takibin talikıne karar verilirse, haksız çıktığı takdirde alacaklının muhtemel
zararına karşı davacıdan 36 ncı maddede gösterilen teminat alınır. Teminatın
cins ve miktarı mevcut delillerin mahiyetine göre takdir olunur.

Takibin devamına dair verilen icra mahkemesi kararı kesindir.

Üçüncü şahıs, icra mahkemesi kararının tefhim veya tebliğinden itibaren yedi
gün içinde icra mahkemesinde istihkak davası açmaya mecburdur. Bu müddet
zarfında dava edilmediği takdirde üçüncü şahıs alacaklıya karşı iddiasından
vazgeçmiş sayılır.

Yukardaki hükümler dairesinde kendisine istihkak talebinde bulunmak imkanı
verilmemiş olan üçüncü şahıs, haczedilen şey hakkında veya satılıp da bedeli
henüz alacaklıya verilmemişse bedeli hakkında, hacze ıttıla tarihinden itibaren
yedi gün içinde, icra mahkemesinde istihkak davası açabilir. Aksi takdirde aynı
takipte bu iddiayı ileri sürmek hakkını kaybeder. Bu halde davacının talebi
üzerine icra hakimi takibin talik edilip edilmemesi hakkında yukardaki hükümler
dairesinde acele karar vermeye mecburdur. Bu karar diğer taraf dinlenmeksizin
de verilebilir.

İstihkak davası neticelenmeden mahcuz mal paraya çevrilmiş bulunursa icra
hakimi işbu bedelin yargılama neticesine kadar ödenmemesi veya teminat
karşılığında veya halin icabına göre teminatsız derhal alacaklıya verilmesi
hususunda ayrıca karar verir.

İstihkak davasına umumi hükümler dairesinde ve basit yargılama usulüne göre
bakılır.

İstihkak davası üzerine takibin talikine karar verilip de neticede dava
reddolunursa alacaklının alacağından bu dava dolayısıyla istifası geciken
miktarın yüzde yirmisinden aşağı olmamak üzere davacıdan tazminat alınmasına
hükmolunur.

Davanın reddi hakkındaki karara karşı istinaf veya temyiz yoluna başvuran
istihkak davacısı icra dairesinden 36 ncı maddeye göre mühlet isteyebilir.

İstihkak davası sabit olur ve birinci fıkra gereğince istihkak iddiasına karşı
itiraz eden alacaklı veya borçlunun kötü niyeti tahakkuk ederse haczolunan
malın değerinin yüzde onbeşinden aşağı olmamak üzere itiraz edenden tazminat
alınmasına asıl dava ile birlikte hükmolunur.

İstihkak davalarının hukuki niteliği doktrinde tartışmalıdır. İstihkak iddiası
ileri sürüldüğünde icra mahkemesinde verilen kararın kesin hüküm teşkil edip
etmeyeceğine yönelik farklı görüşler vardır. Yargıtay da bu konuda çelişik
kararlar verebilmektedir.

İcra mahkemesinin inceleme yetkisi ile genel mahkemelerin inceleme yetkisi ve
kapsamı arasında fark yok ise icra mahkemesinin kararı kesin hüküm teşkil
etmektedir. Bu anlamda icra mahkemesinin istihkak iddialarını incelerken
yetkisine bakıldığında genel mahkemelerden daha yetkili olduğu görülür.
Dolayısıyla kürsüye göre istihkak davaları sonunda verilen hükmün kesin hüküm
olduğunu kabul etmek gerekir.
