:icons: font
:toc:
:toc-title: İCRA İFLAS

== İCRA TEŞKİLATI

. İcra Dairesi
. İcra Mahkemesi
. Bölge Adliye Mahkemesi
. Yargıtay'ın icra ve iflas işleri ile görevli daireleri

=== İCRA DAİRESİ

Neredeyse bütün icra takiplerinin başlaması bir icra dairesine başvurulması
suretiyle gerçekleşir. İcra daireleri hemen her ilçede kurulur ve o ilçenin
adıyla anılır (örn. Sarıyer 1. İcra Dairesi). _Her asliye mahkemesinin yargı
çevresinde yeteri kadar icra dairesi bulunur._

==== İCRA MEMURLARI

İcra takibi icra dairesinde icra memuruna başvurulmak suretiyle başlatılır.
İcra takibi talebini alan icra memuru borçluya bir ödeme emri gönderir.

İcra memuru, yargı çevresi içinde görev yaptığı icra mahkemesinin emir ve
talimatını almaz. Gerektiği takdirde kolluk kuvvetlerinden faydalanabilir.

İcra ve iflas daireleri yaptıkları işlemleri ve kendilerine gelen talep ve
beyanları tutanağa kaydederler. Aksi ispat edilinceye kadar bu tutanaklar doğru
kabul edilir (İİK 8).

İcra ve iflas dairelerince yapılacak her türlü icra ve iflas iş ve işlemlerinde
Ulusal Yargı Ağı Bilişim Sistemi kullanılır; her türlü veri, bilgi, belge ve
karar, Ulusal Yargı Ağı Bilişim Sistemi vasıtasıyla işlenir, kaydedilir ve
saklanır.

Usulüne göre güvenli elektronik imza ile oluşturulan elektronik veriler senet
hükmündedir. Güvenli elektronik imza, elle atılan imza ile aynı ispat gücünü
haizdir. Güvenli elektronik imza, kanunlarda güvenli elektronik imza ile
yapılamayacağı açıkça belirtilmiş olan işlemler dışında, elle atılan imza
yerine kullanılabilir (İİK 8/a).

WARNING: Elektronik ortamda yapılan işlemlerde süre gün sonunda biter.

İcra ve iflas işlerine bakan memur

. Kendisinin,
. Karı veya kocasının, nişanlısının yahut kan ve sıhri usul ve füruunun veya
üçüncü derece dahil olmak üzere bu dereceye kadar olan kan ve sıhri civar
hısımlarının,
. Kanuni mümessili veya vekili yahut müstahdemi bulunduğu bir şahsın,
Menfaati olan işleri göremeyip derhal icra mahkemesine haber vermeye mecburdur.

İcra mahkemesi müracaatı yerinde görürse o işi diğer bir memura, bulunmıyan
yerlerde katiplerinden birine verir (İİK 10).

Tetkik vazifesini gören hakimler ve icra ve iflas memurları, dairelerince takip
edilmekte olan bir alacak veya satılmakta bulunan bir şey hakkında kiminle
olursa olsun kendileri veya başkaları hesaplarına bir akit yapamazlar.
Yaparlarsa hükümsüzdür (İİK 11).

NOTE: Tetkik mercii İcra Mahkemesidir.

İcra ve İflas Dairesi görevlilerinin kusurlarından doğan tazminat davaları,
ancak idare aleyhine açılabilir. Devletin, zararın meydana gelmesinde kusuru
bulunan görevlilere rücu hakkı saklıdır.Bu davalara asliye mahkemelerinde
bakılır (İİK 5).

İcra dairesine tevdi veya bu dairece tahsil olunan veya muhafaza altına alınan
paraların,ilgili memur tarafından zimmete geçirilmesi halinde, zimmete
geçirilen miktar, cezai takibat sonucu beklenmeden ve tazmin yolunda bir hükme
hacet kalmaksızın hazine tarafından derhal icra veznesine yatırılır. Devletin
asıl sorumlulara rücu hakkı saklıdır (İİK 6).

İcra ve iflâs dairelerinin muamelelerine karşı yapılan şikâyetlerle itirazların
incelenmesi icra mahkemesi hâkimi yahut kanun gereğince bu görev kendisine
verilmiş olan hâkim tarafından yapılır. İş durumunun gerekli kıldığı yerlerde
Hâkimler ve Savcılar Yüksek Kurulunun olumlu görüşü ile Adalet Bakanlığınca
icra mahkemesinin birden fazla dairesi kurulabilir. Bu durumda icra mahkemesi
daireleri numaralandırılır. İcra mahkemesinin birden fazla dairesi bulunan
yerlerde iş dağılımı ve buna ilişkin esaslar, Hâkimler ve Savcılar Yüksek
Kurulunca belirlenir. Her icra mahkemesi hâkimi, kendisine Adlî Yargı Adalet
Komisyonu Başkanlığınca dönüşümlü olarak bağlanan icra ve iflâs dairelerinin
muamelelerine yönelik şikâyetleri ve itirazları inceler, bu dairelerin gözetim
ve denetimlerini yapar, idarî işlerine bakar. İcra yetkisini haiz sulh
mahkemelerinin muamelelerine karşı vuku bulacak şikayet ve itirazların icra
mahkemesi o mahkemenin hakimidir (İİK 4).

İcra ve iflâs daireleri, 4 üncü maddedeki esaslara göre icra mahkemesi
hâkiminin daimî gözetimi ve denetimi altındadır. Bu daireler Cumhuriyet
savcıları ve adalet müfettişleri vasıtası ile denetime tabi tutulur. Cumhuriyet
savcıları bu daireleri yılda en az bir defa denetlerler (İİK 13).

=== İCRA MAHKEMELERİ

* *Basit yargılama usulüne* göre karar verirler.
* Kural olarak icra takibi sırasında ortaya çıkan sorunlarla ilgilenir.
İstisnai olarak ceza mahkemesi gibi bazı cezalara da hükmedebilir.
* Tek hakimlidir.
* *Verdikleri kararlar kural olarak kesin hüküm teşkil etmez*.
* Kararlarına karşı istinaf yoluna başvurulabilir ancak istinaf sınırı diğer
hukuk mahkemelerine göre daha yüksektir.

== ŞİKAYET

Şikayet, icra ve iflas memurlarının yapmış oldukları kanuna aykırı işlemlerin
düzeltilmesi amacıyla düzenlenmiş bir müessesedir.

IMPORTANT: Şikayet dava değildir!

Şikayet icra memurunun bağlı olduğu icra mahkemesine yöneltilir. İcra mahkemesi
hakimi dilerse işlemi yapmış olan icra memurunu davet ederek dinler ancak
çağırmak zorunda değildir. Takibin karşı tarafı da bu şikayet konusu işlemin
iptalinden etkileneceği için dilerse hakim onu da dinleyebilir.

İşlem aşağıdaki sebeplerle şikayet konusu yapılabilir:

. *İşlemin kanuna uygun olmaması*
. *İşlemin olaya uygun olmaması*: Kanunun icra memuruna takdir yetkisi tanıdığı
durumlarda takdir yetkisinin olaya uygun kullanılmaması
. *Bir hakkın yerine getirilmemesi*
. *Bir hakkın sebepsiz sürüncemede bırakılması*

Şikayet eden icra takibinin tarafı olmak zorunda değildir. Kanun hukuki yararı
olmak şartıyla bütün üçüncü kişilerin şikayet yoluna başvurabileceğini
söylemektedir.

Şikayet işlemin öğrenilmesinden itibaren *yedi gün* içinde yapılmalıdır. Ancak
_kamu düzenine aykırılık_ ve _bir hakkın yerine getirilmemesi_ veya _sebepsiz
sürüncemede bırakılması_ halinde şikayet süreye bağlı değildir.

NOTE: Şikayet bir hata sonucu icra mahkemesine değil de icra dairesine yapılmış
ise süre korunmayacaktır.

Şikayet yazılı veya sözlü olarak yapılabilir.

Şikayet, icra mahkemesince karar verilmedikçe icrayı durdurmaz.

İcra mahkemesi işlemin kanuna aykırı olduğunu tespit ederse işlemi iptal ederek
icra memurundan kanuna uygun işlem yapmasını ister. İcra memurları icra
mahkemelerinin emir ve talimatı altında olmasalar bile şikayet üzerine verilen
kararlar emirdir ve buna uyulmak zorundadır.

CAUTION: İcra mahkemesi hiçbir şekilde icra mahkemesi hakimi icra memurunun
yerine geçip işlem yapmaz. Ancak kanunun saydığı istisnai hallerde düzelterek
onama kararı verebilir.

Şikayet hakkında karar veren icra mahkemesinin kararlarına karşı istinaf yoluna
başvurulabilir.

== TATİL VE TALİK HALLERİ

=== TATİLLER

Güneşin batmasından bir saat sonra ile güneşin doğmasından bir saat önceye
kadarki devrede (Gece vakti) ve tatil günlerinde takip muameleleri yapılamaz.
Ancak, gece iş görülen yerlerde gece vakti hasılat haczi mümkündür.

Tatil günlerinde haciz ve tebligat yapılabileceği gibi muhafaza tedbirleri de
alınabilir.

Borçlunun mal kaçırdığı anlaşılırsa gece vakti dahi haciz yapılması caizdir.

=== TALİK HALLERİ

. *Borçlunun ailesinden birinin ölümü halinde*: Karısı yahut kocası ve kan ve
sıhriyet itibariyle usul veya füruundan birisi ölen bir borçlu aleyhindeki
takip, ölüm günü ile beraber üç gün için talik olunur.
. *Terekenin borçlarında*: Terekenin borçlarından dolayı ölüm günü ile beraber
üç gün içinde takip geri bırakılır. Mirasçı mirası kabul veya reddetmemişse bu
hususta Kanunu Medenide muayyen müddetler geçinceye kadar takip geri kalır.
. *Tutukluluk ve hükümlülük halinde*: Mümessili olmıyan bir tutuklu veya
hükümlü aleyhine takipte, mümessil tayini vesayet makamına ait olmadıkça, icra
memuru bir mümessil tayin etmesi için kendisine münasip bir mühlet verir ve
takibi bu sürenin bitmesine bırakır. Bu mühlet içinde temsilci tayin edip icra
dairesine bildirmiyen tutuklu veya hükümlü hakkında takibe devam olunur. Mal
kaçırılması ihtimali olan hallerde bu mühlet içinde de haciz yapılabilir.
. *Askerlik halinde*: Askerlik hizmetinin devamı müddetince erler, onbaşılar ve
kıta çavuşları (Uzman veya uzatmalı çavuş ve onbaşılar hariç) aleyhine takipte,
icra memuru, bir mümessil tayin etmesi için kendisine münasip bir mühlet verir
ve takibi bu sürenin bitmesine bırakır. Bu müddet içinde temsilci tayin edip
icra dairesine bildirmiyenler hakkında takibe devam olunur. Mal kaçırılması
ihtimali olan hallerde bu mühlet içinde de haciz yapılabilir.
. *Borçlunun ağır hastalığı halinde*: Takip borçlunun mümessil tayin edemiyecek
derecede ağır hastalığı halinde muayyen bir zaman için icra memurluğunca talik
olunabilir. Ağır hastalığın resmi belge ile tahakkuku lazımdır. Mal kaçırılması
ihtimali olan hallerde hastalığın devamı sırasında da haciz yapılabilir.

NOTE: Takip talikleri esnasında müddetlerin cerayanı durmaz. Müddetin nihayeti
bir talik gününe rastlarsa müddet talikin bitiminden sonra bir gün daha
uzatlır.

== İCRA TAKİBİ

=== TAKİBİN TARAFLARI

İcra takibinin tarafları; alacaklı ve borçludur.

Takibi yapan kendisini alacaklı olarak gösterecektir. Maddi hukuk bakımından
alacaklı olup olmadığı araştırılmaz. Aleyhine takip yapılan kişi de borçludur.
Yine maddi hukuk bakımından borçlu sıfatını taşıyıp taşımadığı araştırılmaz.

Takibi başlatabilmek veya aleyhine takip başlatılabilmesi için hem alacaklının
hem de borçlunun hak ehliyetine sahip olması gerekir. Hak ehliyetinin usul
hukukundaki görünümü taraf ehliyetidir. Taraf ehliyeti icra memurunun
kendiliğinden gözetmesi gereken bir husustur. Taraf ehliyeti eksik ise icra
memuru takibi başlatmayacaktır.

=== TAKİBİN KONUSU

Genel haciz yoluyla takip para ve teminat alacakları için söz konusudur.

TIP: Para alacağı TL dışında bir para birimi üzerindense alacaklı bir seçim
hakkına sahiptir. Yabancı para borcunu dilerse vade tarihindeki dilerse fiili
ödeme tarihindeki kur üzerinden isteyebilir.

=== TAKİP TALEBİ

Takip talebi icra dairesine yazılı veya sözlü olarak ya da elektronik ortamda
yapılır.

Talepte şunlar gösterilir:

. Alacaklının ve varsa kanuni temsilcisinin ve vekilinin adı, soyadı; alacaklı
veya vekili adına ödemenin yapılacağı banka adı ile hesap bilgileri; varsa
Türkiye Cumhuriyeti kimlik numarası veya vergi kimlik numarası; şöhret ve
yerleşim yeri; alacaklı yabancı memlekette oturuyorsa Türkiye’de göstereceği
yerleşim yeri (Yerleşim yeri gösteremezse icra dairesinin bulunduğu yer
yerleşim yeri sayılır.);
. Borçlunun ve varsa kanuni temsilcisinin adı, soyadı, alacaklı tarafından
biliniyorsa Türkiye Cumhuriyeti kimlik numarası veya vergi kimlik numarası,
şöhret ve yerleşim yeri; Bir terekeye karşı yapılan taleplerde kendilerine
tebligat yapılacak mirasçıların adı, soyadı, biliniyorsa Türkiye Cumhuriyeti
kimlik numarası veya vergi kimlik numarası, şöhret ve yerleşim yerleri;
. Alacağın veya istenen teminatın Türk parasıyla tutarı ve faizli alacaklarda
faizin miktarı ile işlemeye başladığı gün, alacak veya teminat yabancı para ise
alacağın hangi tarihteki kur üzerinden talep edildiği ve faizi;
. Senet, senet yoksa borcun sebebi;
. Takip yollarından hangisinin seçildiği;

Alacak belgeye dayanmakta ise, belgenin aslının veya alacaklı yahut mümessili
tarafından tasdik edilmiş, borçlu sayısından bir fazla örneğinin takip talebi
anında icra dairesine tevdii mecburidir.

Alacaklıya takip talebinde bulunduğuna ve verdiği belgelere, talep ve takip
masraflarına dair bedava ve pulsuz bir makbuz verilir.

Yabancı para alacaklısı takip yaparken takip talebinde alacağını Türk parasına
çevirmek zorundadır. Bu çeviri takip tarihindeki Merkez Bankası efektif satış
kuru esas alınarak yapılır. Buna rağmen alacaklının para alacağını fiili ödeme
tarihindeki kur üzerinden ya da vade tarihindeki kur üzerinde talep etmesi de
mümkündür. Ancak bunun takip talebinde özellikle belirtilmiş olması gerekir.

Takip masrafları *borçluya* aittir. Takip talebinde bulunan alacaklıdan *maktu
başvurma harcı*, *nispi peşin harç*, *ödeme emrinin tebliği için gerekli
masraflar* ve borçlunun İİK 62'ye göre itirazı halinde bu *itirazın alacaklıya
tebliği için gerekli masraflar* peşinen alınır. Alacaklı ilk ödenen paradan
masraflarını alabilir.

=== TAKİBİN SONUÇLARI

. İcra müdürü ödeme emri düzenleyip borçlu veya borçlulara gönderir.
. Alacaklıya icra dairesi tarafından kendiliğinden takip talebinde bulunduğuna
ve belgelere ve takip giderlerine ilişkin bedava ve pulsuz bir belge verilir.
. Takip talebi ile zamanaşımı kesilir. Takip dolayısı ile yapılan her işlemle
tekrar kesilir.
. Borçlu o ana kadar düşmemişse ödeme emrinin tebliği ile temerrüde düşer.

NOTE: Alacaklı, yaptığı icra takibinden vazgeçip takip talebini geri alabilir.
Bunun için borçlunun rızasına ihtiyaç yoktur.

== ÖDEME EMRİ

İcra müdürü takip talebinin bu Kanunda öngörülen şartları içerdiğine karar
verirse ödeme emri düzenler. Talebin kabul edilmemesi halinde verilen karar
tutanağa yazılır.

Emir:

. Alacaklının veya vekilinin banka hesap numarası hariç olmak üzere, 58 inci
maddeye göre takip talebine yazılması lazım gelen kayıtları,
. Borcun ve masrafların yedi gün içinde icra dairesine ait ödeme emrinde yazılı
olan banka hesabına ödenmesi, borç, teminat verilmesi mükellefiyeti ise
teminatın bu süre içinde gösterilmesi ihtarını,
. Takibin dayandığı senet altındaki imza kendisine ait değilse yine bu yedi gün
içinde bu cihetin ayrıca ve açıkça bildirilmesi; aksi halde icra takibinde
senedin kendisinden sadır sayılacağı,
+
Senet altındaki imzayı reddettiği takdirde icra mahkemesi önünde yapılacak
duruşmada hazır bulunması; buna uymazsa vakı itirazın muvakkaten kaldırılmasına
karar verileceği,
+
Borcun tamamına veya bir kısmına yahut alacaklının takibat icrası hakkına dair
bir itirazı varsa bunu da aynı süre içinde beyan etmesi,
+
İhtarını,
. Senet veya borca itirazını bildirmediği takdirde yukarda yazılı yedi günlük
süre içinde 74 üncü maddeye göre mal beyanında bulunması ve bulunmazsa hapisle
tazyik olunacağı; mal beyanında bulunmaz veya hakikate aykırı beyanda bulunursa
ayrıca hapisle cezalandırılacağı ihtarını,
. Borç ödenmez veya itiraz olunmazsa cebri icraya devam edileceği beyanını,
+
İhtiva eder.

Ödeme emri iki nüsha olarak düzenlenir. Bir nüshası borçluya gönderilir, diğeri
icra dosyasına konulur. Alacaklı isterse kendisine ayrıca tasdikli bir nüsha
verilir. Nüshalar arasında fark bulunduğu takdirde borçludaki muteber sayılır.

Ödeme emri borçluya takip talebinden itibaren nihayet 3 gün içinde tebliğe
gönderilir. Takip belgeye dayanıyorsa, belgenin tasdikli bir örneği ödeme
emrine bağlanır.

Müşterek borçlular aynı zamanda takip ediliyorlarsa hepsinin veya bir kısmının
bir mümessil tarafından temsil edilmeleri hali müstesna olmak üzere her birine
ayrı ayrı ödeme emri tebliğ edilmek lazımdır.

== İTİRAZ

İtiraz etmek istiyen borçlu, itirazını, ödeme emrinin tebliği tarihinden
itibaren yedi gün içinde dilekçe ile veya sözlü olarak icra dairesine
bildirmeye mecburdur.

İtiraz, takibi yapan icra dairesinden başka bir icra dairesine yapıldığı
takdirde bu daire gereken masrafı itirazla birlikte alarak itirazı derhal
yetkili icra dairesine gönderir; alınmayan masraftan memur şahsen sorumludur.

Takibe itiraz edildiği, 59 uncu maddeye göre alacaklının yatırdığı avanstan
karşılanmak suretiyle üç gün içinde bir muhtıra ile alacaklıya tebliğ edilir.

Borçlu veya vekili, dava ve takip işlemlerine esas olmak üzere borçluya ait
yurt içinde bir adresi itirazla birlikte bildirmek zorundadır. Adresini
değiştiren borçlu yurt içinde yeni adres bildirmediği ve tebliğ memurunca yurt
içinde yeni adresi tespit edilemediği takdirde, takip talebinde gösterilen
adrese çıkarılacak tebligat borçlunun kendisine yapılmış sayılır.

Borcun bir kısmına itiraz eden borçlunun o kısman cihet ve miktarını açıkca
göstermesi lazımdır. Aksi takdirde itiraz edilmemiş sayılır.

Borçlu takibin müstenidi olan senet altındaki imzayı reddediyorsa, bunu
itirazında ayrıca ve açıkça beyan etmelidir. Aksi takdirde icra takibi
yönünden senetteki imzayı kabul etmiş sayılır.

İtiraz eden borçlu, itirazın kaldırılması duruşmasında, alacaklının dayandığı
senet metninden anlaşılanlar dışında, itiraz sebeplerini değiştiremez ve
genişletemez.

Borçlu kusuru olmaksızın bir mani sebebiyle müddeti içinde itiraz edememiş ise
paraya çevirme muamelesi bitinceye kadar itiraz edebilir.

Ancak borçlu, maniin kalktığı günden itibaren üç gün içinde, mazeretini gösterir
delillerle birlikte itiraz ve sebeplerini ve müstenidatını bildirmeye ve
mütaakıp fıkra için yapılacak duruşmaya taallük eden harç ve masrafları ödemeye
mecburdur. İtiraz üzerine icra mahkemesi ancak gecikme sebebinin mahiyetine ve
hadisenin özelliklerine göre takibin tatilini tensip edebilir.

İcra mahkemesi, tetkikatını evrak üzerinde yapar. Lüzumu halinde iki tarafı
hemen davetle mazeretin kabule şayan olup olmadığına karar verir. Duruşmaya
karar verilmemesi halinde borçludan alınan masraflar kendisine iade olunur.
Mazeretin kabulü halinde icra takibi durur. Aynı celsede alacaklı itirazın
kaldırılmasını sözlü olarak da istiyebilir. Bu takdirde tahkikata devam
olunarak gerekli karar verilir.

Daha önce borçlunun mallarına haciz konulmuşsa mazeretin kabulü kararının
tefhim veya tebliği tarihinden itibaren alacaklı yedi gün içinde, icra
mahkemesinden itirazın kaldırılmasını istemez veya aynı süre içinde 67 nci
maddeye göre mahkemeye başvurmazsa haciz kalkar.

Müddeti içinde yapılan itiraz takibi durdurur. İtiraz müddetinde değilse
alacaklının talebi üzerine icra memuru takip muamelelerine alacağın tamamı için
devam eder. Borçlu, borcun yalnız bir kısmına itirazda bulunmuşsa takibe, kabul
ettiği miktar için devam olunur.

Takip talebine itiraz edilen alacaklı, itirazın tebliği tarihinden itibaren bir
sene içinde mahkemeye başvurarak, genel hükümler dairesinde alacağının
varlığını ispat suretiyle itirazın iptalini dava edebilir.

Talebine itiraz edilen alacaklının takibi, imzası ikrar veya noterlikçe tasdik
edilen borç ikrarını içeren bir senede yahut resmî dairelerin veya yetkili
makamların yetkileri dahilinde ve usulüne göre verdikleri bir makbuz veya
belgeye müstenitse, alacaklı itirazın kendisine tebliği tarihinden itibaren
altı ay içinde itirazın kaldırılmasını isteyebilir. Bu süre içerisinde itirazın
kaldırılması istenilmediği takdirde yeniden ilâmsız takip yapılamaz.

=== İTİRAZIN İPTALİ DAVASI

İtiraz sonucunda duran takibe devam edebilmek için alacaklının başvurabileceği
yollardan biri *itirazın iptali* davasıdır. Bu dava genel mahkemede genel
hükümlere göre açılır.

[TIP]
====
İtirazın iptali davasının eda davasından farkı; eda davası sonunda alınan
hükme dayanılarak ilamlı icra takibi yapılabilir, ancak itirazın iptali
davasında verilen karara dayanarak sadece duran takibin devamı sağlanabilir.
Duran takibe devam edilmesi ilamlı takip değil, başlatılmış ilamsız takibin
devamıdır.

Davacı, davayı açarken itirazın iptali davasını doğru bir şekilde ifade etmeli
ve talep sonucunu doğru yazmalıdır. Neticede hakim talep ile bağlıdır, başka
bir şeye karar veremez. Başta eda davası olarak açılıp sonradan durmuş takibin
devamına karar verilmesi istenirse iddianın değiştirilmesi ve genişletilmesi
yasağı gündeme gelecektir.
====

İtirazın iptali davası genel hükümlere göre açılır ve incelenir. Alacaklı genel
hükümlere göre alacağını ispat yükü altındadır. Dava konusunun değerine göre
senetle ispat mecburiyeti vs. gündeme gelebilir.

İtirazın iptali davası itirazın tebliğ tarihinden itibaren *bir sene*
içerisinde açılmalıdır. Bu bir seneliik süre hak düşürücüdür. Bir senelik
sürenin geçmesi üzerine ancak genel mahkemelerde eda davası açılıp, alınacak
karar ile birlikte ilamlı icra takibi yapılabilir.

Bu davada borçlunun itirazının haksızlığına karar verilirse borçlu; takibinde
haksız ve kötü niyetli görülürse alacaklı; diğer tarafın talebi üzerine iki
tarafın durumuna, davanın ve hükmolunan şeyin tahammülüne göre, red veya
hükmolunan meblağın yüzde yirmisinden aşağı olmamak üzere, uygun bir tazminatla
mahkum edilir.

Alacaklının aleyhine tazminata hükmedilebilmesi için haksız ve kötü niyetli
olması aranırken, borçlunun tazminat ile sorumlu olması için haksız çıkması
yeterlidir.

NOTE: %20 tazminatın alacaklı veya borçlu aleyhine hükmedilebilmesi için talep
zorunludur. Talep olmadan mahkeme kendiliğinden böyle bir tazminata hükmedemez.

Borçlu aleyhine hükmedilen tazminata *inkar tazminatı*, alacaklı aleyhine
hükmedilen tazminata *kötüniyet tazminatı* denir.

TIP: Yargıtay'a göre borçlunun aleyhine inkar tazminatına hükmedilebilmesi için
itiraz ettiği borcun likit, yani kararlaştırılmış ve bilinen olması gerekir.
Eğer itiraz edilen borç, yargılamanın sonunda tespti gereken bir miktar ise
herhangi bir şekilde inkar tazminatına hükmedilemez.

IMPORTANT: İtirazın iptali davası ancak genel mahkemelerde açılabilir. İcra
mahkemesinde açılırsa görevsizlik kararı verilecektir.

İtirazın iptali davası sonunda verilen hüküm maddi anlamda kesin hüküm teşkil
eder. Alacaklı veya borçlubu davayo tekrar açamaz.

İtirazın iptali davası kabul edildiği takdirde borçlu, eğer daha önceden
bulunmamışsa, mahkeme kararının kendisine tefhim veya tebliğinden itibaren üç
gün içinde mal beyanında bulunmak zorundadır.

=== İTİRAZIN KESİN KALDIRILMASI

"_Talebine itiraz edilen alacaklının takibi, imzası ikrar veya noterlikçe
tasdik edilen borç ikrarını içeren bir senede yahut resmî dairelerin veya
yetkili makamların yetkileri dahilinde ve usulüne göre verdikleri bir makbuz
veya belgeye müstenitse, alacaklı itirazın kendisine tebliği tarihinden
itibaren altı ay içinde itirazın kaldırılmasını isteyebilir. Bu süre içerisinde
itirazın kaldırılması istenilmediği takdirde yeniden ilâmsız takip yapılamaz._"

Alacaklı aşağıdaki belgelerden birini göstermek şartıyla icra mahkemesinden
itirazın kesin olarak kaldırılmasını isteyebilir.

. *İmzası ikrar edilmiş senet*
. *İmzası noterlikçe onaylanmış senet*
. *Resmi dairelerin ve yetkili makamların yetkileri dahilinde usulüne uygun
verdikleri belgeler*

İtirazın kesin kaldırılması itirazdan itibaren altı ay içinde istenebilir.
İtirazın kesin kaldırılması talebi reddedilirse itirazdan itibaren bir yıl
içinde itirazın iptali davası açılabilir. Zira icra mahkemesinin verdiği karar
kesin değildir.

"_Borçlunun gösterdiği belge altındaki imza alacaklı tarafından inkar edilirse
hakim, 68/a maddesinde yazılı usule göre yaptığı inceleme neticesinde imzanın
alacaklıya ait olduğuna kanaat getirdiği takdirde alacaklının itirazın
kaldırılması talebini reddeder ve alacaklıyı sözü edilen belgenin taalluk
ettiği değer veya miktarın yüzde onu oranında para cezasına mahkum eder.
Alacaklı genel mahkemede dava açarsa bu para cezasının infazı dava sonuna kadar
tehir olunur ve alacaklı bu davada alacağını ve imzanın kendisine ait
olmadığını ispat ederse bu ceza kalkar._"

"_Tatbika medar imza mevcutsa bununla, yoksa borçluya yazdıracağı yazı ve
attıracağı imza ile yapılacak mükayese ve incelemelerden veya diğer delil ve
karinelerden icra mahkemesi, reddedilen imzanın borçluya aidiyetine kanaat
getirirse itirazın muvakkaten kaldırılmasına karar verir. Hakim lüzum görürse,
oturumun bir defadan fazla talikine meydan vermiyecek surette, bilirkişi
incelemesi de yaptırabilir._" (İİK 68/a fıkra 3)

CAUTION: İnkar tazminatı alacaklıya ödenirken para cezası devlete ödenir.

Alacaklı duruşmada bizzat bulunmayıp da imza vekili tarafından reddolunduğu
takdirde vekil mütaakıp oturumda müvekkilini imza tatbikatı için hazır
bulundurmaya veya masraflarını vererek davetiye tebliğ ettirmeye mecburdur.
Kabule değer mazereti olmadan gelmiyen alacaklı borçlunun dayandığı belgede
yazılı miktar hakkındaki itirazın kaldırılması talebinden vazgeçmiş sayılır.

İtirazın kaldırılması talebinin esasa ilişkin nedenlerle kabulü hâlinde borçlu,
talebin aynı nedenlerle reddi hâlinde ise alacaklı, diğer tarafın talebi
üzerine yüzde yirmiden aşağı olmamak üzere tazminata mahkûm edilir. Borçlu,
menfi tespit ve istirdat davası açarsa, yahut alacaklı genel mahkemede dava
açarsa, hükmolunan tazminatın tahsili dava sonuna kadar tehir olunur ve dava
lehine sonuçlanan taraf için, daha önce hükmedilmiş olan tazminat kalkar.

=== İTİRAZIN GEÇİCİ KALDIRILMASI

Takibin dayandığı senet hususî olup, imza itiraz sırasında borçlu tarafından
reddedilmişse, alacaklı itirazın kendisine tebliği tarihinden itibaren altı ay
içinde itirazın geçici olarak kaldırılmasını isteyebilir.

IMPORTANT: Alacaklının takip talebinde dayandığı senet, imzası noter tarafından
onaylı bir senet ise buradaki imza inkar edilemez, ancak sahtelik davası
açılabilir. İtirazın geçici kaldırılması ancak adi senet için söz konusu olur.

Senet altındaki imzayı reddeden borçlu takibi yapan icra dairesinin yetki
çevresi içinde ise, itirazın kaldırılması için icra mahkemesi önünde yapılacak
duruşmada, mazeretini daha önce bildirip tevsik etmediği takdirde, bizzat
bulunmaya mecburdur. İcra dairesinin yetki çevresi dışında ödeme emri tebliğ
edilen borçlu, istinabe yolu ile isticvabına karar verilmesi halinde, aynı
mecburiyete tabidir.

Tatbika medar imza mevcutsa bununla, yoksa borçluya yazdıracağı yazı ve
attıracağı imza ile yapılacak mükayese ve incelemelerden veya diğer delil ve
karinelerden icra mahkemesi, reddedilen imzanın borçluya aidiyetine kanaat
getirirse itirazın muvakkaten kaldırılmasına karar verir. Hakim lüzum görürse,
oturumun bir defadan fazla talikine meydan vermiyecek surette, bilirkişi
incelemesi de yaptırabilir.

Yapılacak duruşmada, borçlunun hazır bulunmaması halinde icra mahkemesince
başka bir cihet tetkik edilmeksizin itirazın muvakkaten kaldırılmasına ve
borçlunun sözü edilen senede dayanan takip konusu alacağın yüzde onu oranında
para cezasına mahkumiyetine karar verilir. Duruşmaya gelmeyen borçlunun
itirazının muvakkaten kaldırılmasına ve hakkında para cezasına karar
verilebilmesi için keyfiyetin davetiyeye yazılması şarttır.

İcra hakimi, imzanın borçluya aidiyetine karar verdiği takdirde borçluyu sözü
edilen senede dayanan takip konusuna alacağın yüzde onu oranında para cezasına
mahkum eder. Borçlu, borçtan kurtulma, menfi tespit veya istirdat davası
açarsa, bu para cezasının infazı dava sonuna kadar tehir olunur ve borçlu
açtığı davayı kazanırsa bu ceza kalkar.

Borçlu inkar ettiği imzayı, itirazın kaldırılması duruşmasında ve en geç
alacaklının senedin aslını ibraz ettiği celsede kabul ederse, hakkında para
cezası hükmolunmaz ve kendisine yargılama giderleri yükletilmez. Şu kadar ki,
kötü niyetle takibe sebebiyet ver en borçlu yargılama giderleri ile mülzem
olur. Senedin aslı takip talebi anında icra dairesine tevdi edilmiş ise, icra
dairesinin yetki çevresi içinde ödeme emri tebliğ edilen borçlu hakkında bu
fıkra hükmü uygulanmaz.

İtirazın muvakkaten kaldırılması talebinin kabulü halinde borçlu, bu talebin
reddi halinde ise alacaklı, diğer tarafın talebi üzerine yüzde yirmiden aşağı
olmamak üzere tazminata mahkum edilir. Borçlu, borçtan kurtulma, menfi tespit
veya istirdat davası açarsa, yahut alacaklı genel mahkemede dava açarsa
hükmolunan tazminatın tahsili dava sonuna kadar tehir olunur ve dava lehine
sonuçlanan taraf için, daha önce hükmedilmiş olan tazminat kalkar.

İtirazın muvakkaten kaldırılmasına karar verilir ve ödeme emrindeki müddet
geçmiş bulunursa alacaklının talebi ile borçlunun malları üzerine muvakkat
haciz konur.

== BORÇLUNUN AÇABİLECEĞİ DAVALAR

=== BORÇTAN KURTULMA DAVASI

İtirazın muvakkaten kaldırılması kararının tefhim veya tebliğinden itibaren
yedi gün içinde borçlu, takibin yapıldığı mahal veya alacaklının yerleşim yeri
mahkemesinde borçtan kurtulma davası açabilir. Bu davanın dinlenebilmesi için
borçlunun dava konusu alacağın yüzde 15 ini ilk duruşma gününe kadar mahkeme
veznesine nakden depo etmesi veya mahkemece kabul edilecek aynı değerde esham
ve tahvilat veya banka teminat mektubu tevdi etmesi şarttır. Aksi takdirde dava
reddolunur.

NOTE: Borçtan kurtulma davasının özel dava şartı dava konusu alacağın %15'i
oranında teminat yatırılmasıdır. %15'lik teminat yatırılmadığı takdirde bu dava
yalnızca menfi tespit davasıdır.

NOTE: Borçlu menfi tespit davasını önceden açmış ise, itirazın geçici kaldırılması
kararından sonra bu davayı %15 teminat yatırmak suretiyle borçtan kurtulma
davasına dönüştürebilir.

Borçlu yukarda yazılı müddet içinde dava etmez veya davası reddolunursa
itirazın kaldırılması kararı ve varsa muvakkat haciz kesinleşir.

Davanın reddi hakkındaki karara karşı istinaf yoluna başvuran borçlu, ayrıca 36
ncı madde hükümlerini yerine getirmek şartiyle, icra dairesinden mühlet
istiyebilir.

Borçtan kurtulma davasında haksız çıkan taraf, dava veya hükmolunan şeyin yüzde
yirmisinden aşağı olmamak üzere münasip bir tazminatla mahkum edilir.

=== MENFİ TESPİT DAVASI

Borçlu, icra takibinden önce veya takip sırasında borçlu bulunmadığını ispat
için menfi tesbit davası açabilir.

TIP: Tespit davalarının eda davalarından en önemli farkı; eda davalarında
hukuki yararın ayrıca ispatı gerekli değilken, tespit davalarında davacının
davayı açmaktan hukuki yararı olduğunu ispat etmesinin gerekmesidir.

İcra takibinden önce açılan menfi tesbit davasına bakan mahkeme, talep üzerine
alacağın yüzde onbeşinden aşağı olmamak üzere gösterilecek teminat mukabilinde,
icra takibinin durdurulması hakkında ihtiyati tedbir kararı verebilir.

İcra takibinden sonra açılan menfi tesbit davasında ihtiyati tedbir yolu ile
takibin durdurulmasına karar verilemez.  Ancak, borçlu gecikmeden doğan
zararları karşılamak ve alacağın yüzde onbeşinden aşağı olmamak üzere
göstereceği teminat karşılığında, mahkemeden ihtiyati tedbir yoluyle icra
veznesindeki paranın alacaklıya verilmemesini istiyebilir.

TIP: Kanunda takipten sonra açılan menfi tespit davasının takibi durdurmayacağı
söyleniyorsa da Yargıtay, borçlunun borcun tamamını ve ek olarak %15'ini
teminat göstermesi halinde takibin durdurulacağını içtihat etmiştir. Böylece
borçlu dava konusu alacağın %115'ini teminat göstermek suretiyle takibi
durdurabilir.

Dava alacaklı lehine neticelenirse ihtiyati tedbir kararı kalkar. Buna dair
hükmün kesinleşmesi halinde alacaklı ihtiyati tedbir dolayısıyla alacağını geç
almış bulunmaktan doğan zararlarını gösterilen teminattan alır. Alacaklının
uğradığı zarar aynı davada takdir olunarak karara bağlanır. Bu zarar herhalde
yüzde yirmiden aşağı tayin edilemez.

Dava borçlu lehine hükme bağlanırsa derhal takip durur. İlamın kesinleşmesi
üzerine münderecatına göre ve ayrıca hükme hacet kalmadan icra kısmen veya
tamamen eski hale iade edilir. Borçluyu menfi tespit davası açmaya zorlayan
takibin haksız ve kötü niyetli olduğu anlaşılırşa, talebi üzerine, borçlunun
dava sebebi ile uğradığı zararın da alacaklıdan tahsiline karar verilir. Takdir
edilecek zarar, haksızlığı anlaşılan takip konusu alacağın yüzde yirmisinden
aşağı olamaz.

=== İSTİRDAT DAVASI

Borçlu, menfi tesbit davası zımmında tedbir kararı almamış ve borç da ödenmiş
olursa, davaya istirdat davası olarak devam edilir.

Takibe itiraz etmemiş veya itirazının kaldırılmış olması yüzünden borçlu
olmadığı bir parayı tamamen ödemek mecburiyetinde kalan şahıs, ödediği tarihten
itibaren bir sene içinde, umumi hükümler dairesinde mahkemeye başvurarak
paranın geriye alınmasını istiyebilir.

İstirdat davasının şartları:

. *Borç olmayan paranın ödenmiş olması*
. *Paranın icra takibi sırasında ödenmiş olması*
. *Paranın cebri icra tehdidi altında ödenmiş olması*
. *Davanın borcun ödenmesinden itibaren bir sene içinde açılmış olması*

TIP: Bir yıllık süre geçirilirse bile genel hükümlere göre borcun ödenmesinden
itibaren 2 yıl içinde sebepsiz zenginleşme davası açılabilir.

Dava kesin hüküm teşkil eder ama dava sonunda inkar tazminatına hükmedilmez.
İstirdat davasının sonunda tazminata hükmedilmesi söz konusu değildir. Ancak
menfi tespit davası açılmış, bu davada tedbir kararı alınmıl ve bu davanın
sonunda istirdat davası kazanılmış ise borçlu lehine tazminata karar
verilecektir.

Menfi tesbit ve istirdat davaları, takibi yapan icra dairesinin bulunduğu yer
mahkemesinde açılabileceği gibi, davalının yerleşim yeri mahkemesinde de
açılabilir.

Davacı istirdat davasında yalnız paranın verilmesi lazım gelmediğini ispata
mecburdur.

== İCRA TAKİBİNİN İPTALİ VE ERTELENMESİ

=== İTFA

Borçlu takibin kesinleşmesinden sonraki evrede borcu ve ferilerini alacaklıya
öder ve ödediğini noterden tasdikli veya imzası ikrar edilmiş bir belge ile
ispat ederse takibin iptalini icra mahkemesinden her zaman isteyebilir.

Takibin iptali, icra takibinin yapıldığı yerdeki icra mahkemesinden istenir.
Takibin kesinleşmesinden paraların paylaştırılmasına kadar takibin iptali
istenebilir.

=== SÜRE VERİLMESİ

Takibe konu alacağın ödenmesi için alacaklı borçluya süre verebilir. Süre
verilmesi durumunda takibin ertelenmesi için üç şart aranacaktır:

. *Alacaklı tarafından borçluya, borcu ifa için süre verilmiş olmalıdır.*
. *Süre takibin kesinleşmesinden sonra verilmiş olmalıdır.*
. *Borçluya süre verildiği, alacaklı tarafından verilen ve imzası noterlikçe
onaylı veya imzası alacaklı tarafından ikrar edilmiş senetle ispat
edilmelidir.*

Taraflar erteleme konusunda uzlaştıktan sonra alacaklı takibe devam etmeye
kalkışırsa borçlu takibin ertelendiğini ve takibe devam edilmemesi gerektiğini
ileri sürerek icra mahkemesinde dava açabilir.

=== ZAMANAŞIMI

İcra takibinin kesinleşmesinden sonra alacağın zamanaşımına uğraması halinde
borçlu her zaman icra mahkemesine başvurarak takibin geri bırakılmasını
isteyebilir.

Takibin kesinleşmesinden sonra alacağın zamanaşımına uğradığı itirazı süreye
tabi değildir. Buna karşılık zamanaşımı takibin kesinleşmesinden önce dolmuşsa,
zamanaşımı itirazı ödeme emrine itiraz süresi içinde ileri sürülmelidir.

Borçlunun alacağın zamanaşımına uğradığını ispat için özel bir belge sunmasına
gerek yoktur. Hakim dosya üzerinden gerekli incelemeyi yapacaktır. Her takip
işlemi zamanaşımını kestiğinden yapılan son takip işleminin tarihine
bakacaktır.

Eğer alacaklı zamanaşımının durduğunu veya kesildiğini iddia ediyorsa, bunu
ancak resmi belgelerle veya imzası borçlu tarafından ikrar edilen belge ile
ispat edilebilir.

Borçlunun takibin kesinleşmesinden sonra zamanaşımı itirazını ileri sürmesi
halinde İİK 33/a hükmü uygulanır.

"_İlamın zamanaşımına uğradığı veya zamanaşımının kesildiği veya tatile
uğradığı iddiaları icra mahkemesi tarafından resmi vesikalara müsteniden
incelenerek icranın geri bırakılmasına veya devamına karar verilir._

_Alacaklı, icranın geri bırakılması kararının kesinleştiğinin kendisine
tebliğinden sonra, zamanaşımının vakı olmadığını ispat sadedinde ve 7 gün
içinde umumi mahkemelerde dava açabilir. Aksi takdirde icrası istenen ilamın
zamanaşımına uğradığı hususu kesin hüküm teşkil eder._

_İcranın devamına karar verilmesi halinde 33 üncü maddenin son fıkrası burada da
uygulanır._" (İİK 33/a)

"_Borçlu olmadığı parayı ödemek mecburiyetinde kalan borçlunun 72 nci madde
mucibince istirdat davası açarak paranın geriye verilmesini istemek hakkı
saklıdır._" (İİK 33/son)

== MAL BEYANI

*Mal beyanı*, borçlunun gerek kendisinde ve gerek üçüncü şahıslar yedinde
bulunan mal ve alacak ve haklarında borcuna yetecek miktarın nevi ve mahiyet ve
vasıflarını ve her türlü kazanç ve gelirlerini ve yaşayış tarzına göre geçim
membalarını ve buna nazaran borcunu ne suretle ödeyebileceğini yazı ile veya
şifahen icra dairesine bildirmesidir

Borçlu ödeme emrine 7 gün içerisinde itiraz etmediği takdirde mal beyanında
bulunmak zorundadır. Eğer mal beyanında bulunmazsa hapisle tazyik edileceği
ihtar edilir.

İtirazının iptaline veya kat'i veya muvakkat surette kaldırılmasına karar
verilen borçlu, bu kararın kendisine tebliğinden itibaren üç gün içinde
yukarıdaki maddede gösterildiği üzere beyanda bulunmaya mecburdur.

Mal beyanında bulunmıyan borçlu, alacaklının talebi üzerine beyanda bulununcaya
kadar icra mahkemesi hakimi tarafından bir defaya mahsus olmak üzere hapisle
tazyik olunur. Ancak bu hapis üç ayı geçemez.

İcra dairesine vakı olan beyanda malı olmadığını bildirmiş veya borcuna yetecek
mal göstermemiş yahut beyandan imtina etmiş olan borçlu sonradan kazandığı
malları ve kazancında ve gelirinde vukua gelen tezayütleri yedi gün içinde
mezkür daireye taahhütlü mektupla veya şifahi olarak bildirmeğe mecburdur.

"_Bu Kanuna göre istenen beyanı, hakikate aykırı surette yapan kimse,
alacaklının şikâyeti üzerine, üç aydan bir yıla kadar hapis cezası ile
cezalandırılır._

_Hakkında aciz vesikası alınmış borçlu, asgari ücretin üstünde bir geçim
sürdürdüğü, aciz vesikası hamili alacaklının alacağının aciz vesikasına
bağlanmasından en geç beş sene içinde müracaatı üzerine sabit olursa, asgari
ücretin üstünde kalan gelirlerinden icra mahkemesinin dörtte birden az olmamak
üzere tespit edeceği kısmını icra mahkemesi kararının kesinleşmesinden itibaren
en geç bir ay içinde ve aciz vesikasındaki borcun ödenmesine kadar her ay icra
dairesine yatırmaya mecburdur. Bu mükellefiyeti yerine getirmeyen borçlu
hakkında bir yıla kadar tazyik hapsine karar verilir. Hapsin tatbikine
başlandıktan sonra borçlu borcun tamamını veya o tarihe kadar icra veznesine
yatırmak zorunda olduğu meblağı öderse tahliye edilir; ödemelerini tekrar
keserse, hakkında tazyik hapsine yeniden karar verilir. Ancak, bir borçtan
dolayı tazyik hapsinin süresi bir yılı geçemez._"

== HACİZ

Ödeme emrindeki müddet geçtikten ve borçlu itiraz etmiş ise itirazı
kaldırıldıktan sonra mal beyanını beklemeksizin alacaklı haciz konmasını
isteyebilir.

Haciz istemek hakkı, ödeme emrinin tebliği tarihinden itibaren bir sene
geçmekle düşer. İtiraz veya dava halinde bunların vukuundan hükmün
katileşmesine kadar veya alacaklıyla borçlunun icra dairesinde taksit
sözleşmeleri yapmaları halinde taksit sözleşmesinin ihlaline kadar geçen zaman
hesaba katılmaz.

Haciz talebi kanuni müddet içinde yapılmaz veya geri alındıktan sonra bu müddet
içinde yenilenmezse dosya muameleden kaldırılır. Yeniden haciz istemek,
alacaklı tarafından vukubulan yenileme talebinin borçluya tebliğine
mütevakkıftır. İlama müstenit olmayan takiplerde yenileme talebi üzerine
yeniden harc alınır. Yenileme masraf ve harcları borçluya tahmil edilmez.

İcra dairesi talepten nihayet üç gün içinde haczi yapar.

Haczolunacak mallar başka yerde ise haciz yapılmasını malların bulunduğu yerin
icra dairesine hemen yazar. Bu halde hacizle ilgili şikayetler, istinabe olunan
icra dairesinin tabi bulunduğu icra mahkemesince çözümlenir. Resmî sicile
kayıtlı malların haczi, takibin yapıldığı icra dairesince, kaydına işletilmek
suretiyle doğrudan da yapılabilir.

Borçlu haciz sırasında malın bulunduğu yerde bulunmaz ve hemen bulundurulması
mümkün olmazsa haciz, gıyabında yapılır.

Talep vukuunda borçlu kilitli yerleri ve dolapları açmağa vesair eşyayı
göstermeğe mecburdur. Bu yerler icabında zorla açtırılır.

Haczi yapan memur, borçlunun üzerinde para, kıymetli evrak, altın veya gümüş
veya diğer kıymetli şeyleri sakladığını anlar ve borçlu bunları vermekten
kaçınırsa, borçlunun şahsına karşı kuvvet istimal edilebilir.

Taşınır bir malı haciz için mahallinde bir tutanak tutulur. Tutanakta alacaklı
ve borçlunun isim ve şöhretleri, alacağın miktarı, haczin hangi gün ve saatte
yapıldığı, haczedilen mallar ve takdir edilen kıymetleri ve varsa üçüncü
şahısların iddiaları yazılır ve haczi icra eden memur tarafından imza edilir.

Haczi kabil mallar kafi gelmezse veya hiç bulunmazsa bu hal tutanağa
kaydolunur. Haczi kabil mal bulunmazsa haciz tutanağı 143 üncü maddedeki aciz
vesikası hükmündedir.  İcraca takdir edilen kıymete göre haczi kabil malların
kifayetsizliği anlaşıldığı surette dahi tutanak muvakkat aciz vesikası yerine
geçerek alacaklıya 277 nci maddede yazılı hakları verir.

Tutanak tutulurken alacaklı, borçlu veya namlarına Tebligat Kanunu hükümlerine
göre tebellüğe yetkili kimse bulunmazsa, bulunmayan alacaklı veya borçlu üç gün
içinde tutanağı tetkik ve diyeceği varsa söylemesi için icra dairesine davet
olunur. Kanunen ilavesi gereken müddetler mahfuzdur. Haciz sırasında borçlu
veya alacaklı adına Tebligat Kanunu hükümlerine göre tebellüğe yetkili kimse
bulunduğu takdirde haciz tutanağının bir örneği bulunan şahsa verilir. Borçluya
veya alacaklıya ayrıca haber verilmez.

NOTE: Hacizden sonra icra memuru haczedilen malların satışını kendiliğinden
yapamaz. Satış için alcaklının taleptu bulunması gerekir.

=== HACİZ TÜRLERİ

* *Geçici haciz:* İtirazın geçici kaldırılmasından sonra yapılan hacizdir.
* *İhtiyati haciz:* Daha takip başlamadan, dava açılmadan önce borçlunun
malvarlığını elden çıkarmasını önlemek amacıyla yapılan hacizdir.
* *Kesin haciz*

** *Tamamlama haczi:* Satış tutarı bütün alacakları ödemiye yetmezse icra
memuru kendiliğinden yeni hacizler yaparak haczi tamamlar; ancak bu suretle
haczolunan mallar üzerinde sonra gelen derecelerin evvelce koydurdukları
hacizler varsa bu hacizlerin doğurduğu haklara halel gelmez. Yeniden haczedilen
mallar ayrıca satış talebine hacet kalmaksızın ve mümkün olduğu kadar çabuk
satılır.
** *İlave haciz:* İştirak halinde icra dairesi müracaat üzerine aynı derecedeki
alacaklıların bütün alacaklarına yetecek nispette ilave suretiyle hacizler
yapar.

=== HACZEDİLEMEYEN MAL VE HAKLAR

Aşağıdaki şeyler haczolunamaz:

. Devlet malları ile mahsus kanunlarında haczi caiz olmadığı gösterilen mallar,
. Ekonomik faaliyeti, sermayesinden ziyade bedenî çalışmasına dayanan borçlunun
mesleğini sürdürebilmesi için gerekli olan her türlü eşya,
. Para, kıymetli evrak, altın, gümüş, değerli taş, antika veya süs eşyası gibi
kıymetli şeyler hariç olmak üzere, borçlu ve aynı çatı altında yaşayan aile
bireyleri için lüzumlu eşya; aynı amaçla kullanılan eşyanın birden fazla olması
durumunda bunlardan biri,
. Borçlu çiftçi ise kendisinin ve ailesinin geçimi için zaruri olan arazi ve
çift hayvanları ve nakil vasıtaları ve diğer eklenti ve ziraat aletleri;
değilse, sanat ve mesleki için lüzumlu olan alat ve edevat ve kitapları ve
arabacı, kayıkçı, hamal gibi küçük nakliye erbabının geçimlerini temin eden
nakil vasıtaları,
. Borçlu ve ailesinin idareleri için lüzumlu ise borçlunun tercih edeceği bir
süt veren mandası veya ineği veyahut üç keçi veya koyunu ve bunların üç aylık
yem ve yataklıkları,
. Borçlunun ve ailesinin iki aylık yiyecek ve yakacakları ve borçlu çiftçi ise
gelecek mahsül için lazım olan tohumluğu,
. Borçlu bağ, bahçe veya meyva veya sebze yetiştiricisi ise kendisinin ve
ailesinin geçimi için zaruri olan bağ bahçe ve bu sanat için lüzumlu bulunan
alat ve edevat,
+
Geçimi hayvan yetiştirmeye münhasır olan borçlunun kendisi ve ailesinin
maişetleri için zaruri olan miktarı ve bu hayvanların üç aylık yem ve
yataklıkları,
. Borçlar Kanununun 510 uncu maddesi mucibince haczolunmamak üzere tesis
edilmiş olan kaydı hayatla iratlar,
. Memleketin ordu ve zabıta hizmetlerinde malül olanlara bağlanan emeklilik
maaşları ile bu hizmetlerden birinin ifası sebebiyle ailelerine bağlanan
maaşlar ve ordunun hava ve denizaltı mensuplarına verilen uçuş ve dalış
tazminat ve ikramiyeleri,
+
Askeri malüllerle, şehit yetimlerine verilen terfi zammı ve 1485 numaralı kanun
hükmüne göre verilen inhisar beyiye hisseleri,
. Bir muavenet sandığı veya cemiyeti tarafından hastalık, zaruret ve ölüm
gibi hallerde bağlanan maaşlar, ı11. Vücut veya sıhhat üzerine ika edilen
zararlar için tazminat olarak mutazarrırın kendisine veya ailesine toptan veya
irat şeklinde verilen veya verilmesi lazım gelen paralar,
. Borçlunun haline münasip evi,
+
NOTE: Borçlunun haline münasip evi, oturmakta olduğu evdir. Borçlu yalı
dairesinde oturuyorsa tek evi bu olsa bile bu hayatına devam ettirmek için
gerekenin çok üstünde olduğu için o evin satılıp, ev alınacak bir miktar
paranın borçluya verilmesi gerekir.
. Öğrenci bursları.

Medeni Kanunun 807 nci maddesi hükmü saklıdır. 2, 3, 4, 5, 7 ve 12 numaralı
bendlerdeki istisna, borcun bu eşya bedelinden doğmaması haline munhasırdır.

(2), (4), (7) ve (12) numaralı bentlerde sayılan malların kıymetinin fazla
olması durumunda, bedelinden haline münasip bir kısmı, ihtiyacını
karşılayabilmesi amacıyla borçluya bırakılmak üzere haczedilerek satılır.

İcra memuru, haczi talep edilen mal veya hakların haczinin caiz olup olmadığını
değerlendirir ve talebin kabulüne veya reddine karar verir.

Maaşlar, tahsisat ve her nevi ücretler, intifa hakları ve hasılatı, ilama
müstenit olmayan nafakalar, tekaüt maaşları, sigortalar veya tekaüt sandıkları
tarafından tahsis edilen iratlar, borçlu ve ailesinin geçinmeleri için icra
memurunca lüzumlu olarak takdir edilen miktar tenzil edildikten sonra
haczolunabilir. Ancak haczolunacak miktar bunların dörtte birinden az olamaz.
Birden fazla haciz var ise sıraya konur. Sırada önde olan haczin kesintisi
bitmedikçe sonraki haciz için kesintiye geçilemez.

Yukarıda yazılı mal ve hakların haczolunabileceğine dair önceden yapılan
anlaşmalar muteber değildir.

NOTE: Haczedilmezliklere ilişkin şikayet Yargıtay'a göre süresizdir.

=== HACİZDE TERTİP

Haciz yapılırken belirli bir sıraya uyulması gerekir. Buna *hacizde tertip*
denir.

Haczi koyan memur borçlu ile alacaklının menfaatlerini mümkün olduğu kadar
telif etmekle mükelleftir.

Borçlunun kendi yedinde veya üçüncü şahısta olan taşınır mallariyle
taşınmazlarından ve alacak ve haklarından alacaklının ana, faiz ve masraflar da
dahil olmak üzere bütün alacaklarına yetecek miktarı haczolunur.

Borçlu yahut borçlu ile birlikte malı elinde bulunduran şahıslar, taşınır mal
üzerinde üçüncü bir şahsın mülkiyet veya rehin hakkı gibi sınırlı bir ayni
hakkının bulunması veya taşınır malın üçüncü şahıs tarafından haczedilmiş
olması halinde bu hususu haciz yapan memura beyan etmek ve beyanının haciz
tutanağına geçerilmesini talep etmek, haczi yapan memur da borçluyu yahut
borçlu ile birlikte malı elinde bulunduran şahısları bu beyana davet etmek
zorundadır. Bu tür mallar ile üçüncü şahıs tarafından ihtiyaten haciz veya
istihkak iddia edilmiş bulunan malların haczi en sonraya bırakılır.

. *Öncelikle çekişmesiz mallar haczedilir.*

.. _Öncelikle muhafaza ve satılması en kolay ve yokluğu borçlu için en az yük
teşkil edecek taşınır mallar haczedilir._
.. _Daha sonra taşınmazlar haczedilir._

. *Çekişmesiz mallardan sonra, alacaklının alacağına yetecek kadar haciz
yapılamışsa çekişmeli mallar haczedilir.* Çekişmeli mallar haczedilirken bu
durum haciz tutanağına yazılır.

=== TAŞINIRLARIN HACZİ

Haczolunan paraları, banknotları, hamiline ait senetleri, poliçeler ve sair
cirosu kabil senetler ile altın, gümüş ve diğer kıymetli şeyleri icra dairesi
muhafaza eder.

Diğer taşınır mallar, masrafı peşinen alacaklıdan alınarak muhafaza altına
alınır. Alacaklı muvafakat ederse, istenildiği zaman verilmek şartıyla,
muvakkaten borçlu yedinde veya üçüncü şahıs nezdinde bırakılabilir. Üçüncü
şahsın elinde bulunan taşınır mallar haczedildiğinde, üçüncü şahsın kabulü
hâlinde üçüncü şahsa yediemin olarak bırakılır. Mallar satış mahalline
getirilmediği takdirde muhafaza altına alınabilir veya yediemin değişikliği
yapılabilir.

Türkiye’nin taraf olduğu uluslararası andlaşma hükümleri saklı kalmak kaydıyla,
yabancı devlet başkanı, parlamento başkanı, hükümet başkanı veya hükümet
üyelerini taşıyan ulaşım araçları, bu kişiler Türkiye’de bulundukları sürece,
muhafaza altına alınamaz ve yediemine bırakılamaz.

İcra dairesi üçüncü bir şahsa rehnedilmiş olan malları da muhafaza altına
alabilir. Ticari işletme rehni kapsamındaki taşınırlar ise icra dairesince
satılmalarına karar verilmesinden sonra muhafaza altına alınabilir. Bu mallar
paraya çevrilmediği takdirde geri verilir.

=== ANONİM ŞİRKET PAYININ HACZİ

Anonim şirketlerde paylar için pay senedi veya pay ilmühaberi çıkarılmamışsa,
borçlunun şirketteki payı icra dairesi tarafından şirkete tebliğ olunarak
haczedilir. Bu haczin şirket pay defterine işlenmesi zorunludur; ancak haciz,
şirket pay defterine işlenmemiş olsa bile şirkete tebliğ tarihinde yapılmış
sayılır. Haciz, icra dairesi tarafından tescil edilmek üzere Ticaret Siciline
bildirilir. Bu durumda haczedilen payların devri, alacaklının haklarını ihlâl
ettiği oranda batıldır. Haczedilen payların satışı, taşınır malların satışı
usulüne tâbidir.

=== HAKLARIN HACZİ

Bir intıfa hakkı veya taksim edilmemiş bir miras veya bir şirket yahut iştirak
halinde tasarruf edilen bir mal hissesi haczedilirse icra dairesi, yerleşim
yerleri bilinen ilgili üçüncü şahıslara keyfiyeti ihbar eder. Bu suretle
borçlunun muayyen bir taşınmazdaki tasfiye sonundaki hissesi haczedilmiş olursa
icra memuru haciz şerhinin taşınmazın kaydına işlenmesi için tapu sicil
muhafızlığına tebligat yapar.

Borçlunun reddetmediği miras veya başka bir sebeple iktisap eyleyip henüz
tapuya veya gemi siciline tescil ettirmediği mülkiyet veya diğer aynı hakların
borçlu namına tescili alacaklı tarafından istenebilir. Bu talep üzerine icra
dairesi alacaklının bu muameleyi takip edebileceğini tapu veya gemi sicili
dairesine ve icabında mahkemeye bildirir.

Borçlunun zilyed bulunduğu bir taşınmaz üzerindeki fevkalade zamanaşımı ile
iktisabını istemek hakkının haczedilmesi halinde, icra dairesi zilyedliğin
başkasına devrine mani olacak tedbirleri alır ve alacaklıya bir ay içinde
taşınmazın borçlusu adına tescili için dava açması yetkisini verir. Mahkemenin
tescil kararı ile taşınmaz bu alacaklı lehine mahcuz sayılır.

Alacaklının bu sebeple yapacağı kanuni masraflar ayrıca takip ve hükme hacet
kalmaksızın dairece borçludan tahsil olunur.

=== BORÇLUNUN ÜÇÜNCÜ KİŞİLERDEKİ MAL VE ALACAKLARININ HACZİ

Hamiline ait olmıyan veya cirosu kabil bir senetle müstenit bulunmıyan alacak
veya sair bir talep hakkı veya borçlunun üçüncü şahıs elindeki taşınır bir malı
haczedilirse icra memuru; borçlu olan hakiki veya hükmi şahsa bundan böyle
borcunu ancak icra dairesine ödiyebileceğini ve takip borçlusuna yapılan
ödemenin muteber olmadığını veya malı elinde bulunduran üçüncü şahsa bundan
böyle taşınır malı ancak icra dairesine teslim edebileceğini, malı takip
borçlusuna vermemesini, aksi takdirde malın bedelini icra dairesine ödemek
zorunda kalacağını bildirir (Haciz ihbarnamesi).Bu haciz ihbarnamesinde, ayrıca
2, 3 ve 4 üncü fıkra hükümleri de üçüncü şahsa bildirilir.

Üçüncü şahıs; borcu olmadığı veya malın yedinde bulunmadığı veya haciz
ihbarnamesinin tebliğinden önce borç ödenmiş veya mal istihlak edilmiş veya
kusuru olmaksızın telef olmuş veya malın borçluya ait olmadığı veya malın
kendisine rehnedilmiş olduğu veya alacak borçluya veya emrettiği yere verilmiş
olduğu gibi bir iddiada ise, keyfiyeti, haciz ihbarnamesinin kendisine
tebliğinden itibaren yedi gün içinde icra dairesine yazılı veya sözlü olarak
bildirmeye mecburdur.

Üçüncü şahıs, haciz ihbarnamesinin kendisine tebliğinden itibaren yedi gün
içinde itiraz etmezse, mal yedinde veya borç zimmetinde sayılır ve kendisine
gönderilen haciz ihbarnamesine süresinde itiraz etmediği, bu nedenle de malın
yedinde veya borcun zimmetinde sayıldığı ikinci bir ihbarname ile bildirilir.
Bu ikinci ihbarnamede ayrıca, üçüncü şahsın ihbarnamenin kendisine tebliğinden
itibaren yedi gün içinde yukarıda belirtilen sebeplerle itirazda bulunması,
itirazda bulunmadığı takdirde zimmetinde sayılan borcu icra dairesine ödemesi
veya yedinde sayılan malı icra dairesine teslim etmesi istenir.

İkinci ihbarnameye süresi içinde itiraz etmeyen ve zimmetinde sayılan borcu
icra dairesine ödemeyen veya yedinde sayılan malı icra dairesine teslim etmeyen
üçüncü şahsa onbeş gün içinde parayı icra dairesine ödemesi veya yedinde
sayılan malı teslim etmesi yahut bu süre içinde menfi tespit davası açması,
aksi takdirde zimmetinde sayılan borcu ödemeye veya yedinde sayılan malı
teslime zorlanacağı bildirilir.

Bu bildirimi alan üçüncü şahıs, icra takibinin yapıldığı veya yerleşim yerinin
bulunduğu yer mahkemesinde süresi içinde menfi tespit davası açtığına dair
belgeyi bildirimin yapıldığı tarihten itibaren yirmi gün içinde ilgili icra
dairesine teslim ettiği takdirde, hakkında yürütülen cebri icra işlemleri menfi
tespit davası sonunda verilen kararın kesinleşmesine kadar durur. Bu süre
içinde 106 ncı maddede belirtilen süreler işlemez. Bu davada üçüncü şahıs,
takip borçlusuna borçlu olmadığını veya malın takip borçlusuna ait olmadığını
ispat etmeye mecburdur.

Üçüncü şahıs açtığı bu davayı kaybederse, mahkemece, dava konusu şeyin yüzde
yirmisinden aşağı olmamak üzere bir tazminata mahkûm edilir.

Üçüncü şahıs, haciz ihbarnamesine müddeti içinde itiraz ederse, alacaklı,
üçüncü şahsın verdiği cevabın aksini icra mahkemesinde ispat ederek üçüncü
şahsın 338 inci maddenin 1 inci fıkrası hükmüne göre cezalandırılmasını ve
ayrıca tazminata mahküm edilmesini istiyebilir. İcra mahkemesi, tazminat
hakkındaki davayı genel hükümlere göre halleder.

Üçüncü şahıs, kusuru olmaksızın bir mani sebebiyle müddeti içinde haciz
ihbarnamesine itiraz etmediği takdirde 65 inci madde hükmü uygulanır. Her hâlde
üçüncü şahıs, borçlu ile kötü niyetli alacaklıya karşı dava açarak ödemek
zorunda kaldığı paranın veya teslim ettiği malın iadesini isteyebilir.

Malın teslimi mümkün olmazsa, alacaklı icra mahkemesine müracaatla değerini
üçüncü şahsa ödetmek hakkını haizdir.

Haciz ihbarnamesi, borçlunun hak ve alacaklarının bulunabileceği bir tüzel
kişinin veya müessesenin şubesine veya tüm şubelerini kapsayacak şekilde
merkezine tebliğ edilir. Haciz ihbarnamesinin tebliğ edildiği merkez, tüm
şubeleri veya birimlerini kapsayacak şekilde beyanda bulunmakla yükümlüdür.

=== HACZE ADİ İŞTİRAK

İlk haciz üzerine satılan malın tutarı vezneye girinciye kadar aynı derecede
hacze iştirak edebilecek alacaklılar:

. İlk haciz ilamsız takibe müstenitse takip talebinden ve ilama istinat
ediyorsa dava ikamesinden mukaddem yapılmış bir takip üzerine alınan aciz
vesikasına,
. Yukarıdaki fıkrada yazılı tarihlerden önce açılmış bir dava üzerine alınan
ilama,
. Aynı tarihlerden mukaddem tarihli resmi veya tarih ve imzası tasdikli bir
senede,
. Aynı tarihlerden mukaddem tarihli resmi dairelerin veya yetkili makamların
yetkileri dahilinde ve usulüne göre verdikleri makbuz veya vesikaya

istinat eden alacaklılardır.

Bunların haricindeki alacaklılar ancak, evvelki dereceden artacak bedeller için
hacze iştirak edebilirler.

Bu suretle iştirak halinde icra dairesi müracaat üzerine aynı derecedeki
alacaklıların bütün alacaklarına yetecek nispette ilave suretiyle hacizler
yapar.

CAUTION: Ücret haczinde iştirak olmaz.

Hacze adi iştirakin şartları:

. *Takip yapmış olma*
. *Öncelik*
. *Belge ile ispat*

TIP: Hacze iştirak edilip edilemeyceğinin anlaşılması için ilk haciz uygulayan
alacaklının takip tarihine bakılması gerekir. Eğer ilamlı takip söz konusu ise
dava açtığı tarih esas alınır. Kişinin alacağı bu tarihten önce doğmuş ve yine
bu tarihten önce bir takip başlatılmışsa hacze iştirak edebilir.

Kişinin hacze iştirak talebi reddedilirse şikayet yoluna başvurabilir.

=== HACZE İMTİYAZLI İŞTİRAK

Borçlunun eşi ve çocukları ve vasi veya kayyımı olduğu şahıslar evlenme,
velayet veya vesayetten mütevellit alacaklar için önce icrası lazım gelen takip
merasimine lüzum olmaksızın ilk haciz üzerine satılan malın tutarı vezneye
girinceye kadar aynı derecede hacze iştirak edebilirler. Şu kadar ki bu hak
ancak haciz, vesayetin veya velayetin veya evliliğin devamı esnasında veya
zevalini takip eden sene içinde yapıldığı takdirde istimal olunabilir.

Bir dava veya takibin devam ettiği müddet hesaba katılmaz.

Borçlunun reşit çocukları Medeni Kanunun 321 inci maddesine müstenit
alacaklarından dolayı önce icrası lazım gelen takip merasimine hacet
kalmaksızın her zaman aynı derecede hacze iştirak edebilirler.

Sulh mahkemesi dahi küçükler, vesayet altında bulunanlar veya kendilerine
kayyım tayin edilmiş olanlar namına aynı suretle hacze iştirak edebilirler.

İcra dairesi iştirak taleplerini borçlu ve alacaklılara bildirir.Onlara, itiraz
etmeleri için yedi günlük bir mühlet verir. İtiraz halinde iştirak talebinde
bulunan kimsenin hacze iştiraki muvakkaten kabul olunur ve yedi gün içinde dava
açması lüzumu bildirilir. Bu süre içinde dava açmazsa iştirak hakkı düşer.
Açılacak davaya basit yargılama usulüne göre bakılır.

Nafaka ilamına istinat eden alacaklı önce takip merasiminin icrasına lüzum
olmaksızın her zaman aynı derecede hacze iştirak edebilir. Kötü niyet hali
müstesnadır.

TIP: Nafaka çok yüksekse diğer alacaklılar hacze iştirak edilmesine karşı
koyabilir.

=== HACİZDE İSTİHKAK PROSEDÜRÜ

İstihkak prosedürünün amacı malların gerçekte kime ait olduğunu tespit etmek
değil, haczedilen mal üzerindeki somut uyuşmazlığın sadece o takip bakımından
çözülmesidir. *İstihkak davası, takip hukukuna ilişkin özel bir davadır. Bu
dava ile amaçlanan o takip bakımından mala uygulanan haczin yerine olup
olmadığının tespitidir.*

==== HACİZLİ MALIN BORÇLUNUN VEYA BORÇLU İLE BİRLİKTE ÜÇÜNCÜ KİŞİNİN ELİNDE OLMASI

Borçlunun elinden bulunan bir mal haczedilirken, borçlu veya üçüncü kişi
tarafından malın üçüncü kişiye ait olduğu ileri sürülürse, icra müdürü bu
iddiayı tutanağa geçirir.

Bir malın haczedildiğini öğrenen borçlu veya üçüncü kişi haczi öğrendiği
tarihten itibaren *7 gün içinde* istihkak iddiasında bulunabilir. Bu iddiada
bulunulmazsa aynı takipte bir daha ileri sürülemez.

İddianın üçüncü kişi tarafından ileri sürülmesi halinde icra müdürü bunu borçlu
ve alacaklıya bildirir. Eğer alacaklı veya borçlu üçüncü kişinin iddiasını
itiraz etmezse istihkak iddiasını kabul edilmiş sayılır ve o mallar bakımından
haciz son bulur.

Alacaklı veya borçlu istihkak iddiasına itiraz ederse icra müdürü kendisi karar
veremez ve dosyayı icra mahkemesine gönderir. İcra mahkemesi öncelikle takibin
ertelenip ertelenmeyeceğine karar verir. *Bu erteleme sadece istihkak iddia
edilen mal içindir.* Eğer takibin ertelenmesine karar verilirse doğabilecek
zararların karşılanması amacıyla bir teminat yatırılmasına karar verilir. Bu
teminat bakımından takdir icra mahkemesine aittir.

İcra mahkemesinin takibin ertelenmesine veya devamına dair kararı kesindir.

Üçüncü kişi, takibin ertelenmesi veya devamına ilişkin icra mahkemesi kararının
kendisine *tefhim veya tebliğ tarihinden itibaren 7 gün içinde* aynı mercide
istihkak davası açabilir.

NOTE: Bu aşamaya kadar üçüncü kişiye istihkak iddiasına bulunma imkanı
verilmemişse, üçüncü kişi *haczi öğrendiği tarihten itibaren 7 gün içinde*
haczedilmiş mal satılıp, bedeli alacaklıya ödeninceye kadar istihkak davası
açabilir. Mal satılmışsa dava, mal bedeli üzerinden yürütülür. Mal satılıp
bedeli alacaklıya ödenmişse üçüncü kişi ancak borçluya karşı sebepsiz
zenginleşme davası açabilir.

Üçüncü kişi süresi içinde istihkak davası açmazsa, iddiasından vazgeçmiş
sayılır. Fakat bu borçluya karşı sebepsiz zenginleşmeden doğan taleplerini
engellemez.

İstihkak davasının davacısı üçüncü kişi, davalısı ise alacaklıdır. İstihkak
iddiasına borçlu itiraz etmişse, borçlu da davalı olabilir. İstihkak davası
icra mahkemelerinde, genel hükümlere göre ve basit yargılama usulü ile görülür.

İstihkak davacısı üçüncü kişi, malı ne surette iktisap ettiğini ve malın
borçlunun elinde bulunmasını gerektiren hukuki ve fiili sebep ve olayları
göstermek ve bunları ispat etmekle yükümlüdür.

Borçlu ile birlikte oturulan yerlerdeki mallardan mahiyetleri gereği kadın,
erkek ve çocuklara ait olduğu açıkça anlaşılan veya örf, adet, sanat, meslek,
meşgale icabı olanlar bu kişilerin farz olunur. Bunun aksini iddia eden ispat
etmelidir. Böyle bir malın haczedilmesine karşı şikayet yoluna başvurulabilir.
Fakat şikayet prosedürü ile istihkak prosedürü birleştirilemez.

Borçlunun üçüncü kişinin iddiasını kabul etmesi alacaklıyı etkilemez. Borçlunun
ikrarına rağmen üçüncü kişi iddiasını ispat etmelidir. Yapılmış olan bu ikrarın
sonucu borçlu ile üçüncü kişi arasındaki meseleyi etkiler.

Bir görüşe göre istihkak davası sonunda icra mahkemesi tarafından verilen hüküm
maddi anlamda kesin hüküm teşkil eder. Diğer bir görüşe göre ise bu karar
sadece takip hukuku bakımından sonuç doğurur ve kesin hüküm teşkil etmez.

Dava devam ederken haciz kalkarsa dava konusuz kalır.

İcra mahkemesinin kararına karşı istinaf kanun yoluna başvurulabilir.

İstihkak davasının reddedilmesi halinde, daha önce takibin ertelenmesine karar
verilmişse ve bu karar dolayısıyla alacaklının bir zararı varsa üçüncü kişi
aleyhine istifası geciken miktarın %20'sinden az olmamak kaydıyla tazminata
hükmedilir. Daha önce teminat yatırılmışsa bu teminattan karşılanır. Tazminata
hükmedilmesi için talebe ihtiyaç yoktur.

TIP: İcra mahkemesince tazminata hükmedilmemiş olsa bile genel hükümler
çerçevesinde zararın tazmini talep edilebilir.

İstihkak davasının kabul edilmesi halinde söz konusu mal üzerindeki haciz
kalkar. İtiraz eden alacaklı veya borçlunun kötü niyetli olduğu tespit
edilirse, malın değerinin %15'inden az olmamak üzere tazminata hükmolunur.
Burada da talep olmasa da tazminata hükmedilir.

TIP: Malı haksız yere haczedilen üçüncü kişi, bu yüzden doğan gerçek zararının
tazminini genel hükümler çerçevesinde de talep edebilir.

==== HACİZLİ MALIN ÜÇÜNCÜ KİŞİNİN ELİNDE BULUNMASI

Malın üçüncü kişinin elinde bulunduğu durumlarda mal karinesi tersine işler ve
mal üçüncü kişinin sayılır. Bu durumda istihkak prosedürü alacaklı tarafından
başlatılmalıdır.

Alacaklı 7 günlük süre içerisinde üçüncü kişiye karşı istihkak davası
açmalıdır. Bu dava açıldığı takdirde dava sonuna kadar haczedilen malların
satışı yapılmaz.

Bu davada tazminata dair hükümler dışında yukarıdaki prosedür izlenecektir.

== BORCUN TAKSİTLE ÖDENMESİ

Borcun taksitle ödenmesi sözleşmesi, hacizden önce iki şekilde yapılabilir:

. Borçlu ve alacaklı taksit sözleşmesi yapar ve tutanağa geçirilir. Bu
sözleşmede borçlu, alacaklı ve icra müdürünün imzası bulunmalıdır.
. Borçlu taksitle ödeme talebini icra müdürüne bildirir ve bu talep alacaklıya
iletilir. Alacaklı kabul ederse sözleşme yapılır.

IMPORTANT: Hacizden önce taksitle ödeme sözleşmesi bakımından alacaklının
rızasının alınması mecburidir.

Sözleşmede taksitle ödenecek miktarların ve taksit sayısının açıkça belirtilmiş
olması gerekir.

NOTE: Hacizden önce böyle bir taksit sözleşmesi yapılırsa haciz isteme süresi
işlemez.

[caption=""]
.İİK 111 - Taksitle ödeme
====
Borçlu alacaklının satış talebinden evvel borcunu muntazam taksitlerle ödemeği
taahüt eder ve birinci taksiti de derhal verirse icra muamelesi durur.

Şukadar ki borçlunun kafi miktar malı haczedilmiş bulunması ve her taksitin
borcun dörtte biri miktarından aşağı olmaması ve nihayet aydan aya verilmesi ve
müddetin üç aydan fazla olmaması şarttır.

Borçlu ile alacaklının borcun taksitlendirilmesi için icra dairesinde
yapacakları sözleşme veya sözleşmelerin devamı süresince 106 ve 150/e
maddelerindeki süreler işlemez. Ancak bu sözleşme veya sözleşmelerin toplam
süresinin on yılı aşması hâlinde, aştığı tarihten itibaren süreler kaldığı
yerden işlemeye başlar.

Taksitlerden biri zamanında verilmezse icra muamelesi ve süreler kaldığı yerden
devam eder.
====

Hacizden sonra taksitle ödeme halinde, borçlu İİK 111'deki şartları taşıyan bir
taksitle ödeme planı sunarsa alacaklı bunu kabul etmek *zorundadır*. Borçlu bu
şartları taşımayan bir plan da sunabilir, alacaklı bu halde kabul etmek zorunda
değildir.

== HACZEDİLEN MALLARIN SATIŞI

Malların haczinden sonra, satışın yapılabilmesi için alacaklının satış
talebinde bulunması gerekir. Sadece talepte bulunmak yetmez, satış
masraflarının da ödenmesi gerekir. Alacaklı talep etmeden borçlunun talebiyle
de satış yapılabilir.

NOTE: İstisnai hallerde, malların bozulması söz konusu ise icra müdürü talep
olmadan da satışı yapabilir.

Hacizli taşınır mallar için satışı talep süresi heczin kesinleşmesinden
itibaren 6 aydır. Taşınmazlar bakımından ise 1 yıl içerisinde satış talebinde
bulunulmalıdır.

TIP: Hacizden sonra istihkak davası açılmışsa, bu davanın görülmesi ve
sonuçlanmasına kadar geçen süre bu sürelerin içinde hesaba katılmayacaktır.

Satış talep süresi içinde satış istenmezse, mallar üzerindeki haciz kalkar ama
takip durmaya devam eder. Alacaklı tekrar haciz ve satış isteyebilir.

=== TAŞINIR MALLARIN SATIŞI

Taşınır mallar satış talebinden nihayet iki ay içinde satılır. Bu süre
düzenleyicidir.

Satış açık artırma ile yapılır. Birinci ve ikinci artırmanın yapılacağı yer,
gün ve saat daha önceden ilân edilir. İlanın şekli, malın değerine, en doğru
şekilde nasıl satılacağına göre belirlenir.

NOTE: İlanın yanlış yazılması ve satışın yapılması ihalenin feshi sebebi
olabilir.

Taşınırlar için mutlaka gazeteyle ilan şartı yoktur. El ilanı vs. ile de
yapılabilir.

Açık artırmaya elektronik ortamda teklif verme yoluyla başlanır. Elektronik
ortamda teklif verme, birinci ihale tarihinden on gün önce başlar, ihalenin
tamamlanacağı günden önceki gün sonunda sona erer; ikinci ihalede ise
elektronik ortamda teklif verme birinci ihaleden sonraki beşinci gün başlar, en
az on gün sonrası için belirlenecek ikinci ihalenin tamamlanacağı günden önceki
gün sonunda sona erer.

Elektronik ortamda verilecek teklifler haczedilen malın tahmin edilen
kıymetinin yüzde ellisinden az olamaz; teklif vermeden önce, haczedilen malın
tahmin edilen kıymetinin yüzde yirmisi nispetinde teminat gösterilmesi
zorunludur.

Birinci ve ikinci ihale icra memuru tarafından, ilanda belirlenen yer, gün ve
saatte, elektronik ortamda verilen en yüksek teklif üzerinden başlatılır.

Satışa çıkarılan mal üç defa bağırıldıktan sonra, elektronik ortamda verilen en
yüksek teklif de değerlendirilerek, en çok artırana ihale edilir. Şu kadar ki,
artırma bedelinin malın tahmin edilen bedelinin yüzde ellisini bulması ve satış
isteyenin alacağına rüçhanı olan diğer alacaklar o malla temin edilmişse bu
suretle rüçhanı olan alacakların mecmuundan fazla olması ve bundan başka paraya
çevirme ve paraların paylaştırılması masraflarını aşması gerekir.

Birinci ihalede, alıcı çıkmazsa veya bu maddede yazılı miktara ulaşılmazsa
satış icra memuru tarafından geri bırakılır.

İkinci ihalede, alıcı çıkmazsa veya bu maddede yazılı şartlar gerçekleşmezse
satış talebi düşer.

Altın ve gümüş eşya maden halindeki kıymetlerinden daha aşağı bir bedel ile
satılamaz.

Satış peşin para ile yapılır. Ancak icra memuru müşteriye yedi günü geçmemek
üzere bir mühlet verebilir.

Satılan mal ihale kesinleşmeden teslim olunmaz.

İhaleye katılıp daha sonra ihale bedelini yatırmamak suretiyle ihalenin feshine
sebep olan tüm alıcılar ve kefilleri, teklif ettikleri bedel ile son ihale
bedeli arasındaki farktan ve diğer zararlardan ve ayrıca temerrüt faizinden
müteselsilen sorumludurlar. İhale farkı ve temerrüt faizi ayrıca hükme hacet
kalmaksızın dairece tahsil olunur. Bu fark, varsa öncelikle teminat bedelinden
tahsil olunur.

Aşağıdaki hallerde satış pazarlık suretiyle yapılabilir:

. Bütün alakadarlar isterse,
. Borsa veya piyasada fiyatı bulunan kıymetli evrak veya diğer mallar için o
günün piyasasında mukarrer fiyat teklif edilirse,
. Artırmada maden kıymetini bulmamış olan altın ve gümüş eşyaya bu kıymet
verilirse,
. 113 üncü maddenin ikinci fıkrasında gösterilen haller bulunursa,
. Mahcuz malın tahmin edilen değeri 3.230 lirayı geçmezse.

== TAŞINMAZ MALLARIN SATILMASI

Taşınmazlar, satış talebinden itibaren 3 ay içinde icra dairesi tarafından açık
artırma ile satılır. 3 aylık bu süre düzenleyici süredir.

CAUTION: Taşınmazlar pazarlık suretiyle satılamaz.

Satış talebi ile birlikte icra memuru, tapu idaresinden taşınmaz üzerindeki
hakları öğrenerek bir mükellefiyetler listesi hazırlar. İhale gerçekleşip satış
yapıldığında alıcı, taşınmazı mükellefiyetler listesindeki haklar ve külfetler
ile birlikte almış olur.

IMPORTANT: Tapuda kayıtlı olduğu halde mükellefiyetler listesinde yazılı
olmayan bir şey, ihale yoluyla taşınmazı satın alan bakımından bağlayıcı
değildir.

Alıcı, mükellefiyetler listesindeki durum ile tapudaki durumun uyuşmaması
sebebiyle zarar görürse devletin sorumluluğuna gidebilir.

Satış, açık artırma ile yapılır. Birinci ve ikinci ihalenin yapılacağı yer, gün
ve saat önceden ilan edilir. Bu ilan metninin ilgililere tebliğ edilmesi
gerekir. *Şikayet süresi tebliğden itibaren başlamaktadır*. Tapudaki kayıtlı
adrese yapılan tebligat geçerli sayılacaktır.

Alacaklı veya borçlu tebliğ tarihinden itibaren 3 gün içerisinde şikayet yoluna
başvurarak mükellefiyetler listesinde yazılı olmayan haklarını listeye
yazdırabilir. Bu istihkak prosedürü içinde çözülecektir.

Bir kişinin artırmaya katılıp pey ileri sürebilmesi için, taşınmazın değerinin
%20'si oranında teminat göstermesi gerekmektedir.

=== KIYMET TAKDİRİ

Kıymet takdirinin tebliğ edildiği ilgililer, raporun tebliğinden itibaren *yedi
gün içinde* raporu düzenleten icra dairesinin bulunduğu icra mahkemesinde
şikayette bulunabilirler.

Şikayet tarihinden itibaren *yedi gün içinde* gerekli masraf ve ücretin mahkeme
veznesine yatırılması halinde yeniden bilirkişi incelemesi yaptırılabilir; aksi
halde başka bir işleme gerek olmaksızın şikayet kesin olarak reddedilir.

*Kesinleşen kıymet takdirinin yapıldığı tarihten itibaren iki yıl geçmedikçe
yeniden kıymet takdiri istenemez.* Ancak, doğal afetler ve imar durumundaki
çok önemli değişiklikler meydana getiren benzer hallerde yeniden kıymet takdiri
istenebilir.

Kıymet takdirine ilişkin şikayet yetkisiz icra mahkemesine yapılırsa, icra
mahkemesi evrak üzerinde inceleme yaparak başvuru tarihinden itibaren en geç on
gün içinde yetkisizlik kararı verir. Mahkemenin verdiği bu karar kesindir.

=== İHALE

Birinci ve ikinci ihale icra memuru tarafından, ilanda belirlenen yer, gün ve
saatte, elektronik ortamda verilen en yüksek teklif üzerinden başlatılır.

Taşınmaz üç defa bağırıldıktan sonra, elektronik ortamda verilen en yüksek
teklif de değerlendirilerek, en çok artırana ihale edilir.

Artırma bedelinin, malın tahmin edilen bedelinin yüzde ellisini bulması ve
satış isteyenin alacağına rüçhanı olan diğer alacaklar o malla temin edilmişse
bu suretle rüçhanı olan alacakların toplamından fazla olması ve bundan başka
paraya çevirme ve paraların paylaştırılması masraflarını aşması gerekir.

Birinci ihalede alıcı çıkmaz veya aranan miktara ulaşılmazsa satış icra memuru
tarafından geri bırakılır.

İkinci ihalede alıcı çıkmazsa veya aranan miktara ulaşılmazsa satış talebi
düşer.

=== ÖDEME USULÜ

Satış bedeli peşin ödenir. Anca icra memuru alıcıya on günü geçmemek üzere bir
süre verebilir.

Satış bedelinin ödenmesi için süre verilmişse para verilinceya kadar hasar ve
masrafı müşteriye ait olmak üzere taşınmaz, icra dairesi tarafından idare
olunur. Bu müddet içinde icra dairesinin izni olmadan tapuca hiç bir tescil
yapılamaz.

İcra dairesi, satış bedelini temin için ayrıca teminat gösterilmesini
isteyebilir.

İhaleye katılıp daha sonra ihale bedelini yatırmamak suretiyle
ihalenin feshine sebep olan tüm alıcılar ve kefilleri teklif ettikleri
bedel ile son ihale bedeli arasındaki farktan ve diğer zararlardan ve ayrıca
temerrüt faizinden müteselsilen sorumludurlar. İhale farklı ve temerrüt
faizi ayrıca hükme gerek olmaksızın dairece tahsil olunur. Bu fark, varsa
öncelikle teminat bedelinden tahsil olunur.

Taşınmaz kendisine ihale olunan kimse derhal veya verilen süre içinde parayı
vermezse, ihale kararı icra memuru tarafından kaldırılarak teminat akçesi
alıcının yukarıdaki hüküm gereğince sorumlu bulunduğu miktara mahsup edilmek
üzere alıkonulur.

Kendisinden evvel en yüksek teklifte bulunan kimsenin ileri sürdüğü pey, ihale
için aranan şartlara bulunması ve bu kimsenin adresinin de biliniyor olması
halinde teklif ettiği bedel ile taşınmaz kendisine teklif edilir ve üç gün
içinde almaya razı olursa ona ihale olunur.

Böyle bir kişi bulunmaz, bulunsa da razı olmaz ya da teklifi cevapsız bırakırsa
taşınmaz icra dairesince hemen artırmaya çıkarılır. Bu artırma ilgililere
tebliğ edilmeyip yalnızca satıştan en az yedi gün önce yapılacak ilanla
yetinilir. Bu artırmada, teklifin ihale için aranan şartlara uygun olması
şartıyla taşınmaz en çok artırana ihale olunur.

TIP: Ancak birinci artırma sonunda ihale yapılmış ve alıcı ödememişse
yukarıdaki usul işletilip yeniden artırma yapılabilir. Aynı taşınmaz için üç
kere artırma yapılamaz.

=== İHALENİN FESHİ

İcra dairesi tarafından taşınmaz kendisine ihale edilen alıcı o taşınmazın
mülkiyetini iktisap etmiş olur. İhale kesinleşinceye kadar taşınmazın ne
şekilde muhafaza ve idare edileceği icra dairesi tarafından kararlaştırılır.

İhalenin feshini, yalnız satış isteyen alacaklı, borçlu, tapu sicilindeki
ilgililer ve pey sürmek suretiyle ihaleye iştirak edenler, yurt içinde bir
adres göstermek koşuluyla icra mahkemesinden şikayet yolu ile ihale tarihinden
itibaren *yedi gün içinde* isteyebilirler.

İlgililerin ihale yapıldığı ana kadar cereyan eden muamelelerdeki yolsuzlukları
en geç ihale günü öğrendikleri kabul edilir ve bunlardan dolayı ihalenin feshi
ihale tarihinden itibaren *yedi gün içinde* istenebilir. Sonradan ihaleye fesah
karıştırıldığının öğrenilmesi ya da alıcının malın vasıflarında sonradan hataya
düştüğünü öğrenmesi halinde ihale tarihinden itibaren *bir yıl içinde* fesih
talep edilebilir.

İhale tarihinden en fazla bir yıl içinde ihalenin feshinin istenebileceği özel
durumlar:

.. Satış ilanının tebliğ edilmemiş olması
.. Satılan malın esaslı vasıflarında hataya düşülmüş olması
.. İhaleye fesat karıştırıldığının sonradan öğrenilmesi

İhalenin feshi talebi üzerine icra mahkemesi talep tarihinden itibaren yirmi
gün içinde duruşma yapar ve taraflar gelmeseler bile icap eden kararı verir.

Talebin reddine karar verilmesi halinde icra mahkemesi davacıyı feshi istenilen
ihale bedelinin yüzde onu oranında para cezasına mahkum eder. Ancak işin
esasına girilmemesi nedeniyle talebin reddi halinde para cezasına hükmolunamaz.

İhalenin feshine ilişkin şikayet görevsiz veya yetkisiz icra mahkemesi veya
mahkemeye yapılırsa, icra mahkemesi veya mahkeme evrak üzerinde inceleme
yaparak başvuru tarihinden itibaren en geç on gün içinde görevsizlik veya
yetkisizlik kararı verir. Bu kararlar kesindir.

IMPORTANT: İhalenin feshinin reddi kararı, Yargıtay tarafından kesin hüküm
olarak kabul edilmektedir.

İcra mahkemesinin dosya üzerinden, duruşma yapmadan karar verebilme imkanı
yoktur. Yargıtay'a göre ilgisi olan herkes burada taraftır.

Mahkeme ihalenin feshi talebini kabul ederse:

. İhale kalkar.
. Mülkiyet borçluya geri döner.
. İhale bedeli alıcıya iade edilir.
. _İhalenin feshi süresince icra dairesi ihale bedelini nemalandırır._

=== TAŞINMAZIN TESCİLİ

Taşınmaz alıcıya ihale edilip bedeli alındıktan sonra alıcı namına tescil
edilmesi için tapuya müzekkere yazılır.

Taşınmaz borçlu tarafından veya hacizden evvelki bir tarihte yapıldığı resmi
bir belge ile belgelenmiş bir akte dayanmayarak başkaları tarafından işgal
edilmekte ise onbeş gün içinde tahliyesi için borçluya veya işgal edene bir
tehliye emri tebliğ edilir. Bu müddet içinde tahliye edilmezse zorla çıkarılıp
taşınmaz alıcıya teslim olunur.

== PARALARIN PAYLAŞTIRILMASI

Mahcuz (hacizli) mallar tamamen satıldıktan sonra bedelleri ilgililere
hisselerine göre paylaştırılır.

Malların bir kısmı satılabildiyse, durum gerektiriyorsa, bedelleri hisselerine
göre ilgililere *avans* olarak dağıtılır.

Haciz, paraya çevirme ve paylaştırma gibi bütün alacaklıları ilgilendiren
masraflar önce satış tutarından alınır ve artan para takip masrafları ve
işlemiş faizler dahil olduğu halde alacakları oranında paylaştırılır.

Satış tutarı bütün alacakları ödemeye yetmezse icra memuru kendiliğinden yeni
hacizler yaparak haczi tamamlar; ancak bu suretle haczolunan mallar üzerinde
sonra gelen derecelerin evvelce koydurdukları hacizler varsa bu hacizlerin
doğurduğu haklara halel gelmez. Yeniden haczedilen mallar ayrıca satış
talebine hacet kalmaksızın ve mümkün olduğu kadar çabuk satılır.

Toplam elde edilen paranın tüm alacaklılara yetmemesi halinde *sıra cetveli*
düzenlenir. Sıra cetvelinde alacaklar sıraya konulur. Birinci sıradaki
alacakların tamamı tahsil edilmeden ikinci sıraya geçilmez.

Sıra cetvelinin düzenlenmesi için:

. Borçlunun birden fazla alacaklısı olmalıdır.
. Borçlunun mallarının satılmasıyla elde edilen para, alacaklıları tatmin
etmemelidir.

TIP: Mal üzerinde birden fazla haciz olması halinde, Yargıtay'a göre ilk haczi
koyan icra dairesi sıra cetvelini de hazırlayacaktır.

Sıra cetvelinin bir sureti icra dairesi tarafından alacaklılara tebliğ edilir.

Cetvel suretinin tebliğinden itibaren *yedi gün içinde* her alacaklı takibin
icra edildiği mahal mahkemesinde ilgililer aleyhine dava etmek suretiyle cetvel
içeriğine itiraz edebilir. Başka bir ifade ile, cetvelde başka bir alacaklının
alacağına veya sırasına itiraz edilmek isteniyorsa dava açılmak zorundadır.

Alacaklı yalnızca kendi sırasına itiraz etmek istiyorsa şikayet yoluna
başvuracaktır.

Sıra cetveline karşı şikayet veya dava yoluna başvurulmuş ise diğer alacaklılar
teminat göstererek kendilerine düşen payı alabilirler.

Sıra cetvelinde dört sıra vardır. İlk üç sıradaki alacaklar imtiyazlı alacak,
son sıradaki alacak adi alacaktır.

NOTE: Bu dört sıranın üzerinde olan ve doktrinde *süper imtiyazlı alacak*
denilen alacaklar da vardır: _Rehinler_ ve _bir kısım devlet alacakları_
(motorlu taşıt vergisi, emlak vergisi gibi malın aynından kaynaklanan
alacaklar).

.Alacak sırası
****
. SIRA

..  _Hacizden önceki bir yıl içinde doğan ve iş ilişkisinden kaynaklanan işçi
alacakları_
.. _Hacizden önceki bir yıl içinde doğan nafaka alacakları_

. SIRA

.. _Vesayet alacakları_

. SIRA

.. _Özel kanunlardan doğan alacaklar_

... *Vekalet ücreti alacağı*
... *Kat mülkiyeti kanunundan doğan alacaklar*
****

IMPORTANT: Her sıradaki alacaklar, kendi aralarında garame usulü ile
paylaştırılır. Örneğin 1. sıradaki işçi alacakları nafaka alacaklarından önce
gelmez.

== BORÇ ÖDEMEDEN ACİZ VESİKASI

Alacaklı alacağının tamamını alamamış ve aciz vesikası düzenlenmesi için
gerekli şartlar yerine gelmişse, icra dairesi kalan miktar için hemen bir aciz
vesikası düzenleyip alacaklıya ve borçluya tebliğ eder.

Elinde aciz vesikası bulunan alacaklı, bir yıl içinde takibe gerek olmaksızın
borçlunun mallarını haczettirip sattırabilir. Bir yıllık süre geçtikten sonra
yeniden takip yapılmak zorundadır.

Borç, aciz vesikasının düzenlenmesinden itibaren *yirmi yıl geçmesiyle*
zamanaşımına uğrar. Borçlunun mirasçıları, mirasın açılmasından itibaren bir
sene içinde alacaklı hakkını aramamışsa, borcun zamanaşımına uğradığını ileri
sürebilirler.

Borçlu, hakkında verilmiş aciz belgesinin sicilden terkini istiyorsa faiziyle
birlikte borcunu ödemelidir. Normalde aciz vesikasında yazılı alacak miktarı
için faiz istenemez ve borçlu sadece bu miktarı ödeyerek borcundan kurtulur.
Ancak terkinini istiyorsa faiziyle birlikte ödemesi gerekir.

Aciz belgesinin iki türü vardır:

. *Kesin aciz vesikası:* İcra takibinin sonunda, bütün tamamlama hacizlerine
rağmen alacaklının alacağı tahsil edilememişse, tahsil edilemeyen kısım için
verilir.

.. Madde 68 anlamında bir belgedir.
.. Bir sene içinde takip yapmak zorunda olmadan borçlunun mallarını haczettirme
imkanı sunar.
.. Tasarrufun iptali davası açılabilir.
.. Hacze iştirak imkanı sunar.

. *Geçici aciz vesikası:* Hacze gidildiğinde borçlunun hiç malvarlığı ya da
alacaklının alacağına yetecek kadar malvarlığı olmadığı tespit edilirse
düzenlenen haciz tutanağı bu hükümdedir. Tasarrufun iptali davası vs. gibi
imkanlardan yararlanma şansı sunar. *Yargıtay'a göre borçlunun sadece evine
veya işyerine gidilip malvarlığı bulunamayınca düzenlenen tutanak geçici aciz
vesikası hükmünde değildir.* Geçici aciz vesikası hükmünde olması için
yeterince araştırma yapılması gerekir.

== KAMBİYO SENETLERİNE ÖZGÜ HACİZ YOLUYLA TAKİP

Elinde kambiyo senedi olan bir alacaklı;

. Kambiyo senetlerine özgü haciz yoluyla takip yapabilir.
. Genel haciz yoluyla takip yapabilir.
. (Elinde bir ilam varsa) ilamlı takip yapabilir.
. Tacir ise iflas yoluyla takip yapabilir.

Takibin başlatılacağı icra dairesi, İcra Kanunun yollamasıyla HMK'daki yetkiye
kurallara göre belirlenir.

Takibi başlatacak kişi yetkili hamil olmalıdır. Bunun için senet üzerindeki
ciro zincirinin sıhhatli olması gerekir.

Takip talebini kambiyo senedinin aslı da eklenmelidir. Gerekirse ödememe
protestosu da eklenecektir.

TIP: Çek Kanunu'ndaki düzenleme gereğince, çekin karşılıksız kalması halinde
çekin aslı bankada kalır ve banka hamile çekin onaylı bir fotokopisini verir.
Alacaklı bu fotokopi ile takip başlatabilecektir.

İcra müdürü aşağıdaki hususları inceleyecektir:

* Senedin aslı eklenmiş mi?
* Eklenen senet bir kambiyo senedi mi?
* Alacaklının takip yetkisi var mı?
* Senedin vadesi gelmiş mi?

İcra müdürü bunlarda bir eksiklik görmezse borçluya ödeme emri göndererek üç
seçenek sunar:

. *Öde*: 10 gün içinde
. *İtiraz et*: 5 gün içinde
+
İtiraz için dilekçe ile *icra mahkemesine* başvurulmalıdır. Genel haciz yoluyla
takipteki _gecikmiş itiraz_ müessesesi burada da uygulanabilir.
+
İtiraz ederken borca veya imzaya itiraz edilebilr. *İtiraz takibi kendiliğinden
durdurmaz, icra mahkemesi gerekli görürse bu yönde karar verebilir*.
+
Boçlu borca itiraz ettiğinde, teorik olarak ispat yükü alacaklıya aittir. Ancak
burada alacaklının elinde bir kambiyo senedi olduğundan ispat yükü borçlunun
üzerinde olacaktır. Borçlu, borca itiraz ederken herhangi bir belge ile ispat
edemez, ancak *resmi senetle veya imzası ikrar edilmiş senetle ispat edebilir*.
+
Mahkeme, borçlunun itirazını kabul veya ret ederse genel haciz yoluyla
takipteki tazminatlar burada da söz konusu olur.
+
.İtirazın takibi durdurmaması ve HMK 209
****
İcra Kanunu'na göre _itiraz, satış harici takibi durdurmaz_. İtirazın takibi
durdurması için mahkemenin karar vermesi gerekir.

HMK 209'daki düzenlemeye göre ise _adi bir senetteki yazı veya imza inkar
edildiğindei bu konuda bir karar verilinceye kadar, o senet herhangi bir işleme
esas alınamaz_.

*Birinci görüşe göre* HMK 209, tüm hukuk sisteminde uygulanması gereken bir
düzenlemedir.

*İkinci görüşe göre* İcra Kanunu'ndaki hüküm özel hüküm olduğundan, o
uygulanır.

*Yargıtay* bu konuda yerleşik bir karara sahip değildir. En son kararında HMK
209'u esas almıştır.
****

. *Şikayet et*

.. _Senedin aslının eklenmemiş olması_: 7 gün içinde
.. _Senedin vadesinin gelmemiş olması_: 7 gün içinde
.. _Eklenen senedin kambiyo senedi olmaması_: 5 gün içinde
.. _Alacaklının takip yetkisinin olmaması_: 5 gün içinde

== İLAMLI İCRA

Para ve teminat alacaklarında ilamlı icraya başvurmak tamamen alacaklının
takdirindedir. Para ve teminat dışındaki alacaklarda ise ilamlı icra
alacaklının tek seçeneğidir.

NOTE: Yargıtay, alacaklının elinde ilam olmasına rağmen ilamsız icraya
başvurmasının dürüstlük kuralına aykırı olduğunu söylemiştir.

Bir kararın ilam niteliğinde olması için eda hükmü içermesi gerekir. Özel
kanunlarda ayrıca ilam niteliğinde olan belgeler sayılmıştır:

. Düzenleme şeklindeki noter senetleri
. Mahkeme önünde yapılan kefaletnameler
. İcra kefaletnameleri
. Mahkeme önündeki sulhler
. Mahkeme önündeki kabuller
. Arabulucuk anlaşma belgesi

Kural olarak ilamlı icraya başvurmak için hükmün kesinleşmesi aranmaz. Bunun
istisnaları:

* Aile hukukuna ilişkin kararlar
* Kişiler hukukuna ilişkin kararlar
* Taşınmaz mallar ile ilgili ayni haklara ilişkin kararlar
* Yabancı mahkeme kararlarının tenfizi hakkındaki kararlar
* Gemilere ilişkin kararlar

İlamların icrası her icra dairesinden talep olunabilir. Alacaklı yerleşim
yerini değiştirirse takibin yeni yerleşim yeri icra dairesine havalesini
isteyebilir.

İcra müdürü takip talebini aldıktan sonra aşağıdaki hususları inceleyecektir:

. İlam veya ilam niteliğinde belge eklenmiş mi?
. Eğer ilamsa, ilam cebri icraya elverişli mi?

İcra müdürü bu hususlarda eksiklik görmezse borçluya *icra emri* gönderir. İcra
emrinde borçluya süresi içinde ifa etmesi teklif edilir. Bu süre normal
şartlarda 7 gündür ancak borçtan borca değişir.

Borçlu icra emrini aldıktan sonra:

. Borcunu ifa edebilir.
. Susabilir.
. İcranın geri bırakılmasına başvurabilir.

=== İLAMLI İCRANIN GERİ BIRAKILMASI

İcranın geri bırakılması yoluna sadece üç sebeple başvurulabilir:

. İtfa (borcun sona ermesi)
. İmhal (borçluya süre verilmesi)
. Zamanaşımı

İcranın geri bırakılması yoluna belirli sürelerde başvurulabilir:

. *Üç sebepten birinin hükümden önce ortaya çıkması halinde* bunların davada
ileri sürülmesi gerekir. Davada ileri sürülmezse daha sonra ileri sürülemez.
. *Hükmün verilmesinden ilamlı icranın başlamasına kadarki süre içinde ortaya
çıkması halinde* ortaya çıkmasından itibaren 7 gün içinde icranın geri
bırakılması istenebilir.
. *İcra emrinin tebliğinden sonra ortaya çıkması halinde* süre sınırı
olmaksızın ileri sürülebilir.

İcranın geri bırakılması sebepleri belirli belgelerle ispat edilebilir:

. Borçlu, *icra emrinin tebliğinden önce* borcunun itfa edildiğini veya
kendisine süre verildiğini iddia ediyorsa, sadece *yetkili mercilerce düzenleme
ya da tasdik şeklinde hazırlanan belgeler* yahut *icra dairesi veya icra
mahkemesini önünde alacaklı tarafından ikrar edilmiş olan belgelerle* bu
iddiasını ispatlayabilir.
. Borçlu, *icra emrinin tebliğinden sonra* ortaya çıkan sebeplere dayanıyorsa
iddiasını ispatlama için *noterlik belgeleri* ya da *icra tutanağına*
dayanabilir.

IMPORTANT: Belirli belgelere dayanma şartı sadece itfa ve imhal için
geçerlidir. Zamanaşımı takip dosyasından anlaşılabilecek bir sebep olduğundan
belirli belgeye dayanma şartı yoktur.

=== İLAMLI İCRANIN DURDURULMASI

İlama karşı istinaf veya temyiz yoluna başvuran borçlu;

* hükmolunan para veya eşyanın resmi bir mercie depo edildiğini ispat ederse,
* ya da hükmolunan para veya eşya değerinde bir teminat gösterirse,
* ya da borçlunun hükmolunan para ve eşyayı karşılayacak hacizli malı mevcut
ise,

icranının geri bırakılması bölge adliye mahkemesi veya Yargıtay'dan karar
alınmak üzere icra müdürü tarafından kendisine uygun bir süre verilir. Bu süre
ancak zorunluluk halinde uzatılabilir.

Borçlu devlet veya adli yardımdan yararlanan biri ise teminat gösterme
zorunluluğu yoktur.

CAUTION: Nafaka hükümlerinde böyle bir süre verilemez.

Bölge adliye mahkemesince başvurunun esastan reddine karar verilmesi veya
Yargıtayca hükmün onaylanması halinde alacaklının istemi üzerine başkaca işleme
gerek kalmaksızın teminata konu olan para alacaklıya ödenir. Mal ve haklar
ise, malın türüne göre icra dairesince paraya çevrilir. İlam alacaklısının
teminat üzerinde rüçhan hakkı vardır.

=== İLAMIN İCRA EDİLMESİ

==== PARA ALACAKLARINDA

İcra emrinden sonraki 7 gün içinde borçlu ödeme yapmazsa alacaklı ya haciz
yoluna başvurabilir ya da borçlu tacir ise iflas yoluna başvurabilir.

==== TAŞINIRLARDA

Taşınır borçlunun elindeyse, taşınır, icra dairesi tarafından zorla alınarak
alacaklıya verilir.

Taşınır üçüncü kişinin elindeyse, malın değeri borçludan alınır. Malın değeri
ilamda yazıyorsa bu esas alınır. Yazmıyorsa bilirkişiden değer tespiti istenir.

==== TAŞINMAZLARDA

Taşınmaz borçlunun elindeyse, önce tapu idaresinden tescili istenir ve ardından
alacaklıya teslim edilir.

Taşınmaz üçüncü kişinin elindeyse ve üçüncü kişi bir *ayni hak iddiasında*
bulunuyorsa öncelikle taşınmazın üçüncü kişiye tescil edilip edilmediği ve
tescil edildiyse iyiniyetli olup olmadığı incelenir. Tescil edilmiş ve
iyiniyetli ise alacaklı ya *satış bedelinin kendisine ödenmesini* isteyebilir
ya da borçludan tazminat talep edebilir.

Taşınmaz üçüncü kişinin elinde ve üçüncü kişi bir *şahsi hak iddiasında*
bulunursa bu üçüncü kişi taşınmazdan çıkarılabilir. Ancak Yargıtay'a göre şahsi
hak tapuya şerh verilmişse, üçüncü kişi taşınmazdan çıkarılamaz.

==== İŞ GÖRME BORÇLARINDA

İşin başkası tarafından yapılması mümkünse yaptırılır ve yaptırma masrafları
borçludan alınır.

İşin başkası tarafından yapılması mümkün değilse, borçlu, 3 aya kadar tazyik
hapsine mahkum edilir.

== REHNİN PARAYA ÇEVRİLMESİ YOLUYLA TAKİP

*Rehinle teminat altına alınmış bir alacak varsa, borçlu iflasa tabi
şahıslardan olsa bile, alacaklı yalnız rehnin paraya çevrilmesi yoluyla takip
yapabilir.*

Ancak rehnin tutarı borcu ödemeye yetmezse alacaklı kalan alacağını iflas veya
haciz yoluyla takip edebilir.

NOTE: Alacaklı rehin varken genel haciz yoluyla takibe başvurmuş ve icra müdürü
bunu denetlememiş ise Yargıtay'a göre süresiz şikayet yoluna başvurulabilir.

Bazı hallerde önce rehne başvurma zorunluluğu yoktur:

* Konut kredileri
* TOKİ alacakları
* Kambiyo senetleri
* İpotekle temin edilen faiz alacakları
* Gemi üzerindeki alacaklar

=== TAŞINIR REHNİNİN PARAYA ÇEVRİLMESİ YOLUYLA TAKİP

Alacağı taşınır rehni ile sağlanmış alacaklı, takip talebinde bulunması gereken
hususlara ek olarak, merhunun ne olduğunu ve merhun üçüncü şahıs tarafından
verilmiş veya merhunun mülkiyeti üçüncü şahısa geçmiş ise onun ve merhun
üzerinde sonra gelen rehin hakkı mevcut ise bu hakka sahip olan şahsın ismini
de bildirir.

Takip talebi üzerine, icra dairesi, keyfiyeti merhun üzerine sonra gelen rehin
hakkı sahibine bir ihbarname ile bildirir ve borçlu ile rehin maliki üçüncü
şahsa aşağıdaki kayıtlara uygun olmak üzere birer ödeme emri gönderir:

. *Ödeme süresi on beş gündür*.
. *Yedi gün içinde itiraz* olunmaz ve yukarıdaki süre içinde borç ödenmezse
rehnin satılacağı bildirilir.

Ödeme emrini itiraz hakkında genel hükümler uygulanır. Ancak;

. Rehin hakkına açıkça itiraz edilmemişse, alacaklının rehin hakkı takip
safhası içinde artık tartışma konusu olamaz.
. Sırf rehin hakkına itiraz olunduğu takdirde, alacaklı, rehnin paraya
çevrilmesi yoluyla takipten vazgeçerek, takibin haciz yolu ile devamını
isteyebilir. Bu takdirde, borçluya mal beyanında bulunması için yedi gün mühlet
verilir.

=== İPOTEĞİN PARAYA ÇEVRİLMESİ YOLUYLA TAKİP

Taşınmaz ipotek alacaklısı, yetkili veya taşınmazın bulunduğu yer icra
dairesine elindeki *ipotek akit tablosunu* ibraz ederek takip talebinde
bulunur.

İcra memuru, ibraz edilen akit tablosunun *kayıtsız şartsız bir para borcu
ikrarını ihtiva ettiğini* ve *alacağın muaccel olduğunu* anlarsa, borçluya
ve taşınmaz üçüncü şahıs tarafından rehnedilmiş veya taşınmazın mülkiyeti
üçüncü şahsa geçmişse ayrıca bunlara birer icra emri gönderir. Bu icra
emrinde *borcun otuz gün içinde ödenmesi* ve bu müddet içinde ödenmez ve
icra mahkemesinden icranın geri bırakılmasına dair bir karar getirilmezse,
alacaklının taşınmazın satışını isteyebileceği bildirilir.*

TIP: Doğmuş bir alacak varsa *anapara ipoteği*, doğmamış bir alacak varsa
*limit ipoteği* söz konusu olur. Anapara ipoteği söz konusuysa, ipotek akit
tablosu kayıtsız şartsız para borcu ikrarı içeriyordur. Dolayısıyla
anapara ipoteğinde ilamlı icraya, limit ipoteğinde ilamsız icraya gidilir.

İcra memuru, borçluya ve varsa taşınmaz sahibi üçüncü şahsa aşağıdaki
kayıtlara uygun olmak üzere birer ödeme emri gönderir:

. *Ödeme süresi otuz gündür.*
. *Yedi gün içinde itiraz* olunmaz ve süresinde ödeme yapılmaz ise
alacaklının taşınmazın satışını isteyebileceği bildirilir.

Borçlu veya üçüncü şahıs ödeme emrinin tebliğinden itibaren yedi gün içinde
itirazda bulunabilirler. *Ancak, rehin hakkı itiraz konusu yapılamaz.*

=== SATIŞ TALEBİ

Satış hükümleri genel haciz yoluyla takip ile aynıdır. Satış talebi
taşınırlarda 6 ay, taşınmazlarda 1 yıl içinde yapılmalıdır.

IMPORTANT: Süresinde satış talebinde bulunulmazsa genel haciz yoluyla takipten
farklı olarak *takip düşer*.

=== REHİN AÇIĞI BELGESİ

Alacaklının satış talebinden sonra takdir edilen ve kesinleşen kıymete göre
merhunun alacağı karşılamayacağı anlaşılırsa, alacaklının talebi üzerine
kendisine açık kalan için bir *muvakkat rehin açığı belgesi* verilir. Alacaklı,
bu belgeye dayanarak borçlunun diğer mallarının haczini icra memurundan talep
edebilir ve diğer alacaklıların haczine iştirak edebilir. Bu takdirde alacaklı,
rehnin satışı neticesinde, alacağının tahsil edilemeyen kısmını borçlunun diğer
mahcuz mallarından rüçhansız olarak alır.

Geçici rehin açığı belgesi sahibi, aynı dosya üzerinden haciz isteyebilir.
Borçlunun mallarını buldukça haczedebilir fakat rehinli mal satılmadan
haczedilen mallar satılamaz. Zira rehinli mal satılmadığı için açık kesin
olarak belli değildir.

Buna karşılık kesin rehin açığı belgesi sahibi, genel haciz yoluyla takibe
başvurabileceği gibi iflas yoluyla takip de başlatabilir. Yani önce rehne
başvurma kuralı bertaraf olur. Yeni takip belgenin düzenlenmesinden itibaren 1
yıl içinde başlatılırsa, borçluya ödeme emri bile gitmez.

NOTE: Yargıtay, kesin rehin açığı belgesinin tasrrufun iptali davasında
kullanılamayacağını kabul etmektedir.

== İHTİYATİ HACİZ

*Rehinle temin edilmemiş* ve *vadesi gelmiş bir para borcunun* alacaklısı,
borçlunun yedinde veya üçüncü şahısta olan taşınır ve taşınmaz mallarını ve
alacaklarıyla diğer haklarını ihtiyaten haczettirebilir.

*Vadesi gelmemiş borçtan* dolayı yalnız aşağıdaki hallerde ihtiyati haciz
istenebilir:

. Borçlunun muayyen yerleşim yeri yoksa
. Borçlu taahhütlerinden kurtulmak maksadıyla mallarını gizlemeye, kaçırmaya
veya kendisi kaçmaya hazırlanır yahut kaçar ya da bu maksatla alacaklının
haklarını ihlal eden hileli işlemlerde bulunursa

Bu suretle ihtiyati haciz konulursa borç yalnız borçlu hakkında muaccelliyet
kesbeder.

İhtiyati hacze, HMK'nın yetkiye dair hükümleri ile belirlenecek mahkeme karar
verir.

İhtiyati haciz için yaklaşık ispat yeterlidir. Alacaklı alacağın varlığını ve
muaccel olduğunu yaklaşık olarak ispat edecektir. Vadesi gelmemiş ise ihtiyati
haciz sebeplerinin varlığını yaklaşık olarak ispat edecektir.

*Mahkeme iki tarafı dinleyip dinlememekte serbesttir.*

İhtiyati haciz talebinin reddine karşı istinaf yolu açık fakat temyiz yolu
kapalıdır.

İhtiyati haciz talebi kabul edilirse alacaklının alacağını dayandırdığı hususa
göre teminat alınır:

* Alacaklı ilama dayanıyorsa teminat aranmaz.
* İlam niteliğinde belgeye dayanıyorsa teminat aranması hakimin takdiridir.
* Başka bir belgeye dayanıyorsa alacaklı teminat göstermek zorundadır.

=== TAMAMLAYICI MERASİM

Alacaklı, *ihtiyati haciz kararının verildiği tarihten itibaren on gün içinde*
kararı veren mahkemenin yargı çevresindeki icra dairesinden kararın infazını
istemeye *mecburdur*. Aksi halde ihtiyati haciz kararı kendiliğinden kalkar.

Dava açılmadan veya icra takibine başlanmadan önce ihtiyati haciz yaptırmış
olan alacaklı; haczin tatbikinden, haciz gıyabında yapılmışsa haciz
tutanağının kendisine tebliğinden itibaren *yedi gün içinde* takip talebinde
(haciz veya iflas) bulunmaya ya da dava açmaya *mecburdur*.

İhtiyati haciz, alacak davasının mahkemede görüldüğü sırada konulmuş veya
alacaklı yukarıdaki hüküm uyarınca dava açmış ise, esas hakkında verilecek
hükmün tebliğinden itibaren *bir ay içinde* alacaklı takip talebinde bulunmaya
mecburdur.

İcra takibinde, borçlu ödeme emrine itiraz ederse bu itiraz hemen alacaklıya
tebliğ olunur. Alacaklı, tebliğ tarihinden itibaren *yedi gün içinde* icra
mahkemesinden *itirazın kaldırılmasını istemeye* veya mahkemede *dava açmaya*
*mecburdur*. İcra mahkemesi, itirazın kaldırılması talebini reddederse
alacaklının kararın tefhim veya tebliği tarihinden itibaren yedi gün içinde
dava açması zorunludur.

Borçlu süresi içinde ödeme emrine itiraz etmez veya itirazı icra mahkemesince
kesin olarak kaldırılır veya mahkemece iptal edilirse, ihtiyati haciz
kendiliğinden icrai hacze dönüşür.

CAUTION: Bu süreler ihtiyati haczin devamını sağlamak içindir.

=== İHTİYATİ HACZİN KALDIRILMASI

İhtiyati haciz iki şekilde kaldırılır:

. İhtiyati haciz talebinin kabulüne itiraz
. Teminat gösterme

İhtiyati haczin kaldırılması;

. İhtiyati haciz kararı verildikten sonra, alacaklı henüz tamamlayıcı merasim
yapmadıysa, kararı veren mahkemeden
. Tamamlayıcı merasim ile dava açıldıysa davanın görüldüğü mahkemeden
. Tamamlayıcı merasim ile takip başlatılmışsa icra mahkemesinden

==== İTİRAZ

İhtiyati haciz talebinin kabulüne itiraz, borçlu veya menfaati ihlal edilen
üçüncü kişi tarafından yapılabilir.

*Borçlunun itiraz edebilmesi için ihtiyati haciz yargılamasında dinlenilmemiş
olması gerekir.*

İtiraz, kararı veren mahkemeye, haczin icrası veya haciz tutanağının
tebliğinden itibaren yedi gün içinde yapılır.

Borçlu;

. Yetki itirazında bulunabilir.
. Sebeplere itiraz edebilir.
. Teminata itiraz edebilir.

Üçüncü kişi;

. Sebeplere itiraz edebilir.
. Teminata itiraz edebilir.

*İtiraz üzerine verilen karara karşı istinaf yolu açıktır.*

==== TEMİNAT

Teminat gösterilmesi ihtiyati haczi kendiliğinden kaldırmaz. İcra mahkemesinin
bir karar vermesi gerekir. Karar üzerine ihtiyati haciz teminat üzerinden devam
eder.

=== İHTİYATİ HACİZDEN KAYNAKLANAN TAZMİNAT DAVASI

Borçlunun mallarına haksız şekilde haciz koyduran alacaklı, borçlunun veya
üçüncü kişinin bu sebeple ortaya çıkan zararını tazmin etmek zorundadır. Bu
sorumluluk haksız fiil esaslarına dayanır, *ancak kusur aranmaz*.

Doktrinde bir görüşe göre haksız fiil sorumluluğu olduğu için 2-10 yıllık
zamanaşımı uygulanacak, diğer bir görüşe göre ise HMK ihtiyati tedbire dair
1 yıllık zamanaşımı kıyasen uygulanacaktır.

== İFLAS

İflasa tabi olanlar:

. Tacirler
. Tacir gibi sorumlu olanlar
. Tacir sayılanlar
. Donatma iştiraki
. Kanunda sayılan şartlarda komandit ve kollektif şirket ortakları

=== TAKİPLİ İFLAS

==== ADİ TAKİPLİ İFLAS

Adi takipli iflas, genel haciz yoluyla takipteki gibi bir takip talebi ile
başlar.

_Tacir, her türlü borcu için iflasa tabidir._ Ancak bu takip yolu için borcun
*para* veya *teminat* borcu olması gerekir.

*Önce rehne başvurma kuralı* burada da geçerlidir.

İflas yoluyla takipte yetkili merci, borçlunun muamele merkezinin bulunduğu yer
icra dairesidir.

Merkezleri yurt dışında bulunan ticari işletmeler hakkında yetkili merci,
Türkiye'deki şubenin, birden fazla şube bulunması halinde merkez şubenin
bulunduğu yerdeki icra dairesidir.

Borçlu ile alacaklı yetkili icra dairesini yazılı anlaşma ile tayin etmişlerse,
o yerin icra dairesi de iflas takibi için yetkili sayılır.

Takip talebinde, hangi takip talebinin seçildiği belirtilmelidir.

Borçluya ödeme emri gönderildikten sonra borçlunun yapabileceği üç şey vardır:

. Ödeyebilir.
. İtiraz ederse, takip durur.
. Susarsa, ödeme emri kesinleşir.

Ödeme emri kesinleştikten sonra alacaklı *iflas davası* açacaktır. İflas
davaları için yetki sözleşmesi yapılamaz ve iflas davası mutlaka *boçlunun
muamele merkezinin bulunduğu yer ticaret mahkemesinde açılır*.
