:icons: font
:toc:
:toc-title: İŞ HUKUKU

== İŞÇİ ve İŞVEREN

Bir iş sözleşmesine dayanarak çalışan gerçek kişiye *işçi*, işçi çalıştıran
gerçek veya tüzel kişiye yahut tüzel kişiliği olmayan kurum ve kuruluşlara
*işveren*, işçi ile işveren arasında kurulan ilişkiye *iş ilişkisi* denir.

== İŞVEREN VEKİLİ

İşveren adına hareket eden ve işin, işyerinin ve işletmenin yönetiminde görev
alan kimselere *işveren vekili* denir. İşveren vekilinin bu sıfatla işçilere
karşı işlem ve yükümlülüklerinden doğrudan işveren sorumludur.

Bu Kanunda işveren için öngörülen her çeşit sorumluluk ve zorunluluklar işveren
vekilleri hakkında da uygulanır. İşveren vekilliği sıfatı, işçilere tanınan hak
ve yükümlülükleri ortadan kaldırmaz.

== ALT İŞVEREN

Bir işverenden, işyerin de yürüttüğü mal veya hizmet üretimine ilişkin yardımcı
işlerinde veya asıl işin bir bölümünde işletmenin ve işin gereği ile teknolojik
nedenlerle uzmanlık gerektiren işlerde iş alan ve bu iş için görevlendirdiği
işçilerini sadece bu işyerinde aldığı işte çalıştıran diğer işveren ile iş
aldığı işveren arasında kurulan ilişkiye asıl işveren-alt işveren ilişkisi
denir.

IMPORTANT: Asıl işveren-alt işveren ilişkisi alt işveren işçisiyle asıl işveren
arasında iş ilişkisi doğurmaz.

NOTE: Asıl işveren-alt işveren ilişkisi kurulduğunda işyerinde iki tane işveren
vardır. İki ayrı işverenin hukuki olarak iki ayrı işyeri olduğu kabul edilir ve
iki işyerinin ayrı ayrı bildirilmesi gerekir.

*Asıl işveren-alt işveren ilişkisinin özellikleri*:

. İşyerinde işçi çalıştıran bir asıl işverenin varlığı gereklidir. Bütün işi
alt işverenin işçileri görüyor ise asıl işveren-alt işveren ilişkisi yoktur.
. İşin asıl işverene ait işyerinde görülmesi gerekir.
. İşin işyerinde yürütülen mal ve hizmet üretimine ilişkin olması gerekir.
+
Kanuna göre asıl işe yardımcı olan yan işler hiçbir sınırlama olmadan alt
işverenin işçilerine gördürülebilir. Ancak asıl işverenin yürüttüğü asıl işin
ancak bir kısmı alt işverenenin işçilerine gördürülebilir.
. Alt işverenin bu işe mahsus oluşturduğu işçi grubunun sürekli olması gerekir.
. Asıl işveren-alt işveren sözleşmesinin *yazılı* şekilde yapılması gerekir.

Bu ilişkide asıl işveren, alt işverenin işçilerine karşı o işyeri ile ilgili
olarak bu Kanundan, iş sözleşmesinden veya alt işverenin taraf ol duğu toplu iş
sözleşmesinden doğan yükümlülüklerinden alt işveren ile birlikte sorumludur.

TIP: Çoğu zaman asıl işverenle alt işveren, asıl işverenin alt işverenin
işçilerinin alacaklarından sorumlu olmayacağına dair anlaşırlar. *İşçi
sözleşmede böyle bir hüküm olsa dahi alacaklarını asıl işverenden talep
edebilir.* Ancak taraflar arasındaki bu anlaşma rücuda önem taşır.

Asıl işverenin işçilerinin alt işveren tarafından işe alınarak çalıştırılmaya
devam ettirilmesi suretiyle hakları kısıtlanamaz veya daha önce o işyerinde
çalıştırılan kimse ile alt işveren ilişkisi kurulamaz. Aksi halde ve genel
olarak asıl işveren alt işveren ilişkisinin muvazaalı işleme dayandığı kabul
edilerek alt işverenin işçileri başlangıçtan itibaren asıl işverenin işçisi
sayılarak işlem görürler. İşletmenin ve işin gereği ile teknolojik nedenlerle
uzmanlık gerektiren işler dışında asıl iş bölünerek alt işverenlere verilemez.

== İŞYERİ

İşveren tarafından mal veya hizmet üretmek amacıyla maddî olan ve olmayan
unsurlar ile işçinin birlikte örgütlendiği birime işyeri denir.

İşverenin işyerinde ürettiği mal veya hizmet ile nitelik yönünden bağlılığı
bulunan ve aynı yönetim altında örgütlenen yerler (işyerine bağlı yerler) ile
dinlenme, çocuk emzirme, yemek, uyku, yıkanma, muayene ve bakım, beden ve
meslekî eğitim ve avlu gibi diğer eklentiler ve araçlar da işyerinden sayılır.

İşyeri, işyerine bağlı yerler, eklentiler ve araçlar ile oluşturulan iş
organizasyonu kapsamında bir bütündür.

== İŞ SÖZLEŞMESİ

İş sözleşmesi, bir tarafın (işçi) bağımlı olarak iş görmeyi, diğer tarafın
(işveren) da ücret ödemeyi üstlenmesinden oluşan sözleşmedir. İş sözleşmesi,
Kanunda aksi belirtilmedikçe, özel bir şekle tâbi değildir.

Ücret unsurunu içermeyen bir iş sözleşmesinden söz edilemez. Ancak ücret
sözleşmede belirlenmemiş olabilir. Bu durumda mahkeme tarafından emsal ücret
belirlenir.

İşçinin işverene ait iş organizasyonu içinde onun yararına bir iş görmesi
bağımlılık unsurunun var olduğunu gösterir.

İş sözleşmeleri belirli veya belirsiz süreli yapılır. Bu sözleşmeler çalışma
biçimleri bakımından tam süreli veya kısmî süreli yahut deneme süreli ya da
diğer türde oluşturulabilir.

Süresi bir yıl ve daha fazla olan iş sözleşmelerinin yazılı şekilde yapılması
zorunludur.

Yasada öngörülen şekil kuralının ihlal edilmesi halinde uygulanacak sonuç
doktrinde tartışmalıdır. Bir görüşe göre kanunda öngörülen şekil şartları ispat
şartıdır. Diğer bir görüş ise bunların geçerlilik şartı olduğunu savunmaktadır.

IMPORTANT: İş hukukunda geçersizlik ileriye etkili olarak sonuç doğurur.

== SÖZLEŞME SERBESTİSİ

Taraflar iş sözleşmesini, Kanun hükümleriyle getirilen sınırlamalar saklı
kalmak koşuluyla, ihtiyaçlarına uygun türde düzenleyebilirler.

=== SÖZLEŞME YAPILMASININ YASAK OLDUĞU HALLER

. *Yaş küçüklüğü*: On beş yaşını doldurmamış çocukların çalıştırılması
yasaktır. Ancak, on dört yaşını doldurmuş ve zorunlu ilköğretim çağını
tamamlamış olan çocuklar; bedensel, zihinsel, sosyal ve ahlaki gelişmelerine ve
eğitime devam edenlerin okullarına devamına engel olmayacak hafif işlerde
çalıştırılabilirler. On dört yaşını doldurmamış çocuklar ise bedensel,
zihinsel, sosyal ve ahlaki gelişmelerine ve eğitime devam edenlerin okullarına
devamına engel olmayacak sanat, kültür ve reklam faaliyetlerinde yazılı
sözleşme yapmak ve her bir faaliyet için ayrı izin almak şartıyla
çalıştırılabilirler.
. *Cinsiyet*
. *Yabancılık*

=== SÖZLEŞME YAPILMASININ ZORUNLU OLDUĞU HALLER

. *Engelli ve eski hükümlü çalıştırma yükümlülüğü*: Bir işverenin işyerinde
engelli ya da eski hükümlü çalıştırma zorunluluğunun doğabilmesi için işyerinde
çalıştırılan işçi sayısının en az elli olması gerekir.
+
Bu kapsamda çalıştırılacak işçi sayısının tespitinde belirli ve belirsiz süreli
iş sözleşmesine göre çalıştırılan işçiler esas alınır. Kısmi süreli iş
sözleşmesine göre çalışanlar, çalışma süreleri dikkate alınarak tam süreli
çalışmaya dönüştürülür.
+
Aynı işverene ait birden fazla işyeri varsa aynı il sınırları içerisinde
olanlar işyerlerinde çalışan toplam çalışan sayısı elliyi geçiyor ise
yükümlülük doğar.
+
Özel kesim işverenleri sadece engelli işçi çalıştırma yükümlülüğü altındadır.
. *İşyerinden malulen ayrılanlarla akit yapma yükümlülüğü*: Bir işyerinden
malulen ayrılmak zorunda kalıp da sonradan maluliyeti ortadan kalkan işçiler
eski işyerlerinde tekrar işe alınmalarını istedikleri takdirde, işveren bunları
eski işleri veya benzeri işlerde boş yer varsa derhal, yoksa boşalacak ilk işe
başka isteklilere tercih ederek, o andaki şartlarla işe almak zorundadır.
Aranan şartlar bulunduğu halde işveren iş sözleşmesi yapma yükümlülüğünü yerine
getirmezse, işe alınma isteğinde bulunan eski işçiye altı aylık ücret tutarında
tazminat öder.
. *Askerlik veya yasal görev nedeniyle işten ayrılanların yeniden işe
başlatılması*: Herhangi bir askeri ve kanuni ödev dolayısıyla işinden ayrılan
işçiler bu ödevin sona ermesinden başlayarak iki ay içinde işe girmek
istedikleri takdirde işveren bunları eski işleri veya benzeri işlerde boş yer
varsa derhal, yoksa boşalacak ilk işe başka isteklilere tercih ederek, o andaki
şartlarla işe almak zorundadır. Aranan şartlar bulunduğu halde işveren iş
sözleşmesi yapma yükümlülüğünü yerine getirmezse, işe alınma isteğinde bulunan
eski işçiye üç aylık ücret tutarında tazminat öder.
. *Toplu işten çıkarma*: İşveren toplu işçi çıkarmanın kesinleşmesinden
itibaren altı ay içinde aynı nitelikteki iş için yeniden işçi almak istediği
takdirde nitelikleri uygun olanları tercihen işe çağırır.

Yukarıdaki yükümlülükleri yerine getirmeyen işveren için idari para cezası veya
tazminat yaptırımları öngörülmüştür. Bunların kanunda öngörülmemiş olduğu
durumlarda doktrinde bir görüşe göre tazminat ödeme yükümlülüğü doğacak diğer
bir görüşe göre ise aynen ifa davası açılacaktır. Yargıtay da bazı kararlarında
aynen ifayı kabul etmiştir.

== İŞ SÖZLEŞMESİ TÜRLERİ

=== SÜREKLİ VE SÜREKSİZ İŞ SÖZLEŞMESİ

Nitelikleri bakımından en çok otuz iş günü süren işlere süreksiz iş, bundan
fazla devam edenlere sürekli iş denir.

=== DENEME SÜRELİ İŞ SÖZLEŞMESİ

Taraflarca iş sözleşmesine bir deneme kaydı konulduğunda, bunun süresi en çok
iki ay olabilir. Ancak deneme süresi toplu iş sözleşmeleriyle dört aya kadar
uzatılabilir.

Deneme süresi içinde taraflar iş sözleşmesini bildirim süresine gerek
olmaksızın ve tazminatsız feshedebilir. İşçinin çalıştığı günler için ücret ve
diğer hakları saklıdır.

=== BELİRLİ SÜRELİ İŞ SÖZLEŞMESİ

İş ilişkisinin bir süreye bağlı olarak yapılmadığı halde sözleşme belirsiz
süreli sayılır. Belirli süreli işlerde veya belli bir işin tamamlanması veya
belirli bir olgunun ortaya çıkması gibi objektif koşullara bağlı olarak işveren
ile işçi arasında yazılı şekilde yapılan iş sözleşmesi belirli süreli iş
sözleşmesidir.

Belirli süreli iş sözleşmesi, esaslı bir neden olmadıkça, birden fazla üst üste
(zincirleme) yapılamaz. Aksi halde iş sözleşmesi başlangıçtan itibaren belirsiz
süreli kabul edilir.

Esaslı nedene dayalı zincirleme iş sözleşmeleri, belirli süreli olma özelliğini
korurlar.

Belirli süreli iş sözleşmesi ile çalıştırılan işçi, ayırımı haklı kılan bir
neden olmadıkça, salt iş sözleşmesinin süreli olmasından dolayı belirsiz süreli
iş sözleşmesiyle çalıştırılan emsal işçiye göre farklı işleme tâbi tutulamaz.

Belirli süreli iş sözleşmesi ile çalışan işçiye, belirli bir zaman ölçüt
alınarak ödenecek ücret ve paraya ilişkin bölünebilir menfaatler, işçinin
çalıştığı süreye orantılı olarak verilir. Herhangi bir çalışma şartından
yararlanmak için aynı işyeri veya işletmede geçirilen kıdem arandığında belirli
süreli iş sözleşmesine göre çalışan işçi için farklı kıdem uygulanmasını haklı
gösteren bir neden olmadıkça, belirsiz süreli iş sözleşmesi ile çalışan emsal
işçi hakkında esas alınan kıdem uygulanır

Emsal işçi, işyerinde aynı veya benzeri işte belirsiz süreli iş sözleşmesiyle
çalıştırılan işçidir. İşyerinde böyle bir işçi bulunmadığı takdirde, o
işkolunda şartlara uygun bir işyerinde aynı veya benzer işi üstlenen belirsiz
süreli iş sözleşmesiyle çalıştırılan işçi dikkate alınır.

=== KISMİ SÜRELİ İŞ SÖZLEŞMESİ

İşçinin normal haftalık çalışma süresinin (45 saat), tam süreli iş
sözleşmesiyle çalışan emsal işçiye göre önemli ölçüde daha az belirlenmesi
durumunda sözleşme kısmî süreli iş sözleşmesidir.

NOTE: Bir sözleşmenin kısmi süreli iş sözleşmesi olarak nitelendirilebilmesi
için işyerinde uygulanan haftalık çalışma süresinin 2/3 altında çalışmayı
üstlenmiş olması gerekir.

Kısmî süreli iş sözleşmesi ile çalıştırılan işçi, ayırımı haklı kılan bir neden
olmadıkça, salt iş sözleşmesinin kısmî süreli olmasından dolayı tam süreli
emsal işçiye göre farklı işleme tâbi tutulamaz. Kısmî süreli çalışan işçinin
ücret ve paraya ilişkin bölünebilir menfaatleri, tam süreli emsal işçiye göre
çalıştığı süreye orantılı olarak ödenir.

Emsal işçi, işyerinde aynı veya benzeri işte tam süreli çalıştırılan işçidir.
İşyerinde böyle bir işçi bulunmadığı takdirde, o işkolunda şartlara uygun
işyerinde aynı veya benzer işi üstlenen tam süreli iş sözleşmesiyle
çalıştırılan işçi esas alınır.

İşyerinde çalışan işçilerin, niteliklerine uygun açık yer bulunduğunda kısmî
süreliden tam süreliye veya tam süreliden kısmî süreliye geçirilme istekleri
işverence dikkate alınır ve boş yerler zamanında duyurulur.

Kanunun 74 üncü maddesinde öngörülen izinlerin (Analık izni) bitiminden sonra
mecburi ilköğretim çağının başladığı tarihi takip eden ay başına kadar bu
maddeye göre ebeveynlerden biri kısmi süreli çalışma talebinde bulunabilir. Bu
talep işveren tarafından karşılanır ve geçerli fesih nedeni sayılmaz. Bu fıkra
kapsamında kısmi süreli çalışmaya başlayan işçi, aynı çocuk için bir daha bu
haktan faydalanmamak üzere tam zamanlı çalışmaya dönebilir. Kısmi süreli
çalışmaya geçen işçinin tam zamanlı çalışmaya başlaması durumunda yerine işe
alınan işçinin iş sözleşmesi kendiliğinden sona erer. Bu haktan faydalanmak
veya tam zamanlı çalışmaya geri dönmek isteyen işçi işverene bunu en az bir ay
önce yazılı olarak bildirir. Ebeveynlerden birinin çalışmaması hâlinde,
çalışan eş kısmi süreli çalışma talebinde bulunamaz. Üç yaşını doldurmamış bir
çocuğu eşiyle birlikte veya münferiden evlat edinenler de çocuğun fiilen teslim
edildiği tarihten itibaren bu haktan faydalanır.

NOTE: İşçinin birden fazla işverenle aynı anda kısmi süreli iş sözleşmesi
yapmasına engel yoktur. Ancak doktrinde işçinin toplam çalıştığı sürenin 45
saati geçmemesi gerektiği savunulmaktadır.

Kısmi süreli iş sözleşmesiyle çalışan işçiler fazla mesai yapamaz.

Kısmi süreli iş sözleşmesiyle çalışan işçiler dinlenmeyle ilgili mevzuatta yer
alan düzenlemelerden tam süreli işçiler gibi yararlanır.

İş sözleşmesinin sona erdirilmesine dair mevzuatta yer alan kurallar kısmi
süreli işçiler için aynen geçerlidir.

TIP: Kısmi süreli işçilerin kıdem tazminatına hak kazanmaları için gereken 1
yıllık süre işe giriş tarihinden itibaren 1 yılın geçmesiyle tamamlanır.
Yargıtay'ın görüşü de bu yöndedir.

=== ÇAĞRI ÜZERİNE ÇALIŞMAYA DAYALI İŞ SÖZLEŞMESİ

Yazılı sözleşme ile işçinin yapmayı üstlendiği işle ilgili olarak kendisine
ihtiyaç duyulması halinde iş görme ediminin yerine getirileceğinin
kararlaştırıldığı iş ilişkisi, çağrı üzerine çalışmaya dayalı kısmi süreli bir
iş sözleşmesidir.

Hafta, ay veya yıl gibi bir zaman dilimi içinde işçinin ne kadar süreyle
çalışacağını taraflar belirlemedikleri takdirde, haftalık çalışma süresi yirmi
saat kararlaştırılmış sayılır. Çağrı üzerine çalıştırılmak için belirlenen
sürede işçi çalıştırılsın veya çalıştırılmasın ücrete hak kazanır.

İşçiden iş görme borcunu yerine getirmesini çağrı yoluyla talep hakkına sahip
olan işveren, bu çağrıyı, aksi kararlaştırılmadıkça, işçinin çalışacağı
zamandan en az dört gün önce yapmak zorundadır. Süreye uygun çağrı üzerine işçi
iş görme edimini yerine getirmekle yükümlüdür. Sözleşmede günlük çalışma süresi
kararlaştırılmamış ise, işveren her çağrıda işçiyi günde en az dört saat üst
üste çalıştırmak zorundadır.

=== UZAKTAN ÇALIŞMA

Uzaktan çalışma; işçinin, işveren tarafından oluşturulan iş organizasyonu
kapsamında iş görme edimini evinde ya da teknolojik iletişim araçları ile
işyeri dışında yerine getirmesi esasına dayalı ve yazılı olarak kurulan iş
ilişkisidir.

Yukarıdaki tanıma göre yapılacak iş sözleşmesinde; işin tanımı, yapılma şekli,
işin süresi ve yeri, ücret ve ücretin ödenmesine ilişkin hususlar, işveren
tarafından sağlanan ekipman ve bunların korunmasına ilişkin yükümlülükler,
işverenin işçiyle iletişim kurması ile genel ve özel çalışma şartlarına ilişkin
hükümler yer alır.

=== GEÇİCİ İŞ İLİŞKİSİ

Geçici iş ilişkisi, özel istihdam bürosu aracılığıyla ya da holding bünyesi
içinde veya aynı şirketler topluluğuna bağlı başka bir işyerinde görevlendirme
yapılmak suretiyle kurulabilir.

==== ÖZEL İSTİHDAM BÜROSU ARACILIĞIYLA

Özel istihdam bürosu aracılığıyla geçici iş ilişkisi, Türkiye İş Kurumunca izin
verilen özel istihdam bürosunun bir işverenle geçici işçi sağlama sözleşmesi
yaparak bir işçisini geçici olarak bu işverene devri ile;

.. Kanunun 13 üncü maddesinin beşinci fıkrası ile 74 üncü maddesinde belirtilen
hâllerde, işçinin askerlik hizmeti hâlinde ve iş sözleşmesinin askıda kaldığı
diğer hâllerde,
.. Mevsimlik tarım işlerinde,
.. Ev hizmetlerinde,
.. İşletmenin günlük işlerinden sayılmayan ve aralıklı olarak gördürülen
işlerde,
.. İş sağlığı ve güvenliği bakımından acil olan işlerde veya üretimi önemli
ölçüde etkileyen zorlayıcı nedenlerin ortaya çıkması hâlinde,
.. İşletmenin ortalama mal ve hizmet üretim kapasitesinin geçici iş ilişkisi
kurulmasını gerektirecek ölçüde ve öngörülemeyen şekilde artması hâlinde,
.. Mevsimlik işler hariç dönemsellik arz eden iş artışları hâlinde,

kurulabilir.

Geçici işçi sağlama sözleşmesi (a) bendinde sayılan hâllerin devamı süresince,
(b) ve (c) bentlerinde sayılan hâllerde süre sınırı olmaksızın, diğer bentlerde
sayılan hâllerde ise en fazla dört ay süreyle kurulabilir. Yapılan bu sözleşme
(g) bendi hariç toplam sekiz ayı geçmemek üzere en fazla iki defa
yenilenebilir. Geçici işçi çalıştıran işveren, belirtilen sürenin sonunda aynı
iş için altı ay geçmedikçe yeniden geçici işçi çalıştıramaz.

Kanunun 29 uncu maddesi kapsamında toplu işçi çıkarılan işyerlerinde sekiz ay
süresince, kamu kurum ve kuruluşlarında ve yer altında maden çıkarılan
işyerlerinde geçici iş ilişkisi kurulamaz.

Geçici işçi çalıştıran işveren, grev ve lokavtın uygulanması sırasında
18/10/2012 tarihli ve 6356 sayılı Sendikalar ve Toplu İş Sözleşmesi Kanununun
65 inci maddesi hükümleri saklı kalmak kaydıyla geçici iş ilişkisiyle işçi
çalıştıramaz.

(f) bendi kapsamında geçici iş ilişkisi ile çalıştırılan işçi sayısı, işyerinde
çalıştırılan işçi sayısının dörtte birini geçemez. Ancak, on ve daha az işçi
çalıştırılan işyerlerinde beş işçiye kadar geçici iş ilişkisi kurulabilir. İşçi
sayısının tespitinde, kısmi süreli iş sözleşmesine göre çalışanlar, çalışma
süreleri dikkate alınarak tam süreli çalışmaya dönüştürülür. Geçici işçi
sağlama sözleşmesi ile çalışan işçi, 30 uncu maddenin uygulanmasında özel
istihdam bürosu ve geçici işçi çalıştıran işverenin işçi sayısına dâhil
edilmez.

Geçici işçi çalıştıran işveren, iş sözleşmesi feshedilen işçisini fesih
tarihinden itibaren altı ay geçmeden geçici iş ilişkisi kapsamında
çalıştıramaz.

Geçici işçi çalıştıran işveren;

.. İşin gereği ve geçici işçi sağlama sözleşmesine uygun olarak geçici işçisine
talimat verme yetkisine sahiptir.
.. İşyerindeki açık iş pozisyonlarını geçici işçisine bildirmek ve Türkiye İş
Kurumu tarafından istenecek belgeleri belirlenen sürelerle saklamakla
yükümlüdür.
.. Geçici işçinin iş kazası ve meslek hastalığı hâllerini özel istihdam
bürosuna derhâl, 31/5/2006 tarihli ve 5510 sayılı Sosyal Sigortalar ve Genel
Sağlık Sigortası Kanununun 13 üncü ve 14 üncü maddelerine göre ilgili mercilere
bildirmekle yükümlüdür.
.. Geçici işçileri çalıştıkları dönemlerde, işyerindeki sosyal hizmetlerden
eşit muamele ilkesince yararlandırır. Geçici işçiler, çalışmadıkları dönemlerde
ise özel istihdam bürosundaki eğitim ve çocuk bakım hizmetlerinden
yararlandırılır.
.. İşyerindeki geçici işçilerin istihdam durumuna ilişkin bilgileri varsa
işyeri sendika temsilcisine bildirmekle yükümlüdür.
.. 20/6/2012 tarihli ve 6331 sayılı İş Sağlığı ve Güvenliği Kanununun 17 nci
maddesinin altıncı fıkrasında öngörülen eğitimleri vermekle ve iş sağlığı ve
güvenliği açısından gereken tedbirleri almakla, geçici işçi de bu eğitimlere
katılmakla yükümlüdür.

Geçici işçinin, geçici işçiyi çalıştıran işverenin işyerindeki çalışma
süresince temel çalışma koşulları, bu işçilerin aynı işveren tarafından aynı iş
için doğrudan istihdamı hâlinde sağlanacak koşulların altında olamaz.

Geçici iş ilişkisinde işveren özel istihdam bürosudur. Özel istihdam bürosu
aracılığıyla geçici iş ilişkisi, geçici işçi ile iş sözleşmesi, geçici işçi
çalıştıran işveren ile geçici işçi sağlama sözleşmesi yapmak suretiyle yazılı
olarak kurulur. Özel istihdam bürosu ile geçici işçi çalıştıran işveren
arasında yapılacak geçici işçi sağlama sözleşmesinde; sözleşmenin başlangıç ve
bitiş tarihi, işin niteliği, özel istihdam bürosunun hizmet bedeli, varsa
geçici işçi çalıştıran işverenin ve özel istihdam bürosunun özel yükümlülükleri
yer alır. Geçici işçinin, Türkiye İş Kurumundan veya bir başka özel istihdam
bürosundan hizmet almasını ya da iş görme edimini yerine getirdikten sonra
geçici işçi olarak çalıştığı işveren veya farklı bir işverenin işyerinde
çalışmasını engelleyen hükümler konulamaz. Geçici işçi ile yapılacak iş
sözleşmesinde, işçinin ne kadar süre içerisinde işe çağrılmazsa haklı nedenle
iş sözleşmesini feshedebileceği belirtilir. Bu süre üç ayı geçemez.

(f) bendi kapsamında kurulan geçici iş ilişkisinde, geçici işçi çalıştıran
işveren işyerinde bir ayın üzerinde çalışan geçici işçilerin ücretlerinin
ödenip ödenmediğini çalıştığı süre boyunca her ay kontrol etmekle, özel
istihdam bürosu ise ücretin ödendiğini gösteren belgeleri aylık olarak geçici
işçi çalıştıran işverene ibraz etmekle yükümlüdür. Geçici işçi çalıştıran
işveren, ödenmeyen ücretler mevcut ise bunlar ödenene kadar özel istihdam
bürosunun alacağını ödemeyerek, özel istihdam bürosunun alacağından mahsup
etmek kaydıyla geçici işçilerin en çok üç aya kadar olan ücretlerini doğrudan
işçilerin banka hesabına yatırır. Ücreti ödenmeyen işçiler ve ödenmeyen ücret
tutarları geçici işçi çalıştıran işveren tarafından çalışma ve iş kurumu il
müdürlüğüne bildirilir.

Sözleşmede belirtilen sürenin dolmasına rağmen geçici iş ilişkisinin devam
etmesi hâlinde, geçici işçi çalıştıran işveren ile işçi arasında sözleşmenin
sona erme tarihinden itibaren belirsiz süreli iş sözleşmesi kurulmuş sayılır.
Bu durumda özel istihdam bürosu işçinin geçici iş ilişkisinden kaynaklanan
ücretinden, işçiyi gözetme borcundan ve sosyal sigorta primlerinden sözleşme
süresiyle sınırlı olmak üzere sorumludur.

Geçici işçi, işyerine ve işe ilişkin olmak kaydıyla kusuru ile neden olduğu
zarardan, geçici işçi çalıştıran işverene karşı sorumludur.

==== HOLDİNG BÜNYESİ İÇİNDE

İşverenin, devir sırasında yazılı rızasını almak suretiyle bir işçisini,
holding bünyesi içinde veya aynı şirketler topluluğuna bağlı başka bir
işyerinde iş görme edimini yerine getirmek üzere geçici olarak devretmesi
hâlinde de geçici iş ilişkisi kurulmuş olur.

Geçici iş ilişkisi, yazılı olarak altı ayı geçmemek üzere kurulabilir ve en
fazla iki defa yenilenebilir. İşçisini geçici olarak devreden işverenin ücret
ödeme yükümlülüğü devam eder. Geçici iş ilişkisi kurulan işveren, işçinin
kendisinde çalıştığı sürede ödenmeyen ücretinden, işçiyi gözetme borcundan ve
sosyal sigorta primlerinden, devreden işveren ile birlikte sorumludur.

== DEVİR

=== İŞ SÖZLEŞMESİNİN DEVRİ

Borçlar Kanunu 429'a göre "_Hizmet sözleşmesi, ancak işçinin yazılı rızası
alınmak suretiyle, sürekli olarak başka bir işverene devredilebilir. Devir
işlemiyle, devralan, bütün hak ve borçları ile birlikte, hizmet sözleşmesinin
işveren tarafı olur. Bu durumda, işçinin, hizmet süresine bağlı hakları
bakımından, devreden işveren yanında işe başladığı tarih esas alınır._"

[NOTE]
====
TBK 429'da rızanın hangi anda alınmasına dair bir hüküm yoktur. TBK 205/2 ise
"_Sözleşmeyi devralan ile devreden arasında yapılan ve sözleşmede kalan diğer
tarafça önceden verilen izne dayanan veya sonradan onaylanan anlaşma da,
sözleşmenin devri hükümlerine tabidir_" demektedir.

Doktrinde TBK 205/2'nin uygulanıp uygulanmayacağı yönünde tartışmalar vardır.
Bazı yazarlar bu hükmün uygulanması gerektiğini söylerken bazı yazarlar ise bu
hükmün İş Hukuku'na uygun olmayacağını ve iznin devir anında alınması
gerektiğini savunmaktadır.
====

=== İŞYERİNİN DEVRİ

İşyeri veya işyerinin bir bölümü hukukî bir işleme dayalı olarak başka birine
devredildiğinde, devir tarihinde işyerinde veya bir bölümünde mevcut olan iş
sözleşmeleri bütün hak ve borçları ile birlikte devralana geçer.

Devralan işveren, işçinin hizmet süresinin esas alındığı haklarda, işçinin
devreden işveren yanında işe başladığı tarihe göre işlem yapmakla yükümlüdür.

Yukarıdaki hükümlere göre devir halinde, devirden önce doğmuş olan ve devir
tarihinde ödenmesi gereken borçlardan devreden ve devralan işveren birlikte
sorumludurlar. Ancak bu yükümlülüklerden devreden işverenin sorumluluğu devir
tarihinden itibaren iki yıl ile sınırlıdır

NOTE: Kıdem tazminatı alacağı devirden sonra doğan bir alacaktır ancak buna
rağmen devreden bu alacaktan sorumludur ve burada bir süre sınırı yoktur. Zira
1457 sayılı mülga İş Kanununun yürürlükte olan 14. maddesi özel bir
düzenlemedir.

Tüzel kişiliğin birleşme veya katılma ya da türünün değişmesiyle sona erme
halinde birlikte sorumluluk hükümleri uygulanmaz.

Devreden veya devralan işveren iş sözleşmesini sırf işyerinin veya işyerinin
bir bölümünün devrinden dolayı feshedemez ve devir işçi yönünden fesih için
haklı sebep oluşturm az. Devreden veya devralan işverenin ekonomik ve
teknolojik sebeplerin yahut iş organizasyonu değişikliğinin gerekli kıldığı
fesih hakları veya işçi ve işverenlerin haklı sebeplerden derhal fesih hakları
saklıdır.

Yukarıdaki hükümler, iflas dolayısıyla malvarlığının tasfiyesi sonucu işyerinin
veya bir bölümünün başkasına devri halinde uygulanmaz.

NOTE: Asıl işveren-alt işveren ilişkisi hukuka uygun şekilde kurulmuşsa alt
işveren değişmesine rağmen alt işverenin işçileri çalışmalarına asıl işverenin
işyerinde aynen devam ettiği durumlarda Yargıtay kıyas yoluyla işyerinin devri
hükümlerinin uygulanmasını kabul ediyor.

== İŞÇİNİN BORÇLARI

=== İŞ GÖRME BORCU

İş görme borcunun iki ayrı boyutu vardır:

. *İşin bizzat yapılması*: "_Sözleşmeden veya durumun gereğinden aksi
anlaşılmadıkça, işçi yüklendiği işi bizzat yapmakla yükümlüdür._"
+
İşçinin bizzat yapmakla yükümlü olduğu iş, sözleşmede belirlenen iştir.
İşveren işçinin üstlendiği işte esaslı bir değişiklik yapacaksa işçinin
rızasını almak zorundadır.
+
"_İşveren, iş sözleşmesiyle veya iş sözleşmesinin eki niteliğindeki personel
yönetmeliği ve benzeri kaynaklar ya da işyeri uygulamasıyla oluşan çalışma
koşullarında esaslı bir değişikliği ancak durumu işçiye yazılı olarak bildirmek
suretiyle yapabilir. Bu şekle uygun olarak yapılmayan ve işçi tarafından altı
işgünü içinde yazılı olarak kabul edilmeyen değişiklikler işçiyi bağlamaz. İşçi
değişiklik önerisini bu süre içinde kabul etmezse, işveren değişikliğin geçerli
bir nedene dayandığını veya fesih için başka bir geçerli nedenin bulunduğunu
yazılı olarak açıklamak ve bildirim süresine uymak suretiyle iş sözleşmesini
feshedebilir._"
. *İşin özenle yerine getirilmesi*: "_- İşçi, yüklendiği işi özenle yapmak ve
işverenin haklı menfaatinin korunmasında sadakatle davranmak zorundadır._"
+
İşin özenle yapılması, işçinin işi bütün mesleki birikimini kullanarak
layıkıyla ifa etmesidir.
+
İşi özenle görme borcunun ihlali iki şekilde ortaya çıkabilir:

. _İşçinin işi hiç ifa etmemesi_

.. İşveren işin yapılmamasından kaynaklanan zararları talep etme hakkına
sahiptir.
.. İşveren ödemezlik defini kullanarak ücret ödemekten kaçınabilir.
.. Önceden disiplin cezası öngörülmüş ise bu ceza uygulanabilir.
.. İş Kanunu 25/2'nin (h) bendindeki düzenleme çerçevesinde sözleşme sona
erdirilebilir.
. _İşçinin işi kötü ifa etmesi_

.. İşçi işverenin zararlarını karşılamakla yükümlüdür.
.. İş Kanunu 25/2'nin (ı) bendinde belirtilen esaslar çerçevesinde sözleşme
haklı sebeple feshedilebilir.

=== DÜZENLEME VE TALİMATLARA UYMA BORCU

"_İşveren, işin görülmesi ve işçilerin işyerindeki davranışlarıyla ilgili genel
düzenlemeler yapabilir ve onlara özel talimat verebilir. İşçiler, bunlara
dürüstlük kurallarının gerektirdiği ölçüde uymak zorundadırlar._"

=== SADAKAT BORCU

"_İşçi, yüklendiği işi özenle yapmak ve işverenin haklı menfaatinin
korunmasında sadakatle davranmak zorundadır._"

"_İşçi, hizmet ilişkisi devam ettiği sürece, sadakat borcuna aykırı olarak bir
ücret karşılığında üçüncü kişiye hizmette bulunamaz ve özellikle kendi işvereni
ile rekabete girişemez._"

"_İşçi, iş gördüğü sırada öğrendiği, özellikle üretim ve iş sırları gibi
bilgileri, hizmet ilişkisinin devamı süresince kendi yararına kullanamaz veya
başkalarına açıklayamaz. İşverenin haklı menfaatinin korunması için gerekli
olduğu ölçüde işçi, hizmet ilişkisinin sona ermesinden sonra da sır saklamakla
yükümlüdür._"

TIP: Yargıtay bir kararında, görevi sırasında uyuyan bir güvenlik görevlisinin
sözleşmesinin haklı sebeple feshedilmeyeceğini savunmuş ve ilk seferinde
uyarıldıktan sonra devam edilmesi halinde haklı sebep sebei sayılabileceğini
söylemiştir.

=== REKABET ETMEME BORCU

İş görme, sadakat ve düzenleme ve talimatlara uyma borcu sözleşmenin doğmasıyla
kendiliğinden ortaya çıkan borçlardır. Ancak rekabet etmeme borcu ancak ve
ancak tarafların anlaşması halinde *sözleşme bittikten sonra* ortaya çıkar.

"_Fiil ehliyetine sahip olan işçi, işverene karşı, sözleşmenin sona ermesinden
sonra herhangi bir biçimde onunla rekabet etmekten, özellikle kendi hesabına
rakip bir işletme açmaktan, başka bir rakip işletmede çalışmaktan veya bunların
dışında, rakip işletmeyle başka türden bir menfaat ilişkisine girişmekten
kaçınmayı *yazılı* olarak üstlenebilir._"


Geçerli bir rekabet yasağı hükmünün söz konusu olabilmesi için iki temel şart
aranır:

. Rekabet yasağı kaydı, ancak hizmet ilişkisi işçiye müşteri çevresi veya
üretim sırları ya da işverenin yaptığı işler hakkında bilgi edinme imkânı
sağlıyorsa ve aynı zamanda bu bilgilerin kullanılması, işverenin önemli bir
zararına sebep olacak nitelikteyse geçerlidir.
. Rekabet yasağı, işçinin ekonomik geleceğini hakkaniyete aykırı olarak
tehlikeye düşürecek biçimde yer, zaman ve işlerin türü bakımından uygun olmayan
sınırlamalar içeremez ve süresi, özel durum ve koşullar dışında iki yılı
aşamaz.

"_Hâkim, aşırı nitelikteki rekabet yasağını, bütün durum ve koşulları serbestçe
değerlendirmek ve işverenin üstlenmiş olabileceği karşı edimi de hakkaniyete
uygun biçimde göz önünde tutmak suretiyle, kapsamı veya süresi bakımından
sınırlayabilir._"

Rekabet yasağına aykırı davranan işçi, bunun sonucu olarak işverenin uğradığı
bütün zararları gidermekle yükümlüdür. Yasağa aykırı davranış bir ceza koşuluna
bağlanmışsa ve sözleşmede aksine bir hüküm de yoksa, işçi öngörülen miktarı
ödeyerek rekabet yasağına ilişkin borcundan kurtulabilir; ancak, işçi bu
miktarı aşan zararı gidermek zorundadır.

İşveren, ceza koşulu ve doğabilecek ek zararlarının ödenmesi dışında,
sözleşmede yazılı olarak açıkça saklı tutması koşuluyla, kendisinin ihlal veya
tehdit edilen menfaatlerinin önemi ile işçinin davranışı haklı gösteriyorsa,
yasağa aykırı davranışa son verilmesini de isteyebilir.

Rekabet yasağı, işverenin bu yasağın sürdürülmesinde gerçek bir yararının
olmadığı belirlenmişse sona erer.

İş sözleşmesi, haklı bir sebep olmaksızın işveren tarafından veya işverene
yüklenebilen bir nedenle işçi tarafından feshedilirse, rekabet yasağı sona
erer.

== İŞVERENİN BORÇLARI

=== ÜCRET ÖDEME BORCU

Genel anlamda *ücret* bir kimseye bir iş karşılığında işveren veya üçüncü
kişiler tarafından sağlanan ve para ile ödenen tutardır.

IMPORTANT: Ücret unsuru olmayan bir sözleşme iş sözleşmesi olamaz.

*Brüt ücret*, ücretten yasal kesintiler yapılmadan önceki ücrettir. Yasal
kesintiler kesildikten sonra kalan miktara *net ücret* denir. İşçinin
sözleşmeden belirlenmiş işe karşılık aldığı ücrete *çıplak ücret*, bu ücrete
ilave ödemelerin (yemek, yol vs.) eklendikten sonraki ücrete *giydirilmiş
ücret* denir.

TIP: Ücretin parayla ödenmesi kuralı çıplak ücret için geçerlidir. İşveren
ilave ödemeleri ayni olarak da yapabilir.

Emre muharrer senetle (bono ile), kuponla veya yurtta geçerli parayı temsil
ettiği iddia olunan bir senetle veya diğer herhangi bir şekilde ücret ödemesi
yapılamaz.

Ücret, prim, ikramiye ve bu nitelikteki her çeşit istihkak kural olarak, Türk
parası ile işyerinde veya özel olarak açılan bir banka hesabına ödenir.

NOTE: 5 veya daha fazla işçi çalıştıran işyerlerinde işveren işçi ücretlerini
mutlaka banka aracılığıyla ödemek zorundadır.

Ücret en geç ayda bir ödenir. İş sözleşmeleri veya toplu iş sözleşmeleri ile
ödeme süresi bir haftaya kadar indirilebilir.

İşveren, işçiye sözleşmede veya toplu iş sözleşmesinde belirlenen; sözleşmede
hüküm bulunmayan hâllerde ise, asgari ücretten az olmamak üzere emsal ücreti
ödemekle yükümlüdür.

İş sözleşmesi ile çalışan ve bu Kanunun kapsamında olan veya olmayan her türlü
işçinin ekonomik ve sosyal durumlarının düzenlenmesi için Çalışma ve Sosyal
Güvenlik Bakanlığınca Asgari Ücret Tespit Komisyonu aracılığı ile ücretlerin
asgari sınırları en geç iki yılda bir belirlenir.

Ücret alacağı olduğunu ispatlama yükü işçiye aittir.

Ücret alacaklarında zamanaşımı süresi 5 yıldır.

Ücreti ödeme gününden itibaren yirmi gün içinde mücbir bir neden dışında
ödenmeyen işçi, iş görme borcunu yerine getirmekten kaçınabilir. Bu nedenle
kişisel kararlarına dayanarak iş görme borcunu yerine getirmemeleri sayısal
olarak toplu bir nitelik kazansa dahi grev olarak nitelendirilemez. Gününde
ödenmeyen ücretler için mevduata uygulanan en yüksek faiz oranı uygulanır. Bu
işçilerin bu nedenle iş akitleri çalışmadıkları için feshedilemez ve yerine
yeni işçi alınamaz, bu işler başkalarına yaptırılamaz.

NOTE: Yargıtay, bu hakkını kullanan işçinin çalışmadığı süre boyunca ücret
almaya hak kazanmayacağına karar vermiştir. İşçi çalışmıyorsa ancak kanun
ücretin ödenmesiyle ilgili bir düzenleme getirdiyse ücret alacağını talep
edebilir. Yargıtay da kararında buna dayanmıştır. Kürsü ise kanunun ruhuna
aykırı olduğu gerekçesiyle aksi görüşte.

Gelecekteki ücret alacaklarının devredilmesi veya rehnedilmesi geçersizdir.

İşveren, işçiden olan alacağı ile ücret borcunu işçinin rızası olmadıkça takas
edemez. Ancak, işçinin kasten sebebiyet verdiği yargı kararıyla sabit bir
zarardan doğan alacaklar, ücretin haczedilebilir kısmı kadar takas edilebilir.

Ücretin işveren lehine kullanılacağına ilişkin anlaşmalar geçersizdir.

İşveren toplu sözleşme veya iş sözleşmelerinde gösterilmiş olan sebepler
dışında işçiye ücret kesme cezası veremez.

İşçi ücretlerinden ceza olarak yapılacak kesintilerin işçiye derhal
sebepleriyle beraber bildirilmesi gerekir. İşçi ücretlerinden bu yolda
yapılacak kesintiler bir ayda iki gündelikten veya parça başına yahut yapılan
iş miktarına göre verilen ücretlerde işçinin iki günlük kazancından fazla
olamaz.

Her türlü işte uygulanmakta olan çalışma sürelerinin yasal olarak daha aşağı
sınırlara indirilmesi veya işverene düşen yasal bir yükümlülüğün yerine
getirilmesi nedeniyle ya da bu Kanun hükümlerinden herhangi birinin uygulanması
sonucuna dayanılarak işçi ücretlerinden her ne şekilde olursa olsun eksiltme
yapılamaz.

=== İŞÇİYİ KORUMA VE GÖZETME BORCU

İşveren, hizmet ilişkisinde işçinin kişiliğini korumak ve saygı göstermek ve
işyerinde dürüstlük ilkelerine uygun bir düzeni sağlamakla, özellikle işçilerin
psikolojik ve cinsel tacize uğramamaları ve bu tür tacizlere uğramış olanların
daha fazla zarar görmemeleri için gerekli önlemleri almakla yükümlüdür.

İşveren, işyerinde iş sağlığı ve güvenliğinin sağlanması için gerekli her türlü
önlemi almak, araç ve gereçleri noksansız bulundurmak; işçiler de iş sağlığı ve
güvenliği konusunda alınan her türlü önleme uymakla yükümlüdür.

=== EŞİT DAVRANMA BORCU

İş ilişkisinde dil, ırk, renk, cinsiyet, engellilik, siyasal düşünce, felsefî
inanç, din ve mezhep ve benzeri sebeplere dayalı ayrım yapılamaz.

İşveren, esaslı sebepler olmadıkça tam süreli çalışan işçi karşısında kısmî
süreli çalışan işçiye, belirsiz süreli çalışan işçi karşısında belirli süreli
çalışan işçiye farklı işlem yapamaz.

İşveren, biyolojik veya işin niteliğine ilişkin sebepler zorunlu kılmadıkça,
bir işçiye, iş sözleşmesinin yapılmasında, şartlarının oluşturulmasında,
uygulanmasında ve sona ermesinde, cinsiyet veya gebelik nedeniyle doğrudan veya
dolaylı farklı işlem yapamaz.

Aynı veya eşit değerde bir iş için cinsiyet nedeniyle daha düşük ücret
kararlaştırılamaz. İşçinin cinsiyeti nedeniyle özel koruyucu hükümlerin
uygulanması, daha düşük bir ücretin uygulanmasını haklı kılmaz.

NOTE: İş Kanunu madde 5'in işe alım aşamasında uygulanmayacağı kabul
edilmektedir.

İş ilişkisinde veya sona ermesinde yukarıdaki fıkra hükümlerine aykırı
davranıldığında işçi, dört aya kadar ücreti tutarındaki uygun bir tazminattan
başka yoksun bırakıldığı haklarını da talep edebilir. 2821 sayılı Sendikalar
Kanununun 31 inci maddesi hükümleri saklıdır.

20 nci madde hükümleri saklı kalmak üzere işverenin yukarıdaki fıkra
hükümlerine aykırı davrandığını işçi ispat etmekle yükümlüdür. Ancak, işçi bir
ihlalin varlığı ihtimalini güçlü bir biçimde gösteren bir durumu ortaya
koyduğunda, işveren böyle bir ihlalin mevcut olmadığını ispat etmekle yükümlü
olur.

== İŞ SÖZLEŞMESİNİN SONA ERMESİ

=== İKALE

*İkale*, tarafların uzlaşarak aralarındaki sözleşmeyi sona erdirmesidir.

Yargıtay kötü niyetli ikalelere müdahale etmekte ve ikalenin geçerli olup
olmadığını kontrol etmektedir. Yargıtay'ın aradığı şartlar:

. İkale hakkında işçinin işveren tarafından bilgilendirilmiş olması
. Makul bir menfaatin sağlanması

=== SÖZLEŞME SÜRESİNİN DOLMUŞ OLMASI

Belirli süreli hizmet sözleşmesi, aksi kararlaştırılmadıkça, fesih bildiriminde
bulunulmasına gerek olmaksızın, sürenin bitiminde kendiliğinden sona erer.

Belirli süreli sözleşme, süresinin bitiminden sonra örtülü olarak
sürdürülüyorsa, belirsiz süreli sözleşmeye dönüşür.  Ancak, esaslı bir sebebin
varlığı hâlinde, üst üste belirli süreli hizmet sözleşmesi kurulabilir.

Taraflardan her biri, on yıldan uzun süreli hizmet sözleşmesini on yıl
geçtikten sonra, altı aylık fesih bildirim süresine uyarak feshedebilir. Fesih,
ancak bu süreyi izleyen aybaşında hüküm ifade eder.

Sözleşmenin fesih bildirimiyle sona ereceği kararlaştırılmış ve iki taraf da
fesih bildiriminde bulunmamışsa, sözleşme belirsiz süreli sözleşmeye dönüşür.

=== İŞÇİNİN ÖLÜMÜ

Sözleşme, işçinin ölümüyle kendiliğinden sona erer. İşveren, işçinin sağ kalan
eşine ve ergin olmayan çocuklarına, yoksa bakmakla yükümlü olduğu kişilere,
ölüm gününden başlayarak bir aylık; hizmet ilişkisi beş yıldan uzun bir süre
devam etmişse, iki aylık ücret tutarında bir ödeme yapmakla yükümlüdür.

=== İŞVERENİN ÖLÜMÜ

İşverenin ölümü hâlinde, yerini mirasçıları alır. Bu durumda işyerinin
tamamının veya bir bölümünün devri ile gerçekleşen hizmet ilişkisinin devrine
ilişkin hükümler kıyas yoluyla uygulanır.

Hizmet sözleşmesi ağırlıklı olarak işverenin kişiliği dikkate alınmak suretiyle
kurulmuşsa, onun ölümüyle kendiliğinden sona erer. Ancak, işçi sözleşmenin
süresinden önce sona ermesi yüzünden uğradığı zarar için, mirasçılardan
hakkaniyete uygun bir tazminat isteminde bulunabilir.

=== SÜRELİ FESİH

Belirsiz süreli iş sözleşmelerinin feshinden önce durumun diğer tarafa
bildirilmesi gerekir.

İş sözleşmeleri;

.. İşi altı aydan az sürmüş olan işçi için, bildirimin diğer tarafa
yapılmasından başlayarak iki hafta sonra,
.. İşi altı aydan birbuçuk yıla kadar sürmüş olan işçi için, bildirimin diğer
tarafa yapılmasından başlayarak dört hafta sonra,
.. İşi birbuçuk yıldan üç yıla kadar sürmüş olan işçi için, bildirimin diğer
tarafa yapılmasından başlayarak altı hafta sonra,
.. İşi üç yıldan fazla sürmüş işçi için, bildirim yapılmasından başlayarak
sekiz hafta sonra,

feshedilmiş sayılır. Bu süreler asgari olup sözleşmeler ile artırılabilir.

NOTE: İşçi ve işveren bakımından ihbar sürelerinin ayrı ayrı artırılmasının
mümkün olup olmadığı kanunda düzenlenmemiştir. Bir görüşe göre "_Fesih bildirim
sürelerinin her iki taraf için de aynı olması zorunludur; sözleşmede farklı
süreler öngörülmüşse, her iki tarafa da en uzun olan fesih bildirim süresi
uygulanır._" diyen TBK 432/5 uygulanır. Diğer bir görüş ise TBK 432/5'in İş
Hukukuna uygun olmadığını, uzun olan ihbar süresinin uygulanmasının işçi
aleyhine bir durum oluşturduğunu savunmaktadır. Buna göre işçinin işverene
karşı sözleşmeyi sona erdirirken ihbar süresi daha kısaysa bu yararınadır ve
mümkün olmalıdır. Ancak işverenin uyması gereken süre daha azsa bu anlaşma
geçersiz olmalıdır.

İhbar sürelerine uyularak iş sözleşmesi sona erdirildiğinde sona erme anı ihbar
süresinin bitim tarihidir. Henüz ihbar süresi dolmadan bir haklı sebep ortaya
çıkması halinde sözleşmeyi sona erdirmek mümkündür.

Bildirim süreleri içinde işveren, işçiye yeni bir iş bulması için gerekli olan
iş arama iznini iş saatleri içinde ve ücret kesintisi yapmadan vermeye
mecburdur. İş arama izninin süresi günde iki saatten az olamaz ve işçi isterse
iş arama izin saatlerini birleştirerek toplu kullanabilir. Ancak iş arama
iznini toplu kullanmak isteyen işçi, bunu işten ayrılacağı günden evvelki
günlere rastlatmak ve bu durumu işverene bildirmek zorundadır.

WARNING: Yeni iş arama izninin doğması için sözleşmeyi sona erdiren tarafın bir
önemi yoktur.

İşveren yeni iş arama iznini vermez veya eksik kullandırırsa o süreye ilişkin
ücret işçiye ödenir.

İşveren, iş arama izni esnasında işçiyi çalıştırır ise işçinin izin kullanarak
bir çalışma karşılığı olmaksızın alacağı ücrete ilaveten, çalıştırdığı sürenin
ücretini yüzde yüz zamlı öder.

NOTE: İşçinin işten çıkış sebebi yeni iş bulması ise işverenin yeni iş arama
izni vermesine gerek yoktur. İşçi yeni iş bulmuş olduğunu, yeni iş arama izni
almak için gizlerse bu durum sadakat borcuna aykırılık oluşturur ve haklı
nedenle fesih sebebi oluşturabilir.

Verilen ihbar süresinin işlediği devrede işçinin haklarında bir değişiklik
olursa bu değişiklik işçiye yansıyacaktır.

=== PEŞİN ÖDEME YOLUYLA FESİH

*Peşin ödeme yoluyla fesih* de ihbar sürelerine uyularak yapılan bir fesihtir.
Ancak burada işçi ihbar süresi boyunca çalıştırılmayacak ve ihbar süresine
denk gelen ücret işçiye peşin olarak ödenecektir. Bu ücret çıplak değil,
giydirilmiş ücrettir.

CAUTION: İhbar süresine uyulacaksa tam olarak uyulmalı aksi takdirde tam olarak
peşin ödeme yoluyla fesih yapılmalıdır. İhbar süresinin yarısında işçiyi
çalıştırıp geri kalan kısmın ücretini peşin ödemek usulsüz fesihtir.

Doktrine göre işveren sözleşmeyi peşin ödeme yoluyla feshettiğinde sözleşmenin
sona ermesi fesih sürelerinin sona ermesiyle olur ve bu süre içerisinde
haklarda değişme olursa işçiye yansıtılması gerekir.

Yargıtay'ın yerleşik içtihadına göre ise işveren sözleşmeyi peşin ödeme yoluyla
feshetmişse peşin ödemeyi yaptığı tarihte sözleşme sona erer. Dolayısıyla bu
tarihten sonra haklarda meydana gelen değişiklik işçiye yansıtılmaz. Yargıtay
buna iki istisna kabul etmiştir:

. İşveren meydana gelen değişikliklerden işçiyi yararlandırmamak için kötü
niyetle peşin ödeme yoluyla fesih hakkı kullanmışsa
. Sözleşmede bu konuyu düzenleyen açık bir hüküm getirildiyse toplu
sözleşmelerdeki kural gereği

=== USULSÜZ FESİH

Süreli fesih kurallarına uyulmadan bir fesih gerçekleştirilmişse *usulsüz
fesih* söz konusu olur.

. Hiç bildirim süresi verilmemiş olabilir.
. Verilmesi gerekenden eksik süre verilmiş olabilir.
. Peşin ödeme yoluyla yapılan fesihte ücret ödenmemiş ya da eksik ödenmiş
olabilir.

IMPORTANT: Usulsüz fesih söz konusu olduğunda da sözleşme sona erer.

İşçinin veya işverenin yasada öngörülen fesih sürelerine uymadan sözleşmeyi
feshetmeleri durumunda ihbar süresine denk düşecek miktarda bir tazminatı
ödemesi gerekir. Ayrıca bir zararın meydana gelmesi şartı yoktur. Bildirim
yükümlülüğünü ihlal etmiş olmak tazminat sorumluluğu için yeterlidir.

İş sözleşmesinin bildirim şartına uyulmaksızın feshinden kaynaklanan tazminat
için zamanaşımı süresi 5 yıldır.

=== İŞ GÜVENCESİ

İşverenin bildirim şartına uymaması veya bildirim süresine ait ücreti peşin
ödeyerek sözleşmeyi feshetmesi, İş Kanunu'nun 18, 19, 20 ve 21 inci maddesi
hükümlerinin uygulanmasına engel olmaz.

İş Kanunu'nun 18, 19, 20 ve 21 inci maddeleri iş güvencesi hükümleridir.

[caption=""]
.İŞ KANUNU 18 - Feshin geçerli sebebe dayandırılması
====
Otuz veya daha fazla işçi çalıştıran işyerlerinde en az altı aylık kıdemi olan
işçinin belirsiz süreli iş sözleşmesini fesheden işveren, işçinin
yeterliliğinden veya davranışlarından ya da işletmenin, işyerinin veya işin
gereklerinden kaynaklanan geçerli bir sebebe dayanmak zorundadır. Yer altı
işlerinde çalışan işçilerde kıdem şartı aranmaz.

Altı aylık kıdem hesabında bu Kanunun 66 ncı maddesindeki süreler dikkate alınır.

Özellikle aşağıdaki hususlar fesih için geçerli bir sebep oluşturmaz:

.. Sendika üyeliği veya çalışma saatleri dışında veya işverenin rızası ile
çalışma saatleri içinde sendikal faaliyetlere katılmak.
.. İşyeri sendika temsilciliği yapmak.
.. Mevzuattan veya sözleşmeden doğan haklarını takip veya yükümlülüklerini
yerine getirmek için işveren aleyhine idari veya adli makamlara başvurmak veya
bu hususta başlatılmış sürece katılmak.
.. Irk, renk, cinsiyet, medeni hal, aile yükümlülükleri, hamilelik, doğum, din,
siyasi görüş ve benzeri nedenler.
.. 74 üncü maddede öngörülen ve kadın işçilerin çalıştırılmasının yasak olduğu
sürelerde işe gelmemek.
.. Hastalık veya kaza nedeniyle 25 inci maddenin (I) numaralı bendinin (b) alt
bendinde öngörülen bekleme süresinde işe geçici devamsızlık.

İşçinin altı aylık kıdemi, aynı işverenin bir veya değişik işyerlerinde geçen
süreler birleştirilerek hesap edilir. İşverenin aynı işkolunda birden fazla
işyerinin bulunması halinde, işyerinde çalışan işçi sayısı, bu işyerlerinde
çalışan toplam işçi sayısına göre belirlenir.

İşletmenin bütününü sevk ve idare eden işveren vekili ve yardımcıları ile
işyerinin bütününü sevk ve idare eden ve işçiyi işe alma ve işten çıkarma
yetkisi bulunan işveren vekilleri hakkında bu madde, 19 ve 21 inci maddeler ile
25 inci maddenin son fıkrası uygulanmaz.
====

[caption=""]
.İŞ KANUNU 19 - Sözleşmenin feshinde usul
====
İşveren fesih bildirimini yazılı olarak yapmak ve fesih sebebini açık ve kesin
bir şekilde belirtmek zorundadır.

Hakkındaki iddialara karşı savunmasını almadan bir işçinin belirsiz süreli iş
sözleşmesi, o işçinin davranışı veya verimi ile ilgili nedenlerle feshedilemez.
Ancak, işverenin 25 inci maddenin (II) numaralı bendi şartlarına uygun fesih
hakkı saklıdır.
====

[caption=""]
.İŞ KANUNU 20 - Fesih bildirimine itiraz ve usulü
====
İş sözleşmesi feshedilen işçi, fesih bildiriminde sebep gösterilmediği veya
gösterilen sebebin geçerli bir sebep olmadığı iddiası ile fesih bildiriminin
tebliği tarihinden itibaren bir ay içinde iş mahkemesinde dava açabilir.
Taraflar anlaşırlarsa uyuşmazlık aynı sürede özel hakeme götürülür.

Feshin geçerli bir sebebe dayandığını ispat yükümlülüğü işverene aittir. İşçi,
feshin başka bir sebebe dayandığını iddia ettiği takdirde, bu iddiasını ispatla
yükümlüdür.  Dava seri muhakeme usulüne göre iki ay içinde sonuçlandırılır.
Mahkemece verilen kararın temyizi halinde, Yargıtay bir ay içinde kesin olarak
karar verir.
====

[caption=""]
.İŞ KANUNU 21 - Geçersiz sebeple yapılan feshin sonuçları
====
İşverence geçerli sebep gösterilmediği veya gösterilen sebebin geçerli olmadığı
mahkemece veya özel hakem tarafından tespit edilerek feshin geçersizliğine
karar verildiğinde, işveren, işçiyi bir ay içinde işe başlatmak zorundadır.
İşçiyi başvurusu üzerine işveren bir ay içinde işe başlatmaz ise, işçiye en az
dört aylık ve en çok sekiz aylık ücreti tutarında tazminat ödemekle yükümlü
olur.

Mahkeme veya özel hakem feshin geçersizliğine karar verdiğinde, işçinin işe
başlatılmaması halinde ödenecek tazminat miktarını da belirler.

Kararın kesinleşmesine kadar çalıştırılmadığı süre için işçiye en çok dört aya
kadar doğmuş bulunan ücret ve diğer hakları ödenir.

İşçi işe başlatılırsa, peşin olarak ödenen bildirim süresine ait ücret ile
kıdem tazminatı, yukarıdaki fıkra hükümlerine göre yapılacak ödemeden mahsup
edilir. İşe başlatılmayan işçiye bildirim süresi verilmemiş veya bildirim
süresine ait ücret peşin ödenmemişse, bu sürelere ait ücret tutarı ayrıca
ödenir.

İşçi kesinleşen mahkeme veya özel hakem kararının tebliğinden itibaren on
işgünü içinde işe başlamak için işverene başvuruda bulunmak zorundadır. İşçi bu
süre içinde başvuruda bulunmaz ise, işverence yapılmış olan fesih geçerli bir
fesih sayılır ve işveren sadece bunun hukuki sonuçları ile sorumlu olur.
====

[NOTE]
====
İşveren altı aylık kıdem süresinin dolmasına birkaç gün kala iş ilişkisini sona
erdirirse işçi altı aylık süreyi tamamlamadığı için işe iade davası açamayacak
mıdır?

Yargıtay burada TBK 175'teki "_Taraflardan biri, koşulun gerçekleşmesine
dürüstlük kurallarına aykırı olarak engel olursa, koşul gerçekleşmiş sayılır._"
hükmünün kıyasen uygulanacağını ve işçinin işe iade davası açabileceğini kabul
ediyor.

Doktrine göre ise bu durumda koşul gerçekleşmediği için işe iade davası
açılamaz ancak kötü niyetli bir fesih olduğu için kötü niyet tazminatı gündeme
gelir.
====

18 inci maddenin birinci fıkrası uyarınca İş Kanunu'nun 18, 19, 20 ve 21 inci
maddelerinin uygulanma alanı dışında kalan işçilerin iş sözleşmesinin, fesih
hakkının kötüye kullanılarak sona erdirildiği durumlarda işçiye bildirim
süresinin üç katı tutarında tazminat ödenir.

Kötü niyet tazminatı yaptırımı işverenin işçiyi kötü niyetli olarak işten
çıkarmasına karşılık sadece iş güvencesine tabi olmayan işçiler için
geçerlidir. İşçi kötü niyetli olarak iş sözleşmesini sona erdirirse kötü niyet
tazminatı gündeme gelmez, işveren genel hükümlere başvuracaktır.

CAUTION: Kötü niyetli fesih gerçekleştirilirken aynı zamanda ihbar süresine de
uyulmamışsa ihbar tazminatı da devreye girecektir. Bu iki tazminat birbirinden
bağımsızdır. Fesih için bildirim şartına da uyulmaması ayrıca tazminat
ödenmesini gerektirir.

=== GEÇERLİ SEBEPLER

Geçerli fesih sebebi olarak kabul edilen sebepler haklı fesih sebepleri kadar
ağır olmayan nedenlerdir. Haklı sebeplerin varlığı durumunda iş sözleşmesinin
devam etmesi taraflar için çekilmez hale gelmiştir.

Geçerli fesih sebeplerinin hepsi yargı denetimine açıktır. İşçi konuyu yargıya
taşıdığı takdirde mahkeme böyle bir sebebin gerçekte var olup olmadığını
araştıracaktır.

==== İŞÇİNİN KENDİSİNDEN KAYNAKLANAN SEBEPLER

. *İşçinin yetersizliği*

.. _Fiziki yetersizlik_

... *Hastalık*

.... Uzun süreli hastalığın geçerli fesih sebebi oluşturabilmesi için işçinin
kıdemine göre tabi olduğu bildirim süresinin üzerinden altı hafta geçmesi
gerekir.
.... Kısa süreli hastalıklarda ise hastalığın işyerinde birtakım olumsuzluklar
yaratıyor olması gerekir.

... *Yaşlılık*: Yargıtay ve doktrin tarafından kişinin belirli bir yaşa
ulaşması geçerli bir fesih sebebi olarak kabul edilmemektedir. Yaşlılık
sebebiyle performansta bir düşüş söz konusuysa yaşlılıktan değil mesleki
yetersizlikten dolayı sözleşmeyi sona erdirmek mümkündür.

.... Ekonomik yeniliklerden dolayı işyerinden bir grup işçinin çıkarılması söz
konusuysa Yargıtay öncelikle belirli bir yaşa gelmiş olanların çıkartılması
geçerli bir fesih sebebi oluşturabilir demektedir.
.... Bazı mesleklerde belirli bir yaşa gelmiş olmak o mesleğin niteliğiyle
bağdaşmaz. Bu durumlarda da yaşlılık geçerli fesih sebebi sayılabilir.
.... İşyerinin iç yönetmeliğinde belirli yaşa gelenlerin işten çıkarılacağına
dair bir hüküm varsa ve bu hükümler objektif ve genel ise Yargıtay bunu kabul
etmektedir.

.. _Mesleki yetersizlik:_ İşçinin mesleki yetersizliği kural olarak geçerli bir
fesih sebebidir. Bunun için işçi ne kadar çalışması gerektiğini bilmeli, bir
performans değerlendirme kriteri hazırlanmış olmalı ve bu işçiye bildirilmiş
olmalıdır.
+
İşçinin yapamayacağı bilinen bir işin işçiye verilip sonra bunun geçerli sebep
olarak öne sürülmesi geçerli değildir.
+
İşçinin bir işi sürdürmek için gerekli olan yasal izni kaybetmesi de geçerli
fesih sebebi oluşturur.
. *Akdin esaslı olmayan unsurlarında yanıltma:* Akdin esaslı unsurlarında
yanıltma söz konusuysa bu bir haklı sebep oluşur. Yanıltmanın gerçekleştiği
unsur esaslı değilse geçerli fesih sebebi oluşturabilir.
. *İşi aksatacak kadar devamsızlık:* Haklı sebep oluşturmayacak ancak işi
aksatacak kadar devamsızlık yapıldıysa geçerli fesih sebebi gündeme gelebilir.
. *İşçinin ödevini eksik veya kötü olarak yerine getirmesi*
. *İşçinin ücretlerine çok sık haciz konması*

==== İŞYERİNDEN KAYNAKLANAN SEBEPLER

. *Ekonomik güçlükler*
. *Yeniden yapılanma*
. *Teknolojik yenilikler*

IMPORTANT: Bu üç sebebin hepsi istihdam fazlasına yol açmalıdır.

=== FESHİN SON ÇARE OLMASI İLKESİ

Bu konuda herhangi bir düzenleme olmamasına rağmen Yargıtay buna çok önem
vermektedir. Geçerli bir fesih sebebi olsa bile fesih yapılmadan önce işverenin
başka çözümler araması gerekir. Yargıtay'a göre işletmesel kararla varılmak
istenen sonuca fesihten başka bir yolla ulaşmak mümkünse geçerli bir fesih
sebebinden bahsedilemez.

=== TOPLU İŞÇİ ÇIKARMA

İşveren; ekonomik, teknolojik, yapısal ve benzeri işletme, işyeri veya işin
gerekleri sonucu toplu işçi çıkarmak istediğinde, bunu en az otuz gün önceden
bir yazı ile, işyeri sendika temsilcilerine, ilgili bölge müdürlüğüne ve
Türkiye İş Kurumuna bildirir.

İşyerinde çalışan işçi sayısı:

.. 20 ile 100 işçi arasında ise, en az 10 işçinin,
.. 101 ile 300 işçi arasında ise, en az yüzde on oranında işçinin,
.. 301 ve daha fazla ise, en az 30 işçinin,

İşine 17 nci madde uyarınca ve bir aylık süre içinde aynı tarihte veya farklı
tarihlerde son verilmesi toplu işçi çıkarma sayılır.

Yapılacak bildirimde işçi çıkarmanın sebepleri, bundan etkilenecek işçi sayısı
ve grupları ile işe son verme işlemlerinin hangi zaman diliminde
gerçekleşeceğine ilişkin bilgilerin bulunması zorunludur.

Bildirimden sonra işyeri sendika temsilcileri ile işveren arasında yapılacak
görüşmelerde, toplu işçi çıkarmanın önlenmesi ya da çıkarılacak işçi sayısının
azaltılması yahut çıkarmanın işçiler açısından olumsuz etkilerinin en aza
indirilmesi konuları ele alınır. Görüşmelerin sonunda, toplantının yapıldığını
gösteren bir belge düzenlenir.

Fesih bildirimleri, işverenin toplu işçi çıkarma isteğini bölge müdürlüğüne
bildirmesinden otuz gün sonra hüküm doğurur. İhbar süreleri bu 30 günün
bitmesinden sonra işlemeye başlar. Bu hükme uyulmaması feshi geçersiz kılacağı
gibi işveren işçi başına 584 TL idari para cezası ödemek zorunda kalacaktır.

İşyerinin bütünüyle kapatılarak kesin ve devamlı suretle faaliyete son
verilmesi halinde, işveren sadece durumu en az otuz gün önceden ilgili bölge
müdürlüğüne ve Türkiye İş Kurumuna bildirmek ve işyerinde ilan etmekle
yükümlüdür. İşveren toplu işçi çıkarmanın kesinleşmesinden itibaren altı ay
içinde aynı nitelikteki iş için yeniden işçi almak istediği takdirde
nitelikleri uygun olanları tercihen işe çağırır.

Mevsim ve kampanya işlerinde çalışan işçilerin işten çıkarılmaları hakkında,
işten çıkarma bu işlerin niteliğine bağlı olarak yapılıyorsa, toplu işçi
çıkarmaya ilişkin hükümler uygulanmaz.

İşveren toplu işçi çıkarılmasına ilişkin hükümleri 18, 19, 20 ve 21 inci madde
hükümlerinin uygulanmasını engellemek amacıyla kullanamaz; aksi halde işçi bu
maddelere göre dava açabilir.

=== FESİH BİLDİRİMİNE İTİRAZ

İş sözleşmesi feshedilen işçi, fesih bildiriminde sebep gösterilmediği veya
gösterilen sebebin geçerli bir sebep olmadığı iddiası ile fesih bildiriminin
tebliği tarihinden itibaren bir ay içinde iş mahkemesinde dava açabilir.
Taraflar anlaşırlarsa uyuşmazlık aynı sürede özel hakeme götürülür.

TIP: 2018'te yürürlüğe girecek değişiklik ile feshe itiraz için mahkemeden önce
arabulucuya gidilmesi şarttır.

Feshe itiraz için ihbar süresinin dolmasını beklemek şart değildir.

Feshin geçerli bir sebebe dayandığını ispat yükümlülüğü işverene aittir. İşçi,
feshin başka bir sebebe dayandığını iddia ettiği takdirde, bu iddiasını ispatla
yükümlüdür.

İşe iade talebinin haklı olmadığı sonucuna varılırsa hiçbir parasal sonuç
doğmaz, sadece iş sözleşmesinin geçerli nedenle sona erdirilmesinin sonuçları
doğar. Böylece işçi iş güvencesine özgü parasal imkanlardan yararlanamaz.

Dava seri muhakeme usulüne göre iki ay içinde sonuçlandırılır. Mahkemece
verilen kararın temyizi halinde, Yargıtay bir ay içinde kesin olarak karar
verir.

İşverence geçerli sebep gösterilmediği veya gösterilen sebebin geçerli olmadığı
mahkemece veya özel hakem tarafından tespit edilerek feshin geçersizliğine
karar verildiğinde, işveren, işçiyi bir ay içinde işe başlatmak zorundadır.
İşçiyi başvurusu üzerine işveren bir ay içinde işe başlatmaz ise, işçiye en az
dört aylık ve en çok sekiz aylık ücreti tutarında tazminat ödemekle yükümlü
olur.

Mahkeme veya özel hakem feshin geçersizliğine karar verdiğinde, işçinin işe
başlatılmaması halinde ödenecek tazminat miktarını da belirler.

Kararın kesinleşmesine kadar çalıştırılmadığı süre için işçiye en çok dört aya
kadar doğmuş bulunan ücret ve diğer hakları ödenir.

İşçi işe başlatılırsa, peşin olarak ödenen bildirim süresine ait ücret ile
kıdem tazminatı, yukarıdaki fıkra hükümlerine göre yapılacak ödemeden mahsup
edilir. İşe başlatılmayan işçiye bildirim süresi verilmemiş veya bildirim
süresine ait ücret peşin ödenmemişse, bu sürelere ait ücret tutarı ayrıca
ödenir.

İşçi kesinleşen mahkeme veya özel hakem kararının tebliğinden itibaren on
işgünü içinde işe başlamak için işverene başvuruda bulunmak zorundadır. İşçi bu
süre içinde başvuruda bulunmaz ise, işverence yapılmış olan fesih geçerli bir
fesih sayılır ve işveren sadece bunun hukuki sonuçları ile sorumlu olur.

Yargıtay'a göre:

. 10 iş günlük süre içerisinde işçinin başvuruda bulunmaması halinde fesih
geçerli hale gelir.
. 10 iş günlük süre içerisinde işçinin başvuruda bulunması ve işverenin de
başvuruyu kabul etmesine rağmen işçinin işe gitmemesi halinde işçi hiç
başvurmamış sayılır ve fesih geçerli hale gelir.
. 10 iş günlük süre içerisinde işçinin başvuruda bulunması ve işverenin de
kabul etmesi üzerine işçi işe başlarsa eski iş ilişkisi hiç fesih yapılmamış
gibi devam eder. İhbar tazminatı ile kıdem tazminatı ödenmişse bir dayanağı
kalmadığı için mahsup edilir. Ücreti ödenen 4 aylık süre kıdeme eklenir.
+
CAUTION: İşveren, 4 aylık boşta geçen ücretin alınmayacağı şeklinde şartlar öne
süremez. Eski iş ilişkisi *aynen* devam eder.
. İşçi 10 iş günü içinde müracaat etmesine rağmen işe başlatılmazsa iş
sözleşmesi feshedilmiş olur. Sözleşmenin fesih tarihi 1 aylık işe başlatma
süresinin sonudur. Eğer bir aylık süre bitmeden işçinin işe başlatılmayacağı
kesin şekilde belirtildiyse sözleşme bu beyanın yapıldığı tarihte sona erer.
. İşçi dava sürerken başka bir işyerinde çalışmaya başlarsa buradan elde ettiği
gelir bir görüşe göre mahsup edilirken bir görüşe göre mahsup edilemez.
. Dava devam ederken işçin işe davet edilmesi üzerine işe başlaması halinde işe
iade ve iş güvencesi talepleri konusuz kalmaktadır. Ancak 4 aylık ücretin hükme
bağlanması gerekir.
. Dava devam ederken işçin işe davet edilmesi üzerine işçinin bu daveti
reddetmesinde haklı menfaati vardır. Kabul etmediği için kötü niyetli olduğu
sonucuna varılamaz.
. Dava devam ederken işyerinin kapanması feshi geçerli hale getirmez. Zira
fesih yapıldığında işyeri faal durumdadır. Doktrin ise işçinin iade edileceği
bir işyeri kalmadığına göre kapanma tarihine kadarki boşta geçen süreye ait
ücret ve yargılama giderleri devam eder ancak işe iadeye ve iş güvencesi
tazminatına ilişkin hüküm kurulamaz demektedir.
. İşçi dava açmadan ölürse dava açma hakkı kişiye bağlı hak olduğundan
mirasçıları dava açamaz.
. Yargılama devam ederken işçinin hayatını kaybetmesi durumunda işe iade, iş
güvencesi tazminatı ve boşta geçen süre ücreti taleplerinin reddine karar
verilir. Yargılama masraflarının kime yükletileceği ve vekalet ücretiyle ilgili
sonuçlar hakkında karar verilir. Doktrin boşta geçen süre ücreti de sonuca
bağlanmalıdır dese de Yargıtay bunu kabul etmemektedir.
. İşe iade davası sonuçlandıktan sonra işçi işverene başvurmuş ve sonrasında
ölmüş ise 4 aylık boşta geçen süre ücreti için mirasçıları talepte bulunabilir.

=== ÇALIŞMA KOŞULLARINDA ESASLI DEĞİŞİKLİK

İşverenin yapmak istediği değişiklik işçinin durumunu ağırlaştırıyorsa esaslı
değişiklik söz konusudur. Esaslı olmayan değişiklikler işveren tarafından tek
taraflı şekilde yönetim hakkına dayanılarak yapılabilir.

Taraflar aralarında anlaşarak çalışma koşullarını her zaman değiştirebilir.
Çalışma koşullarında değişiklik geçmişe etkili olarak yürürlüğe konulamaz.

İşveren, iş sözleşmesiyle ya da işyeri uygulamasıyla oluşan çalışma
koşullarında esaslı bir değişikliği ancak durumu işçiye yazılı olarak bildirmek
suretiyle yapabilir. Bu şekle uygun olarak yapılmayan ve işçi tarafından altı
işgünü içinde yazılı olarak kabul edilmeyen değişiklikler işçiyi bağlamaz.

İşçi değişiklik önerisini bu süre içinde kabul etmezse, işveren değişikliğin
geçerli bir nedene dayandığını veya fesih için başka bir geçerli nedenin
bulunduğunu yazılı olarak açıklamak ve bildirim süresine uymak suretiyle iş
sözleşmesini feshedebilir. İşçi bu durumda süreli fesih ve iş güvencesi
hükümlerine göre dava açabilir.

TIP: Yargıtay'a göre uzun bir süre değişikliklere uygun olarak çalışmak
değişikliğin zımni kabulü anlamına gelir.

İş sözleşmesinin içinde, işverene bütün çalışma koşullarında tek taraflı
değişiklik yetkisi verilmesi geçersizdir. Buna karşılık Yargıtay'a göre
işverene belirli bir çalışma koşulunda tek taraflı değişiklik yetkisi verilmesi
geçerli kabul edilmektedir.

=== HAKLI SEBEPLE DERHAL FESİH

24 ve 25 inci maddelerde gösterilen ahlak ve iyiniyet kurallarına uymayan
hallere dayanarak işçi veya işveren için tanınmış olan sözleşmeyi fesih
yetkisi, iki taraftan birinin bu çeşit davranışlarda bulunduğunu diğer tarafın
*öğrendiği günden başlayarak altı iş günü* geçtikten ve her halde *fiilin
gerçekleşmesinden itibaren bir yıl* sonra kullanılamaz. Ancak işçinin olayda
maddi çıkar sağlaması halinde bir yıllık süre uygulanmaz.

Bu haller sebebiyle işçi yahut işverenden iş sözleşmesini yukarıdaki fıkrada
öngörülen süre içinde feshedenlerin diğer taraftan tazminat hakları saklıdır.

CAUTION: Haklı nedene bağlı fesihte ihbar tazminatı söz konusu olmaz.

==== İŞVERENİN HAKLI SEBEPLE DERHAL FESİH HAKKI

Süresi belirli olsun veya olmasın işveren, aşağıda yazılı hallerde iş
sözleşmesini sürenin bitiminden önce veya bildirim süresini beklemeksizin
feshedebilir:

. *Sağlık sebepleri*

.. İşçinin kendi kastından veya derli toplu olmayan yaşayışından yahut içkiye
düşkünlüğünden doğacak bir hastalığa yakalanması veya engelli hâle gelmesi
durumunda, bu sebeple doğacak devamsızlığın ardı ardına üç iş günü veya bir
ayda beş iş gününden fazla sürmesi.
+
Bu sebepler dışında işçinin hastalık, kaza, doğum ve gebelik gibi hallerde
işveren için iş sözleşmesini bildirimsiz fesih hakkı; belirtilen hallerin
işçinin işyerindeki çalışma süresine göre 17 nci maddedeki bildirim sürelerini
altı hafta aşmasından sonra doğar. Doğum ve gebelik hallerinde bu süre 74 üncü
maddedeki sürenin bitiminde başlar. Ancak işçinin iş sözleşmesinin askıda
kalması nedeniyle işine gidemediği süreler için ücret işlemez.
+
TIP: Doktrinde bir görüşe göre doğum ve gebelik hallerinde bu süre analık izin
sürelerinin bitmesi + ihbar süresi + 6 haftadır. Diğer bir görüşe göre ise
analık izin sürelerinin bitmesinden itibaren 6 hafta geçmesiyle süre
tamamlanmış olur.
.. İşçinin tutulduğu hastalığın tedavi edilemeyecek nitelikte olduğu ve
işyerinde çalışmasında sakınca bulunduğunun Sağlık Kurulunca saptanması
durumunda.
. *Ahlak ve iyi niyet kurallarına uymayan haller ve benzerleri*

.. İş sözleşmesi yapıldığı sırada bu sözleşmenin esaslı noktalarından biri için
gerekli vasıflar veya şartlar kendisinde bulunmadığı halde bunların kendisinde
bulunduğunu ileri sürerek, yahut gerçeğe uygun olmayan bilgiler veya sözler
söyleyerek işçinin işvereni yanıltması.
.. İşçinin, işveren yahut bunların aile üyelerinden birinin şeref ve namusuna
dokunacak sözler sarfetmesi veya davranışlarda bulunması, yahut işveren
hakkında şeref ve haysiyet kırıcı asılsız ihbar ve isnadlarda bulunması.
.. İşçinin işverenin başka bir işçisine cinsel tacizde bulunması.
.. İşçinin işverene yahut onun ailesi üyelerinden birine yahut işverenin başka
işçisine sataşması, işyerine sarhoş yahut uyuşturucu madde almış olarak gelmesi
ya da işyerinde bu maddeleri kullanması.
.. İşçinin, işverenin güvenini kötüye kullanmak, hırsızlık yapmak, işverenin
meslek sırlarını ortaya atmak gibi doğruluk ve bağlılığa uymayan davranışlarda
bulunması.
.. İşçinin, işyerinde, yedi günden fazla hapisle cezalandırılan ve cezası
ertelenmeyen bir suç işlemesi.
.. İşçinin işverenden izin almaksızın veya haklı bir sebebe dayanmaksızın ardı
ardına iki işgünü veya bir ay içinde iki defa herhangi bir tatil gününden
sonraki iş günü, yahut bir ayda üç işgünü işine devam etmemesi.
.. İşçinin yapmakla ödevli bulunduğu görevleri kendisine hatırlatıldığı halde
yapmamakta ısrar etmesi.
.. İşçinin kendi isteği veya savsaması yüzünden işin güvenliğini tehlikeye
düşürmesi, işyerinin malı olan veya malı olmayıp da eli altında bulunan
makineleri, tesisatı veya başka eşya ve maddeleri otuz günlük ücretinin
tutarıyla ödeyemeyecek derecede hasara ve kayba uğratması.
. *Zorlayıcı sebepler:* İşçiyi işyerinde bir haftadan fazla süre ile
çalışmaktan alıkoyan zorlayıcı bir sebebin ortaya çıkması.
. İşçinin gözaltına alınması veya tutuklanması halinde devamsızlığın 17 nci maddedeki
bildirim süresini aşması.

İşçi feshin yukarıdaki bentlerde öngörülen sebeplere uygun olmadığı iddiası ile
18, 20 ve 21 inci madde hükümleri çerçevesinde yargı yoluna başvurabilir.

==== İŞÇİNİN HAKLI SEBEPLE DERHAL FESİH HAKKI

Süresi belirli olsun veya olmasın işçi, aşağıda yazılı hallerde iş sözleşmesini
sürenin bitiminden önce veya bildirim süresini beklemeksizin feshedebilir:

. *Sağlık sebepleri*

.. İş sözleşmesinin konusu olan işin yapılması işin niteliğinden doğan bir
sebeple işçinin sağlığı veya yaşayışı için tehlikeli olursa.
.. İşçinin sürekli olarak yakından ve doğrudan buluşup görüştüğü işveren yahut
başka bir işçi bulaşıcı veya işçinin işi ile bağdaşmayan bir hastalığa
tutulursa.

. *Ahlak ve iyiniyet kurallarına uymayan haller ve benzerleri*

.. İşveren iş sözleşmesi yapıldığı sırada bu sözleşmenin esaslı noktalarından
biri hakkında yanlış vasıflar veya şartlar göstermek yahut gerçeğe uygun
olmayan bilgiler vermek veya sözler söylemek suretiyle işçiyi yanıltırsa.
.. İşveren işçinin veya ailesi üyelerinden birinin şeref ve namusuna dokunacak
şekilde sözler söyler, davranışlarda bulunursa veya işçiye cinsel tacizde
bulunursa.
.. İşveren işçiye veya ailesi üyelerinden birine karşı sataşmada bulunur veya
gözdağı verirse, yahut işçiyi veya ailesi üyelerinden birini kanuna karşı
davranışa özendirir, kışkırtır, sürükler, yahut işçiye ve ailesi üyelerinden
birine karşı hapsi gerektiren bir suç işlerse yahut işçi hakkında şeref ve
haysiyet kırıcı asılsız ağır isnad veya ithamlarda bulunursa.
.. İşçinin diğer bir işçi veya üçüncü kişiler tarafından işyerinde cinsel
tacize uğraması ve bu durumu işverene bildirmesine rağmen gerekli önlemler
alınmazsa.
.. İşveren tarafından işçinin ücreti kanun hükümleri veya sözleşme şartlarına
uygun olarak hesap edilmez veya ödenmezse,
+
Buradaki ücret geniş anlamıyla ücrettir. Sadece yapılan işin karşılığında
verilen ücret değil, ikramiyeler vs. de buna girer.
+
İşçinin ücret artışının yeterli olmaması veya zam isteğinin işverence kabul
edilmemesi haklı fesih sebebi değildir. İşverenin kural olarak ücrete zam yapma
gibi bir yükümlülüğü yoktur.
.. Ücretin parça başına veya iş tutarı üzerinden ödenmesi kararlaştırılıp da
işveren tarafından işçiye yapabileceği sayı ve tutardan az iş verildiği
hallerde, aradaki ücret farkı zaman esasına göre ödenerek işçinin eksik aldığı
ücret karşılanmazsa, yahut çalışma şartları uygulanmazsa.

. *Zorlayıcı sebepler:* İşçinin çalıştığı işyerinde bir haftadan fazla süre ile
işin durmasını gerektirecek zorlayıcı sebepler ortaya çıkarsa.

=== İŞVERENİN HAKSIZ FESHİ

Bir iş sözleşmesinin feshedilmesine yönelik işlemin haksız olması 3 şekilde
gerçekleşebilir:

. Haklı bir fesih sebebi olmamasına rağmen varmış gibi sözleşme feshedilmiştir.
. Haklı bir fesih sebebi var olmasına rağmen ispatlanamıyordur.
. Haklı bir fesih sebebi vardır ancak fesih süre geçtikten sonra yapılmıştır.

IMPORTANT: Fesih haksız olsa da sözleşme sona erer.

İşverenin iş ilişkisini haksız feshetmesi halinde doğacak sonuçlar sözleşmenin
belirli ya da belirsiz süreli iş sözleşmesi olmasına göre farklılık gösterir.

==== BELİRSİZ SÜRELİ İŞ SÖZLEŞMESİ

Belirsiz süreli bir iş sözleşmesi ile çalışan işçi, iş güvencesi hükümlerine
tabi ise işe iade imkanından faydalanabilir.

İşçi iş güvencesine tabi değilse TBK uyarınca:

. İhbar tazminatı isteyebilir.
. Kıdem tazminatına hak kazandıran şartlar gerçekleşmişse kıdem tazminatını
isteyebilir.
. 6 aylık ücreti tutarında haksız fesih tazminatı isteyebilir.

==== BELİRLİ SÜRELİ İŞ SÖZLEŞMESİ

Belirli süreli sözleşmelerde ise, sözleşme süresine uyulmaması durumunda, bu
sürelere uyulmuş olsaydı kazanabileceği miktarı, tazminat olarak isteyebilir.

Belirli süreli hizmet sözleşmesinde işçinin hizmet sözleşmesinin sona ermesi
yüzünden tasarruf ettiği miktar ile başka bir işten elde ettiği veya bilerek
elde etmekten kaçındığı gelir, tazminattan indirilir.

Hâkim, bütün durum ve koşulları göz önünde tutarak, ayrıca miktarını serbestçe
belirleyeceği bir tazminatın işçiye ödenmesine karar verebilir; ancak
belirlenecek tazminat miktarı, işçinin altı aylık ücretinden fazla olamaz.

=== İŞÇİNİN HAKSIZ FESHİ

İşçi, haklı sebep olmaksızın işe başlamadığı veya aniden işi bıraktığı takdirde
işveren, aylık ücretin dörtte birine eşit bir tazminat isteme hakkına sahiptir.

İşverenin, ayrıca ek zararlarının giderilmesini isteme hakkı da vardır.
İşveren zarara uğramamışsa veya uğradığı zarar işçinin aylık ücretinin dörtte
birinden az ise, hâkim tazminatı indirebilir.

Tazminat isteme hakkı takas yoluyla sona ermemişse işveren, işçinin işe
başlamamasından veya işi bırakmasından başlayarak otuz gün içinde, dava veya
takip yoluyla bu hakkını kullanmak zorundadır. Aksi takdirde, tazminat isteme
hakkı düşer.

=== KIDEM TAZMİNATI

*Kıdem tazminatı*, kanunda belirtilen asgari çalışma süresini dolduran kişiye
veya kanuni mirasçılarına, iş sözleşmesinin kanunda sayılan sebepler nedeniyle
sona ermesi halinde kıdemi ve ücreti dikkate alınarak işverence ödenmesi
gereken paradır.

WARNING: 1475 sayılı eski iş kanununun yürürlükte olan tek maddesi kıdem
tazminatını düzenleyen 14. maddedir.

"_İşçinin işe başladığı tarihten itibaren hizmet aktinin devamı süresince her
geçen tam yıl için işverence işçiye 30 günlük ücreti tutarında kıdem tazminatı
ödenir. Bir yıldan artan süreler için de aynı oran üzerinden ödeme yapılır._"

İşçinin kıdem tazminatına hak kazanabilmesi için bir yıllık çalışma süresini
tamamlamış olması gerekir. Bir yıldan az çalışan işçiye çalıştığı süreye
oranlayarak bir ödeme yapılması söz konusu değildir. 1 yıllık süre dolduktan
sonra oranlayarak ödeme yapılabilir.

Kural olarak, istifa eden işçi kıdem tazminatı alamaz. Bu kuralın istisnaları:

. Kadın işçiler evlendikleri tarihten itibaren 1 yıl içerisinde istifa
ederlerse kıdem tazminatı alabilir.
. Muvazzaf askerlik hizmeti dolayısıyla istifa durumunda kıdem tazminatı
alabilir.
. Emeklilik gerekçesiyle istifa eden işçiye kıdem tazminatı ödenir.

[IMPORTANT]
====
İş sözleşmesi işçi tarafından haklı sebeple feshedilmişse, işçi her halde kıdem
tazminatı alabilir.

İşverenin sözleşmeyi haklı sebeple feshi halinde "_ahlak ve iyi niyet
kurallarına uymayan haller ve benzerleri_" başlığı dışındaki bütün sebeplerde
kıdem tazminatı ödenecektir.
====

İşçinin kıdem süresinin başlangıcı, sözleşmenin akdedildiği tarih değil fiilen
çalışmaya başladığı tarihtir. Kıdem süresinin sonu ise iş sözleşmesinin bittiği
tarihtir. Süreli fesih halinde ihbar süresinin bittiği, derhal fesih halinde
fesih beyanının karşı tarafa iletildiği an sözleşmenin bittiği andır.

WARNING: Peşin ödeme ile fesih konusunda doktrin ve Yargıtay arasında görüş
ayrılığı vardır.  Doktrine göre işveren sözleşmeyi peşin ödeme yoluyla
feshettiğinde sözleşmenin sona ermesi fesih sürelerinin sona ermesiyle olur.
Yargıtay'ın yerleşik içtihadına göre ise işveren sözleşmeyi peşin ödeme yoluyla
feshetmişse peşin ödemeyi yaptığı tarihte sözleşme sona erer.

Taraflar deneme süreli bir iş sözleşmesi yapmışlarsa işçinin kıdem süresine
deneme süresi de dahil olur.

Kısmi süreli iş sözleşmesiyle çalışan işçinin kıdemi, tam süreli iş sözleşmesi
gibi hesaplanır.

Bir yıllık çalışma süresi aynı işverenin farklı iş yerlerinde de geçirilebilir.

İşçi işverene ait bir iş yerinde 1 yıldan fazla çalışmış ve kıdem tazminatı
ödenmeden ayrılmışsa sonra bir daha 1 yıl daha çalıştığında eski çalışma süresi
hesaba katılarak kıdemi hesaplanır.

Kıdem tazminatı, işçinin her bir yıllık çalışmasının karşılığında 30 günlük (1
ay değil!) ücreti kadardır. Hesaplamada işçinin son, brüt ve giydirilmiş ücreti
esas alınır.

TIP: Yargıtay'a göre süreklilik arz ediyor olsa bile fazla mesai ücretleri
giydirilmiş ücrete dahil edilmez.

Kıdem tazminatı hesaplanırken yürürlükte olan tavan miktarı gözetilir. Tavan,
en yüksek devlet m yürürlükte olan tavan miktarı gözetilir. Tavan, en yüksek
devlet memurunun (başbakanlık müsteşarı) emekli olduğunda alacağı emekli
ikramiyesinin bir yıllık tutarıdır.

Sözleşmenin feshedildiği tarihten itibaren işçinin faiz isteme hakkı vardır.
Zamanaşımı süresi ise 5 yıldır.

=== YENİ İŞVERENİN SORUMLULUĞU

Süresi belirli olan veya olmayan sürekli iş sözleşmesi ile bir işverenin işine
girmiş olan işçi, sözleşme süresinin bitmesinden önce yahut bildirim süresine
uymaksızın işini bırakıp başka bir işverenin işine girerse sözleşmenin bu
suretle feshinden ötürü, işçinin sorumluluğunun yanında, ayrıca yeni işveren de
aşağıdaki hallerde sorumludur:

.. İşçinin bu davranışına, yeni işe girdiği işveren sebep olmuşsa
.. Yeni işveren, işçinin bu davranışını bilerek işe almışsa
.. Yeni işveren işçinin bu davranışını öğrendikten sonra dahi onu çalıştırmaya
devam ederse

=== İBRANAME

*İbra*, borcun özel bir sona erme sebebi olup, alacaklının alacak hakkından
vazgeçmesini ve bu suretle borçlunun borcundan kurtarılmasını sağlayan
sözleşmedir.

İşçinin işverenden alacağına ilişkin ibra sözleşmesinin geçerli olması için
aşağıdaki şartların gerçekleşmesi gerekir:

. Sözleşmenin yazılı olması
. Sözleşmenin, iş sözleşmesinden bitmesinden *bir ay sonra* yapılması
. İbra konusu alacağın türünün ve miktarının açıkça belirtilmesi
. Alacağın banka aracılığıyla eksiksiz şekilde ödenmesi

=== İŞÇİNİN FESİH HAKKININ CEZAİ ŞART İLE SINIRLANDIRILMASI

Kural olarak haklı fesih yetkisi cezai şarta bağlanamaz, bağlansa da geçerli
olmaz. Ancak işçinin iş sözleşmesini haklı neden dışında sona erdirmesi
yetkisinin sözleşmelerle sınırlandırılabileceği kabul edilmektedir.

TIP: Yargıtay'ın süregelen uygulamasına göre, işveren işçinin eğitimden
geçirilmesini sağlamışsa fesih hakkını cezai şarta bağlayabilir.

Sözleşmede iki taraflı olarak cezai şart öngörülmüşse, işçi en fazla işveren
için öngörülmüş cezai şart ile bağlıdır.

IMPORTANT: Hizmet sözleşmelerine sadece işçi aleyhine koyulan ceza koşulu
geçersizdir.

== İŞİN DÜZENLENMESİ

=== ÇALIŞMA SÜRESİ

Genel bakımdan çalışma süresi haftada *en çok kırkbeş saattir*. Aksi
kararlaştırılmamışsa bu süre, işyerlerinde haftanın çalışılan günlerine eşit
ölçüde bölünerek uygulanır.

Tarafların anlaşması ile haftalık normal çalışma süresi, işyerlerinde haftanın
çalışılan günlerine, günde onbir saati aşmamak koşulu ile farklı şekilde
dağıtılabilir. Bu halde, iki aylık süre içinde işçinin haftalık ortalama çalışma
süresi, normal haftalık çalışma süresini aşamaz.

NOTE: Denkleştirme süresi toplu iş sözleşmeleri ile dört aya kadar
artırılabilir.

TIP: İşçi bir gün dinlendirilmek zorunda olduğu için iş mevzuatındaki
düzenlemelere göre haftada en fazla 6 gün ve her gün en fazla 11 saat
çalıştırılabilir. Dolayısıyla bir işçi haftada en fazla 66 saat
çalıştırılabilir.

=== FAZLA ÇALIŞMA VE FAZLA SÜRELERLE ÇALIŞMA

İşçinin haftalık kırkbeş saatlik sınırın üzerinde yaptığı çalışmalara *fazla
çalışma* adı verilir. İşyerlerinde uygulanacak haftalık çalışma süresi kırkbeş
saatin altında belirlenmişse, belirlenen sürenin üzerinde yapılan ancak kırkbeş
saatin altında olan çalışmalara *fazla sürelerle çalışma* adı verilir.

NOTE: Fazla çalışma süreleri toplamı yılda *270 saatten* fazla olamaz.

11 saatlik süre, fazla çalışma için de sınır oluşturur. Yargıtay kararlarına
göre, kırkbeş saatlik haftalık sınır aşılmamasına rağmen günlük 11 saatin
üstünde bir çalışma varsa fazla çalışma ücretinin ödenmesi gerekir.

Yargıtay'a göre fazla çalıştığını işçinin ispatlaması gerekir. İspat için tanık
dahil her türlü delil kullanılabilir. Fazla çalışma ücretinin ödendiğini ispat
yükü ise işveren üzerindedir.

İşçi fazla çalışma ücreti yerine izin de kullanılabilir. Seçme hakkı işçinindir.
İşveren tek taraflı olarak karar veremez. Her bir saatlik çalışma için bir buçuk
saatlik izin kullanılabilir. İşveren altı aylık süre içerisinde bu izni
kullandırmak zorundadır. Aksi takdirde işçi fazla çalışma ücretini talep
edebilir.

İşçi fazla çalışma yapmışsa her bir saatlik fazla çalışmanın karşılığında %50
zamlı olarak ücret talep edebilir. Fazla sürelerle çalışma söz konusu ise %25
zamlı ücret uygulanır.

CAUTION: Fazla çalışma ücretinin talep edilebilmesi için bu çalışmanın
yapılmasını işveren istemiş olmalıdır. İşçi kendi iradesiyle fazla çalışmışsa,
bunun karşılığında ücret verme zorunluluğu yoktur. Ancak Yargıtay'a göre
işverenin işçiye verdiği iş yükü sebebiyle işçi fazla çalışma yapmak zorunda
kalıyorsa bu durumda işçi ücrete hak kazanır.

=== ARA DİNLENMESİ

İşçiye,

* Dört saat veya daha kısa süreli işlerde *onbeş dakika*
* Dört saatten fazla ve yedibuçuk saate kadar (yedibuçuk saat dahil) süreli
işlerde *yarım saat*
* Yedibuçuk saatten fazla süreli işlerde *bir saat*

ara dinlenmesi verilir. Bu dinlenme süreleri en az olup, aralıksız verilir.

IMPORTANT: Ara dinlenmeleri çalışma süresinden sayılmaz.

=== HAFTA TATİLİ

İşçiye, yedi günlük bir zaman dilimi içerisinde kesintisiz en az yirmidört saat
dinlenme (hafta tatili) verilir. Çalışılmayan hafta tatili günü için işveren
tarafından bir iş karşılığı olmaksızın o günün ücreti tam olarak ödenir.

TIP: Yargıtay'a göre 24 saat olarak verilmesi gereken izin daha az bir süreyle
verilmişse hiç verilmemiş sayılır.

Hafta tatilinde çalışan işçi 2.5 günlük ücrete hak kazanır:

. Her halükarda verilecek bir günlük ücret
. Çalıştırıldığı için verilecek bir günlük ücret
. Fazla mesai için %50 zamlı ücret

=== YILLIK ÜCRETLİ İZİN

İşyerinde işe başladığı günden itibaren, deneme süresi de içinde olmak üzere, en
az bir yıl çalışmış olan işçilere yıllık ücretli izin verilir. *Yıllık ücretli
izin hakkından vazgeçilemez.*

İşçilere verilecek yıllık ücretli izin süresi, hizmet süresi;

.. Bir yıldan beş yıla kadar (beş yıl dahil) olanlara ondört günden,
.. Beş yıldan fazla onbeş yıldan az olanlara yirmi günden,
.. Onbeş yıl ve daha fazla olanlara yirmialtı günden

az olamaz.

NOTE: İşçi 18 yaşında veya daha küçükse ya da 50 yaşında veya daha fazlaysa,
hizmet süresine bakılmaksızın en az yirmi günlük ücretli izine hak kazanır.

Yıllık izin iş günü olarak hesaplanır. Yıllık izin ve ulusal bayram izni
çakışırsa ya da iznin arasında hafta tatili günü olursa işveren bunlar yıllık
izinden düşemez.

İşveren kural olarak izni bölmeden, bir bütün halinde kullandırmak zorundadır.
İşçi ile işveren bunun aksini kararlaştırabilir. Bir parçası 10 günden aşağı
olmadığı sürece istenildiği kadar parçaya bölünebilir.

İş sözleşmesinin, *herhangi bir nedenle* sona ermesi halinde işçinin hak
kazanıp da kullanmadığı yıllık izin sürelerine ait ücreti, sözleşmenin sona
erdiği tarihteki ücreti üzerinden kendisine veya hak sahiplerine ödenir.

Bu ücrete ilişkin zamanaşımı sözleşmenin sona erdiği tarihten itibaren başlar.
Yıllık ücretli izin alacakları beş yıllık zamanaşımı süresine tabidir.

IMPORTANT: Akit devam ederken yıllık izin ücretinin ödenmesi mümkün değildir.
Bunun izin olarak kullandırılması gerekir.

== SENDİKALAR

*Sendika*, işçilerin veya işverenlerin çalışma ilişkilerinde, ortak ekonomik ve
sosyal hak ve çıkarlarını korumak ve geliştirmek için *en az yedi* işçi veya
işverenin bir araya gelerek bir işkolunda faaliyette bulunmak üzere
oluşturdukları tüzel kişiliğe sahip kuruluşları ifade eder. Sendikalar özel
hukuk tüzel kişileridir.

*Konfederasyon*, değişik işkollarında *en az beş sendikanın* bir araya gelerek
oluşturdukları tüzel kişiliğe sahip kuruluşu ifade eder.

=== SENDİKA ÖZGÜRLÜĞÜ

*Çalışanlar ve işverenler*, üyelerinin çalışma ilişkilerinde, ekonomik ve
sosyal hak ve menfaatlerini korumak ve geliştirmek için önceden izin almaksızın
*sendikalar ve üst kuruluşlar* kurma, bunlara serbestçe üye olma ve üyelikten
serbestçe çekilme haklarına sahiptir. Hiç kimse bir sendikaya üye olmaya ya da
üyelikten ayrılmaya zorlanamaz.

*Olumlu sendika özgürlüğü:*

* Bireylerin serbestçe sendika kurma hakkı
* Kurulmuş olan sendikalara üye olma hakkı
* Mevcut birden fazla sendikadan birini seçme hakkı
* Sendika içerisinde faaliyette bulunabilme hakkı
* Sendikanın faaliyetlerinden yararlanma hakkı

*Olumsuz sendika özgürlüğü:*

* Sendikaya girmeme hakkı
* Sendikadan serbestçe ayrılabilme hakkı

=== İŞKOLUNA GÖRE SENDİKALAŞMA İLKESİ

Kanunumuz işkoluna göre sendikalaşma ilkesini benimsemiştir.

NOTE: Kamu işveren sendikalarının, aynı işkolundaki kamu işverenleri tarafından
kurulması ve faaliyette bulunması şartı aranmaz.

Yürürlükte olan kanuna göre 20 değişik işkolu bulunmaktadır. Yasanın arkasında
bulunan cetvelde bunlar sayılmıştır.

TIP: Bir işyerinde yürütülen asıl işe yardımcı işler de, asıl işin girdiği
işkolundan sayılır.

Bir işyerinin girdiği işkolunun tespiti Bakanlıkça yapılır. Bakanlık, tespit
ile ilgili kararını Resmi Gazete'de yayımlar. Bu tespite karşı ilgililer,
kararın yayımından itibaren *on beş gün içinde* dava açabilir. Mahkeme iki ay
içinde karar verir.

=== SENDİKADA KURUCULUK ŞARTLARI

Fiil ehliyetine sahip ve fiilen çalışan gerçek veya tüzel kişiler sendika kurma
hakkına sahiptir.

NOTE: İşçi sendikası için işçi, işveren sendikası için işveren sıfatına sahip
olmak gerekir.

Sendikalar en az yedi kişinin bir araya gelmesiyle kurulur.

*Kürsüye göre* sendika kurucularının fiilen o işkolunda çalışıyor olması
gerekir.

Sendika kurucularının kanunda sayılan suçlardan mahkum edilmemiş olması
gerekir.

=== SENDİKAYA ÜYE OLMAK

*On beş yaşını dolduran* ve İş Kanunu hükümlerine göre *işçi sayılanlar*, işçi
sendikalarına üye olabilir.

İşçi veya işverenler aynı işkolunda ve aynı zamanda birden çok sendikaya üye
olamaz. *Ancak aynı işkolunda ve aynı zamanda farklı işverenlere ait
işyerlerinde çalışan işçiler birden çok sendikaya üye olabilir.* İşçi ve
işverenlerin bu hükme aykırı şekilde *birden çok sendikaya üye olmaları halinde
sonraki üyelikler geçersizdir*.

Üyelik başvurusu, sendika tarafından *otuz gün içinde reddedilmediği takdirde*
üyelik talebi kabul edilmiş sayılır. Haklı bir neden gösterilmeden üyelik
başvurusu kabul edilmeyenler, bu kararın kendilerine tebliğinden itibaren otuz
gün içinde dava açabilir. Mahkemenin kararı kesindir. *Mahkemenin davacı lehine
karar vermesi halinde üyelik, red kararının alındığı tarihte kazanılmış
sayılır*.

Üyelik aidatının miktarı kuruluşların tüzüklerinde belirtilen usul ve esaslara
göre genel kurul tarafından belirlenir. Üyelik ve dayanışma aidatları, yetkili
işçi sendikasının işverene yazılı başvurusu üzerine, işçinin ücretinden
kesilmek suretiyle ilgili sendikaya ödenir.

=== ÜYELİĞİN SONA ERMESİ

Üyelik için taşınması gereken koşullar yitirilirse kural olarak sendika üyeliği
de kendiliğinden ortadan kalkar.

NOTE: İşçi sıfatının sona ermesi üyeliği hemen sona erdirmez. _İşçi sendikası
üyesinin bir yılı geçmemek üzere işsiz kalması üyeliğini etkilemez._

Çekilme, sendikaya bildirim tarihinden itibaren bir ay sonra geçerlilik
kazanır. Çekilenin bir aylık süre içinde başka bir sendikaya üye olması halinde
yeni üyelik bu sürenin bitimi tarihinde kazanılmış sayılır.

Çıkarılma kararına karşı üye, kararın tebliğinden itibaren otuz gün içinde
mahkemeye itiraz edebilir. Mahkeme iki ay içinde kesin olarak karar verir.
Üyelik, çıkarılma kararı kesinleşinceye kadar devam eder.

İşveren veya işveren vekili sıfatını kaybedenlerin sendika ve üst
kuruluşlardaki üyelikleri ve görevleri, bu sıfatı kaybettikleri tarihte
kendiliğinden sona erer.

Sosyal Güvenlik Kurumundan yaşlılık veya malüllük aylığı ya da toptan ödeme
alarak işten ayrılan işçilerin sendika üyeliği sona erer.

İşkolunu değiştirenin sendika üyeliği kendiliğinden sona erer.

Herhangi bir askeri ödev nedeniyle silah altına alınan üyenin üyelik ilişkisi
bu süre içinde askıda kalır.

=== SENDİKANIN ZORUNLU ORGANLARI

. *Genel Kurul*: Karar organıdır.
. *Yönetim Kurulu*: İcra organıdır.
. *Denetleme Kurulu*: Yönetim kurulunu denetler.
. *Disiplin Kurulu*: Kurallara uymayanlara yaptırım uygular.

=== GÜVENCE

==== İŞÇİ KURULUŞU YÖNETİCİLİĞİNİN GÜVENCESİ

İşçi kuruluşunda *yönetici* olduğu için çalıştığı işyerinden ayrılan işçinin iş
sözleşmesi *askıda kalır*. Yönetici dilerse işten ayrıldığı tarihte iş
sözleşmesini bildirim süresine uymaksızın veya sözleşme süresinin bitimini
beklemeksizin fesheder ve kıdem tazminatına hak kazanır.

Yönetici, yöneticilik süresi içerisinde iş sözleşmesini feshederse kıdem
tazminatı fesih tarihindeki emsal ücret üzerinden hesaplanır.

İş sözleşmesi askıya alınan yönetici; sendikanın tüzel kişiliğinin sona ermesi,
seçime girmemek, yeniden seçilmemek veya kendi isteği ile çekilmek suretiyle
görevinin sona ermesi halinde, sona erme tarihinden itibaren bir ay içinde
ayrıldığı işyerinde işe başlatılmak üzere işverene başvurabilir.

İşveren, talep tarihinden itibaren bir ay içinde bu kişileri o andaki şartlarla
eski işlerine veya eski işlerine uygun bir diğer işe başlatmak zorundadır. Bu
kişiler süresi içinde işe başlatılmadığı takdirde, iş sözleşmeleri işverence
feshedilmiş sayılır.

Yukarıda sayılan nedenler dışında yöneticilik görevi sona eren sendika
yöneticisine ise başvuruları halinde işveren tarafından kıdem tazminatı ödenir.
Ödenecek tazminatın hesabında, iyerinde çalışılmış süreler gözönünde
bulundurulur ve fesih anında emsalleri için geçerli olan ücret ve diğer hakları
esas alınır.

==== İŞYERİ SENDİKA TEMSİLCİLİĞİNİN GÜVENCESİ

İşveren, işşyeri sendika temsilcilerinin iş sözleşmelerini *haklı bir neden
olmadıkça* ve nedenini *yazılı olarak açık ve kesin şekilde belirtmedikçe*
feshedemez.

Fesih bildiriminin tebliği tarihinden itibaren bir ay içinde, temsilci veya
üyesi bulunduğu sendika dava açabilir.

Temsilcinin işe iadesine karar verilirse fesih geçersiz sayılarak *temsilcilik
süresini aşmamak kaydıyla* fesih tarihi ile kararın kesinleşme tarihi
arasındaki ücret ve diğer hakları ödenir.

Kararın kesinleşmesinden itibaren altı iş günü içinde işe başlatılmaması
halinde, iş ilişkisinin devam ettiği kabul edilerek ücreti ve diğer hakları
temsilcilik süresince ödenmeye devam edilir.

İşveren, *yazılı rızası olmadıkça* işyeri sendika temsilcisinin işyerini
değiştiremez veya işinde esaslı tarzda değişiklik yapamaz. Aksi halde
değişiklik geçersiz sayılır.

Yukarıdaki hükümler, işyerinde çalışmaya devam eden yöneticiler (*amatör
yöneticiler*) hakkında da uygulanır.

==== SENDİKA ÖZGÜRLÜĞÜNÜN GÜVENCESİ

İşveren, bir sendikaya üye olan işçilerle sendika üyesi olmayan işçiler veya
ayrı sendikalara üye olan işçiler arasında, çalışma şartları veya çalıştırmaya
son verilmesi bakımından herhangi bir ayrım yapamaz. Ücret, ikramiye, prim ve
paraya ilişkin sosyal yardım konularında *toplu iş sözleşmesi hükümleri
saklıdır*.

İşçiler, sendikaya üye olmaları veya olmamaları, iş saatleri dışında veya
işverenin izni ile iş saatleri içinde işçi kuruluşlarının faaliyetlerine
katılmaları veya sendikal faaliyette bulunmalarından dolayı işten çıkarılamaz
veya farklı işleme tabi tutulamaz.

İşveren yukarıdaki hükümlere aykırı hareket ettiği takdirde işçinin bir yıllık
ücretinden az olmamak kaydıyla sendikal tazminata hükmedilir.

== TOPLU İŞ SÖZLEŞMELERİ

*Toplu iş sözleşmesi*, iş sözleşmesinin yapılması, içeriği ve sona ermesine
ilişkin hususları düzenlemek üzere işçi sendikası ile işveren sendikası veya
sendika üyesi olmayan işveren arasında yapılan sözleşmeyi ifade eder.

Toplu iş sözleşmesi, iş sözleşmesinin yapılması, içeriği ve sona ermesine
ilişkin hükümleri içerir.

Toplu iş sözleşmesi, tarafların karşılıklı hak ve borçları ile sözleşmenin
uygulanması ve denetimini ve uyuşmazlıkların çözümü için başvurulacak yolları
düzenleyen hükümleri de içerebilir.

*Toplu iş sözleşmeleri, Anayasaya ve kanunların emredici hükümlerine aykırı
düzenlemeler içeremez.* Normlar hiyerarşisinde önce kanun, sonra toplu iş
sözleşmesi, sonra bireysel iş sözleşmesi gelir. Toplu iş sözleşmesinin
getirdiği haklardan bireysel iş sözleşmesinde vazgeçilemez.

=== YETKİ

Kurulu bulunduğu işkolunda çalışan işçilerin *en az yüzde birinin* üyesi
bulunması şartıyla işçi sendikası, toplu iş sözleşmesinin kapsamına girecek
işyerinde başvuru tarihinde çalışan işçilerin yarıdan fazlasının, işletmede ise
yüzde kırkının kendi üyesi bulunması halinde bu işyeri veya işletme için toplu
iş sözleşmesi yapmaya yetkilidir.

İşletme toplu iş sözleşmeleri için işyerleri bir bütün olarak dikkate alınır
ve yüzde kırk çoğunluk buna göre hesaplanır.

CAUTION: İşletme toplu iş sözleşmelerinde *işletmenin bütünlüğü* ilkesi
hakimdir. İşletmenin sadece bir bölümü için sözleşme yapılması mümkün değildir.
Ancak bütün işyerleri için aynı koşullar bulunması gerekmez. Aynı sözleşme
içerisinde farklı işyerleri için farklı düzenlemeler yapılabilir. Önemli olan
aynı yetki ve aynı sözleşmenin olmasıdır.

İşletmede birden çok sendikanın yüzde kırk veya fazla üyesinin olması durumunda
başvuru tarihinde en çok üyeye sahip sendika toplu iş sözleşmesi yapmaya
yetkilidir.

*Bir işkolunda çalışan işçilerin yüzde birinin tespitinde Bakanlıkça her yıl
ocak ve temmuz aylarında yayımlanan istatistikler esas alınır.*

NOTE: Bir işçi sendikası ile bir işveren sendikası arasında, birden çok üye
işverene ait aynı işkolunda kurulu işyerleri ve işletmeleri kapsayacak şekilde
yapılan sözleşmeye *grup toplu iş sözleşmesi* denir.

Toplu iş sözleşmesi yapmak isteyen işçi sendikası *Bakanlığa* başvurarak
yetkili olduğunun tespitini ister. İşveren sendikası veya sendika üyesi olmayan
işveren de Bakanlığa başvurarak yetkili işçi sendikasının tespitini
isteyebilir.

Başvuru, yürürlükte bir toplu iş sözleşmesi yoksa her zaman yapılabilir.
Yürürlükte bir toplu iş sözleşmesi varsa en erken sözleşmenin süresinin
dolmasından 120 gün önce başvuru yapılabilir.

Bakanlık, kayıtlarına göre başvuru tarihi itibarıyla bir işçi sendikasının
yetkili olduğunu tespit ettiğinde, başvuruyu, işyeri veya işletmedeki işçi ve
üye sayısını, o işkolunda kurulu işçi sendikaları ile taraf olacak işveren
sendikası veya sendika üyesi olmayan işverene *altı iş günü* içinde bildirir.

İşçi sendikasının yetki şartlarına sahip olmadığının ya da işyerinde yetki
şartlarına sahip bir işçi sendikasının bulunmadığının tespiti halinde, bu
bilgiler sadece başvuruyu yapan tarafa bildirilir.

Kendilerine tespit yazısını gönderilen işvi veya işveren sendikaları veya
sendika üyesi olmayan işveren; *taraflardan birinin veya her ikisinin yetki
şartlarına sahip olmadığı* veya *kendisinin bu şartları taşıdığı* yolundaki
itirazını, nedenlerini de göstererek yazının kendilerine tebliğ edildiği
tarihten itibaren *altı iş günü* içinde *iş mahkemesine* yapabilir.

*İşkolunda çalışan işçilerin yüzde birinden daha az üyesi bulunan işçi
sendikası, yetki itirazında bulunamaz.*

Kendisine yetki şartlarına sahip olmadığı bildirilen işçi sendikası, *altı iş
günü* içinde yetkili olup olmadığının tespiti için dava açabilir. Mahkeme
açılan davayı o işkolunda çalışan işçilerin en az yüzde birini üye kaydeden
işçi sendikaları ile işveren sendikası veya sendika üyesi olmayan işverene de
bildirir. Mahkeme davayı iki ay içinde sonuçlandırır.

*İtiraz, karar kesinleşinceye kadar yetki işlemlerini durdurur.*

Tespit yazısına süresi içinde itiraz edilmemişse sürenin bitimini takip eden
altı iş günü içinde; yapılan itiraz reddedilmişse ya da kendisine yetki
şartlarına sahip olmadığı bildirilen sendikanın itirazı sonucunda yetki
şartlarına sahip olduğunu tespit eden kesinleşmiş mahkeme kararının tebliğ
edildiği tarihten itibaren altı iş günü içinde; ilgili sendikaya, Bakanlıkça
bir yetki belgesi verilir.

=== TOPLU GÖRÜŞMEYE ÇAĞRI

Taraflardan biri, yetki belgesinin alındığı tarihten itibaren *on beş gün
içinde* karşı tarafı toplu görüşmeye çağırır. Çağrı tarihi, çağrıyı yapan
tarafça derhal görevli makama bildirilir. *Bu süre içinde çağrı yapılmazsa,
yetki belgesinin hükmü kalmaz.*

Çağrıyı yapan taraf, toplu görüşmede ileri süreceği tekliflerin bütününü çağrı
süresi içinde karşı tarafa vermek zorundadır. Ancak, tarafların toplu görüşme
gereği ileri sürecekleri tekliflerde değişiklik yapma hakları saklıdır.

Çağrının karşı tarafa tebliğ edildiği tarihten itibaren *altı iş günü* içinde
taraflar toplu görüşmenin yer, gün ve saatini aralarında *anlşarak* belirler ve
bunu görevli makama yazı ile bildirir. Anlaşmaya varılamazsa, taraflardan
birinin başvurusu üzerine, yapılacak ilk toplantının yeri, günü ve saati
görevli makamca derhal belirlenir ve taraflara bildirilir.

İşçi sendikası, çağrı tarihinden itibaren *otuz günü içinde yapılacak olan ilk
toplantıya gelmez* veya *aynı süre içinde toplu görüşmeye başlamazsa* yetkisi
düşer.

Toplu görüşmenin süresi, ilk toplantı tarihinden itibaren altmış gündür.

=== TOPLU İŞ SÖZLEŞMESİNİN HÜKMÜ

Toplu iş sözleşmesinde aksi belirtilmedikçe iş sözleşmeleri toplu iş
sözleşmesine aykırı olamaz.

İş sözleşmelerinin toplu iş sözleşmesine aykırı hükümlerinin yerini toplu
iş sözleşmesindeki hükümler alır.

Toplu iş sözleşmesinde iş sözleşmelerine aykırı hükümlerin bulunması halinde
ise iş sözleşmesinin işçi yararına olan hükümleri geçerlidir.

Sona eren toplu iş sözleşmesinin iş sözleşmesine ilişkin hükümleri yenisi
yürürlüğe girinceye kadar iş sözleşmesi hükmü olarak devam eder.

=== TOPLU İŞ SÖZLEŞMESİNDEN YARARLANMA

Toplu iş sözleşmesinden *taraf işçi sendikasının üyeleri* yararlanır.

CAUTION: Asıl işverenin tarafı olduğu bir toplu iş sözleşmesi varsa, o
işyerinde alt işveren işçisi olarak çalışanlar bundan yararlanamaz.

Toplu iş sözleşmesinden, sözleşmenin imzalanması tarihinde *taraf sendikaya üye
olanlar yürürlük tarihinden*, imza tarihinden sonra üye olanlar ise
*üyeliklerinin taraf işçi sendikasınca işverene bildirildiği tarihten* itibaren
yararlanır.

.Yürürlük tarihi geriye yürütülmüş sözleşmeler
****
*Toplu iş sözleşmelerinin yürürlük tarihi geçmiş bir tarih olarak da
belirlenebilir.* Bu durumda imzalandığı tarihte ya da imzalanmaya yakın bir
tarihte sendikaya üye olan işçi hangi andan itibaren sözleşmeden yararlanır?

Kanundaki hükmün lafzı açıktır: "_Toplu iş sözleşmesinden, sözleşmenin
imzalanması tarihinde taraf sendikaya üye olanlar yürürlük tarihinden itibaren
yararlanır._"

Bir grup yazar, hükmün lafzına bağlı kalarak, işçi imza tarihinde sendikaya üye
ise yürürlük tarihi geçmişe yürütülse bile yürürlük tarihinden itibaren
sözleşmeden yararlanacağını kabul etmektedir.

Bu görüşe karşı çıkan yazarlar ise, toplu iş sözleşmesinden yararlanmanın
üyelik şartına bağlandığının hareketle üyeliğin olmadığı bir tarihte toplu iş
sözleşmesinden yararlanılamayacağını savunmaktadır.
****

Toplu iş sözleşmesinin imza tarihi ile yürürlük tarihi arasında iş sözleşmesi
sona eren üyeler de, iş sözleşmelerinin sona erdiği tarihe kadar toplu iş
sözleşmesinden yararlanır.

Toplu iş sözleşmesinin imzası sırasında taraf işçi sendikasına üye olmayanlar,
sonradan işyerine girip de üye olmayanlar veya imza tarihinde taraf işçi
sendikasına üye olup da ayrılanlar veya çıkarılanların toplu iş sözleşmesinden
yararlanabilmeleri, toplu iş sözleşmesinin tarafı olan işçi sendikasına
*dayanışma aidatı* ödemelerine bağlıdır. Bunun için işçi sendikasının onayı
aranmaz. Dayanışma aidatı ödemek suretiyle toplu iş sözleşmesinden yararlanma,
talep tarihinden itibaren geçerlidir. *İmza tarihinden önceki talepler, imza
tarihi itibarıyla hüküm doğurur*.

İşveren vekilleri ile toplu iş sözleşmesi görüşmelerine işvereni temsilen
katılanlar, toplu iş sözleşmesinden yararlanamaz.

Grev sonunda yapılan toplu iş sözleşmesinden, kanun gereği zorunlu olarak
çalışanlar dışında işyerine çalışmış olanlar, sözleşmede aksine hüküm
bulunmadıkça yararlanamaz.

NOTE: Toplu iş sözleşmesinde bulunan ücret, ikramiye, paraya ilişkin sosyal
yardım konularına ilişkin hükümlerden işverenin sadece belirli bir kesimi
yararlandırması ayrımcılık yasağı kapsamında değerlendirilemez.

IMPORTANT: İşyeri düzenine dair toplu iş sözleşmesinde bulunan düzenlemeler,
sendika üyesi olsun olmasın bütün işçiler için uygulanır. Sadece parasal
haklara ilişkin düzenlemeler yararlanma hükümleri kapsamındadır.

=== TOPLU İŞ SÖZLEŞMESİNİN SONA ERMESİ

Toplu iş sözleşmesi belirli süreli (1-3 yıl) bir sözleşme olduğu için
sözleşmede öngörülen sürenin bitiminde yürürlükten kalkar. *Sözleşme süresinden
önce sona erdirilemez.*

Toplu iş sözleşmesine taraf olan sendikanın tüzel kişiliğinin sona ermesi,
faaliyetinin durdurulması, işçi sendikasının yetkiyi kaybetmesi ve toplu iş
sözleşmesinin uygulandığı işyerlerinde işverenin veya işyerinin girdiği
işkolunun değişmesi toplu iş sözleşmesini sona erdirmez.

== İŞ UYUŞMAZLIKLARI

İş uyuşmazlıkları, işçiler veya işçi sendikaları ile işverenler veya işveren
sendikaları arasında işçilerin ve işverenlerin karşılıklı olarak ekonomik veya
sosyal durumlarının, çalışma şartlarının teslim edilmesi, uygulanması,
yorumlanması, değiştirilmesi ya da daha iyi hale getirilmesine yönelik olarak
ortaya çıkan uyuşmazlıklardır.

İş uyuşmazlıkları ikiye ayrılır:

. *Hak veya menfaat uyuşmazlıkları*

.. _Hak uyuşmazlığı:_ İş mevzuatı, toplu iş sözleşmesi veya iş sözleşmesindeki
hakların hiç ya da gereği gibi yerine getirilmemesi halinde ortaya çıkan
uyuşmazlıklardır. *Burada tarafların üzerinde anlaştıkları bir hak ihlal
edilmektedir.*
.. _Menfaat uyuşmazlığı:_ Daha önce mevcut olmayan bir hakkın tanınmasına
yönelik uyuşmazlıklardır.
. *Bireysel veya toplu iş uyuşmazlıkları*

.. _Bireysel hak uyuşmazlığı_
.. _Bireysel menfaat uyuşmazlığı_
.. _Toplu hak uyuşmazlığı:_ Toplu iş sözleşmesinin yorumu veya uygulanması ile
ilgili uyuşmazlıklardır.
+
_Uygulanmakta olan bir toplu iş sözleşmesinin yorumundan doğan uyuşmazlıklarda
sözleşmenin taraflarınca dava açılabilir. Mahkeme en geç iki ay içinde karar
verir. Karar hakkında istinaf yoluna başvurulması halinde bölge adliye
mahkemesi, uyuşmazlığı iki ay içinde kesin olarak karara bağlar._
+
_Toplu iş sözleşmesine dayanan eda davalarında, temerrüt tarihinden itibaren
işletme kredilerine uygulanan en yüksek faiz oranı uygulanır._
.. _Toplu menfaat uyuşmazlığı:_ Toplu iş sözleşmesi yapılırken ortaya çıkan
uyuşmazlıklardır. Taraflar toplu iş sözleşmesi görüşmelerinde uzlaşamazlarsa
öncelikli olarak işletilmesi gereken barışçıl çözüm yolu arabuluculuktur.

=== ARABULUCULUK

Toplu iş sözleşmesi görüşmelerinde _uyuşmazlık yazısını alan görevli makam
*altı iş günü içinde* taraflardan en az birinin katılımı ile veya katılım
olmazsa re'sen bir arabulucu görevlendirir._

Taraflar bir arabulucu üzerinde anlaşırlarsa, belirlenen kişi görevli makam
tarafından arabulucu olarak görevlendirilir.

*Arabulucunun görevi kendisine yapılacak bildirimden itibaren on beş gün sürer.
Bu süre tarafların anlaşması ile en çok altı iş günü uzatılabilir ve görevli
makama bildirilir.*

Arabuluculuk süresinin sonunda anlaşma sağlanamamışsa, arabulucu üç iş günü
içinde uyuşmazlığı belirleyen bir tutanak düzenler ve uyuşmazlığın sona
erdirilmesi için gerekli gördüğü önerileri de ekleyerek görevli makama tevdi
eder. Görevli makam, tutanağı en geç üç iş günü içinde taraflara tebliğ eder.

=== GREV

İşçilerin, topluca çalışmamak suretiyle işyerinde faaliyeti durdurmak veya işin
niteliğine göre önemli ölçüde aksatmak amacıyla, aralarında anlaşarak veya bir
kuruluşun aynı amaçla topluca çalışmamaları için verdiği karara uyarak işi
bırakmalarına *grev* denir.

Toplu iş sözleşmesinin yapılması sırasında uyuşmazlık çıkması halinde,
işçilerin ekonomik ve sosyal durumları ile çalışma şartlarını korumak veya
geliştirmek amacıyla, kanun hükümlerine uygun olarak yapılan greve *kanuni
grev* denir.

_Grev kararı, uyuşmazlık tutanağının tebliği tarihinden itibaren *altmış gün
içinde* alınabilir ve bu süre içerisinde *altı iş günü önceden* karşı tarafa
bildirilecek tarihte uygulamaya konulabilir. Bu süre içerisinde grev kararının
alınmaması veya uygulanacağı tarihin karşı tarafa bildirilmemesi halinde toplu
iş sözleşmesi yapma yetkisi düşer._

_Uyuşmazlığın tarafı olan işveren sendikası veya sendika üyesi olmayan
işveren, grev kararının kendisine tebliğinden itibaren altmış gün içinde
*lokavt* kararı alabilir ve bu süre içerisinde altı iş günü önceden karşı
tarafa bildirilecek tarihte uygulamaya koyabilir._

Bildirilen tarihte başlamayan grev hakkı veya lokavt düşer. Süresi içinde grev
kararı uygulamaya konulmamışsa ve alınmış bir lokavt kararı da yoksa veya
lokavt da süresi içinde uygulamaya konulmamışsa yetki belgesinin hükmü kalmaz.

Grev ve lokavt kararlarının uygulanacağı tarih, kararı alan tarafça karşı
tarafa tebliğ edilmek üzere notere bir örneği de görevli makama tevdi edilir.

*Kanuni grev kararı alınan bir uyuşmazlıkta Çalışma ve Sosyal Güvenlik Bakanı
uyuşmazlığın çözümü için bizzat arabuluculuk yapabileceği gibi bir kişiyi de
arabulucu olarak görevlendirebilir.*

Kanuni grevden söz edilebilmesi için dört unsur gerekir:

. *Mesleki amaç:* Toplu iş sözleşmeleri sırasında taraflar arasında ortaya
çıkan bir uyuşmazlığa dayanmayan grev kanuni değildir. Mevzuatımızda hakkın
yerine getirilmemesi sebebiyle greve gidebilmek mümkün değildir.
. *Kanunda belirlenen usule uygun olması:* Öncelikle barışçıl çözüm yollarının
denenmiş olması ve bir sonuca varılamamış olması gerekir. Grev kararını alma
yetkisi sadece işçi sendikasına tanınmıştır. Konfederasyon vs. grev kararı
alamaz.
. *Grevin yasaklanmamış olması:* Bakanlar Kurulu, *genel hayatı önemli ölçüde
etkileyen doğa olaylarının gerçekleştiği yerlerde* bu durumun devamı süresince
yürürlükte kalmak kaydıyla gerekli gördüğü işyerlerinde grev ve lokavtı
yasaklayabilir. Yasağın kalkmasından itibaren altmış gün içinde altı iş günü
önce karşı tarafa bildirilmek kaydıyla grev ve lokavt uygulamasına devam
edilir.
+
Başladığı yolculuğu yurt içindeki varış yerlerinde bitirmemiş deniz, hava,
demir ve kara ulaştırma araçlarında grev ve lokavt yapılamaz.
+
****
Aşağıdaki işlerde veya işyerlerinde grev ve lokavt yapılamaz:

.. Can ve mal kurtarma işlerinde
.. Cenaze işlerinde ve mezarlıklarda
.. Şehir şebeke suyu, elektrik, doğal gaz, petrol üretimi, tasfiyesi ve
dağıtımı işlerinde
.. Milli Savunma Bakanlığı ile Jandarma Genel Komutanlığı ve Sahil Güvenlik
Komutanlığınca doğrudan işletilen işyerlerinde
.. Kamu kuruluşlarınca yürütülen itfaiye ve hastanelerde
****
. *Grev engellerinin söz konusu olmaması*

.. _Grev oylaması:_ Grev kararının *işyerinde ilan edildiği tarihte o işyerinde
çalışan işçilerin en az dörtte birinin* ilan tarihinden itibaren *altı iş günü
içinde* işyerinin bağlı bulunduğu görevli makama yazılı başvurusu üzerine,
görevli makamca talebin yapılmasından başlayarak altı iş günü içinde grev
oylaması yapılır.
+
Oylamaya ilişkin itiraz, oylama gününden başlayarak üç iş günü içinde mahkemeye
yapılır. İtiraz, mahkemece üç iş günü içinde kesin olarak karara bağlanır.
+
Oylamada grev ilanının yapıldığı tarihte işyerinde çalışan *işçilerden oylamaya
katılanların salt çoğunluğu* grevin yapılmaması yönünde karar verirse, bu
uyuşmazlıkta alınan grev kararı uygulanamaz.
.. _Grevin ertelenmesi:_ Karar verilmiş veya başlanmış olan kanuni bir grev
veya lokavt; genel sağlığı veya milli güvenliği, büyükşehir belediyelerinin
şehir içi toplu taşıma hizmetlerini, bankacılık hizmetlerinde ekonomik veya
finansal istikrarı bozucu nitelikte ise Bakanlar Kurulu bu uyuşmazlıkta grev ve
lokavtı *altmış gün süre ile* erteleyebilir. Erteleme süresi, kararın yayımı
tarihinde başlar.
+
Erteleme kararının yürürlüğe girmesi üzerine, Çalışma ve Sosyal Güvenlik Bakanı
veya onun belirlediği arabulucu, uyuşmazlığın çözümü için ertleme süresince her
türlü çabayı gösterir. Erteleme süresi içinde taraflar aralarında anlaşarak
uyuşmazlığı özel hakeme de götürebilir.
+
Erteleme süresinin sonunda anlaşma sağlanamazsa, altı iş günü içinde
taraflardan birinin başvurusu üzerine uyuşmazlık Yüksek Hakem Kurulunca
çözülür. Aksi takdirde işçi sendikasının yetkisi düşer.
.. _Grevin mahkeme kararıyla durdurulması:_ Taraflardan birinin veya Çalışma ve
Sosyal Güvenlik Bakanının başvurusu üzerine mahkemece, grev hakkı veya lokavtın
iyi niyet kurallarına aykırı şekilde toplum zararına veya milli servete zarar
verecek şekilde kullanıldığının tespit edilmesi halinde, uygulanmakta olan grev
veya lokavtın durdurulmasına karar verilir.
+
Taraflardan her biri, karar verilen veya uygulanmakta olan bir grev veya
lokavtın kanun dışı olup olmadığının tespitini mahkemeden her zaman talep
edebilir. Mahkeme bir ay içinde karar verir. Karar hakkında istinaf yoluna
başvurulması halinde bölge adliye mahkemesi bir ay içinde kesin olarak karar
verir. Verilecek karar, tarafları, işçi ve işveren sendikasının üyelerini
bağlar ve ceza davaları için kesin delil teşkil eder.
+
Hakim *tedbir olarak* dava konusu grev veya lokavtın durdurulmasına karar
verebilir.

=== GREVİN HUKUKİ SONUÇLARI

==== GREVİN İŞ SÖZLEŞMESİ ÜZERİNDEKİ ETKİSİ

Kanuni bir grev kararının alınmasına katılma, teşvik etme, greve katılma veya
greve katılmaya teşvik etme nedeniyle bir işçinin iş sözleşmesi feshedilemez.

Kanuni greve katılan, greve katılmayan veya katılmaktan vazgeçip de grev
nedeniyle çalıştırılamayan ve kanuni lokavta maruz kalan işçilerin iş
sözleşmeleri grev ve lokavt süresince askıda kalır.

İşveren, grev ve lokavt nedeniyle iş sözleşmeleri askıda kalan işçilerin grev
veya lokavtın başlamasından önce işleyen ücretlerini ve eklerini doğrudan
olağan ödeme gününde ödemek zorundadır. *Ödemeyi yapacak personel de bunun için
çalışmakla yükümlüdür.*

Grev veya lokavt süresince iş sözleşmeleri askıda kalan işçilere bu dönem için
işverence ücret ve sosyal yardımlar ödenemez, bu süre *kıdem tazminatı
hesabında dikkate alınmaz.* Toplu iş sözleşmelerine ve iş sözleşmelerine
bunların aksine hüküm konulamaz.

==== İŞYERİNDEN AYRILMA ZORUNLULUĞU

İşçiler greve katılıp katılmamakta serbesttir. Greve katılan işçiler ile
lokavta maruz kalan işçiler işyerinden ayrılmak zorundadır. Greve katılmayan
veya katılmaktan vazgeçenlerin işyerinde çalışmaları hiçbir şekilde
engellenemez. Ancak, işveren bu işçileri çalıştırıp çalıştırmamakta serbesttir.

Greve katılan veya lokavta maruz kalan işçilerin işyerine giriş çıkışları
engellemeleri yasaktır.

Grev başlamadan önce üretilen ürünlerin satılmasına ve işyeri dışına
çıkarılmasına engel olunamaz.

Greve katılmayıp çalışan işçilerin ürettiği ürünlerin satılmasına ve işyeri
dışına çıkarılmasına, işyeri için gerekli maddelerin, araç ve gereçlerin
işyerine sokulmasına engel olunamaz.

==== BAŞKA İŞÇİ ÇALIŞTIRMA VE BAŞKA İŞVEREN YANINDA ÇALIŞMA YASAĞI

Kanuni bir grev ve lokavt dolayısıyla iş sözleşmeleri askıda kalan işçiler,
grev veya lokavt süresince *başka bir işverenin yanında çalışamaz*. Aksi halde
işçinin iş sözleşmesi işverence haklı nedenle feshedilebilir.

NOTE: Kısmi süreli iş sözleşmesi ile çalışan işçiler, kanuni haftalık çalışma
süresini tamamlayacak süreyi aşmamak üzere başka bir işverenin işyerinde
çalışabilir.

İşveren, kanuni bir grev ya da lokavt süresince iş sözleşmeleri askıda kalan
işçilerin yerine, sürekli ya da geçici olarak başka işçi alamaz veya
başkalarını çalıştıramaz. Ancak greve katılamayacak ve lokavta maruz
bırakılamayacak işçilerden, ölen, kendi isteği ile ayrılan veya iş sözleşmesi
işveren tarafından haklı sebeple feshedilenlerin yerine yeni işçi alınabilir.
İşverenin bu yasağa aykırı hareketi, taraf sendikanın yazılı başvurusu halinde
görevli makamca denetlenir.

Greve katılmayan veya katılmaktan vazgeçen işçiler, ancak kendi işlerinde
çalışabilir. Bu işçilere, greve katılan işçilerin işleri yaptırılamaz.

==== GREVE KATILAMAYACAK İŞÇİLER

Hiçbir surette üretim veya satışa yönelik olmamak kaydıyla niteliği bakımından
sürekli olmasında teknik zorunluluk bulunan işlerde faaliyetin devamlılığını
veya işyeri güvenliğini, makine ve demirbaş eşyalarının, gereçlerinin,
hammadde, yarı mamul ve mamul maddelerin bozulmamasını ya da hayvan ve
bitkilerin korunmasını sağlayacak sayıda işçi, kanuni grev ve lokavt sırasında
çalışmak, işveren de bunları çalıştırmak zorundadır.

İşveren, grev ve lokavt nedeniyle iş sözleşmeleri askıda kalan işçilerin grev
veya lokavtın başlamasından önce işleyen ücretlerini ve eklerini olağan ödeme
gününde ödemek zorundadır. Ödemeyi yapacak personel de bunun için çalışmakla
yükümlüdür.

NOTE: Özel güvenlik görevlileri de kendi kanunlarından kaynaklanan hükümdem
dolayı greve katılamazlar.

==== İŞYERİNDE MEYDANA GELEN ZARAR

Grev esnasında greve karar veren sendikanın kusurlu hareketi sonucu grev
uygulanan işyerinde neden olunan maddi zarardan sendika sorumludur.

Yetkili işçi sendikasının kararı olmadan işçi ya da yöneticilerin bireysel
eylemlerinden kaynaklanan zararlardan kusuru olan yönetici ya da işçi
sorumludur.

==== GREVE KATILIMIN DENETLENMESİ

İşyerinde grev ilan etmiş olan işçi sendikası, kanuni bir grev kararına
uyulmasını sağlamak için güç kullanmaksızın ve tehditte bulunmaksızın kendi
üyelerinin grev kararına uyup uymadıklarını denetlemek amacıyla, işyerinin
giriş ve çıkış yerlerine, kendi üyeleri arasından en çok dörder grev gözcüsü
koyabilir.
