== GEMİ

Tahsis edildiği amaç suda hareket etmesini gerektiren, yüzme özelliği bulunan
ve pek küçük olmayan her araç, kendiliğinden hareket etmesi imkânı bulunmasa
da, TTK bakımından *gemi* sayılır (TTK 931).

Geminin unsurları:

. _Pek küçük olmamak_: Her somut olayda denizcilik sektöründe egemen olan
anlayışa göre belirlenir.
. _Suda hareketi gerektiren bir amaca tahsis edilmiş olması_
. _Yüzme özelliğinin bulunması_

NOTE: Bir yerden bir yere bir başka gemi tarfından çekilerek götürülüyor olması
tek başına gemi olma özelliğini etkilemez.

Yukarıdaki unsurların başlangıçta mevcut olup, geçici olarak ortadan kalkması
aracın gemi olma niteliğini etkilemez. Aşağıdaki durumlarda ise gemi, gemi olma
özelliğini kaybeder:

. *Kurtarılamayacak şekilde batmış gemi*
. *Tamir kabul etmez gemi*: Tamiri hiç veya bulunduğu yerde mümkün değilse ve
tamir edilebileceği bir limana götürülemezse
. *Suda devamlı olarak hareketi gerektiren bir amaca tahsis edilme unsurunun
ortadan kalkması*

=== BÜTÜNLEYİCİ PARÇA VE EKLENTİ

Geminin yapısını değiştirmeden, zarara uğratmadan ondan ayrılamayan parçalara
*bütünleyici parça* denir. Örneğin geminin makinesi, pervanesi, dümeni
bütünleyici parça olarak kabul edilir. Gemi üzerinde yapılan her tasarruf
işlemi bütünleyici parçaları da kapsar, bunun aksini kararlaştırmak mümkün
değildir.

Bütünleyici parça niteliğinde olmayan ancak devamlı olarak gemiye özgülenmiş
taşınırlar **eklenti**dir. Eklentiler de tasarruf işlemine kendiliğinden dahil
olur ancak bunun aksini kararlaştırmak mümkündür.

[NOTE]
====
Gemideki bazı şeyler ne bütünleyici parça ne de eklentidir. Bu şeyler tasarruf
işlemine kendiliğinden dahil olmaz, açıkça dahil edilmeleri gerekir. Bu konuda
en tipik örnek yakıttır.
====

=== TİCARİ GEMİ

Suda ekonomik menfaat sağlama amacına tahsis edilen veya fiilen böyle bir amaç
için kullanılan her gemi, kimin tarafından ve kimin adına veya hesabına
kullanılırsa kullanılsın *ticaret gemisi* sayılır.

TIP: Kazanç elde etme doğrudan olabileceği gibi dolaylı da olabilir. Bir gemi
sahibi kendi yükünü taşıyarak başkasına taşıtmış olsaydı ödeyeceği navlunu
ödemekten kurtulduğu için malvarlığının aktifinde meydana gelecek azalmanın
önlenmesi şeklinde dolaylı kazanç elde etmiş olur.

TTK hükümleri kural olarak sadece ticari gemiler için geçerlidir. Ancak TTK
hükümlerinin ticari olmayan gemilere uygulanacağı istisnaları TTK 935
belirtmiştir.

TTK'nın;

. “Gemi”, “Kaptan”, “Gemi Alacakları” ve “Cebrî İcraya İlişkin Özel Hükümler”
başlıklı Kısımları, “Çatma” ve “Kurtarma” başlıklı Bölümleri, deniz
alacaklarına karşı sorumluluğun sınırlanması hakkındaki hükümleri ile
donatanın, gemi adamlarının kusurundan doğan sorumluluğuna ilişkin 1062 nci
maddesi, yatlar, denizci yetiştirme gemileri gibi sadece gezinti, spor, eğitim,
öğretim ve bilim amaçlarına tahsis edilmiş gemilere,
. “Çatma” ve “Kurtarma” başlıklı Bölümleri, deniz alacaklarına karşı
sorumluluğun sınırlanması hakkındaki hükümleri ile donatanın, gemi adamlarının
kusurundan doğan sorumluluğuna ilişkin 1062 nci maddesi, münhasıran bir kamu
hizmetine tahsis edilen Devlet gemileriyle donanmaya bağlı harp gemilerine ve
yardımcı gemilere,
. Bayrak şahadetnamesi ile ilgili 944 üncü maddenin ikinci fıkrası ile 945,
947, 948 ve 949 uncu maddeleri, sicille ilgili 955, 956, 973 ve 991 inci
maddeleri, kanuni ipotekle ilgili 1013 üncü maddesi ve yapı hâlinde bulunan
gemiler üzerindeki haklarla ilgili 1054 ilâ 1058 inci maddeleri yabancı bir
devlet veya onun vatandaşları adına Türkiye’de yapılmakta olan gemilere de,

nitelikleri ile bağdaştığı ölçüde, uygulanır.

=== GEMİNİN HUKUKİ NİTELİĞİ

Sicile kayıtlı olup olmadıklarına bakılmaksızın bütün gemiler TTK'nın ve diğer
kanunların uygulanmasında taşınır eşyadandır (TTK 936).

