:icons: font

== İLGİLİNİN RIZASI

Kişinin mutlak suretle üzerinde tasarruf edebileceği haklarla ilgili açıkladığı
rıza çerçevesinde işlenen eylemler *cezalandırılmaz*, dolayısıyla ilgilinin
rızası hukuka uygunluk sebeplerinden biridir.

Rızanın geçerli olabilmesi için:

. Rıza verecek kişinin rıza açıklama yeteneğine sahip olması gerekir.
. Rıza verecek kişinin rıza vereceği konuda aydınlatılmış olması gerekir.
. Rızanın, kişinin üzerinde tasarruf edebileceği bir konu ile ilgili olması
gerekir.

NOTE: Rıza gösterecek kişinin eylemin niteliğini, sonuçlarını ve risklerini
algılayabilecek durumda olması yeterlidir.

== HASTANIN RIZASI

Tıbbi müdahalelerde hastanın rızası gerekir. Hasta küçük veya mahcur ise
velisinden veya vasisinden izin alınır. Hastanın, velisinin veya vasisinin
olmadığı veya hazır bulunamadığı veya hastanın ifade gücünün olmadığı hallerde,
bu şart aranmaz.

NOTE: Ameliyat sırasında hekimin başka bir bölgeye müdahale etmesini gerektiren
bir durumun ortaya çıkması halinde bu müdahale kişinin hayatını kurtaracak ya
da hayatını tehlikeye atmaktan kurtaracak nitelikteyse rıza alınmadan müdahale
yapılabilir.

Kanuni temsilcinin rızasının yeterli olduğu hallerde dahi, anlatılanları
anlayabilecekleri ölçüde, küçük veya kısıtlı olan hastanın dinlenmesi suretiyle
mümkün olduğu kadar bilgilendirme sürecine ve tedavisi ile ilgili alınacak
kararlara katılımı sağlanır.

Kanuni temsilci tarafından rıza verilmeyen hallerde, müdahalede bulunmak tıbben
gerekli ise, velayet ve vesayet altındaki hastaya tıbbi müdahalede
bulunulabilmesi; Türk Medeni Kanununun 346 ncı ve 487 inci maddeleri uyarınca
mahkeme kararına bağlıdır.

Tıbbi müdahale sırasında isteğini açıklayabilecek durumda bulunmayan bir
hastanın, tıbbî müdahale ile ilgili olarak önceden açıklamış olduğu istekleri
göz önüne alınır.

Yeterliğin zaman zaman kaybedildiği tekrarlayıcı hastalıklarda, hastadan
yeterliği olduğu dönemde onu kaybettiği dönemlere ilişkin yapılacak tıbbi
müdahale için rıza vermesi istenebilir.

Hastanın rızasının alınamadığı hayati tehlikesinin bulunduğu ve bilincinin
kapalı olduğu acil durumlar ile hastanın bir organının kaybına veya
fonksiyonunu ifa edemez hale gelmesine yol açacak durumun varlığı halinde,
hastaya tıbbi müdahalede bulunmak rızaya bağlı değildir. Bu durumda hastaya
gerekli tıbbi müdahale yapılarak durum kayıt altına alınır. Ancak bu durumda,
mümkünse hastanın orada bulunan yakını veya kanuni temsilcisi; mümkün olmadığı
takdirde de tıbbi müdahale sonrasında hastanın yakını veya kanuni temsilcisi
bilgilendirilir. Ancak hastanın bilinci açıldıktan sonraki tıbbi müdahaleler
için hastanın yeterliği ve ifade edebilme gücüne bağlı olarak rıza işlemlerine
başvurulur.

Sağlık kurum ve kuruluşlarında yatarak tedavisi tamamlanan hastaya, genel
sağlık durumu, ilaçları, kontrol tarihleri diyet ve sonrasında neler yapması
gerektiği gibi bilgileri içeren taburcu sonrası tedavi planı sağlık meslek
mensubu tarafından sözel olarak anlatılır. Daha sonra bu tedavi planının yer
aldığı epikrizin bir nüshası hastaya verilir.

== HEKİMİN AYDINLATMA YÜKÜMLÜLÜĞÜ

Rızanın geçerliliği bakımından hastanın müdahale hakkında aydınlatılmış olması
önemlidir. Aydınlatma kapsamında müdahalenin kapsamı, yöntemi, muhtemel sonuç
ve riskleri konusunda hasta bilgilendirilmelidir.

Hastaya;

.. Hastalığın muhtemel sebepleri ve nasıl seyredeceği,
.. Tıbbi müdahalenin kim tarafından nerede, ne şekilde ve nasıl yapılacağı ile
tahmini süresi,
.. Diğer tanı ve tedavi seçenekleri ve bu seçeneklerin getireceği fayda ve
riskler ile hastanın sağlığı üzerindeki muhtemel etkileri,
.. Muhtemel komplikasyonları,
.. Reddetme durumunda ortaya çıkabilecek muhtemel fayda ve riskleri,
.. Kullanılacak ilaçların önemli özellikleri,
.. Sağlığı için kritik olan yaşam tarzı önerileri,
.. Gerektiğinde aynı konuda tıbbî yardıma nasıl ulaşabileceği,

hususlarında bilgi verilir.

Kural olarak müdahale kim tarafından yapılacaksa aydınlatma yükümlülüğünü de o
yerine getirecektir. Aydınlatmanın kural olarak bir şekil şartı yoktur. Ancak
kanun belli müdahaleler için yazılı aydınlatma yapılmasını zorunlu kılmıştır.

Bilgi, mümkün olduğunca sade şekilde, tereddüt ve şüpheye yer verilmeden,
hastanın sosyal ve kültürel düzeyine uygun olarak anlayabileceği şekilde
verilir.

Hasta, tıbbi müdahaleyi gerçekleştirecek sağlık meslek mensubu tarafından tıbbi
müdahale konusunda sözlü olarak bilgilendirilir. Bilgilendirme ve tıbbi
müdahaleyi yapacak sağlık meslek mensubunun farklı olmasını zorunlu kılan
durumlarda, bu duruma ilişkin hastaya açıklama yapılmak suretiyle bilgilendirme
yeterliliğine sahip başka bir sağlık meslek mensubu tarafından bilgilendirme
yapılabilir.

Hastanın kendisinin bilgilendirilmesi esastır. Hastanın kendisi yerine bir
başkasının bilgilendirilmesini talep etmesi halinde, bu talep kişinin imzası
ile yazılı olarak kayıt altına alınmak kaydıyla sadece bilgilendirilmesi
istenilen kişilere bilgi verilir.

Hasta, aynı şikayeti ile ilgili olarak bir başka hekimden de sağlık durumu
hakkında ikinci bir görüş almayı talep edebilir.

Acil durumlar dışında, bilgilendirme hastaya makul süre tanınarak yapılır.

Bilgilendirme uygun ortamda ve hastanın mahremiyeti korunarak yapılır.

[TIP]
====
Hastanın manevi yapısı üzerinde fena tesir yapmak suretiyle hastalığın artması
ihtimalinin bulunması ve hastalığın seyrinin ve sonucunun vahim görülmesi
hallerinde, teşhisin saklanması caizdir.

Hastaya veya yakınlarına, hastanın sağlık durumu hakkında bilgi verilip
verilmemesi, yukarıdaki fıkrada belirtilen şartlar çerçevesinde tabibinin
takdirine bağlıdır.

Tedavisi olmayan bir teşhis, ancak bir tabip tarafından ve tam bir ihtiyat
içinde hastaya hissettirilebilir veya bildirilebilir. Hastanın aksi yönde bir
talebinin bulunmaması veya açıklanacağı şahsın önceden belirlenmemesi halinde,
böyle bir teşhis ailesine bildirilir.

İlgili mevzuat hükümleri ve/veya yetkili mercilerce alınacak tedbirlerin
gerektirdiği haller dışında; kişi, sağlık durumu hakkında kendisinin,
yakınlarının ya da hiç kimsenin bilgilendirilmemesini talep edebilir. Bu
durumda kişinin kararı yazılı olarak alınır. Hasta, bilgi verilmemesi talebini
istediği zaman değiştirebilir ve bilgi verilmesini talep edebilir.
====

=== AYDINLATMA TÜRLERİ

. *Tedavi aydınlatması (Güvenlik aydınlatması)*: Tedavi aydınlatmasının amacı,
hekimin tavsiyeleri ile hastayı yönlendirmek, en iyi tercihi yaptırmak ve
komplikasyonları bildirmektir.

.. _Teşhise yönelik aydınlatma_: Teşhis için yapılacak müdahaleler konusunda
hastanın bilgilendirilmesidir.
.. _Teşhis aydınlatması_: Hastanın tıbbi bulgu konusunda aydınlatılmasıdır.
.. _İlaçlar hakkında aydınlatma_
.. _Araç kullanma konusunda aydınlatma_

. *Karar aydınlatması (otonomi aydınlatması)*: Amaç hastanın karar vermesini
mümkün kılmaktır. Hekimin hastayı zorlamaması gerekir.
. *Riziko aydınlatması*: Muhtemel geçici ya da daimi yan etkilerin hastaya
anlatılmasıdır.

.. _Tıbbi müdahaleye ve genel rizikolara ilişkin aydınlatma_
.. _Tıbbi müdahalenin amacına ve gerekliliğine ilişkin aydınlatma_
.. _Tıbbi müdahalenin ağırlığına ilişkin aydınlatma_
.. _Kişinin kişiliğine, davranışlarına ve bünyesine göre aydınlatılması_


Hekim teşhis, müdahale veya tedavi aşamalarında hata yapmış ise bunu kişiye
bildirmeli ve anlayacağı şekilde anlatmalıdır.

Hekim hastanın tedavisine yönelik olarak muhtemel masrafları ve niceliği
konusunda hastayı aydınlatmalıdır.

=== AYDINLATMA ZORUNLULUĞUNUN İSTİSNALARI

* Hasta aydınlatılma hakkından vazgeçmiş olabilir.
* Hasta tıbbi müdahalenin sonuçları, riskleri konusunda bilgi sahibi olabilir.
* Aydınlatma hastayı olumsuz etkileyecek olabilir.
* Acil bir hal söz konusu olabilir.
* Aydınlatma hasta bakımından önemini yitirmiş olabilir.
* Hastanın akli melekeleri yerinde olmayabilir.

== HEKİMİN SORUMLULUĞU

* Hekimin **özen yükümlülüğü**ne uygun şekilde hareket etmesi gerekir.
* Hekim edimi *bizzat* yerine getirmelidir. Ancak tedavi için gereken yan
edimlerin yerine getirilmesi için yardım alınabilir.
* Hekim hastanın tıbbi öyküsünü dinlemek zorundadır.
* Hekim hastayı yüz yüze tedavi etmelidir.
* Muayene sonunda ulaşılan teşhis hekim tarafından hastanın yüzüne karşı
açıklanmalıdır.
* Hekim acil veya zorunlu haller dışında hastayı reddetme hakkına sahiptir.
* Hekim elinde bulunan teknik ve tıbbi cihazları kullanmalıdır. Her cihazın her
hekim veya hastanede bulunması beklenemez. Ancak birtakım zorunlu cihazların
bulunması şarttır. Hekimin bunların bulunmadığını hastaneye rapor etmesi
şarttır.
* Hekimin veya hastanenin tuttuğu kayıtlar hastalar tarafından istendiğinde
verilmek zorundadır.

== HASTANIN TEDAVİYİ RET HAKKI

Kanunen zorunlu olan haller dışında ve doğabilecek olumsuz sonuçların
sorumluluğu hastaya ait olmak üzere; hasta kendisine uygulanması planlanan veya
uygulanmakta olan tedaviyi reddetmek veya durdurulmasını istemek hakkına
sahiptir. Bu halde, tedavinin uygulanmamasından doğacak sonuçların hastaya veya
kanuni temsilcilerine veyahut yakınlarına anlatılması ve bunu gösteren yazılı
belge alınması gerekir.

Bu hakkın kullanılması, hastanın sağlık kuruluşuna tekrar müracaatında hasta
aleyhine kullanılamaz.

== ÖTENAZİ

*Ötenazi*, kişinin belirli bir rahatsızlığından dolayı çektiği acı ve ızdırabın
giderilmesi amacıyla kendi yaşam hakkından vazgeçmesidir.

Ötenazi üçe ayrılır:

. *Aktif ötenazi*: Kişinin yaşam hakkından feragat beyanıyla hekim tarafından
öldürülmesidir.
. *Dolaylı ötenazi*: Kanunumuzda hekimin, hastanın iyileşme imkanı yoksa onu
rahatlatacak ve huzur içinde yaşamasını sağlayacak birtakım tedbirler alması
gerektiğinden bahsedilmektedir. Bu tedbirler hastanın ölümünü hızlandıracak
olsa da hekim tarafından alınabilir.
. *Pasif ötenazi*: Yukarıda açıklanan hastanın tedaviyi reddetmesi hakkının
kullanımıdır.

NOTE: AİHM, bunun ülkelerin iç hukukuna dair bir husus olduğunu savunmaktadır.

== İNSAN ÜZERİNDE DENEY

İnsan üzerinde bilimsel bir deney yapan kişi, bir yıldan üç yıla kadar hapis
cezası ile cezalandırılır.

İnsan üzerinde yapılan rızaya dayalı bilimsel deneyin ceza sorumluluğunu
gerektirmemesi için;

.. Deneyle ilgili olarak yetkili kurul veya makamlardan gerekli iznin alınmış
olması,
.. Deneyin öncelikle insan dışı deney ortamında veya yeterli sayıda hayvan
üzerinde yapılmış olması,
.. İnsan dışı deney ortamında veya hayvanlar üzerinde yapılan deneyler
sonucunda ulaşılan bilimsel verilerin, varılmak istenen hedefe ulaşmak
açısından bunların insan üzerinde de yapılmasını gerekli kılması,
.. Deneyin, insan sağlığı üzerinde öngörülebilir zararlı ve kalıcı bir etki
bırakmaması,
.. Deney sırasında kişiye insan onuruyla bağdaşmayacak ölçüde acı verici
yöntemlerin uygulanmaması,
.. Deneyle varılmak istenen amacın, bunun kişiye yüklediği külfete ve kişinin
sağlığı üzerindeki tehlikeye göre daha ağır basması,
.. Deneyin mahiyet ve sonuçları hakkında yeterli bilgilendirmeye dayalı olarak
açıklanan rızanın yazılı olması ve herhangi bir menfaat teminine bağlı
bulunmaması,

gerekir.

Çocuklar üzerinde bilimsel deneyin ceza sorumluluğunu gerektirmemesi için
yukarıda aranan koşulların yanı sıra;

.. Yapılan deneyler sonucunda ulaşılan bilimsel verilerin, varılmak istenen
hedefe ulaşmak açısından bunların çocuklar üzerinde de yapılmasını gerekli
kılması,
.. Rıza açıklama yeteneğine sahip çocuğun kendi rızasının yanı sıra ana ve
babasının veya vasisinin yazılı muvafakatinin de alınması,
.. Deneyle ilgili izin verecek yetkili kurullarda çocuk sağlığı ve hastalıkları
uzmanının bulunması,

gerekir.

Hasta olan insan üzerinde rıza olmaksızın tedavi amaçlı denemede bulunan kişi,
bir yıla kadar hapis cezası ile cezalandırılır. Ancak, bilinen tıbbi müdahale
yöntemlerinin uygulanmasının sonuç vermeyeceğinin anlaşılması üzerine, kişi
üzerinde yapılan rızaya dayalı bilimsel yöntemlere uygun tedavi amaçlı deneme,
ceza sorumluluğunu gerektirmez. Açıklanan rızanın, denemenin mahiyet ve
sonuçları hakkında yeterli bilgilendirmeye dayalı olarak yazılı olması ve
tedavinin uzman hekim tarafından bir hastane ortamında yapılması gerekir.

Yukarıda tanımlanan suçun işlenmesi sonucunda mağdurun yaralanması veya ölmesi
halinde, kasten yaralama veya kasten öldürme suçuna ilişkin hükümler uygulanır.

== ORGAN VEYA DOKU TİCARETİ

Hukuken geçerli rızaya dayalı olmaksızın, kişiden organ alan kimse, beş yıldan
dokuz yıla kadar hapis cezası ile cezalandırılır. Suçun konusunun doku olması
halinde, iki yıldan beş yıla kadar hapis cezasına hükmolunur.

Organ veya doku satın alan, satan, satılmasına aracılık eden kişi hakkında,
yukarıda belirtilen cezalara hükmolunur.

Hukuka aykırı olarak, ölüden organ veya doku alan kimse, bir yıla kadar hapis
cezası ile cezalandırılır.

Yukarıda tanımlanan suçların bir örgütün faaliyeti çerçevesinde işlenmesi
halinde, sekiz yıldan onbeş yıla kadar hapis ve onbin güne kadar adlî para
cezasına hükmolunur.

Hukuka aykırı yollarla elde edilmiş olan organ veya dokuyu saklayan, nakleden
veya aşılayan kişi, iki yıldan beş yıla kadar hapis cezası ile cezalandırılır.

Belli bir çıkar karşılığında organ veya doku teminine yönelik olarak ilan veya
reklam veren veya yayınlayan kişi, bir yıla kadar hapis cezası ile
cezalandırılır.

Yukarıda tanımlanan suçun işlenmesi sonucunda mağdurun ölmesi halinde,
kasten öldürme suçuna ilişkin hükümler uygulanır.

Organ veya dokularını satan kişinin içinde bulunduğu sosyal ve ekonomik
koşullar göz önünde bulundurularak, hakkında verilecek cezada indirim
yapılabileceği gibi, ceza vermekten de vazgeçilebilir.

Organ veya dokularını satan kişi, resmi makamlar tarafından haber alınmadan
önce durumu merciine haber vererek suçluların yakalanmalarını kolaylaştırırsa,
hakkında cezaya hükmolunmaz.

Bu suç haberalındıktan sonra, organ veya dokularını satan kişi, gönüllü olarak,
suçun meydana çıkmasına ve diğer suçluların yakalanmasına hizmet ve yardım
ederse; hakkında verilecek cezanın, yardımın niteliğine göre, dörtte birden
yarısına kadarı indirilir.

== HEKİM İLE HASTA ARASINDAKİ İLİŞKİNİN HUKUKİ NİTELİĞİ

Hasta ile hekim arasındaki ilişkinin hukuki niteliği aşağıdakilerden biri
olabilir:

* Sözleşme (vekalet veya eser)
* Haksız fiil
* Vekaletsiz iş görme
* Culpa in contrahendo: Sözleşme görüşmeleri sırasında tarafların özenli ve
dürüst davranma ilkelerine kusurlu olarak uymamaları veya diğer taraf nezdinde
uyandırılan güvene aykırılık nedeniyle verdikleri zarardan hakkaniyet ilkesi
gereğince sorumlu olmalarını ifade eder.

Türkiye'de üç tür hastane vardır:

. Özel hastane
. Vakıf hastanesi
. Devlet hastanesi

*Özel hastanede* muhatap hastanedir. Hastane ile hasta arasında *hasta kabul
sözleşmesi* kurulur.

Hastane ile hasta arasında karşılıklı irade beyanları uyuşuyorsa sözleşme
kurulur. İrade beyanları yazılı veya sözlü olabilir ya da davranışlarla da
kurulabilir.

Kural olarak hastanenin hastanın kaydını alması ve hastanın şikayeti üzerine
gerekli incelemelerin yapılmasını kabul etmesiyle birlikte sözleşme kurulmuş
olur.

NOTE: Hasta küçükse yasal temsilcisinin rızası aranacaktır. Ancak her halükarda
sözleşmenin tarafı küçük olan hastadır.

Hekim burada ifa yardımcısıdır. Hekimin haksız fiili durumunda hasta hem
hekimin hem de hastanenin sorumluluğuna gidebilir. Hekimin kısmen veta tamamen
sorumsuz olduğuna ilişkin anlaşmalar geçersizdir.

Hastanenin sözleşmeden doğan borcunu ifa edebilmesi için alacaklının rızasına
ihtiyacı vardır. Hastanın rızası ifa aşamasına geçebilmek için zorunludur. Aynı
zamanda hasta kural olarak istediği anda rızasını geri alabilir.

Dava hastaneye karşı açılmışsa tedavi sadece tıbbi müdahalenin kendisi
değildir. Hastane hem hekimlik hizmeti verir, hem de müdahaleden önce ve sonra
bakım hizmeti verir.

TIP: Özel hastanelerdeki müdahalelerden doğan zarardan devletin sorumluluğu söz
konusu değildir. Ancak devlet özel hastaneyi denetim ve gözetim yükümlülüğüne
aykırı davranırsa sorumluluğu gündeme gelir.

Hekim ile hasta arasındaki sözleşme bir vekalet sözleşmesidir. Hekim sonucu
taahhüt ediyor olsa bile bu bir eser sözleşmesi meydana getirmez. Dolayısıyla
hekimin ayıba karşı yükümlülüğü yoktur ama üstlendiği işi özenle yapma borcu
vardır. Hekim gereken özeni göstermesine rağmen sonuç meydana gelmemişse
sorumluluğuna gidilemez.

TIP: Yargıtay'ın uygulamasına göre estetik ameliyat eser sözleşmesinin konusunu
oluşturur.

Hekim hem vekalet sözleşmesinden kaynaklanan borcunu yerine getirecektir hem de
hastanın vücuduna yönelik eylemi haksız fiil teşkil edecektir.

NOTE: Birden fazla hukuki sebep varsa kişi tazminat için istediği sebebe
dayanabilir. Burada sebeplerin yarışması söz konusudur. Hangisine dayandığına
göre uygulanacak hükümler farklı olacaktır. Ancak ikisini aynı anda ileri
sürmek mümkün değildir.

*Kamu hastanesinde* hasta ile hekim arasında idare hukuku ilişkisi vardır.
Yargıtay'a göre ister hizmet kusuru olsun ister hekimin şahsi kusuru olsun dava
her zaman idareye karşı açılır.

CAUTION: Hekimin göreviyle alakalı olmayan veya yetkisini ciddi şekilde aşan
eyleminden doğan zararlar için doğrudan hekime dava açılabilir.

== MALPRAKTİS

Bir malpraktis iddiasında hekime sorumluluk atfedebilmek için dört şartın
yerine gelmiş olması gerekir:

. Hasta-hekim ilişkisi kurulmuş olmalıdır.
. Hekim tedaviyi uygularken bilimsel standartlardan sapmış olmalıdır.
. Hekim bilimsel standartlara uygun hareket etseydi önlenebilir bir zararın
oluşması gerekir.
. Hekimin eylemi ya da eylemsizliği ile zarar arasında bir illiyet bağı
olmalıdır.

TIP: Bu dört şartın ortaya çıktığı dava _Bolam_ davasıdır.

== SAĞLIK FAALİYETİ

Türkiye'deki temel sağlık otoritesi Sağlık Bakanlığı'dır. Sağlık Bakanlığı
bünyesinde bazı kurullar bulunmaktadır:

. *Yüksek Sağlık Şurası:* Özelllikle adli konularda mahkemeye görüş vermek
üzere oluşturulmuştur.
. *Tıpta Uzmanlık Kurulu:* Tıp ve diş hekimliği alanında uzmanlık eğitimi veren
kurumlara eğitim yetkisi vermektedir.
. *Sağlık Meslekleri Kurulu:* Sağlık eğitimi veren kurumlarında mesleki alan ve
dallarının belirlenmesi için kurulmuştur.

Bunlar dışında Bakanlık'tan ayrı tüzel kişiliğe sahip kurumlar vardır:

. *Türkiye Halk Sağlığı Kurumu:* Bakanlığın politika ve hedeflerine uygun
olarak sağlık hizmetlerini yürütür.
. *Türkiye İlaç ve Tıbbi Cihaz Kurumu:* İlaç üretiminde etken maddeler, tıbbi
cihazlar, hastalıklarda kullanılabilecek geleneksel bitkiler gibi konularda
karar alıp düzenlemeler yapar.
. *Türkiye Hudut ve Sahilleri Sağlık Genel Müdürlüğü:* Deniz seyahatleri
yoluyla bulaşıcı hastalıkların yayılmasını engellemek için çalışır.
. *Türkiye Kamu Hastaneleri Kurumu:* Kamu hastanelerinin uyum ve koordine için
çalışmasını temin etmek için kurulmuştur.
. *Kamu Hastane Birlikleri:* Sağlık hizmetlerinin il düzeyinde koordineli
şekilide yürütülmesini amaçlar.
