:toc:
:toc-title: CMK
:icons: font

== GENEL SÜREÇ

Suç şüphesiyle başlayıp iddianamenin kabulüyle biten evreye *soruşturma* denir.

Soruşturma evresine başlanabilmesi için mutlaka bir şüpheliye ihtiyaç yoktur.
Soruşturma evresinde suç şüphesi altında olan birisi varsa buna *şüpheli*,
şüpheliyi temsil eden avukata da *müdafi* adı verilir. Soruşturma evresi
bakımından asıl yetkili **Cumhuriyet Savcısı**dır. Dolayısıyla bütün işlemler
cumhuriyet savcısının talimatıyla gerçekleşir. Bu süreçte hakim kararına
ihtiyaç duyulması halinde karar verecek olan hakim CMK 162 uyarınca **Sulh Ceza
Hakimi**dir.

Soruşturma aşamasında suçun oluşup oluşmadığına, farklı şüphelilerin olup
olmadığına yönelik araştırma yapılır ve bu araştırmalar neticesinde şüphe belli
bir düzeye gelince cumhuriyet savcısı bir iddianame düzenler. Bu iddianame
kabul veya reddedilmesi için mahkemeye gönderilir. _İddianamenin kabulüyle,
kamu davası açılmış olur ve kovuşturma evresi başlar._ (CMK 175).

İddianamenin kabulünden olağan kanun yolları evresinin bitmesine (verilen
kararın kesinleşmesine) kadar olan sürece *kovuşturma* evresi denir. Kovuşturma
evresinde şüpheli, *sanık* haline gelir.

Kovuşturma evresi üç ana bölümden oluşur:

. İddianamenin kabulü ile duruşma günü arasındaki duruşma hazırlığı
. Duruşma ve hüküm
. Kanun yolları ve kesinleşme

== NORMLARIN ZAMAN BAKIMINDAN UYGULANMASI

Ceza muhakemesi kuralları yürürlüğe girdikleri tarihten itibaren şüphelinin,
sanığın, suçtan zarar görenin, katılanın veya herhangi bir başka öznenin
durumunu olumlu ya da olumsuz etkilemesine bakılmaksızın *derhal* uygulanırlar
ve hiçbir şekilde geriye yürümezler. Her işlem yapıldığı tarihteki norma göre
hukuka uygunluk hususunda değerlendirmeye tabi tutulur.

== KIYAS SERBESTİSİ

Kanun koyucu bir hukuki soruna ilişkin iradesini açıkça ortaya koymamışsa
hakim, ilk olarak diğer usul kanunlarından, ikinci olarak ana ilkelerle
çatışmamak kaydıyla kanunun içindeki diğer hükümlerden, üçüncü olarak da yine
ana ilkelerle çatışmamak kaydıyla ve gerekçelendirmek koşuluyla normatif
düzlemden bağımsız olarak sorunu çözmek zorundadır.

Ancak bu kıyas serbestisinin iki istisnası vardır:

. *Temel hak ve özgürlüklerle ilgili sınırlayıcı hükümler kıyasa tabi
olamazlar.*
. *İstisnai hükümlerde kıyasa başvurulamaz.*

== MUHAKEME ENGELLERİ

Kanunda bazı müesseseler davanın açılmasını engelleyen bazı müesseseler ise
yargılamanın yapılmasını engelleyen hususlar olarak düzenlenmiştir. Davanın
açılmasını engelleyen koşullara *dava koşulları*, yargılama yapılmasını
engelleyen koşullara *yargılama koşulları* denir.

Dava koşulları sadece davanın açılması noktasında etkili olmaz. Yargılama
aşaması süresince mahkemeler bu koşulları gerçekleşip gerçekleşmediğini
araştırmakla yükümlüdür.

=== ŞİKAYET

Cumhuriyet savcısı, ihbar veya başka bir suretle bir suçun işlendiği izlenimini
veren bir hâli öğrenir öğrenmez kamu davasını açmaya yer olup olmadığına karar
vermek üzere hemen işin gerçeğini araştırmaya başlar.

Takibi şikayete bağlı olmayan suçlar yani re'sen soruşturulan suçlarda her kim
olursa olsun savcılığa, kolluğa, mahkemelere, büyük elçiliklere ve kamu
kurumlarına yapılan bildirimin adı **ihbar**dır. Re'sen soruşturulan suçlarda
bildirimin ne zaman yapıldığının önemi yoktur, dava zamanaşımı süresi dolana
kadar yapılabilir. İhbar veya diğer öğrenme şekilleri re'sen soruşturulan
suçlarda bir dava koşulu değildir.

Takibi şikayete bağlı suçlarda ise *şikayet* bir dava koşuludur. Kanun şikayet
hakkının suçtan zarar görene ait olduğunu belirtmiştir. Korunan hukuki değer
doğrudan birey ile ilişkiliyse suçtan zarar gören mağdurdur. Mülkiyet gibi
müşterek değerler söz konusu ise eşin veya anne ve babanın da suçtan zarar
gören olabileceği kabul edilmektedir.

Birden fazla suçtan zarar gören varsa her kişi diğerlerinden bağımsız olarak
şikayet hakkına sahiptir.

Takibi şikayete bağlı suçlarda kanun şikayet süresini *fiilin ve failin
öğrenilmesinden itibaren altı ay* ile sınırlandırmıştır.

Suça ilişkin ihbar veya şikâyet, Cumhuriyet Başsavcılığına veya kolluk
makamlarına yapılabilir. Valilik veya kaymakamlığa ya da mahkemeye yapılan
ihbar veya şikâyet, ilgili Cumhuriyet Başsavcılığına gönderilir.

Yurt dışında işlenip ülkede takibi gereken suçlar hakkında Türkiye'nin elçilik
ve konsolosluklarına da ihbar veya şikâyette bulunulabilir.

Bir kamu görevinin yürütülmesiyle bağlantılı olarak işlendiği iddia edilen bir
suç nedeniyle, ilgili kurum ve kuruluş idaresine yapılan ihbar veya şikâyet,
gecikmeksizin ilgili Cumhuriyet Başsavcılığına gönderilir.

IMPORTANT: Kamu kurumları kendilerine ulaşan herhangi bir suç bildirimini
savcılığa iletmek zorundadır. Ancak yurt dışında işlenip ülkede takibi gereken
suçlar veya bir kamu görevinin yürütülmesi ile ilgili suçlarda elçilik ve
konsolosluklara veya ilgili kamu kurumuna fiilin ve failin öğrenilmesinden
itibaren altı ay içerisinde yapılacak bildirim süresinde yapılmış kabul
edilecektir. Bunun dışında kalan suçlar bakımından yapılacak bildirim ilgili
kurum tarafından savcılığa ulaştırıldığı tarihte yapılmış sayılacak ve süre
buna göre hesaplanacaktır.

İhbar veya şikâyet yazılı veya tutanağa geçirilmek üzere sözlü olarak
yapılabilir.

Yürütülen soruşturma sonucunda kovuşturma evresine geçildikten sonra suçun
şikâyete bağlı olduğunun anlaşılması halinde; mağdur açıkça şikâyetten
vazgeçmediği takdirde, yargılamaya devam olunur.

Şikayetin konusu takibi şikayete bağlı bir suç oluşturduğu öne sürülen somut
bir fiildir. Dolayısıyla şikayet hakkına sahip olanlardan bir tanesi bu hakkını
kullandığında o suça iştirak eden herkes bakımından dava koşulu sağlanmış olur.
Buna *şikayetin bölünmezliği* veya *şikayetin sirayeti* denir.

Yapılmış bir şikayet hak sahibi olan kişi veya kişiler tarafından o fiille
ilgili hüküm kesinleşinceye kadar geri alınabilir. Şikayetin geri alınması
soruşturmayı takipsizlikle sonuçlandırır, kovuşturma aşamasında ise davanın
düşmesine neden olur. Ancak hüküm kesinleştikten sonra şikayetin geri alınması
kural olarak infaza etki etmez.

Suçtan zarar gören kişi veya kişiler şikayet hakkı doğduktan sonra bu
haklarından vazgeçebilirler. İspat kolaylığı bakımından bu bildirimin savcılık
veya kolluk nezdinde yapılması isabetli olacaktır.

Takibi şikayete bağlı suçlarda şikayetin geri alınması kabul etmeyen sanığı
bağlamaz.

Şikayet geri alındıktan sonra tekrar kullanılamaz.

=== DAVA SÜRELERİ

Kanun koyucu bazı suçlar bakımından fiilin işlenmesinden itibaren davanın
belirli bir süre içerisinde açılmasını zorunlu kılmıştır. Uygulamada çok
rastlanan bir koşul değildir. Örnek için Basın Kanunu 26.

=== İZİN

Anayasa'nın 129. maddesine göre "_Memurlar ve diğer kamu görevlileri hakkında
işledikleri iddia edilen suçlardan ötürü ceza kovuşturması açılması, kanunla
belirlenen istisnalar dışında, kanunun gösterdiği idari merciin iznine
bağlıdır._"

IMPORTANT: İznin konusu suç değil, soruşturmanın konusu olan fiildir.
Soruşturma makamı isnat edilen bir fiilin görev sebebiyle olduğunu belirtmiş ve
izin almışsa süreç içerisinde suç vasfının değişmesi herhangi bir etki
yaratmaz.

İznin istisnası irtikap, rüşvet, basit veya nitelikli zimmet, görevi sırasında
göreviyle alakalı kaçakçılık, resmi ihalede alım satıma fesat karıştırma
suçlarıdır. Bu suçlar söz konusu ise memur veya kamu görevlisinin yargılanması
için izin alınmasına gerek yoktur.

TIP: İznin verilmesine veya verilmemesine ilişkin karar idari bir karardır. Bu
nedenle bu karara karşı çıkma mekanizması da idari yargıdadır. Kanunda da izin
verilmesi halinde şüphelinin izin verilmemesi halinde ise savcı veya suçtan
zarar görenin 10 gün içerisinde bölge adliye mahkemesine itiraz hakkı olduğu
belirtilmiştir.

NOTE: Bkz. 4483 sayılı kanun

=== TALEP

Bazı suçlardan dolayı dava açılması için bir kamu makamının, genellikle Adalet
Bakanlığı'nın talebi gereklidir. Bu durumlarda talep suçun vasfı ne olursa
olsun bir dava koşuludur.

IMPORTANT: Bu başvuru şikayet değildir. Dolayısıyla şikayet ile ilgili hükümler
burada uygulanamaz. Başvuru yapıldıktan sonra geri alınması artık bir dava
koşulu veya engeli değildir.

=== ADALET BAKANI'NIN İZNİ

IMPORTANT: Bu izin ile 4483 sayılı kanunda düzenlenen izin müessesesi aynı
değildir.

Bazı suçlarda, soruşturma veya kovuşturmanın sonucunda bir siyasi etki doğacak
ise davanın açılması Adalet Bakanı'nın iznine bağlıdır. Bu konuda tipik
örnekler Cumhurbaşkanı'na Hakaret, Anayasal Organları ve Türklüğü Tahkir
suçlarıdır.

=== DERDEST DAVA BULUNMASI

Aynı fiil ve aynı kişi ile ilgili daha önce açılmış ve sonuçlandırılmış veya
hali hazırda görülmekte olan bir dava var ise bu bir dava engeli teşkil eder.
Bu durumda soruşturma aşamasında kovuşturmaya yer olmadığına karar
verilmelidir. Kovuşturma aşamasında ise *davanın reddi* kararı verilmelidir.

TIP: Ceza muhakemesinde açılmış bir davanın reddine karar verilebilen tek durum
budur.

=== ÖN ÖDEME

Ön ödemeye tabi suçlar, sadece para cezasını gerektiren veya cezanın üst sınırı
6 ayı geçmeyen suçlardır. Cumhuriyet savcısı ön ödemeye tabi suçlar için
soruşturma sonucunda dava açmaya yeter bir şüpheye ulaşırsa şüpheliye öngörülen
cezanın asgari bir miktarını ödemesini teklif eder. Şüpheli ön ödeme talebini
kabul eder ve ödeme yaparsa soruşturma, kovuşturmaya yer olmadığına dair bir
kararla sonuçlandırılır.

Ön ödemeye tabi bir suç bu yola başvurulmaksızın dava konusu edildiğinde bu
öncelikle bir iddianamenin iadesi sebebidir. Eğer kovuşturma aşamasında suç
vasfı değişip ön ödemeye tabi bir suç haline gelirse mahkeme ön ödemeyi teklif
eder ve ödeme yapıldığı takdirde davanın düşmesine karar verir. Dolayısıyla ön
ödemeye tabi suçlarda ön ödemenin teklif edilip başarısızlıkla sonuçlanması bir
dava koşuludur.

=== UZLAŞTIRMA

Uzlaştırmaya tabi bir suç söz konusu ise uzlaşmanın başarısızlık sonuçlanması
bir dava koşuludur.

=== SANIĞIN HAZIR BULUNMAMASI

Kanunun ayrık tuttuğu hâller saklı kalmak üzere, hazır bulunmayan sanık
hakkında duruşma yapılmaz. Gelmemesinin geçerli nedeni olmayan sanığın zorla
getirilmesine karar verilir.

==== İSTİSNALAR

===== MAHKUMİYET DIŞI KARAR

Sanık hakkında, toplanan delillere göre mahkûmiyet dışında bir karar verilmesi
gerektiği kanısına varılırsa, sorgusu yapılmamış olsa da dava yokluğunda
bitirilebilir.

===== GAİPLİK

Bulunduğu yer bilinmeyen veya yurt dışında bulunup da yetkili mahkeme önüne
getirilemeyen veya getirilmesi uygun bulunmayan sanık gaip sayılır.

Gaip hakkında duruşma açılmaz; mahkeme, delillerin ele geçirilmesi veya
korunması amacıyla gerekli işlemleri yapar.

Bu işlemler naip hâkim veya istinabe olunan mahkeme aracılığıyla da
yapılabilir.

Bu işlemler sırasında sanığın müdafii veya kanunî temsilcisi veya eşi hazır
bulunabilir. Gerektiğinde, mahkemece barodan bir müdafi görevlendirilmesi
istenir.

Adresi bilinmeyen gaibe, mahkeme önüne gelmesi veya adresini bildirmesi
hususları uygun bir iletişim aracıyla ihtar edilir.

Mahkeme, gaip olan sanık hakkında duruşmaya gelmesi hâlinde tutuklanmayacağı
hususunda bir güvence belgesi verebilir ve bu güvence koşullara bağlanabilir.

Sanık, hapis cezası ile mahkûm olur veya kaçmak hazırlığında bulunur veya
güvence belgesinin bağlı olduğu koşullara uymazsa belgenin hükmü kalmaz.

===== SANIĞIN YOKLUĞU

* *Sanığın mahkemeden uzaklaşması:* Mahkemeye gelen sanığın duruşmanın devamı
süresince hazır bulunması sağlanır ve savuşmasının önüne geçmek için mahkeme
gereken tedbirleri alır. Sanık savuşur veya ara vermeyi izleyen oturuma
gelmezse, önceden sorguya çekilmiş ve artık hazır bulunmasına mahkemece gerek
görülmezse, dava yokluğunda bitirilebilir.
* *Sanığın yokluğunda duruşma:* Suç, yalnız veya birlikte adlî para cezasını
veya müsadereyi gerektirmekte ise; sanık gelmese bile duruşma yapılabilir. Bu
gibi hâllerde sanığa gönderilecek davetiyede gelmese de duruşmanın yapılacağı
yazılır.
* *Sanığın duruşmadan bağışık tutulması:* Mahkemece sorgusu yapılmış olan sanık
veya bu hususta sanık tarafından yetkili kılındığı hâllerde müdafii isterse,
mahkeme sanığı duruşmada hazır bulunmaktan bağışık tutabilir.
* *Sorgu sırasında sanığın mahkeme salonundan çıkarılabilmesi:* Sanığın yüzüne
karşı suç ortaklarından birinin veya bir tanığın gerçeği söylemeyeceğinden
endişe edilirse, mahkeme, sorgu ve dinleme sırasında o sanığın mahkeme
salonundan çıkarılmasına karar verebilir. Sanık tekrar getirildiğinde,
tutanaklar okunur ve gerektiğinde içeriği anlatılır.
* *Sanığın duruşmanın düzenini bozması:* Mahkeme başkanı veya hâkim, duruşmanın
düzenini bozan kişinin, savunma hakkının kullanılmasını engellememek koşuluyla
salondan çıkarılmasını emreder.
* *Sanığın dışarı çıkarılması:* Davranışları nedeniyle, hazır bulunmasının
duruşmanın düzenli olarak yürütülmesini tehlikeye sokacağı anlaşıldığında
sanık, duruşma salonundan çıkarılır. Mahkeme, sanığın duruşmada hazır
bulunmasını dosyanın durumuna göre savunması bakımından zorunlu görmezse,
oturumu yokluğunda sürdürür ve bitirir. Ancak, sanığın müdafii yoksa, mahkeme
barodan bir müdafi görevlendirilmesini ister. Oturuma yeniden alınmasına karar
verilen sanığa, yokluğunda yapılan işlemler açıklanır.

===== KAÇAKLIK

Hakkındaki soruşturmanın veya kovuşturmanın sonuçsuz kalmasını sağlamak
amacıyla yurt içinde saklanan veya yabancı ülkede bulunan ve bu nedenle
Cumhuriyet savcısı veya mahkeme tarafından kendisine ulaşılamayan kişiye kaçak
denir.

Hakkında, 248 inci maddenin ikinci fıkrasında belirtilen suçlardan dolayı
soruşturma veya kovuşturma başlatılmış olan şüpheli veya sanığın, yetkili
Cumhuriyet savcısı veya mahkemece usulüne göre yapılan tebligata uymamasından
dolayı verilen zorla getirilme kararı da yerine getirilemez ise, Cumhuriyet
savcısı veya mahkeme;

.. Çağrının bir gazete ile şüpheli veya sanığın bilinen konutunun kapısına
asılmak suretiyle ilânına karar verir; yapılacak ilânlarda, onbeş gün içinde
gelmediği takdirde 248 inci maddede gösterilen tedbirlere hükmedilebileceğini
ayrıca açıklar,
.. Bu işlemlerin yerine getirildiğinin bir tutanak ile saptanmasından itibaren
onbeş gün içinde başvurmayan şüpheli veya sanığın kaçak olduğuna karar verir.

Kaçak sanık hakkında kovuşturma yapılabilir. Ancak, daha önce sorgusu
yapılmamış ise, mahkûmiyet kararı verilemez.

Duruşma yapılan hâllerde kaçak sanığın müdafii yoksa, mahkeme barodan bir
avukat görevlendirilmesini ister.

Kaçağın Cumhuriyet savcısına başvurmasını veya duruşmaya gelmesini sağlamak
amacıyla Türkiye'de bulunan mallarına, hak ve alacaklarına amaçla orantılı
olarak Cumhuriyet savcısının istemi üzerine sulh ceza hâkimi veya mahkeme
kararıyla elkonulabilir ve gerektiğinde idaresi için kayyım atanır. Elkoyma ve
kayyım atama kararı müdafiine bildirilir.

Yukarıdaki tedbirler;

.. Türk Ceza Kanununda tanımlanan;

. Soykırım ve insanlığa karşı suçlar (madde 76, 77, 78),
. Göçmen kaçakçılığı ve insan ticareti (madde 79, 80),
. Hırsızlık (madde 141, 142),
. Yağma (madde 148, 149),
. Güveni kötüye kullanma (madde 155),
. Dolandırıcılık (madde 157, 158),
. Hileli iflas (madde 161),
. Uyuşturucu veya uyarıcı madde imal ve ticareti (madde 188),
. Parada sahtecilik (madde 197),
. Suç işlemek amacıyla örgüt kurma (madde 220),
. Zimmet (madde 247),
. İrtikâp (madde 250),
. Rüşvet (madde 252),
. İhaleye fesat karıştırma (madde 235),
. Edimin ifasına fesat karıştırma (madde 236),
. Devletin Güvenliğine Karşı Suçlar (madde 302, 303, 304, 305, 306, 307, 308),
. Anayasal Düzene ve Bu Düzenin İşleyişine Karşı Suçlar (madde 309, 310, 311,
312, 313),
. Silahlı örgüt (madde 314) veya bu örgütlere silah sağlama (madde 315),
. Devlet Sırlarına Karşı Suçlar ve Casusluk (madde 328, 329, 330, 331, 333,
334, 335, 336, 337) suçları,

.. Ateşli Silahlar ve Bıçaklar ile Diğer Aletler Hakkında Kanunda tanımlanan
silah kaçakçılığı (madde 12) suçları,
.. Bankalar Kanununun 22 nci maddesinin (3) ve (4) numaralı fıkralarında
tanımlanan zimmet suçu,
.. Kaçakçılıkla Mücadele Kanununda tanımlanan ve hapis cezasını gerektiren
suçlar,
.. Kültür ve Tabiat Varlıklarını Koruma Kanununun 68 ve 74 üncü maddelerinde
tanımlanan suçlar,

Hakkında uygulanır.

Elkonulan mal, hak ve alacakların korunmasında, elkoymaya ilişkin hükümler
uygulanır. Tedbirlere ilişkin kararların özetinin bir gazetede ilânına sulh
ceza hâkimince veya mahkemece karar verilebilir.


Kaçak yakalandığında veya kendiliğinden gelerek teslim olduğunda elkoymanın
kaldırılmasına karar verilir.

Kaçak hakkında 100 üncü ve sonraki maddeler gereğince, sulh ceza hâkimi veya
mahkeme tarafından yokluğunda tutuklama kararı verilebilir.

Sulh ceza hâkimi veya mahkeme elkoymaya karar verdiğinde, kaçağın yasal olarak
bakmakla yükümlü bulunduğu yakınlarının alınan tedbirler nedeniyle yoksulluğa
düşebileceklerini saptarsa, bunların geçimlerini sağlamak üzere, elkonulan mal
varlığından sosyal durumları ile orantılı miktarda yardımda bulunulması
konusunda kayyıma izin verir.

NOTE: 246 ncı madde hükmü kaçaklar hakkında da uygulanır.

TIP: Bu kararlara karşı itiraz edilebilir.

== CEZA MUHAKEMESİNİN ÖZNELERİ

=== HAKİM

==== HAKİMİN YASAKLILIK HALLERİ

Hâkim;

.. Suçtan kendisi zarar görmüşse,
.. Sonradan kalksa bile şüpheli, sanık veya mağdur ile aralarında evlilik,
vesayet veya kayyımlık ilişkisi bulunmuşsa,
.. Şüpheli, sanık veya mağdurun kan veya kayın hısımlığından üstsoy veya
altsoyundan biri ise,
.. Şüpheli, sanık veya mağdur ile aralarında evlât edinme bağlantısı varsa,
.. Şüpheli, sanık veya mağdur ile aralarında üçüncü derece dahil kan hısımlığı
varsa,
.. Evlilik sona ermiş olsa bile, şüpheli, sanık veya mağdur ile aralarında
ikinci derece dahil kayın hısımlığı varsa,
.. Aynı davada Cumhuriyet savcılığı, adlî kolluk görevi, şüpheli veya sanık
müdafiliği veya mağdur vekilliği yapmışsa,
.. Aynı davada tanık veya bilirkişi sıfatıyla dinlenmişse,

hâkimlik görevini yapamaz.

==== HAKİMİN YARGILAMAYA KATILAMAYACAĞI HALLER

Bir karar veya hükme katılan hâkim, yüksek görevli mahkemece bu hükme ilişkin
olarak verilecek karar veya hükme katılamaz.

Aynı işte soruşturma evresinde görev yapmış bulunan hâkim, kovuşturma evresinde
görev yapamaz.

CAUTION: Suçüstü hâli ile gecikmesinde sakınca bulunan hâllerde, Cumhuriyet
savcısına erişilemiyorsa veya olay genişliği itibarıyla Cumhuriyet savcısının
iş gücünü aşıyorsa, sulh ceza hâkimi de bütün soruşturma işlemlerini yapabilir.
Ancak bu durumda soruşturma evresinde görev yapmış hakim kovuşturma evresinde
görev alamaz. Diğer durumlar için yukarıdaki hüküm uygulanmaz.

Yargılamanın yenilenmesi halinde, önceki yargılamada görev yapan hâkim, aynı
işte görev alamaz.

==== HAKİMİN REDDİ

Hâkimin davaya bakamayacağı hâllerde reddi istenebileceği gibi, tarafsızlığını
şüpheye düşürecek diğer sebeplerden dolayı da reddi istenebilir.

TIP: Hakimin yargılama sürecinde dosya ile ilgili düşüncesini ortaya koyan
herhangi bir ifade hakimin reddi sebebidir. Ancak somut olaya benzer bilimsel
veya siyasi görüşler hakimin reddi sebebi oluşturmaz.

Cumhuriyet savcısı; şüpheli, sanık veya bunların müdafii; katılan veya vekili,
hâkimin reddi isteminde bulunabilirler.

Tarafsızlığını şüpheye düşürecek sebeplerden dolayı bir hâkimin reddi, ilk
derece mahkemelerinde sanığın sorgusu başlayıncaya; duruşmalı işlerde bölge
adliye mahkemelerinde inceleme raporu ve Yargıtayda görevlendirilen üye veya
tetkik hâkimi tarafından yazılmış olan rapor üyelere açıklanıncaya kadar
istenebilir. Diğer hâllerde, inceleme başlayıncaya kadar hâkimin reddi
istenebilir.

Sonradan ortaya çıkan veya öğrenilen sebeplerle duruşma veya inceleme bitinceye
kadar da hâkimin reddi istenebilir. Ancak bu istemin, ret sebebinin
öğrenilmesinden itibaren yedi gün içinde yapılması şarttır.

Hâkimin reddi, mensup olduğu mahkemeye verilecek dilekçeyle veya bu hususta
zabıt kâtibine bir tutanak düzenlenmesi için başvurulması suretiyle yapılır.

Ret isteminde bulunan, öğrendiği ret sebeplerinin tümünü bir defada açıklamak
ve süresi içinde olguları ile birlikte ortaya koymakla yükümlüdür.

Reddi istenen hâkim, ret sebepleri hakkındaki görüşlerini yazılı olarak
bildirir.

Hâkimin reddi istemine mensup olduğu mahkemece karar verilir. Ancak, reddi
istenen hâkim müzakereye katılamaz. Bu nedenle mahkeme teşekkül edemezse bu
hususta karar verilmesi;

.. Reddi istenen hâkim asliye ceza mahkemesine mensup ise bu mahkemenin yargı
çevresi içerisinde bulunan ağır ceza mahkemesine,
.. Reddi istenen hâkim ağır ceza mahkemesine mensup ise o yerde ağır ceza
mahkemesinin birden fazla dairesinin bulunması hâlinde, numara olarak kendisini
izleyen daireye, son numaralı daire için (1) numaralı daireye; o yerde ağır
ceza mahkemesinin tek dairesi bulunması hâlinde ise, en yakın ağır ceza
mahkemesine,

Aittir.

Ret istemi sulh ceza hâkimine karşı ise, yargı çevresi içinde bulunduğu asliye
ceza mahkemesi ve tek hâkime karşı ise, yargı çevresi içerisinde bulunan ağır
ceza mahkemesi karar verir.

Ret isteminin kabulü halinde, davaya bakmakla bir başka hâkim veya mahkeme
görevlendirilir.

Ret isteminin kabulüne ilişkin kararlar kesindir; kabul edilmemesine ilişkin
kararlara karşı itiraz yoluna gidilebilir. İtiraz üzerine verilen ret kararı
hükümle birlikte incelenir.

Reddi istenen hâkim, ret hakkında bir karar verilinceye kadar yalnız
gecikmesinde sakınca olan işlemleri yapar.

Ancak, hâkimin oturum sırasında reddedilmesi hâlinde, bu konuda bir karar
verilebilmesi için oturuma ara vermek gerekse bile ara vermeksizin devam
olunur. Şu kadar ki, 216 ncı madde uyarınca tarafların iddia ve sözlerinin
dinlenilmesine geçilemez ve ret konusunda bir karar verilmeden reddedilen hâkim
tarafından veya onun katılımıyla bir sonraki oturuma başlanamaz.

Ret isteminin kabulüne karar verildiğinde, gecikmesinde sakınca bulunan hâl
nedeniyle yapılmış işlemler dışında, duruşma tekrarlanır.

Hâkim, yasaklılığını gerektiren sebeplere dayanarak çekindiğinde; merci, bir
başka hâkimi veya mahkemeyi davaya bakmakla görevlendirir.

Hâkim, tarafsızlığını şüpheye düşürecek sebepler ileri sürerek çekindiğinde,
merci çekinmenin uygun olup olmadığına karar verir. Çekinmenin uygun bulunması
halinde, davaya bakmakla bir başka hâkim veya mahkeme görevlendirilir.

Mahkeme, kovuşturma evresinde ileri sürülen hâkimin reddi istemini aşağıdaki
durumlarda geri çevirir:

.. Ret istemi süresinde yapılmamışsa.
.. Ret sebebi ve delili gösterilmemişse.
.. Ret isteminin duruşmayı uzatmak amacı ile yapıldığı açıkça anlaşılıyorsa.

Bu hâllerde ret istemi, toplu mahkemelerde reddedilen hâkimin müzakereye
katılmasıyla, tek hâkimli mahkemelerde de reddedilen hâkimin kendisi tarafından
geri çevrilir. Bu konudaki kararlara karşı itiraz yoluna başvurulabilir.

=== SAVCI

Cumhuriyet savcılarının görevi kamu adına iddiada bulunmak, iddia faaliyetini
gerçekleştirmektir.

İddia makamı sadece kişinin suçlanması, ceza alması için uğraşan bir makam
değildir. *Savcı, şüpheli veya sanığın lehine bir delil gördüğü zaman bunu da
dosyaya koymalıdır.

TIP: Savcının reddine ilişkin bir düzenleme hukukumuzda yer almamaktadır.
Hakimin reddi sebepleri sınırlayıcı bir hüküm olduğundan kıyas serbestisinin
istisnasını oluşturur ve savcının reddi için uygulanamaz.

Cumhuriyet savcıları il merkezinde ve gerektiği takdirde ilçelerd kurulan
Cumhuriyet Başsavcılıkları şeklinde örgütlenir. Cumhuriyet Başsavcılıklarında
bir Cumhuriyet Başsavcısı ve yeterli sayıda Cumhuriyet savcısı bulunur.
Cumhuriyet Başsavcısı görevini altındaki Cumhuriyet savcıları eliyle ifa eder.
Cumhuriyet savcıları görevlerini ifa ederken bağlı bulundukları Cumhuriyet
Başsavcısı adına hareket ederler.

NOTE: Cumhuriyet savcıları arasındaki ilişki işbölümü ilişkisidir.

==== CUMHURİYET SAVCILARININ GÖREVLERİ

. *Suçun işlendiğine dair bildirimin araştırılması*: Cumhuriyet savcısı bir suç
şüphesi bildirimi aldıktan sonra fiile ilişkin birtakım delilleri toplayıp,
süpheli hakkındaki şüpheyi belirli bir seviyeye getirdikten sonra iddianameyi
düzenler.
+
NOTE: Ağustos 2017'ye kadar Cumhuriyet savcıları kendilerene gelen tüm suç
bildirimlerini değerlendirerek soruşturma açmak zorundaydı. Ancak son yapılan
değişiklik ile gelen suç bildirimi soyut veya yalan olduğu ilk bakışta
anlaşılır nitelikte ise soruşturma açma zorunluluğu kaldırıldı.
+
IMPORTANT: Cumhuriyet savcısının *dava açma yetkisi yoktur*. Kamu davasını
açacak olan makam iddianameyi kabul eden görevli ve yetkili mahkemedir.
. *Kamu davası açıldıktan sonra davanın takip edilmesi*: Cumhuriyet savcısı
yargılamayı baştan sona takip etmek zorundadır. Burada delilleri ileri sürmek,
mütalaa vermek gibi birtakım görevleri söz konusudur. Yargılamanın sonunda
karara karşı kanun yoluna başvurma yetkisi vardır.
+
NOTE: Bunlar Ağır Ceza mahkemeleri için geçerlidir. 2020 yılına kadar Asliye
Ceza mahkemelerinde Cumhuriyet savcıları yer almayacaktır.
. *Koruma tedbirlerine başvurma*: Kural olarak şüpheli veya sanık hakkında
koruma tedbirine başvurmak için hakim kararı gerekir. Ancak gecikmesinde
sakınca bulunan hallerde Cumhuriyet savcıları koruma tedbirlerine karar
verebilir.
. *Cezanın infazını takip etme*
. *Kanunun verdiği diğer görevleri yerine getirme*

==== ADLİ KOLLUK

Polis, kamu düzenini koruyan ve esas amacı suçun işlenmesi önlemek olan meslek
grubudur. Ancak Cumhuriyet savcısının polisten beklentisi işlenmiş olan bir
fiil sonucunda ortaya çıkan kamu düzeni bozukluğuna yönelik birtakım delillerin
bulunup kişilere ulaşılmasıdır.

Kolluk valilere, oradan da İçişleri Bakanlığı'na bağlıdır. Bütün atamalar,
maaşlar İçişleri Bakanlığı tarafından organize edilmektedir. Ancak Cumhuriyet
savcısı da her yılın sonunda adli kolluk hakkında bir rapor hazırlayarak mülki
amire gönderir.

Adli kolluk personeli görevi sırasında Cumhuriyet savcısı ve adli kolluk amiri
dışında kimseden emir almaz ve kimseye de görevi hakkında bilgi vermemelidir.
Soruşturma aşamasında kural olarak tek yetkili Cumhuriyet savcısıdır.
Cumhuriyet savcısının emri olmaksızın adli kolluk işlem yapamaz.

TIP: Son çıkan bir KHK ile kolluğa Cumhuriyet savcısına haber vermeden gözaltı
yapabilme yetkisi verilmiştir.

Cumhuriyet savcısının adli kolluğa her işlem için ayrı ayrı emir vermesi
gerekir. Kolluğa genel bir yetki verilemez. Adli kolluğa verilecek emir kural
olarak yazılı olmalıdır. Ancak gecikmesinde sakınca olan hallerde emir önce
sözlü sonra yazılı verilebilir.

===== KOLLUĞUN İŞLEDİĞİ SUÇLAR

Kolluk mensubu kişilerin işledikleri suçlar için önemli olan fiil ile görev
arasında bağlantı olup olmadığıdır.

Fiil ile görev arasında bağlantı olmadığı hallerde suçu normal bir vatandaş
işlemiş gibi sorumluluk doğar.

Görev ile fiil arasında bağlantı varsa görev bakımından amirin kim olduğu
sorusu gündeme gelir.

Kolluğun önleyici görevi sırasında bir suç işlenmişse soruşturma başlatılması
için mülki amirden izin alınacaktır. *Cumhuriyet savcısı nezdinde bir soruşturma
yürütülürken adli kolluk görevi sırasında suç işlenmişse Cumhuriyet savcısı
herhangi bir izne tabi olmadan soruşturma başlatabilecektir.*

NOTE: Kolluğun işlediği suç zimmet, rüşvet, irtikap gibi izin alınmasına gerek
olmayan suçlardan biri ise amirin kim olduğuna bakılmaksızın izinsiz soruşturma
başlatılabilir.

=== SULH CEZA HAKİMİ

Soruşturma aşamasında hakim kararı gereken işlemlerde kararı verecek olan Sulh
Ceza hakimidir.

Ayrıca Sulh Ceza hakimi, Cumhuriyet savcısına ulaşılamadığı veya Cumhuriyet
savcısının iş yükünden dolayı işlem yapamadığı hallerde Cumhuriyet savcısı gibi
hareket edebilir.

=== MAĞDUR, ZARAR GÖREN, MALEN SORUMLU VE KATILAN

*Mağdur*, bir suçta suçun maddi unsurlarına maruz kalan kimsedir. Mağdur ile
*suçtan zarar gören* aynı kişi olmak zorunda değildir.

Suçtan zarar gören;

. Sağ bir kişi olmalıdır.
. Dava ehliyetine sahip olmalıdır.
. Gerçek veya tüzel kişi olabilir.

Suçtan zarar gören veya mağdur, katılan sıfatıyla yargılamaya katılabilecektir.
Katılan yargılamanın bir tarafı olur ve birtakım hak ve yükümlülüklere sahip
olur.

Mağdur veya suçtan zarar gören olmak katılan olmak için yeterli değildir. Bu
kişiler ayrıca **katılma talebi**nde bulunmalıdır.

IMPORTANT: Kanun yoluna başvurmak için katılma talebinin var olması yeterlidir.

*Malen sorumlu*, yargılamadaki sonuca göre bir kimse suçlu olarak kabul
edildiğinde ekonomik olarak sorumluluğu doğacak kimsedir. Malen sorumlu da
katılma talebinde bulunabilir.

Katılma talebinin kabul edilmesinden sonra katılan bakımından dava bir yan dava
şeklinde yürüyecektir. Bu yan dava tamamen ana davaya bağlıdır.

NOTE: Yargıtay, re'sen kovuşturulacak suçlar bakımından kişinin katılan
olabilmesi için bir şart aramaktadır. Suçtan zarar gören veya mağdur olarak
olayı mahkemeye anlatırken sanığın cezalandırılması istendiği açıkça söylenmez
ise Yargıtay'a göre artık katılan talebinde bulunulamaz.

IMPORTANT: Soruşturma aşamasında katılma olmaz. Katılan olabilmek için
soruşturmanın kovuşturma aşamasına geçmiş olması ve ilk derece mahkemesinin
kararını vermesine kadar katılma talebinde bulunulması gerekir.

=== ŞÜPHELİ VE SANIK

Kişi *soruşturma aşamasındayken şüpheli*, *kovuşturma aşamasında sanıktır*.

Bir kişinin suç işlediğine dair ihbarın Cumhuriyet savcılığına iletilmiş olması
o kişiyi şüpheli hale getirmez. Şüpheli sıfatının kazanılması için o kişi
hakkında soruşturma başlatılması gerekir.

Soruşturma açılabilmesi için şüphelinin kimliğinin belli olması şart değildir.

[TIP]
====
Doktrinde iddianemede şüphelinin belli olması gerekip gerekmediği tartışma
konusudur.

Bir görüşe göre kişinin kimliğinin bilinmesine gerek yoktur. Kişinin eşkalinin
belirlenmesi ve ona geçici bir isim vermek suretiyle iddianame düzenlenebilir.

Kürsüye göre ise iddianamenin düzenlenebilmesi için şüphelinin kimliğinin
belirli olması gerekir.
====

==== ŞÜPHELİ VE SANIĞIN HAKLARI

. *Savunma hakkı*: En tipik örnek olarak soruşturma aşamasında şüphelinin
ifadesini almayan Cumhuriyet savcısı bu kişi hakkında iddianeme düzenleyemez.
. *Susma hakkı*: Şüpheli veya sanık dava veya soruşturma konusu fiil ile ilgili
olarak bir şey söylemek zorunda değildir. Bir şey söylenmemiş olması ikrar
anlamına gelmez.
+
TIP: Kişi kimliğinin tespitine ilişkin durumlarda susma hakkını kullanamaz.
. *Kendisini ve yakınlarını suçlamama hakkı*
. *Soru sorma hakkı*
. *Tercümandan yararlanma hakkı*
. *Delil toplama ve ibraz etme hakkı*
. *Delillerin toplanmasını isteme hakkı*
. *Duruşmada hazır bulunma hakkı*: Mahkemede hazır bulunmak hak olduğu kadar
yükümlülüktür. Sanık çağrıldığı halde gelmezse zorla getirtilebilir. Kişi hazır
değilse ve istisnalar da söz konusu değilse yargılamaya devam edilemez.
. *Yakalandığını veya gözaltına alındığını yakınlarına bildirme hakkı*
. *Müdafii tayin hakkı*: Kişi müdafii olmadan kollukta ifade verir ancak
mahkemede bu ifadesini kabul etmez ise ifade geçersiz olur. Kanun koyucu bazı
suçlar bakımından müdafiden yararlanmayı zorunlu kılmıştır.
. *Yakalanma ve gözaltı işlemlerine veya gözaltı süresinin uzatılmasına ilişkin
Cumhuriyet savcısının emirlerine karşı Sulh Ceza Hakimliğine başvurma hakkı*

=== MÜDAFİ

Müdafi, şüpheli veya sanığın avukatıdır. Müdafilikte temsilden ziyade
yardımcılık ilişkisi vardır. Sanık veya şüpheli ile müdafi arasında vekalet
ilişkisinin olmasına gerek yoktur. Müdafi ile sanık birbirinden ayrı iki
öznedir.

Müdafi ile sanık arasında vekalet ilişkisi olmasa da müdafi sanığın iradesi ile
sınırlıdır. Sanık istediği zaman müdafiyi görevden alabilir.

AİHS, sanık veya şüphelinin müdafiden yararlanması bakımından üç ilke
belirlemiştir:

. Kişiye kendisini bizzat savunma hakkı tanınmalıdır.
. Kişiye müdafiden yararlanma hakkı tanınmalıdır.
. Kişi müdafiden yararlanmak için gerekli olan mali güce sahip değilse
müdafi devlet tarafından atanmalıdır.

Kişi müdafisini istediği şekilde seçebilir. Birden fazla müdafiye de sahip
olabilir. Bunun iki istisnası vardır:

. Soruşturma aşamasında, ifade verme işlemine en fazla üç müdafi katılabilir.
. Kovuşturma aşamasında, terör suçlarıyla ilgili olan yargılamalarda duruşmaya
en fazla üç müdafi girebilir.

Kural olarak sanık veya şüpheli istediği sürece müdafiden yararlanabilir.
İsterse müdafiden yararlanma hakkını kullanmaz. Zorunlu müdafilik istisnai
durumdur.

Şüpheli veya sanık;

. Çocuksa
. Kendini savunamayacak derecede malulse
. Sağır *ve* dilsiz ise
. Alt sınırı *beş yıldan fazla* hapis cezası öngören bir suçtan yargılanıyorsa

zorunlu müdafilik sistemi geçerlidir.

NOTE: Tutuklanacak veya gözlem altına alınacak kişinin müdafisi yoksa kişinin
iradesine bakılmaksızın müdafi atanacaktır.

Zorunlu müdafilik halinde kişi istediği avukatı seçebilir. Ancak avukat
seçmemesi halinde iradesine bakılmaksızın bir müdafi atanacaktır. Bu
görevlendirme soruşturma aşamasında soruşturmayı yapan makamın, kovuşturma
aşamasında kovuşturmayı yapan makamın talebi üzerine o yerin bağlı olduğu
barodan yapılacaktır.

İhtiyari müdafilikte kollukta müdafi olmadan alınan ifade kural olarak hukuka
uygundur ancak sanık kovuşturma aşamasında ifadesinden dönebilir. Ancak zorunlu
müdafilikte müdafi olmadan verilen ifade hukuka aykırıdır. Bu durumda verilen
ifade hiçbir şekilde delil olarak kullanılamaz.

TIP: Yargılama esnasında suçun niteliği değişir ve zorunlu müdafiliği
gerektiren bir suçun varlığı tespit edilirse daha önce yapılmış işlemler
geçerliliğini korur.

Müdafi, bulunduğu pozisyon itibariyle ancak sanığın lehine olan delilleri
ortaya koymak zorundadır. Mahkeme aleyhe bir delili direkt olarak sorarsa
müdafi susma hakkını kullanabilir ancak yalan söyleme hakkı yoktur.

Müdafi, soruşturma evresinde dosya içeriğini inceleyebilir ve istediği
belgelerin bir örneğini harçsız olarak alabilir.

Müdafiin dosya içeriğini inceleme veya belgelerden örnek alma yetkisi,
soruşturmanın amacını tehlikeye düşürebilecek ise Cumhuriyet savcısının istemi
üzerine hâkim kararıyla kısıtlanabilir. Bu karar ancak CMK 153'teki suçlar söz
konusu ise verilebilir.

Müdafiden yararlanma hakkı aynı zamanda kişilerin müdafi ile serbest bir
şekilde görüşme imkanını da kapsar. 2016 yılında çıkan bir KHK ile buna bir
istina getirilmiştir. Buna göre şüpheli müdafi ile görüşmekten 24 saat ile
sınırlı olmak kaydıyla men edilebilir.

== GÖREV VE YETKİ

=== MADDİ ANLAMDA YETKİ (GÖREV)

Ceza mahkemeleri kanun tarafından ikiye ayrılmıştır: *Asliye ceza* mahkemeleri
ve *ağır ceza* mahkemeleri.

Kural olarak bütün suçlar asliye ceza mahkemelerinde görülür. İstisnai olarak
cezası ağırlaştırılmış müebbet hapis, müebbet hapis veya 10 yıl üstü olan
suçlarda görevli mahkeme ağır ceza mahkemeleridir.

Ayrıca hileli iflas, nitelikli dolandırıcılık, irtikap, resmi belgede
sahtecilik ve Terörle Mücadele Kanunu kapsamındaki suçlarda öngörülen ceza 10
yıldan az olsa da görevli mahkeme ağır ceza mahkemeleridir.

Mahkeme, yargıladığı olay bakımından görevli olup olmadığını kovuşturmanın her
aşamasında denetlemekle yükümlüdür.

TIP: Kanun bir mahkemeye özel yargılama usullerini öngörmüş, yani işbölümüne ek
olarak birtakım özel usullere yer vermişse artık bu ayrıma görev ayrımına
yaklaşır.

Bir mahkeme görevli veya yetkili olup olmadığını ancak kovuşturmaya geçtikten
sonra denetleyebilir. Ancak Yargutay'a göre mahkeme iddianameye baktığında
kendisinin açıkça görevsiz olduğunu görüyorsa iddianemeyi iade edebilir.

==== İSTİSNAEN MADDE BAKIMINDAN YETKİLİ OLMA HALLERİ

. *Görevsizlik kararı verilemeyecek hâl*: Duruşmada suçun hukukî niteliğinin
değiştiğinden bahisle görevsizlik kararı verilerek dosya alt dereceli mahkemeye
gönderilemez.
+
Başka bir ifadeyle, bir ağır ceza mahkemesi duruşma süresince (yoklama ile
başlayıp hükümle son bulan sürece) fiilin hukuki vasfının değiştiği gerekçesi
ile görevsizlik kararı vererek dosyayı asliye ceza mahkemesine gönderemez.
. *Bağlantı*: Bir kişi, birden fazla suçtan sanık olur veya bir suçta her ne
sıfatla olursa olsun birden fazla sanık bulunursa bağlantı var sayılır. Suçun
işlenmesinden sonra suçluyu kayırma, suç delillerini yok etme, gizleme veya
değiştirme fiilleri de bağlantılı suç sayılır.
+
Bir fiil sebebiyle birden fazla kişinin soruşturulduğu veya kovuşturulduğu
durumlarda **objektif bağlantı**dan bahsedilir. Bir kişinin birden fazla fiil
sebebiyle soruşturulduğu veya kovuşturulduğu durumlarda ise **subjektif
bağlantı**dan söz edilir.
+
Bağlantılı suçlardan her biri değişik mahkemelerin görevine giriyorsa, bunlar
hakkında birleştirilmek suretiyle yüksek görevli mahkemede dava açılabilir.
+
Kovuşturma evresinin her aşamasında, bağlantılı ceza davalarının
birleştirilmesine veya ayrılmasına yüksek görevli mahkemece karar verilebilir.
Birleştirilen davalarda, bu davaları gören mahkemenin tâbi olduğu yargılama
usulü uygulanır. İşin esasına girdikten sonra ayrılan davalara aynı mahkemede
devam olunur.
+
*Geniş bağlantı sebebiyle birleştirme*: Mahkeme, bakmakta olduğu birden çok
dava arasında bağlantı görürse, bu bağlantı yukarıda gösterilen türden olmasa
bile, birlikte bakmak ve hükme bağlamak üzere bu davaların birleştirilmesine
karar verebilir.
+
Birleştirme kararının verilebilmesi için yargılamanın amaca uygun biçimde
sonuçlandırılması bakımından bir fayda bulunmalıdır.
+
Birleştirme kararı soruşturma evresinde soruşturmayı yürüten savcılık
tarafından, kovuşturma evresinde ise yüksek görevli mahkeme tarafından
verilecektir.
+
Bağlantının varlığı halinde *birleştirme* yapılabileceği gibi diğer mahkemedeki
uyuşmazlığın çözümü *bekletici sorun* yapılabilir veya mahkeme diğer uyuşmazlık
kendi yargı alanına girmemesine rağmen kendisine yetecek kadar olan kısmı
çözebilir, yani *nisbi muhakeme* yapabilir. Bunlarda hangisinin yapılacağı
kural olarak ceza hakiminin takdirine kalmıştır. Bunun iki istisnası vardır:

.. Anayasa'ya aykırılık iddiası ileri sürüldüğünde ceza hakimi nisbi muhakeme
yapamaz. Bu durumda bekletici mesele yapmak ve söz konusu başvuruyu Anayasa
Mahkemesi'ne göndermek zorundadır.
.. Kovuşturma evresinde mağdur veya sanığın yaşının ceza hükümleri bakımından
tespitiyle ilgili bir sorunla karşılaşılması halinde; mahkeme, ilgili kanunda
belirlenen usule göre bu sorunu çözerek hükmünü verir.

==== GÖREV UYUŞMAZLIĞI

Bir uyuşmazlık hakkında iki mahkemenin de kendini görevli olarak görmesi
*olumlu görev uyuşmazlığı*, görevsiz olarak görmesi ise *olumsuz görev
uyuşmazlığı* olarak adlandırılır.

Olumsuz görev uyuşmazlığının çözümlenmesi bir üst dereceli mahkeme tarafından
yapılır.

==== GÖREVLİ OLMAYAN MAHKEMENİN İŞLEMLERİ

Yenilenmesi mümkün olmayanlar dışında, görevli olmayan hâkim veya mahkemece
yapılan işlemler hükümsüzdür.

NOTE: İddianamenin kabulü kararı yenilenmesi mümkün olmayan bir işlemdir.

=== YER BAKIMINDAN YETKİ

Yer bakımından yetki bir yargılamanın hangi coğrafi bölgedeki mahkemede
yapılacağını belirtir.

Davaya bakmak yetkisi, suçun işlendiği yer mahkemesine aittir.

Teşebbüste son icra hareketinin yapıldığı, kesintisiz suçlarda kesintinin
gerçekleştiği ve zincirleme suçlarda son suçun işlendiği yer mahkemesi
yetkilidir.

Suç, ülkede yayımlanan bir basılı eserle işlenmişse yetki, eserin yayım merkezi
olan yer mahkemesine aittir. Ancak, aynı eserin birden çok yerde basılması
durumunda suç, eserin yayım merkezi dışındaki baskısında meydana gelmişse, bu
suç için eserin basıldığı yer mahkemesi de yetkilidir.

Soruşturulması ve kovuşturulması şikâyete bağlı olan hakaret suçunda eser,
mağdurun yerleşim yerinde veya oturduğu yerde dağıtılmışsa, o yer mahkemesi de
yetkilidir. Mağdur, suçun işlendiği yer dışında tutuklu veya hükümlü
bulunuyorsa, o yer mahkemesi de yetkilidir.

Görsel veya işitsel yayınlarda da bu maddenin üçüncü fıkrası hükmü uygulanır.
Görsel ve işitsel yayın, mağdurun yerleşim yerinde ve oturduğu yerde işitilmiş
veya görülmüşse o yer mahkemesi de yetkilidir.

Suçun işlendiği yer belli değilse, şüpheli veya sanığın yakalandığı yer,
yakalanmamışsa yerleşim yeri mahkemesi yetkilidir.

Şüpheli veya sanığın Türkiye'de yerleşim yeri yoksa Türkiye'de en son adresinin
bulunduğu yer mahkemesi yetkilidir.

Mahkemenin bu suretle de belirlenmesi olanağı yoksa, ilk usul işleminin
yapıldığı yer mahkemesi yetkilidir.

CAUTION: Yer bakımından yetki kamu düzenine ilişkin değildir.

==== YER BAKIMINDAN YETKİ KURALININ İSTİSNALARI

. *Bağlantı*: Her biri değişik mahkemelerin yetkisi içinde bulunan bağlantılı
ceza davaları, yetkili mahkemelerden herhangi birisinde birleştirilerek
görülebilir.
+
Bağlantılı ceza davalarının değişik mahkemelerde bakılmasına başlanmış olursa,
Cumhuriyet savcılarının istemlerine uygun olmak koşuluyla, mahkemeler arasında
oluşacak uyuşma üzerine, bu davaların hepsi veya bir kısmı bu mahkemelerin
birinde birleştirilebilir.
+
Uyuşulmazsa, Cumhuriyet savcısı veya sanığın istemi üzerine ortak yüksek
görevli mahkeme birleştirmeye gerek olup olmadığına ve gerek varsa hangi
mahkemede birleştirileceğine karar verir.
+
Birleştirilmiş olan davaların ayrılması da bu suretle olur.
. *Muhakemenin nakli*: Yetkili hâkim veya mahkeme, hukukî veya fiilî sebeplerle
görevini yerine getiremeyecek hâlde bulunursa; yüksek görevli mahkeme, davanın
başka yerde bulunan aynı derecede bir mahkemeye nakline karar verir.
+
Kovuşturmanın görevli ve yetkili olan mahkemenin bulunduğu yerde yapılması kamu
güvenliği için tehlikeli olursa, davanın naklini Adalet Bakanı Yargıtaydan
ister.
+
Mahkeme, fiili sebepler veya güvenlik gerekçesiyle duruşmanın il sınırları
içinde başka bir yerde yapılmasına karar verebilir. Bu karara karşı itiraz yolu
açıktır.
. *İstinabe*: Hakim bir takım işlemler için yetkisini bir başka hakime sadece o
işlemle sınırlı ve geçici olarak nakledebilir. İstinabe bir coğrafi bölgedeki
makamın başka bir coğrafi bölgede yapması gereken işlemi kendisiyle aynı
seviyede olan ve işlemin olduğu bölgedeki yetkili hakim veya savcılığa o işleri
yapması için yazısıdır. *Makamlar birbirine denk olmalıdır.*

==== YETKİ UYUŞMAZLIĞI

Birkaç hâkim veya mahkeme arasında olumlu veya olumsuz yetki uyuşmazlığı
çıkarsa, ortak yüksek görevli mahkeme, yetkili hâkim veya mahkemeyi belirler.

IMPORTANT: Soruşturma aşamasındaki bir dosya kendisine yetkisizlik ile gelen
cumhuriyet savcılığı kendisinin de yetkisiz olduğunu düşünüyor olsa bile
dosyayı geri gönderemez. Dosyayı bağlı bulunduğu ağır ceza mahkemesi bölgesine
en yakın yer ağır ceza bölgesindeki ağır ceza mahkemesine uyuşmazlığın çözümü
için göndermek zorundadır.

==== YETKİSİZLİK İDDİASI

Sanık, yetkisizlik iddiasını, ilk derece mahkemelerinde duruşmada sorgusundan,
bölge adliye mahkemelerinde incelemenin başlamasından ve duruşmalı işlerde
inceleme raporunun okunmasından önce bildirir.

Yetkisizlik iddiasına ilişkin karar, ilk derece mahkemelerinde sanığın
sorgusundan önce, bölge adliye mahkemelerinde duruşmasız işlerde incelemenin
hemen başlangıcında, duruşmalı işlerde inceleme raporu okunmadan önce verilir.
Bu aşamalardan sonra yetkisizlik iddiasında bulunulamayacağı gibi mahkemeler de
bu hususta re'sen karar veremez.

Yetkisizlik kararlarına karşı itiraz yoluna gidilebilir.

==== YETKİLİ OLMAYAN MAHKEMENİN İŞLEMLERİ

Yetkili olmayan hâkim veya mahkemece yapılan işlemler, sadece yetkisizlik
nedeniyle hükümsüz sayılmaz. Bir hâkim veya mahkeme, yetkili olmasa bile,
gecikmesinde sakınca bulunan hâllerde, yargı çevresi içerisinde gerekli
işlemleri yapar.

=== KİŞİ BAKIMINDAN YETKİ

Bazı kişiler taşıdıkları sıfatlardan ötürü kendilerine özel birtakım kurallarla
soruşturulup kovuşturulurlar.

=== GÖREV İTİBARİYLE YETKİ

Görev itibariyle yetkide bir mahkemenin görev veya yetki alanında yapılacak işi
yapması için yetkinin devredilmesi söz konusudur. Mahkeme heyeti yapılacak iş
için hakimlerden birini *naip hakim* olarak yetkilendirir ve naip hakim işlemi
yaparken *heyet adına* hareket eder. Her işlem için ayrıca yetkilendirme gerekir.

== ESKİ HALE GETİRME

Kişi belirli bir süre içinde yapılması gereken işlem için süreyi kusuru olmadan
kaçırmışsa eski hale getirme imkanından yararlanabilir.

Eski haline getirme talebi süre kaçırılmasaydı işlemi hangi mercii yapacaksa o
merciye dilekçe ile başvuru şeklinde iletilir. Engelin kalkmasından itibaren 7
gün içinde başvurunun yapılması gerekir.

Kişi başvurusunda engel olmasaydı yapacağı işlemi de sunmalıdır.

Eski hale getirme talebi kabul edildiği takdirde kesin iken reddedildiği
takdirde itiraza konu edilebilir.

== KORUMA TEDBİRLERİ

Kural olarak koruma tedbirlerine hükmedecek makam Sulh Ceza Hakimidir. İstisnai
olarak Cumhuriyet Savcısı gecikmesinde sakınca bulunan hallerin varlığı halinde
hakim kararı olmadan da koruma tedbirlerine başvurabilir. Hatta Cumhuriyet
Savcısına ulaşılamıyorsa kolluk amiri de bir kısım koruma tedbirlerine
başvurabilir.

Koruma tedbirlerinin ortak özellikleri:

* Mahkeme hükmünden önce bir anayasal özgürlük sınırlanır.
* Koruma tedbiri ile kısıtlanan özgürlük ile ulaşılmak istenen amaç arasında
orantı olmalıdır.
* Koruma tedbirleri geçicidir.
* Tüm koruma tedbirleri kanuna dayanmalıdır.
* Verilen koruma tedbiri kararı en azından görünüşte bir haklılığa sahip
olmalıdır.
* Koruma tedbirleri uygulanması zorunlu hallerde uygulanır.
* Koruma tedbirlerinin uygulanması için kural olarak hakim kararı gerekir.
