:toc:
:toc-title: CMK
:icons: font

== GENEL SÜREÇ

Suç şüphesiyle başlayıp iddianamenin kabulüyle biten evreye *soruşturma* denir.

Soruşturma evresine başlanabilmesi için mutlaka bir şüpheliye ihtiyaç yoktur.
Soruşturma evresinde suç şüphesi altında olan birisi varsa buna *şüpheli*,
şüpheliyi temsil eden avukata da *müdafi* adı verilir. Soruşturma evresi
bakımından asıl yetkili **Cumhuriyet Savcısı**dır. Dolayısıyla bütün işlemler
cumhuriyet savcısının talimatıyla gerçekleşir. Bu süreçte hakim kararına
ihtiyaç duyulması halinde karar verecek olan hakim CMK 162 uyarınca **Sulh Ceza
Hakimi**dir.

Soruşturma aşamasında suçun oluşup oluşmadığına, farklı şüphelilerin olup
olmadığına yönelik araştırma yapılır ve bu araştırmalar neticesinde şüphe belli
bir düzeye gelince cumhuriyet savcısı bir iddianame düzenler. Bu iddianame
kabul veya reddedilmesi için mahkemeye gönderilir. _İddianamenin kabulüyle,
kamu davası açılmış olur ve kovuşturma evresi başlar._ (CMK 175).

İddianamenin kabulünden olağan kanun yolları evresinin bitmesine (verilen
kararın kesinleşmesine) kadar olan sürece *kovuşturma* evresi denir. Kovuşturma
evresinde şüpheli, *sanık* haline gelir.

Kovuşturma evresi üç ana bölümden oluşur:

. İddianamenin kabulü ile duruşma günü arasındaki duruşma hazırlığı
. Duruşma ve hüküm
. Kanun yolları ve kesinleşme

== NORMLARIN ZAMAN BAKIMINDAN UYGULANMASI

Ceza muhakemesi kuralları yürürlüğe girdikleri tarihten itibaren şüphelinin,
sanığın, suçtan zarar görenin, katılanın veya herhangi bir başka öznenin
durumunu olumlu ya da olumsuz etkilemesine bakılmaksızın *derhal* uygulanırlar
ve hiçbir şekilde geriye yürümezler. Her işlem yapıldığı tarihteki norma göre
hukuka uygunluk hususunda değerlendirmeye tabi tutulur.

== KIYAS SERBESTİSİ

Kanun koyucu bir hukuki soruna ilişkin iradesini açıkça ortaya koymamışsa
hakim, ilk olarak diğer usul kanunlarından, ikinci olarak ana ilkelerle
çatışmamak kaydıyla kanunun içindeki diğer hükümlerden, üçüncü olarak da yine
ana ilkelerle çatışmamak kaydıyla ve gerekçelendirmek koşuluyla normatif
düzlemden bağımsız olarak sorunu çözmek zorundadır.

Ancak bu kıyas serbestisinin iki istisnası vardır:

. *Temel hak ve özgürlüklerle ilgili sınırlayıcı hükümler kıyasa tabi
olamazlar.*
. *İstisnai hükümlerde kıyasa başvurulamaz.*

== MUHAKEME ENGELLERİ

Kanunda bazı müesseseler davanın açılmasını engelleyen bazı müesseseler ise
yargılamanın yapılmasını engelleyen hususlar olarak düzenlenmiştir. Davanın
açılmasını engelleyen koşullara *dava koşulları*, yargılama yapılmasını
engelleyen koşullara *yargılama koşulları* denir.

Dava koşulları sadece davanın açılması noktasında etkili olmaz. Yargılama
aşaması süresince mahkemeler bu koşulları gerçekleşip gerçekleşmediğini
araştırmakla yükümlüdür.

=== ŞİKAYET

Cumhuriyet savcısı, ihbar veya başka bir suretle bir suçun işlendiği izlenimini
veren bir hâli öğrenir öğrenmez kamu davasını açmaya yer olup olmadığına karar
vermek üzere hemen işin gerçeğini araştırmaya başlar.

Takibi şikayete bağlı olmayan suçlar yani re'sen soruşturulan suçlarda her kim
olursa olsun savcılığa, kolluğa, mahkemelere, büyük elçiliklere ve kamu
kurumlarına yapılan bildirimin adı **ihbar**dır. Re'sen soruşturulan suçlarda
bildirimin ne zaman yapıldığının önemi yoktur, dava zamanaşımı süresi dolana
kadar yapılabilir. İhbar veya diğer öğrenme şekilleri re'sen soruşturulan
suçlarda bir dava koşulu değildir.

Takibi şikayete bağlı suçlarda ise *şikayet* bir dava koşuludur. Kanun şikayet
hakkının suçtan zarar görene ait olduğunu belirtmiştir. Korunan hukuki değer
doğrudan birey ile ilişkiliyse suçtan zarar gören mağdurdur. Mülkiyet gibi
müşterek değerler söz konusu ise eşin veya anne ve babanın da suçtan zarar
gören olabileceği kabul edilmektedir.

Birden fazla suçtan zarar gören varsa her kişi diğerlerinden bağımsız olarak
şikayet hakkına sahiptir.

Takibi şikayete bağlı suçlarda kanun şikayet süresini *fiilin ve failin
öğrenilmesinden itibaren altı ay* ile sınırlandırmıştır.

Suça ilişkin ihbar veya şikâyet, Cumhuriyet Başsavcılığına veya kolluk
makamlarına yapılabilir. Valilik veya kaymakamlığa ya da mahkemeye yapılan
ihbar veya şikâyet, ilgili Cumhuriyet Başsavcılığına gönderilir.

Yurt dışında işlenip ülkede takibi gereken suçlar hakkında Türkiye'nin elçilik
ve konsolosluklarına da ihbar veya şikâyette bulunulabilir.

Bir kamu görevinin yürütülmesiyle bağlantılı olarak işlendiği iddia edilen bir
suç nedeniyle, ilgili kurum ve kuruluş idaresine yapılan ihbar veya şikâyet,
gecikmeksizin ilgili Cumhuriyet Başsavcılığına gönderilir.

IMPORTANT: Kamu kurumları kendilerine ulaşan herhangi bir suç bildirimini
savcılığa iletmek zorundadır. Ancak yurt dışında işlenip ülkede takibi gereken
suçlar veya bir kamu görevinin yürütülmesi ile ilgili suçlarda elçilik ve
konsolosluklara veya ilgili kamu kurumuna fiilin ve failin öğrenilmesinden
itibaren altı ay içerisinde yapılacak bildirim süresinde yapılmış kabul
edilecektir. Bunun dışında kalan suçlar bakımından yapılacak bildirim ilgili
kurum tarafından savcılığa ulaştırıldığı tarihte yapılmış sayılacak ve süre
buna göre hesaplanacaktır.

İhbar veya şikâyet yazılı veya tutanağa geçirilmek üzere sözlü olarak
yapılabilir.

Yürütülen soruşturma sonucunda kovuşturma evresine geçildikten sonra suçun
şikâyete bağlı olduğunun anlaşılması halinde; mağdur açıkça şikâyetten
vazgeçmediği takdirde, yargılamaya devam olunur.

Şikayetin konusu takibi şikayete bağlı bir suç oluşturduğu öne sürülen somut
bir fiildir. Dolayısıyla şikayet hakkına sahip olanlardan bir tanesi bu hakkını
kullandığında o suça iştirak eden herkes bakımından dava koşulu sağlanmış olur.
Buna *şikayetin bölünmezliği* veya *şikayetin sirayeti* denir.

Yapılmış bir şikayet hak sahibi olan kişi veya kişiler tarafından o fiille
ilgili hüküm kesinleşinceye kadar geri alınabilir. Şikayetin geri alınması
soruşturmayı takipsizlikle sonuçlandırır, kovuşturma aşamasında ise davanın
düşmesine neden olur. Ancak hüküm kesinleştikten sonra şikayetin geri alınması
kural olarak infaza etki etmez.

Suçtan zarar gören kişi veya kişiler şikayet hakkı doğduktan sonra bu
haklarından vazgeçebilirler. İspat kolaylığı bakımından bu bildirimin savcılık
veya kolluk nezdinde yapılması isabetli olacaktır.

Takibi şikayete bağlı suçlarda şikayetin geri alınması kabul etmeyen sanığı
bağlamaz.

Şikayet geri alındıktan sonra tekrar kullanılamaz.

=== DAVA SÜRELERİ

Kanun koyucu bazı suçlar bakımından fiilin işlenmesinden itibaren davanın
belirli bir süre içerisinde açılmasını zorunlu kılmıştır. Uygulamada çok
rastlanan bir koşul değildir. Örnek için Basın Kanunu 26.

=== İZİN

Anayasa'nın 129. maddesine göre "_Memurlar ve diğer kamu görevlileri hakkında
işledikleri iddia edilen suçlardan ötürü ceza kovuşturması açılması, kanunla
belirlenen istisnalar dışında, kanunun gösterdiği idari merciin iznine
bağlıdır._"

IMPORTANT: İznin konusu suç değil, soruşturmanın konusu olan fiildir.
Soruşturma makamı isnat edilen bir fiilin görev sebebiyle olduğunu belirtmiş ve
izin almışsa süreç içerisinde suç vasfının değişmesi herhangi bir etki
yaratmaz.

İznin istisnası irtikap, rüşvet, basit veya nitelikli zimmet, görevi sırasında
göreviyle alakalı kaçakçılık, resmi ihalede alım satıma fesat karıştırma
suçlarıdır. Bu suçlar söz konusu ise memur veya kamu görevlisinin yargılanması
için izin alınmasına gerek yoktur.

TIP: İznin verilmesine veya verilmemesine ilişkin karar idari bir karardır. Bu
nedenle bu karara karşı çıkma mekanizması da idari yargıdadır. Kanunda da izin
verilmesi halinde şüphelinin izin verilmemesi halinde ise savcı veya suçtan
zarar görenin 10 gün içerisinde bölge adliye mahkemesine itiraz hakkı olduğu
belirtilmiştir.

NOTE: Bkz. 4483 sayılı kanun

=== TALEP

Bazı suçlardan dolayı dava açılması için bir kamu makamının, genellikle Adalet
Bakanlığı'nın talebi gereklidir. Bu durumlarda talep suçun vasfı ne olursa
olsun bir dava koşuludur.

IMPORTANT: Bu başvuru şikayet değildir. Dolayısıyla şikayet ile ilgili hükümler
burada uygulanamaz. Başvuru yapıldıktan sonra geri alınması artık bir dava
koşulu veya engeli değildir.

=== ADALET BAKANI'NIN İZNİ

IMPORTANT: Bu izin ile 4483 sayılı kanunda düzenlenen izin müessesesi aynı
değildir.

Bazı suçlarda, soruşturma veya kovuşturmanın sonucunda bir siyasi etki doğacak
ise davanın açılması Adalet Bakanı'nın iznine bağlıdır. Bu konuda tipik
örnekler Cumhurbaşkanı'na Hakaret, Anayasal Organları ve Türklüğü Tahkir
suçlarıdır.

=== DERDEST DAVA BULUNMASI

Aynı fiil ve aynı kişi ile ilgili daha önce açılmış ve sonuçlandırılmış veya
hali hazırda görülmekte olan bir dava var ise bu bir dava engeli teşkil eder.
Bu durumda soruşturma aşamasında kovuşturmaya yer olmadığına karar
verilmelidir. Kovuşturma aşamasında ise *davanın reddi* kararı verilmelidir.

TIP: Ceza muhakemesinde açılmış bir davanın reddine karar verilebilen tek durum
budur.

=== ÖN ÖDEME

Ön ödemeye tabi suçlar, sadece para cezasını gerektiren veya cezanın üst sınırı
6 ayı geçmeyen suçlardır. Cumhuriyet savcısı ön ödemeye tabi suçlar için
soruşturma sonucunda dava açmaya yeter bir şüpheye ulaşırsa şüpheliye öngörülen
cezanın asgari bir miktarını ödemesini teklif eder. Şüpheli ön ödeme talebini
kabul eder ve ödeme yaparsa soruşturma, kovuşturmaya yer olmadığına dair bir
kararla sonuçlandırılır.

Ön ödemeye tabi bir suç bu yola başvurulmaksızın dava konusu edildiğinde bu
öncelikle bir iddianamenin iadesi sebebidir. Eğer kovuşturma aşamasında suç
vasfı değişip ön ödemeye tabi bir suç haline gelirse mahkeme ön ödemeyi teklif
eder ve ödeme yapıldığı takdirde davanın düşmesine karar verir. Dolayısıyla ön
ödemeye tabi suçlarda ön ödemenin teklif edilip başarısızlıkla sonuçlanması bir
dava koşuludur.

=== UZLAŞTIRMA

Uzlaştırmaya tabi bir suç söz konusu ise uzlaşmanın başarısızlık sonuçlanması
bir dava koşuludur.

=== SANIĞIN HAZIR BULUNMAMASI

Kanunun ayrık tuttuğu hâller saklı kalmak üzere, hazır bulunmayan sanık
hakkında duruşma yapılmaz. Gelmemesinin geçerli nedeni olmayan sanığın zorla
getirilmesine karar verilir.

==== İSTİSNALAR

===== MAHKUMİYET DIŞI KARAR

Sanık hakkında, toplanan delillere göre mahkûmiyet dışında bir karar verilmesi
gerektiği kanısına varılırsa, sorgusu yapılmamış olsa da dava yokluğunda
bitirilebilir.

===== GAİPLİK

Bulunduğu yer bilinmeyen veya yurt dışında bulunup da yetkili mahkeme önüne
getirilemeyen veya getirilmesi uygun bulunmayan sanık gaip sayılır.

Gaip hakkında duruşma açılmaz; mahkeme, delillerin ele geçirilmesi veya
korunması amacıyla gerekli işlemleri yapar.

Bu işlemler naip hâkim veya istinabe olunan mahkeme aracılığıyla da
yapılabilir.

Bu işlemler sırasında sanığın müdafii veya kanunî temsilcisi veya eşi hazır
bulunabilir. Gerektiğinde, mahkemece barodan bir müdafi görevlendirilmesi
istenir.

Adresi bilinmeyen gaibe, mahkeme önüne gelmesi veya adresini bildirmesi
hususları uygun bir iletişim aracıyla ihtar edilir.

Mahkeme, gaip olan sanık hakkında duruşmaya gelmesi hâlinde tutuklanmayacağı
hususunda bir güvence belgesi verebilir ve bu güvence koşullara bağlanabilir.

Sanık, hapis cezası ile mahkûm olur veya kaçmak hazırlığında bulunur veya
güvence belgesinin bağlı olduğu koşullara uymazsa belgenin hükmü kalmaz.

===== SANIĞIN YOKLUĞU

* *Sanığın mahkemeden uzaklaşması:* Mahkemeye gelen sanığın duruşmanın devamı
süresince hazır bulunması sağlanır ve savuşmasının önüne geçmek için mahkeme
gereken tedbirleri alır. Sanık savuşur veya ara vermeyi izleyen oturuma
gelmezse, önceden sorguya çekilmiş ve artık hazır bulunmasına mahkemece gerek
görülmezse, dava yokluğunda bitirilebilir.
* *Sanığın yokluğunda duruşma:* Suç, yalnız veya birlikte adlî para cezasını
veya müsadereyi gerektirmekte ise; sanık gelmese bile duruşma yapılabilir. Bu
gibi hâllerde sanığa gönderilecek davetiyede gelmese de duruşmanın yapılacağı
yazılır.
* *Sanığın duruşmadan bağışık tutulması:* Mahkemece sorgusu yapılmış olan sanık
veya bu hususta sanık tarafından yetkili kılındığı hâllerde müdafii isterse,
mahkeme sanığı duruşmada hazır bulunmaktan bağışık tutabilir.
* *Sorgu sırasında sanığın mahkeme salonundan çıkarılabilmesi:* Sanığın yüzüne
karşı suç ortaklarından birinin veya bir tanığın gerçeği söylemeyeceğinden
endişe edilirse, mahkeme, sorgu ve dinleme sırasında o sanığın mahkeme
salonundan çıkarılmasına karar verebilir. Sanık tekrar getirildiğinde,
tutanaklar okunur ve gerektiğinde içeriği anlatılır.
* *Sanığın duruşmanın düzenini bozması:* Mahkeme başkanı veya hâkim, duruşmanın
düzenini bozan kişinin, savunma hakkının kullanılmasını engellememek koşuluyla
salondan çıkarılmasını emreder.
* *Sanığın dışarı çıkarılması:* Davranışları nedeniyle, hazır bulunmasının
duruşmanın düzenli olarak yürütülmesini tehlikeye sokacağı anlaşıldığında
sanık, duruşma salonundan çıkarılır. Mahkeme, sanığın duruşmada hazır
bulunmasını dosyanın durumuna göre savunması bakımından zorunlu görmezse,
oturumu yokluğunda sürdürür ve bitirir. Ancak, sanığın müdafii yoksa, mahkeme
barodan bir müdafi görevlendirilmesini ister. Oturuma yeniden alınmasına karar
verilen sanığa, yokluğunda yapılan işlemler açıklanır.

===== KAÇAKLIK

Hakkındaki soruşturmanın veya kovuşturmanın sonuçsuz kalmasını sağlamak
amacıyla yurt içinde saklanan veya yabancı ülkede bulunan ve bu nedenle
Cumhuriyet savcısı veya mahkeme tarafından kendisine ulaşılamayan kişiye kaçak
denir.

Hakkında, 248 inci maddenin ikinci fıkrasında belirtilen suçlardan dolayı
soruşturma veya kovuşturma başlatılmış olan şüpheli veya sanığın, yetkili
Cumhuriyet savcısı veya mahkemece usulüne göre yapılan tebligata uymamasından
dolayı verilen zorla getirilme kararı da yerine getirilemez ise, Cumhuriyet
savcısı veya mahkeme;

.. Çağrının bir gazete ile şüpheli veya sanığın bilinen konutunun kapısına
asılmak suretiyle ilânına karar verir; yapılacak ilânlarda, onbeş gün içinde
gelmediği takdirde 248 inci maddede gösterilen tedbirlere hükmedilebileceğini
ayrıca açıklar,
.. Bu işlemlerin yerine getirildiğinin bir tutanak ile saptanmasından itibaren
onbeş gün içinde başvurmayan şüpheli veya sanığın kaçak olduğuna karar verir.

Kaçak sanık hakkında kovuşturma yapılabilir. Ancak, daha önce sorgusu
yapılmamış ise, mahkûmiyet kararı verilemez.

Duruşma yapılan hâllerde kaçak sanığın müdafii yoksa, mahkeme barodan bir
avukat görevlendirilmesini ister.

Kaçağın Cumhuriyet savcısına başvurmasını veya duruşmaya gelmesini sağlamak
amacıyla Türkiye'de bulunan mallarına, hak ve alacaklarına amaçla orantılı
olarak Cumhuriyet savcısının istemi üzerine sulh ceza hâkimi veya mahkeme
kararıyla elkonulabilir ve gerektiğinde idaresi için kayyım atanır. Elkoyma ve
kayyım atama kararı müdafiine bildirilir.

Yukarıdaki tedbirler;

.. Türk Ceza Kanununda tanımlanan;

. Soykırım ve insanlığa karşı suçlar (madde 76, 77, 78),
. Göçmen kaçakçılığı ve insan ticareti (madde 79, 80),
. Hırsızlık (madde 141, 142),
. Yağma (madde 148, 149),
. Güveni kötüye kullanma (madde 155),
. Dolandırıcılık (madde 157, 158),
. Hileli iflas (madde 161),
. Uyuşturucu veya uyarıcı madde imal ve ticareti (madde 188),
. Parada sahtecilik (madde 197),
. Suç işlemek amacıyla örgüt kurma (madde 220),
. Zimmet (madde 247),
. İrtikâp (madde 250),
. Rüşvet (madde 252),
. İhaleye fesat karıştırma (madde 235),
. Edimin ifasına fesat karıştırma (madde 236),
. Devletin Güvenliğine Karşı Suçlar (madde 302, 303, 304, 305, 306, 307, 308),
. Anayasal Düzene ve Bu Düzenin İşleyişine Karşı Suçlar (madde 309, 310, 311,
312, 313),
. Silahlı örgüt (madde 314) veya bu örgütlere silah sağlama (madde 315),
. Devlet Sırlarına Karşı Suçlar ve Casusluk (madde 328, 329, 330, 331, 333,
334, 335, 336, 337) suçları,

.. Ateşli Silahlar ve Bıçaklar ile Diğer Aletler Hakkında Kanunda tanımlanan
silah kaçakçılığı (madde 12) suçları,
.. Bankalar Kanununun 22 nci maddesinin (3) ve (4) numaralı fıkralarında
tanımlanan zimmet suçu,
.. Kaçakçılıkla Mücadele Kanununda tanımlanan ve hapis cezasını gerektiren
suçlar,
.. Kültür ve Tabiat Varlıklarını Koruma Kanununun 68 ve 74 üncü maddelerinde
tanımlanan suçlar,

Hakkında uygulanır.

Elkonulan mal, hak ve alacakların korunmasında, elkoymaya ilişkin hükümler
uygulanır. Tedbirlere ilişkin kararların özetinin bir gazetede ilânına sulh
ceza hâkimince veya mahkemece karar verilebilir.


Kaçak yakalandığında veya kendiliğinden gelerek teslim olduğunda elkoymanın
kaldırılmasına karar verilir.

Kaçak hakkında 100 üncü ve sonraki maddeler gereğince, sulh ceza hâkimi veya
mahkeme tarafından yokluğunda tutuklama kararı verilebilir.

Sulh ceza hâkimi veya mahkeme elkoymaya karar verdiğinde, kaçağın yasal olarak
bakmakla yükümlü bulunduğu yakınlarının alınan tedbirler nedeniyle yoksulluğa
düşebileceklerini saptarsa, bunların geçimlerini sağlamak üzere, elkonulan mal
varlığından sosyal durumları ile orantılı miktarda yardımda bulunulması
konusunda kayyıma izin verir.

NOTE: 246 ncı madde hükmü kaçaklar hakkında da uygulanır.

TIP: Bu kararlara karşı itiraz edilebilir.

== CEZA MUHAKEMESİNİN ÖZNELERİ

=== HAKİM

==== HAKİMİN YASAKLILIK HALLERİ

Hâkim;

.. Suçtan kendisi zarar görmüşse,
.. Sonradan kalksa bile şüpheli, sanık veya mağdur ile aralarında evlilik,
vesayet veya kayyımlık ilişkisi bulunmuşsa,
.. Şüpheli, sanık veya mağdurun kan veya kayın hısımlığından üstsoy veya
altsoyundan biri ise,
.. Şüpheli, sanık veya mağdur ile aralarında evlât edinme bağlantısı varsa,
.. Şüpheli, sanık veya mağdur ile aralarında üçüncü derece dahil kan hısımlığı
varsa,
.. Evlilik sona ermiş olsa bile, şüpheli, sanık veya mağdur ile aralarında
ikinci derece dahil kayın hısımlığı varsa,
.. Aynı davada Cumhuriyet savcılığı, adlî kolluk görevi, şüpheli veya sanık
müdafiliği veya mağdur vekilliği yapmışsa,
.. Aynı davada tanık veya bilirkişi sıfatıyla dinlenmişse,

hâkimlik görevini yapamaz.

==== HAKİMİN YARGILAMAYA KATILAMAYACAĞI HALLER

Bir karar veya hükme katılan hâkim, yüksek görevli mahkemece bu hükme ilişkin
olarak verilecek karar veya hükme katılamaz.

Aynı işte soruşturma evresinde görev yapmış bulunan hâkim, kovuşturma evresinde
görev yapamaz.

CAUTION: Suçüstü hâli ile gecikmesinde sakınca bulunan hâllerde, Cumhuriyet
savcısına erişilemiyorsa veya olay genişliği itibarıyla Cumhuriyet savcısının
iş gücünü aşıyorsa, sulh ceza hâkimi de bütün soruşturma işlemlerini yapabilir.
Ancak bu durumda soruşturma evresinde görev yapmış hakim kovuşturma evresinde
görev alamaz. Diğer durumlar için yukarıdaki hüküm uygulanmaz.

Yargılamanın yenilenmesi halinde, önceki yargılamada görev yapan hâkim, aynı
işte görev alamaz.

==== HAKİMİN REDDİ

Hâkimin davaya bakamayacağı hâllerde reddi istenebileceği gibi, tarafsızlığını
şüpheye düşürecek diğer sebeplerden dolayı da reddi istenebilir.

TIP: Hakimin yargılama sürecinde dosya ile ilgili düşüncesini ortaya koyan
herhangi bir ifade hakimin reddi sebebidir. Ancak somut olaya benzer bilimsel
veya siyasi görüşler hakimin reddi sebebi oluşturmaz.

Cumhuriyet savcısı; şüpheli, sanık veya bunların müdafii; katılan veya vekili,
hâkimin reddi isteminde bulunabilirler.

Tarafsızlığını şüpheye düşürecek sebeplerden dolayı bir hâkimin reddi, ilk
derece mahkemelerinde sanığın sorgusu başlayıncaya; duruşmalı işlerde bölge
adliye mahkemelerinde inceleme raporu ve Yargıtayda görevlendirilen üye veya
tetkik hâkimi tarafından yazılmış olan rapor üyelere açıklanıncaya kadar
istenebilir. Diğer hâllerde, inceleme başlayıncaya kadar hâkimin reddi
istenebilir.

Sonradan ortaya çıkan veya öğrenilen sebeplerle duruşma veya inceleme bitinceye
kadar da hâkimin reddi istenebilir. Ancak bu istemin, ret sebebinin
öğrenilmesinden itibaren yedi gün içinde yapılması şarttır.

Hâkimin reddi, mensup olduğu mahkemeye verilecek dilekçeyle veya bu hususta
zabıt kâtibine bir tutanak düzenlenmesi için başvurulması suretiyle yapılır.

Ret isteminde bulunan, öğrendiği ret sebeplerinin tümünü bir defada açıklamak
ve süresi içinde olguları ile birlikte ortaya koymakla yükümlüdür.

Reddi istenen hâkim, ret sebepleri hakkındaki görüşlerini yazılı olarak
bildirir.

Hâkimin reddi istemine mensup olduğu mahkemece karar verilir. Ancak, reddi
istenen hâkim müzakereye katılamaz. Bu nedenle mahkeme teşekkül edemezse bu
hususta karar verilmesi;

.. Reddi istenen hâkim asliye ceza mahkemesine mensup ise bu mahkemenin yargı
çevresi içerisinde bulunan ağır ceza mahkemesine,
.. Reddi istenen hâkim ağır ceza mahkemesine mensup ise o yerde ağır ceza
mahkemesinin birden fazla dairesinin bulunması hâlinde, numara olarak kendisini
izleyen daireye, son numaralı daire için (1) numaralı daireye; o yerde ağır
ceza mahkemesinin tek dairesi bulunması hâlinde ise, en yakın ağır ceza
mahkemesine,

Aittir.

Ret istemi sulh ceza hâkimine karşı ise, yargı çevresi içinde bulunduğu asliye
ceza mahkemesi ve tek hâkime karşı ise, yargı çevresi içerisinde bulunan ağır
ceza mahkemesi karar verir.

Ret isteminin kabulü halinde, davaya bakmakla bir başka hâkim veya mahkeme
görevlendirilir.

Ret isteminin kabulüne ilişkin kararlar kesindir; kabul edilmemesine ilişkin
kararlara karşı itiraz yoluna gidilebilir. İtiraz üzerine verilen ret kararı
hükümle birlikte incelenir.

Reddi istenen hâkim, ret hakkında bir karar verilinceye kadar yalnız
gecikmesinde sakınca olan işlemleri yapar.

Ancak, hâkimin oturum sırasında reddedilmesi hâlinde, bu konuda bir karar
verilebilmesi için oturuma ara vermek gerekse bile ara vermeksizin devam
olunur. Şu kadar ki, 216 ncı madde uyarınca tarafların iddia ve sözlerinin
dinlenilmesine geçilemez ve ret konusunda bir karar verilmeden reddedilen hâkim
tarafından veya onun katılımıyla bir sonraki oturuma başlanamaz.

Ret isteminin kabulüne karar verildiğinde, gecikmesinde sakınca bulunan hâl
nedeniyle yapılmış işlemler dışında, duruşma tekrarlanır.

Hâkim, yasaklılığını gerektiren sebeplere dayanarak çekindiğinde; merci, bir
başka hâkimi veya mahkemeyi davaya bakmakla görevlendirir.

Hâkim, tarafsızlığını şüpheye düşürecek sebepler ileri sürerek çekindiğinde,
merci çekinmenin uygun olup olmadığına karar verir. Çekinmenin uygun bulunması
halinde, davaya bakmakla bir başka hâkim veya mahkeme görevlendirilir.

Mahkeme, kovuşturma evresinde ileri sürülen hâkimin reddi istemini aşağıdaki
durumlarda geri çevirir:

.. Ret istemi süresinde yapılmamışsa.
.. Ret sebebi ve delili gösterilmemişse.
.. Ret isteminin duruşmayı uzatmak amacı ile yapıldığı açıkça anlaşılıyorsa.

Bu hâllerde ret istemi, toplu mahkemelerde reddedilen hâkimin müzakereye
katılmasıyla, tek hâkimli mahkemelerde de reddedilen hâkimin kendisi tarafından
geri çevrilir. Bu konudaki kararlara karşı itiraz yoluna başvurulabilir.

=== SAVCI

Cumhuriyet savcılarının görevi kamu adına iddiada bulunmak, iddia faaliyetini
gerçekleştirmektir.

İddia makamı sadece kişinin suçlanması, ceza alması için uğraşan bir makam
değildir. *Savcı, şüpheli veya sanığın lehine bir delil gördüğü zaman bunu da
dosyaya koymalıdır.

TIP: Savcının reddine ilişkin bir düzenleme hukukumuzda yer almamaktadır.
Hakimin reddi sebepleri sınırlayıcı bir hüküm olduğundan kıyas serbestisinin
istisnasını oluşturur ve savcının reddi için uygulanamaz.

Cumhuriyet savcıları il merkezinde ve gerektiği takdirde ilçelerd kurulan
Cumhuriyet Başsavcılıkları şeklinde örgütlenir. Cumhuriyet Başsavcılıklarında
bir Cumhuriyet Başsavcısı ve yeterli sayıda Cumhuriyet savcısı bulunur.
Cumhuriyet Başsavcısı görevini altındaki Cumhuriyet savcıları eliyle ifa eder.
Cumhuriyet savcıları görevlerini ifa ederken bağlı bulundukları Cumhuriyet
Başsavcısı adına hareket ederler.

NOTE: Cumhuriyet savcıları arasındaki ilişki işbölümü ilişkisidir.

==== CUMHURİYET SAVCILARININ GÖREVLERİ

. *Suçun işlendiğine dair bildirimin araştırılması*: Cumhuriyet savcısı bir suç
şüphesi bildirimi aldıktan sonra fiile ilişkin birtakım delilleri toplayıp,
süpheli hakkındaki şüpheyi belirli bir seviyeye getirdikten sonra iddianameyi
düzenler.
+
NOTE: Ağustos 2017'ye kadar Cumhuriyet savcıları kendilerene gelen tüm suç
bildirimlerini değerlendirerek soruşturma açmak zorundaydı. Ancak son yapılan
değişiklik ile gelen suç bildirimi soyut veya yalan olduğu ilk bakışta
anlaşılır nitelikte ise soruşturma açma zorunluluğu kaldırıldı.
+
IMPORTANT: Cumhuriyet savcısının *dava açma yetkisi yoktur*. Kamu davasını
açacak olan makam iddianameyi kabul eden görevli ve yetkili mahkemedir.
. *Kamu davası açıldıktan sonra davanın takip edilmesi*: Cumhuriyet savcısı
yargılamayı baştan sona takip etmek zorundadır. Burada delilleri ileri sürmek,
mütalaa vermek gibi birtakım görevleri söz konusudur. Yargılamanın sonunda
karara karşı kanun yoluna başvurma yetkisi vardır.
+
NOTE: Bunlar Ağır Ceza mahkemeleri için geçerlidir. 2020 yılına kadar Asliye
Ceza mahkemelerinde Cumhuriyet savcıları yer almayacaktır.
. *Koruma tedbirlerine başvurma*: Kural olarak şüpheli veya sanık hakkında
koruma tedbirine başvurmak için hakim kararı gerekir. Ancak gecikmesinde
sakınca bulunan hallerde Cumhuriyet savcıları koruma tedbirlerine karar
verebilir.
. *Cezanın infazını takip etme*
. *Kanunun verdiği diğer görevleri yerine getirme*

==== ADLİ KOLLUK

Polis, kamu düzenini koruyan ve esas amacı suçun işlenmesi önlemek olan meslek
grubudur. Ancak Cumhuriyet savcısının polisten beklentisi işlenmiş olan bir
fiil sonucunda ortaya çıkan kamu düzeni bozukluğuna yönelik birtakım delillerin
bulunup kişilere ulaşılmasıdır.

Kolluk valilere, oradan da İçişleri Bakanlığı'na bağlıdır. Bütün atamalar,
maaşlar İçişleri Bakanlığı tarafından organize edilmektedir. Ancak Cumhuriyet
savcısı da her yılın sonunda adli kolluk hakkında bir rapor hazırlayarak mülki
amire gönderir.

Adli kolluk personeli görevi sırasında Cumhuriyet savcısı ve adli kolluk amiri
dışında kimseden emir almaz ve kimseye de görevi hakkında bilgi vermemelidir.
Soruşturma aşamasında kural olarak tek yetkili Cumhuriyet savcısıdır.
Cumhuriyet savcısının emri olmaksızın adli kolluk işlem yapamaz.

TIP: Son çıkan bir KHK ile kolluğa Cumhuriyet savcısına haber vermeden gözaltı
yapabilme yetkisi verilmiştir.

Cumhuriyet savcısının adli kolluğa her işlem için ayrı ayrı emir vermesi
gerekir. Kolluğa genel bir yetki verilemez. Adli kolluğa verilecek emir kural
olarak yazılı olmalıdır. Ancak gecikmesinde sakınca olan hallerde emir önce
sözlü sonra yazılı verilebilir.

===== KOLLUĞUN İŞLEDİĞİ SUÇLAR

Kolluk mensubu kişilerin işledikleri suçlar için önemli olan fiil ile görev
arasında bağlantı olup olmadığıdır.

Fiil ile görev arasında bağlantı olmadığı hallerde suçu normal bir vatandaş
işlemiş gibi sorumluluk doğar.

Görev ile fiil arasında bağlantı varsa görev bakımından amirin kim olduğu
sorusu gündeme gelir.

Kolluğun önleyici görevi sırasında bir suç işlenmişse soruşturma başlatılması
için mülki amirden izin alınacaktır. *Cumhuriyet savcısı nezdinde bir soruşturma
yürütülürken adli kolluk görevi sırasında suç işlenmişse Cumhuriyet savcısı
herhangi bir izne tabi olmadan soruşturma başlatabilecektir.*

NOTE: Kolluğun işlediği suç zimmet, rüşvet, irtikap gibi izin alınmasına gerek
olmayan suçlardan biri ise amirin kim olduğuna bakılmaksızın izinsiz soruşturma
başlatılabilir.

=== SULH CEZA HAKİMİ

Soruşturma aşamasında hakim kararı gereken işlemlerde kararı verecek olan Sulh
Ceza hakimidir.

Ayrıca Sulh Ceza hakimi, Cumhuriyet savcısına ulaşılamadığı veya Cumhuriyet
savcısının iş yükünden dolayı işlem yapamadığı hallerde Cumhuriyet savcısı gibi
hareket edebilir.

=== MAĞDUR, ZARAR GÖREN, MALEN SORUMLU VE KATILAN

*Mağdur*, bir suçta suçun maddi unsurlarına maruz kalan kimsedir. Mağdur ile
*suçtan zarar gören* aynı kişi olmak zorunda değildir.

Suçtan zarar gören;

. Sağ bir kişi olmalıdır.
. Dava ehliyetine sahip olmalıdır.
. Gerçek veya tüzel kişi olabilir.

Suçtan zarar gören veya mağdur, katılan sıfatıyla yargılamaya katılabilecektir.
Katılan yargılamanın bir tarafı olur ve birtakım hak ve yükümlülüklere sahip
olur.

Mağdur veya suçtan zarar gören olmak katılan olmak için yeterli değildir. Bu
kişiler ayrıca **katılma talebi**nde bulunmalıdır.

IMPORTANT: Kanun yoluna başvurmak için katılma talebinin var olması yeterlidir.

*Malen sorumlu*, yargılamadaki sonuca göre bir kimse suçlu olarak kabul
edildiğinde ekonomik olarak sorumluluğu doğacak kimsedir. Malen sorumlu da
katılma talebinde bulunabilir.

Katılma talebinin kabul edilmesinden sonra katılan bakımından dava bir yan dava
şeklinde yürüyecektir. Bu yan dava tamamen ana davaya bağlıdır.

NOTE: Yargıtay, re'sen kovuşturulacak suçlar bakımından kişinin katılan
olabilmesi için bir şart aramaktadır. Suçtan zarar gören veya mağdur olarak
olayı mahkemeye anlatırken sanığın cezalandırılması istendiği açıkça söylenmez
ise Yargıtay'a göre artık katılan talebinde bulunulamaz.

IMPORTANT: Soruşturma aşamasında katılma olmaz. Katılan olabilmek için
soruşturmanın kovuşturma aşamasına geçmiş olması ve ilk derece mahkemesinin
kararını vermesine kadar katılma talebinde bulunulması gerekir.

=== ŞÜPHELİ VE SANIK

Kişi *soruşturma aşamasındayken şüpheli*, *kovuşturma aşamasında sanıktır*.

Bir kişinin suç işlediğine dair ihbarın Cumhuriyet savcılığına iletilmiş olması
o kişiyi şüpheli hale getirmez. Şüpheli sıfatının kazanılması için o kişi
hakkında soruşturma başlatılması gerekir.

Soruşturma açılabilmesi için şüphelinin kimliğinin belli olması şart değildir.

[TIP]
====
Doktrinde iddianemede şüphelinin belli olması gerekip gerekmediği tartışma
konusudur.

Bir görüşe göre kişinin kimliğinin bilinmesine gerek yoktur. Kişinin eşkalinin
belirlenmesi ve ona geçici bir isim vermek suretiyle iddianame düzenlenebilir.

Kürsüye göre ise iddianamenin düzenlenebilmesi için şüphelinin kimliğinin
belirli olması gerekir.
====

==== ŞÜPHELİ VE SANIĞIN HAKLARI

. *Savunma hakkı*: En tipik örnek olarak soruşturma aşamasında şüphelinin
ifadesini almayan Cumhuriyet savcısı bu kişi hakkında iddianeme düzenleyemez.
. *Susma hakkı*: Şüpheli veya sanık dava veya soruşturma konusu fiil ile ilgili
olarak bir şey söylemek zorunda değildir. Bir şey söylenmemiş olması ikrar
anlamına gelmez.
+
TIP: Kişi kimliğinin tespitine ilişkin durumlarda susma hakkını kullanamaz.
. *Kendisini ve yakınlarını suçlamama hakkı*
. *Soru sorma hakkı*
. *Tercümandan yararlanma hakkı*
. *Delil toplama ve ibraz etme hakkı*
. *Delillerin toplanmasını isteme hakkı*
. *Duruşmada hazır bulunma hakkı*: Mahkemede hazır bulunmak hak olduğu kadar
yükümlülüktür. Sanık çağrıldığı halde gelmezse zorla getirtilebilir. Kişi hazır
değilse ve istisnalar da söz konusu değilse yargılamaya devam edilemez.
. *Yakalandığını veya gözaltına alındığını yakınlarına bildirme hakkı*
. *Müdafii tayin hakkı*: Kişi müdafii olmadan kollukta ifade verir ancak
mahkemede bu ifadesini kabul etmez ise ifade geçersiz olur. Kanun koyucu bazı
suçlar bakımından müdafiden yararlanmayı zorunlu kılmıştır.
. *Yakalanma ve gözaltı işlemlerine veya gözaltı süresinin uzatılmasına ilişkin
Cumhuriyet savcısının emirlerine karşı Sulh Ceza Hakimliğine başvurma hakkı*

=== MÜDAFİ

Müdafi, şüpheli veya sanığın avukatıdır. Müdafilikte temsilden ziyade
yardımcılık ilişkisi vardır. Sanık veya şüpheli ile müdafi arasında vekalet
ilişkisinin olmasına gerek yoktur. Müdafi ile sanık birbirinden ayrı iki
öznedir.

Müdafi ile sanık arasında vekalet ilişkisi olmasa da müdafi sanığın iradesi ile
sınırlıdır. Sanık istediği zaman müdafiyi görevden alabilir.

AİHS, sanık veya şüphelinin müdafiden yararlanması bakımından üç ilke
belirlemiştir:

. Kişiye kendisini bizzat savunma hakkı tanınmalıdır.
. Kişiye müdafiden yararlanma hakkı tanınmalıdır.
. Kişi müdafiden yararlanmak için gerekli olan mali güce sahip değilse
müdafi devlet tarafından atanmalıdır.

Kişi müdafisini istediği şekilde seçebilir. Birden fazla müdafiye de sahip
olabilir. Bunun iki istisnası vardır:

. Soruşturma aşamasında, ifade verme işlemine en fazla üç müdafi katılabilir.
. Kovuşturma aşamasında, terör suçlarıyla ilgili olan yargılamalarda duruşmaya
en fazla üç müdafi girebilir.

Kural olarak sanık veya şüpheli istediği sürece müdafiden yararlanabilir.
İsterse müdafiden yararlanma hakkını kullanmaz. Zorunlu müdafilik istisnai
durumdur.

Şüpheli veya sanık;

. Çocuksa
. Kendini savunamayacak derecede malulse
. Sağır *ve* dilsiz ise
. Alt sınırı *beş yıldan fazla* hapis cezası öngören bir suçtan yargılanıyorsa

zorunlu müdafilik sistemi geçerlidir.

NOTE: Tutuklanacak veya gözlem altına alınacak kişinin müdafisi yoksa kişinin
iradesine bakılmaksızın müdafi atanacaktır.

Zorunlu müdafilik halinde kişi istediği avukatı seçebilir. Ancak avukat
seçmemesi halinde iradesine bakılmaksızın bir müdafi atanacaktır. Bu
görevlendirme soruşturma aşamasında soruşturmayı yapan makamın, kovuşturma
aşamasında kovuşturmayı yapan makamın talebi üzerine o yerin bağlı olduğu
barodan yapılacaktır.

İhtiyari müdafilikte kollukta müdafi olmadan alınan ifade kural olarak hukuka
uygundur ancak sanık kovuşturma aşamasında ifadesinden dönebilir. Ancak zorunlu
müdafilikte müdafi olmadan verilen ifade hukuka aykırıdır. Bu durumda verilen
ifade hiçbir şekilde delil olarak kullanılamaz.

TIP: Yargılama esnasında suçun niteliği değişir ve zorunlu müdafiliği
gerektiren bir suçun varlığı tespit edilirse daha önce yapılmış işlemler
geçerliliğini korur.

Müdafi, bulunduğu pozisyon itibariyle ancak sanığın lehine olan delilleri
ortaya koymak zorundadır. Mahkeme aleyhe bir delili direkt olarak sorarsa
müdafi susma hakkını kullanabilir ancak yalan söyleme hakkı yoktur.

Müdafi, soruşturma evresinde dosya içeriğini inceleyebilir ve istediği
belgelerin bir örneğini harçsız olarak alabilir.

Müdafiin dosya içeriğini inceleme veya belgelerden örnek alma yetkisi,
soruşturmanın amacını tehlikeye düşürebilecek ise Cumhuriyet savcısının istemi
üzerine hâkim kararıyla kısıtlanabilir. Bu karar ancak CMK 153'teki suçlar söz
konusu ise verilebilir.

Müdafiden yararlanma hakkı aynı zamanda kişilerin müdafi ile serbest bir
şekilde görüşme imkanını da kapsar. 2016 yılında çıkan bir KHK ile buna bir
istina getirilmiştir. Buna göre şüpheli müdafi ile görüşmekten 24 saat ile
sınırlı olmak kaydıyla men edilebilir.

== GÖREV VE YETKİ

=== MADDİ ANLAMDA YETKİ (GÖREV)

Ceza mahkemeleri kanun tarafından ikiye ayrılmıştır: *Asliye ceza* mahkemeleri
ve *ağır ceza* mahkemeleri.

Kural olarak bütün suçlar asliye ceza mahkemelerinde görülür. İstisnai olarak
cezası ağırlaştırılmış müebbet hapis, müebbet hapis veya 10 yıl üstü olan
suçlarda görevli mahkeme ağır ceza mahkemeleridir.

Ayrıca hileli iflas, nitelikli dolandırıcılık, irtikap, resmi belgede
sahtecilik ve Terörle Mücadele Kanunu kapsamındaki suçlarda öngörülen ceza 10
yıldan az olsa da görevli mahkeme ağır ceza mahkemeleridir.

Mahkeme, yargıladığı olay bakımından görevli olup olmadığını kovuşturmanın her
aşamasında denetlemekle yükümlüdür.

TIP: Kanun bir mahkemeye özel yargılama usullerini öngörmüş, yani işbölümüne ek
olarak birtakım özel usullere yer vermişse artık bu ayrıma görev ayrımına
yaklaşır.

Bir mahkeme görevli veya yetkili olup olmadığını ancak kovuşturmaya geçtikten
sonra denetleyebilir. Ancak Yargutay'a göre mahkeme iddianameye baktığında
kendisinin açıkça görevsiz olduğunu görüyorsa iddianemeyi iade edebilir.

==== İSTİSNAEN MADDE BAKIMINDAN YETKİLİ OLMA HALLERİ

. *Görevsizlik kararı verilemeyecek hâl*: Duruşmada suçun hukukî niteliğinin
değiştiğinden bahisle görevsizlik kararı verilerek dosya alt dereceli mahkemeye
gönderilemez.
+
Başka bir ifadeyle, bir ağır ceza mahkemesi duruşma süresince (yoklama ile
başlayıp hükümle son bulan sürece) fiilin hukuki vasfının değiştiği gerekçesi
ile görevsizlik kararı vererek dosyayı asliye ceza mahkemesine gönderemez.
. *Bağlantı*: Bir kişi, birden fazla suçtan sanık olur veya bir suçta her ne
sıfatla olursa olsun birden fazla sanık bulunursa bağlantı var sayılır. Suçun
işlenmesinden sonra suçluyu kayırma, suç delillerini yok etme, gizleme veya
değiştirme fiilleri de bağlantılı suç sayılır.
+
Bir fiil sebebiyle birden fazla kişinin soruşturulduğu veya kovuşturulduğu
durumlarda **objektif bağlantı**dan bahsedilir. Bir kişinin birden fazla fiil
sebebiyle soruşturulduğu veya kovuşturulduğu durumlarda ise **subjektif
bağlantı**dan söz edilir.
+
Bağlantılı suçlardan her biri değişik mahkemelerin görevine giriyorsa, bunlar
hakkında birleştirilmek suretiyle yüksek görevli mahkemede dava açılabilir.
+
Kovuşturma evresinin her aşamasında, bağlantılı ceza davalarının
birleştirilmesine veya ayrılmasına yüksek görevli mahkemece karar verilebilir.
Birleştirilen davalarda, bu davaları gören mahkemenin tâbi olduğu yargılama
usulü uygulanır. İşin esasına girdikten sonra ayrılan davalara aynı mahkemede
devam olunur.
+
*Geniş bağlantı sebebiyle birleştirme*: Mahkeme, bakmakta olduğu birden çok
dava arasında bağlantı görürse, bu bağlantı yukarıda gösterilen türden olmasa
bile, birlikte bakmak ve hükme bağlamak üzere bu davaların birleştirilmesine
karar verebilir.
+
Birleştirme kararının verilebilmesi için yargılamanın amaca uygun biçimde
sonuçlandırılması bakımından bir fayda bulunmalıdır.
+
Birleştirme kararı soruşturma evresinde soruşturmayı yürüten savcılık
tarafından, kovuşturma evresinde ise yüksek görevli mahkeme tarafından
verilecektir.
+
Bağlantının varlığı halinde *birleştirme* yapılabileceği gibi diğer mahkemedeki
uyuşmazlığın çözümü *bekletici sorun* yapılabilir veya mahkeme diğer uyuşmazlık
kendi yargı alanına girmemesine rağmen kendisine yetecek kadar olan kısmı
çözebilir, yani *nisbi muhakeme* yapabilir. Bunlarda hangisinin yapılacağı
kural olarak ceza hakiminin takdirine kalmıştır. Bunun iki istisnası vardır:

.. Anayasa'ya aykırılık iddiası ileri sürüldüğünde ceza hakimi nisbi muhakeme
yapamaz. Bu durumda bekletici mesele yapmak ve söz konusu başvuruyu Anayasa
Mahkemesi'ne göndermek zorundadır.
.. Kovuşturma evresinde mağdur veya sanığın yaşının ceza hükümleri bakımından
tespitiyle ilgili bir sorunla karşılaşılması halinde; mahkeme, ilgili kanunda
belirlenen usule göre bu sorunu çözerek hükmünü verir.

==== GÖREV UYUŞMAZLIĞI

Bir uyuşmazlık hakkında iki mahkemenin de kendini görevli olarak görmesi
*olumlu görev uyuşmazlığı*, görevsiz olarak görmesi ise *olumsuz görev
uyuşmazlığı* olarak adlandırılır.

Olumsuz görev uyuşmazlığının çözümlenmesi bir üst dereceli mahkeme tarafından
yapılır.

==== GÖREVLİ OLMAYAN MAHKEMENİN İŞLEMLERİ

Yenilenmesi mümkün olmayanlar dışında, görevli olmayan hâkim veya mahkemece
yapılan işlemler hükümsüzdür.

NOTE: İddianamenin kabulü kararı yenilenmesi mümkün olmayan bir işlemdir.

=== YER BAKIMINDAN YETKİ

Yer bakımından yetki bir yargılamanın hangi coğrafi bölgedeki mahkemede
yapılacağını belirtir.

Davaya bakmak yetkisi, suçun işlendiği yer mahkemesine aittir.

Teşebbüste son icra hareketinin yapıldığı, kesintisiz suçlarda kesintinin
gerçekleştiği ve zincirleme suçlarda son suçun işlendiği yer mahkemesi
yetkilidir.

Suç, ülkede yayımlanan bir basılı eserle işlenmişse yetki, eserin yayım merkezi
olan yer mahkemesine aittir. Ancak, aynı eserin birden çok yerde basılması
durumunda suç, eserin yayım merkezi dışındaki baskısında meydana gelmişse, bu
suç için eserin basıldığı yer mahkemesi de yetkilidir.

Soruşturulması ve kovuşturulması şikâyete bağlı olan hakaret suçunda eser,
mağdurun yerleşim yerinde veya oturduğu yerde dağıtılmışsa, o yer mahkemesi de
yetkilidir. Mağdur, suçun işlendiği yer dışında tutuklu veya hükümlü
bulunuyorsa, o yer mahkemesi de yetkilidir.

Görsel veya işitsel yayınlarda da bu maddenin üçüncü fıkrası hükmü uygulanır.
Görsel ve işitsel yayın, mağdurun yerleşim yerinde ve oturduğu yerde işitilmiş
veya görülmüşse o yer mahkemesi de yetkilidir.

Suçun işlendiği yer belli değilse, şüpheli veya sanığın yakalandığı yer,
yakalanmamışsa yerleşim yeri mahkemesi yetkilidir.

Şüpheli veya sanığın Türkiye'de yerleşim yeri yoksa Türkiye'de en son adresinin
bulunduğu yer mahkemesi yetkilidir.

Mahkemenin bu suretle de belirlenmesi olanağı yoksa, ilk usul işleminin
yapıldığı yer mahkemesi yetkilidir.

CAUTION: Yer bakımından yetki kamu düzenine ilişkin değildir.

==== YER BAKIMINDAN YETKİ KURALININ İSTİSNALARI

. *Bağlantı*: Her biri değişik mahkemelerin yetkisi içinde bulunan bağlantılı
ceza davaları, yetkili mahkemelerden herhangi birisinde birleştirilerek
görülebilir.
+
Bağlantılı ceza davalarının değişik mahkemelerde bakılmasına başlanmış olursa,
Cumhuriyet savcılarının istemlerine uygun olmak koşuluyla, mahkemeler arasında
oluşacak uyuşma üzerine, bu davaların hepsi veya bir kısmı bu mahkemelerin
birinde birleştirilebilir.
+
Uyuşulmazsa, Cumhuriyet savcısı veya sanığın istemi üzerine ortak yüksek
görevli mahkeme birleştirmeye gerek olup olmadığına ve gerek varsa hangi
mahkemede birleştirileceğine karar verir.
+
Birleştirilmiş olan davaların ayrılması da bu suretle olur.
. *Muhakemenin nakli*: Yetkili hâkim veya mahkeme, hukukî veya fiilî sebeplerle
görevini yerine getiremeyecek hâlde bulunursa; yüksek görevli mahkeme, davanın
başka yerde bulunan aynı derecede bir mahkemeye nakline karar verir.
+
Kovuşturmanın görevli ve yetkili olan mahkemenin bulunduğu yerde yapılması kamu
güvenliği için tehlikeli olursa, davanın naklini Adalet Bakanı Yargıtaydan
ister.
+
Mahkeme, fiili sebepler veya güvenlik gerekçesiyle duruşmanın il sınırları
içinde başka bir yerde yapılmasına karar verebilir. Bu karara karşı itiraz yolu
açıktır.
. *İstinabe*: Hakim bir takım işlemler için yetkisini bir başka hakime sadece o
işlemle sınırlı ve geçici olarak nakledebilir. İstinabe bir coğrafi bölgedeki
makamın başka bir coğrafi bölgede yapması gereken işlemi kendisiyle aynı
seviyede olan ve işlemin olduğu bölgedeki yetkili hakim veya savcılığa o işleri
yapması için yazısıdır. *Makamlar birbirine denk olmalıdır.*

==== YETKİ UYUŞMAZLIĞI

Birkaç hâkim veya mahkeme arasında olumlu veya olumsuz yetki uyuşmazlığı
çıkarsa, ortak yüksek görevli mahkeme, yetkili hâkim veya mahkemeyi belirler.

IMPORTANT: Soruşturma aşamasındaki bir dosya kendisine yetkisizlik ile gelen
cumhuriyet savcılığı kendisinin de yetkisiz olduğunu düşünüyor olsa bile
dosyayı geri gönderemez. Dosyayı bağlı bulunduğu ağır ceza mahkemesi bölgesine
en yakın yer ağır ceza bölgesindeki ağır ceza mahkemesine uyuşmazlığın çözümü
için göndermek zorundadır.

==== YETKİSİZLİK İDDİASI

Sanık, yetkisizlik iddiasını, ilk derece mahkemelerinde duruşmada sorgusundan,
bölge adliye mahkemelerinde incelemenin başlamasından ve duruşmalı işlerde
inceleme raporunun okunmasından önce bildirir.

Yetkisizlik iddiasına ilişkin karar, ilk derece mahkemelerinde sanığın
sorgusundan önce, bölge adliye mahkemelerinde duruşmasız işlerde incelemenin
hemen başlangıcında, duruşmalı işlerde inceleme raporu okunmadan önce verilir.
Bu aşamalardan sonra yetkisizlik iddiasında bulunulamayacağı gibi mahkemeler de
bu hususta re'sen karar veremez.

Yetkisizlik kararlarına karşı itiraz yoluna gidilebilir.

==== YETKİLİ OLMAYAN MAHKEMENİN İŞLEMLERİ

Yetkili olmayan hâkim veya mahkemece yapılan işlemler, sadece yetkisizlik
nedeniyle hükümsüz sayılmaz. Bir hâkim veya mahkeme, yetkili olmasa bile,
gecikmesinde sakınca bulunan hâllerde, yargı çevresi içerisinde gerekli
işlemleri yapar.

=== KİŞİ BAKIMINDAN YETKİ

Bazı kişiler taşıdıkları sıfatlardan ötürü kendilerine özel birtakım kurallarla
soruşturulup kovuşturulurlar.

=== GÖREV İTİBARİYLE YETKİ

Görev itibariyle yetkide bir mahkemenin görev veya yetki alanında yapılacak işi
yapması için yetkinin devredilmesi söz konusudur. Mahkeme heyeti yapılacak iş
için hakimlerden birini *naip hakim* olarak yetkilendirir ve naip hakim işlemi
yaparken *heyet adına* hareket eder. Her işlem için ayrıca yetkilendirme gerekir.

== ESKİ HALE GETİRME

Kişi belirli bir süre içinde yapılması gereken işlem için süreyi kusuru olmadan
kaçırmışsa eski hale getirme imkanından yararlanabilir.

Eski haline getirme talebi süre kaçırılmasaydı işlemi hangi mercii yapacaksa o
merciye dilekçe ile başvuru şeklinde iletilir. Engelin kalkmasından itibaren 7
gün içinde başvurunun yapılması gerekir.

Kişi başvurusunda engel olmasaydı yapacağı işlemi de sunmalıdır.

Eski hale getirme talebi kabul edildiği takdirde kesin iken reddedildiği
takdirde itiraza konu edilebilir.

== KORUMA TEDBİRLERİ

Kural olarak koruma tedbirlerine hükmedecek makam Sulh Ceza Hakimidir. İstisnai
olarak Cumhuriyet Savcısı gecikmesinde sakınca bulunan hallerin varlığı halinde
hakim kararı olmadan da koruma tedbirlerine başvurabilir. Hatta Cumhuriyet
Savcısına ulaşılamıyorsa kolluk amiri de bir kısım koruma tedbirlerine
başvurabilir.

=== KORUMA TEDBİRLERİNİN ORTAK ÖZELLİKLERİ

* Mahkeme hükmünden önce bir anayasal özgürlük sınırlanır.
* Koruma tedbiri ile kısıtlanan özgürlük ile ulaşılmak istenen amaç arasında
orantı olmalıdır.
* Koruma tedbirleri geçicidir.
* Tüm koruma tedbirleri kanuna dayanmalıdır.
* Ortada bir suç şüphesi olmalıdır.
* Verilen koruma tedbiri kararı en azından görünüşte bir haklılığa sahip
olmalıdır.
* Koruma tedbirleri uygulanması zorunlu hallerde uygulanır.
* Koruma tedbirlerinin uygulanması için kural olarak hakim kararı gerekir.

=== ÖNLEYİCİ TEDBİRLER

Suç şüphesinden sonra bir delil elde edilmesi veya daha sonra infazın
sağlanması için verilen tedbirlere koruma tedbiri denirken suç şüphesine kadar
kadar kolluk tarafından yapılan tehlikeyi önlemeye yönelik davranışlara
önleyici tedbirler denir.

Önleyici tedbirler soruşturma ve kovuşturma aşaması yokken yapılan
işlemlerdir.

Önleyici tedbirler aşağıdaki şartlar altında yapılabilir:

. Bir suç veya kabahatin engellenmesi
. Suç işlendikten sonra kaçan faillerin yakalanmasını sağlamak
. İşlenen suç veya kabahatin faillerinin kimliklerini tespit etmek
. Hakkında yakalama emri veya zorla getirme kararı verilmiş olan kişileri
tespit etmek
. Kişilerin hayatı, vücut bütünlüğü veya malvarlığı bakımından ya da topluma
yönelik mevcut veya muhtemel bir tehlikenin önlenmesi

Önleyici tedbirler kapsamında suç delili ile karşılaşılırsa bu deliller
soruşturma sırasında kullanılabilir. Bunların soruşturmada kullanılabilmesi
için tek şart önleyici tedbirin hukuka uygun şekilde yapılmasıdır.

=== YAKALAMA

*Yakalama*, bir suç şüphesi sebebiyle şüpheli veya sanığın hareket özgürlüğünün
anlık biçimde kısıtlanmasıdır.

Aşağıda belirtilen hâllerde, herkes tarafından geçici olarak yakalama
yapılabilir:

.. Kişiye suçu işlerken rastlanması.
.. Suçüstü bir fiilden dolayı izlenen kişinin kaçması olasılığının bulunması
veya hemen kimliğini belirleme olanağının bulunmaması.
+
Suçüstü;

... Failin suçun maddi unsurlarını gerçekleştirirken yakalanması
... Fail suçu henüz işlemiş olmakla birlikte yakalamak için takip edilmesi
... Failin üstündeki birtakım iz ve eşyalar ile fiili az önce işlediğinin
anlaşılması

==== YAKALAMA EMRİ

Soruşturma evresinde çağrı üzerine gelmeyen veya çağrı yapılamayan şüpheli
hakkında, Cumhuriyet savcısının istemi üzerine sulh ceza hâkimi tarafından
yakalama emri düzenlenebilir. Bunun bir istisnası CMK 199'daki "_Mahkeme,
sanığın hazır bulunmasına ve zorla getirme kararı veya yakalama emriyle
getirilmesine her zaman karar verebilir_" hükmüdür. Bu durumda çağrı yapmasına
veya yaptığı çağrının sonuçsuz kalmasına gerek yoktur.

NOTE: Yakalama emri soruşturma aşamasında verildiğinde bir sulh hakimi kararı
olduğuna göre emre karşı başvurulacak yol da itiraz kanun yoludur. Kovuşturma
evresinde ise ancak mahkemeden emri kaldırması talep edilebilir.

Ayrıca, tutuklama isteminin reddi kararına itiraz halinde, itiraz mercii
tarafından da yakalama emri düzenlenebilir.

[TIP]
====
Tutuklamaya, ancak sanığın hazır bulunduğu ve savunmasının alındığı bir
tutuklama yargılamasının sonunda karar verilir. Kişiye ilişkin soruşturma
çerçevesinde Cumhuriyet savcısı tutuklama talep eder ve sulh ceza hakimliğine
sevk eder. Sulh ceza hakimi sorguyu yapar ve tutuklama talebini reddedebilir.
Savcının bu karara karşı başvurabileceği yol itiraz kanun yoludur. Bu itiraz
ise bir sonraki numaralı sulh ceza hakimliği tarafından incelenir. İtirazın
konusu tutuklama isteminin reddine ilişkin karardır. Dolayısıyla itirazı
inceleyecek olan merci bu itirazı kabul ederse aslında tutuklamaya karar vermiş
olur. Tutuklamaya karar verilebilmesi için de kişinin hazır bulunması ve
savunmasının alınması gerekir. Kişinin hazır bulunmaması halinde, hakim
doğrudan itirazı reddetmiyor, yargılamaya değer buluyorsa verebileceği azami
karar yakalama emri çıkartılmasıdır.

Yakalama emri tutuklama yargılaması yapılabilmesine yöneliktir. *Ancak hakimin
tutuklanmak üzere yakalanmasına dair bir emir çıkartması tutuklama yargılaması
bitmeden ihsas anlamına gelir ve dolayısıyla tarafsızlığı şüpheye düşüren
sebeple reddi sonuçlar.*
====

Yakalanmış iken kolluk görevlisinin elinden kaçan şüpheli veya sanık ya da
tutukevi veya ceza infaz kurumundan kaçan tutuklu veya hükümlü hakkında
Cumhuriyet savcıları ve kolluk kuvvetleri de yakalama emri düzenleyebilirler.

Kovuşturma evresinde kaçak sanık hakkında yakalama emri re'sen veya Cumhuriyet
savcısının istemi üzerine hâkim veya mahkeme tarafından düzenlenir.

Yakalama emrinde, kişinin açık eşkâli, bilindiğinde kimliği ve yüklenen suç ile
yakalandığında nereye gönderileceği gösterilir.

Hâkim veya mahkeme tarafından verilen yakalama emri üzerine soruşturma veya
kovuşturma evresinde yakalanan kişi, en geç yirmi dört saat içinde yetkili
hâkim veya mahkeme önüne çıkarılır.

Yakalanan kişi, en geç yirmi dört saat içinde yetkili hâkim veya mahkeme önüne
çıkarılamıyorsa, aynı süre içinde yakalandığı yer adliyesinde, mevcut değil ise
en yakın adliyede kurulu sesli ve görüntülü iletişim sisteminin (SEGBIS)
kullanılması suretiyle yetkili hâkim veya mahkeme tarafından bu kişinin sorgusu
yapılır veya ifadesi alınır.

TIP: Yakalama emrinin diğer koruma tedbirlerinden en önemli farkı infazın
yaygınlığıdır. Yakalama emri, kişinin yurt genelinde kolluk birimleri
tarafından yakalanabilmesini sağlar.

Yakalama işlemi veya yakalama emrinin tek muhattabı şüpheli veya sanıktır.
Şüpheli veya sanık dışındaki kişilere yönelik olarak yakalama işleminin tatbik
edilebilmesi ya da yakalama emrinin çıkartılabilmesi imkanı yoktur.

==== YAKALAMA EMRİ OLMADAN YAKALAMA

Kolluk görevlileri, tutuklama kararı veya yakalama emri düzenlenmesini
gerektiren ve gecikmesinde sakınca bulunan hâllerde; Cumhuriyet savcısına veya
âmirlerine derhâl başvurma olanağı bulunmadığı takdirde, yakalama yetkisine
sahiptirler.

Kolluk görevlisi karşılaştığı bir durumun öncelikle yakalama emri düzenlenmesi
veya tutuklama kararı verilmesi gereken bir hal olup olmadığını değerlendirmek
durumundadır. Bu değerlendirmenin doğru olup olmadığı hususunda denetim yapma
yetkisi kolluk görevlisine ait olamaz. Bu yetki amirine veya kural olarak
Cumhuriyet Savcısına aittir. Kolluk görevlisi ulaşabildiği takdirde Cumhuriyet
savcısının bilgisi doğrultusunda işlem yapmak durumundadır. Cumhuriyet savcısı
durumun yakalama emri veya tutuklama kararı verilmesi gerektiren ve
gecikmesinde sakınca olan bir hal olduğuna kanaat getirirse kolluğa *yakalama
talimatı* verecektir. *Burada bir emir söz konusu değildir.*

Soruşturma ve kovuşturması şikâyete bağlı olmakla birlikte, çocuklara, beden
veya akıl hastalığı, malûllük veya güçsüzlükleri nedeniyle kendilerini idareden
aciz bulunanlara karşı işlenen suçüstü hallerinde kişinin yakalanması şikâyete
bağlı değildir.

==== YAKALAMA İŞLEMİ

Yakalamada belirli bir oranda cebir kullanılması gerekebilir. Bu cebrin
yakalamayı gerçekleştirecek miktarda ölçülü olması gerekir. Eğer ölçülülük
aşılırsa işlem hukuka aykırı olacaktır. Ayrıca söz konusu zor kullanmanın
gerekli olması gerekir.

Kolluk, yakalandığı sırada kaçmasını, kendisine veya başkalarına zarar
vermesini önleyecek tedbirleri aldıktan sonra, yakalanan kişiye kanunî
haklarını derhal bildirir.

Yakalanan veya tutuklanarak bir yerden diğer bir yere nakledilen kişilere,
kaçacaklarına ya da kendisi veya başkalarının hayat ve beden bütünlükleri
bakımından tehlike arz ettiğine ilişkin belirtilerin varlığı hâllerinde kelepçe
takılabilir.

TIP: Çocuklar bakımından kelepçe asla uygulanamaz. Hatta 12 yaşından küçük
çocuklar için yakalamaya karar verilemez.

Yakalama işlemi yapıldıktan sonra yakalanan kişinin üstü kaba üst araması
şeklinde aranabilir.

Yakalandıktan sonra kişiye, yakalanmasının sebebi, hangi fiil sebebiyle
kendisine yakalama tatbik edildiği, haklarının neler olduğu anlatılmalıdır.

Yakalama işlemi bir tutanağa bağlanır. Bu tutanağa yakalananın, hangi suç
nedeniyle, hangi koşullarda, hangi yer ve zamanda yakalandığı, yakalamayı
kimlerin yaptığı, hangi kolluk mensubunca tespit edildiği, haklarının tam
olarak anlatıldığı açıkça yazılır.

Yakalama anında zor kullanılmışsa, kişi hakkında gözaltı kararı verilmişse,
gözaltı süresinin uzatılması kararı verilmişse veya gözaltı süresi içinde kişi
bir yerden bir yere nakledilmişse; bütün bu işlemler sırasında sağlık raporu
almak zorunluluğu söz konusudur.

CAUTION: Kişiyi yakalayan kolluk görevlisi ile sağlık raporu almaya götüren
kolluk görevlisi aynı kişi olmamalıdır.

Şüpheli veya sanık yakalandığında, gözaltına alındığında veya gözaltı süresi
uzatıldığında, Cumhuriyet savcısının emriyle bir yakınına veya belirlediği bir
kişiye gecikmeksizin haber verilir.

Yakalanan veya gözaltına alınan yabancı ise, yazılı olarak karşı çıkmaması
halinde, durumu, vatandaşı olduğu devletin konsolosluğuna bildirilir.

Soruşturma ve kovuşturması şikâyete bağlı olan suç hakkında 90 ıncı maddenin
üçüncü fıkrasına göre şikâyetten önce şüpheli yakalanmış olursa şikâyete
yetkili olan kimseye ve bunlar birden fazla ise hiç olmazsa birine yakalama
bildirilir.

Yakalamanın gerçekleşmesi ile birlikte yakalama koruma tedbiri de sona erer.
Kişi yakalandıktan sonra ya serbest bırakılır ya da bir başka koruma tedbiri
olan gözaltı gündeme gelir.

=== GÖZALTI

Yakalanan kişi, Cumhuriyet Savcılığınca bırakılmazsa, soruşturmanın
tamamlanması için gözaltına alınmasına karar verilebilir.

*Gözaltı*, kişinin soruşturma işleminin yapılması için zorunlu olması sebebiyle
CMK 91'deki azami süreler içerisinde adliyeyinin eli altında tutulmasıdır.

Gözaltı süresi, yakalama yerine en yakın hâkim veya mahkemeye gönderilmesi için
zorunlu süre hariç, yakalama anından itibaren yirmidört saati geçemez. Yakalama
yerine en yakın hâkim veya mahkemeye gönderilme için zorunlu süre oniki saatten
fazla olamaz.

Toplu olarak işlenen suçlarda, delillerin toplanmasındaki güçlük veya şüpheli
sayısının çokluğu nedeniyle; Cumhuriyet savcısı gözaltı süresinin, her
defasında bir günü geçmemek üzere, üç gün süreyle uzatılmasına yazılı olarak
emir verebilir. Gözaltı süresinin uzatılması emri gözaltına alınana derhâl
tebliğ edilir.

Gözaltına alma, bu tedbirin soruşturma yönünden zorunlu olmasına ve kişinin bir
suçu işlediği şüphesini gösteren somut delillerin varlığına bağlıdır.

==== GÖZALTI KARARI

Gözaltı talimatı yazılı veya sözlü olarak verilebilir. Zira ilk gözaltına alma
işlemi niteliği gereği gecikmesinde sakınca olan bir işlemdir. Cumhuriyet
savcısnın hazır bulunduğu durumlarda soruşturma işlemleri yazılı olarak
yapılmalıdır. Ancak savcı hazır bulunmuyorsa sözlü olarak da yapılıp tutanağa
bağlanabilir.

CAUTION: Gözaltı süresinin uzatılması söz konusu olduğunda ise artık
gecikmesinde sakınca bulunan bir işlem yoktur. Dolayısıyla gözaltı süresinin
uzatılmasına dair bütün işlemler yazılı olarak yapılmak zorundadır.

==== KOLLUK AMİRİNİN GÖZALTI KARARI

Suçüstü hâlleriyle sınırlı olmak kaydıyla; kişi hakkında aşağıdaki bentlerde
belirtilen suçlarda mülki amirlerce belirlenecek kolluk amirleri tarafından
yirmi dört saate kadar, şiddet olaylarının yaygınlaşarak kamu düzeninin ciddi
şekilde bozulmasına yol açabilecek toplumsal olaylar sırasında ve toplu olarak
işlenen suçlarda kırk sekiz saate kadar gözaltına alınma kararı verilebilir.
Gözaltına alma nedeninin ortadan kalkması hâlinde veya işlemlerin tamamlanması
üzerine derhâl ve her hâlde en geç yukarıda belirtilen sürelerin sonunda
Cumhuriyet savcısına, yapılan işlemler hakkında bilgi verilerek talimatı
doğrultusunda hareket edilir. Kişi serbest bırakılmazsa yukarıdaki fıkralara
göre işlem yapılır. Ancak kişi en geç kırk sekiz saat, toplu olarak işlenen
suçlarda dört gün içinde hâkim önüne çıkarılır. Bu fıkra kapsamında kolluk
tarafından gözaltına alınan kişiler hakkında da gözaltına ilişkin hükümler
uygulanır.

.. Toplumsal olaylar sırasında işlenen cebir ve şiddet içeren suçlar.
.. 5237 sayılı Türk Ceza Kanununda yer alan;

. Kasten öldürme, taksirle öldürme
. Kasten yaralama
. Cinsel saldırı
. Çocukların cinsel istismarı
. Hırsızlık
. Yağma
. Uyuşturucu veya uyarıcı madde imal ve ticareti
. Bulaşıcı hastalıklara ilişkin tedbirlere aykırı davranma
. Fuhuş
. Kötü muamele

.. 12/4/1991 tarihli ve 3713 sayılı Terörle Mücadele Kanununda yer alan suçlar.
.. 6/10/1983 tarihli ve 2911 sayılı Toplantı ve Gösteri Yürüyüşleri Kanununun
33 üncü maddesinin birinci fıkrasının (a) bendinde belirtilen suçlar.
.. 10/6/1949 tarihli ve 5442 sayılı İl İdaresi Kanununa dayanılarak ilan edilen
sokağa çıkma yasağını ihlal etme.
.. 21/3/2007 tarihli ve 5607 sayılı Kaçakçılıkla Mücadele Kanununun 3 üncü
maddesinde belirtilen suçlar

==== GÖZALTI İŞLEMLERİNİN DENETİMİ

Cumhuriyet başsavcıları veya görevlendirecekleri Cumhuriyet savcıları, adlî
görevlerinin gereği olarak, gözaltına alınan kişilerin bulundurulacakları
nezarethaneleri, varsa ifade alma odalarını, bu kişilerin durumlarını,
gözaltına alınma neden ve sürelerini, gözaltına alınma ile ilgili tüm kayıt ve
işlemleri denetler; sonucunu Nezarethaneye Alınanlar Defterine kaydederler.

==== GÖZALTI KARARINA İTİRAZ

Yakalama işlemine, gözaltına alma ve gözaltı süresinin uzatılmasına ilişkin
Cumhuriyet savcısının yazılı emrine karşı, yakalanan kişi, müdafii veya kanunî
temsilcisi, eşi ya da birinci veya ikinci derecede kan hısımı, hemen serbest
bırakılmayı sağlamak için sulh ceza hâkimine başvurabilir.

Sulh ceza hâkimi incelemeyi evrak üzerinde yaparak derhâl ve nihayet yirmidört
saat dolmadan başvuruyu sonuçlandırır.

Yakalamanın veya gözaltına alma veya gözaltı süresini uzatmanın yerinde olduğu
kanısına varılırsa başvuru reddedilir ya da yakalananın derhâl soruşturma
evrakı ile Cumhuriyet Savcılığında hazır bulundurulmasına karar verilir.

NOTE: Sulh hakimi yakalamanın, gözaltının veya gözaltı süresinin uzatılmasına
ilişkin işlemlerin hukuka aykırı olduğuna karar vererek kişinin derhal serbest
bırakılmasına hükmedebilir.

==== GÖZALTININ SONA ERMESİ

* *1. ihtimal:* Gözaltı süresi içerisinde kişinin serbest bırakılmasına
Cumhuriyet savcısı karar verebilir.
* *2. ihtimal:* Gözaltı süresinin sonunda veya bu sürenin öncesinde Cumhuriyet
savcısı gözaltını sonlandırarak kişinin sorguya sevkine karar verebilir.
* *3. ihtimal:* Sorgunun sonunda veya sorguya sevkle beraber kişinin
tutuklanması talep edilebilir. Kişi tutuklanırsa gözaltı tutuklamaya dönüşür.
Ancak tutuklama istemi reddedilirse ya da tutuklama yerine adli kontrole karar
verilirse gözaltı yine son bulur.

Gözaltı süresinin dolması veya sulh ceza hâkiminin kararı üzerine serbest
bırakılan kişi hakkında yakalamaya neden olan fiille ilgili yeni ve yeterli
delil elde edilmedikçe ve Cumhuriyet savcısının kararı olmadıkça bir daha aynı
nedenle yakalama işlemi uygulanamaz.

=== TUTUKLAMA

Tutuklama tedbirine karar verildiğinde kişi, Anayasa'da belirlenen süreler
içerisinde tutukevi olarak adlandırılan bir yerde tutulur. Kişinin burada
tutulmasının temel gerekçesi, gözaltında olduğu gibi belirli işlemlerin
tamamlanması değil, muhakemenin bütününe yönelik bir tehlikenin bertaraf
edilmesidir.

Tutuklama koruma tedbirine başvurulabilmesi için ilk olarak bir *tutuklama
nedeninin var olması*, ikinci olarak *kuvvetli suç şüphesinin bulunması* ve son
olarak da *tutuklamanın ölçülü olması* gerekir.

Aşağıdaki hallerde bir tutuklama nedeni var sayılabilir:

.. Şüpheli veya sanığın kaçması, saklanması veya kaçacağı şüphesini uyandıran
somut olgular varsa.
.. Şüpheli veya sanığın davranışları;

. Delilleri yok etme, gizleme veya değiştirme,
. Tanık, mağdur veya başkaları üzerinde baskı yapılması girişiminde bulunma,

+
Hususlarında kuvvetli şüphe oluşturuyorsa.

IMPORTANT: Tutuklama nedeni bir vakıanın, bir olgunun varlığına bağlıdır.

CMK 100/3'te sayılan suçlarda tutuklama nedeninin varlığı karine olarak kabul
edilir.

Ölçülülük değerlendirmesi tedbirin tatbik edileceği kişiye göre yapılmalıdır.
Ölçülülükten kasıt, tedbirin tatbik edilmesi nedeniyle yarattığı ihlalin, suç
soruşturmasından elde edilecek menfaate nazaran daha önemli olmamasıdır.

NOTE: 2 yılın altında cezayı gerektiren suçlarda tutuklama yasaktır (vücut
dokunulmazlığını ihlal eden suçlar hariç). 

Tutuklamanın maddi koşulları olan neden, şüphe ve ölçülülük hem kararın talep
edilmesi aşamasında hem kararın verilmesi aşamasında hem de denetlenmesi
aşamasında tekrar tekrar gözden geçirilmelidir. Bu koşullardan herhangi biri
ortadan kalktığı takdirde tutuklamaya kendiliğinden son verilmesi gerekir.

Ölçülülük denetiminde dikkat edilmesi gereken bir husus tutuklamayla ortadan
kaldırılmak istenen tehlikenin adli kontrol ile ortadan kaldırılabilir olup
olmamasıdır. Dolayısıyla tutuklama talebinde savcı, adli kontrol tedbirlerinin
neden yetersiz kaldığını açıklamalı ve hakim de tutuklama kararında adli kontrol
tedbirlerinin neden yetersiz kaldığını gerekçelendirmelidir. Adli kontrolün
yeterli olması tutuklamanın ölçüsüz olması anlamına gelecektir.

[caption=""]
.Güvence belgesi
====
Güvence belgesi, kaçak ya da gaip sanığa verilen ve tutuklanmayacağı garantisini
içeren belgedir. Bu belge, sadece bir suç için değil; bir kişi için verilir.
Dolayısıyla o kişi hakkında ne dar soruşturma ve kovuşturma var ise o soruşturma
ve kovuşturmalara kişinin tutuklanmasını imkansız hale getirir; yeter ki belge
düzenlendikten sonra kişi hakkında yeni bir tutuklama nedeni ortaya çıkmasın.

Kaçak veya gaip sanığa güvence belgesi verilmiş olması tutuklamanın bozucu şekil
şartıdır. Tutuklamanın bütün koşulları gerçekleşmiş olsa bile güvence belgesi
verilmişse tutuklama yapılamaz.
====

Tutuklama kararını verebilecek yegane merci hakim veya mahkemelerdir. Soruşturma
evresinde sulh ceza hakimi, kovuşturma evresinde yargılamayı yapan hakimin
vereceği bir tutuklama kararı gereklidir.

Tutuklama kararının verilebilmesi, tutuklama yargılaması denebilecek bir tali
muhakemeye ihtiyaç duyar. Tutuklama mahkemesinin ilk ve en önemli koşulu
**şüpheli veya sanığın hazır bulunması**dır. Mahkeme ya da hakim mevcut
delillere göre tutuklama kararı verilmesi gerektiğini düşünüyorsa verebileceği
azami karar yakalama emri çıkarmaktır. Çünkü tutuklama kararı ancak sanığın
hazır bulunması ile sorgu ve savunması alındıktan sonra verilebilir.

TIP: Şüpheli veya sanık yurtdışında kaçak ise yokluğunda tutuklama kararı
verilebilir.

Tutuklama muhakemesi soruşturma evresinde ancak istem üzerine başlatılabilir.
Dolayısıyla soruşturma evresinde tutuklama kararının verilebilmesi Cumhuriyet
savcısının talebine bağlıdır. Bu aşamada hakimin yetkisi savcının istemiyle
sınırlıdır.

Soruşturma evresinde tutuklama talebi üzerine hakimin adli kontrol kararı
verebilmesinin önünde bir engel yoktur.

NOTE: Soruşturma evresinde Cumhuriyet savcısı artık tutuklamanın gereksiz
olduğuna kanaat getirirse karara gerek olmaksızın kişiyi salıvermek yetkisine
sahiptir.

Kovuşturma evresinde ise mahkeme re'sen tutuklama kararı verebilir. 

Tutuklama muhakemesi zorunlu müdafilik hallerinden bir tanesidir. Müdafinin
yokluğunda tutuklama kararı verilemez.

[caption=""]
.Tutukluluk denetimi
====
Anayasa Mahkemesi ve AİHM'in tutukluluk denetimi yaklaşımı benzerdir. Her iki
mahkeme de aşağıdaki hususlara dikkat çekmektedir:

* Tutuklamanın hukuki olması için öncelikle mevcut normlara uygun bir tutuklama
kararının verilmesi gerekir.
* Tutuklama kararındaki gerekçe, kişi ve fiil özelinde delille
ilişkilendirilmelidir.
* İsnat edilen suçun cezasının ağır olması tek başına tutuklama gerekçesi
olamaz.
====

Tutuklama bakımından anayasal sınır **makul süre**dir. Anayasa "_Kişi ancak o
soruşturma veya kovuşturma bakımından makul sayılabilecek bir süreyle tutuklu
kalabilir_" demektedir.

Ağır ceza mahkemelerinin görev alanı dışında kalan suçlarda bu süre 1 yıldır.
Ancak zorunlu hallerde gerekçe gösterilerek 6 ay uzatılabilir. Yani asliye
cezalık suçlarda kişi ancak 18 aya kadar tutuklu yargılanabilir.

Ağır cezalık suçlarda ise bu süre 2 yıldır. Ancak zorunlu hallerde gerekçe
gösterilerek bu süre 3 yıl daha uzatılabilir. Dolayısıyla ağır cezalık suçlarda
kişi en fazla 5 yıl tutuklu yargılanabilir.

TIP: OHAL KHK'larından biri ile 5 yıllık süre 7 yıla çıkarılmıştır.

NOTE: Anayasa Mahkemesi tutukluluk süresinin makul olup olmadığını incelerken
yapılan işlemler ve bu işlemler için gereken makul süreyi dikkate alır.
İşlemler, gereken makul süre içerisinde yapılmamışsa azami tutukluluk süresi
aşılmamış olsa bile makul süreden bahsedilemez.

Azami süre bittiğinde tutukluluğa son verilmesi gerekir. Fakat bu süre
Yargıtay'a göre ilk derece mahkemesi için geçerli süredir. Kişi hakkında ilk
derece mahkemesinde bir mahkumiyet kararı verilmişse kanun yolu denetiminde
geçecek süre bu azami sürelere dahil değildir.

CAUTION: Azami süre dolmuş olsa bile tutukluluğun son bulması için hakim veya
mahkeme tarafından bir karar verilmesine ihtiyaç vardır.

Soruşturma evresinde şüpheli hakkında tutuklama kararı verilmişse, kovuşturmaya
yer olmadığı kararı ile birlikte tutuklama bir karara ihtiyaç bulunmaksızın son
bulur.

Beraat kararı da başka herhangi bir karara ihtiyaç duyulmaksızın tutuklamayı
sona erdirir.

NOTE: Soruşturmada savcının tutuklama veya adli kontrol kararı vermek gibi bir
yetkisi yoktur. Ancak verilmiş bir adli kontrol veya tutuklama kararını
kaldırabilir.

Tutuklama kararına karşı itiraz yoluna başvurmak mümkündür. Tutuklama kararının
verildiği tarihten itibaren *7 gün* içerisinde itiraz kanun yoluna gidilebilir.

Soruşturma veya kovuşturma sürecinde şüpheli/sanık ve müdafisi diledikleri zaman
tahliye talebinde bulunabilir. Tahliye isteminin kabul veya reddine ilişkin
karara karşı da yeniden itiraz mekanizmasının işletilmesi mümkündür.

CAUTION: Katılanın veya suçtan zarar görenin tutuklama kararlarına itiraz gibi
bir hakkı yoktur.

Hem soruşturma hem kovuşturma evresinde tutukluluk hali belirli aralıklara (en
fazla 30 günde bir) mahkeme ya da hakimlik tarafından denetlenir. Bu denetim,
kural olarak duruşmalı olarak gerçekleştirilir. Bu denetimlerin sonucunda
tutukluluk halinin devamına ya da kişinin tahliyesine karar verilebilir.
Dolayısıyla bunlar da bağımsız olarak itiraza konu olabilir.

TIP: Kural olarak itiraz üzerine verilen karar kesindir ve ancak nihai hüküm ile
birlikte istinaf veya temyiz incelemesi sırasında denetlenir. İstisnai olarak,
şüpheli veya sanık hakkında ilk tutuklama kararı itiraz muhakemesi üzerine
verilmişse şüpheli veya sanığın bir kez daha itiraz imkanı vardır.

=== ADLİ KONTROL

Tutuklama neden ve koşullarının varlığına rağmen hakimlik veya mahkeme ya da
Cumhuriyet savcısı, tutuklamanın ölçüsüz olduğu sonucuna ulaşır ve tutuklamayla
hedeflenen amacın adli kontrol tedbirlerinden birinin veya birden fazlasının
uygulanması suretiyle temin edilebileceği kanaatine varırsa tutuklamaya değil
adli kontrole başvurur. Adli kontrol tutuklamaya alternatif ve öncül bir
tedbirdir. Dolayısıyla tutuklamadan beklenen fayda adli kontrol tedbirleri ile
sağlanabiliyorsa adli kontrole başvurulması zorunludur.

Adli kontrol tedbirleri:

* Yurt dışına çıkamamak
* Hakim tarafından belirlenen yerlere, belirtilen süreler içinde düzenli olarak
başvurmak
* Hakimin belirttiği merci veya kişilerin çağrılarına ve gerektiğinde mesleki
uğraşlarına ilişkin veya eğitime devam konularında kontrol tedbirlerine uymak
* Her türlü taşıtı veya bunlardan bazılarını kullanamamak ve gerektiğinde
kaleme, makbuz karşılığında sürücü belgesini teslim etmek
* Uyuşturucu, uyarıcı veya uçucu maddeler ile alkol bağımlılığından arınmak
amacıyla hastaneye yatmak dahil, tedavi veya muayene tedbirlerine tabi olmak ve
bunları kabul etmek
* Şüphelinin parasal durumu göz önünde bulundurularak, miktarı ve bir defada
veya birden çok taksitle ödeme süreleri hakimce belirlenecek bir güvence miktarı
yatırmak
* Silah bulunduramamak veya taşıyamamak, gerektiğinde sahip olunan silahları
makbuz karşılığında adli emanete teslim etmek
* Hakim tarafından miktarı ve ödeme süresi belirlenecek parayı, mağdurun
haklarını güvence altına almak üzere ayni veya kişisel güvenceye bağlamak
* Aile yükümlülüklerini yerine getireceğine ve adli kararlar gereğince ödemeye
mahkum edildiği nafakayı düzenli olarak ödeyeceğine dair güvence vermek
* Konutunu terk etmemek
* Belirli bir yerleşim bölgesini terk etmemek
* Belirlenen yer veya bölgelere gitmemek

Tıpkı tutuklamada olduğu gibi adli kontrole karar verilebilmesi de soruşturma
evresinde Cumhuriyet savcısının istemine bağlıdır. Kovuşturma evresinde ise
mahkeme, talep olsun veya olmasın re'sen adli kontrole karar verebilir.

NOTE: Sulh ceza hakiminden tutuklama istendiğinde hakim tutuklama yerine adli
kontrole karar verebilir.

Adli kontrole ilişkin kararların tamamına itiraz edilebilir.

Adli kontrol tedbirlerinin herhangi bir süresi yoktur. Nihayetinde yargılamanın
sonuna kadar bir tedbire başvurulabilir.

IMPORTANT: Adli kontrolde geçirilen zaman mahkumiyet halinde hükümden mahsup
edilmez. İstisnaen, uyuşturucu madde suçlarında bağımlılıktan kurtulmak için bir
tedavi kurumuna yatırılma kararlarında burada geçirilen süre hükümden mahsup
edilir.

[caption=""]
.Güvence bedeli
====
Güvence bedelinin temel amacı kişinin kaçmamasını ve soruşturma veya kovuşturma
işlemlerine katılmasını sağlamaktır. İkinci amaç ise söz konusu suç sebebiyle
mağdurun veya kamunun uğradığı bir zarar varsa bunların karşılanmasıdır. Üçüncü
amaç, kişinin aile hukukundan kaynaklanan yükümlülükleri varsa bu
yükümlülüklerin yerine getirilmesini sağlamaktır.

Adli kontrol tedbiri, bu amaçların tamamı veya sadece bir tanesi için
verilebilir. Ancak adli kontrol, bu şekilde bir güvencenin yatırılması olarak
verildiğinde ne kadar miktarın neyi garanti ettiği söz konusu kararda
belirtilmelidir.
====

NOTE: Tutuklamanın azami süresini doldurup salıverilmiş kişi hakkında adli
kontrol tedbirine karar verilmiş ve kişi bu tedbirin gereklerini yerine
getirmemişse yeniden tutuklanabilir. Bu halde tutuklama süresi ağır cezalık
suçlarda 9 ayı, asliye cezalık suçlarda 2 ayı geçemez.

=== ZORLA GETİRME

Soruşturma evresinde ifade söz konusuysa Cumhuriyet savcısı, kovuşturma
evresinde ise mahkemenin zorla getirme kararı verebilme imkanı vardır. Zorla
getirmenin temel amacı, şüpheli veya sanığın ifadesinin alınmasını veya
sorgusunun yapılmasını sağlamaktır.

Zorla getirme, tanık, bilirkişi ve suçtan zarar gören bakımından da
uygulanabilecek bir tedbirdir. Ancak bu kişilerin zorla getirilebilmesi için
bunlara yapılacak davette, gelmemesi durumunda zorla getirileceği ihtar
edilmelidir.

Zorla getirme bir kişiye ve bir yere yöneliktir. Bütün yurt sathında zorla
getirme kararı verilemez. Zira bu durumda bir yakalama kararından söz edilir.
Zorla getirme kararı, işlemin yapılacağı tarih ve saatte kişinin bulunduğu
yerden alınıp, kararı veren makamın huzuruna çıkartılması şeklinde infaz edilir.

Zorla getirme kararına karşı herhangi bir kanun yolu düzenlemesi yoktur.

=== GÖZLEM ALTINA ALMA

Şüpheli veya sanığın akıl hastası olduğu yönünde bir şüphe ortaya çıkarsa
hekimin görüşü alınarak akıl sağlığının yerinde olup olmadığının, akıl sağlığı
yerinde değilse ne zamandır yerinde olmadığının ve işlediği suçun hukuki anlam
ve sonuçlarını idrak etmek ihtimalinin bulunup bulunmadığının tespiti amacıyla 3
haftalığına bir tedavi kurumuna yatırılmasına karar verilebilir. Bu tedbire
*gözlem altına alma* denir.

Bu üç haftalık süre üçer haftalık periyotlar halinde ve 3 ayı geçmemek üzere
uzatılabilir.

Gözlem altına alma işlemi zorunlu müdafilik hallerinden birisidir.

NOTE: Gözlem altına alma kararına karşı itiraz, kararın uygulanmasını
kendiliğinden durdurur.

=== ARAMA

Görülemeyen veya gizlenmiş şüpheli, sanık ya da suç delillerini elde etmek
amacıyla gerçekleştirilen araştırma faaliyetine *arama* denir.

[caption=""]
.Önleme araması
====
PVSK 9, suç şüphesi sebebiyle değil, tehlikenin ortadan kaldırılması amacıyla
belirli şartlarda aramaya izin verir.

Önleme aramasının muhatabı, tehlikenin ortaya çıktığı yer ve zaman diliminde
bulunan herkes olabilir. Yeter ki tehlikenin bertaraf edilmesi bakımından tıpkı
durdurmada olduğu gibi o kişinin aranmasını meşru kılabilecek yeterli şüphe
ortaya çıksın.

Önleme aramasına sulh ceza hakimi karar verir. Gecikmesinde sakınca bulunan
hallerde ise mülki amirin emri de yeterlidir.

Sulh ceza hakiminin verdiği bir önleme araması kararının denetimi itiraz
hükümlerine göre yapılır. Valinin emri söz konusu olduğunda ise idari yargının
devreye girmesi icap eder.

*Önleme araması sadece kamuya açık alanlar için geçerli bir işlemdir.*

Önleme araması hukuka uygun olarak yapılmış ve işlem sırasında bir suçun
işlendiğine dair deliller elde edilmişse bunlar bir soruşturmanın başlangıcında
ve sonrasında ispat aracı olarak kullanılabilir.
====

Kanun bazı durumlarda kolluk görevlisine herhangi bir karar veya emir olmaksızın
arama yetkisi vermektedir:

* Gözaltına alınırken kişinin üstünün aranması
* Polisin kendi koruduğu binaların giriş ve çıkışlarında arama işlemi gerçekleştirilmesi
* Spor müsabakalarının yapıldığı yerlerin girişinde arama işlemi gerçekleştirilmesi
* Gümrük bölgelerindeki şüpheli eşyaların aranması
* Havalimanı ve istasyonlar gibi yerlerin girişinde arama yapılması
* Kolluğun elindeyken kaçmış ya da suçüstü halinde bulunan kişinin kesintisiz
takibi sırasında girdiği yerler bakımından kanun, kolluğa doğrudan girme ve
arama yetkisi verir.

NOTE: Arama işlemi, PVSK'da düzenlenen kimlik sorma yetkisiyle
karıştırılmamalıdır. Durdurma ve kimlik sorma işleminde kolluk, kişinin
kendisine veya çevresine zarar verebilecek tehlike barındırdığından
şüphelenirse, kıyafetlerini çıkartmamak veya aracın dışarıdan bakıldığında
görülmeyen yerlerini açtırmamak koşuluyla üst arama yetkisi vardır. Bunlar
aramaya ilişkin olsa da arama işlemi değildir.

*Adli arama*, suç şüphesini bertaraf etmek bakımından, üçüncü kişiye ya da
şüpheli veya sanığa yönelik üstünde, eşyasında, konutunda gerçekleştirilen ve
şüpheli veya sanığın, delilin ya da müsadereye tabi eşyanın tespitine yönelik
işlemdir.

Aramanın yapılması, aranılan kişinin veya suçun delillerinin belirtilen yerlerde
bulunduğunun kabul edilebilmesine olanak sağlayan olayların varlığına bağlıdır.

Adli aramayı diğerlerinden ayıran husus, bir şüphelinin varlığı değil bir suç
şüphesinin varlığıdır. Arama işleminin gerçekleştirilmesi için mutlaka bir
şüpheliye ihtiyaç yoktur.

Aramaya kural olarak hakim karar verir. Ancak gecikmesinde sakınca bulunan
hallerde Cumhuriyet savcısı da arama kararı verebilir. Bu hallerde savcıya
ulaşılamıyorsa kolluk amiri de arama kararı verebilir.

CAUTION: Konut, işyeri veya kamuya kapalı yerlerde arama kararını vermek yetkisi
sadece hakime ve gecikmesinde sakınca bulunan hallerde savcıya aittir. Kolluk
amirinin arama emri verebilme yetkisi sadece üst, eşya ve araçlarda mümkündür.

Yargıtay'a göre savcının arama talimatı vermesi bakımından iki temel ölçüt
bulunmaktadır:

. Savcı önceden arama için karar talep etmiş ve bu talebi reddedilmiş ise, daha
sonra gecikmesinde sakınca bulunduğu gerekçesiyle doğrudan arama emri veremez.
. Savcının arama talimatını verdiği hal, esasında gecikmesinde sakınca bulunan
hal değilse arama işlemi hukuka uygun değildir. Halin gecikmesinde sakınca
bulunan hal olup olmadığı geriye bakarak denetlenir.

*Aramanın hukuka aykırı olmasının en önemli sonucu, arama ile elde edilen
deliller ve bu delillerden hareketle elde edilen diğer delillerin soruşturma
veya kovuşturmada kullanılamamasıdır.*

Arama kararında bulunması zorunlu hususlar şunlardır:

. Aramanın nedenini oluşturan fiil
. Aranacak kişi veya yer
. Aramanın ne kadar süreyle geçerli olduğu

NOTE: Arama kararları tek kullanımlık kararlardır. Arama kararı ne kadar süre
ile verilmişse o süre içerisinde sadece tek bir arama yapılabilir.

İster hakim kararı olsun, ister savcı talimatı ya da kolluk amiri emri olsun
aramaya ilişkin bütün karar ve emirler *yazılı* olarak yapılmak zorundadır.

TIP: Adli arama bakımından, suç şüphesi altında bulunan kişinin soruşturma
makamına aramanın yapılması için verdiği rızanın özgür irade ile verilmiş bir
rıza olduğundan söz edilemez.

Konut, işyeri ve kamuya kapalı alanlarda gece arama yapılması yasaktır. Gece
araması kural olarak sadece kişinin üstünde, eşyasında ve aracında
gerçekleştrilebilir. Gece, güneşin batmasından 1 saat sonra ve doğumundan bir
saat önceki zaman dilimidir. İstisnaen, gecikmesinde sakınca bulunan hallerde
veya firar etmiş kişinin yeniden yakalanması için gece araması her yerde
yapılabilir.

Aramanın mutlaka şüpheli/sanığa karşı yapılması şart değildir. Dolayısıyla
aramanın mutlaka malik denetiminde gerçekleşmesine ihtiyaç vardır. Ancak burada
da işlemi geciktirmemek koşulu aranır.

Cumhuriyet savcısı arama işlemine bizzat nezaret edemiyorsa o yer ihtiyar
heyetinden veya komşulardan iki kişinin de işleme nezaret etmesi sağlanır. Bu
kişiler arama işleminden başından sonuna tanıklık etmek ve tutanağı imzalamak
ile yükümlüdür. Bu kişilere *işlem tanığı* denir.

NOTE: Yargıtay, işlem tanığının bulunmamasının arama işlemini hukuka aykırı hale
getirmeyeceğini kabul etmektedir.

Arama işleminin sonunda işlem bir tutanakla tespit edilir. Tutanakta aramanın
hangi karara veya emre istinaden, hangi fiil sebebiyle, hangi şüpheli/sanık ya
da üçüncü kişi hakkında, nerede ve ne hakkında, ne zaman tatbik edildiği, elde
edilen delillerin neler olduğu tespit edilir. Yine bu tutanakta, elde edilen
eşyaya ilişkin mülkiyet veya başka bir iddia varsa bu belirtilir. Sonunda da
hazır bulunanlarca imzalanır.

=== EL KOYMA

El koymanın konusu iki şey olabilir:

. *İspat vasıtası* olarak yararlı görülen eşyalar, yani deliller
. *Mülkiyeti devlete geçmesi gereken* malvarlığı değerleri veya eşyalar

Taşınması veya bulundurulması suç olan eşyalar bakımından el koyma kararına
ihtiyaç yoktur.

Bir ispat vasıtası ya da müsadereye tabi eşya, ilgilisi tarafından rızayla
teslim edilebilir. Bu durumda eşya *muhafaza altına alınır*. Fakat muhafaza
altına işlemi sonrasında eşyanın adliyenin elinde tutulmasını sürdürebilmek
için *hakim kararına* ihtiyaç vardır. Muhafaza altına almanın el koymaktan
farkı, bünyesinde zor barındırmamasıdır.

Eşya ilgilisi tarafından rızayla teslim edilmiyor ise iki tür zor
kullanılabilir:

. El koyma kararı vermek
. Eşyanın teslimini sağlamak için disiplin hapsi tatbik etmek (60 güne kadar,
tanıklıktan çekinme hakkına sahip olanlar için uygulanamaz)

El koymanın maddi koşulu, eşyanın, delil olduğuna ilişkin tespit ya da
müsadereye tabi olabileceğine ilişkin tespittir.

El koymaya kural olarak *hakim karar verir*. *Gecikmesinde sakınca bulunan
hallerde* cumhuriyet savcısı talimat verir. *Savcıya ulaşılamaması halinde*
kolluk amiri emir verir.

NOTE: Savcı talimatının veya kollum amiri emrinin *yazılı* olarak verilmesi
gerekir.

Hakim kararıyla verilmeyen el koymaların, *el koymanın tatbikinden itibaren 24
saat içinde* hakim onayına sunulması gerekir. Hakimin de el koymanın
tatbikinden *48 saat içinde* işlemi onaylaması veya reddetmesi gerekir. 48 saat
içinde bir karar verilmezse el koyma kendiliğinden kalkar ve işleme son
verilir.

CAUTION: El koyma bakımından _aksi belirtilen özel el koymalar hariç_ eşyanın
kime ait olduğu ya da kimin elinde bulunduğu önemli değildir.

Söz konusu eşyanın adliyenin eli altında bulundurulması zorunlu değildir:

* Eşyaya el konulup yediemine teslim edilebilir.
* Eşya mağdura ait ise, *ispat vasıtası olmamak veya ispat vasıtası ise
işlevini tamamlamış olmak koşulu ile* mağdura teslim edilebilir.
* Muhafaza imkanı yoksa elden çıkartılmasına karar verilebilir. Zira el koyma
tatbik edildiğinde eşyanın değerinin korunması ve bir zarara uğramaması
adliyenin yükümlülüğü altındadır. Bu karar soruşturmada hakim, kovuşturmada
mahkeme tarafından verilir. Her iki aşamada da hem cumhuriyet savcısının hem de
ilgilinin elden çıkartmaya ilişkin talep ve beyanları alınır. *Elden çıkartma
ancak müsadereye tabi eşya için söz konusu olur, ispat vasıtası hiçbir şekilde
elden çıkartılamaz.*

Kanunda el koyma kararına doğrudan itiraz imkanı düzenlenmemiştir. Soruşturma
evresinde bütün hakim kararları itiraz yoluna açık olduğundan el koyma kararına
veya el koyma emrinin onaylanmasına itiraz edilebilir. Kovuşturma evresinde ise
eşyanın iadesi istenip reddedilirse, ret kararına karşı itiraz yoluna
başvurulabilir.

Soruşturma veya kovuşturma herhangi bir biçimde bittiğinde el koyma son
bulacaktır. Soruşturma takipsizlikle bittiğinde elkonulan eşyanın iadesine
karar verilir. Kovuşturma beraat ile biterse de eşyanın iadesi söz konusu olur.
Kovuşturma mahkumiyet ile biterse el koyma işlemi müsadereye dönüşür.

.İçeriği devlet sırrı oluşturan belgelerde el koyma
****
Açıklanması, devletin dış ilişkilerine, milli savunmasına ve milli güvenliğine
zarar verebilecek; anayasal düzeni ve dış ilişkilerinde tehlike yaratabilecek
nitelikteki bilgiler, Devlet sırrı sayılır.

Bir belgenin içeriğinin devlet sırrı olduğu iddiası, belgeyi elinde tutan
kişiler bakımından her zaman ileri sürülebilir. *Ancak belgenin devlet sırrı
olup olmadığı tespiti mahkeme tarafından yapılacaktır*.

İleri sürülen sır iddiası, mahkeme tarafından yerinde görülmezse belge üzerine
el koyma kararı verilmesi mümkündür.

Sır iddiası yerinde görülürse, kanun, devlet sırlarının bir ceza muhakemesi
sürecinde ancak alt sınır 5 yıldan daha fazla bir cezayı öngören bir suçta
ispat işlevi görebileceğini düzenlemiştir. Söz konusu suçun daha az bir cezayı
öngörmesi halinde belgenin elde edilmesine de değerlendirilmesine de kanun
müsaade etmemektedir.
****

CAUTION: Şüpheli veya sanığın tanıklıktan çekinebilecek yakınlarıyla arasında
geçen yazışmalar ve bu kişiler nezdindeki belgeler el koyma kararının konusunu
oluşturamaz.

==== POSTADA EL KOYMA

*Suçun delillerini oluşturduğundan şüphe edilen ve gerçeğin ortaya çıkartılması
için soruşturma ve kovuşturmada adliyenin eli altında olması zorunlu sayılıp*,
posta hizmeti veren her türlü resmi veya özel kuruluşta bulunan gönderilere,
hakimin veya gecikmesinde sakınca bulunan hallerde cumhuriyet savcısının
kararı ile elkonulabilir.

CAUTION: Sadece ispat vasıtaları bakımından bu hüküm uygulanabilir. Müsadereye
tabi eşya bakımından uygulanamaz.

Hakim kararının veya cumhuriyet savcısının emrinin kendilerine bildirilmesi
üzerine elkoyma işlemini yerine getiren kolluk memurları, gönderilerin içinde
bulunduğu zarfları veya paketleri açamazlar. Elkonulan gönderiler, ilgili posta
görevlilerinin huzuru ile mühür altına alınıp derhal elkoyma kararını veya
emrini veren hakim veya Cumhuriyet savcısına teslim edilir.

TIP: Tehlikeli maddelerin izinsiz taşınması (silah dahil), uyuşturucu madde
imal ve ticareti, silah kaçakçılığı, tarihi eser kaçakçılığı suçlarında kolluk
görevlilerinin paketi açma yetkisi vardır.

Soruşturma ve kovuşturmanın amacına zarar vermek olasılığı bulunmadıkça,
alınmış tedbirler ilgililere bildirilir.

==== AVUKAT BÜROSUNDA ARAMA VE EL KOYMA

Avukata soruşturma açılması Adalet Bakanlığı'nın iznine tabidir. Dava
açılabilmesi Adalet Bakanı izniyle beraber yargılamanın yapılacağı yere en
yakın Ağır Ceza Mahkemesinin kararına bağlıdır. Yargılama yapacak mahkeme de
suç ne olursa olsun suçun işlendiği yerdeki Ağır Ceza Mahkemesidir.

Avukat büroları *ancak mahkeme kararı ile ve kararda belirtilen olayla ilgili
olarak cumhuriyet savcısının denetiminde* aranabilir. Baro başkanı veya onu
temsil eden bir avukat aramada hazır bulundurulur.

TIP: Avukatın konutu da yukarıdaki hükmün kapsamındadır.

Arama sonucu elkonulmasına karar verilen şeyler bakımından bürosunda arama
yapılan avukat, baro başkanı veya onu temsil eden avukat, bunların avukat ile
müvekkili arasındaki mesleki ilişkiye ait olduğunu öne sürerek karşı
koyduğunda, bu şey ayrı bir zarf veya paket içerisine konularak hazır
bulunanlarca mühürlenir ve bu konuda gerekli kararı vermesi, soruşturma
evresinde sulh ceza hakiminden, kovuşturma evresinde hakim veya mahkemeden
istenir.

Yetkili hakim elkonulan şeyin avukatla müvekkili arasındaki mesleki ilişkiye
ait olduğunu saptadığında, elkonulan şey derhal avukata iade edilir ve yapılan
işlemi belirten tutanaklar ortadan kaldırılır.

Yukarıdaki kararlar, 24 saat içinde verilir.

==== TAŞINMAZ MAL, HAK VE ALACAKLARA EL KOYMA

Soruşturma veya kovuşturma konusu suçun işlendiğine ve bu suçlardan elde elde
edildiğine dair kuvvetli şüphe sebebi bulunan hallerde, *şüpheli veya sanığa
ait*;

. Taşınmazlara
. Kara, deniz veya hava ulaşım araçlarına
. Banka veya diğer mali kurumlardaki her türlü hesaba
. Gerçek veya tüzel kişiler nezdindeki her türlü hak ve alacaklara
. Kıymetli evraka
. Ortağı bulunduğu şirketteki ortaklık paylarına
. Kiralık kasa mevcutlarına
. Diğer malvarlığı değerlerine

elkonulabilir. Bu taşınmaz, hak, alacak ve diğer malvarlığı değerlerinin
şüpheli veya sanıktan başka bir kişinin zilyetliğinde bulunması halinde dahi,
elkoyma işlemi yapılabilir. Bu hüküm ancak kanunda sayılan katalog suçlar için
söz konusudur.

IMPORTANT: Bu tip el koymaya ancak hakim karar verebilir.

==== ŞİRKET YÖNETİMİ İÇİN KAYYIM TAYİNİ

Suçun bir şirketin faaliyeti çerçevesinde işlenmekte olduğu hususunda kuvvetli
şüphe sebeplerinin varlığı ve *maddi gerçeğin ortaya çıkarılabilmesi için
gerekli olması halinde*; soruşturma ve kovuşturma sürecinde, hakim veya
mahkeme, şirket işlerinin yürütülmesiyle ilgili olarak kayyım atayabilir.
Atama kararında, yönetim organının yetkilerinin tümüyle kayyıma verildiği
açıkça belirtilir.

==== BİLGİSAYARLARDA, BİLGİSAYAR PROGRAMLARINDA VE KÜTÜKLERİNDE ARAMA, KOPYALAMA, ELKOYMA

Bir suç dolayısıyla yapılan soruşturmada, *başka surette delil elde etme
imkanının bulunmaması halinde*, Cumhuriyet savcısının istemi üzerine şüphelinin
kullandığı bilgisayar kütüklerinde arama yapılmasına, bilgisayar kayıtlarından
kopya çıkarılmasına, bu kayıtların çözülerek metin haline getirilmesine hakim
tarafından karar verilir.

Bilgisayar, bilgisayar programları ve bilgisayar kütüklerine şifrenin
çözülememesinden dolayı girilememesi veya gizlenmiş bilgilere ulaşılamaması
halinde çözüm yapılabilmesi ve gerekli kopyaların alınabilmesi için, bu araç ve
gereçlere el konulabilir. Şifrenin çözümünün yapılması ve gerekli kopyaların
alınması halinde, elkonulan cihazlar gecikme olmaksızın iade edilir.

== GİZLİ SORUŞTURMA TEDBİRLERİ

=== TELEKOMÜNİKASYONUN DENETLENMESİ

Bir suç dolayısıyla yapılan soruşturma ve kovuşturmada, *suç işlendiğine
ilişkin somut delillere dayanan kuvvetli şüphe sebeplerinin varlığı* ve *başka
suretle delil elde edilmesi imkanının bulunmaması* durumunda, hakim veya
gecikmesinde sakınca bulunan hallerde Cumhuriyet savcısının kararıyla *şüpheli
veya sanığın* telekomünikasyon yoluyla iletişimi dinlenebilir, kayıt altına
alınabilir ve sinyal bilgileri değerlendirilebilir.

Cumhuriyet savcısı kararını *derhal* hakimin onayına sunar ve kararını en geç
yirmi dört saat içinde verir. Sürenin dolması veya hakim tarafından aksine
karar verilmesi halinde tedbir Cumhuriyet savcısı tarafından derhal kaldırılır.

Tedbir kararı *en çok iki ay* için verilebilir; bu süre, bir ay daha
uzatılabilir. Ancak, *örgütün faaliyeti çerçevesinde işlenen suçlarla ilgili
olarak gerekli görülmesi halinde*, hakim yukarıdaki sürelere ek olarak her
defasında bir aydan fazla olmamak ve toplam üç ayı geçmemek üzere uzatılmasına
karar verebilir.

Tedbirin konusu telekomünikasyon araçları kullanmak suretiyle, sanık veya
şüpheli ile üçüncü kişi arasında *devam eden* bir iletişimdir.

Telekomünikasyonun yoluyla iletişimin denetlenmesinde beş işleme müsaade
edilir:

. Dinleme
. Kaydetme
. Sinyal bilgilerin değerlendirilmesi
. Yer tespiti
. Kimlik tespiti

NOTE: Dinleme, kaydetme ve sinyal bilgilerinin değerlendirilmesi ancak kanunda
sayılan katalog suçlar için söz konusu olabilir.

Kuvvetli suç şüphesi ve başka şekilde elde etme imkanı olup olmadığı her suç
bakımından ayrı ayrı denetlenmek zorunda olunduğuna göre, suç vasfı
değiştiğinde tedbire son verilmesi icap eder. Yargıtay, suç vasfı değiştiye ve
yeni suç katalogda yer alan suçlardansa elde edilmiş delillerin
kullanılabileceğini kabul etmektedir. Yeni suç katalog dışındaysa ama
katalogdaki suçlardan birine dönüşebilecek nitelikte ise yine deliller
kullanılabilir.

Sanık veya şüphelinin, tanıklıktan çekinebilecek yakınlarından biri ile olan
iletişimi dinlenemez. Dinlense ve kaydedilse bile silinmesi gerekir. Ancak
Yargıtay'a göre, sanık veya şüphelinin konuştuğu yakını da suçtan şüpheli ise
bu yasak uygulanmaz. Zira şüpheli veya sanıklar birbirlerinin fiilleri hakkında
tanık sıfatıyla dinlenebilirler.

Mevcut dinleme sırasında bir başka suça ilişkin bilgi edinilirse ve bu suç
katalogdaki suçlardansa o ana kadar yapılan dinleme hukuka uygundur, ancak
devam etmek için yeni bir karar almak gerekir. Suç katalogda yer almıyorsa, bu
dinleme ile elde edilen bilgiler delil olarak kullanılmayacaktır. Ancak delilin
kullanılamaması, fiili bildirme yükümlülüğünü ortadan kaldırmaz.

=== GİZLİ SORUŞTURMACI

Soruşturma konusu suçun işlendiği hususunda *somut delillere dayanan kuvvetli
şüphe sebeplerinin bulunması* ve *başka suretle delil elde edilememesi*
halinde, kamu görevlileri gizli soruşturmacı olarak görevlendirilebilir. Bu
görevlendirmeye *hakim* karar verir.

Soruşturmacının kimliği değiştirilebilir. Bu kimlikle hukuki işlemler
yapılabilir. Kimliğin oluşturulması ve devam ettirilmesi için zorunlu olması
durumunda gerekli belgeler hazırlanabilir, değiştirilebilir ve kullanılabilir.

Soruşturmacı, faaliyetlerini izlemek ile görevlendirildiği örgüte ilişkin her
türlü araştırmada bulunmak ve bu örgütün faaliyetleri çerçevesinde işlenen
suçlarla ilgili delilleri toplamakla yükümlüdür.

Soruşturmacı, görevini yerine getirirken suç işleyemez ve görevlendirildiği
örgütün işlemekte olduğu suçlardan sorumlu tutulamaz.

Soruşturmacı görevlendirilmesiyle suretiyle elde edilen kişisel bilgiler,
görevlendirildiği ceza soruşturması ve kovuşturması dışında kullanılamaz. Suçla
bağlantılı olmayan kişisel bilgiler derhal yok edilir.

IMPORTANT: Soruşturmacı, kamu görevlisi olmak zorundadır.

=== TEKNİK ARAÇLA İZLEME

Kanunda sayılmış katalog suçların *işlendiği hususunda somut delillere dayanan
kuvvetli şüphe sebepleri bulunması* ve *başka suretle delil elde edilememesi*
halinde, *şüpheli veya sanığın* kamu açık yerlerdeki faaliyetleri ve işyeri
teknik araçla izlenebilir, ses veya görüntü kaydı alınabilir.

Teknik araçlarla izlemeye hâkim, gecikmesinde sakınca bulunan hâllerde
Cumhuriyet savcısı tarafından karar verilir. Cumhuriyet savcısı tarafından
verilen kararlar yirmi dört saat içinde hâkim onayına sunulur. Hâkim kararını
en geç yirmi dört saat içinde verir. Sürenin dolması veya hâkim tarafından
aksine karar verilmesi hâlinde kayıtlar derhâl imha edilir.

Teknik araçlarla izleme kararı *en çok üç haftalık* süre için verilebilir. Bu
süre gerektiğinde *bir hafta daha* uzatılabilir. Ancak, *örgütün faaliyeti
çerçevesinde işlenen suçlarla ilgili olarak gerekli görülmesi hâlinde*, hâkim
yukarıdaki sürelere ek olarak her defasında bir haftadan fazla olmamak ve
toplam dört haftayı geçmemek üzere uzatılmasına karar verebilir.

NOTE: Teknik araçlarla izleme tedbiri ile birlikte gizli soruşturmacı
görevlendirilmesi halinde bu süreler bir kat artırılarak uygulanır.

Elde edilen deliller, yukarıda sayılan suçlarla ilgili soruşturma ve kovuşturma
dışında kullanılamaz; ceza kovuşturması bakımından gerekli olmadığı taktirde
Cumhuriyet savcısının gözetiminde derhâl yok edilir.

IMPORTANT: Bu hükümler, kişinin konutunda uygulanamaz.

== GÖZLEM ALTINA ALMA

*Gözlem altına alma*, bir kişinin akıl hastası olup olmadığını, akıl hastasıysa
ne kadar süredir akıl hastası olduğunu ve hastalığının kişinin fiillerine
etkisini tespit etmeye yarayan bir tedbirdir. Bu tedbirin uygulanabilmesi için
kişinin fiili işlediği hususunda kuvvetli suç şüphesinin olması ve bu kişinin
akıl hastalığı şüphesinin olması gerekir.

Gözlem altına alma ile akıl hastalığının fiilden önce mi sonra mı akıl hastası
olduğunun tespiti önemlidir. Fiilden önce akıl hastası olduğu tespiti yapıldığı
takdirde bu *kusuru etkileyen faktör* olur. Fiil gerçekleştikten sonra
*hastalığa düçar olunması* halinde ise muhakeme şartlarının oluşmamasına sebep
olur.

Gözlem süresi *üç haftayı geçemez*. Bu sürenin yetmeyeceği anlaşılırsa resmi
sağlık kurumunun istemi üzerine, her seferinde *üç haftayı geçmemek üzere* ek
süreler verilebilir; ancak sürelerin toplamı *üç ayı geçemez*.

== BEDEN MUAYENESİ

Bir suça ilişkin delil elde etmek için *şüpheli* veya *sanık* üzerinde iç beden
muayenesi yapılabilmesine ya da vücuttan kan veya benzeri biyolojik örneklerle
saç, tükürük
