:icons: font

== 29.12.2016 tarihli pratik çalışma

Bay M, 1995 yılında ölümünde torunları A ile B’ye Esenyurt’ta tapulu bir arazi
bırakmıştır.  Aynı yıl imar düzenlemeleri nedeniyle taşınmaz 110 ve 111
numaralı iki parsele bölünerek söz konusu parseller için eski tapu iptal
edilmeden yeni tapu sahifeleri ihdas edilmiştir. A ve B, 2005 yılında 111
numaralı parseli bölgede fabrika kurmak isteyen F’ye satarak onun adına tescil
ettirirler. F, 2005 yılında bu parselde G lehine geçit hakkı kurar. Ayrıca F,
aynı sene noterde yapılan bir sözleşme ile 111 nolu parsel için S lehine
taşınmaz satış vaadinde bulunur.  Satış vaadi sözleşmesi tapuya şerh edilir.
Tüm bunlardan haberi olmayan C, eski tapu sayfasını inceledikten sonra her iki
parsel için A ve B’ye oldukça cazip bir fiyat teklif ederek almak istediğini
söyleyince A ve B bu teklifi kabul ederek satışı ve C üzerine tescili
gerçekleştirirler.

Akşehir’de çiftçilikle uğraşan H, 2005 yılında komşusu İ’ye bir aylığına tarım
ilaçlama makinesini kiralayarak teslim etmiştir. Bir ayın sonunda ekonomik
sıkıntıya giren H, İ’yi arayarak borç para ister ve ilaçlama makinesinin borca
karşılık kendisinde rehin olarak kalabileceğini söyler, İ de bu teklifi kabul
eder. L, bir gece gizlice ilaçlama makinesini İ’nin bahçesinden çalar.
Makinenin fark edilmemesi için başka bir renge boyatan L, 2011 yılına
gelindiğinde makinenin bazı bozuk parçalarını yeniler ve makinenin pompasını
daha büyük hazneli bir pompa ile değiştirir. Daha sonra da makineyi, Eğirdir’de
kurulan ve ikinci el çiftlik malzemelerinin de satıldığı bir pazarda, orada
yaşayan N’ye satar ve teslim eder. Bu arada Beşiktaş’taki bir taşınmaza A %10,
kardeşi B %20, kuzenlerinden S %30 ve T de %40 paylarla birlikte maliktirler.
Bu kişilerin aralarında yaptıkları sözleşmeye göre “taşınmazla ilgili işlem
yapılması, önlem alınması ya da masraf yapılması vs.  her türlü konuda alınacak
kararlar, çifte çoğunlukla alınır.” Bir müddet sonra S ile T, A ile B’nin karşı
çıkmasına rağmen taşınmazı K’ya kiralarlar.

. Taşınmaz üzerinde A ile B, F ve C mülkiyet hakkı, G geçit hakkı kazanmış
mıdır?  Açıklayınız.

. S, lehine yapılan satış vaadinin şerh edilmiş olması karşısında, bu yerin
satılmasını A, B veya C’ye ileri sürmek hakkına sahip midir?

.  Durumun düzeltilmesi için hangi hukuki yola kim/kimler tarafından
başvurulmak gerekir?  Dava açılması söz konusu ise kimlere karşı dava
açılacağını ve dava sonunda verilen kararı, hukuki niteliğini de belirterek
açıklayınız.

. Bu durum karşısında kimlerin hangi zararlarını, kim/ kimlerden talep
edebileceklerini olayın koşullarını da dikkate alarak açıklayınız.

. İ, ilaçlama makinesinin zilyetliğini kazanmış mıdır? Açıklayınız.

. N’ye karşı taşınır davası açılması mümkün müdür? Koşulları ve kimlerin
talepte bulunabilme imkânına sahip olduğunu da belirterek açıklayınız.

. Dava sırasında N’nin avukatının, “Sayın Mahkemenin ilaçlama makinesini iade
etmemize karar vermesi halinde, müvekkilim N’nin ödediği bedelin tarafımıza
iade edilmesini ve yapılan tüm masrafların tazmin edilmesini istiyoruz”
yolundaki talebi karşısında, siz hâkim olsaydınız nasıl bir karar verirdiniz?
Gerekçesi ile açıklayınız.

. Beşiktaş’taki taşınmaz ile ilgili olarak A ile B, K’ya karşı el atmanın
önlenmesi davası açabilirler mi? Hâkimin, tarafların aralarındaki sözleşmeye
göre A ile B’nin bu davayı açamayacağı gerekçesi ile davayı reddetmesi mümkün
müdür? Açıklayınız.
