:icons: font
:toc:
:toc-title: TAŞINMAZ MÜLKİYETİ II. DÖNEM

== TAŞINMAZLARLA İLGİLİ İŞLEMLERDE RASTLANAN ÖZEL DURUMLAR

=== MUVAZAA

Muvazaa bilinçli olarak iç iradeden farklı bir şeyin dış iradeye
yansıtılmasıdır. Muvazaanın olması için öncelikle taraflar arasında *muvazaa
anlaşması* yapılması gerekir. Muvazaa anlaşması tarafların _aslında hiç
yapmadıkları işlemi görünüşte yapmış gibi görünmek_ (*adi muvazaa*) ya da
_gerçekte yapmak istedikleri işlemden farklı bir işlemi yapmış gibi görünmek_
(*nitelikli muvazaa*) hususunda anlaşmaları ile yapılır.

*Kanun tarafların gerçek iradelerine hüküm bağladığı için görünüşteki işlem
geçersiz, gizli işlem geçerlidir*. Ancak taşınmazlarda devir borcu doğuran
sözleşmelerde devir işlemleri resmi şekle bağlıdır ve tapuda yapılır. Bu şekil
şartı sadece tapu memurunun imzasını değil, o sözleşmenin diğer unsurlarını da
içerir. *Nitelikli muvazaa taşınmazlara ilişkin olduğunda gizli işlem de şekil
şartlarını sağlamadığı için geçersiz olacaktır.*

NOTE: Taşınırlarda şekil şartı olmadığı için eğer bir taşınır muvazaalı olarak
bağışlanmış ve satış olarak gösterilmişse bağışlamanın geçerli olduğunu
söylemek gerekir.

=== İNANÇLI İŞLEM

İnançlı işlemin iki türü vardır:

. *Saf inançlı işlem*: Belli bir işin yaptırılması için bir taşınır ya da
taşınmazın idari ya da başka bir amaçla bir kişiye devredilmesi ve o amaç
gerçekleştiğinde geri alınması
. *Karma inançlı işlem*: Bir kişiden borç alındığında bunun teminatı olarak
rehin hukukunun araçları yerine mülkiyetin kendisini teminat olarak kullanmak

İki türün de konusu taşınmaz, taşınır veya hak (senet vs.) olabilir.

İnançlı işlemin ilk safhası **inanç anlaşması**dır. İnanç anlaşması bir
borçlandırıcı işlemdir. İkinci safha ise **taşınmaz devri**dir. Taşınmaz
devrinin hukuki sebebi inanç anlaşmasıdır.

[NOTE]
====
Taşınmazın iş yapıldıktan veya borç ödendikten sonra iade edilmesi lazımdır.
Ancak inanç anlaşması tapuda yapılamamaktadır. Taşınmaz inanç anlaşması
çerçevesinde iade edilmezse ne olur?

Yargıtay, 1947 tarihli bir içtihadı birleştirme kararına dayanarak tapuda satış
olarak görünüyor olsa bile taraflar bu satıştan önce veya aynı gün adi yazılı
şekilde yapılmış bir inanç anlaşmasının varlığını belgeleyebilirlerse işlemin
inançlı işlem olduğunu ve iade borcu doğduğunu kabul etmektedir.
====

[CAUTION]
====
Sözleşmeye "_borç ödenmediği takdirde taşınmaz alacaklıda kalacaktır_" şeklinde
bir hüküm koyulmuşsa bu hüküm geçersizdir (*Lex Commissoria yasağı*). Borç
ödenmediği takdirde verilen teminatın alacaklıda kalmasına dair anlaşmalar Roma
Hukukundan beri yasaktır. *Teminat mutlaka paraya çevrilecektir*. Sözleşmede
böyle bir hükmün bulunması TBK 27/2 uyarınca __kısmi butlan__a yol açar. Ancak
borcun vadesi geldikten sonra taraflar _ifa yerine edim_ anlaşması yapabilirler,
buna bir engel yoktur. 

Başlangıçta yapılan tüm rayiç anlaşmaları da bu yasağın içine girer ve mutlaka
borcun vadesinin geldiği tarihteki rayiç üzerinden hesaplama yapılmalıdır. Aksi
_lex commisoria_ yasağına aykırıdır.
====

İnançlı devir, inanç anlaşması çerçevesinde yapılan bir devirdir. İnanç
anlaşması bir borçlandırıcı işlemdir ve iade borcu doğurur. Bu anlaşma sözleşme
olması itibari ile nisbi etki doğurur. Taşınmazı devralan kişi taşınmazın
malikidir ve taşınmaz üzerinde tüm tasarrufları yapabilir. Taşınmazı bir üçüncü
kişiye satması durumunda bu satışa engel hiçbir durum yoktur. Ancak inanç
anlaşması çerçevesinde taşınmazı devreden kişiye karşı sözleşmeden doğan
sorumlulukları devam etmektedir. Taşınmazın yeni malikinin iyiniyetli olup
olmamasının bir önemi yoktur, zira burada bir yolsuz tescil yoktur. Yeter ki
TBK 49/2 uyarınca kasten zarar vermek için hareket etmiş olmasın.

== TAŞINMAZ SATIŞ VAADİ

Taşınmaz satış vaadi bir **ön sözleşme**dir. Ön sözleşmenin ifası, asıl
sözleşmenin yapılmasıdır. Bu sözleşmeyle hem alıcı hem de satıcı olan vaatte
bulunabileceği gibi taraflardan sadece biri de vaatte bulunabilir. Satış
vaadinin satma ve alma şeklinde tanıdığı hak bir yenilik doğuran haktır. Bu hak
kullanıldığında karşı taraf bir borç altına girecektir.

Taşınmazlarda ayni hak devri borcu doğuran bütün sözleşmeler resmi şekle
tabidir. Resmi şekli sağlayacak makam tapu memuru veya noterdir. 

Taşınmaz satış vaadinden doğan borç, satışı ve tescili yapma borcudur.
Mahkemenin vereceği karar satışın yapılması gerektiğine dair bir hüküm
olmalıdır. Bu karardan sonra satıcı tescil yapmaya yanaşmıyor ise tescil için
ikinci bir dava açılmalıdır. Burada iki dava açılması meşakatli bir yol olduğu
için Yargıtay tek bir dava açılarak hem satışın yapılmasına hem tesciline karar
verilir diyor.

Taşınmaz satış vaadinden doğan hak *şerh edilebilir* bir haktır. Hatta kanun
tek taraflı şerh konulması imkanı tanımıştır. Yani bir şerh anlaşmasına gerek
duymaksızın satış vaadi sözleşmesinin alıc veya satıcı tarafı tek başına
giderek şerhi sağlayabilir. *Şerhin etkisi 5 yıldır*. 

== TAPUSUZ TAŞINMAZLARDA MÜLKİYET DEVRİ

Tapusuz taşınmazlarda mülkiyet devri yapılabilmesi için, taşınmazsa mülkiyet
hakkının varlığı kanıtlanmış olmalıdır. Tapusuz taşınmazların mülkiyeti
Kadastro Kanununa göre 20 yıl boyunca, malik sıfatıyla, çekişmesiz olarak
zilyetliği sürdüren kişiye aittir. Bu tescil dışı bir kazanımdır. 

Tapusuz taşınmazların devri de MK 706 gereği resmi şekle tabidir. Dolayısıyla
devri sağlamak için mutlaka tapuda önce malik adına tescil yapılmalı,
sonrasında da devir işlemi gerçekleştirilmelidir.

Uygulamada tapusuz taşınmazlar *harici satım* senedi denilen senetlerle
devredilmektedir. Burada mülkiyet devri yoktur, zilyetliğin devri söz
konusudur. Tapusuz taşınmazlarda zilyetlik adi yazılı veya resmi bir sözleşme
ile devredilebilir.

== TESCİL DIŞI KAZANIM

====
*MK 705*: (1) Taşınmaz mülkiyetinin kazanılması, tescille olur.

(2) Miras, mahkeme kararı, cebrî icra, işgal, kamulaştırma hâlleri ile kanunda
öngörülen diğer hâllerde, mülkiyet tescilden önce kazanılır. Ancak, bu hâllerde
malikin tasarruf işlemleri yapabilmesi, mülkiyetin tapu kütüğüne tescil edilmiş
olmasına bağlıdır. 
====

MK 705 sicil dışı kazanımı düzenleyen genel hükümdür. MK 705 sınırlayıcı
değildir. MK'da görülen diğer haller de sicil dışı kazanım olarak ortaya
çıkabilir. MK 705'de öngörülen haller:

* *Miras*: Ölümle birlikte _külli halefiyet_ kendiliğinden ortaya çıkmaktadır.
Ölenin tüm hak ve borçları ölüm anında mirasçılarına geçer. Ölümle birlikte
ölenin tüm taşınmazları da sicil dışı olarak mirasçılara geçmektedir.
+
[CAUTION]
====
Bir kişinin mirasçı olarak atanması durumunda ölüm ile birlikte taşınmazlar
sicil dışı kazanılacaktır. Ancak _vasiyet alacaklısı_ olarak atanması durumunda
ölüm ile birlikte taşınmaz kendiliğinden kazanılmaz. Vasiyet alacaklısı kişi
ölenin mirasçılarına alacak davası açarak taşınmazın kendine devrini talep
edecektir. Bu devrin yapılması ile taşınmaz tescil ile kazanılmış olur.
====
* *Mahkeme kararı*: Bir taşınmazda ayni hak devri borcu doğuran bir sözleşme
ifa edilmediği takdirde, mahkemeden mülkiyetin MK 716'ya göre geçirilmesi talep
edilebilir. Bu durumda mahkemenin verdiği karar mülkiyeti geçiren yenilik
doğuran bir karardır. Bu karardan sonra yapılan tescil açıklayıcıdır.
+
[caption=""]
.Tescili isteme hakkı
====
*TMK 716*: (1) Mülkiyetin kazanılmasına esas olacak bir hukukî sebebe dayanarak
malikten mülkiyetin kendi adına tescilini istemek hususunda kişisel hakka sahip
olan kimse, malikin kaçınması hâlinde hâkimden, mülkiyetin hükmen geçirilmesini
isteyebilir.

(2) Bir taşınmazın mülkiyetini işgal, miras, kamulaştırma, cebrî icra veya
mahkeme kararına dayanarak kazanan kişi tescili doğrudan doğruya yaptırabilir.

(3) Bir taşınmazın mülkiyetinde eşler arasındaki mal rejimi dolayısıyla meydana
gelen değişiklikler, eşlerden birinin istemiyle tapu kütüğüne doğrudan tescil
olunur.
====
* *Cebri icra*: Haciz, rehnin paraya çevrilmesi veya iflas yoluyla takipte
birinin taşınmazı üzerinde haciz işlemi uygulatıp satış yapıldığında ihale
bittiği anda ihaleyi kazanan kişi sicil dışı mülkiyet sahibi olur.
* *İşgal*: İşgal bir yere el atma, orada bir hakimiyet kurmadır. İşgal yolu ile
mülkiyet kazanımı tapulu olup mülkiyet hakkı terkin edilmiş bir taşınmaz
olmalıdır.
+
NOTE: Mülkiyet hakkının terkin edilmiş olması sınırlı ayni hakları etkilemez.
İşgal yoluyla mülkiyeti kazanan kişi sınırlı ayni hakları tanımak zorundadır.
* *Kamulaştırma*

== TAŞINMAZLARDA ZAMANAŞIMI İLE MÜLKİYET KAZANIMI

=== OLAĞAN ZAMANAŞIMI İLE KAZANIM

[caption=""]
.Olağan zamanaşımı
====
*TMK 712*: Geçerli bir hukukî sebep olmaksızın tapu kütüğüne malik olarak
yazılan kişi, taşınmaz üzerindeki zilyetliğini davasız ve aralıksız olarak on
yıl süreyle ve iyiniyetle sürdürürse, onun bu yolla kazanmış olduğu mülkiyet
hakkına itiraz edilemez.
====

Şartları: 

. *Tapulu* bir taşınmaz olacak
. Tapudaki kayıt *yolsuz* olacak
. Zamanaşımı ile kazandığını iddia eden tapuda *malik olarak* görünecek
. Taşınmazda *10 yıl* süre ile *malik sıfatıyla* ve *aralıksız* zilyet olacak
+
TIP: Eğer kişi sürenin başında ve sonunda zilyetse karine olarak o süre boyunca
da zilyet kabul edilir. Küçük ara vermeler aralıksız olma şartını bozmaz.
. Bu 10 yıl *davasız* geçecek
+
NOTE: Zilyetliğin davasız olma şartı kendisine karşı dava açılmamış olmasıdır.
Bu dava kural olarak istihkak davası niteliğinde tapu kaydının düzeltilmesi
davasıdır. İstihkak davası niteliğinde olmayan bir dava, davasız olma şartını
bozmaz.
. Kişi *iyiniyetli* olacak
+
TIP: İstihkak davası dışında bir dava davasızlık şartını bozmazsa da iyiniyet
durumunu bozabilir. İyiniyet yolsuz kaydın konulmasından 10 yılın dolmasına
kadar bütün süreçte bulunması gereken bir şarttır.

Bu şartların varlığı halinde 10 yılın sonunda kanun gereği yolsuz kayıt
düzelerek hukuka uygun hale gelir. Artık malik aleyhine tapu kaydının
düzeltilmesi davası açılsa bile bu davanın reddedilmesi gerekir. Kişinin
tescilin yolsuz olduğu andan itibaren malik olarak kabul edilmesi gerektiği
kabul edilir.

=== OLAĞANÜSTÜ ZAMANAŞIMI İLE KAZANIM

[caption=""]
.Olağanüstü zamanaşımı
====
*TMK 713*: (1) Tapu kütüğünde kayıtlı olmayan bir taşınmazı davasız ve
aralıksız olarak yirmi yıl süreyle ve malik sıfatıyla zilyetliğinde bulunduran
kişi, o taşınmazın tamamı, bir parçası veya bir payı üzerindeki mülkiyet
hakkının tapu kütüğüne tesciline karar verilmesini isteyebilir.

(2) Aynı koşullar altında, maliki tapu kütüğünden anlaşılamayan veya yirmi yıl
önce (…)(1) hakkında gaiplik kararı verilmiş bir kimse adına kayıtlı bulunan
taşınmazın tamamının veya bölünmesinde sakınca olmayan bir parçasının zilyedi
de, o taşınmazın tamamı, bir parçası veya bir payı üzerindeki mülkiyet hakkının
tapu kütüğüne tesciline karar verilmesini isteyebilir.

(3) Tescil davası, Hazineye ve ilgili kamu tüzel kişilerine veya varsa tapuda
malik gözüken kişinin mirasçılarına karşı açılır.

(4) Davanın konusu, mahkemece gazeteyle bir defa ve ayrıca taşınmazın bulunduğu
yerde uygun araç ve aralıklarla en az üç defa ilân olunur.

(5) Son ilândan başlayarak üç ay içinde yukarıdaki koşulların gerçekleşmediğini
ileri sürerek itiraz eden bulunmaz ya da itiraz yerinde görülmez ve davacının
iddiası ispatlanmış olursa, hâkim tescile karar verir. Mülkiyet, birinci
fıkrada öngörülen koşulların gerçekleştiği anda kazanılmış olur.

(6) Davalılar ve itiraz edenler, aynı davada kendi adlarına tescile karar
verilmesini isteyebilirler.

(7) Kararda, tescili istenilen taşınmazın niteliği, yeri, sınırları ve
yüzölçümü belirtilir ve karara, uzmanlarca düzenlenen teknik bilgileri içeren
krokisi de eklenir.

(8) Özel kanun hükümleri saklıdır.
====

<<<

==== TAPUSUZ TAŞINMAZLARDA OLAĞANÜSTÜ ZAMANAŞIMI İLE KAZANIM

[caption=""]
.Tapuda kayıtlı olmayan taşınmaz malların tespiti
====
*Kadastro Kanunu 14*: (1) Tapuda kayıtlı olmayan ve aynı çalışma alanı içinde
bulunan ve toplam yüzölçümü sulu toprakta 40, kuru toprakta 100 dönüme kadar
olan (40 ve 100 dönüm dahil) bir veya birden fazla taşınmaz mal, çekişmesiz ve
aralıksız en az yirmi yıldan beri malik sıfatıyla zilyetliğini belgelerle veya
bilirkişi veyahut tanık beyanlarıyla ispat eden zilyedi adına tespit edilir.

(2) Sulu veya kuru arazi ayrımı, Toprak Koruma ve Arazi Kullanımı Kanunu
hükümlerine göre yapılır.

(3) 4342 sayılı Mera Kanununun 7 nci maddesinin üçüncü fıkrası gereği 3402
sayılı Kanun hükümlerine göre yapılacak işlemlerde Kadastro Komisyonlarına konu
uzmanı Ziraat Mühendisi dâhil edilir.

(4) Taşınmaz malın, yukarıdaki fıkranın kapsamı dışında kalan kısmının zilyedi
adına tespit edilebilmesi için, birinci fıkra gereğince delillendirilen
zilyetliğin ayrıca aşağıdaki belgelerden birine dayandırılması lazımdır.

.. 31/12/1981 tarihine veya daha önceki tarihlere ait vergi kayıtları,
.. Tasdikli irade suretleri ile fermanlar,
.. Muteber mütevelli, sipahi, mültezim temessük veya senetleri,
.. Kayıtları bulunmayan tapu veya mülga hazinei hassa senetleri veya muvakkat
tasarruf ilmuhaberleri,
.. Tasdiksiz tapu yoklama kayıtları,
.. Mülkname, muhasebatı atika kalemi kayıtları,
.. Mubayaa, istihkam ve ihbar hüccetleri,
.. Evkaf idarelerinden tapuya devredilmemiş tasarruf kayıtları. 
====

Tapusuz taşınmazlar için MK 713 ve Kadastro Kanunu 14 uygulanır. Hatta MK
713'ün devre dışı kaldığı söylenebilir. Tapusuz taşınmazlar bakımından şartları
belirleyen Kadastro Kanunudur ve Kadastro Kanunu yürürlükten kalkana kadar
böyle devam edecektir. Bunun kadastro yapılmasıyla ilgisi yoktur. Kadastro
yapılmayan yerlerde de Kadastro Kanunu 33 gereği Kadastro Kanunu 14 uygulanır.

Sulu toprakta 40, kuru toprakta 100 dönüme kadar olan yerler sınırdır. Bir kişi
zamanaşımı ile ancak bu kadar kazanabilir. MK 713'te böyle bir sınır yoktur.

20 yıl bir zamanaşımı süresi olduğu için hesaplanması TBK'daki zamanaşımı
sürelerinin hesaplanmasına ilişkindir. 

Zilyetlik devir yoluyla geçmiş ise ve geçerli bir hukuki sebep varsa zilyetliği
devralan kendisine devredenin zilyetlik süresinden faydalanabilir.

Davasız olma şartı burada da geçerlidir. Ancak dava dışında zilyetliğin
zamanaşımı ile kazandırmasını engellemez, zira olağanüstü zamanaşımı ile
kazanımda iyiniyet şartı yoktur. Kişi taşınmazın başkasına ait olduğunu bilse
dahi, tapusuz taşınmaza 20 yıl boyunca davasız zilyet olmuşsa mülkiyeti
kazanır.

[NOTE]
====
Taşınmazda 15 yıldır zilyet olan kişi olağanüstü zamanaşımı ile mülkiyeti
kazanmış olduğu iddiası ile mahkemeye başvurur ve taşınmazın kendisi adına
tescilini isterse dava reddedilecektir. Zira olağanüstü zamanaşımı ile kazanım
için gerekli süre 20 yıldır. Bu durumda aynı kişi 5 yıl sonra tekrar dava
açabilir mi?

Bu problem 2007 tarihli bir içtihadı birleştirme kararı ile çözülmüştür.
Yargıtay, davanın süre şartı dolmadığı için reddi halinde yeni bir 20 yıllık
süreye ihtiyaç duyulacağını, sürenin baştan başlayacağını kabul etmiştir.
====

Kadastro çalışmasında kişi hakkını sulu arazide 40, kuru arazide 100 dönüme
kadar bilirkişi ve tanık beyanıyla ispat ettiği takdirde önce tutanağa
geçirilir, sonrasında da itiraz edilmezse tutanaklar tapuya dönüştürülür. 

Kadastro teknisyeni şartların varlığına ikna olursa tutanağa yazar. Şartların
gerçekleşmemişse dava açılır ve mahkeme kararı ile kesin çözüme bağlanır.

IMPORTANT: Bir kadastro bölgesinde, kadastro kesinleştikten sonra kadastro
öncesi bir hukuki sebebe dayanarak dava açılması için 10 yıllık bir hak
düşürücü süre tanınmıştır.

Kadastro çalışması dışında, 20 yıl boyunca tapusuz taşınmaza zilyet olmuş kişi
taşınmazın kendisine tescili için MK 713 uyarınca dava açmalıdır. 

NOTE: 1998 tarihli bir içtihadi birleştirme kararında Yargıtay mahkemenin
kararının kurucu olduğunu kabul etmiştir. Doktrinde bu karar çokça
eleştirilmiş, 20 yıllık zilyetlik aranan şartlarda dolduğu anda mülkiyetin
kazanıldığı savunulmuştur.

[caption=""]
.Hazine adına tespit
====
*Kadastro Kanunu 18*: (1) Yukarıdaki maddelerin hükümleri dışında kalan ve
tescile tabi bulunan taşınmaz mallar ile tarım alanına dönüştürülmesi veya
ekonomik yarar sağlanması mümkün olan yerler Hazine adına tespit olunur.

(2) Orta malları, hizmet malları, ormanlar ve Devletin hüküm ve tasarrufu
altında olup da bir kamu hizmetine tahsis edilen yerler ile kanunları uyarınca
Devlete kalan taşınmaz mallar, tapuda kayıtlı olsun olmasın kazandırıcı
zamanaşımı yolu ile iktisap edilemez.
====

[caption=""]
.İhya edilen taşınmaz mallar
====
*Kadastro Kanunu 17*: (1) Orman sayılmayan Devletin hüküm ve tasarrufu altında
bulunan ve kamu hizmetine tahsis edilmeyen araziden, masraf ve emek sarfı ile
imar ve ihya edilerek tarıma elverişli hale getirilen taşınmaz mallar 14 üncü
maddedeki şartlar mevcut ise imar ve ihya edenler veya halefleri adına, aksi
takdirde hazine adına tespit edilir.

(2) İl, ilçe ve kasabaların imar planının kapsadığı alanlarda kalan taşınmaz
mallarda bu hüküm uygulanmaz. 
====

== TAŞINMAZ MÜLKİYETİNİN KAPSAMI

[caption=""]
.Kapsam
====
*MK 718*: (1) Arazi üzerindeki mülkiyet, kullanılmasında yarar olduğu ölçüde,
üstündeki hava ve altındaki arz katmanlarını kapsar.

(2) Bu mülkiyetin kapsamına, yasal sınırlamalar saklı kalmak üzere yapılar,
bitkiler ve kaynaklar da girer.
====

Arazi sınırları belirlenmiş yeryüzü parçasıdır. Sınırların belirlenmesi MK
719'da düzenlenmiştir.

[caption=""]
.Sınırların belirlenmesi
====
*MK 719*: (1) Taşınmazın sınırları, tapu plânları ve arz üzerindeki sınır
işaretleriyle belirlenir.

(2) Tapu plânları ile arz üzerindeki işaretler birbirini tutmazsa, asıl olan
plândaki sınırdır. Bu kural, yetkili makamlarca heyelân bölgesi olduğu
belirlenen yörelerde uygulanmaz.
====

Tapudaki belgeler arasında harita ya da plan denilen krokiler vardır. Bu
krokiler taşınmazın sınırını belli eden en önemli belgelerdir. Kural sınırların
krokiye göre belirlenmesidir. Eğer krokiye göre belirlenen sınıra bir başkası
tecavüz ediyorsa, mülkiyet hakkına dayanan *el atmanın önlenmesi davası* tecavüz
önlenir. Eğer tapuda bir yanlışlık varsa, kroki yanlış olduğu için yüzölçümü
sınırları tapuya yanlış geçirilmişse o zaman da mülkiyet hakkına dayanan *tapu
kaydının düzeltimesi davası* açılacaktır.

[caption=""]
.Sınır belirleme yükümlülüğü
====
*MK 720*: (1) Her arazi maliki, komşusunun istemi üzerine belli olmayan
sınırların belirlenmesi için tapu plânlarının düzeltilmesine veya arz üzerine
sınır işaretleri konulmasına katkıda bulunmakla yükümlüdür.
====

=== HAKSIZ YAPI

[caption=""]
.Mülkiyet ilişkisi
====
*MK 722*: (1) Bir kimse kendi arazisindeki yapıda başkasının malzemesini ya da
başkasının arazisindeki yapıda kendisinin veya bir başkasının malzemesini
kullanırsa, bu malzeme arazinin bütünleyici parçası olur.

(2) Ancak, sahibinin rızası olmaksızın kullanılmış olan malzemenin sökülmesi
aşırı zarara yol açmayacaksa, malzeme sahibi, gideri yapıyı yaptırana ait olmak
üzere bunların sökülüp kendisine verilmesini isteyebilir.

(3) Aynı koşullar altında arazinin maliki de, rızası olmaksızın yapılan yapıda
kullanılan malzemenin, gideri yapıyı yaptırana ait olmak üzere sökülüp
kaldırılmasını isteyebilir.
====

[caption=""]
.Tazminat
====
*MK 723*: (1) Malzeme sökülüp alınmazsa arazi maliki, malzeme sahibine uygun
bir tazminat ödemekle yükümlüdür.  Yapıyı yaptıran arazi maliki iyiniyetli
değilse hâkim, malzeme sahibinin uğradığı zararın tamamının tazmin edilmesine
karar verebilir.

(2) Yapıyı yaptıran malzeme sahibi iyiniyetli değilse, hâkimin hükmedeceği
miktar bu malzemenin arazi maliki için taşıdığı en az değeri geçmeyebilir.
====

[caption=""]
.Arazinin mülkiyetinin malzeme sahibine verilmesi
====
*MK 724*: (1) Yapının değeri açıkça arazinin değerinden fazlaysa, iyiniyetli
taraf uygun bir bedel karşılığında yapının ve arazinin tamamının veya yeterli
bir kısmının mülkiyetinin malzeme sahibine verilmesini isteyebilir.
====

==== HAKSIZ YAPIYI ARAZİ MALİKİNİN YAPMASI

Arazi malikinin kendi arazisi üzerinde inşa ettiği yapıda başkasına ait
malzemeyi haksız olarak kullanması durumudur. Normal şartlarda yapı arazinin
bütünleyici parçası olduğu için arazi malikinin olur.

. *MK 722 kapsamında malzemenin sökülerek geri verilmesi için*:

.. İnşaat malzeme malikinin rızası olmadan yapılmış olmalıdır.
.. Malzemenin sökülerek kaldırılması aşırı zarara yol açmamalıdır.

. *MK 723 kapsamında tazminat talep edilebilmesi için*:

.. Malzemenin sökülerek geri verilmesi talep edilmemiş veya edilse bile
reddedilmiş olmalıdır.

[NOTE]
====
Tarafların iyiniyeti tazminat ödeme yükümlülüğünün olup olmaması kapsamında
değil, tazminat miktarının takdiri aşamasında önem arz eder. Ödenecek tazminat
miktarı tarafların iyiniyetine göre farklılık gösterir.

Arazi malikinin malzemenin başkasına ait olduğunu bilmemesi ve bilmesinin
gerekmemesi ya da bunu bilmekle birlikte malzeme malikinin rızasının olduğunu
düşünmekte haklı olması durumunda iyiniyetli olduğu kabul edilir.

Arazi maliki iyiniyetli ise uygun bir tazminat ödemekle yükümlüdür. İyiniyetli
değilse, hakim malzeme malikinin uğradığı zararın tümünün tazminine
hükmedebilir. Ancak tazminat taşınmazın arazi malikine sağladığı objektif değer
faydasını aşamaz.

Arazi maliki iyiniyetli ise _sebepsiz zenginleşme_, iyiniyetli değilse _haksız
fiil_ hükümlerine göre sorumlu olur.

Malzeme sahibi iyiniyetli değilse, malzemenin alındığını, kullanıldığını görmüş
ama ses çıkarmamışsa tazminat miktarı, malzemenin arazi maliki için taşıdığı en
az değeri geçmeyebilir.
====

. *MK 724 kapsamında arazi mülkiyetinin malzeme malikine geçirilmesi için*:

.. Malzeme maliki arazi mülkiyetinin kendisine geçirilmesini talep etmelidir.
.. Malzeme maliki iyiniyetli olmalıdır.
.. Yapının değeri *açıkça* arazinin değerinden fazla olmalıdır.
.. Malzeme maliki MK 722 uyarınca talepte bulunmamış veya bulunmuş olsa bile
talebi reddedilmiş olmalıdır.
.. Malzeme maliki MK 723 uyarınca tazminat talebinde bulunmamış olmalıdır.

Yukarıdaki şartların varlığı halinde malzeme maliki, yapının ve arazinin
mülkiyetinin *uygun bir bedel karşılığında* kendisine verilmesini isteyebilir.

==== HAKSIZ YAPIYI MALZEME MALİKİNİN YAPMASI

Bir kişinin kendisine ait malzeme ile başkasının taşınmazına haksız yapı
yapması durumudur.

. *MK 722/3 uyarınca arazi malikinin malzemenin sökülerek kaldırılmasını talep
etmesi için*: 

.. Yapı arazi malikinin rızası olmadan yapılmış olmalıdır.
.. Malzemenin sökülerek kaldırılması aşırı zarara yol açmamalıdır.

Arazi malikinin malzemenin sökülerek kaldırılmasını talep etmemiş olması veya
bu talebin reddedilmiş olması halinde malzeme maliki arazi malikinden tazminat
talep edebilir.

. *MK 723 uyarınca tazminat talep edilebilmesi için*:

.. Arazi malikinin malzemenin sökülerek kaldırılmasını talep etmemiş olması
veya bu talebin reddedilmiş olması gerekir.

[NOTE]
====
Malzeme maliki iyiniyetli ise, yani arazinin başkasına ait olduğunu bilmiyorsa
ve bilmesi gerekmiyorsa ya da arazi malikinin rızasının olduğunu düşünmekte
haklı ise uygun bir tazminat isteyebilir. Hem malzemenin parasını hem de
emeğini isteyebilir.

Malzeme maliki iyiniyetli değilse, arazi malikinin vereceği tazminat bu
malzemenin arazi maliki için taşıdığı en az değeri geçemez.

Arazi maliki iyiniyetli değilse malzeme malikinin bütün zararlarının tazminine
hükmedebilir.
====

. *MK 724 uyarınca arazi müllkiyetinin malzeme malikine geçirilmesi talebi*:

.. Bu talebi hem arazi maliki hem de malzeme maliki yöneltebilir. Talep eden
taraf iyiniyetli olmalıdır. 
.. Arazi malikine uygun bir tazminat verilmelidir.
.. Malzemenin sökülerek kaldırılması talep edilmemiş veya reddedilmiş
olmalıdır.
.. Tazminat talep edilmemiş olmalıdır.
.. Yapının değeri açıkça arazinin değerinden fazla olmalıdır.

==== HAKSIZ YAPIYI ÜÇÜNCÜ KİŞİNİN YAPMASI

Üçüncü bir kişinin başkasına ait bir malzeme ile bir başka kişinin arazisi
üzerinde haksız yapı inşa etmesi durumudur.

. *Arazi malikinin hakları*

.. _Giderleri yapana ait olmak üzere malzemenin sökülüp kaldırılması_

... Arazi malikinin rızası olmamalıdır.
... Malzemenin sökülüp kaldırılması aşırı zarara yol açmamalıdır.

.. _Vekaletsiz iş görme veya haksız fiil kurallarına göre yapandan tazminat
talebi_

. *Malzeme malikinin hakları*

.. _Yapı arazi malikinin rızası ile yapılmış ise MK 722 veya 723'ün
uygulanması_
+
NOTE: Malzeme maliki, arazi malikinden sebepsiz zenginleşme hükümlerine göre,
inşaatı yapandan ise haksız fiil veya sebepsiz zenginleşme kurallarına göre
talepte bulunabilir. Zararını bir tarafa tazmin ettirmiş ise artık diğer tarafa
başvurması mümkün değildir.
.. _Malzeme maliki iyiniyetli ise MK 724 uyarınca arazi mülkiyetinin kendisine
geçirilmesi_

. *Yapıyı yapanın hakları*
+
Malzeme malikinden bir talepte bulunamaz.

.. _Arazi malikinin rızası varsa, arazi malikine vekalet hükümleri kapsamında
başvurabilir._
.. _Arazi malikinin rızası varsa, arazi malikine karşı vekaletsiz iş görme
hükümlerinden faydalanabilir._

=== ARAZİDEKİ YAPININ ARAZİ MÜLKİYETİNE TABİ OLMASI KURALININ İSTİSNALARI

==== TAŞKIN YAPI

[caption=""]
.Taşkın yapılar
====
*MK 725*: (1) Bir yapının başkasına ait araziye taşırılan kısmı, eğer yapıyı
yapan malik taşırılan arazi üzerinde bir irtifak hakkına sahip bulunuyorsa, ona
ait taşınmazın bütünleyici parçası olur.

(2) Böyle bir irtifak hakkı yoksa, zarar gören malik taşmayı öğrendiği tarihten
başlayarak onbeş gün içinde itiraz etmediği, aynı zamanda durum ve koşullar da
haklı gösterdiği takdirde, taşkın yapıyı iyiniyetle yapan kimse, uygun bir
bedel karşılığında taşan kısım için bir irtifak hakkı kurulmasını veya bu
kısmın bulunduğu arazi parçasının mülkiyetinin kendisine devredilmesini
isteyebilir.
====

* *Malik, diğer arazideki yapının kendi arazisine taşmasına izin vermeyi
* taahhüt etmişse (irtifak hakkı varsa)*: Taşma toprağa bağlı bir yapının
taşması şeklindeyse bu irtifakın üst hakkı olması lazımdır. Bunun dışındaki
irtifaklar taşkın yapı kurumunun işletilmesi için yeterli olmaz. Böyle bir üst
hakkı söz konusu ise MK 725/1 gereğince taşan kısım hangi yapıdan taşmışsa o
taşınmazın bütünleyici parçası olur.
* *Taraflar arasında irtifak hakkı söz konusu değilse*
+
Aşağıdaki şartlar söz konusu ise kanun koyucu MK 725/2'de iki ayrı hak
tanımıştır:
****
. İrtifak hakkı veya irtifak taahhüdü olmamalıdır.
. İnşaat iyiniyetle yapılmış olmalıdır.
. Arazi maliki yapının arazisine taştığını öğrendiği tarihten itibaren 15 gün
içinde itiraz etmemiş olmalıdır.
. Durum ve koşullar yapının kalmasını haklı göstermelidir.
****
+
Bu haklar;

. Uygun bir bedel karşılığında irtifak hakkı tanınması (eşyaya bağlı olmak zorunda)
. Uygun bir bedel karşılığında mülkiyet hakkı tanınması

==== ÜST HAKKI

[caption=""]
.Üst hakkı
====
*MK 726*: (1) Bir üst irtifakına dayalı olarak başkasına ait bir arazinin
altında veya üstünde sürekli kalmak üzere inşa edilen yapıların mülkiyeti,
irtifak hakkı sahibine ait olur.

(2) Bir binanın başlı başına kullanılmaya elverişli bağımsız bölümleri üzerinde
kat mülkiyeti veya kat irtifakı kurulması, Kat Mülkiyeti Kanununa tâbidir.

(3) Bağımsız bölümler üzerinde ayrıca üst hakkı kurulamaz.
====

*Üst hakkı*, bir kişiye başkasına ait bir arazideki yapının maliki olma yetkisi
veren bir irtifak hakkıdır.

Üst hakkının sağladığı mülkiyet hakkı, irtifak hakkının sağladığı yetkidir.
Yapı üzerindeki mülkiyet hakkı üzerinde yapılacak tasarruf işlemleri irtifak
üzerinde tasarruf yolu ile yapılabilecektir.

Kanun koyucu üst hakkı bakımından 100 yıllık bir sınır koymuştur. Bu süre
bittiğinde irtifak hakkı sona erecektir. İrtifak hakkın sona ermesiyle arazi
üzerindeki yapıların mülkiyeti arazi malikine geçer.

==== MECRALAR

[caption=""]
.Mecralar
====
*MK 727*: (1) Su, gaz, elektrik ve benzerlerinin mecraları, işletmenin
bulunduğu taşınmazın dışında olsalar bile, aksine bir düzenleme olmadıkça o
işletmenin eklentisi ve işletme malikinin malı sayılır.

(2) Komşuluk hukukunun gerektirdiği hâller dışında bir taşınmazın böyle bir
mecra ile aynî hak olarak yüklenmesi, ancak bir irtifak hakkı kurulması
suretiyle olabilir.

(3) İrtifak hakkı, mecra dışarıdan görülmüyorsa tapu kütüğüne tesciliyle,
dışarıdan görülüyorsa noterce düzenlenecek sözleşmeye dayanılarak mecranın
yapılmasıyla doğar.
====

*Mecra*, doktrinde "_kuvvet ve maddelerin taşıma ve dağıtımına yarayan teknik
tesisat_" olarak tanımlanmaktadır.

* Mecra komşuluk hukukuna göre zorunlu olarak kurulabilir.
* İki taraf anlaşarak mecra irtifakı kurabilir.
* Bir taraf mecra irtifakı kurmayı taahhüt etmiş olabilir.
* Bir taraf diğerinin haberi olmadan mecra inşa etmişse haksız yapı kuralları
uygulanabilir.

TIP: Mecraların mutlaka hizmet ettiği araziye ait olacağına dair emredici bir
kural yoktur, aksine düzenleme mümkündür.

=== DİKİLİ BİTKİLER

Arazinin mülkiyeti o araziye sıkı sıkıya bağlı olan ve topraktan sökülmemesi
gereken bitkileri de kapsar. Bitkiler hakkında bir üst hakkı tanınması mümkün
değildir.

Uygulamada ağaçların başkasının arazine dikilmiş olması halinde haksız yapı
hükümleri kıyasen uygulanır.

[caption=""]
.Araziye dikilen fidanlar
====
*MK 729*: (1) Bir kimse başkasının fidanını kendi arazisine ya da kendisinin
veya bir üçüncü kişinin fidanını başkasının arazisine dikerse, başkasının
malzemesini kullanarak yapılan yapılara veya taşınır yapılara ilişkin hükümler
bunlar hakkında da uygulanır.

(2) Ağaçlar ve ormanlar üst hakkına konu olamaz.
====

Ağaçların başkasının arazisine taşması durumunda müdahalenin men'i davası
açılarak ağacın kaldırılması istenebilir. Kaldırılmazsa taşan dallar
kesilebilir.

=== ARAZİDEKİ KAYNAKLAR

*Kaynak*, doğal olarak veya insan emeği ile toprak sathına çıkan su olarak
tanımlanabilir. MK 748 vd. kaynakların korunmasına ilişkin maddeler vardır.
Herkes kaynağına zarar verilmemesini, kirletilmemesini isteme hakkına sahiptir.
Eğer bir kişinin kaynağı başkasının fiilinden dolayı zarar görürse bu zararın
tazmini istenebilir.

Aynı kaynaktan beslenen kişiler arasında ortak mülkiyet ilişkisi kurulur.

[caption=""]
.Aynı yataktan beslenen kaynaklar
====
*MK 759*: (1) Değişik maliklere ait komşu kaynaklar, ortak bir ana kaynaktan
beslenmekte ise maliklerden her biri, bu kaynakların birlikte tutulmasını ve
suyun hak sahiplerine o zamana kadarki yararlanmaları oranında dağıtılmasını
isteyebilir.

(2) Hak sahipleri, ortak tesis masraflarını yararlanmaları oranında
üstlenirler.

(3) Birinin karşı çıkması hâlinde, hak sahiplerinden her biri, diğer
kaynaklardaki su azalacak olsa bile, kendi kaynağındaki suyun tutulup
akıtılması için gerekli işleri yapabilir ve kendi kaynağına gelen suyun miktarı
bu işler sonunda çoğaldığı takdirde, ancak bu çoğalma oranında bir bedel
vermekle yükümlü olur.
====

== TAŞINMAZ MÜLKİYETİNİN SINIRLAMALARI

=== MALİKİN HUKUKİ İŞLEMİNDEN DOĞAN SINIRLAMALAR

==== ALIM HAKKI

*Alım hakkı*, hak sahibine tek taraflı bir beyanla taşınmazın alıcısı olabilme
hakkı veren, yenilik doğuran bir haktır.

[caption=""]
.Şekil
====
*TBK 237*: (2) Taşınmaz satışı vaadi, geri alım ve alım sözleşmeleri, resmî
şekilde düzenlenmedikçe geçerli olmaz.
====

Alım hakkı TBK 237/2 uyarınca resmi şekilde düzenlenmelidir. *Noterler bu
sözleşmeyi düzenlemeye yetkili değildir*. Taşınmazlara ilişkin resmiyet
kazandırma yetkisi tapu memurlarındadır. Noterde düzenlendiği takdirde _tahvil_
kurumu uygulanarak taşınmaz satış vaadine çevrilebilir.

Alım hakkı sahibi hakkını kullanınca taşınmaz maliki ile aralarında
kendiliğinden bir satış ilişkisi doğar. Böylece taşınmaz malikinin ilgili
taşınmazın mülkiyetini tapuda devretme borcu ortaya çıkar. Buna karşılık da
alım hakkı sahibi bir semen ödeyecektir.

Malik devir borcunu ifa etmezse alım hakkı sahibi MK 716 uyarınca dava açarak
tescili talep edebilir. Hakim mülkiyetin geçirilmesine hükmederse mülkiyet
tescil dışı bir şekilde alım hakkı sahibine geçer. Bundan sonra yapılacak
tescil açıklayıcıdır.

TIP: Taşınmaz satış vaadinde satış sözleşmesi yapma borcu doğar. Alım hakkında
ise satış ilişkisi doğar.

[caption=""]
.Süresi ve şerhi
====
*TBK 238*: (1) Önalım, geri alım ve alım hakları en çok on yıllık süre için
kararlaştırılabilir ve kanunlarda belirlenen süreyle tapu siciline şerh
edilebilir.
====

Alım hakkı sözleşmesi en fazla 10 yıllık yapılır.

[caption=""]
.Alım ve geri alım hakları
====
*MK 736*: (1) Tapu kütüğüne şerh verilen alım ve geri alım hakları, şerhde
belirtilen süre içinde her malike karşı kullanılabilir.

(2) Şerhin etkisi, her durumda, şerhin verildiği tarihin üzerinden on yıl
geçmekle sona erer.
====

Alım hakkı sözleşmesi şerhedilebilir. Şerhin etkisi 10 yıl boyunca devam eder.
Şerh için şerh anlaşması gereklidir.

Şerhin iki etkisi vardır:

. Taşınmazı devretme borcunu eşyaya bağlı borç haline getirir.
. Munzam etki ile hakkın kullanılması önündeki engelleri bertaraf eder.

Alım hakkı ancak sözleşmede açık hüküm olması durumunda mümkündür.

[caption=""]
.Devredilmesi ve miras yoluyla geçmesi
====
*TBK 239*: (1) Aksine anlaşma olmadıkça, sözleşmeden doğan önalım, alım ve geri
alım hakları devredilemez, ancak miras yoluyla geçer.

(2) Bu hakların devredilebileceği sözleşmeyle kararlaştırılmışsa, devir işlemi
hakkın kurulması için öngörülen şekilde yapılmadıkça geçerli olmaz.
====

==== GERİ ALIM HAKKI

*Geri alım hakkı*, taşınmazını başkasına devretmiş olan kişiye tek taraflı
irade beyanıyla taşınmazını geri alabilme yetkisi sağlayan, yenilik doğuran bir
haktır.

Bir hakkın geri alım hakkı olarak nitelendirilmesi için en geç taşınmaz
mülkiyetinin devri anına kadar kurulması gerekir. Taşınmaz mülkiyetinin
devrinden sonra yapılmış sözleşmeler alım sözleşmesi olarak nitelendirilir.

Geri alım hakkı resmi şekilde kurulur (TBK 237/2). Hak kullanıldığında alım
hakkındaki gibi bir satış ilişkisi doğar. Semen sözleşmede belirlenmiş ise o
değer üzerindeni belirlenmemiş ise hakkın kullanıldığı andaki taşınmazın rayiç
bedeli üzerinden satış yapılır.

Şerh anlaşması yapılarak şerhi mümkündür (TBK 238, MK 736). Şerhin süresi on
yıldır (MK 736/2).

Sözleşmede aksi kararlaştırılmamışsa devri mümkün değildir (TBK 239).

.Geri alım hakkının inançlı işlem ile ilişkisi
****
*Ortak yönleri*:

. Mülkiyet başlangıçta alıcıya geçmektedir.
. İki kurum da _Lex Commissoria_ yasağına aykırılık teşkil etmez.

*Farkları*:

. Geri alım hakkında şerh mümkündür.
. İnanç anlaşması herhangi bir resmi şekle tabi değildir.
. Geri alım hakkında iade borcu hakkın kullanılması ile doğar. İnanç
anlaşmasında ise koşulun gerçekleşmesi ile iade borcu doğar.
****

==== HUKUKİ İŞLEMDEN KAYNAKLANAN ÖNALIM HAKKI

*Önalım hakkı*, taşınmaz malikinin, taşınmazını bir üçüncü kişiye satması
halinde hak sahibine tek taraflı beyanla taşınmaza alıcı olabilme hakkı veren
yenilik doğuran haktır.

CAUTION: Önalım hakkının kullanılması şarta bağlıdır. Şart taşınmaz malikinin
taşınmazı üçüncü kişiye satmasıdır.

[caption=""]
.İleri sürülmesi
====
*TBK 240*: (1) Önalım hakkı, taşınmazın satışı ya da ekonomik bakımdan satışa
eşdeğer her türlü işlemin yapılması hâllerinde kullanılabilir.

(2) Taşınmazın, mirasın paylaşımında mirasçılardan birine özgülenmesi, cebrî
artırma yoluyla satışı ve kamu hizmetlerinin yerine getirilmesi ve bunlara
benzer amaçlarla edinilmesi hâllerinde önalım hakkı kullanılamaz.
====

[caption=""]
.Koşulları ve hükümleri
====
*TBK 241*: (1) Satıcı veya alıcı, satış sözleşmesinin yapıldığını ve içeriğini
önalım hakkı sahibine noter aracılığıyla bildirmek zorundadır.

(2) Önalım hakkı kullanıldıktan sonra satış sözleşmesi ortadan kaldırılırsa ya
da alıcının şahsından kaynaklanan sebeplerle onaylanmazsa, bu durum önalım
hakkı sahibine karşı ileri sürülemez.

(3) Önalım hakkını kuran sözleşmede aksi öngörülmemişse, önalım hakkı sahibi
taşınmazı, satıcının üçüncü kişiyle kararlaştırdığı satışa ilişkin koşullarla
kazanır.

(4) Ekonomik bakımdan satışa eşdeğer işlemlerde de yukarıdaki hükümler
uygulanır.
====

Önalım sözleşmesi resmi şekle tabi değildir, yazılı yapılması yeterlidir.

[caption=""]
.Şekil
====
*TBK 237*: (3) Önalım sözleşmesinin geçerliliği, yazılı şekilde yapılmış
olmasına bağlıdır.
====

Önalım hakkının şerhi mümkündür. Şerh 10 yıl süre için geçerlidir.

Önalım hakkı diğerlerinin aksine dava açılarak kullanılmak zorundadır.

[caption=""]
.Kullanılması ve hükümleri
====
*TBK 242*: (1) Sözleşmeden doğan önalım hakkını kullanmak isteyen hak sahibi,
bu hak şerhedilmiş ve taşınmazın mülkiyeti alıcı adına tescil edilmişse
alıcıya; aksi takdirde satıcıya karşı, satışın veya ekonomik bakımdan satışa
eşdeğer başka bir işlemin kendisine bildirildiği tarihten başlayarak üç ay ve
her hâlde satışın yapılmasından başlayarak iki yıl içinde dava açmak
zorundadır.
====

Yargıtay önalım hakkı sahibi ne kadar önce bilirse bilsin hak düşürücü sürenin
başlangıcı için noterden yapılan ihtarı kabul etmektedir. Noterden yapılan
ihtarla bu sürenin başlaması için, yapılan ihtarda hangi sözleşmenin yapıldığı,
alıcının kim olduğu, bedelin ne olduğu yer almalıdır. Aksi takdirde ihtar
yapılmamış sayılır.

Taşınmaz mülkiyeti mahkeme kararıyla tescil dışı kazanılır. Ancak hakim önce
bedelin yatırılmasını aramaktadır.

* Önalım sözleşmesinde herhangi bir bedel belirlenmemişse, önalım hakkını
doğuran satış ilişkisinin bedeli yatırılır.
* Sözleşmede bedel belirlenmişse bu bedel yatırılır.

=== KANUNLARDAN KAYNAKLANAN KISITLAMALAR

==== KANUNDAN KAYNAKLANAN ÖNALIM HAKKI

Yasal önalım hakkı paydaşlardan birinin mülkiyet payını satış veya ekonomik
olarak satışa eşdeğer bir sözleşme ile üçüncü kişiye geçirmesi halinde
kullanılacak bir haktır.

====
*MK 732*: (1) Paylı mülkiyette bir paydaşın taşınmaz üzerindeki payını tamamen
veya kısmen üçüncü kişiye satması hâlinde, diğer paydaşlar önalım hakkını
kullanabilirler.
====

CAUTION: Bir paylı mülkiyet ilişkisinde yasal önalım hakkı sahibi olmak için
paydaş olmak şarttır.

Önalım hakkının muhatabı olan kişi, payı önalım hakkı sahibine devretme
yükümlülüğü altına girer. Bunun için hakkın şerh edilmiş olması gerekmez,
kanun eşyaya bağlı borç etkisi yaratır.

NOTE: Sözleşmeden doğan önalım hakkının sadece ilk satıştan sonraki satışlar
için de geçerli olup olmayacağı tartışmalıdır. Ancak burada *kanundan doğan bir
sınırlama olduğu için yapılan her pay satışında bu hak yeniden doğar*.

Önalım hakkı dava yoluyla kullanılır. Yapılan satışın alıcı veya satıcı
tarafından önalım hakkı sahibini noter aracılığıyla bildirilmesinden itibaren 3
ay ve her halükarda 2 yıl içerisinde dava açılmalıdır.

Henüz devir yapılmamışsa satış yapan paydaşa, tescil yapılmış ise alıcıya karşı
dava açılır.

[caption=""]
.Kullanılması
====
*MK 734*: (1) Önalım hakkı, alıcıya karşı dava açılarak kullanılır.

(2) Önalım hakkı sahibi, adına payın tesciline karar verilmeden önce, satış
bedeli ile alıcıya düşen tapu giderlerini, hâkim tarafından belirlenen süre
içinde hâkimin belirleyeceği yere nakden yatırmakla yükümlüdür.
====

[TIP]
====
Hak alıcıya karşı kullanıldıktan sonra alıcının taşınmazı bir üçüncü kişiye
satması durumunda hak üçüncü kişiye karşı ileri sürülemez.

Örneğin A malını D'ye satar ve B kanundan doğan önalım hakkını D'ye karşı
kullanır. D de taşınmazı E'ye satar ve devreder. Bu durumda B önalım hakkını
E'ye karşı ileri süremez. Bunun E'ye karşı da ileri sürülebilmesi için bir
kanun hükmüne ihtiyaç vardır. Sözleşmesel önalım hakkında bunu şerh sağlar. E
payını F'ye satarsa, bu yeni bir satış olduğu için B hakkını F'ye karşı
kullanabilir.
====

Önalım hakkını birden çok malik kullanırsa pay maliklere payları oranında
dağıtılır.

[caption=""]
.Kullanma yasağı, feragat ve hak düşürücü süre
====
*MK 733*: (1) Cebrî artırmayla satışlarda önalım hakkı kullanılamaz.

(2) Önalım hakkından feragatin resmî şekilde yapılması ve tapu kütüğüne şerh
verilmesi gerekir. Belirli bir satışta önalım hakkını kullanmaktan vazgeçme,
yazılı şekle tâbidir ve satıştan önce veya sonra yapılabilir.

(3) Yapılan satış, alıcı veya satıcı tarafından diğer paydaşlara noter
aracılığıyla bildirilir.

(4) Önalım hakkı, satışın hak sahibine bildirildiği tarihin üzerinden üç ay ve
her hâlde satışın üzerinden iki yıl geçmekle düşer.
====

==== KOMŞULAR LEHİNE KONULMUŞ KISITLAMALAR

===== TAŞINMAZIN KULLANILMA TARZINA AİT KISITLAMALAR

[caption=""]
.Kullanma biçimi
====
*MK 737*: (1) Herkes, taşınmaz mülkiyetinden doğan yetkileri kullanırken ve
özellikle işletme faaliyetini sürdürürken, komşularını olumsuz şekilde
etkileyecek taşkınlıktan kaçınmakla yükümlüdür.

(2) Özellikle, taşınmazın durumuna, niteliğine ve yerel âdete göre komşular
arasında hoş görülebilecek dereceyi aşan duman, buğu, kurum, toz, koku
çıkartarak, gürültü veya sarsıntı yaparak rahatsızlık vermek yasaktır.

(3) Yerel âdete uygun ve kaçınılmaz taşkınlıklardan doğan denkleştirmeye
ilişkin haklar saklıdır.
====

Taşkınlığın etkisini hisseden her diğer malik komşu sayılmaktadır. Her komşu
taşkınlığa itiraz etme ve durdurma hakkına sahiptir. Taşkınlığa devam eden
malik komşuların zararlarını ödemekle yükümlüdür.

===== KAZI VE YAPILARA İLİŞKİN KISITLAMALAR

====
*MK 738*: (1) Malik, kazı ve yapı yaparken komşu taşınmazlara, onların
topraklarını sarsmak veya tehlikeye düşürmek ya da üzerlerindeki tesisleri
etkilemek suretiyle zarar vermekten kaçınmak zorundadır.

(2) Komşuluk hukuku kurallarına aykırı yapılar hakkında taşkın yapılara ilişkin
hükümler uygulanır.
====

MK 738'a aykırı davranan malik durdurulabilir. Zarar ortaya çıkmışsa da MK 730
çerçevesinde zararın tazmini istenebilir.

[caption=""]
.Taşınmaz malikinin sorumluluğu
====
*MK 730*: (1) Bir taşınmaz malikinin mülkiyet hakkını bu hakkın yasal
kısıtlamalarına aykırı kullanması sonucunda zarar gören veya zarar tehlikesi
ile karşılaşan kimse, durumun eski hâline getirilmesini, tehlikenin ve uğradığı
zararın giderilmesini dava edebilir.

(2) Hâkim, yerel âdete uygun ve kaçınılmaz taşkınlıklardan doğan zararların
uygun bir bedelle denkleştirilmesine karar verebilir.
====

===== KOMŞU ARAZİYE AİT AĞAÇLARIN KÖK VE DALLARININ KENDİ ARAZİSİNE GEÇMESİNE KATLANMA YÜKÜMLÜLÜĞÜ

====
*MK 740*: (1) Komşunun arazisine taşarak zarar veren dal ve kökler, onun istemi
üzerine uygun bir süre içinde kaldırılmazsa, komşu bu dal ve kökleri kesip
kendi mülkiyetine geçirebilir.

(2) Ekilmiş veya üzerine yapı yapılmış arazisine dalların taşmasına katlanan
komşu, bu dallarda yetişen meyvaları toplama hakkına sahip olur.

(3) Komşu ormanlar hakkında bu hükümler uygulanmaz.
====

===== SULARIN AKIŞINA ENGEL OLMAMA YÜKÜMLÜLÜĞÜ

[caption=""]
.Doğal olarak akan su
====
*MK 742*: (1) Taşınmaz maliki, üst taraftaki araziden kendi arazisine doğal
olarak akan suların ve özellikle yağmur, kar ve tutulmamış kaynak sularının
akışına katlanmak zorundadır.

(2) Komşulardan hiçbiri bu suların akışını diğerinin zararına değiştiremez.

(3) Üstteki arazi maliki, alt taraftaki taşınmaza gerekli olan suyu, ancak
kendi taşınmazı için zorunlu olduğu ölçüde tutabilir.
====

===== MECRA GEÇİRİLMESİNE KATLANMA YÜKÜMLÜLÜĞÜ

[caption=""]
.Katlanma yükümlülüğü
====
*MK 744*: (1) Her taşınmaz maliki, uğrayacağı zararın tamamının önceden
ödenmesi koşuluyla, su yolu, kurutma kanalı, gaz ve benzerlerine ait boruların,
elektrik hat ve kablolarının, başka yerden geçirilmesi olanaksız veya aşırı
ölçüde masraflı olduğu takdirde, kendi arazisinin altından veya üstünden
geçirilmesine katlanmakla yükümlüdür.

(2) Mecra geçirilmesinin kamulaştırma kurallarına bağlı olması hâlinde, bu
Kanunun mecralara ilişkin komşuluk hükümleri uygulanmaz.

(3) Mecrayı geçirme hakkı, hak sahibinin istemi üzerine ve giderleri ödemesi
koşuluyla tapu kütüğüne tescil edilir.
====

MK 744'teki şartlar gerçekleştiği anda kanun gereği irtifak hakkı kendiliğinden
doğar. Hakkın doğumu için tescile gerek yoktur.

İrtifak hakkının doğumu için aşağıdaki şartların aynı anda gerçekleşmesi
gerekir:

. Mecra geçirecek malikin mecraya gerçek bir ihtiyacı bulunmalıdır.
. Mecranın başka yerden geçirilmesi imkansız veya aşırı ölçüde masraflı
olmalıdır.
. Mecra geçirecek kişi, yükümlü malikin uğrayacağı zararı tamamen ve peşin
olarak ödemelidir.

Yükümlü taşınmaz maliki, kendi menfaatinin hakkaniyete uygun bir şekilde
gözetilmesini isteyebilir. Hatta eğer mümkünse mecranın geçirileceği kısmın
mülkiyetinin alınmasını talep edebilir.

[caption=""]
.Yükümlü taşınmaz malikinin menfaatinin korunması
====
*MK 745*: (1) Yükümlü taşınmaz maliki, kendi menfaatinin hakkaniyete uygun bir
biçimde gözetilmesini isteyebilir.

(2) Arazinin üzerinden geçecek mecralarda olağanüstü durumlar varsa malik, bu
mecraların üzerinden geçirileceği arazi parçasının uygun bir kısmının, zararını
tam olarak karşılayacak bir bedelle satın alınmasını isteyebilir.
====

Şartların değişmesi halinde yükümlü taşınmaz maliki mecranın yerini
değiştirilmesini isteme hakkına sahiptir.

[caption=""]
.Durumun değişmesi
====
*MK 746*: (1) Durum değişirse, yükümlü taşınmaz maliki, mecranın kendi yararına
olarak başka bir yere nakledilmesini isteyebilir.

(2) Yer değiştirme giderleri, kural olarak mecra hakkı sahibine aittir.

(3) Özel durumlar haklı gösterdiği takdirde, taşınmaz maliki de giderlerin
uygun bir kısmına katılmakla yükümlü tutulabilir.
====

===== GEÇİT İRTİFAKI KURMA YÜKÜMLÜLÜĞÜ

[caption=""]
.Zorunlu geçit
====
*MK 747*: (1) Taşınmazından genel yola çıkmak için yeterli geçidi bulunmayan
malik, tam bir bedel karşılığında bir geçit hakkı tanınmasını komşularından
isteyebilir.

(2) Bu hak, ilk önce kendisinden bu geçidin istenmesi önceki mülkiyet ve yol
durumuna göre en uygun düşen komşuya karşı ve daha sonra bundan en az zarar
görecek olana karşı kullanılır.

(3) Zorunlu geçit iki tarafın menfaati gözetilerek belirlenir.
====

Geçit irtifakı mecra irtifakı gibi kendiliğinden doğmaz. Kanun koyucu burada
geçit ihtiyacı olan kişiye yenilik doğuran bir hak tanımıştır.

[caption=""]
.Diğer geçit hakları
====
*MK 748*: (1) Taşınmaz malikinin taşınmazını işletme veya iyileştirme ya da
taşınmazı üzerinde yapı yapma amacıyla komşu taşınmaza geçici olarak girme
hakkı ile tarla yolu, hayvan sulama yolu, kış geçidi, tomruk kaydırma yolu ve
oluğu ve bunlara benzer diğer geçitler özel kanun hükümlerine tâbidir.

(2) Özel kanun hükmü yoksa yerel âdet uygulanır.

(3) Doğrudan doğruya kanundan kaynaklanan geçit hakları, tapu kütüğüne tescil
edilmeksizin doğar. Ancak, bunlardan sürekli nitelikte olanlar beyanlar
sütununda gösterilir.
====

===== KAYNAK İRTİFAKI KURMA YÜKÜMLÜLÜĞÜ

[caption=""]
.Zorunlu su
====
*MK 761*: (1) Evi, arazisi veya işletmesi için gerekli sudan yoksun olup, bunu
aşırı zahmet ve gidere katlanmaksızın başka yoldan sağlayamayan taşınmaz
maliki, komşusundan, onun ihtiyacından fazla olan suyu tam bir bedel
karşılığında almasını sağlayacak bir irtifak kurulmasını isteyebilir.

(2) Zorunlu su irtifakının kurulmasında öncelikle kaynak sahibinin menfaati
gözetilir.

(3) Durum değişirse, kurulmuş irtifak hakkının değiştirilmesi veya kaldırılması
istenebilir.
====

Burada da ihtiyacı olan malike yenilik doğuran bir hak tanınmıştır. Kanundan
doğan bir irtifak hakkı değildir.

===== KOMUŞULUK İÇİN GEREKLİ ŞEYLERE VE MASRAFLARA KATILMA YÜKÜMLÜLÜĞÜ

[caption=""]
.Katılma yükümlülüğü
====
*MK 750*: (1) Her taşınmaz maliki, komşuluk hukukundan doğan yetkilerin
kullanılması için gerekli işlere ve bunların giderlerine, kendi yararlanması
oranında katılmakla yükümlüdür.
====

== TAŞINMAZ MALİKİNİN SORUMLULUĞU

[caption=""]
.Taşınmaz malikinin sorumluluğu
====
*MK 730*: (1) Bir taşınmaz malikinin mülkiyet hakkını bu hakkın yasal
kısıtlamalarına aykırı kullanması sonucunda zarar gören veya zarar tehlikesi
ile karşılaşan kimse, durumun eski hâline getirilmesini, tehlikenin ve uğradığı
zararın giderilmesini dava edebilir.

(2) Hâkim, yerel âdete uygun ve kaçınılmaz taşkınlıklardan doğan zararların
uygun bir bedelle denkleştirilmesine karar verebilir.
====

MK 730 hem tazminat hem de fedakarlığın denkleştirilmesi esasını öngören bir
hükümdür.

MK 730 ile aşağıdaki davalar tanınmıştır:

.. *Eski hale getirme davası*: Kısıtlamalara aykırılık teşkil eden sebebin
bertaraf edilmesini amaçlar. Taşkınlık devam ettiği sürece açılabilir.
.. *Tazminat davası*: Taşkınlık sonucu zarar ortaya çıkmışsa açılabilir.
.. *Tehlikenin giderilmesi davası*: Zarar tehlikesinin ortaya çıkması halinde
zarar görme ihtimali doğan kimsenin henüz zarar meydana gelmeden önlem
alınmasını talep etmesini sağlar.

aşınmaz malikinin sorumluluğu bir **kusursuz sorumluluk**tur. Aşağıdaki
şartların varlığı halinde malikin kusuru olmasa dahi sorumluluk doğar:

. Mülkiyetin yasal kısıtlamalara aykırı kullanılması
. Zarar ile taşkınlık arasında illiyet bağının bulunması
. Zarar veya zarar tehlikesi

NOTE: Zamanaşımı bakımından TBK 72 yani haksız fiil zamanaşımı (2/10 yıl)
uygulanır.

MK 730 uyarınca malikin taşkınlığından etkilenen herkes (ayni veya şahsi hak
sahipleri) dava açabilir. Davalı olarak öncelikle malik sorumludur. Sınırlı
ayni hak sahipleri de sorumlu olabilir ama şahsi hak sahiplerine dava açılamaz.
Şahsi hak sahiplerinin kullanımından zarar görenler de davayı malike açar.

== KAT MÜLKİYETİ

Kat mülkiyetine konu olabilecek bağımsız bölümlerden bahsedebilmek için ayrı
ayrı mülkiyet kurulmak istenen bölümlerin tek başına kullanılmaya elverişli
olması gerekir.

====
*KAT MÜLKİYETİ KANUNU 1*: (1) Tamamlanmış bir yapının kat, daire, iş bürosu,
dükkan, mağaza, mahzen, depo gibi bölümlerinden ayrı ayrı ve başlı başına
kullanılmaya elverişli olanları üzerinde, o gayrimenkulün maliki veya ortak
malikleri tarafından, bu Kanun hükümlerine göre, bağımsız mülkiyet hakları
kurulabilir.

(2) Yapılmakta veya ileride yapılacak olan bir yapının, birinci fıkrada yazılı
nitelikteki bölümleri üzerinde, yapı tamamlandıktan sonra geçilecek kat
mülkiyetine esas olmak üzere, arsa maliki veya arsanın ortak malikleri
tarafından, bu Kanun hükümlerine göre irtifak hakları kurulabilir.
====

Arsanın tamamına *ana taşınmaz*, ana taşınmaz üzerindeki yapıya *ana yapı*
denir. Ana yapının içinde olup da ayrı ayrı ve başlı başına kullanılmaya
elverişli olduğu için üzerinde bağımsız mülkiyet hakkı kurulabilen yerlere ise
*bağımsız bölüm* denir. Bağımsız bölümler üzerindeki mülkiyet hakkı **kat
mülkiyeti**dir.

[caption=""]
.Tarifler
====
*KAT MÜLKİYETİ KANUNU 2*: (1) Bu Kanuna göre :

.. Kat mülkiyetine konu olan gayrimenkulün bütününe (Anagayrimenkul); yalnız
esas yapı kısmına (Anayapı) anagayrimenkulün ayrı ayrı ve başlı başına
kullanılmaya elverişli olup, bu Kanun hükümlerine göre bağımsız mülkiyete konu
olan bölümlerine (Bağımsız bölüm); bir bağımsız bölümün dışında olup, doğrudan
doğruya o bölüme tahsis edilmiş olan yerlere (Eklenti); bağımsız bölümler
üzerinde kurulan mülkiyet hakkına (Kat mülkiyeti) ve bu hakka sahip olanlara
(Kat maliki);
.. Anagayrimenkulün bağımsız bölümleri dışında kalıp, korunma ve ortaklaşa
kullanma veya faydalanmaya yarıyan yerlerine (Ortak yerler); kat maliklerinin
ortak malik sıfatiyle paydaşı bulundukları bu yerler üzerindeki faydalanma
haklarına (Kullanma hakkı);
.. Bir arsa üzerinde ileride kat mülkiyetine konu olmak üzere yapılacak veya
yapılmakta olan bir veya birden çok yapının bağımsız bölümleri için o arsanın
maliki veya ortak malikleri tarafından bu Kanun hükümlerine göre kurulan
irtifak hakkına (kat irtifakı); bu hakka sahip olanlara da (kat irtifak
sahibi);
.. Arsanın, bu Kanunda yazılı esasa göre bağımsız bölümlere tahsis edilen ortak
mülkiyet paylarına (Arsa payı);
.. Kat mülkiyetinin veya irtifakının kurulmasına ait resmi senede (Sözleşme);

Denir.
====

Kat mülkiyeti sadece bağımsız bölümü değil, arsa paylarını da kapsar.  Örneğin
taşınmaz üzerinde 5 tane taşınmaz var ise arsanın tamamı 5'e bölünür.  Ancak
paylar eşit olmak zorunda değildir, paylar kat mülkiyetine konu olacak bağımsız
bölümün değeri ile orantılı olarak tahsis edilir.

[caption=""]
.Kat mülkiyetinin ve kat irtifakının niteliği
====
*KAT MÜLKİYETİ KANUNU 3*: (1) Kat mülkiyeti, arsa payı ve anagayrimenkuldeki
ortak yerlerle bağlantılı özel bir mülkiyettir.

(2) Kat mülkiyeti ve kat irtifakı, bu mülkiyete konu olan anagayrimenkulün
bağımsız bölümlerinden her birinin konum ve büyüklüklerine göre hesaplanan
değerleri ile oranlı olarak projesinde tahsis edilen arsa payının ortak
mülkiyet esaslarına göre açıkça gösterilmesi suretiyle kurulur. Arsa paylarının
bağımsız bölümlerin payları ile oranlı olarak tahsis edilmediği hallerde, her
kat maliki veya kat irtifakı sahibi, arsa paylarının yeniden düzenlenmesi için
mahkemeye başvurabilir. Bağımsız bölümlerden her birine bu fıkra uyarınca
tahsis edilen arsa payı, o bölümlerin değerinde sonradan meydana gelen çoğalma
veya azalma sebebiyle değiştirilemez. 44 üncü madde hükmü saklıdır.

(3) Kat irtifakı arsa payına bağlı bir irtifak çeşidi olup, yapının tamamı için
düzenlenecek yapı kullanma izin belgesine dayalı olarak, bu Kanunda gösterilen
şartlar uyarınca kat mülkiyetine resen çevrilir. Bu işlem, arsa malikinin veya
kat irtifakına sahip ortak maliklerden birinin istemi ile dahi
gerçekleştirilebilir.
====

Kat mülkiyeti aynı zamanda **ortak yer**leri de kapsar. Ortak yerler, ana
taşınmazın bağımsız bölümleri dışında kalıp ortaklaşa kullanılan yerlerdir.

[caption=""]
.Ortak yerler
====
*KAT MÜLKİYETİ KANUNU 4*: (1) Ortak yerlerin konusu sözleşme ile
belirtilebilir. Aşağıda yazılı yerler ve şeyler bu Kanun gereğince her halde
ortak yer sayılır.

.. Temeller ve ana duvarlar, taşıyıcı sistemi oluşturan kiriş, kolon ve perde
duvarlar ile taşıyıcı sistemin parçası diğer elemanlar,bağımsız bölümleri
ayıran ortak duvarlar, tavan ve tabanlar, avlular, genel giriş kapıları,
antreler, merdivenler, asansörler, sahanlıklar, koridorlar ve buralardaki genel
tuvalet ve lavabolar, kapıcı daire veya odaları, genel çamaşırlık ve çamaşır
kurutma yerleri, genel kömürlük ve ortak garajlar, elektrik, su ve havagazı
saatlerinin korunmasına mahsus olup bağımsız bölüm dışında bulunan yuvalar ve
kapalı kısımlar, kalorifer daireleri, kuyu ve sarnıçlar, yapının genel su
depoları, sığınaklar,
.. Her kat malikinin kendi bölümü dışındaki kanalizasyon tesisleri ve çöp
kanalları ile kalorifer, su, havagazı ve elektrik tesisleri, telefon, radyo ve
televizyon için ortak şebeke ve antenler sıcak ve soğuk hava tesisleri,
.. Çatılar, bacalar, genel dam terasları, yağmur olukları, yangın emniyet
merdivenleri.  Yukarıda sayılanların dışında kalıp da, yine ortaklaşa kullanma,
korunma veya faydalanma için zaruri olan diğer yerler ve şeyler de (Ortak yer)
konusuna girer.
====

Kat Mülkiyeti Kanunu'nun 4. maddesindeki yerler kesinlikle ortak yerdir.
Taraflar anlaşsa dahi buralar ortak yer olmaktan çıkarılamaz. Ancak bunlar
dışındaki yerlerin ortak yer olması kararlaştırılabilir.

CAUTION: Bağımsız bölüm maliki sadece bağımsız bölüm üzerinde tasarruf
edebilir, ortak yerler veya arsa payı üzerinde tasarruf kesinlikle mümkün
değildir.

Bağımsız bölümün dışında olup da bağımsız bölüme tahsis edilen yerlere
*eklenti* denir. Eklentiler tapu kütüğünde bağımsız bölümlerin beyanlar
kısmında gösterilir.

[caption=""]
.Bağımsız bölümlerle eklentiler ve ortak yerler arasındaki bağlantı
====
*KAT MÜLKİYETİ KANUNU 6*: (1) Bir bağımsız bölümün dışında olup, doğrudan
doğruya o bölüme tahsis edilmiş olan kömürlük, su deposu, garaj, elektrik,
havagazı veya su saati yuvaları, tuvalet gibi eklentiler, ait olduğu bağımsız
bölümün bütünleyici parçası sayılır ve o bölümün maliki, eklentilerin de tek
başına maliki olur.

(2) Eklentiler kat mülkiyeti kütüğünün (Beyanlar) hanesine kaydedilir ve
bunlardan anayapının oturduğu zeminin dışında kalanlar kadastro planında veya
tapu haritasında ayrıca gösterilir.

(3) Bağımsız bölüm üzerinde kat mülkiyetiyle ve diğer kat maliklerinin
haklariyle bağdaşması mümkün olmayan irtifaklar kurulamaz.

(4) Bağımsız bölümlerin başkasına devri, kayıtlanması veya kiralanması halinde,
eklentiler ve ortak yerler de kendiliğinden devredilmiş, kayıtlanmış vaya
kiralanmış olur.
====

.Kat irtifakı
****
Kat irtifakı bilinen anlamda bir irtifak hakkı değildir. MK 779'a göre irtifak
hakkında yapma borcu asli borç olarak öngörülemez. Kat irtifakı o taşınmazın
paydaşlarına binayı yapıp, kat mülkiyetine çevirme borcu yükler. Burada eşyaya
bağlı borç söz konusudur. 
****

[caption=""]
.Genel hükümlerin uygulanma alanı
====
*KAT MÜLKİYETİ KANUNU 7*: (1) Kat mülkiyetine veya kat irtifakına ait kütük
kaydında veya kat malikleri arasındaki sözleşmede veya yönetim planında veya bu
kanunda hüküm bulunmayan hallerde, kat mülkiyetinden doğan anlaşmazlıklar,
Medeni Kanun ve ilgili diğer kanunlar hükümlerine göre karara bağlanır.
====

Kat mülkiyetinde;

* Paylaşma istenemez.
* Önalım hakkı yoktur.

=== KAT MÜLKİYETİNİN KURULMASI

İstenilen her taşınmazda kat mülkiyeti kurulamaz. Öncelikle üzerinde kat
mülkiyeti kurulmak istenen bina tamamlanmış olmalıdır. Tamamlanmamışsa ancak
kat irtifakı kurulabilir.

Başlı başına kullanılmaya elverişli her bölüm bağımsız bölüm olmak zorunda
değildir. Başlı başına kullanılmaya müsait birden fazla bölüm birlikte bir
bağımsız bölüm sayılabilir. Bağımsız bölümlerin farklı maliklere ait olması da
gerekmez. Ancak her bağımsız bölüme arsa payı tahsis edilmek zorundadır.

Üzerine sınırlı ayni hak veya kişisel hak şerh edilmiş taşınmazların kat
mülkiyetine çevrilmesine engel yoktur. Bu haklar ana taşınmazın sayfası katılıp
bağımsız bölümler ayrı sayfalara kaydedildiğinde her bir sayfaya kendi
değerleri oranında kaydedilir.

CAUTION: Kat mülkiyetine ana taşınmazın tamamını ilgilendiren irtifak hakları
geçirilmez.

*Kat mülkiyetini kurmak için* ya malik veya malikler aralarında anlaşarak
tapuda resmi senet düzenleyecektir. Resmi senedin düzenlenmesine dair talep
aynı zamanda tescil talebidir.

NOTE: Yargıtay'a göre ileride kurulmak üzere kat mülkiyeti yapılabilir.
Yargıtay bunu satış vaadi sözleşmesi olarak kabul ettiği için bunun noterden
yapılması gerekir. Bu satış vaadinde alacaklı malik haline gelmeyeceği için
resmi senedin düzenlenmesine katılması gerekmez.

Resmi senette her bir bağımsız bölüme tahsis edilen arsa payı gösterilmelidir.

TIP: Bir paylaşma davasında paylı maliklerden birisi paylaşmanın parayla değil
de kat mülkiyetine geçirilerek olmasını talep ederse hakim bu tür bir
paylaşmaya karar verebilir. *Kanunda karar verebilir dese de Yargıtay karar
vermek zorundadır diyor*.

==== KAT İRTİFAKI

Kat irtifakı paya bağlı, eşyaya bağlı bir borçtur.

Kat irtifakında bir paylı mülkiyet söz konusudur. Bu paylı mülkiyette paydaşlar
birbirlerine karşı kat mülkiyetine konu olacak taşınmazda bir bina inşa etmeyi
ya da inşaatına başlanmış binayı bitirmeyi taahhüt ederler. Tamamlanacak olan
binadan, paydaşların hepsine bağımsız bölümler intikal etmesi söz konusu
olacaktır.

Kat irtifakı kat mülkiyeti kütüğüne tescil ile kurulur. Dolayısıyla
paydaşlardan biri payını devretse bile yeni paydaş da kat irtifakı çerçevesinde
binayı kat mülkiyetine geçirme borcu altına girecektir.

Kat irtifakının kurulması için resmi senet düzenlenmesi ve kat mülkiyeti
kütüğüne tescil yapılması gerekir.

Kat irtfakının kurulabilmesi için:

. Yapı tamamlanmamış olmalıdır.
. İnşası hedeflenen bina kat mülkiyeti kurmaya elverişli bir bina olmalıdır.
. Kat irtifakı kurulurken, üzerinde inşaat yapılmakta olan veya yapılacak olan
taşınmazın mülkiyetinin, yapı tamamlandıktan sonra kat mülkiyetine konu
olabilecek bağımsız bölümlere tahsis olunan arsa payı oranlarına göre paylara
ayrılması gerekir.
. İleride yapılması belirlenen binanın bütünüyle kat mülkiyetine geçirilmesi
lazımdır.
. Kat irtifakı ancak, irtifaka konu taşınmazda pay sahibi olan lehine yani paya
bağlı olarak kurulabilir.

Her bir paya hangi bağımsız bölümün isabet edeceği, her bir bağımsız bölüme ne
kadar arsa payının tahsis edileceği resmi senette düzenlenmiş olması gerekir.
Tapu kütüğündeki sayfaya da kat irtifakına geçildiği ve hangi paya hangi
bağımsız bölümün, ne kadar arsa payının isabet ettiği kaydedilir.

Kat irtifakı sahiplerinin hak ve borçları:

. Kat irtifakı sahiplerinin sözleşmede yazılı şartlara göre binanın inşa
edilmesi borcu vardır. Bu borcu paydaşlar birbirlerinden talep edebilirler.
. Kat irtifakı sahipleri dürüstlük kuralı uyarınca birbirlerine karşı binanın
inşasını kolaylaştırmakla yükümlüdürler.
+
Sözleşmeye uymayan kişi karşı ifa davası açılır. Ancak ifa davası açan kişinin
kendisinin borcunu ifa etmiş ya da en azından ifa etmeyi teklif etmiş olması
gerekir.
+
Borcunu yerine getirmeyen paydaşa ihtar çekilir. İhtara rağmen borcunu 2 ay
içinde yerine getirmezse, diğer irtifak hakkı sahipleri ve paydaşlar birlikte,
onun arsa payının kendilerine satılmasını isteyebilirler.
. Arsa üzerinde inşaat tamamlanıp bina oturmaya elverişli hale gelince
paydaşların kat mülkiyetine geçme hakkı vardır.

Aşağıdaki hallerde kat irtifakı sona erer:

. Binanın tamamlanarak kat mülkiyetine çevrilmesi
. Tarafların anlaşarak terkin ettirmesi
. Taşınmazın yok olması
. Taşınmazın maddi veya hukuki sebepler ile üzerinde yapı yapılamayacak hale
gelmesi
. Taşınmazın kamulaştırılması
. Kat irtifakının kurulmasından itibaren 5 yıl içinde yapı yapılmazsa,
maliklerden birinin talebi üzerine mahkeme kat irtifakının uzatılmasına ve sona
ermesine karar verir.

=== KAT MALİKLERİNİN HAK VE BORÇLARI

. *Dürüstlük kuralına uygun davranma yükümlülüğü*: Her bir kat maliki birbirini
rahatsız etmemek, diğerlerinin haklarını engellememek ile yükümlüdür. Bu
yükümlülükler sadece kat malikleri için değil, bağımsız bölümde kat malikinin
tanıdığı yetkiye dayanarak devamlı surette faydalanan kişiler için de
geçerlidir.
. *Bağımsız bölüme ve eklentileri ile ilgili yükümlülükler*

.. Bağımsız bölüm ve eklentiyi özgülenme amacına uygun kullanma yükümlülüğü
.. Bağımsız bölümde ana yapıya zarar verecek nitelikte onarar ve tesis yapmama
yükümlülüğü
.. Onarım için bağımsız bölümüne girme, izin verme ve bölümünde gerekli
işlerin yapılmasına katlanma yükümlülüğü

. *Ana taşınmaz ve ortak yerler ile ilgili yükümlülükler*

.. Ana taşınmazın bakımı, mimari durumu ile güzelliği ve sağlamlığını koruma
yükümlülüğü
.. Genel giderlere katılma yükümlülüğü
+
Eğer bir malik, ortak giderlere katılma borcunu ödemediği için hakkında 2
takvim yılı içinde 3 defa dava veya icra takibi açılmış ise bağımsız bölümü
üzerindeki mülkiyet hakkının zorunlu devri mahkemeden talep edilebilir.

[NOTE]
====
Kat maliklerinden biri borç ve yükümlülüklerini çok fazla ihlal ettiği için,
diğer kat maliklerinden aynı yerde yaşamayı sürdürmek dürüstlük kuralı
kapsamında katlanılamayacak bir hal aldıysa mahkemeye başvurularak kat
mülkiyetinin zorunlu devri talep edilebilir.

Söz konusu bağımsız bölüm diğer kat maliklerine arsa payları oranında
geçirilebilir ya da tek bir kat malikine de devredilebilir. Ancak üçüncü
kişilere satışı istenemez.

Bağımsız bölümün devri için karara en yakın tarihteki rayiç bedel dikkate
alınır.

Davanın açılması için sayı ve arsa payı çoğunluğu ile karar alınır. Dava
kararın alınmasın itibaren 6 ay ve her halükarda dava hakkının doğumundan
başlayarak 5 yıl içinde açılmalıdır.
====

=== KAT MÜLKİYETİNİN YÖNETİMİ

==== YÖNETİM PLANI

*Yönetim planı*, ana taşınmazın yönetim tarzını, kullanma maksat ve şeklini,
yönetici ve denetçilerin alacakları ücreti ve yönetime ilişkin diğer hususları
düzenleyen belgedir.

Yönetim planı en başta oybirliği ile düzenlenir. Daha sonra taraflar
değiştirmek isterse kat maliklerinin 4/5 çoğunluğu ile değiştirebilirler.

Yönetim planı her bağımsız bölümün beyanlar hanesine kaydedilerek külli ve cüzi
haleflere karşı ileri sürülebilir. Kaydedilmemişse sadece taraflar arasında
geçerli olur.

Bağımsız bölüm maliklerinden biri yönetim planını haklı bir sebebi olmaksızın
imzalamıyorsa hakimden müdahale istenebilir.

==== GENEL KURUL (KAT MALİKLERİ KURULU)

Genel kurul, ana taşınmazdaki bütün kat maliklerinden oluşur. Yönetim ile
ilgili bütün kararlar genel kurulda alınır. Yöneticiyi seçer. Ana taşınmazın
kullanılmasıyla ilgili kat malikleri ile yönetici veya denetçi arasında
çıkabilecek sorunları çözer.

Genel kurul, emredici hükümlere ve yönetim planına uymak zorundadır.

Genel kurul, olağan şekilde yılda en az bir defa toplanır. Olağanüstü toplantı
için ise yönetici, denetçi ya da kat maliklerinin 1/3'ünün talebi gerekir.
Yönetim planında belirlenmiş bir toplantı tarihi yoksa toplantı tarihinden 15
gün önce maliklere bildirim yapılmalıdır.

Toplantı yeter sayısı sayı ve arsa payı çoğunluğudur. Birden fazla bağımsız
bölümü olan kişi her bir bağımsız bölümü için (toplantı yeter sayısı
bakımından) ayrı bir kişi sayılır.

Oy yeter sayısı bakımından ise bir kişinin birden fazla bağımsız bölümü olsa
bile kullanacağı oyların sayısı, tüm oyların 1/3'ünden fazla olamaz.

*Oybirliği aranan durumlar*:

* Meskenin daha sonradan eğlence, toplantı yeri, gıda ve beslenme yeri,
imalathane, boyahane, basımevi, dükkan haline getirilmesi
* Ana taşınmazın tamamının bölünmesi, bölünen kısmın başkasına devri, ana
taşınmazla ilgili tasarruf işlemleri
* Ana yapının çatısının, dış duvarlarının reklam için kiralanması
* Ana taşınmaza yeni bağımsız bölüm eklenmesi
* Merkezi ısıtma sisteminin ferdi sisteme dönüştürülmesi

Yönetim planını değiştirmek için kat maliklerinin 4/5'inin oyu gereklidir.

Ortak yerden faydalanmayı daha elverişli, daha düzgün bir hale getirmek için
değişiklik yapmak isteniyorsa sayı ve arsa payı çoğunluğu aranmıştır.

Yönetici atanması için de sayı ve arsa payı çoğunluğu aranır.

==== YÖNETİCİ

Tek kişi yönetici olabileceği gibi 3 kişilik bir yönetim kurulu da atanabilir.
Eğer bir binanın 8 veya daha fazla bağımsız bölümü varsa yönetici atanması
mecburidir. 

Yönetici yıllık olarak arsa payı ve sayı çoğunluğu ile atanır. Eğer taraflar
anlaşamazlarsa, sulh hakimince tayin olunur.

Yönetici, kat maliklerinden biri veya dışarıdan birisi olabilir.

Yönetici ile kat malikleri arasında vekalet sözleşmesi kurulmuş olur.
Dolayısıyla yaptığı masrafları talep edebilir, işini yaparken zarara uğramışsa
bunun tazminini kat maliklerinden talep edebilir. Kat maliklerine yılda en az
bir kere hesap vermek zorundadır.

Yönetici her zaman istifa edebileceği gibi her zaman azledilebilir. Haksız azil
durumunda tazminata hak kazanabilir.

