:icons: font
:toc:
:toc-title: MÖHUK

== LEX FORI VE LEX CAUSA

Milletlerarası usul hukukuna _lex fori_ ilkesi hakimdir. _Lex fori_, ilgili
topraklarda hakim devletin hukukunun geçerli olduğunu ifade eder. İçinde
yabancılık unsuru bulunan ihtilaflarda yargılamanın her aşamasında _lex fori_
gereği mahkemenin bulunduğu yer hukukunun uygulanacaktır.

_Lex causa_ sözleşmenin esası olan hukuktur.

== YARGI VE İCRA BAĞIŞIKLIĞI

Uyuşmazlıktaki taraflardan birinin *yargı bağışıklığı* varsa Türkiye
mahkemeleri bu uyuşmazlık bakımından yargı yetkisine sahip değildir. Yargı
bağışıklığına sahip olabilecek üç grup vardır:

. *Yabancı devletler*: Eğer söz konusu hukuki ilişki yabancı devletin egemenlik
tasarrufu ise burada yabancı devletin yargı bağışıklığı vardır. Ancak yabancı
devlete, özel hukuk ilişkilerinden doğan hukuki uyuşmazlıklarda yargı muafiyeti
tanınmaz.
+
Yabancı devletin yargı bağışıklığı olmasa da *icra bağışıklığı* olabilir. İcra
bağışıklığını tespit etmek için hacze konu edilecek yabancı devlet malının
nasıl bir amaca özgülenmiş olduğuna bakılır. Kamusal amaca özgülenmiş mallar
bakımından icra bağışıklığı söz konusu iken ticari amaca özgülenmiş mallar
hacze konu edilebilir.
. *Devleti sınırsız olarak temsile yetkili kişiler*: Devleti sınırsız olarak
temsil yetkisine sahip kişiler devlet başkanlarıdır. Türkiye bakımından
cumhurbaşkanı, başbakan ve dışişleri bakanı bu kapsama girer. Bunlar görevleri
süresince yargı bağışıklığına tabidir.
. *Diplomatik temsilciler ve konsoloslar*:

.. *Diplomatik temsilciler*: Diplomatik temsilcilerin yargı bağışıklığı
_Diplomatik İlişkiler Hakkında Viyana Sözleşmesi_ uyarınca belirlenir. Bu
sözleşmede üç halde diplomatik temsilcilerin yargı bağışıklığının olmadığı
belirtilmiştir.
+
[caption=""]
.Diplomatik temsilcinin yargı bağışıklığının olmadığı haller
====
... Taşınmaz üzerindeki ayni hak davaları
... Mirasa ilişkin davalar
... Mesleki veya ticari faaliyetlerden doğan eylemler
====
+
TIP: Yabancı devlet diplomatik temsilcisinin yargı bağışıklığından feragat
edebilir.
.. *Konsoloslar*: Konsolosların yargı bağışıklığına dair hükümler __Konsolosluk
İlişkileri Hakkında Viyana Sözleşmesi__'nde düzenlenmiştir. Bu sözleşmeye göre
konsoloslar sadece *resmi görevini yerine getirirken giriştikleri eylem ve
işlemlerinde* yargı bağışıklığına sahiptir.

Yargı bağışıklığının olmadığı durumlarda tebligatın nasıl yapılacağı önem
taşır. _Lex fori_ ilkesi gereğince HMK ve Tebligat Kanunu'na göre tebligat
yapılacaktır. Tebligat Kanunu'nda tebligatın diplomatik usulle yapılacağı
düzenlenmiştir. Diplomatik usule göre mahkeme tebliğ edilmesi gereken evrakı
Adalet Bakanlığı'na, Adalet Bakanlığı Dışişleri Bakanlığı'na, Dışişleri
Bakanlığı da yabancı devletin dışişleri bakanlığına gönderecektir.

MOHUK 49/2 ile daha kısa bir usul de öngörülmüştür. Buna göre yabancı devletin
diplomatik temsilcilerine de tabligat yapılabilir.

WARNING: Diplomatik temsilci veya konsolosun tarafı olduğu bir uyuşmazlık söz
konusu ise Tebligat Kanunu'nda belirtilen diplomatik usulün işletilmesi
zorunludur.

== MİLLETLERARASI ÖZEL HUKUKTA YETKİ

*Yargı yetkisi*, bir devletin egemenlik hakkından kaynaklanan ve mahkemelerinin
kendi topraklarında olan davalara bakabilme yetkisidir. *Milletlerarası yetki*
ise devletin mahkemelerinin yargı yetkisi varken davaya bakmaya yer olarak
yetkili mahkemenin yetkisidir.

Yabancılık unsuru içeren bir ihtilaf söz konusu ise Türkiye mahkemesi ilk
olarak yargı yetkisinin var olup olmadığını inceleyecektir. Yargı yetkisi HMK
114 uyarınca bir dava şartıdır. Buna karşılık milletlerarası yetki bir ilk
itiraz olarak incelenecektir.

MOHUK 40-47 arasındaki hükümler Türkiye mahkemelerinin milletlerarası
yetkisini tesis eden yetki kurallarıdır.

NOTE: Yerleşim yeri, mutad mesken, ifa yeri gibi kavramlar _lex fori_ gereğince
Türk hukukuna göre belirlenecektir.

Milletlerarası yetki sisteminde yetki kuralları öncelikle ikiye ayrılır:
*Objektif yetki esası* ve *subjektif yetki esası*. Yetkili mahkeme kanun hükmü
uyarınca belirlenmişse objektif yetki esası söz konusudur. Ancak yetkili
mahkeme tarafların iradeleri ile belirlenmişse subjektif yetki esası söz
konusudur.

Objektif yetki esası da kendi içinde *genel milletlerarası yetki* ve *özel
milletlerarası yetki* olarak ikiye ayrılmaktadır.

=== GENEL YETKİ KURALI

[caption=""]
.MOHUK 40 - Milletlerarası yetki
====
Türk mahkemelerinin milletlerarası yetkisini, iç hukukun yer itibariyle yetki
kuralları tayin eder.
====

[caption=""]
.HMK 6 - Genel yetkili mahkeme
====
Genel yetkili mahkeme, davalı gerçek veya tüzel kişinin davanın açıldığı
tarihteki yerleşim yeri mahkemesidir.

Yerleşim yeri, 22/11/2001 tarihli ve 4721 sayılı Türk Medenî Kanunu hükümlerine
göre belirlenir.
====

==== YERLEŞİM YERİNİN TESPİTİ

===== GERÇEK KİŞİLER BAKIMINDAN

[caption=""]
.TMK 19 - Tanım
====
Yerleşim yeri bir kimsenin sürekli kalma niyetiyle oturduğu yerdir.

Bir kimsenin aynı zamanda birden çok yerleşim yeri olamaz.

Bu kural ticarî ve sınaî kuruluşlar hakkında uygulanmaz.
====

[caption=""]
.TMK 20 - Yerleşim yerinin değiştirilmesi ve oturma yeri
====
Bir yerleşim yerinin değiştirilmesi yenisinin edinilmesine bağlıdır.

Önceki yerleşim yeri belli olmayan veya yabancı ülkedeki yerleşim yerini
bıraktığı hâlde Türkiye'de henüz bir yerleşim yeri edinmemiş olan kimsenin
hâlen oturduğu yer, yerleşim yeri sayılır.
====

[caption=""]
.HMK 9 - Türkiye’de yerleşim yerinin bulunmaması hâlinde yetki
====
Türkiye’de yerleşim yeri bulunmayanlar hakkında genel yetkili mahkeme,
davalının Türkiye’deki mutad meskeninin bulunduğu yer mahkemesidir. Ancak,
diğer özel yetki hâlleri saklı kalmak üzere, malvarlığı haklarına ilişkin dava,
uyuşmazlık konusu malvarlığı unsurunun bulunduğu yerde de açılabilir.
====

TIP: *Mutad mesken*, kişinin hayat ilişkilerinin yoğunlaştığı yerdir.

NOTE: Kişinin *yabancı ülkede yerleşim yeri varsa ancak Türkiye'de yerleşim
yeri yoksa* HMK 9 uyarınca mutad mesken mahkemesi milletlerarası yetkili
mahkeme olacaktır. Eğer *yabancı ülkede yerleşim yeri yoksa veya belli değilse*
bu kişi bakımından Türkiye'de halen oturduğu yer mahkemesi yetki kazanacaktır.

===== TÜZEL KİŞİLER BAKIMINDAN

Tüzel kişinin yerleşim yeri, kuruluş belgesinde başka bir hüküm bulunmadıkça
işlerinin yönetildiği yerdir.

Tüzel kişinin Türkiye'de yerleşim yeri yok ancak Türkiye'de bulunan bir şubesi
ile işlem yapılmış ise bu işlemden kaynaklanan davalar bakımından şubenin
bulunduğu yer mahkemesi yetkilidir.

Tüzel kişinin Türkiye'de ne yerleşim yeri ne de şubesi var ancak sözleşme
acente aracılığıyla akdedilmiş ise acentenin bulunduğu yer mahkemesi uyuşmazlık
bakımından milletlerarası yetkili mahkemedir.

==== KARŞI DAVADA YETKİ

[caption=""]
.HMK 13 - Karşı davada yetki
====
Kesin yetkinin söz konusu olmadığı hâllerde, asıl davaya bakan mahkeme, karşı
davaya bakmaya da yetkilidir.
====

==== HAKSIZ FİİLLERDE YETKİ

[caption=""]
.HMK 16 - Haksız fiilden doğan davalarda yetki
====
Haksız fiilden doğan davalarda, haksız fiilin işlendiği veya zararın meydana
geldiği yahut gelme ihtimalinin bulunduğu yer ya da zarar görenin yerleşim yeri
mahkemesi de yetkilidir.
====

==== İHTİYATİ HACİZ VE İHTİYATİ TEDBİR

İhtiyati haciz ve ihtiyati tedbir kararları kesin hüküm niteliği taşımayan
kararlardır. Bunlar bir uyuşmazlığı mutlak olarak hem şekli anlamda hem de
maddi anlamda sona erdirmediği için yabancı mahkemelerce verilen ihtiyati haciz
veya ihtiyati tedbir kararları Türk mahkemelerince tanınmayacaktır.

İhtiyati tedbir sadece uyuşmazlık konusu şey üzerinde sağlanabilir.

İhtiyati haciz kararı sadece para alacakları için getirilmiş bir koruma
tedbiridir. İhtiyati haciz kararı ile birlikte borçlunun elindeki veya üçüncü
şahısta bulunan borçluya ait taşınır ve taşınmaz mallar ile alacaklar ve diğer
haklar haczedilebilir.

[caption=""]
.İİK 257 - İhtiyati haciz şartları
====
Rehinle temin edilmemiş ve vadesi gelmiş bir para borcunun alacaklısı,
borçlunun yedinde veya üçüncü şahısta olan taşınır ve taşınmaz mallarını ve
alacaklariyle diğer haklarını ihtiyaten haczettirebilir.

Vadesi gelmemiş borçtan dolayı yalnız aşağıdaki hallerde ihtiyati haciz
istenebilir:

. Borçlunun muayyen yerleşim yeri yoksa;
. Borçlu taahhütlerinden kurtulmak maksadiyle mallarını gizlemeğe, kaçırmağa
veya kendisi kaçmağa hazırlanır yahut kaçar ya da bu maksatla alacaklının
haklarını ihlâl eden hileli işlemlerde bulunursa;

Bu suretle ihtiyati haciz konulursa borç yalnız borçlu hakkında muacceliyet kesbeder.
====

[NOTE]
====
Bir yabancı mahkeme kararı tanınıp tenfiz edilmemiş ise bu yabancı mahkeme
kararına konu olan alacak vadesi gelmiş bir alacak olarak nitelendirilebilir
mi?

Bazı görüşlere göre böyle bir alacak muaccel değildir, dolayısıyla İİK 257/1
uyarınca ihtiyati haciz talep edilemez ancak İİK 257/2 uyarınca edilebilir.
Diğer bir görüşe göre ise Türk hukukuna göre alacağın muaccel olduğu
söylenebiliyorsa, tanınıp tenfiz edilmemiş de olsa İİK 257/1'e göre muaccel
olmuş bir alacaktır ve ihtiyati haciz talep edilebilir.
====

[caption=""]
.İİK 258 - İhtiyati haciz kararı
====
(1) İhtiyati hacze 50 nci maddeye göre yetkili mahkeme tarafından karar
verilir. Alacaklı alacağı ve icabında haciz sebepleri hakkında mahkemeye
kanaat getirecek deliller göstermeğe mecburdur.
====

[caption=""]
.İİK 50 - Yetki ve itirazları
====
(1) Para veya teminat borcu için takip hususunda Hukuk Usulü Muhakemeleri
Kanununun yetkiye dair hükümleri kıyas yolu ile tatbik olunur. Şu kadar ki,
takibe esas olan akdin yapıldığı icra dairesi de takibe yetkilidir.
====

[NOTE]
====
İhtiyati haciz veya ihtiyati tedbir talebinin dayandığı uyuşmazlığa ilişkin
olarak Türkiye'de davayı görmeye yer itibariyle yetkili bir mahkeme yok ise
ihtiyati tedbir veya ihtiyati haciz kararı alınamayacak mıdır?

Kürsü ve çoğunluk görüşüne göre yabancılık unsuru içeren bir ihtilafta alacaklı
bu koruma tedbirlerinden mahrum bırakılmamalı ve Türk mahkemelerinin egemenlik
yetkisi tanınmalıdır. Taraflar arasında bir yetki anlaşması olmasaydı söz
konusu uyuşmazlık ile ilgili hangi yer mahkemesi yetkili olacak ise o
mahkemeden ihtiyati tedbir ve ihtiyati haciz kararı alınabilmelidir.

*Ancak Türkiye'de yer itibariyle yetkili bir mahkeme yoksa, ihtiyati haciz veya
ihtiyati tebdir kararı alınamayacaktır.*
====

=== ÖZEL YETKİ KURALLARI

WARNING: MOHUK'taki genel yetki-özel yetki ilişkisi HMK'dan farklıdır. HMK'da
özel yetki genel yetkiye alternatif olurken MOHUK'ta özel yetki halleri Türkiye
mahkemelerinin yetkili olup olmadığına *nihai* olarak karar vermektedir. Yani
özel yetki kurallarının kapsamına giren bir hal söz konusu ancak yapılan
değerlendirme sonucu Türkiye mahkemelerinin yetki olmadığı anlaşılmış ise genel
yetki kuralı da uygulanamaz.

NOTE: HMK'daki kesin yetki halleri milletlerarası usul hukuku bakımından Türk
mahkemelerine münhasır yetki kazandırmaz. Türk mahkemelerinin münhasıran
yetkili olması için o davanın yer itibariyle yetkili Türk mahkemesi dışında
görülmesini engelleyecek güçlü bir menfaatin olması gerekir.

IMPORTANT: Bir uyuşmazlık bakımından Türk mahkemeleri münhasıran yetkili ise
taraflar yetki anlaşması ile başka yer mahkemelerini yetkili kılamazlar. Ayrıca
söz konusu dava münhasıran yetkili olan Türk mahkemesi dışında yabancı bir
mahkemede açılmış ise Türk mahkemelerinde söz konusu yabancı mahkeme kararı
tanınmaz.

==== VATANDAŞLARIN KİŞİ HÂLLERİNE İLİŞKİN DAVALAR

[caption=""]
.MOHUK 41 - Türklerin kişi hâllerine ilişkin davalar
====
Türk vatandaşlarının kişi hâllerine ilişkin davaları, yabancı ülke
mahkemelerinde açılmadığı veya açılamadığı takdirde Türkiye’de yer itibariyle
yetkili mahkemede, bulunmaması hâlinde ilgilinin sâkin olduğu yer, Türkiye’de
sâkin değilse Türkiye’deki son yerleşim yeri mahkemesinde, o da bulunmadığı
takdirde Ankara, İstanbul veya İzmir mahkemelerinden birinde görülür.
====

Aşamalı olarak:

. Türkiye'de yer itibariyle yetkili mahkeme
. Yoksa, ilgilinin sakin olduğu yer mahkemesi
. Türkiye'de sakin olduğu yer yoksa, Türkiye'deki son yerleşim yeri mahkemesi
. Türkiye'de hiç yerleşim yeri yoksa, Ankara, İstanbul veya İzmir
mahkemelerinden biri

Bir davanın Türk vatandaşlarının kişi hallerine ilişkin sayılması için:

. Taraflardan biri Türk vatandaşı olmalıdır.
+
TIP: Türk vatandaşı olma hali Vatandaşlık Kanunu'na göre belirlenir. Bir kişi
Türkiye nüfus sistemine kayıtlı olmasa bile Vatandaşlık Kanunu'na göre
vatandaşlığı kazanmış ise MOHUK 41 işletilecektir.
. Dava sonucunda verilen karar kişinin şahsi statüsünü değiştirecek olmalıdır.
Örneğin ehliyetin kısıtlanması, gaiplik, boşanma, velayet.
+
TIP: Yargıtay, yakın zamanlı bir kararında, çocuk mallarının korunmasına
ilişkin davaların kişi hallerine ilişkin olduğuna içtihat etmiştir.
. Davanın yabancı mahkemede açılmaması veya açılamaması gerekmektedir.
+
NOTE: Bu durum *milletlerarası derdestliğin* kabul edildiği bir haldir.
Derdestliğin olması için aynı taraflar arasında, aynı konuda ve aynı sebeplerle
bir dava açılması gerekir. Bir görüşe göre MÖHUK 41 uyarınca Türk
mahkemelerinin milletlerarası yetkisinin engellenmesi yabancı bir mahkemede
görülmekte olan bir davanın olması halinde söz konusu olacaktır. Diğer bir
görüşe göre ise yabancı ülkede açılan davada karar verilmişse bu da Türk
mahkemelerinin milletlerarası yetkisi bakımından engel teşkil edecektir.

==== YABANCILARIN KİŞİ HÂLLERİNE İLİŞKİN DAVALAR

[caption=""]
.MOHUK 42 - Yabancıların kişi hâllerine ilişkin bazı davalar
====
Türkiye'de yerleşim yeri bulunmayan yabancı hakkında vesâyet, kayyımlık,
kısıtlılık, gaiplik ve ölmüş sayılma kararları ilgilinin Türkiye'de sâkin
olduğu yer, sâkin değilse mallarının bulunduğu yer mahkemesince verilir.
====

MÖHUK 42'nin uygulanabilmesi için öncelikle Türkiye'de yerleşim yeri bulunmayan
bir yabancının söz konusu olması gerekir.

[caption=""]
.MOHUK 10 - Vesâyet, kısıtlılık ve kayyımlık
====
(1) Vesâyet veya kısıtlılık kararı verilmesi veya sona erdirilmesi sebepleri,
hakkında vesâyet veya kısıtlılık kararının verilmesi veya sona erdirilmesi
istenen kişinin millî hukukuna tâbidir.

(2) Yabancının millî hukukuna göre vesâyet veya kısıtlılık kararı verilmesi
mümkün olmayan hâllerde bu kişinin mutad meskeni Türkiye'de ise Türk hukukuna
göre vesâyet veya kısıtlılık kararı verilebilir veya kaldırılabilir. Kişinin
zorunlu olarak Türkiye’de bulunduğu hâllerde de Türk hukuku uygulanır.

(3) Vesâyet veya kısıtlılık kararı verilmesi veya sona erdirilmesi sebepleri
dışında kalan bütün kısıtlılık veya vesâyete ilişkin hususlar ve kayyımlık Türk
hukukuna tâbidir.
====

[caption=""]
.MOHUK 11 - Gaiplik veya ölmüş sayılma
====
Gaiplik veya ölmüş sayılma kararı, hakkında karar verilecek kişinin millî
hukukuna tâbidir. Millî hukukuna göre hakkında gaiplik veya ölmüş sayılma
kararı verilemeyen kişinin mallarının Türkiye'de bulunması veya eşinin veya
mirasçılardan birinin Türk vatandaşı olması hâlinde, Türk hukukuna göre gaiplik
veya ölmüş sayılma kararı verilir.
====

MÖHUK 10 ve 11'in uygulanabilmesi için Türkiye'de yer itibariyle yetkili bir
mahkemenin olması gerekir. MÖHUK 42 burada devreye girecektir.

==== MİRAS DAVALARI

[caption=""]
.MOHUK 43 - Miras davaları
====
Mirasa ilişkin davalar ölenin Türkiye'deki son yerleşim yeri mahkemesinde, son
yerleşim yerinin Türkiye'de olmaması hâlinde terekeye dâhil malların bulunduğu
yer mahkemesinde görülür.
====

Bir kişi öldüğünde mirastan hak talep eden kişiler öncelikle mahkemeye
başvurarak mirasçılık belgesi alır. Mirasçılık belgesi almak için yapılan
başvuru bir dava değil çekişmesiz yargı işidir. Çekişmesiz yargı işleri MÖHUK
43'ün kapsamına girmemektedir. Mirasçılık belgesi başvurusu için Türkiye
mahkemelerinin milletlerarası yetkisi HMK 384'e göre belirlenecektir.

Mirasçılardan biri mirasçılık belgesinin iptalini isterse bu bir çekişmeli
yargı işidir ve dolayısıyla burada milletlerarası yetki MÖHUK 43'e göre
belirlenecektir.

TIP: Yakın zamanlı bir düzenleme ile mirasçılık belgesinin noterlerden alınma
imkanı getirilmiştir. Ancak Noter Kanununda yer alan düzenleme uyarınca
mirasçılık belgesini talep eden kişi yabancı ise noter bu belgeyi düzenleyemez.

==== İŞ SÖZLEŞMESİ VE İŞ İLİŞKİSİ DAVALARI

[caption=""]
.MOHUK 44 - İş sözleşmesi ve iş ilişkisi davaları
====
Bireysel iş sözleşmesinden veya iş ilişkisinden doğan uyuşmazlıklarda işçinin
işini mutaden yaptığı işyerinin Türkiye’de bulunduğu yer mahkemesi yetkilidir.
İşçinin, işverene karşı açtığı davalarda işverenin yerleşim yeri, işçinin
yerleşim yeri veya mutad meskeninin bulunduğu Türk mahkemeleri de yetkilidir.
====

MÖHUK 44 bir özel milletlerarası yetki kuralı tesis ettiği için artık İş
Mahkemeleri Kanunu'nda yer alan yetki kuralı uygulanmayacaktır.

==== TÜKETİCİ SÖZLEŞMESİNE İLİŞKİN DAVALAR

[caption=""]
.MOHUK 45 - Tüketici sözleşmesine ilişkin davalar
====
26 ncı maddede tanımlanan tüketici sözleşmelerinden doğan uyuşmazlıklarda,
tüketicinin seçimine göre, tüketicinin yerleşim yeri veya mutad meskeni ya da
karşı tarafın işyeri, yerleşim yeri veya mutad meskeninin bulunduğu Türk
mahkemeleri yetkilidir.

Birinci fıkra uyarınca yapılan tüketici sözleşmeleri hakkında tüketiciye karşı
açılacak davalarda yetkili mahkeme, tüketicinin Türkiye’deki mutad meskeni
mahkemesidir.
====

[caption=""]
.MOHUK 45 - Tüketici sözleşmesine ilişkin davalar
====
Meslekî veya ticarî olmayan amaçla mal veya hizmet ya da kredi sağlanmasına
yönelik tüketici sözleşmeleri, tüketicinin mutad meskeni hukukunun emredici
hükümleri uyarınca sahip olacağı asgarî koruma saklı kalmak kaydıyla,
tarafların seçtikleri hukuka tâbidir.

Tarafların hukuk seçimi yapmamış olması hâlinde, tüketicinin mutad meskeni
hukuku uygulanır. Tüketicinin mutad meskeni hukukunun uygulanabilmesi için;

.. Sözleşme, tüketicinin mutad meskeninin bulunduğu ülkede, ona gönderilen özel
bir davet üzerine veya ilân sonucunda kurulmuş ve sözleşmenin kurulması için
tüketici tarafından yapılması gerekli hukukî fiiller bu ülkede yapılmış veya
.. Diğer taraf veya onun temsilcisi, tüketicinin siparişini bu ülkede almış
veya
.. İlişkinin bir satım sözleşmesi olması hâlinde, satıcı tüketiciyi satın
almaya ikna etmek amacıyla bir gezi düzenlemiş ve tüketici de bu gezi ile
bulunduğu ülkeden başka ülkeye gidip siparişini orada vermiş,

olmalıdır.

(3) İkinci fıkradaki şartlar altında yapılan tüketici sözleşmelerinin şekline,
tüketicinin mutad meskeni hukuku uygulanır.

(4) Bu madde, paket turlar hariç, taşıma sözleşmeleri ve tüketiciye hizmetin
onun mutad meskeninin bulunduğu ülkeden başka bir ülkede sağlanması zorunlu
olan sözleşmelere uygulanmaz.
====

==== SİGORTA SÖZLEŞMESİNE İLİŞKİN DAVALAR

[caption=""]
.MOHUK 46 - Sigorta sözleşmesine ilişkin davalar
====
Sigorta sözleşmesinden doğan uyuşmazlıklarda, sigortacının esas işyeri veya
sigorta sözleşmesini yapan şubesinin ya da acentasının Türkiye’de bulunduğu yer
mahkemesi yetkilidir. Ancak sigorta ettirene, sigortalıya veya lehdara karşı
açılacak davalarda yetkili mahkeme, onların Türkiye’deki yerleşim yeri veya
mutad meskeni mahkemesidir.
====

=== YETKİ ANLAŞMASI

Yetki anlaşmaları usul hukukuna özgü sözleşmelerdir. Usuli meselelerde _lex
fori_ ilkesi hakimdir. Dolayısıyla yetki sözleşmelerinin geçerlilikleri ve
doğuracakları etkiler hakimin hukukuna göre belirlenecektir. Gerek Türkiye
mahkemelerini yetkilendiren gerekse yabancı mahkemeleri yetkilendiren yetki
sözleşmelerinin geçerlilikleri Türk hukukuna göre belirlenecektir.

Taraflar yetki anlaşması ile Türkiye mahkemelerini yetkili kılmışsa bunun
şartları ve sonuçları HMK 18'e tabi olacaktır. Eğer yabancı bir mahkeme yetkili
kılınmışsa MOHUK 47'ye tabi olacaktır.

Taraflar tacir veya kamu tüzel kişisi değil ise Türkiye mahkemelerini
yetkilendiren bir milletlerarası yetki sözleşmesi yapamazlar. Ancak
mahkemelerin yetkisi kural olarak kamu düzenine ilişkin olmadığından yetki
sözleşmesi geçersiz olsa dahi yetki itirazında bulunulmamışsa mahkeme yetkili
hale gelir.

[caption=""]
.MOHUK 47 - Yetki anlaşması ve sınırları
====
Yer itibariyle yetkinin münhasır yetki esasına göre tayin edilmediği hâllerde,
taraflar, aralarındaki yabancılık unsuru taşıyan ve borç ilişkilerinden doğan
uyuşmazlığın yabancı bir devletin mahkemesinde görülmesi konusunda
anlaşabilirler. Anlaşma, yazılı delille ispat edilmesi hâlinde geçerli olur.
Dava, ancak yabancı mahkemenin kendisini yetkisiz sayması veya Türk
mahkemelerinde yetki itirazında bulunulmaması hâlinde yetkili Türk mahkemesinde
görülür.

44, 45 ve 46 ncı maddelerde belirlenen mahkemelerin yetkisi tarafların
anlaşmasıyla bertaraf edilemez.
====

Yabancı bir mahkemenin yetki sözleşmesi ile yetkilendirilebilmesi için
aşağıdaki şartlar aranır:

. Yabancılık unsuru taşıyan bir uyuşmazlık
+
TIP: Bir görüşe göre ihtilaf bakımından yabancı bir hukuk sisteminin seçilmiş
olması da o ihtilafın yabancılık unsuru taşıdığı anlamına gelir.
. Bu uyuşmazlığın bir borç ilişkisinden kaynaklanması
. Bir münhasır yetkinin bulunmaması

CAUTION: Yetki sözleşmesiyle bir yabancı mahkemenin yetkilendirilmesi hak arama
özgürlüğüne aykırılık teşkil etmemelidir. Yetkilendirilen mahkeme hiçbir
şekilde sonuca ulaşılmasının mümkün olmadığı bir mahkeme ise, adil bir
yargılama yapılamayacağı çok açık bir şekilde ortadaysa yabancı mahkemeyi
yetkilendiren yetki sözleşmesi geçersiz olacaktır.

Geçerli bir yetki sözleşmesi ile yabancı bir mahkemeye yetki verilmesi halinde
MÖHUK 47 uyarınca yabancı mahkeme lehine münhasır yetki tesis edilmiş olur.
Ancak yabancı mahkeme yapılmış yetki sözleşmesini geçerli kabul etmeyerek
kendini yetkisiz görebilir. Yabancı mahkeme kendini yetkisiz gördüğün de dava
artık Türkiye mahkemelerinde görülebilecektir.

Yine yabancı bir mahkemeye yetki veren yetki sözleşmesine rağmen taraflardan
biri Türkiye mahkemelerinde dava açmış ve karşı taraf yetki itirazında
bulunmamışsa Türkiye mahkemesi yetkili olacaktır.

TIP: Yargıtay, bir kararında yetki sözleşmesindeki "Alman mahkemeleri
yetkilidir" ifadesini belirsiz bulmuş ve yetkilendirilen mahkemenin belirli
olması gerektiğini söylemiştir. _Kürsüye göre_ bunu her ülkenin iç hukuku tayin
eder. Dolayısıyla yabancı mahkemenin yetkilendirilmesi için ülke isminin
belirtilmesi yeterlidir.

== TARAFLAR

=== DAVA EHLİYETİ

Bir gerçek veya tüzel kişinin dava ehliyetine sahip olabilmesi için, yani
davacı olabilmesi için fiil ehliyetine sahip olması gerekir.

*Hak ve fiil ehliyeti ilgilinin milli hukukuna tabidir.*

Tüzel kişilerin veya kişi veya mal topluluklarının hak ve fiil ehliyetleri,
statülerindeki idare merkezi hukukuna tabidir. Ancak fiili idare merkezinin
Türkiye'de olması halinde Türk hukuku uygulanabilir.

=== TARAF EHLİYETİ

Taraf ehliyetine sahip olabilmek için, yani bir davada davalı olabilmek için
hak ehliyetine sahip olmak gerekir.

=== TARAF SIFATI

Sıfat, kişinin hakkı ile uyuşmazlık konusu arasında bağlantı olup olmadığını
belirler. Sıfat, uyuşmazlığın esasına uygulanacak hukuka göre belirlenir.
