:toc:
:toc-title: MÖHUK
:icons: font

== LEX FORI VE LEX CAUSA

Milletlerarası usul hukukuna _lex fori_ ilkesi hakimdir. _Lex fori_, ilgili
topraklarda hakim devletin hukukunun geçerli olduğunu ifade eder. İçinde
yabancılık unsuru bulunan ihtilaflarda yargılamanın her aşamasında _lex fori_
gereği mahkemenin bulunduğu yer hukukunun uygulanacaktır.

_Lex causa_ sözleşmenin esası olan hukuktur.

== YARGI VE İCRA BAĞIŞIKLIĞI

Uyuşmazlıktaki taraflardan birinin *yargı bağışıklığı* varsa Türkiye
mahkemeleri bu uyuşmazlık bakımından yargı yetkisine sahip değildir. Yargı
bağışıklığına sahip olabilecek üç grup vardır:

. *Yabancı devletler*: Eğer söz konusu hukuki ilişki yabancı devletin egemenlik
tasarrufu ise burada yabancı devletin yargı bağışıklığı vardır. Ancak yabancı
devlete, özel hukuk ilişkilerinden doğan hukuki uyuşmazlıklarda yargı muafiyeti
tanınmaz.
+
Yabancı devletin yargı bağışıklığı olmasa da *icra bağışıklığı* olabilir. İcra
bağışıklığını tespit etmek için hacze konu edilecek yabancı devlet malının
nasıl bir amaca özgülenmiş olduğuna bakılır. Kamusal amaca özgülenmiş mallar
bakımından icra bağışıklığı söz konusu iken ticari amaca özgülenmiş mallar
hacze konu edilebilir.
. *Devleti sınırsız olarak temsile yetkili kişiler*: Devleti sınırsız olarak
temsil yetkisine sahip kişiler devlet başkanlarıdır. Türkiye bakımından
cumhurbaşkanı, başbakan ve dışişleri bakanı bu kapsama girer. Bunlar görevleri
süresince yargı bağışıklığına tabidir.
. *Diplomatik temsilciler ve konsoloslar*:

.. *Diplomatik temsilciler*: Diplomatik temsilcilerin yargı bağışıklığı
_Diplomatik İlişkiler Hakkında Viyana Sözleşmesi_ uyarınca belirlenir. Bu
sözleşmede üç halde diplomatik temsilcilerin yargı bağışıklığının olmadığı
belirtilmiştir.
+
[caption=""]
.Diplomatik temsilcinin yargı bağışıklığının olmadığı haller
====
... Taşınmaz üzerindeki ayni hak davaları
... Mirasa ilişkin davalar
... Mesleki veya ticari faaliyetlerden doğan eylemler
====
+
TIP: Yabancı devlet diplomatik temsilcisinin yargı bağışıklığından feragat
edebilir.
.. *Konsoloslar*: Konsolosların yargı bağışıklığına dair hükümler __Konsolosluk
İlişkileri Hakkında Viyana Sözleşmesi__'nde düzenlenmiştir. Bu sözleşmeye göre
konsoloslar sadece *resmi görevini yerine getirirken giriştikleri eylem ve
işlemlerinde* yargı bağışıklığına sahiptir.

Yargı bağışıklığının olmadığı durumlarda tebligatın nasıl yapılacağı önem
taşır. _Lex fori_ ilkesi gereğince HMK ve Tebligat Kanunu'na göre tebligat
yapılacaktır. Tebligat Kanunu'nda tebligatın diplomatik usulle yapılacağı
düzenlenmiştir. Diplomatik usule göre mahkeme tebliğ edilmesi gereken evrakı
Adalet Bakanlığı'na, Adalet Bakanlığı Dışişleri Bakanlığı'na, Dışişleri
Bakanlığı da yabancı devletin dışişleri bakanlığına gönderecektir.

MOHUK 49/2 ile daha kısa bir usul de öngörülmüştür. Buna göre yabancı devletin
diplomatik temsilcilerine de tabligat yapılabilir.

WARNING: Diplomatik temsilci veya konsolosun tarafı olduğu bir uyuşmazlık söz
konusu ise Tebligat Kanunu'nda belirtilen diplomatik usulün işletilmesi
zorunludur.

== MİLLETLERARASI ÖZEL HUKUKTA YETKİ

*Yargı yetkisi*, bir devletin egemenlik hakkından kaynaklanan ve mahkemelerinin
kendi topraklarında olan davalara bakabilme yetkisidir. *Milletlerarası yetki*
ise devletin mahkemelerinin yargı yetkisi varken davaya bakmaya yer olarak
yetkili mahkemenin yetkisidir.

Yabancılık unsuru içeren bir ihtilaf söz konusu ise Türkiye mahkemesi ilk
olarak yargı yetkisinin var olup olmadığını inceleyecektir. Yargı yetkisi HMK
114 uyarınca bir dava şartıdır. Buna karşılık milletlerarası yetki bir ilk
itiraz olarak incelenecektir.

MOHUK 40-47 arasındaki hükümler Türkiye mahkemelerinin milletlerarası
yetkisini tesis eden yetki kurallarıdır.

NOTE: Yerleşim yeri, mutad mesken, ifa yeri gibi kavramlar _lex fori_ gereğince
Türk hukukuna göre belirlenecektir.

Milletlerarası yetki sisteminde yetki kuralları öncelikle ikiye ayrılır:
*Objektif yetki esası* ve *subjektif yetki esası*. Yetkili mahkeme kanun hükmü
uyarınca belirlenmişse objektif yetki esası söz konusudur. Ancak yetkili
mahkeme tarafların iradeleri ile belirlenmişse subjektif yetki esası söz
konusudur.

Objektif yetki esası da kendi içinde *genel milletlerarası yetki* ve *özel
milletlerarası yetki* olarak ikiye ayrılmaktadır.

=== GENEL YETKİ KURALI

[caption=""]
.MOHUK 40 - Milletlerarası yetki
====
Türk mahkemelerinin milletlerarası yetkisini, iç hukukun yer itibariyle yetki
kuralları tayin eder.
====

[caption=""]
.HMK 6 - Genel yetkili mahkeme
====
Genel yetkili mahkeme, davalı gerçek veya tüzel kişinin davanın açıldığı
tarihteki yerleşim yeri mahkemesidir.

Yerleşim yeri, 22/11/2001 tarihli ve 4721 sayılı Türk Medenî Kanunu hükümlerine
göre belirlenir.
====

==== YERLEŞİM YERİNİN TESPİTİ

===== GERÇEK KİŞİLER BAKIMINDAN

[caption=""]
.TMK 19 - Tanım
====
Yerleşim yeri bir kimsenin sürekli kalma niyetiyle oturduğu yerdir.

Bir kimsenin aynı zamanda birden çok yerleşim yeri olamaz.

Bu kural ticarî ve sınaî kuruluşlar hakkında uygulanmaz.
====

[caption=""]
.TMK 20 - Yerleşim yerinin değiştirilmesi ve oturma yeri
====
Bir yerleşim yerinin değiştirilmesi yenisinin edinilmesine bağlıdır.

Önceki yerleşim yeri belli olmayan veya yabancı ülkedeki yerleşim yerini
bıraktığı hâlde Türkiye'de henüz bir yerleşim yeri edinmemiş olan kimsenin
hâlen oturduğu yer, yerleşim yeri sayılır.
====

[caption=""]
.HMK 9 - Türkiye’de yerleşim yerinin bulunmaması hâlinde yetki
====
Türkiye’de yerleşim yeri bulunmayanlar hakkında genel yetkili mahkeme,
davalının Türkiye’deki mutad meskeninin bulunduğu yer mahkemesidir. Ancak,
diğer özel yetki hâlleri saklı kalmak üzere, malvarlığı haklarına ilişkin dava,
uyuşmazlık konusu malvarlığı unsurunun bulunduğu yerde de açılabilir.
====

TIP: *Mutad mesken*, kişinin hayat ilişkilerinin yoğunlaştığı yerdir.

NOTE: Kişinin *yabancı ülkede yerleşim yeri varsa ancak Türkiye'de yerleşim
yeri yoksa* HMK 9 uyarınca mutad mesken mahkemesi milletlerarası yetkili
mahkeme olacaktır. Eğer *yabancı ülkede yerleşim yeri yoksa veya belli değilse*
bu kişi bakımından Türkiye'de halen oturduğu yer mahkemesi yetki kazanacaktır.

===== TÜZEL KİŞİLER BAKIMINDAN

Tüzel kişinin yerleşim yeri, kuruluş belgesinde başka bir hüküm bulunmadıkça
işlerinin yönetildiği yerdir.

Tüzel kişinin Türkiye'de yerleşim yeri yok ancak Türkiye'de bulunan bir şubesi
ile işlem yapılmış ise bu işlemden kaynaklanan davalar bakımından şubenin
bulunduğu yer mahkemesi yetkilidir.

Tüzel kişinin Türkiye'de ne yerleşim yeri ne de şubesi var ancak sözleşme
acente aracılığıyla akdedilmiş ise acentenin bulunduğu yer mahkemesi uyuşmazlık
bakımından milletlerarası yetkili mahkemedir.

==== KARŞI DAVADA YETKİ

[caption=""]
.HMK 13 - Karşı davada yetki
====
Kesin yetkinin söz konusu olmadığı hâllerde, asıl davaya bakan mahkeme, karşı
davaya bakmaya da yetkilidir.
====

==== HAKSIZ FİİLLERDE YETKİ

[caption=""]
.HMK 16 - Haksız fiilden doğan davalarda yetki
====
Haksız fiilden doğan davalarda, haksız fiilin işlendiği veya zararın meydana
geldiği yahut gelme ihtimalinin bulunduğu yer ya da zarar görenin yerleşim yeri
mahkemesi de yetkilidir.
====

==== İHTİYATİ HACİZ VE İHTİYATİ TEDBİR

İhtiyati haciz ve ihtiyati tedbir kararları kesin hüküm niteliği taşımayan
kararlardır. Bunlar bir uyuşmazlığı mutlak olarak hem şekli anlamda hem de
maddi anlamda sona erdirmediği için yabancı mahkemelerce verilen ihtiyati haciz
veya ihtiyati tedbir kararları Türk mahkemelerince tanınmayacaktır.

İhtiyati tedbir sadece uyuşmazlık konusu şey üzerinde sağlanabilir.

İhtiyati haciz kararı sadece para alacakları için getirilmiş bir koruma
tedbiridir. İhtiyati haciz kararı ile birlikte borçlunun elindeki veya üçüncü
şahısta bulunan borçluya ait taşınır ve taşınmaz mallar ile alacaklar ve diğer
haklar haczedilebilir.

[caption=""]
.İİK 257 - İhtiyati haciz şartları
====
Rehinle temin edilmemiş ve vadesi gelmiş bir para borcunun alacaklısı,
borçlunun yedinde veya üçüncü şahısta olan taşınır ve taşınmaz mallarını ve
alacaklariyle diğer haklarını ihtiyaten haczettirebilir.

Vadesi gelmemiş borçtan dolayı yalnız aşağıdaki hallerde ihtiyati haciz
istenebilir:

. Borçlunun muayyen yerleşim yeri yoksa;
. Borçlu taahhütlerinden kurtulmak maksadiyle mallarını gizlemeğe, kaçırmağa
veya kendisi kaçmağa hazırlanır yahut kaçar ya da bu maksatla alacaklının
haklarını ihlâl eden hileli işlemlerde bulunursa;

Bu suretle ihtiyati haciz konulursa borç yalnız borçlu hakkında muacceliyet kesbeder.
====

[NOTE]
====
Bir yabancı mahkeme kararı tanınıp tenfiz edilmemiş ise bu yabancı mahkeme
kararına konu olan alacak vadesi gelmiş bir alacak olarak nitelendirilebilir
mi?

Bazı görüşlere göre böyle bir alacak muaccel değildir, dolayısıyla İİK 257/1
uyarınca ihtiyati haciz talep edilemez ancak İİK 257/2 uyarınca edilebilir.
Diğer bir görüşe göre ise Türk hukukuna göre alacağın muaccel olduğu
söylenebiliyorsa, tanınıp tenfiz edilmemiş de olsa İİK 257/1'e göre muaccel
olmuş bir alacaktır ve ihtiyati haciz talep edilebilir.
====

[caption=""]
.İİK 258 - İhtiyati haciz kararı
====
(1) İhtiyati hacze 50 nci maddeye göre yetkili mahkeme tarafından karar
verilir. Alacaklı alacağı ve icabında haciz sebepleri hakkında mahkemeye
kanaat getirecek deliller göstermeğe mecburdur.
====

[caption=""]
.İİK 50 - Yetki ve itirazları
====
(1) Para veya teminat borcu için takip hususunda Hukuk Usulü Muhakemeleri
Kanununun yetkiye dair hükümleri kıyas yolu ile tatbik olunur. Şu kadar ki,
takibe esas olan akdin yapıldığı icra dairesi de takibe yetkilidir.
====

[NOTE]
====
İhtiyati haciz veya ihtiyati tedbir talebinin dayandığı uyuşmazlığa ilişkin
olarak Türkiye'de davayı görmeye yer itibariyle yetkili bir mahkeme yok ise
ihtiyati tedbir veya ihtiyati haciz kararı alınamayacak mıdır?

Kürsü ve çoğunluk görüşüne göre yabancılık unsuru içeren bir ihtilafta alacaklı
bu koruma tedbirlerinden mahrum bırakılmamalı ve Türk mahkemelerinin egemenlik
yetkisi tanınmalıdır. Taraflar arasında bir yetki anlaşması olmasaydı söz
konusu uyuşmazlık ile ilgili hangi yer mahkemesi yetkili olacak ise o
mahkemeden ihtiyati tedbir ve ihtiyati haciz kararı alınabilmelidir.

*Ancak Türkiye'de yer itibariyle yetkili bir mahkeme yoksa, ihtiyati haciz veya
ihtiyati tebdir kararı alınamayacaktır.*
====

=== ÖZEL YETKİ KURALLARI

WARNING: MOHUK'taki genel yetki-özel yetki ilişkisi HMK'dan farklıdır. HMK'da
özel yetki genel yetkiye alternatif olurken MOHUK'ta özel yetki halleri Türkiye
mahkemelerinin yetkili olup olmadığına *nihai* olarak karar vermektedir. Yani
özel yetki kurallarının kapsamına giren bir hal söz konusu ancak yapılan
değerlendirme sonucu Türkiye mahkemelerinin yetki olmadığı anlaşılmış ise genel
yetki kuralı da uygulanamaz.

NOTE: HMK'daki kesin yetki halleri milletlerarası usul hukuku bakımından Türk
mahkemelerine münhasır yetki kazandırmaz. Türk mahkemelerinin münhasıran
yetkili olması için o davanın yer itibariyle yetkili Türk mahkemesi dışında
görülmesini engelleyecek güçlü bir menfaatin olması gerekir.

IMPORTANT: Bir uyuşmazlık bakımından Türk mahkemeleri münhasıran yetkili ise
taraflar yetki anlaşması ile başka yer mahkemelerini yetkili kılamazlar. Ayrıca
söz konusu dava münhasıran yetkili olan Türk mahkemesi dışında yabancı bir
mahkemede açılmış ise Türk mahkemelerinde söz konusu yabancı mahkeme kararı
tanınmaz.

==== VATANDAŞLARIN KİŞİ HÂLLERİNE İLİŞKİN DAVALAR

[caption=""]
.MOHUK 41 - Türklerin kişi hâllerine ilişkin davalar
====
Türk vatandaşlarının kişi hâllerine ilişkin davaları, yabancı ülke
mahkemelerinde açılmadığı veya açılamadığı takdirde Türkiye’de yer itibariyle
yetkili mahkemede, bulunmaması hâlinde ilgilinin sâkin olduğu yer, Türkiye’de
sâkin değilse Türkiye’deki son yerleşim yeri mahkemesinde, o da bulunmadığı
takdirde Ankara, İstanbul veya İzmir mahkemelerinden birinde görülür.
====

Aşamalı olarak:

. Türkiye'de yer itibariyle yetkili mahkeme
. Yoksa, ilgilinin sakin olduğu yer mahkemesi
. Türkiye'de sakin olduğu yer yoksa, Türkiye'deki son yerleşim yeri mahkemesi
. Türkiye'de hiç yerleşim yeri yoksa, Ankara, İstanbul veya İzmir
mahkemelerinden biri

Bir davanın Türk vatandaşlarının kişi hallerine ilişkin sayılması için:

. Taraflardan biri Türk vatandaşı olmalıdır.
+
TIP: Türk vatandaşı olma hali Vatandaşlık Kanunu'na göre belirlenir. Bir kişi
Türkiye nüfus sistemine kayıtlı olmasa bile Vatandaşlık Kanunu'na göre
vatandaşlığı kazanmış ise MOHUK 41 işletilecektir.
. Dava sonucunda verilen karar kişinin şahsi statüsünü değiştirecek olmalıdır.
Örneğin ehliyetin kısıtlanması, gaiplik, boşanma, velayet.
+
TIP: Yargıtay, yakın zamanlı bir kararında, çocuk mallarının korunmasına
ilişkin davaların kişi hallerine ilişkin olduğuna içtihat etmiştir.
. Davanın yabancı mahkemede açılmaması veya açılamaması gerekmektedir.
+
NOTE: Bu durum *milletlerarası derdestliğin* kabul edildiği bir haldir.
Derdestliğin olması için aynı taraflar arasında, aynı konuda ve aynı sebeplerle
bir dava açılması gerekir. Bir görüşe göre MÖHUK 41 uyarınca Türk
mahkemelerinin milletlerarası yetkisinin engellenmesi yabancı bir mahkemede
görülmekte olan bir davanın olması halinde söz konusu olacaktır. Diğer bir
görüşe göre ise yabancı ülkede açılan davada karar verilmişse bu da Türk
mahkemelerinin milletlerarası yetkisi bakımından engel teşkil edecektir.

==== YABANCILARIN KİŞİ HÂLLERİNE İLİŞKİN DAVALAR

[caption=""]
.MOHUK 42 - Yabancıların kişi hâllerine ilişkin bazı davalar
====
Türkiye'de yerleşim yeri bulunmayan yabancı hakkında vesâyet, kayyımlık,
kısıtlılık, gaiplik ve ölmüş sayılma kararları ilgilinin Türkiye'de sâkin
olduğu yer, sâkin değilse mallarının bulunduğu yer mahkemesince verilir.
====

MÖHUK 42'nin uygulanabilmesi için öncelikle Türkiye'de yerleşim yeri bulunmayan
bir yabancının söz konusu olması gerekir.

[caption=""]
.MOHUK 10 - Vesâyet, kısıtlılık ve kayyımlık
====
(1) Vesâyet veya kısıtlılık kararı verilmesi veya sona erdirilmesi sebepleri,
hakkında vesâyet veya kısıtlılık kararının verilmesi veya sona erdirilmesi
istenen kişinin millî hukukuna tâbidir.

(2) Yabancının millî hukukuna göre vesâyet veya kısıtlılık kararı verilmesi
mümkün olmayan hâllerde bu kişinin mutad meskeni Türkiye'de ise Türk hukukuna
göre vesâyet veya kısıtlılık kararı verilebilir veya kaldırılabilir. Kişinin
zorunlu olarak Türkiye’de bulunduğu hâllerde de Türk hukuku uygulanır.

(3) Vesâyet veya kısıtlılık kararı verilmesi veya sona erdirilmesi sebepleri
dışında kalan bütün kısıtlılık veya vesâyete ilişkin hususlar ve kayyımlık Türk
hukukuna tâbidir.
====

[caption=""]
.MOHUK 11 - Gaiplik veya ölmüş sayılma
====
Gaiplik veya ölmüş sayılma kararı, hakkında karar verilecek kişinin millî
hukukuna tâbidir. Millî hukukuna göre hakkında gaiplik veya ölmüş sayılma
kararı verilemeyen kişinin mallarının Türkiye'de bulunması veya eşinin veya
mirasçılardan birinin Türk vatandaşı olması hâlinde, Türk hukukuna göre gaiplik
veya ölmüş sayılma kararı verilir.
====

MÖHUK 10 ve 11'in uygulanabilmesi için Türkiye'de yer itibariyle yetkili bir
mahkemenin olması gerekir. MÖHUK 42 burada devreye girecektir.

==== MİRAS DAVALARI

[caption=""]
.MOHUK 43 - Miras davaları
====
Mirasa ilişkin davalar ölenin Türkiye'deki son yerleşim yeri mahkemesinde, son
yerleşim yerinin Türkiye'de olmaması hâlinde terekeye dâhil malların bulunduğu
yer mahkemesinde görülür.
====

Bir kişi öldüğünde mirastan hak talep eden kişiler öncelikle mahkemeye
başvurarak mirasçılık belgesi alır. Mirasçılık belgesi almak için yapılan
başvuru bir dava değil çekişmesiz yargı işidir. Çekişmesiz yargı işleri MÖHUK
43'ün kapsamına girmemektedir. Mirasçılık belgesi başvurusu için Türkiye
mahkemelerinin milletlerarası yetkisi HMK 384'e göre belirlenecektir.

Mirasçılardan biri mirasçılık belgesinin iptalini isterse bu bir çekişmeli
yargı işidir ve dolayısıyla burada milletlerarası yetki MÖHUK 43'e göre
belirlenecektir.

TIP: Yakın zamanlı bir düzenleme ile mirasçılık belgesinin noterlerden alınma
imkanı getirilmiştir. Ancak Noter Kanununda yer alan düzenleme uyarınca
mirasçılık belgesini talep eden kişi yabancı ise noter bu belgeyi düzenleyemez.

==== İŞ SÖZLEŞMESİ VE İŞ İLİŞKİSİ DAVALARI

[caption=""]
.MOHUK 44 - İş sözleşmesi ve iş ilişkisi davaları
====
Bireysel iş sözleşmesinden veya iş ilişkisinden doğan uyuşmazlıklarda işçinin
işini mutaden yaptığı işyerinin Türkiye’de bulunduğu yer mahkemesi yetkilidir.
İşçinin, işverene karşı açtığı davalarda işverenin yerleşim yeri, işçinin
yerleşim yeri veya mutad meskeninin bulunduğu Türk mahkemeleri de yetkilidir.
====

MÖHUK 44 bir özel milletlerarası yetki kuralı tesis ettiği için artık İş
Mahkemeleri Kanunu'nda yer alan yetki kuralı uygulanmayacaktır.

==== TÜKETİCİ SÖZLEŞMESİNE İLİŞKİN DAVALAR

[caption=""]
.MOHUK 45 - Tüketici sözleşmesine ilişkin davalar
====
26 ncı maddede tanımlanan tüketici sözleşmelerinden doğan uyuşmazlıklarda,
tüketicinin seçimine göre, tüketicinin yerleşim yeri veya mutad meskeni ya da
karşı tarafın işyeri, yerleşim yeri veya mutad meskeninin bulunduğu Türk
mahkemeleri yetkilidir.

Birinci fıkra uyarınca yapılan tüketici sözleşmeleri hakkında tüketiciye karşı
açılacak davalarda yetkili mahkeme, tüketicinin Türkiye’deki mutad meskeni
mahkemesidir.
====

[caption=""]
.MOHUK 45 - Tüketici sözleşmesine ilişkin davalar
====
Meslekî veya ticarî olmayan amaçla mal veya hizmet ya da kredi sağlanmasına
yönelik tüketici sözleşmeleri, tüketicinin mutad meskeni hukukunun emredici
hükümleri uyarınca sahip olacağı asgarî koruma saklı kalmak kaydıyla,
tarafların seçtikleri hukuka tâbidir.

Tarafların hukuk seçimi yapmamış olması hâlinde, tüketicinin mutad meskeni
hukuku uygulanır. Tüketicinin mutad meskeni hukukunun uygulanabilmesi için;

.. Sözleşme, tüketicinin mutad meskeninin bulunduğu ülkede, ona gönderilen özel
bir davet üzerine veya ilân sonucunda kurulmuş ve sözleşmenin kurulması için
tüketici tarafından yapılması gerekli hukukî fiiller bu ülkede yapılmış veya
.. Diğer taraf veya onun temsilcisi, tüketicinin siparişini bu ülkede almış
veya
.. İlişkinin bir satım sözleşmesi olması hâlinde, satıcı tüketiciyi satın
almaya ikna etmek amacıyla bir gezi düzenlemiş ve tüketici de bu gezi ile
bulunduğu ülkeden başka ülkeye gidip siparişini orada vermiş,

olmalıdır.

(3) İkinci fıkradaki şartlar altında yapılan tüketici sözleşmelerinin şekline,
tüketicinin mutad meskeni hukuku uygulanır.

(4) Bu madde, paket turlar hariç, taşıma sözleşmeleri ve tüketiciye hizmetin
onun mutad meskeninin bulunduğu ülkeden başka bir ülkede sağlanması zorunlu
olan sözleşmelere uygulanmaz.
====

==== SİGORTA SÖZLEŞMESİNE İLİŞKİN DAVALAR

[caption=""]
.MOHUK 46 - Sigorta sözleşmesine ilişkin davalar
====
Sigorta sözleşmesinden doğan uyuşmazlıklarda, sigortacının esas işyeri veya
sigorta sözleşmesini yapan şubesinin ya da acentasının Türkiye’de bulunduğu yer
mahkemesi yetkilidir. Ancak sigorta ettirene, sigortalıya veya lehdara karşı
açılacak davalarda yetkili mahkeme, onların Türkiye’deki yerleşim yeri veya
mutad meskeni mahkemesidir.
====

=== YETKİ ANLAŞMASI

Yetki anlaşmaları usul hukukuna özgü sözleşmelerdir. Usuli meselelerde _lex
fori_ ilkesi hakimdir. Dolayısıyla yetki sözleşmelerinin geçerlilikleri ve
doğuracakları etkiler hakimin hukukuna göre belirlenecektir. Gerek Türkiye
mahkemelerini yetkilendiren gerekse yabancı mahkemeleri yetkilendiren yetki
sözleşmelerinin geçerlilikleri Türk hukukuna göre belirlenecektir.

Taraflar yetki anlaşması ile Türkiye mahkemelerini yetkili kılmışsa bunun
şartları ve sonuçları HMK 18'e tabi olacaktır. Eğer yabancı bir mahkeme yetkili
kılınmışsa MOHUK 47'ye tabi olacaktır.

Taraflar tacir veya kamu tüzel kişisi değil ise Türkiye mahkemelerini
yetkilendiren bir milletlerarası yetki sözleşmesi yapamazlar. Ancak
mahkemelerin yetkisi kural olarak kamu düzenine ilişkin olmadığından yetki
sözleşmesi geçersiz olsa dahi yetki itirazında bulunulmamışsa mahkeme yetkili
hale gelir.

[caption=""]
.MOHUK 47 - Yetki anlaşması ve sınırları
====
Yer itibariyle yetkinin münhasır yetki esasına göre tayin edilmediği hâllerde,
taraflar, aralarındaki yabancılık unsuru taşıyan ve borç ilişkilerinden doğan
uyuşmazlığın yabancı bir devletin mahkemesinde görülmesi konusunda
anlaşabilirler. Anlaşma, yazılı delille ispat edilmesi hâlinde geçerli olur.
Dava, ancak yabancı mahkemenin kendisini yetkisiz sayması veya Türk
mahkemelerinde yetki itirazında bulunulmaması hâlinde yetkili Türk mahkemesinde
görülür.

44, 45 ve 46 ncı maddelerde belirlenen mahkemelerin yetkisi tarafların
anlaşmasıyla bertaraf edilemez.
====

Yabancı bir mahkemenin yetki sözleşmesi ile yetkilendirilebilmesi için
aşağıdaki şartlar aranır:

. Yabancılık unsuru taşıyan bir uyuşmazlık
+
TIP: Bir görüşe göre ihtilaf bakımından yabancı bir hukuk sisteminin seçilmiş
olması da o ihtilafın yabancılık unsuru taşıdığı anlamına gelir.
. Bu uyuşmazlığın bir borç ilişkisinden kaynaklanması
. Bir münhasır yetkinin bulunmaması

CAUTION: Yetki sözleşmesiyle bir yabancı mahkemenin yetkilendirilmesi hak arama
özgürlüğüne aykırılık teşkil etmemelidir. Yetkilendirilen mahkeme hiçbir
şekilde sonuca ulaşılmasının mümkün olmadığı bir mahkeme ise, adil bir
yargılama yapılamayacağı çok açık bir şekilde ortadaysa yabancı mahkemeyi
yetkilendiren yetki sözleşmesi geçersiz olacaktır.

Geçerli bir yetki sözleşmesi ile yabancı bir mahkemeye yetki verilmesi halinde
MÖHUK 47 uyarınca yabancı mahkeme lehine münhasır yetki tesis edilmiş olur.
Ancak yabancı mahkeme yapılmış yetki sözleşmesini geçerli kabul etmeyerek
kendini yetkisiz görebilir. Yabancı mahkeme kendini yetkisiz gördüğün de dava
artık Türkiye mahkemelerinde görülebilecektir.

Yine yabancı bir mahkemeye yetki veren yetki sözleşmesine rağmen taraflardan
biri Türkiye mahkemelerinde dava açmış ve karşı taraf yetki itirazında
bulunmamışsa Türkiye mahkemesi yetkili olacaktır.

TIP: Yargıtay, bir kararında yetki sözleşmesindeki "Alman mahkemeleri
yetkilidir" ifadesini belirsiz bulmuş ve yetkilendirilen mahkemenin belirli
olması gerektiğini söylemiştir. _Kürsüye göre_ bunu her ülkenin iç hukuku tayin
eder. Dolayısıyla yabancı mahkemenin yetkilendirilmesi için ülke isminin
belirtilmesi yeterlidir.

== TARAFLAR

=== DAVA EHLİYETİ

Bir gerçek veya tüzel kişinin dava ehliyetine sahip olabilmesi için, yani
davacı olabilmesi için fiil ehliyetine sahip olması gerekir.

*Hak ve fiil ehliyeti ilgilinin milli hukukuna tabidir.*

Tüzel kişilerin veya kişi veya mal topluluklarının hak ve fiil ehliyetleri,
statülerindeki idare merkezi hukukuna tabidir. Ancak fiili idare merkezinin
Türkiye'de olması halinde Türk hukuku uygulanabilir.

=== TARAF EHLİYETİ

Taraf ehliyetine sahip olabilmek için, yani bir davada davalı olabilmek için
hak ehliyetine sahip olmak gerekir.

=== TARAF SIFATI

Sıfat, kişinin hakkı ile uyuşmazlık konusu arasında bağlantı olup olmadığını
belirler. Sıfat, uyuşmazlığın esasına uygulanacak hukuka göre belirlenir.

== TEBLİGAT

Türk mahkemesi yurtdışına tebligat yapacağı zaman önce tebligatı Adalet
Bakanlığına gönderir. Adalet Bakanlığı, Dışişleri Bakanlığına; Dışişleri
Bakanlığı da tebligat yapılacak kişi hangi ülkedeyse o ülkedeki Türk
büyükelçiliğine (veya konsolosluğuna); büyükelçilik de yabancı ülkedeki yetkili
makama tebligatı gönderir. *Tebligat, yabancı ülkenin kendi usulüne göre
yapılır.*

Yabancı ülkede kendisine tebligat yapılacak kimse Türk vatandaşı olduğu
takdirde tebliğ, o yerdeki Türkiye Büyükelçiliği veya Konsolosluğu aracılığıyla
da yapılabilir. Tebligat yine yabancı ülkenin kendi usulüne göre yapılır. Kişi
30 gün boyunce tebligata cevap vermezse tebligat yapılmış sayılır. *Kişi Türk
vatandaşı ise bu şekilde tebligat yapılması zorunlu değildir.*

.Milletlerarası sözleşmeler
****
*1954 yılında* imzalanmış bir sözleşme ile tebligat için şöyle bir usul
düzenlenmiştir: Mahkeme tebligatı adalet bakanlığına gönderir, adalet bakanlığı
yurtdışındaki elçiliğe gönderir, elçilik de ülkenin yetkili makamına gönderir.
Burada fark adalet bakanlığı ile elçilik arasında dışişleri bakanlığının
olmamasıdır. Ayrıca burada evrakın karşı tarafın anlayacağı şekilde tercüme
edilmesi zorunludur.

*1965 tarihli* bir sözleşmeye göre ise taraf ülkeler birer merkezi makam
belirler. Her ülke, sözleşmeye taraf bir diğer ülkenin merkezi makamına
doğrudan tebligat yapabilir. Bu sözleşmeye taraf devlet 1954 tarihli sözleşmeye
göre tebligat yapamaz. *Bu sözleşmeye göre tebligat ancak hukuki ve ticari
belgelere ilişkin yapılabilir, cezai belgeler için yapılamaz.* Bu sözleşme
ayrıca yabancı ülkedeki kişiye doğrudan tebligat yapma imkanı da getirmiştir.
Ancak bunun için yabancı ülkenin buna izin vermesi şarttır.
****

== TEMİNAT

Türk mahkemesinde dava açan, davaya katılan veya icra takibinde bulunan
*yabancı* gerçek ve tüzel kişiler, yargılama ve takip giderleriyle karşı
tarafın zarar ve ziyanını karşılamak üzere mahkemenin belirleyeceği teminatı
göstermek zorundadır.

Mahkeme, dava açanı, davaya katılanı veya icra takibi yapanı *karşılıklılık*
esasına göre teminattan muaf tutar.

NOTE: Yargıtay'a göre teminat döviz cinsinden ve %10 oranında yatırılacaktır.

.Vatansız ve mültecilerin durumu
****
_Vatansız bir kişi, daimi ikametinin bulunduğu Sözleşmeci Devlette, adli yardım
ve teminat akçesinden muafiyet dahil olmak üzere mahkemelere başvuruya ilişkin
konularda bir vatandaşınki ile aynı muameleden yararlanır._

Türk vatandaşı mutad meskeni belli olduğu takdirde teminattan muaftır.
Yukarıdaki hüküm gereği vatansız ve mülteciler için de aynı kural geçerlidir.
****

== KANUNLAR İHTİLAFI

Kanunlar ihtilafı kuralı, yabancılık unsuru içeren ihtilaflarda, olaya
uygulanma ihtimali olan hukuklardan hangisinin uygulanacağını gösteren
kuraldır.

Her kanunlar ihtilafı kuralında bir bağlama konusu ve bir bağlama noktası
vardır. *Bağlama konusu*, hakimin çözümlemesi gereken ihtilaftır. *Bağlama
noktası* ise ihtilafın hangi hukuka göre çözümlenmesi gerektiğini gösteren
yabancılık unsurudur.

Kanunlar ihtilafı kuralları, *tek yanlı* bağlama kuralları ve *çift yanlı*
bağlama kuralları olmak üzere ikiye ayrılır. Yalnızca mahkemenin hukukunu
gösteren kurallar tek yanlıdır. Hukuku, uyuşmazlık konusu üzerinden belirleyen
kurallar ise çift yanlıdır.

=== VASIFLANDIRMA

Vasıflandırma, hayat ilişkisini belirli bir hukuki kalıba sokma işlemidir. Türk
hukukunun, o hayat ilişkisine ilişkin vasıflandırması ile lex causanın
vasıflandırması uyuşmazsa vasıf ihtilafı ortaya çıkar.

Hakim dosya önüne geldiğinde lex fori vasıflandırmaya gidebileceği gibi lex
causa vasıflandırmaya da gidebilir. Ancak, *her halükarda hakim önüne gelen
bağlama konusunda lex fori vasıflandırma yapmak zorundadır*. Zira lex causa
vasıflandırmaya bu şekilde ulaşılır.

Bağlama noktasının vasıflandırılmasında ise söz konusu *bağlama noktası hangi
kanunlar ihtilafı kuralının içinde yer alıyorsa o kanunlar ihtilafı kuralının
yer aldığı hukuka göre vasıflandırma yapılır*.

=== ATIF

Uygulanacak yabancı hukukun kanunlar ihtilafı kurallarının başka bir hukuku
yetkili kılması, sadece kişiler hukuku ve aile hukukuna ilişkin ihtilaflarda
dikkate alınır ve bu hukukun maddi hukuk hükümleri uygulanır.

Yabancı hukukun kanunlar ihtilafı kurallarının başka bir devlet hukukunu işaret
etmesi halinde *devam eden atıf* söz konusudur. Yabancı hukuk kanunlar ihtilafı
kurallarının Türk hukukuna geri yollaması durumunda ise *geri yollanan atıf
(iadeli atıf)* söz konusudur.

=== HAKİMİN HUKUKU UYGULAMASI

Hakim, Türk kanunlar ihtilafı kurallarını ve bu kurallara göre yetkili olan
yabancı hukuku re'sen uygular. Hakim, yetkili yabancı hukukun muhtevasının
tespitinde tarafların yardımını isteyebilir.

NOTE: Hakim yabancı hukuku, içtihatları, doktrinleri ile birlikte bir bütün
olarak uygular.

Yabancı hukukun olaya ilişkin hükümlerinin tüm araştırmalara rağmen tespit
edilememesi halinde, Türk hukuku uygulanır.

Hakim taraflardan yardım isteyebileceği gibi _Yabancı Hukuklardan Bilgi
Edinilmesine Dair Avrupa Sözleşmesi_ tarafı olan devletlerin merkezi
makamlarından da bilgi alabilir.

TIP: Hakimin yabancı hukuku yanlış uygulaması bir bozma sebebidir.

=== KAMU DÜZENİ

Yetkili yabancı hukukun belirli bir olaya uygulanan hükmünün Türk kamu düzenine
açıkça aykırı olması halinde, bu hüküm uygulanmaz; gerekli görülen hallerde,
Türk hukuku uygulanır.

* Kamu düzeni istisnaidir.
* Türk kanunlar ihtilafı kurallarının gösterdiği yabancı hukukun uygulanmasının
*somut sonuçlarının* kamu düzenine *açıkça aykırı olması* gerekir.

=== DOĞRUDAN UYGULANAN KURALLAR

Yetkili yabancı hukukun uygulandığı durumlarda, düzenleme amacı ve uygulama
alanı bakımından Türk hukukunun doğrudan uygulanan kurallarının kapsamına giren
hallerde o kural uygulanır.

Sözleşmeden doğan ilişkinin tabi olduğu hukuk uygualnırken, sözleşmeyle sıkı
ilişkili olduğu takdirde üçüncü bir devletin hukukunun doğrudan uygulanan
kurallarına etki tanınabilir. Söz konusu kurallara etki tanımak ve uygulayıp
uygulamamak konusunda bu kuralların amacı, niteliği, muhtevası ve sonuçları
dikkate alınır.

=== TANIMA VE TENFİZ

Yabancı bir mahkeme kararının *kesin hüküm kuvvetinin* Türk hukukunda geçerli
olabilmesi için bir *tanıma* kararı verilmesi gerekir.

Yabancı bir mahkeme kararının *icra kuvvetinin* Türk hukukunda da geçerli
olabilmesi için bir *tenfiz* kararı verilmesi gerekir.

Çekişmesiz yargı işleri ancak verildiği ülkede kesin hüküm kudretine sahipse
Türk hukukunda tanınabilir.

Sadece özel hukuka ilişkin kararlar tanınabilir.

Tanıma ve tenfiz davaları çekişmeli yargı işidir.

Doktrinde nisbi harç mı alınacak maktu harç mı alınacak tartışması mevcuttur.
Uygulamada nisbi harç alınmaktadır. Ancak maktu harç alınması gerektiğine dair
Yargıtay kararları da mevcuttur. Kürsü de maktu harç alınması gerektiği
görüşündedir.

Tanıma ve tenfiz davası açarken yabancı mahkeme kararının noterden tasdikli
çevirisi de dava dilekçesine eklenmelidir.

Hakim, önüne gelen tanıma veya tenfiz meselesinde sadece kanunda yazılı
şartların varlığını denetler. Hiçbir suretle önüne getirilen yabancı mahkeme
kararının içeriğine giremez, *yeniden tetkik* yasağı söz konusudur. Hakim
sadece MOHUK 54'teki şartların varlığını inceleyecektir:

. *Mütekabiliyet:* Yabancı mahkeme kararının verildiği ülke ile Türkiye
arasında bir sözleşme olmalı ya da o devletin kanunları yabancı mahkeme
kararlarının tanınması ve tenfizini sağlayan hukuki düzenlemeye sahip
olmalıdır. Bunlardan ikisi de olmasa bile yabancı mahkeme kararının verildiği
ülkenin mahkemeleri Türk mahkeme kararlarını fiilen tanıyorsa da şart sağlanır.
+
*Tanıma için bu şart aranmaz, tenfiz için aranır.*
+
Mütekabiliyetin aranaco an esas olarak hükmün verildiği andır. Doktrinde bir
görüş, davanın açıldığı tarihi esas almaktadır.
. *Yabancı mahkeme kararının Türk mahkemelerinin münhasır yetkisine girmeyen
bir konuda verilmiş olması*
. *Yabancı mahkeme hükmünün kamu düzenine açıkça aykırı olmaması*
. *Savunma hakkının ihlal edilmiş olmaması*

Tenfiz edilen bir mahkeme kararı, Türk mahkemelerinden verilip kesinleşmesi bir
mahkeme kararı ile aynı hükümdedir. *Tenfiz mahkemesi kararlarına karşı da
kanun yoluna gidilebilir*.

NOTE: Tanıma kararı verildiği andan itibaren geriye etkilidir. Tenfiz kararı
ise verildiği anda icra kabiliyeti kazanır.

Tanıma iki türlü olabilir:

. Taraflardan biri açtığı davada delil olarak yabancı mahkeme kararını
gösterir. Bu durumda mahkeme, yabancı mahkeme kararının tanınıp tanımayacağını
incelemeli ve şartları taşıyorsa tanımalıdır. Tanımadan sonra bu karar delil
olarak kullanılabilir.
. Yabancı mahkeme kararı doğrudan tanıma davasına konu edilir.

Kararın tenfiz edilmesinde hukuki yararı olan herkes tenfiz isteminde
bulunabilir.

=== APOSTİL ŞERHİ

Yabancı ülkeden bir resmi belge alındığı zaman, bunun resmi belge gücü sadece
alındığı ülke için geçerlidir. Resmi belge gücünün Türk hukukunda da geçerli
olması için:

. Belgenin alındığı ülkedeki Türk konsolosluğundan tasdik almak
. _Yabancı Resmi Belgelerin Tasdikten Muafiyetine İlişkin Sözleşme_
çerçevesinde ülkede apostil şerhi vermeye yetkili makamdan tasdik almak

=== TAHKİM

Tahkim alternatif bir yargılama değildir, prensip olarak istisnai bir
yargılamadır. Devlet mahkemesinin istisnasını teşkil eder. Dolayısıyla kanun
koyucu tahkim konusundaki iradenin açık, kesin ve tartışmasız olmasını
aramıştır.

Tahkim iki şekilde kararlaştırılabilir:

. *Tahkim şartı:* Tahkim anlaşması sözleşmenin içinde bulunabilir. Buradaki en
önemli mesele, tahkim şartının sözleşmeye bütün olmaması ve sözleşmenin
geçersizliğinden etkilenmemesidir.
. *Tahkim sözleşmesi:* Bir uyuşmazlık ortaya çıktıktan sonra taraflar
uyuşmazlığın tahkimde görülmesi için anlaşabilirler.

Bütün uyuşmazlıklar tahkimde görülemez. Uyuşmazlığın tahkimde görülmesi için
gereken iki unsur vardır:

. Taraf iradesinden kaynaklanması
. Borç ilişkisinden kaynaklanması

Milletlerarası tahkim mevzuatımızda _Milletlerarası Ticari Tahkime İlişkin
Cenevre Sözleşmesi_ ile _Milletlerarası Tahkim Kanununda_ düzenlenmektedir.

Tahkim yargılamasında yabancı bir devletin usul hukuku kuralları kullanılmışsa
ya da hakem kararlarının verildiği yer yabancı bir ülkeyse yabancılık unsuru
sağlanmış olur.

Yabancı hakem kararının Türkiye'de tenfiz edilmesi için _Yabancı Hakem
Kararlarının Tanınması ve Tenfizine Dair New York Sözleşmesi_ ile MOHUK 62'deki
ret sebepleri dikkate alınır.

.MOHUK 62'deki ret sebepleri
****
. Tahkim sözleşmesi yapılmamış veya esas sözleşmeye tahkim şartı konulmamış ise
. Hakem kararı genel ahlaka veya kamu düzenine aykırı ise
. Hakem kararına konu olan uyuşmazlığın Türk kanunlarına göre tahkim yoluyla
çözümü mümkün değilse
. Taraflardan biri hakemler önünde usulüne göre temsil edilmemiş ve yapılan
işlemleri sonradan açıkça kabul etmemiş ise
. Hakkında hakem kararının tenfizi istenen taraf, hakem seçiminden usulen
haberdar edilmemiş yahut iddia ve savunma imkanından yoksun bırakılmış ise
. Tahkim sözleşmesi veya şartı taraflarca tabi kılındığı kanuna, bu konuda bir
anlaşma yoksa hakem hükmünün verildiği ülke hukukuna göre hükümsüz ise
. Hakemlerin seçimi veya hakemlerin uyguladıkları usul, tarafların
anlaşmasına, böyle bir anlaşma yok ise hakem hükmünün verildiği ülke hukukuna
aykırı ise
. Hakem kararı, hakem sözleşmesinde veya şartında yer almayan bir hususa
ilişkin ise veya sözleşme veya şartın sınırlarını aşıyor ise bu kısım hakkında
. Hakem kararı tabi olduğu veya verildiği ülke hukuku hükümlerine veya tabi
olduğu usule göre kesinleşmemiş yahut icra kabiliyeti veya bağlayıcılık
kazanmamış veya verildiği yerin yetkili mercii tarafından iptal edilmiş ise
****

== KANUNLAR İHTİLAFI KURALLARI

=== ŞEKİL

Hukuki işlemler, yapıldıkları ülke hukukunun veya o hukuki işlemin esası
hakkında yetkili olan hukukun maddi hukuk hükümlerinin öngördüğü şekle uygun
olarak yapılabilir.

=== ZAMANAŞIMI

*Zamanaşımı*, hukuki işlem ve ilişkinin esasına uygulanan hukuka tabidir.

=== EHLİYET

Hak ve fiil ehliyeti *ilgilinin milli hukukuna* tabidir.

Milli hukukuna göre ehliyetsiz olan bir kişi, *işlemin yapıldığı ülke hukukuna
göre ehil ise* yaptığı hukuki işlemle bağlıdır. Aile ve miras hukuku ile başka
bir ülkedeki taşınmazlar üzerindeki ayni haklara ilişkin işlemler bu hükmün
dışındadır.

Kişinin milli hukukuna göre kazandığı erginlik, vatandaşlığının değişmesi ile
sona ermez.

Tüzel kişilerin veya kişi veya mal topluluklarının hak ve fiil ehliyetleri,
statülerindeki idare merkezi hukukuna tabidir. *Ancak fiili idare merkezinin
Türkiye'de olması halinde Türk hukuku uygulanabilir*. Statüsü bulunmayan tüzel
kişiler ile tüzel kişiliği bulunmayan kişi veya mal topluluklarının ehliyeti,
fiili idare merkezi hukukuna tabidir.

=== GAİPLİK VE ÖLMÜŞ SAYILMA

Gaiplik ve ölmüş sayılma kararı, *hakkında karar verilecek kişinin milli
hukukuna tabidir*. Milli hukukuna göre hakkında gaiplik veya ölmüş sayılma
kararı verilemeyen kişinin mallarının Türkiye'de bulunması veya eşinin veya
mirasçılardan birinin Türk vatandaşı olması halinde, Türk hukukuna göre gaiplik
veya ölmüş sayılma kararı verilir.

=== VESAYET, KISITLILIK VE KAYYIMLIK

Vesayet veya kısıtlılık kararı verilmesi veya sona erdirilmesi sebepleri,
hakkında vesayet veya kısıtlılık kararının verilmesi veya sona erdirilmesi
istenen *kişinin milli hukukuna* tabidir.

Yabancının milli hukukuna göre vesayet veya kısıtlılık kararı verilmesi mümkün
olmayan hallerde bu kişinin mutad meskeni Türkiye'de ise Türk hukukuna göre
vesayet veya kısıtlılık karrı verilebilir veya kaldırılabilir. Kişinin zorunlu
olarak Türkiye'de bulunduğu hallerde de Türk hukuku uygulanır.

Vesayet ve kısıtlılık kararı verilmesi veya sona erdirilmesi sebepleri dışında
kalan bütün kısıtlılık veya vesayete ilişkin hususlar ve kayyımlık Türk
hukukuna tabidir.

NOTE: Bir uluslararası sözleşme gereği, çocuğun malları ile ilgili kayyım
atanacaksa çocuğun mutad meskeninin bulunduğu devlet hukuku uygulanır.

=== MİRAS

Miras *ölenin milli hukukuna tabidir*. Türkiye'de bulunan taşınmazlar hakkında
Türk hukuku uygulanır.

Mirasın açılması sebeplerine, iktisabına ve taksimine ilişkin hükümler
terekenin bulunduğu ülke hukukuna tabidir.

Türkiye'de bulunan mirasçısız tereke devlete kalır.

Ölüme bağlı tasarrufun şekline yukarıdaki şekil kuralı uygulanır. Ölenin milli
hukukuna uygun şekilde yapılan ölüme bağlı tasarruflar da geçerlidir.

Ölüme bağlı tasarruf ehliyeti, tasarrufta bulunanın, tasarrufun yapıldığı
andaki milli hukukuna tabidir.

=== NİŞANLILIK

Nişanlanma ehliyeti ve şartları taraflardan her birinin nişanlanma anındaki
milli hukukuna tabidir.

Nişanlılığın hükümlerine ve sonuçlarına müşterek milli hukuk, taraflar ayrı
vatandaşlıkta iseler Türk hukuku uygulanır.

NOTE: Nişanlanma kişiler hukukuna ilişkin bir mesele olduğundan her devletin
kendi hukukundaki kanunlar ihtilafı kuralları dikkate alınır.

=== EVLİLİK

Evlenme ehliyeti ve şartları, taraflardan her birinin evlenme anındaki hukukuna
tabidir.

Evliliğin şekline *yapıldığı ülke hukuku* uygulanır.

Evliliğin genel hükümleri, eşlerin müşterek milli hukukuna tabidir. Tarafların
ayrı vatandaşlıkta olmaları halinde müşterek mutad mesken hukuku, bulunmadığı
takdirde Türk hukuku uygulanır.

NOTE: Evlenme kişiler hukukuna ilişkin bir mesele olduğundan her devletin kendi
hukukundaki kanunlar ihtilafı kuralları dikkate alınır.

Yabancı bir ülkenin Türkiye'deki konsolosluğunda evlenebilmek için öncelikle o
ülkenin konsolosluğa izin vermiş olması ve evlenecek kişilerin o ülkenin
vatandaşı olması gerekir.

Türkiye'nin yabancı bir ülkedeki bir konsolosluğunda evlenebilmek için öncelike
Türk mevzuatının o konsolosluğa evlendirme yetkisi tanımış olması gerekir.
İkinci olarak yabancı ülkenin de konsolosluğa evlendirme yetkisi tanıması
gerekir. Son olarak da evlenecek kişilerin Türk vatandaşı olması gerekir.

.Mal rejimi
****
*Evlilik malları hakkında eşler evlenme anındaki mutad mesken veya milli
hukuklarından birini açık olarak seçebilirler*; böyle bir seçim yapılmamış
olması halinde evlilik malları hakkında eşlerin evlenme anındaki müşterek milli
hukuku, bulunmaması halinde evlenme anındaki müşterek mutad mesken hukuku,
bunun da bulunmaması halinde Türk hukuku uygulanır.

Malların tasfiyesinde, taşınmazlar için bulundukları ülke hukuku uygulanır.

Evlenmeden sonra yeni bir müşterek hukuka sahip olan eşler, üçüncü kişilerin
hakları saklı kalmak üzere, bu yeni hukuka tabi *olabilirler*.
****

=== BOŞANMA

Boşanma ve ayrılık sebepler ve hükümleri, eşlerin müşterek milli hukukuna
tabidir. Tarafların ayrı vatandaşlıkta olmaları halinde müşterek mutad mesken
hukuku, bulunmadığı takdirde Türk hukuku uygulanır.

Boşanmış eşler arasındaki nafaka talepleri, boşanmada velayet ve vesayete
ilişkin sorunlar hakkında da yukarıdaki hüküm uygulanır.

CAUTION: Velayet normalde soybağına ilişkin bir meseledir. *Boşanmadan sonra
bir velayet davası açılacak olursa soybağı hükümlerine tabi olur*.

.Müşterek velayet
****
Kişiler, yabancı hukukta boşanmış ve çocuk hakkında müşterek velayete
hükmedilmiş ise Yargıtay Medeni Kanun'daki düzenlemeyi kamu düzeninden sayarak
müşterek velayete hükmedilemeyeceğini söylüyordu.

Türkiye, 8 Nisan 2016 tarihinde AİHS'in 7 nolu protokolüne imza attı. Bu
protokolün 5. maddesine göre:

_Eşler evlilikte, evlilik süresince ve evliliğin sona ermesi durumunda, kendi
aralarında ve çocukları ile ilişkilerinde medeni haklar ve sorumluluklardan
eşit şekilde yararlanırlar. Bu madde devletlerin çocuklar yararına gereken
tedbirleri almalarını engellemez._

Yargıtay bu sebeple, "_Türkiye artık AİHS'in 7 nolu protokolüne taraf
olduğundan ve Anayasa'nın 90.  maddesi gereği uluslararası bir sözleşme ile iç
hukuktaki bir düzenlemenin çelişmesi halinde uluslararası sözleşme
uygulanacağından müşterek velayete hükmedilebilir._" demiştir.
****

Geçici tedbir taleplerine Türk hukuku uygulanır.

TIP: Boşanmada ehliyet düzenlenmediği için MOHUK 9'daki "_Hak ve fiil ehliyeti
ilgilinin milli hukukuna tabidir._" hükmü uygulanacaktır. *Aile hukukuna
ilişkin bir mesele olduğundan atıf da dikkate alınır.*

=== SOYBAĞI

Soybağının kuruluşu, çocuğun doğum anındaki milli hukukuna, kurulamaması
halinde çocuğun mutad meskeni hukukuna tabidir.

Soybağı bu hukuklara göre kurulamıyorsa, ananın veya babanın, çocuğun doğumu
anındaki milli hukuklarına, bunlara göre kurulamaması halinde ana ve babanın,
çocuğun doğumu anındaki müşterek mutad mesken hukukuna, buna göre de
kurulamıyorsa çocuğun doğum yeri hukukuna tabi olarak kurulur.

Soybağı hangi hukuka göre kurulmuşsa iptali de o hukuka tabidir.

Soybağının hükümleri, soybağını kuran hukuka tabidir. Ancak ana, baba ve çocuk
müşterek milli hukuku bulunuyorsa, soybağının hükümlerine o hukuk, bulunmadığı
takdirde müşterek mutad mesken hukuku uygulanır.

Soybağına ilişkin uluslararası sözleşmeler:

. *Çocuk Haklarına Dair Birleşmiş Milletler Sözleşmesi*
. *Evlenme ile Nesep Düzeltilmesi Hakkında Sözleşme*
. *Evlilik Dışı Çocukların Tanınmalarını Kabule Yetkili Makamların Yetkilerinin
Genişletilmesi Hakkında Sözleşme*
. *Evlilik Dışında Doğan Çocukların Tanınmasına Dair Sözleşme*
. *Velayet Sorumluluğu ve Çocukların Korunması Hakkında Tedbirler Yönünden
Yetki, Uygulanacak Hukuk, Tanıma, Tenfiz, İşbirliğine Dair Sözleşme*
+
****
Bu sözleşme ile:

.. Çocuğun şahsı ve malvarlığı ile ilgili bir tedbir almaya yetkili makam,
.. Bu tedbirlere hangi hukukun uygulanacağı,
.. Velayete hangi hukukun uygulanacağı,
.. Çocuğun şahsına ve kendi malvarlığına ilişkin kararların nasıl tanınacağı ve
tenfiz edileceği

düzenlenmektedir.
****
+
*Çocuğun mutad meskeni makamları, çocukla ilgili gerekli tedbirleri alma
yetkisini haizdir.* Çocuğun üstün menfaati söz konusuysa, istisnaen çocuğu
daha iyi koruyabilecek mahkeme için yetkiden feragat edilebilir. Ancak,
yetkiden feragat edecek mahkeme, öncelikle lehine yetkiden feragat edeceği
mahkemeden izin almalıdır.
+
Sözleşme, mutad mesken mahkemesine ek olarak, boşanma dava görülüyorsa bu
mahkemenin de yetkili olacağını düzenlemektedir.
+
Çocukla ilgili verilmesi gereken çok acil bir karar varsa ve ana ve baba
velayet uyuşmazlığı sebebiyle bu kararı ortaklaşa veremiyorsa, çocuğun
bulunduğu ülke mahkemesi de yetkilidir.
+
Tüm bu yetkili hukukların yanında, üçüncü bir devletin hukukunun çocuk ile daha
sıkı ilişkide bulunduğu ortada ise bu devletin hukuku da uygulanabilir.
+
*Bu sözleşmenin hükümleri, taraf olmayan devlet vatandaşlarına da uygulanır.*
+
Çocuğun malvarlığına ilişkin bir hukuki işlem gerçekleştiren kişi, işlemin
gerçekleştirildiği ülke hukukuna göre ehliyetsiz olsa da işlem geçerli sayılır.
Yani bu sözleşme ile işlem güvenliği ilkesine bir istisna getirilmiştir.
+
Velayete uygulanacak hukuk bakımından bu sözleşme hükümleri, MOHUK 16'dan önce
uygulama alanı bulacaktır.
. *Uluslararası Çocuk Kaçırmanın Yönlerine Dair Sözleşme*
+
Bu sözleşme sadece ana veya baba çocuğu kaçırırsa uygulama alanı bulacaktır.
Üçüncü kişinin kaçırması, sözleşmenin kapsamına girmez.
+
Bu bir adli yardım sözleşmesidir. Kişi doğrudan dava açamaz; bulunduğu yerdeki
Cumhuriyet savcısından talepte bulunur.
+
*Bu sözleşmenin kapsamına sadece 16 yaşından küçük çocuklar girer.*
+
Sözleşme ile sözleşmeye taraf yabancı devlette verilmiş velayet kararının
tanıma ve tenfiz prosedürüne ihtiyaç duyulmaksızın geçerli olacağı
düzenlenmiştir.
+
Sözleşmede, çocuğun iadesine ilişkin dava sonuçlanmadan velayete ilişkin
davanın görülemeyeceği de düzenlenmiştir.
. *Çocukla Kişisel İlişki Kurulmasına Dair Avrupa Sözleşmesi*

=== NAFAKA

Nafaka türleri 4 tanedir:

. *Yardım nafakası:* Kural olarak alt soy ile üst soy arasındaki nafaka
talepleridir. Kanuna göre mirasçılık sırasına göre talepte bulunulabilir.
+
Alt soy - üst soy arasındaki nafaka taleplerine *1973 Tarihli Nafaka
Yükümlülüklerine Uygulanacak Sözleşme* hükümleri uygulanır. Kayın ve civar
hısımları arasındaki nafaka taleplerine ise MOHUK 19 uygulanır. MOHUK 19
uyarınca "_Nafaka talepleri, nafaka alacaklısının mutad meskeni hukukuna
tabidir._"
+
IMPORTANT: Bu sözleşme taraf olmayan devlete karşı da uygulanır.
. *İştirak nafakası:* Çocuğun velayetine sahip olmayan kişinin, çocuğun bakım
ve giderlerini karşılamak için ödeme gücü oranında ödemekle yükümlü olduğu
nafaka türüdür.

.. *1956 Tarihli Çocuklara Karşı Nafaka Yükümlülüğüne Uygulanacak Kanuna Dair
Sözleşme:* 21 yaşından küçük ve evlenmemiş çocuklara karşı olan nafaka
yükümlülüğü düzenlenmiştir. Evlilik içi-evlilik dışı veya evlatlık olması
farketmez. Bu sözleşmeye göre yetkili hukuk *nafaka alacaklısı çocuğun mutad
mesken hukuku*, bu hukuka göre nafaka tesis edilemezse *davanın açıldığı yer
hukukudur*.
+
NOTE: Türkiye'nin çekincesi gereği *nafaka alacaklısı ve borçlusu aynı devlet
vatandaşı ise ve nafaka borçlusu o devlette bulunuyorsa o devletin hukuku
uygulanır.*
.. *1973 Tarihli Nafaka Yükümlülüklerine Uygulanacak Sözleşme:* Sıhhi veya
civar hısımlığı veya evlilik içi-evlilik dışı çocuk farkı gözetmeksizin
*çocuğun mutad meskeni hukuku* uygulanır. Bu yoksa, *nafaka alacaklısı ve
nafaka borçlusunun müşterek milli hukuku* uygulanır. Bu da yoksa, *davanın
açıldığı yer hukuku* uygulanır.
+
NOTE: Türkiye'nin çekincesi gereği *nafaka alacaklısı ve borçlusu aynı devlet
vatandaşı ise ve nafaka borçlusu o devlette bulunuyorsa o devletin hukuku
uygulanır.*
+
TIP: Sınavda çocuğun bakım nafakasına hangi hukukun uygulanacağına ilişkin soru
gelirse şu şekilde cevaplandırılmalıdır: *Bu husus kanunda düzenlenmemiştir. Bu
konuya ilişkin biri 1956 biri 1973 tarihli iki sözleşme vardır. Yabancı
devletin bu sözleşmelerden birine taraf olup olmadığı konusunda bilgi
verilmediği için 1973 tarihli sözleşme uygulanacaktır. Zira 1973 tarihli
sözleşme, taraf olsun olmasın bütün devletlere karşı uygulanacaktır. Bu
sözleşmeye göre uygulanacak hukukun bağlama noktaları şu şekilde
düzenlenmiştir: nafaka alacaklısının mutad meskeni hukuku, bu yoksa nafaka
alacaklısı ile borçlusunun müşterek milli hukuku, bu da yoksa davanın açıldığı
yer hukuku.*

. *Yoksulluk nafakası:* Boşanmadan sonra yoksulluğa düşecek olan eşin belirli
bir hayat standardını sürdürmesi için diğer eş tarafından ödenen nafakadır.
+
Boşanmaya uygulanacak hukuka tabidir.
. *Tedbir nafakası:* Boşanma davası açılmadan önce veya boşanma davası
sırasında talep edilebilecek geçici nafakadır.
+
MOHUK 14/4 uyarınca "_Geçici tedbir taleplerine Türk hukuku uygulanır._"

Nafakanın tahsiline ilişkine sözleşmeler:

. *1956 Tarihli Nafaka Alacağının Tahsiline İlişkin Birleşmiş Milletler
Sözleşmesi:* Bir adli yardım sözleşmesidir. Taraf devletler birer aracı kurum
ile gönderici kurum belirler. *İdari makamlarca verilen kararlar da bu sözleşme
çerçevesinde tanıma ve tenfize konu olabilir.*

.. *(1. olasılık) Yabancı ülkede nafaka davası açmak:* Kişi, Cumhuriyet
savcılıklarına başvurarak yabancı ülkedeki kişiye nafaka davası açabilir.
Cumhuriyet savcısı, kişinin sunduğu tüm belgeleri yabancı devletin aracı
kurumuna gönderir ve aracı kurum kişi adına nafaka davasını açar.
.. *(2. olasılık) Türkiye'deki nafaka kararının tenfizi:* Yabancı ülkenin aracı
kurumu, kişi adına tenfiz davası açar. Vekaletnamede açıkça yetki verilmişse
sulh de olabilir.
. *1958 Tarihli Çocuklara Karşı Nafaka Yükümlülüğü Konusundaki Kararların
Tanınması ve Tenfizine İlişkin Sözleşme:* 21 yaşından küçük çocuklar hakkında
verilen nafaka kararlarının tanıma ve tenfizini düzenlemektedir. Mütekabiliyet
esasına dayalı bir sözleşmedir. Geçici nitelikte bir nafaka kararı varsa bile
taraf devletler tarafından tenfiz edilebilir. *İdari makamlarca verilen kararlar da bu sözleşme
çerçevesinde tanıma ve tenfize konu olabilir.*
. *1973 Tarihli Sözleşmeye İlişkin Nafaka Yükümlülüğü Konusundaki Kararların
Tanınması ve Tenfizine İlişkin Sözleşme:* Uygulanacak hukuka ilişkin
sözleşmenin aksine bu sadece taraf devletler arasında uygulanır. *İdari
makamlarca verilen kararlar da bu sözleşme çerçevesinde tanıma ve tenfize konu
olabilir.* Bu sözleşmeye Türkiye'nin koyduğu çekinceler:

.. Sıhhi hısımlara ilişkin nafaka taleplerine uygulanmaz.
.. Düzenli şekilde ödenmesine hükmedilmemiş nafakalara uygulanmaz.
.. Sulh kabul edilmez.
. *2007 Tarihli Çocuk Nafakası ve Diğer Aile Nafaka Türlerinin Uluslararası
Tahsiline İlişkin Sözleşme:* Taraf devletler arasında geçerlidir. 1956 tarihli
ve 1973 tarihli sözleşmelerin yerine geçer. 1958 tarihli sözleşme ile hükümleri
çelişiyorsa bu sözleşme uygulanır, aksi takdirde 1958 tarihli sözleşme
uygulanabilir. *İdari makamlarca verilen kararlar da bu sözleşme
çerçevesinde tanıma ve tenfize konu olabilir.* Bu sözleşme ile yardım nafakası
talepleri de tenfiz edilebilir.

=== EVLAT EDİNME

Evlat edinme ehliyeti ve şartları, taraflardan her birinin evlat edinme
anındaki milli hukukuna tabidir.

Evlat edinmeye ve edinilmeye diğer eşin rızası konusuda eşlerin milli hukukları
birlikte uygulanır. İki hukukun da izin vermesi şarttır. İki hukuktan
hangisinin şartları daha ağırsa o esas alınır.

Evlat edinmenin hükümleri evlat edinenin milli hukukuna, eşlerin birlikte evlat
edinmesi halinde ise evlenmenin genel hükümlerini düzenleyen hukuka tabidir.

NOTE: Yargıtay evlat edinmeye ilişkin şartların kamu düzeninden olduğunu kabul
etmektedir. Dolayısıyla bu şartları hafifleştiren bir hukuk uygulanamaz.

=== MİRAS

Miras ölenin milli hukukuna tabidir. Türkiye'de bulunan taşınmazlar hakkında
Türk hukuku uygulanır.

Mirasın açılması sebeplerine, iktisabına ve taksimine ilişkin hükümler
terekenin bulunduğu ülke hukukuna tabidir.

Türkiye'de bulunan mirasçısız tereke devlete kalır.

Ölüme bağlı tasarrufun şekline işlemin yapıldığı yer hukukunun öngördüğü şekil
uygulanır. Ölenin milli hukukuna uygun şekilde yapılan ölüme bağlı tasarruf da
geçerlidir.

.Vasiyetnamede şekil
****
Vasiyetnamede şekil, _Vasiyet Tasarrufunun Biçimine İlişkin Lahey
Sözleşmesi_ hükümlerine tabidir. Bu sözleşme mütekabiliyet şartı aranmaksızın
uygulanır.

Bu sözleşmeye göre kişi vasiyetnameyi düzenlediği anda üç tane bağlama noktası
vardır:

. Milli hukuk
. İkametgah hukuku
. Mutad mesken hukuku

Vasiyetnamenin *şekil açısından geçerli olup olmadığı* incelenirken ilk olarak
milli hukukuna bakılır. Geçerli değilse yerleşim yeri hukukuna bakılır. Buna
göre de geçerli değilse mutad mesken hukukuna bakılır. *Bunlar arasında sıra
gözetmek şart değildir.* Vasiyetnameyi ayakta tutmak için vasiyetnamenin
yapıldığı an esas alınacağı gibi, ölüm anı da esas alınabilir.

Vasiyetnamenin yapıldığı yer hukukuna göre şeklin geçerli olup olmadığı
çözümlenebilir. Taşınmaz söz konusu ise taşınmazın bulunduğu yer hukuku da
uygulanabilir.

*Türkiye'nin koyduğu çekince gereği sözleşmede yer alan ikametgah kavramının
nitelendirilmesi Türk hukukuna göre yapılacaktır.*

Türkiye'nin ikinci çekincesi gereği ise Türk vatandaşları bakımından sözlü
yapılan vasiyetnameler için bu sözleşme uygulanmaz.
****

Ölüme bağlı tasarruf ehliyeti, tasarrufta bulunanın, tasarrufun yapıldığı
andaki milli hukukuna tabidir.

*Miras hakkının varlığı ölenin milli hukukuna göre, taşınmaz söz konusu ise
Türk hukukuna göre çözümlenir. Ancak, mirasın iktisabı açısından tapu kanunu
uygulanır.*

=== AYNİ HAKLAR

Taşınırlar ve taşınmazlar üzerindeki mülkiyet hakkı ve diğer ayni haklar,
*işlem anında* malların bulunduğu ülke hukukuna tabidir. İşlemden kasıt
tasarruf işlemidir.

Malın taşınır mı taşınmaz mı olduğu tespiti malın bulunduğu ülke hukukuna göre
yapılır.

Taşınmakta olan mallar üzerindeki ayni haklara varma yeri hukuku uygulanır.

Konişmentonun eşyayı temsil edip etmediği meselesine uygulanacak hukuk ile
ilgili doktrinde çeşitli görüşler vardır. Klasik görüş kıymetli evrakın
bulunduğu yer hukukuna göre cevaplanması gerektiğini, bir başka görüş ise malın
bulunduğu yer hukukunun uygulanması gerektiğini söylemektedir.

Yer değişikliği halinde henüz kazanılmamış ayni haklar malın son bulunduğu ülke
hukukuna tabidir.

Taşınmazlar üzerindeki ayni haklara ilişkin hukuki işlemlere şekil yönünden bu
malların bulundukları ülke hukuku uygulanır.

Taşınırlar üzerindeki ayni haklara ilişkin hukuki işlemlere şekil yönünden
işlemin yapıldığı yer hukuku ya da işlemin esasına yetkili olan hukuk
uygulanır.

=== AKİTLER

Sözleşmeden doğan borç ilişkileri tarafların açık olarak seçtikleri hukuka
tabidir. Sözleşme hükümlerinden veya halin şartlarından tereddüde yer
vermeyecek biçimde anlaşılabilen hukuk seçimi de geçerlidir.

Hukuk seçimi taraflarca her zaman yapılabilir veya değiştirilebilir.
Sözleşmenin kurulmasından sonraki hukuk seçimi, üçüncü kişilerin hakları saklı
kalmak kaydıyla, geriye etkili olarak geçerlidir.

Tarafların hukuk seçimi yapmamış olmaları halinde sözleşmeden doğan ilişkiye, o
sözleşmeyle en sıkı ilişkili olan hukuk uygulanır. Bu hukuk,

* Karakteristik edim borçlusunun, sözleşmenin kuruluşu sırasındaki mutad
meskeni hukuku
* Ticari veya mesleki faaliyetler gereği kurulan sözleşmelerde karakteristik
edim borçlusunun işyeri

** İşyeri bulunmadığı takdirde yerleşim yeri hukuku
** Karakteristik edim borçlusunun birden çok işyeri varsa söz konusu
sözleşmeyle en sıkı ilişki içinde bulunan işyeri hukuku

Ancak halin bütün şartlarına göre sözleşmeyle daha sıkı ilişkili bir hukukun
bulunması halinde sözleşme, bu hukuka tabi olur.

NOTE: Bir sözleşmenin mesleki veya ticari olup olmadığını anlamak için
yapılacak vasıflandırma lex foriye göre yapılır.

Karakteristik edim;

* Sözleşmeye ismini veren edimdir.
* Edimi daha rizikolu olandır.
* Edimi para olmayan taraftır.

Sözleşmeden doğan ilişkinin tabi olduğu hukuk uygulanırken, sözleşmeyle sıkı
ilişkili olduğu takdirde üçüncü bir devletin hukukunun doğrudan uygulanan
kurallarına etki tanınabilir. Söz konusu kurallara etki tanımak ve uygulayıp
uygulamamak konusunda bu kuralların amacı, niteliği, muhtevası ve sonuçları
dikkate alınır.

Sözleşmeden doğan ilişkinin veya bir hükmünün varlığı ve maddi geçerliliği,
sözleşmenin geçerli olması halinde hangi hukuk uygulanacaksa o hukuka tabidir.

Taraflardan birinin davranışına hüküm tanımanın, uygulanacak hukuka tabi
kılınmasının hakkaniyete uygun olmayacağı halin şartlarından anlaşılırsa, irade
beyanının varlığına, rızası olmadığını iddia eden tarafın mutad meskeninin
bulunduğu ülke hukuku uygulanır.

İfa sırasında gerçekleştirilen fiil ve işlemler ile malların korunmasına
ilişkin tedbirler konusunda bu işlem veya fiillerin yapıldığı veya tedbirin
alındığı ülke hukuku dikkate alınır.

==== TAŞINMAZLARA İLİŞKİN AKİTLER

Taşınmazlara veya onların kullanımına ilişkin sözleşmeler taşınmazın bulunduğu
ülke hukukuna tabidir.

CAUTION: Taşınmazlara ilişkin tasarruf işlemleri MOHUK 21'e, borçlandırıcı
işlemler bu hükme (MOHUK 25) tabidir.

[TIP]
====
* Taşınırların satışı: MOHUK 21
* Taşınırların kiralanması: MOHUK 24
* Hava, deniz ve raylı taşıma araçlarının satışı: MOHUK 22
* Kara taşıma araçlarının satışı: MOHUK 21
* Taşınmazların satışı: MOHUK 21
* Taşınmazların kiralanması: MOHUK 25
====

NOTE: Ev kiralarının TÜFE oranına göre artırılacağına ilişkin TBK'daki hüküm,
doğrudan uygulanan kuraldır.

==== TÜKETİCİ SÖZLEŞMELERİ

Mesleki veya ticari olmayan amaçla mal veya hizmet ya da kredi sağlanmasına
yönelik tüketici sözleşmeleri, *tüketicinin mutad meskeni hukukunun emredici
hükümleri uyarınca sahip olacağı asgari koruma saklı kalmak kaydıyla*,
tarafların seçtikleri hukuka tabidir.

Tarafların hukuk seçimi yapmamış olması halinde, tüketicinin mutad meskeni
hukuku uygulanır. Tüketicinin mutad meskeni hukukunun uygulanabilmesi için;

.. Sözleşme, tüketicinin mutad meskeninin bulunduğu ülkede, ona gönderilen özel
bir davet üzerine veya ilan sonucunda kurulmuş ve sözleşmenin kurulması için
tüketici tarafından yapılması gerekli hukuki fiiller bu ülkede yapılmış veya
.. Diğer taraf veya onun temsilcisi, tüketicinin siparişini bu ülkede almış
veya
.. İlişkinin bir satış sözleşmesi olması halinde, satıcı tüketiciyi satın
almaya ikna etmek amacıyla bir gezi düzenlemiş ve tüketici de bu gezi ile
bulunduğu ülkeden başka ülkeye gidip siparişini orada vermiş

olmalıdır.

Yukarıdaki şartlar altında yapılan tüketici sözleşmelerinin şekline,
tüketicinin mutad meskeni hukuku uygulanır.

NOTE: Uyuşmazlık mahkemeye geldiğinde bunun bir tüketici sözleşmesi olup
olmadığı lex foriye göre vasıflandırılır.

Tüketici sözleşmeleri için yetkili mahkemeyi tayin ederken MOHUK 45
uygulanacaktır.

==== İŞ SÖZLEŞMELERİ

İş sözleşmeleri, *işçinin mutad işyeri hukukunun emredici hükümleri uyarınca
sahip olacağı asgari koruma saklı kalmak kaydıyla*, tarafların seçtikleri
hukuka tabidir.

Tarafların hukuk seçimi yapmamış olmaları halinde iş sözleşmesine, işçinin
işini mutad olarak yaptığı işyeri hukuku uygulanır. İşçinin işini geçici olarak
başka bir ülkede yapması halinde, bu işyeri mutad işyeri sayılmaz.

İşçinin işini belirli bir ülkede mutad olarak yapmayı devamlı olarak birden
fazla ülkede yapması halinde iş sözleşmesi, işverenin esas işyerinin bulunduğu
ülke hukukuna tabidir.

Ancak halin bütün şartlarına göre iş sözleşmesiyle daha sıkı ilişkili bir
hukukun bulunması halinde sözleşmeye bu hukuk uygulanabilir.

İşçinin, işi kapsamında ve işinin ifası sırasında meydana getirdiği fikri
ürünler üzerindeki fikri mülkiyet haklarıyla ilgili işçi ve işveren arasındaki
sözleşmelere, iş sözleşmesinin tabi olduğu hukuk uygulanır.

==== EŞYA TAŞIMA SÖZLEŞMELERİ

Eşyanın taşınmasına ilişkin sözleşmeler tarafların seçtikleri hukuka tabidir.

Tarafların hukuk seçimi yapmamış olmaları halinde, sözleşmenin kuruluşu
sırasında taşıyıcının esas işyerinin bulunduğu ülke aynı zamanda yüklemenin
veya boşaltmanın yapıldığı ülke veya gönderenin esas işyerinin bulunduğu ülke
ise bu ülkenin sözleşmeyle en sıkı ilişkili olduğu kabul edilir ve sözleşmeye
bu ülkenin hukuku uygulanır.

=== FİKRİ MÜLKİYET

*Fikri mülkiyete ilişkin haklar*, hangi ülkenin hukukuna göre koruma talep
ediliyorsa o hukuka tabidir.

Taraflar, fikri mülkiyet hakkının ihlalinden doğan talepler hakkında, ihlalden
sonra mahkemenin hukukunun uygulanmasını kararlaştırabilirler.

*Fikri mülkiyet haklarına ilişkin sözleşmeler*, tarafların seçtikleri hukuka
tabidir.

Tarafların hukuk seçimi yapmamış olmaları halinde sözleşmeden doğan ilişkiye,
fikri mülkiyet hakkını veya onun kullanımını devreden tarafın sözleşmenin
kuruluşu sırasındaki işyeri, bulunmadığı takdirde, mutad meskeni hukuku
uygulanır. Ancak halin bütün şartlarına göre sözleşmeyle daha sıkı ilişkili bir
hukukun bulunması halinde sözleşme bu hukuka tabi olur.

=== HAKSIZ FİİLLER

Haksız fiilden doğan borçlar haksız fiilin işlendiği ülke hukukuna tabidir.

Haksız fiilin işlendiği yer ile zararın meydana geldiği yerin farklı ülkelerde
olması halinde, zararın meydana geldiği yer hukuku uygulanır.

Haksız fiilden doğan borç ilişkisinin başka bir ülke ile daha sıkı ilişkili
olması halinde bu ülke hukuku uygulanır.

Haksız fiile veya sigorta sözleşmesine uygulanan hukuk imkan veriyorsa, zarar
gören, talebini doğrudan doğruya sorumlunun sigortacısına karşı ileri
sürebilir.

Taraflar, haksız fiilin meydana gelmesinden sonra uygulanacak hukuku açık
olarak seçebilirler.

==== KİŞİLİK HAKLARININ İHLALİ

Kişilik haklarının, basın, radyo, televizyon gibi medya yoluyla, internet veya
diğer kitle iletişim araçları ile ihlalinden doğan taleplere, zarar görenin
seçimine göre;

.. Zarar veren, zararın bu ülkede meydana geleceğini bilecek durumda ise zarar
görenin mutad meskeni hukuku
.. Zarar verenin işyeri veya mutad meskeninin bulunduğu ülke hukuku veya
.. Zarar veren, zararın bu ülkede meydana geleceğini bilecek durumda ise
zararın meydana geldiği ülke hukuku

uygulanır.

Bu hüküm, kişisel verilen işlenmesi veya kişisel veriler hakkında bilgi alma
hakkının sınırlandırılması yoluyla kişiliğin ihlal edilmesinden doğan taleplere
de uygulanır.

Kişilik haklarının ihlalinde cevap hakkı, süreli yayınlarda, münhasıran
baskının yapıldığı ya da programın yayınlandığı ülke hukukuna tabidir.

==== İMALATÇININ SÖZLEŞME DIŞI SORUMLULUĞU

İmal edilen şeylerin sebep olduğu zarardan doğan sorumluluğa, zarar görenin
seçimine göre, zarar verenin mutad meskeni veya işyeri hukuku ya da imal edilen
şeyin iktisap edildiği ülke hukuku uygulanır.

NOTE: İktisap yeri hukukunun uygulanabilmesi için zarar verenin, mamülün o
ülkeye rızası dışında sokulduğunu ispat edememiş olması gerekir.

==== HAKSIZ REKABET

Haksız rekabetten doğan talepler, haksız rekabet sebebiyle piyasası doğrudan
etkilenen ülke hukukuna tabidir.

Haksız rekabet sonucunda zarar görenin münhasıran işletmesine ilişkin
menfaatleri ihlal edilmişse, söz konusu işletmenin işyerinin bulunduğu ülke
hukuku uygulanır.

==== REKABETİN ENGELLENMESİ

Rekabetin engellenmesinden doğan talepler, bu engellemeden doğrudan etkilenen
piyasanın bulunduğu ülkenin hukukuna tabidir.

Türkiye'de rekabetin engellenmesine yabancı hukuk uygulanan hallerde, Türk
hukuku uygulansaydı verilecek tazminattan daha fazla tazminata hükmedilemez.

==== SEBEPSİZ ZENGİNLEŞME

Sebepsiz zenginleşmeden doğan talepler, zenginleşmeye sebep olan mevcut veya
mevcut olduğu iddia edilen hukuki ilişkiye uygulanan hukuka tabidir. Diğer
hallerde sebepsiz zenginleşmeye, zenginleşmenin gerçekleştiği ülke hukuku
uygulanır.

Taraflar, sebepsiz zenginleşmenin meydana gelmesinden sonra, uygulanacak hukuku
açık olarak seçebilirler.
