== SİGORTA ŞİRKETLERİ

2007 yılında yürürlüğe giren 5684 sayılı Sigortacılık Kanunu'nda kuruluşa,
denetlenmeye, sona ermeye ilişkin prensipler hem sigorta şirketlerini hem de
reasürans şirketlerini kapsar şekilde düzenlenmiştir.

[CAUTION]
====
Sigortacılık Kanunu'nda sigorta şirketinin kuruluşu için izin şartı
öngörülmemiştir. Ancak 2012 yılında TTK'da yapılan değişiklik ile Gümrük ve
Ticaret Bakanlığı'na kuruluşu ve sermaye değişiklikleri izne tabi olan anonim
şirketleri belirleme yetkisi verilmiş ve Bakanlık bu yetki çerçevesinde
çıkardığı tebliğ içerisinde sigorta şirketlerini de saymıştır.

*Dolayısıyla, anonim şirket tarzında kurulan sigorta şirketleri için Gümrük ve
Ticaret Bakanlığı'ndan izin şartı vardır.*
====

NOTE: SK'da Gümrük ve Ticaret Bakanlığı hiç geçmemektedir. Kanunda Müsteşarlık
ile kastedilen *Hazine Müsteşarlığı*, Bakanlık'tan kastedilen Hazine
Müsteşarlığı'nın bağlı olduğu bakanlıktır.

Türkiye’de faaliyet gösterecek sigorta şirketleri ile reasürans şirketlerinin
*anonim şirket veya kooperatif* şeklinde kurulmuş olması şarttır. Sigorta
şirketleri ve reasürans şirketleri, sigortacılık işlemleri ve bunlarla doğrudan
bağlantısı bulunan işler dışında başka işle iştigal edemez (SK 3).

Anonim şirket şeklinde kurulacak sigorta şirketleri ve reasürans şirketlerinin;

. Kurucularının;

.. Müflis veya konkordato ilan etmiş olmaması,
.. Bir sigorta veya reasürans şirketinin kurucusu veya ortağı olmanın
gerektirdiği malî güce ve itibara sahip bulunması,
.. Tasfiyeye tâbi tutulan finansal kuruluşlarda ve hakkında 20 nci maddenin
ikinci ve üçüncü fıkrası hükümleri uygulanan şirketlerde oy hakkının ya da
sermayesinin doğrudan veya dolaylı yüzde on ve daha fazla bir oranda veya bu
oranın altında olsa bile denetim ve yönetime etkili olabilecek şekilde denetim
ve yönetim kurullarına üye belirleme imtiyazı veren pay sahibi olmaması,
.. Taksirli suçlar hariç olmak üzere affa uğramış olsalar dahi süreli hapis
veya sigortacılık mevzuatına aykırı hareketlerinden dolayı hapis veya birden
fazla adlî para cezasına mahkûm edilmemiş yahut cezası ne olursa olsun basit ve
nitelikli zimmet, irtikâp, rüşvet, hırsızlık, dolandırıcılık, sahtecilik,
güveni kötüye kullanma, hileli iflas, görevi kötüye kullanma gibi yüz kızartıcı
suçlar ile kaçakçılık suçları, resmî ihale ve alım satımlara fesat karıştırma,
suçtan kaynaklanan malvarlığı değerlerini aklama, terörün finansmanı, Devlet
sırlarını açığa vurma veya vergi kaçakçılığı suçlarından dolayı hüküm giymemiş
olması,
.. Tüzel kişi olması halinde bu tüzel kişinin yönetim ve denetimine sahip
kişilerin, malî güç dışında kurucularda aranan diğer şartları taşıması,

. Hisse senetlerinin nakit karşılığı çıkarılması ve halka açık anonim
şirketlerde halka açık olan kısım hariç olmak üzere tamamının nama yazılı
olması,
. Bir holding bünyesinde faaliyet gösterecek olması halinde, holding şirketinin
finansal durumunun da sigortacılık faaliyetlerini idame ettirmeye yeterli
olması,

zorunludur.

Sigorta şirketleri ve reasürans şirketleri, faaliyete geçebilmek için, faaliyet
göstermek istedikleri her bir sigorta branşında Müsteşarlıktan ruhsat almak
zorundadır. Alınan ruhsatlar, ticaret siciline tescil ve Ticaret Sicil Gazetesi
ile Türkiye çapında dağıtımı yapılan ve tiraj bakımından ilk on sırada yer alan
günlük gazetelerden ikisinde ilan ettirilir (TTK 5/1).

Sigorta şirketleri hayat ve hayat dışı sigorta gruplarından sadece birinde
faaliyet gösterebilir. Bu gruplarda yer alan sigorta branşları Bakan tarafından
belirlenir (TTK 5/2).
