== SİGORTA ŞİRKETLERİNİN KURULUŞU

2007 yılında yürürlüğe giren 5684 sayılı Sigortacılık Kanunu'nda kuruluşa,
denetlenmeye, sona ermeye ilişkin prensipler hem sigorta şirketlerini hem de
reasürans şirketlerini kapsar şekilde düzenlenmiştir.

[CAUTION]
====
Sigortacılık Kanunu'nda sigorta şirketinin kuruluşu için izin şartı
öngörülmemiştir. Ancak 2012 yılında TTK'da yapılan değişiklik ile Gümrük ve
Ticaret Bakanlığı'na kuruluşu ve sermaye değişiklikleri izne tabi olan anonim
şirketleri belirleme yetkisi verilmiş ve Bakanlık bu yetki çerçevesinde
çıkardığı tebliğ içerisinde sigorta şirketlerini de saymıştır.

*Dolayısıyla, anonim şirket tarzında kurulan sigorta şirketleri için Gümrük ve
Ticaret Bakanlığı'ndan izin şartı vardır.*
====

NOTE: SK'da Gümrük ve Ticaret Bakanlığı hiç geçmemektedir. Kanunda Müsteşarlık
ile kastedilen *Hazine Müsteşarlığı*, Bakanlık'tan kastedilen Hazine
Müsteşarlığı'nın bağlı olduğu bakanlıktır.

Türkiye’de faaliyet gösterecek sigorta şirketleri ile reasürans şirketlerinin
*anonim şirket veya kooperatif* şeklinde kurulmuş olması şarttır. Sigorta
şirketleri ve reasürans şirketleri, sigortacılık işlemleri ve bunlarla doğrudan
bağlantısı bulunan işler dışında başka işle iştigal edemez (SK 3).

Anonim şirket şeklinde kurulacak sigorta şirketleri ve reasürans şirketlerinin;

. Kurucularının;

.. Müflis veya konkordato ilan etmiş olmaması,
.. Bir sigorta veya reasürans şirketinin kurucusu veya ortağı olmanın
gerektirdiği malî güce ve itibara sahip bulunması,
.. Tasfiyeye tâbi tutulan finansal kuruluşlarda ve hakkında 20 nci maddenin
ikinci ve üçüncü fıkrası hükümleri uygulanan şirketlerde oy hakkının ya da
sermayesinin doğrudan veya dolaylı yüzde on ve daha fazla bir oranda veya bu
oranın altında olsa bile denetim ve yönetime etkili olabilecek şekilde denetim
ve yönetim kurullarına üye belirleme imtiyazı veren pay sahibi olmaması,
.. Taksirli suçlar hariç olmak üzere affa uğramış olsalar dahi süreli hapis
veya sigortacılık mevzuatına aykırı hareketlerinden dolayı hapis veya birden
fazla adlî para cezasına mahkûm edilmemiş yahut cezası ne olursa olsun basit ve
nitelikli zimmet, irtikâp, rüşvet, hırsızlık, dolandırıcılık, sahtecilik,
güveni kötüye kullanma, hileli iflas, görevi kötüye kullanma gibi yüz kızartıcı
suçlar ile kaçakçılık suçları, resmî ihale ve alım satımlara fesat karıştırma,
suçtan kaynaklanan malvarlığı değerlerini aklama, terörün finansmanı, Devlet
sırlarını açığa vurma veya vergi kaçakçılığı suçlarından dolayı hüküm giymemiş
olması,
.. Tüzel kişi olması halinde bu tüzel kişinin yönetim ve denetimine sahip
kişilerin, malî güç dışında kurucularda aranan diğer şartları taşıması,

. Hisse senetlerinin nakit karşılığı çıkarılması ve halka açık anonim
şirketlerde halka açık olan kısım hariç olmak üzere tamamının nama yazılı
olması,
. Bir holding bünyesinde faaliyet gösterecek olması halinde, holding şirketinin
finansal durumunun da sigortacılık faaliyetlerini idame ettirmeye yeterli
olması,

zorunludur.

TIP: Sigorta şirketleri ortak sayısı 200'den az olmamak kaydıyla açık veya
kapalı kooperatif olarak da kurulabilir.  Kapalı kooperatifler sadece kendi
üyeleri ile sözleşme yaparken açık kooperatifler üyeleri dışındaki kişilerle de
sözleşme yaparlar. Ancak açık kooperatif kurmak için bunun ana sözleşmede
belirtilmiş olması ve müsteşar tarafından onaylanması gerekir.

Sigorta şirketleri hayat ve hayat dışı sigorta gruplarından sadece birinde
faaliyet gösterebilir. Bu gruplarda yer alan sigorta branşları Bakan tarafından
belirlenir.

Sigorta şirketleri ve reasürans şirketleri, faaliyete geçebilmek için, faaliyet
göstermek istedikleri her bir sigorta branşında Müsteşarlıktan ruhsat almak
zorundadır. Alınan ruhsatlar, ticaret siciline tescil ve Ticaret Sicil Gazetesi
ile Türkiye çapında dağıtımı yapılan ve tiraj bakımından ilk on sırada yer alan
günlük gazetelerden ikisinde ilan ettirilir.

Kuruluş işlemlerini tamamlayan ve ruhsat talebinde bulunan sigorta şirketleri
ile reasürans şirketleri, ödenmiş sermayelerini, ruhsat talep edilen sigorta
branşları için öngörülen sermaye tutarları ile verilmek istenen teminatlara
bağlı olarak, beş milyon Türk Lirasından az olmamak kaydıyla, Müsteşarlıkça
belirlenecek miktara yükseltmek zorundadır. Müsteşarlık, söz konusu miktarı,
Türkiye İstatistik Kurumu tarafından açıklanan Üretici Fiyatları Endeksi artış
oranını aşmamak kaydıyla artırmaya yetkilidir.

Kuruluş işlemlerinin tamamlanmasından itibaren bir yıl içinde ruhsat
başvurusunda bulunmamış sigorta şirketleri ve reasürans şirketleri, ticaret
unvanlarında sigorta şirketi veya reasürans şirketi ibaresini kullanamaz.

[TIP]
====
Ruhsatsız bir şirket ile onun bu durumunu bilerek yapılan sigorta sözleşmeleri
hakkında Türk Borçlar Kanununun 604 ve 605 inci maddeleri uygulanır. Türkiye’de
yerleşik olmayan sigorta şirketleriyle kurulan sigorta sözleşmelerinde bu hüküm
uygulanmaz.


.TBK 604 - Alacağın dava ve takip edilememesi
----
Kumar ve bahisten doğan alacak hakkında dava açılamaz ve takip yapılamaz. Kumar
veya bahis için bilerek verilen avanslar ve ödünç paralar ile kumar ve bahis
niteliğinde oldukları takdirde, borsada işlem gören malların, yabancı paraların
ve kıymetli evrakın fiyat farkı esası üzerine yapılan vadeli satışlar hakkında
da aynı hüküm uygulanır.
----

.TBK 605 - Borç senedi verme ve isteyerek ödeme
----
Kumar oynayan veya bahse giren kişi tarafından imzalanmış adi borç veya kambiyo
senedi üçüncü bir kişiye devredilmiş olsa bile, hiçbir kimse bunlara dayanarak
dava açamaz ve takip yapamaz. Kıymetli evrakın iyiniyetli üçüncü kişilere
sağladığı haklar saklıdır.

Kumar  ve  bahis  borcu  için isteyerek  yapılan  ödemeler  geri  alınamaz.
Ancak,  kumar  veya  bahsin  usulüne  göre yürütülmesi  beklenmedik  olayla
veya  diğer  tara fın  fiiliyle  engellenmişse  ya  da  diğer  taraf  kumar
veya  bahse  hile karıştırmışsa, isteyerek yapılan ödeme geri alınabilir.
----
====

Ruhsat talebi;

.. Sigorta şirketleri ve reasürans şirketlerinin kurucuları ile yönetici ve
denetçilerinin bu Kanunda öngörülen şartları taşımaması,
.. İş planına ve ibraz edilen belgelere göre sigorta sözleşmesine taraf
olanların hak ve menfaatlerinin yeterince korunamayacağının anlaşılması veya
yükümlülüklerin sürekli ve yeterli olarak yerine getirilebilecek şekilde
oluşturulmaması,
+
NOTE: İş planı, sigorta ve reasürans şirketlerinin kuruluş amacı ile en az ilk
üç yıllık faaliyetlerine ilişkin tahminler ve yükümlülüklerini sürekli olarak
nasıl yerine getirebileceğine ilişkin ayrıntılı bir rapordur.
.. Başvurunun yeterli beyan ve bilgileri içermemesi veya bu Kanunda öngörülen
şartları taşımadığının anlaşılması,
.. Sigorta şirketleri ve reasürans şirketlerinin, gerekli teknik donanım ya da
yeterli sayıda nitelikli personele sahip olmadığının veya ruhsat talep edilen
alanda sigortacılık yapma yeterliliğinin bulunmadığının yapılan denetimle
tespit edilmesi,

hallerinden en az birinin gerçekleşmesi durumunda reddedilir.

== SİGORTA ŞİRKETLERİNİN YÜKÜMLÜLÜKLERİ

Sigorta şirketleri ile reasürans şirketlerinin ana sözleşmelerinin
değiştirilmesinde, Müsteşarlığın uygun görüşü aranır. Müsteşarlıkça uygun
görülmeyen değişiklik tasarıları genel kurul gündemine alınamaz ve genel
kurulda görüşülemez. Sicil memuru, Müsteşarlığın uygun görüşü olmaksızın ana
sözleşme değişikliklerini ticaret siciline tescil edemez.

CAUTION: Anonim şirket tarzında kurulan sigorta şirketleri bakımından esas
sözleşme değişikliğinde yetkili kurum Gümrük ve Ticaret Bakanlığıdır.

Sigorta şirketleri ve reasürans şirketleri sigorta sözleşmelerinden doğan
yükümlülükleri için, kanunda belirtilen esaslara göre yeteri kadar karşılık
ayırmak zorundadır.

Sigorta şirketleri, yurt içinde akdetmiş oldukları sigorta sözleşmelerinden
doğan taahhütlerine karşılık olarak kanunda belirlenen esaslara göre teminat
ayırmak zorundadır.

Sigorta şirketleri ve reasürans şirketleri, hesaplarını ve malî tablolarını,
Müsteşarlıkça belirlenecek esaslara ve örneğe uygun olarak düzenlemek, ilan
ettirmek ve Müsteşarlığa göndermek zorundadır.

Sigorta şirketleri ile reasürans şirketleri bilançolarının, kâr ve zarar
cetvellerinin ve Müsteşarlıkça uygun görülecek diğer malî tablolarının bağımsız
denetim kuruluşlarına denetlettirilmesi ve ilan ettirilmesi zorunludur.
Müsteşarlık, sigorta şirketleri ve reasürans şirketlerinin bağımsız dış denetim
kuruluşlarınca denetlenmelerini düzenlemeye yetkilidir.

Sigorta şirketleri ile reasürans şirketlerinin ortakları, yönetim kurulu
üyeleri, denetçileri ve çalışanları, şirket ana sözleşmesi veya genel kurul ya
da yönetim kurulu kararı ile saptanan hükümler dâhilinde personele yapılan
ödemeler, yardım veya verilen avanslar hariç, şirket kaynaklarını dolaylı ya da
dolaysız kullanamaz, iyiniyet kurallarına aykırı olarak aktifin değerini
düşüren işlemlerde bulunamaz ve hiçbir surette örtülü kazanç aktarımı yapamaz.
Sigorta şirketleri ile reasürans şirketleri kendi borçları veya sigorta
işlemlerinden doğanlar hariç olmak üzere personeli, ortakları, iştirakleri veya
diğer kişi ve kurumlar lehine mal varlığını teminat olarak gösteremez, kefil
olamaz ve kredi sağlayamaz.

Bir sigorta veya reasürans şirketinin minumum garanti fonu tutarını
karşılayamadığının, tesis etmesi gereken teminatı tesis edemediğinin, teknik
karşılıkları karşılayacak yeterli veya teknik karşılıklara uygun varlıklarının
bulunmadığının ya da sözleşmelerden doğan yükümlülüklerini yerine
getiremediğinin yahut şirketin malî bünyesinin sigortalıların hak ve
menfaatlerini tehlikeye düşürecek derecede zayıflamakta olduğunun tespiti
hallerinde, Bakan uygun bir süre vererek, malî bünyenin güçlendirilmesine
yönelik olarak ilgili sigorta ve reasürans şirketinden;

.. Malî bünyesindeki zaafiyetin nasıl giderileceğini ve sigortalıların hak ve
menfaatlerinin nasıl korunacağını içeren kapsamlı bir iyileştirme planı
sunulması ve uygulanmasını,
.. Sermayesinin artırılması, ödenmemiş kısmının ödenmesi, sermayeye mahsuben
şirkete ödeme yapılması veya kâr dağıtımının durdurulması ya da ilave teminat
tesis edilmesini,
.. Varlıklarının kısmen ya da tamamen elden çıkarılması veya elden
çıkarılmasının durdurulmasını, yeni iştirak ve sabit değerler edinilmemesini,
.. Malî bünyesini ve likiditesini güçlendirici ve riski azaltıcı benzer
tedbirler alınmasını,
.. Tespit edilecek gündemle genel kurulun olağanüstü toplantıya çağrılmasını
veya genel kurul toplantısının ertelenmesini,
.. Benzeri diğer hususların yerine getirilmesini,

isteyebilir.

Ayrıca, Bakan;

.. Sigorta şirketlerinde şirketin faaliyette bulunduğu sigorta branşlarından,
reasürans şirketlerinde ise sigorta gruplarından birine veya tamamına ait
sigorta portföyünü teminat ve karşılıkları ile birlikte başka şirket veya
şirketlere devretmeye, devralacak şirket bulunamadığı takdirde ise devredilecek
portföyün tasfiyesine yönelik her türlü tedbiri almaya, .. Sigorta portföyünü sınırlandırmaya,
.. Yönetim veya denetim kurulu üyelerinden bir kısmını veya tamamını görevden
alarak ya da bu kurullardaki mevcut üye sayısını artırarak bu kurullara üye
atamaya veya sigorta veya reasürans şirketinin yönetiminin kayyıma
devredilmesini talep etmeye,
.. Malî bünyenin güçlendirilmesine yönelik benzeri diğer tedbirleri almaya,

yetkilidir.

Yukarıda öngörülen tedbirlerin uygulanmaması veya uygulanamayacağının
anlaşılması, sigorta veya reasürans şirketinin ödemelerini tatil etmesi,
sigortalılara olan yükümlülüklerini yerine getirememesi veya şirket
özkaynaklarının minimum garanti fonunun altına düşmesi halinde, Bakan, sigorta
veya reasürans şirketinin tüm branşlarda veya ilgili branşlarda yeni sigorta
sözleşmesi akdetme ve temdit yetkisini kaldırmaya, ruhsatlarını iptal ve
varlıklarını bloke etmeye yetkilidir.

== SİGORTA SÖZLEŞMELERİ

Sigorta sözleşmelerinin ana muhtevası, Müsteşarlıkça onaylanan ve sigorta
şirketlerince aynı şekilde uygulanacak olan genel şartlara uygun olarak
düzenlenir. Ancak, sigorta sözleşmelerinde işin özelliğine uygun olarak özel
şartlar tesis edilebilir. Bu hususlar, sigorta sözleşmesi üzerinde ve özel
şartlar başlığı altında herhangi bir yanılgıya neden olmayacak şekilde açık
olarak belirtilir.

Sigorta tarifeleri, sigortacılık esasına ve genel kabul görmüş aktüeryal
tekniklere uygun olarak sigorta şirketleri tarafından serbestçe belirlenir.
Ancak, bu Kanuna ve diğer kanunlara göre ihdas edilen zorunlu sigortaların
teminat tutarları ile tarife ve talimatları Bakan tarafından tespit olunur ve
Resmî Gazetede yayımlanır.
