:icons: font
:toc:
:toc-title: SİGORTA

== SİGORTA ŞİRKETLERİ

=== KURULUŞ

2007 yılında yürürlüğe giren 5684 sayılı Sigortacılık Kanunu'nda kuruluşa,
denetlenmeye, sona ermeye ilişkin prensipler hem sigorta şirketlerini hem de
reasürans şirketlerini kapsar şekilde düzenlenmiştir.

[CAUTION]
====
Sigortacılık Kanunu'nda sigorta şirketinin kuruluşu için izin şartı
öngörülmemiştir. Ancak 2012 yılında TTK'da yapılan değişiklik ile Gümrük ve
Ticaret Bakanlığı'na kuruluşu ve sermaye değişiklikleri izne tabi olan anonim
şirketleri belirleme yetkisi verilmiş ve Bakanlık bu yetki çerçevesinde
çıkardığı tebliğ içerisinde sigorta şirketlerini de saymıştır.

*Dolayısıyla, anonim şirket tarzında kurulan sigorta şirketleri için Gümrük ve
Ticaret Bakanlığı'ndan izin şartı vardır.*
====

NOTE: SK'da Gümrük ve Ticaret Bakanlığı hiç geçmemektedir. Kanunda Müsteşarlık
ile kastedilen *Hazine Müsteşarlığı*, Bakanlık'tan kastedilen Hazine
Müsteşarlığı'nın bağlı olduğu bakanlıktır.

Türkiye’de faaliyet gösterecek sigorta şirketleri ile reasürans şirketlerinin
*anonim şirket veya kooperatif* şeklinde kurulmuş olması şarttır. Sigorta
şirketleri ve reasürans şirketleri, sigortacılık işlemleri ve bunlarla doğrudan
bağlantısı bulunan işler dışında başka işle iştigal edemez (SK 3).

Anonim şirket şeklinde kurulacak sigorta şirketleri ve reasürans şirketlerinin;

. Kurucularının;

.. Müflis veya konkordato ilan etmiş olmaması,
.. Bir sigorta veya reasürans şirketinin kurucusu veya ortağı olmanın
gerektirdiği malî güce ve itibara sahip bulunması,
.. Tasfiyeye tâbi tutulan finansal kuruluşlarda ve hakkında Sigorta Kanunu 20
nci maddenin ikinci ve üçüncü fıkrası hükümleri uygulanan şirketlerde oy
hakkının ya da sermayesinin doğrudan veya dolaylı yüzde on ve daha fazla bir
oranda veya bu oranın altında olsa bile denetim ve yönetime etkili olabilecek
şekilde denetim ve yönetim kurullarına üye belirleme imtiyazı veren pay sahibi
olmaması,
.. Taksirli suçlar hariç olmak üzere affa uğramış olsalar dahi süreli hapis
veya sigortacılık mevzuatına aykırı hareketlerinden dolayı hapis veya birden
fazla adlî para cezasına mahkûm edilmemiş yahut cezası ne olursa olsun basit ve
nitelikli zimmet, irtikâp, rüşvet, hırsızlık, dolandırıcılık, sahtecilik,
güveni kötüye kullanma, hileli iflas, görevi kötüye kullanma gibi yüz kızartıcı
suçlar ile kaçakçılık suçları, resmî ihale ve alım satımlara fesat karıştırma,
suçtan kaynaklanan malvarlığı değerlerini aklama, terörün finansmanı, Devlet
sırlarını açığa vurma veya vergi kaçakçılığı suçlarından dolayı hüküm giymemiş
olması,
.. Tüzel kişi olması halinde bu tüzel kişinin yönetim ve denetimine sahip
kişilerin, malî güç dışında kurucularda aranan diğer şartları taşıması,

. Hisse senetlerinin nakit karşılığı çıkarılması ve halka açık anonim
şirketlerde halka açık olan kısım hariç olmak üzere tamamının nama yazılı
olması,
. Bir holding bünyesinde faaliyet gösterecek olması halinde, holding şirketinin
finansal durumunun da sigortacılık faaliyetlerini idame ettirmeye yeterli
olması,

zorunludur.

TIP: Sigorta şirketleri ortak sayısı 200'den az olmamak kaydıyla açık veya
kapalı kooperatif olarak da kurulabilir.  Kapalı kooperatifler sadece kendi
üyeleri ile sözleşme yaparken açık kooperatifler üyeleri dışındaki kişilerle de
sözleşme yaparlar. Ancak açık kooperatif kurmak için bunun ana sözleşmede
belirtilmiş olması ve müsteşar tarafından onaylanması gerekir.

Sigorta şirketleri hayat ve hayat dışı sigorta gruplarından sadece birinde
faaliyet gösterebilir. Bu gruplarda yer alan sigorta branşları Bakan tarafından
belirlenir.

Sigorta şirketleri ve reasürans şirketleri, faaliyete geçebilmek için, faaliyet
göstermek istedikleri her bir sigorta branşında Müsteşarlıktan ruhsat almak
zorundadır. Alınan ruhsatlar, ticaret siciline tescil ve Ticaret Sicil Gazetesi
ile Türkiye çapında dağıtımı yapılan ve tiraj bakımından ilk on sırada yer alan
günlük gazetelerden ikisinde ilan ettirilir.

Kuruluş işlemlerini tamamlayan ve ruhsat talebinde bulunan sigorta şirketleri
ile reasürans şirketleri, ödenmiş sermayelerini, ruhsat talep edilen sigorta
branşları için öngörülen sermaye tutarları ile verilmek istenen teminatlara
bağlı olarak, beş milyon Türk Lirasından az olmamak kaydıyla, Müsteşarlıkça
belirlenecek miktara yükseltmek zorundadır. Müsteşarlık, söz konusu miktarı,
Türkiye İstatistik Kurumu tarafından açıklanan Üretici Fiyatları Endeksi artış
oranını aşmamak kaydıyla artırmaya yetkilidir.

Kuruluş işlemlerinin tamamlanmasından itibaren bir yıl içinde ruhsat
başvurusunda bulunmamış sigorta şirketleri ve reasürans şirketleri, ticaret
unvanlarında sigorta şirketi veya reasürans şirketi ibaresini kullanamaz.

[TIP]
====
Ruhsatsız bir şirket ile onun bu durumunu bilerek yapılan sigorta sözleşmeleri
hakkında Türk Borçlar Kanununun 604 ve 605 inci maddeleri uygulanır. Türkiye’de
yerleşik olmayan sigorta şirketleriyle kurulan sigorta sözleşmelerinde bu hüküm
uygulanmaz.


.TBK 604 - Alacağın dava ve takip edilememesi
----
Kumar ve bahisten doğan alacak hakkında dava açılamaz ve takip yapılamaz. Kumar
veya bahis için bilerek verilen avanslar ve ödünç paralar ile kumar ve bahis
niteliğinde oldukları takdirde, borsada işlem gören malların, yabancı paraların
ve kıymetli evrakın fiyat farkı esası üzerine yapılan vadeli satışlar hakkında
da aynı hüküm uygulanır.
----

.TBK 605 - Borç senedi verme ve isteyerek ödeme
----
Kumar oynayan veya bahse giren kişi tarafından imzalanmış adi borç veya kambiyo
senedi üçüncü bir kişiye devredilmiş olsa bile, hiçbir kimse bunlara dayanarak
dava açamaz ve takip yapamaz. Kıymetli evrakın iyiniyetli üçüncü kişilere
sağladığı haklar saklıdır.

Kumar  ve  bahis  borcu  için isteyerek  yapılan  ödemeler  geri  alınamaz.
Ancak,  kumar  veya  bahsin  usulüne  göre yürütülmesi  beklenmedik  olayla
veya  diğer  tara fın  fiiliyle  engellenmişse  ya  da  diğer  taraf  kumar
veya  bahse  hile karıştırmışsa, isteyerek yapılan ödeme geri alınabilir.
----
====

Ruhsat talebi;

.. Sigorta şirketleri ve reasürans şirketlerinin kurucuları ile yönetici ve
denetçilerinin bu Kanunda öngörülen şartları taşımaması,
.. İş planına ve ibraz edilen belgelere göre sigorta sözleşmesine taraf
olanların hak ve menfaatlerinin yeterince korunamayacağının anlaşılması veya
yükümlülüklerin sürekli ve yeterli olarak yerine getirilebilecek şekilde
oluşturulmaması,
+
NOTE: İş planı, sigorta ve reasürans şirketlerinin kuruluş amacı ile en az ilk
üç yıllık faaliyetlerine ilişkin tahminler ve yükümlülüklerini sürekli olarak
nasıl yerine getirebileceğine ilişkin ayrıntılı bir rapordur.
.. Başvurunun yeterli beyan ve bilgileri içermemesi veya bu Kanunda öngörülen
şartları taşımadığının anlaşılması,
.. Sigorta şirketleri ve reasürans şirketlerinin, gerekli teknik donanım ya da
yeterli sayıda nitelikli personele sahip olmadığının veya ruhsat talep edilen
alanda sigortacılık yapma yeterliliğinin bulunmadığının yapılan denetimle
tespit edilmesi,

hallerinden en az birinin gerçekleşmesi durumunda reddedilir.

=== YÜKÜMLÜLÜKLER

Sigorta şirketleri ile reasürans şirketlerinin ana sözleşmelerinin
değiştirilmesinde, Müsteşarlığın uygun görüşü aranır. Müsteşarlıkça uygun
görülmeyen değişiklik tasarıları genel kurul gündemine alınamaz ve genel
kurulda görüşülemez. Sicil memuru, Müsteşarlığın uygun görüşü olmaksızın ana
sözleşme değişikliklerini ticaret siciline tescil edemez.

CAUTION: Anonim şirket tarzında kurulan sigorta şirketleri bakımından esas
sözleşme değişikliğinde yetkili kurum Gümrük ve Ticaret Bakanlığıdır.

Sigorta şirketleri ve reasürans şirketleri sigorta sözleşmelerinden doğan
yükümlülükleri için, kanunda belirtilen esaslara göre yeteri kadar karşılık
ayırmak zorundadır.

Sigorta şirketleri, yurt içinde akdetmiş oldukları sigorta sözleşmelerinden
doğan taahhütlerine karşılık olarak kanunda belirlenen esaslara göre teminat
ayırmak zorundadır.

Sigorta şirketleri ve reasürans şirketleri, hesaplarını ve malî tablolarını,
Müsteşarlıkça belirlenecek esaslara ve örneğe uygun olarak düzenlemek, ilan
ettirmek ve Müsteşarlığa göndermek zorundadır.

Sigorta şirketleri ile reasürans şirketleri bilançolarının, kâr ve zarar
cetvellerinin ve Müsteşarlıkça uygun görülecek diğer malî tablolarının bağımsız
denetim kuruluşlarına denetlettirilmesi ve ilan ettirilmesi zorunludur.
Müsteşarlık, sigorta şirketleri ve reasürans şirketlerinin bağımsız dış denetim
kuruluşlarınca denetlenmelerini düzenlemeye yetkilidir.

Sigorta şirketleri ile reasürans şirketlerinin ortakları, yönetim kurulu
üyeleri, denetçileri ve çalışanları, şirket ana sözleşmesi veya genel kurul ya
da yönetim kurulu kararı ile saptanan hükümler dâhilinde personele yapılan
ödemeler, yardım veya verilen avanslar hariç, şirket kaynaklarını dolaylı ya da
dolaysız kullanamaz, iyiniyet kurallarına aykırı olarak aktifin değerini
düşüren işlemlerde bulunamaz ve hiçbir surette örtülü kazanç aktarımı yapamaz.
Sigorta şirketleri ile reasürans şirketleri kendi borçları veya sigorta
işlemlerinden doğanlar hariç olmak üzere personeli, ortakları, iştirakleri veya
diğer kişi ve kurumlar lehine mal varlığını teminat olarak gösteremez, kefil
olamaz ve kredi sağlayamaz.

Bir sigorta veya reasürans şirketinin minumum garanti fonu tutarını
karşılayamadığının, tesis etmesi gereken teminatı tesis edemediğinin, teknik
karşılıkları karşılayacak yeterli veya teknik karşılıklara uygun varlıklarının
bulunmadığının ya da sözleşmelerden doğan yükümlülüklerini yerine
getiremediğinin yahut şirketin malî bünyesinin sigortalıların hak ve
menfaatlerini tehlikeye düşürecek derecede zayıflamakta olduğunun tespiti
hallerinde, Bakan uygun bir süre vererek, malî bünyenin güçlendirilmesine
yönelik olarak ilgili sigorta ve reasürans şirketinden;

.. Malî bünyesindeki zaafiyetin nasıl giderileceğini ve sigortalıların hak ve
menfaatlerinin nasıl korunacağını içeren kapsamlı bir iyileştirme planı
sunulması ve uygulanmasını,
.. Sermayesinin artırılması, ödenmemiş kısmının ödenmesi, sermayeye mahsuben
şirkete ödeme yapılması veya kâr dağıtımının durdurulması ya da ilave teminat
tesis edilmesini,
.. Varlıklarının kısmen ya da tamamen elden çıkarılması veya elden
çıkarılmasının durdurulmasını, yeni iştirak ve sabit değerler edinilmemesini,
.. Malî bünyesini ve likiditesini güçlendirici ve riski azaltıcı benzer
tedbirler alınmasını,
.. Tespit edilecek gündemle genel kurulun olağanüstü toplantıya çağrılmasını
veya genel kurul toplantısının ertelenmesini,
.. Benzeri diğer hususların yerine getirilmesini,

isteyebilir.

Ayrıca, Bakan;

.. Sigorta şirketlerinde şirketin faaliyette bulunduğu sigorta branşlarından,
reasürans şirketlerinde ise sigorta gruplarından birine veya tamamına ait
sigorta portföyünü teminat ve karşılıkları ile birlikte başka şirket veya
şirketlere devretmeye, devralacak şirket bulunamadığı takdirde ise devredilecek
portföyün tasfiyesine yönelik her türlü tedbiri almaya,
.. Sigorta portföyünü sınırlandırmaya,
.. Yönetim veya denetim kurulu üyelerinden bir kısmını veya tamamını görevden
alarak ya da bu kurullardaki mevcut üye sayısını artırarak bu kurullara üye
atamaya veya sigorta veya reasürans şirketinin yönetiminin kayyıma
devredilmesini talep etmeye,
.. Malî bünyenin güçlendirilmesine yönelik benzeri diğer tedbirleri almaya,

yetkilidir.

Yukarıda öngörülen tedbirlerin uygulanmaması veya uygulanamayacağının
anlaşılması, sigorta veya reasürans şirketinin ödemelerini tatil etmesi,
sigortalılara olan yükümlülüklerini yerine getirememesi veya şirket
özkaynaklarının minimum garanti fonunun altına düşmesi halinde, Bakan, sigorta
veya reasürans şirketinin tüm branşlarda veya ilgili branşlarda yeni sigorta
sözleşmesi akdetme ve temdit yetkisini kaldırmaya, ruhsatlarını iptal ve
varlıklarını bloke etmeye yetkilidir.

=== SONA ERME

==== RUHSAT İPTALİ

Bu Kanunun ruhsat iptaline ilişkin hükümleri saklı kalmak kaydıyla;

.. Ruhsat verilmesine ilişkin şartların bir kısmının veya tamamının kaybolması
halinde, üç aydan az olmamak üzere, Müsteşarlık tarafından verilecek süre
içinde durumun düzeltilmemiş olması,
.. Ruhsatın verildiği tarihten itibaren bir yıl içinde veya Müsteşarlığın uygun
görüşüyle yapılanlar hariç olmak üzere aralıksız olarak altı ay süre ile
sigorta veya reasürans sözleşmesi akdedilmemesi,
.. Sigortacılık mevzuatına aykırı uygulamalar sonucunda sigorta sözleşmesi ile
ilgili kişilerin hak ve menfaatlerinin tehlikeye düştüğünün anlaşılması,
.. 20 nci madde hükmü hariç olmak üzere, bu Kanun hükümlerinden doğan
yükümlülüklerin ağır şekilde ihlâl edilmesi veya yükümlülüklerin ihlâlinin
mutat hale gelmesi durumunda, Müsteşarlık tarafından, üç aydan az olmamak
kaydıyla, verilecek süre içinde durumun düzeltilmemiş olması,
.. İş planında belirtilen hedeflerden, Müsteşarlığın bilgisi dahilinde yapılan
değişiklik dışında makul nedenler olmaksızın aşırı derecede uzaklaşılmış
olması,

hallerinden en az birinin gerçekleşmesi durumunda, sigorta şirketlerinin ve
reasürans şirketlerinin ilgili branş ya da bütün branşlardaki ruhsatları
Müsteşarlık tarafından iptal edilebilir.

Ruhsat iptali, ticaret siciline tescil ve Ticaret Sicil Gazetesi ile Türkiye
çapında dağıtımı yapılan ve tiraj bakımından ilk on sırada yer alan günlük
gazetelerden ikisinde ilan ettirilir.

Ruhsatı iptal edilen şirketler, altı ayı geçmemek üzere Müsteşarlık tarafından
verilecek süre içinde iptal edilen ruhsatla bağlantılı portföylerini devretmek
zorundadır. Aksi takdirde Müsteşarlık re’sen devir de dâhil olmak üzere
portföyün tasfiyesine yönelik her türlü tedbiri almaya yetkilidir.

==== TASFİYE, BİRLEŞME, DEVİR, PORTFÖY DEVRİ VE İFLAS

Bir sigorta şirketinin kendi talebi ile tasfiye edilmesi, bir veya birkaç
şirket ile birleşmesi veya aktif ve pasifleri ile başka bir şirkete
devrolunması, sigorta portföyünü teminat ve karşılıkları ile birlikte kısmen
veya tamamen diğer bir şirkete devretmesi Bakanın iznine tâbidir. Reasürans
şirketleri hakkında da bu fıkra hükümleri uygulanır. Bu fıkra hükmüne aykırı
olarak yapılan tasfiye, birleşme, devralma ve portföy devirleri hükümsüzdür.

TIP: Portföy devrinde alacağın temliki ve borcun nakli bir arada
gerçekleşmektedir. Borcun naklinde alacaklının rızası aranmaktadır. Bakanın
izni tüm alacaklıların izni yerine geçmektedir.

Müsteşarlık, lüzumu halinde, tasfiye memurlarının değiştirilmesini talep
edebilir.

Birleşme, devir ve portföy devirleri, Türkiye çapında dağıtımı yapılan ve tiraj
bakımından ilk on sırada yer alan günlük gazetelerden ikisinde, birer hafta
arayla en az ikişer defa yayımlanmak suretiyle duyurulur. Sigorta sözleşmeleri
devredilen portföyde yer almak kaydıyla portföyünü devreden veya bir şirkete
devrolunan ya da birleşen şirketlerle sigorta sözleşmesi akdetmiş olan kişiler;
birleşme, devir ya da portföy devrini öğrendikleri tarihten itibaren, devir,
birleşme ya da portföy devri nedeniyle, üç ay içinde sözleşmelerini
feshedebilir.

Sigorta şirketinin iflası halinde sigortalılar, iflas masasına üçüncü sırada
iştirak eder.

Müsteşarlık, lüzumu halinde iflas masasındaki yetkililerin değiştirilmesini
talep edebilir.

== SİGORTA SÖZLEŞMELERİ

Sigorta sözleşmesi, sigortacının bir prim karşılığında, kişinin para ile
ölçülebilir bir menfaatini zarara uğratan tehlikenin, rizikonun, meydana
gelmesi hâlinde bunu tazmin etmeyi ya da bir veya birkaç kişinin hayat süreleri
sebebiyle ya da hayatlarında gerçekleşen bazı olaylar dolayısıyla bir para
ödemeyi veya diğer edimlerde bulunmayı yükümlendiği sözleşmedir.

NOTE: Sigorta sözleşmesinin tarafları *sigortacı* ve **sigorta ettiren**dir.
*Sigortalı*, sözleşmenin tarafı olmayan ama sözleşmeden yararlanan üçüncü
kişidir.

Sigorta sözleşmesi, her iki tarafa borç yükleyen bir sözleşmedir. Sigorta
ettirenin asıl edimi, *prim ödeme* borcudur. Sigortacının edimi ise *himaye
sağlama* borcudur.

[TIP]
====
Doktrinde sigortacının edimini izah eden iki görüş vardır: *Para ödeme teorisi*
ve *tehlike taşıma teorisi*.

Para ödeme teorisine göre sigortacının borcu riziko gerçekleştiğinde ortaya
çıkar.

Tehlike taşıma teorisine göre ise sigortacının borcu sözleşmenin kurulması
anından itibaren başlar ve prim toplamak, bunları nemalandırmak, reasürans
sözleşmeleri akdetmek vs. sigortacının ediminin bir parçasıdır.
====

Ruhsatsız bir şirket ile onun bu durumunu bilerek yapılan sigorta sözleşmeleri
hakkında Türk Borçlar Kanununun 604 ve 605 inci maddeleri uygulanır. Türkiye’de
yerleşik olmayan sigorta şirketleriyle kurulan sigorta sözleşmelerinde bu hüküm
uygulanmaz.

Sigorta sözleşmelerinin ana muhtevası, Müsteşarlıkça onaylanan ve sigorta
şirketlerince aynı şekilde uygulanacak olan genel şartlara uygun olarak
düzenlenir. Ancak, sigorta sözleşmelerinde işin özelliğine uygun olarak özel
şartlar tesis edilebilir. Bu hususlar, sigorta sözleşmesi üzerinde ve özel
şartlar başlığı altında herhangi bir yanılgıya neden olmayacak şekilde açık
olarak belirtilir.

Sigorta sözleşmelerinde kapsam dahiline alınmış olan riskler haricinde, kapsam
dışı bırakılmış riskler açıkça belirtilir. Belirtilmemiş olan riskler teminat
kapsamında sayılır.

=== SÖZLEŞME TÜRLERİ

==== ZARAR SİGORTASI

Zarar sigortalarında teminat altına alınan rizikoların gerçekleşmesi ile ortaya
çıkan somut zararın giderilmesi hedeflenmektedir.

===== AKTİF ZARAR SİGORTASI

Aktif zarar sigortalarının konusunu *menfaat* teşkil eder. Menfaat, bir
malvarlığı değerine sahip olmak, kullanmak, işletmek dolayısıyla oluşan
ekonomik değer ilişkisidir.

IMPORTANT: Sigortanın konusu malın kendisi değil, o mal üzerindeki menfaattir.

Bir mal üzerinde menfaat sahibi olan herkes kendisine ait menfaati sigorta
ettirebilir.

===== PASİF ZARAR SİGORTASI

Kişinin, rizikonun gerçekleşmesi sebebiyle üçüncü kişilere karşı sorumlu hale
gelmesi ihtimalini kapsayan sigorta türlerine pasif zarar sigortası denir.

TIP: Trafik sigortası işleten sıfatındaki kişinin üçüncü kişilere karşı sorumlu
olması halinde üçüncü kişilerin zararının giderilmesine yönelik bir pasif zarar
sigortasıdır.

==== MEBLAĞ SİGORTASI

Meblağ sigortaları, zarar kavramından bağımsız sigorta sözleşmeleridir.
Sigortacının ödeme yapması için teminat kapsamında yer alan rizikonun
gerçekleşmiş olması yeterlidir.

=== TARİFELER

Sigorta tarifeleri, sigortacılık esasına ve genel kabul görmüş aktüeryal
tekniklere uygun olarak sigorta şirketleri tarafından serbestçe belirlenir.
Ancak, bu Kanuna ve diğer kanunlara göre ihdas edilen zorunlu sigortaların
teminat tutarları ile tarife ve talimatları Bakan tarafından tespit olunur ve
Resmî Gazetede yayımlanır.

Bakan, gerek görülen hallerde hayat, bir yıldan uzun süreli ferdî kaza, sağlık,
hastalık ve ihtiyarî deprem sigortaları tarifeleri ile prim, formül ve
cetvellerinin uygulamaya konulabilmesini Müsteşarlığın onayına tâbi kılabilir
veya özel kanunlardaki hükümler saklı kalmak kaydıyla gerekli görülen hallerde,
tespit ve ilan ettiği aracılık komisyonlarını, tasdike tâbi kıldığı veya tespit
ettiği her türlü tarifeyi serbest bırakabilir.

=== ZORUNLU SİGORTALAR

Bakanlar Kurulu, kamu yararı açısından gerekli gördüğü hallerde zorunlu
sigortalar ihdas edebilir. Sigorta şirketleri, Sigorta Kanunu 20 nci maddenin
ikinci fıkrasının (b) bendi ile üçüncü fıkrası hükümleri saklı kalmak kaydıyla
faaliyet gösterdiği sigorta branşlarının kapsamında bulunan zorunlu sigortaları
yapmaktan kaçınamaz.

=== SÖZLEŞMENİN YAPILMASI SIRASINDA SUSMA

Sigortacı ile sigorta sözleşmesi yapmak isteyen kişinin, sözleşmenin yapılması
için verdiği teklifname, teklifname tarihinden itibaren otuz gün içinde
reddedilmemişse sigorta sözleşmesi kurulmuş sayılır.

Teklifnamenin verilmesi sırasında yapılmış ödemeler, sözleşmenin yapılmasından
sonra prim olarak kabul edilir veya ilk prime sayılır. Bu ödemeler, sözleşme
yapılmadığı takdirde, kesinti yapılmadan, faiziyle birlikte geri verilir.

Ticaret Kanunu 1483. madde hükümleri saklıdır.

== ACENTE

*Sigorta acentesi*, ticarî mümessil, ticarî vekil, satış memuru veya müstahdem
gibi tâbi bir sıfatı olmaksızın bir sözleşmeye dayanarak muayyen bir yer veya
bölge içinde daimî bir surette sigorta şirketlerinin nam ve hesabına sigorta
sözleşmelerine aracılık etmeyi veya bunları sigorta şirketleri adına yapmayı
meslek edinen, sözleşmenin akdinden önce hazırlık çalışmalarını yürüten ve
sözleşmenin uygulanması ile tazminatın ödenmesinde yardımcı olan kişiyi ifade
eder.

İki tür acenter vardır: *Sözleşme yapma yetkisine sahip olan* acente ve *sadece
aracılık yapma yetkisine sahip olan* acente. Uygulamada bunlara *A tipi* ve *B
tipi* denilmektedir.

Acenteye, şirketin tüm branşları bakımından yetki verilirse *umumi acente*,
belirli branşlar bakımından yetki verilirse *hususi acente* adı verilir.

TIP: Acentenin yetkilendirdiği acenteye *tali acente* denir. Hazine
Müsteşartlığı sigortacılık bakımından buna izin vermemektedir.

Acente, aracılıkta bulunduğu veya yaptığı sözleşmelerle ilgili her türlü ihtar,
ihbar ve protesto gibi hakkı koruyan beyanları müvekkili adına yapmaya ve
bunları kabule yetkilidir.

=== ACENTE OLMAK İÇİN GEREKLİ KOŞULLAR

Hem gerçek hem de tüzel kişiler sigorta acentesi olabilir. Sigorta Acenteleri
Yönetmeliğinde aranan şartlar belirtilmiştir.

==== GERÇEK KİŞİ ACENTELER

Acentelik faaliyetinde bulunacak gerçek kişilerde aşağıdaki nitelikler aranır.

.. Teknik personel unvanını taşıması.
.. Türkiye’de yerleşik olması.
.. Kasten işlenen bir suçtan dolayı affa uğramış olsalar dahi 5 yıldan fazla
hapis,  sigortacılık mevzuatına aykırı hareketlerinden dolayı hapis veya birden
fazla adlî para cezasına mahkûm edilmemiş olması; devletin güvenliğine,
Anayasal düzene ve bu düzenin işleyişine, milli savunmaya ve devlet sırlarına
karşı suçlar ile casusluk, zimmet, irtikâp, rüşvet, hırsızlık, dolandırıcılık,
sahtecilik, güveni kötüye kullanma, hileli iflas, ihaleye fesat karıştırma,
edimin ifasına fesat karıştırma, bilişim sistemini engelleme, bozma, verileri
yok etme veya değiştirme, banka veya kredi kartlarının kötüye kullanılması,
suçtan kaynaklanan malvarlığı değerlerini aklama, terörün finansmanı,
kaçakçılık, vergi kaçakçılığı veya haksız mal edinme suçlarından hüküm giymemiş
olması.
.. Asgari mal varlığı şartını yerine getirmiş olması.
.. Fiziki şartlar, teknik ve idari altyapı ile insan kaynakları bakımından
yeterli donanıma sahip olması.
.. Mesleki deneyim süresini tamamlaması.

==== TÜZEL KİŞİ ACENTELER

Acentelik faaliyetinde bulunacak tüzel kişilerde aşağıdaki nitelikler aranır.

.. Merkezlerinin Türkiye’de bulunması ve anonim şirket veya limited şirket
şeklinde kurulmuş olmaları.
.. Asgari ödenmiş sermaye şartını yerine getirmiş olması.
.. Fiziki şartlar, teknik ve idari altyapı ile insan kaynakları bakımından
yeterli donanıma sahip olması.
.. Tüzel kişi acentelerin gerçek kişi ortakları ile tüzel kişi ortaklarının
gerçek kişi ortaklarında gerçek kişi acenteler için aranan şartlarda belirtilen
suçlardan birini işlememiş olma şartı aranır.

=== DENKLEŞTİRME TAZMİNATI

Sözleşme ilişkisinin sona ermesinden sonra;

.. Müvekkil, acentenin bulduğu yeni müşteriler sayesinde, sözleşme ilişkisinin
sona ermesinden sonra da önemli menfaatler elde ediyorsa,
.. Acente, sözleşme ilişkisinin sona ermesinin sonucu olarak, onun tarafından
işletmeye kazandırılmış müşterilerle yapılmış veya kısa bir süre içinde
yapılacak olan işler dolayısıyla sözleşme ilişkisi devam etmiş olsaydı elde
edeceği ücret isteme hakkını kaybediyorsa ve
.. Somut olayın özellik ve şartları değerlendirildiğinde, ödenmesi hakkaniyete
uygun düşüyorsa,

acente müvekkilden uygun bir tazminat isteyebilir.

Tazminat, acentenin son beş yıllık faaliyeti sonucu aldığı yıllık komisyon veya
diğer ödemelerin ortalamasını aşamaz. Sözleşme ilişkisi daha kısa bir süre
devam etmişse, faaliyetin devamı sırasındaki ortalama esas alınır.

Müvekkilin, feshi haklı gösterecek bir eylemi olmadan, acente sözleşmeyi
feshetmişse veya acentenin kusuru sebebiyle sözleşme müvekkil tarafından haklı
sebeplerle feshedilmişse, acente denkleştirme isteminde bulunamaz.

Denkleştirme isteminden önceden vazgeçilemez. Denkleştirme istem hakkının
sözleşme ilişkisinin sona ermesinden itibaren bir yıl içinde ileri sürülmesi
gerekir.

== BROKER

*Broker*, sigorta veya reasürans sözleşmesi yaptırmak isteyenleri temsil
ederek, bu sözleşmelerin yaptırılacağı şirketlerin seçiminde tamamen tarafsız
ve bağımsız davranarak ve teminat almak isteyen kişilerin hak ve menfaatlerini
gözeterek sözleşmelerin akdinden önceki hazırlık çalışmalarını yürütmeyi ve
gerektiğinde sözleşmelerin uygulanmasında veya tazminatın tahsilinde yardımcı
olmayı meslek edinen kişidir.

Brokerlik faaliyetinde bulunacak gerçek kişilerde aşağıdaki nitelikler aranır:

.. Türkiye’de yerleşik olması.
.. Medeni hakları kullanma ehliyetine sahip olması.
.. Kasten işlenen bir suçtan dolayı affa uğramış olsalar dahi 5 yıldan fazla
hapis veya sigortacılık mevzuatına aykırı hareketlerinden dolayı hapis veya
birden fazla adlî para cezasına mahkûm edilmemiş olması; devletin güvenliğine,
Anayasal düzene ve bu düzenin işleyişine, milli savunmaya ve devlet sırlarına
karşı suçlar ile casusluk, zimmet, irtikâp, rüşvet, hırsızlık, dolandırıcılık,
sahtecilik, güveni kötüye kullanma, hileli iflas, ihaleye fesat karıştırma,
edimin ifasına fesat karıştırma, bilişim sistemini engelleme, bozma, verileri
yok etme veya değiştirme, banka veya kredi kartlarının kötüye kullanılması,
suçtan kaynaklanan malvarlığı değerlerini aklama, terörün finansmanı,
kaçakçılık, vergi kaçakçılığı veya haksız mal edinme suçlarından hüküm giymemiş
olması.
.. Asgari malvarlığı şartını yerine getirmiş olması.
.. Brokerlik faaliyetinin yürütüleceği fiziksel mekân, teknik ve idari altyapı
ile insan kaynakları bakımından yeterli donanıma sahip olması.
.. Mesleki deneyim süresini tamamlaması.

Brokerlik faaliyetinde bulunacak tüzel kişilerde aşağıdaki nitelikler aranır:

.. Merkezlerinin Türkiye’de bulunması.
.. Anonim veya limited şirket şeklinde kurulmuş olması.
.. Asgari ödenmiş sermaye şartını yerine getirmiş olması.
.. Brokerlik faaliyetinin yürütüleceği fiziksel mekân, teknik ve idari altyapı
ile insan kaynakları bakımından yeterli donanıma sahip olması.
.. Genel müdür ile faaliyette bulunulan branşlar itibarıyla sigortacılık veya
sigortacılık tekniği ile ilgili konulardan sorumlu yeter sayıda genel müdür
yardımcısı atanması.

Brokerlik ruhsatı hayat, hayat dışı veya reasürans alanlarından bir veya
birkaçında ayrı ayrı verilir. Brokerlik faaliyetinde bulunmak isteyen gerçek
veya tüzel kişiler tarafından, Müsteşarlıkça belirlenecek usul ve esaslar
çerçevesinde ruhsat verilmesini teminen başvuru yapılır.

Brokerlik yetkisi, temsil edilecek tarafça sözleşmelerin akdinden önceki
hazırlık çalışmalarını yürütmeyi ve gerektiğinde sözleşmelerin uygulanmasına
ilişkin işlemleri gerçekleştirmeyi içeren yetki belgesi ile brokere verilir.
Ancak, tarafların fizikî olarak karşı karşıya gelmesinin ve işin gereği olarak
yetki belgesi verilmesinin söz konusu olmadığı hâllerde yetkilendirmenin sözlü
veya elektronik olarak verilmesi mümkündür.

Yetki belgesinde, yetkinin kapsamı, sınırı ve süresi açıkça belirtilir.
Brokerlik yetkisi, broker tarafından başka brokerlere veya kişilere
devredilmez.

Yetki verilen brokerlerin, yetki belgelerini ibraz etmek suretiyle teklif
alması, bu teklifleri ve karşılaştırmalı fiyatları brokerlik yetkisi veren
tarafa bildirmesi esastır.

Şirketler tarafından brokerlere verilecek yetkinin kapsam ve sınırı ile çalışma
esasları protokolle belirlenebilir. Brokerler, şirketlere portföy taahhüdünde
bulunamaz.

Prim tahsilatının şirket tarafından doğrudan sigorta ettirenden yapılması
esastır. Prim transferi konusunda brokerin şirket tarafından
yetkilendirilmesine ilişkin Müsteşarlıkça usul ve esas belirlenebilir.

Şirket tarafından prim transferi konusunda yetkilendirilen brokerlere yapılan
ödeme şirkete yapılmış sayılır.

Şirketlerce brokerlere yapılan prim iadeleri hak sahibi tarafından tahsil
edilmedikçe ödenmiş sayılmaz.

== AYDINLATMA YÜKÜMLÜLÜĞÜ

Sigortacı ve acentesi, sigorta sözleşmesinin kurulmasından önce, gerekli
inceleme süresi de tanınmak şartıyla kurulacak sigorta sözleşmesine ilişkin tüm
bilgileri, sigortalının haklarını, sigortalının özel olarak dikkat etmesi
gereken hükümleri, gelişmelere bağlı bildirim yükümlülüklerini sigorta ettirene
yazılı olarak bildirir. Ayrıca, poliçeden bağımsız olarak sözleşme süresince
sigorta ilişkisi bakımından önemli sayılabilecek olayları ve gelişmeleri
sigortalıya yazılı olarak açıklar.

TTK 1423 uyarınca öngörülen aydınlatma yükümlülüğü hem sözleşme müzakerelerinin
devam ettiği dönemde hem de sözleşmenin kurulmasından sonraki döndem varlığını
sürdürür.

Aydınlatma açıklamasının verilmemesi hâlinde, sigorta ettiren, sözleşmenin
yapılmasına ondört gün içinde itiraz etmemişse, sözleşme poliçede yazılı
şartlarla yapılmış olur. Aydınlatma açıklamasının verildiğinin ispatı
sigortacıya aittir.

NOTE: Sigorta ettirenin 14 gün içinde yapacağı itiraz genel kabule göre
sözleşmeyi sona erdirme beyanıdır. Bir görüşe göre sigorta sözleşmesi sürekli
borç doğuran bir sözleşme olduğundan ileriye etkili şekilde sona erecektir.
Diğer bir görüşe göre ise sözleşme bu 14 günlük süre boyunca askıda hükümsüzdür
ve beyan ileri sürüldüğü takdirde baştan itibaren geçersiz sayılır.

== SİGORTA POLİÇESİ VERME YÜKÜMLÜLÜĞÜ

*Poliçe*, sözleşmenin kurulduğunu ve hangi şartları içerdiğini belgeleyen, bunu
ispata yarayan araçtır.

Sigortacı; sigorta sözleşmesi kendisi veya acentesi tarafından yapılmışsa,
sözleşmenin yapılmasından itibaren yirmidört saat, diğer hâllerde onbeş gün
içinde, yetkililerce imzalanmış bir poliçeyi sigorta ettirene vermekle
yükümlüdür.

NOTE: Poliçeyi düzenleyip verme süresi sigorta şirketinin kendisi veya A tipi
acentesi için 24 saat, B tipi acente veya broker için 15 gündür.

Sigortacı poliçenin geç verilmesinden doğan zarardan sorumludur.

Sigorta ettiren poliçesini kaybederse, gideri kendisine ait olmak üzere, yeni
bir poliçe verilmesini sigortacıdan isteyebilir.

Poliçenin verilmediği hâllerde, sözleşmenin ispatı genel hükümlere tabidir.

Sigorta poliçesi, tarafların haklarını, temerrüde ilişkin hükümler ile genel ve
varsa özel şartları içerir, rahat ve kolay okunacak biçimde düzenlenir.

Poliçenin ve zeyilnâmenin eklerinin içeriği teklifnameden veya kararlaştırılan
hükümlerden farklıysa, anılan belgelerde yer alıp teklifnameden değişik olan ve
sigorta ettirenin, sigortalının ve lehtarın aleyhine öngörülmüş bulunan
hükümler geçersizdir.

Kanunlarda aksine hüküm bulunmadıkça, genel şartlarda sigorta ettirenin,
sigortalının veya lehtarın lehine olan bir değişiklik hemen ve doğrudan
uygulanır.

Ancak, bu değişiklik ek prim alınmasını gerektiriyorsa, sigortacı değişiklikten
itibaren sekiz gün içinde prim farkı isteyebilir. İstenilen prim farkının sekiz
gün içinde kabul edilmemesi hâlinde sözleşme eski genel şartlarla devam eder.
