:icons: font
:toc:
:toc-title: DENİZ TİCARET

== GEMİ

Tahsis edildiği amaç suda hareket etmesini gerektiren, yüzme özelliği bulunan
ve pek küçük olmayan her araç, kendiliğinden hareket etmesi imkânı bulunmasa
da, TTK bakımından *gemi* sayılır (TTK 931).

Geminin unsurları:

. _Pek küçük olmamak_: Her somut olayda denizcilik sektöründe egemen olan
anlayışa göre belirlenir.
. _Suda hareketi gerektiren bir amaca tahsis edilmiş olması_
. _Yüzme özelliğinin bulunması_

NOTE: Bir yerden bir yere bir başka gemi tarfından çekilerek götürülüyor olması
tek başına gemi olma özelliğini etkilemez.

Yukarıdaki unsurların başlangıçta mevcut olup, geçici olarak ortadan kalkması
aracın gemi olma niteliğini etkilemez. Aşağıdaki durumlarda ise gemi, gemi olma
özelliğini kaybeder:

. *Kurtarılamayacak şekilde batmış gemi*
. *Tamir kabul etmez gemi*: Tamiri hiç veya bulunduğu yerde mümkün değilse ve
tamir edilebileceği bir limana götürülemezse
. *Suda devamlı olarak hareketi gerektiren bir amaca tahsis edilme unsurunun
ortadan kalkması*

=== BÜTÜNLEYİCİ PARÇA VE EKLENTİ

Geminin yapısını değiştirmeden, zarara uğratmadan ondan ayrılamayan parçalara
*bütünleyici parça* denir. Örneğin geminin makinesi, pervanesi, dümeni
bütünleyici parça olarak kabul edilir. Gemi üzerinde yapılan her tasarruf
işlemi bütünleyici parçaları da kapsar, bunun aksini kararlaştırmak mümkün
değildir.

Bütünleyici parça niteliğinde olmayan ancak devamlı olarak gemiye özgülenmiş
taşınırlar **eklenti**dir. Eklentiler de tasarruf işlemine kendiliğinden dahil
olur ancak bunun aksini kararlaştırmak mümkündür.

[NOTE]
====
Gemideki bazı şeyler ne bütünleyici parça ne de eklentidir. Bu şeyler tasarruf
işlemine kendiliğinden dahil olmaz, açıkça dahil edilmeleri gerekir. Bu konuda
en tipik örnek yakıttır.
====

=== TİCARİ GEMİ

Suda ekonomik menfaat sağlama amacına tahsis edilen veya fiilen böyle bir amaç
için kullanılan her gemi, kimin tarafından ve kimin adına veya hesabına
kullanılırsa kullanılsın *ticaret gemisi* sayılır.

TIP: Kazanç elde etme doğrudan olabileceği gibi dolaylı da olabilir. Bir gemi
sahibi kendi yükünü taşıyarak başkasına taşıtmış olsaydı ödeyeceği navlunu
ödemekten kurtulduğu için malvarlığının aktifinde meydana gelecek azalmanın
önlenmesi şeklinde dolaylı kazanç elde etmiş olur.

TTK hükümleri kural olarak sadece ticari gemiler için geçerlidir. Ancak TTK
hükümlerinin ticari olmayan gemilere uygulanacağı istisnaları TTK 935
belirtmiştir.

TTK'nın;

. “Gemi”, “Kaptan”, “Gemi Alacakları” ve “Cebrî İcraya İlişkin Özel Hükümler”
başlıklı Kısımları, “Çatma” ve “Kurtarma” başlıklı Bölümleri, deniz
alacaklarına karşı sorumluluğun sınırlanması hakkındaki hükümleri ile
donatanın, gemi adamlarının kusurundan doğan sorumluluğuna ilişkin 1062 nci
maddesi, yatlar, denizci yetiştirme gemileri gibi sadece gezinti, spor, eğitim,
öğretim ve bilim amaçlarına tahsis edilmiş gemilere,
. “Çatma” ve “Kurtarma” başlıklı Bölümleri, deniz alacaklarına karşı
sorumluluğun sınırlanması hakkındaki hükümleri ile donatanın, gemi adamlarının
kusurundan doğan sorumluluğuna ilişkin 1062 nci maddesi, münhasıran bir kamu
hizmetine tahsis edilen Devlet gemileriyle donanmaya bağlı harp gemilerine ve
yardımcı gemilere,
. Bayrak şahadetnamesi ile ilgili 944 üncü maddenin ikinci fıkrası ile 945,
947, 948 ve 949 uncu maddeleri, sicille ilgili 955, 956, 973 ve 991 inci
maddeleri, kanuni ipotekle ilgili 1013 üncü maddesi ve yapı hâlinde bulunan
gemiler üzerindeki haklarla ilgili 1054 ilâ 1058 inci maddeleri yabancı bir
devlet veya onun vatandaşları adına Türkiye’de yapılmakta olan gemilere de,
nitelikleri ile bağdaştığı ölçüde, uygulanır.

=== GEMİNİN HUKUKİ NİTELİĞİ

Sicile kayıtlı olup olmadıklarına bakılmaksızın bütün gemiler TTK'nın ve diğer
kanunların uygulanmasında taşınır eşyadandır (TTK 936).

TTK'da, İcra ve İflas Kanununun taşınmazlara ilişkin hükümlerine tabi
olacağı açıkça bildirilen gemiler hakkında 936 ncı madde hükmü uygulanmaz.

Türk Medenî Kanununun 429 uncu maddesinin birinci fıkrasının (2) numaralı bendi
ile 444 üncü, 523 üncü ve 635 inci maddelerinin uygulanmasında, “taşınmaz”
terimine yapı hâlinde veya tamamlanmış olan bütün gemiler ve “tapu sicili”
terimine “gemi sicilleri” de dâhildir.

=== GEMİNİN AYIRICI UNSURLARI

. *Geminin adı*: Geminin ilk Türk maliki, gemiye dilediği adı vermekte
serbesttir. Şu kadar ki, seçilen ad karıştırılmaya yol açmayacak şekilde
başka gemilerin adlarından farklı olmalıdır.
+
CAUTION: Gemi tasdiknamesi verilmiş olan bir geminin adı Ulaştırma,
Denizcilik ve Haberleşme Bakanlığının izniyle değiştirilebilir.
+
Sicile kayıtlı bir geminin bordasının her iki tarafına adı, kıçına da adı ile
bağlama limanı; silinmez, bozulmaz ve kolayca okunacak harflerle yazılır.
. *Tanınma işareti*: Ulaştırma, Denizcilik ve Haberleşme Bakanlığı tarafından
Gemi Sicil Müdürlüklerine gönderilen telsiz tanınma işareti tescil sırasına
göre gemilere dağıtılır.
. *Bağlama limanı*: Bir geminin bağlama limanı o gemiye ait seferlerin
yönetildiği yerdir.
+
Gemi, bağlama limanının tabi olduğu sicil dairesine tescil edilir. Bağlama
limanı yoksa tescil edilecek sicil dairesi iradi olarak seçilebilir. Tescil
edilen sicil dairesi bağlama limanı haline gelir.
+
Bağlama limanı aşağıdaki hallerde yoktur:

.. Gemi seferlerinin yabancı bir limandan yönetilmesi
.. Gemi seferlerinin bir kara kentinden yönetilmesi
.. Gemi seferlerinin gemi bordasından yönetilmesi

+
[caption=""]
.Bağlama limanının önem taşıdığı diğer haller
====
* Kaptanın donatanı temsil yetkisi geminin bağlama limanında bulunup
bulunmamasına göre daralır veya genişler.
* Donatana karşı veya donatan sıfatıyla açılacak davalar genel yetki kuralları
haricinde bağlama limanının bulunduğu mahkemede de açılabilir.
====
. *Geminin tonajı*: Gemilerin ölçümü 1969 tarihli _Gemilerin Tonilatolarını
Ölçme Uluslarası Antlaşması_ uyarınca iç hukukumuzda çıkarılmış _Gemilerin
Tonilatolarını Ölçme Yönetmeliği_ ile düzenlenmiş kurallar çerçevesinde
yapılır. Ölçüm sonucunda bir *tonilato belgesi* düzenlenir ve sicile geçirilir.

* *GRT*: Geminin bütün kapalı yerlerinin hacmi
* *Net ton*: GRT'den yönetmelikte belirtilen bir takım hacimlerin eksiltilmesi
ile hesaplanır.
* *Deadweight (dwt)*: Geminin yük, yakıt vs. taşıyabileceği maksimum ağırlık

+
[caption=""]
.Tonilatonun önem taşıdığı haller
====
* Yük ve yolcu kapasitesinin belirlenmesi
* Donatanın sorumluluğunun belirlenmesi
* Alınacak verginin belirlenmesi
* Gemide bulunması gereken teçhizat ve gemi adamlarının belirlenmesi
====
. *Geminin sınıfı*: Uluslararası bağımsız gemi sınıflama kuruluşları tarafından
gemiler belli aralıklarla veya belli durumlarda denetlenerek sınıfları
belirlenir ve bu sınıf sicile geçirilir.
. *Geminin milliyeti*: Geminin milliyeti, çektiği bayrağa göre belirlenir.

== BAYRAK ÇEKME HAKKI VE KAZANILMASI

=== MİLLİ GEMİ SİCİLİNE GÖRE

Her Türk gemisi Türk Bayrağı çeker. Yalnız Türk vatandaşının malik olduğu gemi,
Türk gemisidir.

Birden fazla kişiye ait olan gemiler;

.. Paylı mülkiyet hâlinde, payların çoğunluğunun,
.. Elbirliğiyle mülkiyet hâlinde, maliklerinin çoğunluğunun,

Türk vatandaşı olması şartıyla Türk gemisi sayılırlar.

Türk kanunları uyarınca kurulup da;

.. Tüzel kişiliğe sahip olan kuruluş, kurum, dernek ve vakıflara ait olan
gemiler, yönetim organını oluşturan kişilerin çoğunluğunun Türk vatandaşı
olması,
.. Türk ticaret şirketlerine ait olan gemiler, şirketi yönetmeye yetkili
olanların çoğunluğunun Türk vatandaşı olmaları ve şirket sözleşmesine göre oy
çoğunluğunun Türk ortaklarda bulunması, anonim ve sermayesi paylara bölünmüş
komandit şirketlerde ayrıca payların çoğunluğunun nama yazılı ve bir
yabancıya devrinin şirket yönetim kurulunun iznine bağlı bulunması,

şartıyla Türk gemisi sayılırlar.

Türk ticaret siciline tescil edilen donatma iştiraklerinin mülkiyetindeki
gemiler, paylarının yarısından fazlası Türk vatandaşlarına ait ve iştiraki
yönetmeye yetkili paydaş donatanların çoğunluğunun Türk vatandaşı olması
şartıyla Türk gemisi sayılırlar (TTK 940).

Bir Türk gemisi, kendilerine ait olduğu takdirde Türk Bayrağı çekme hakkını
kaybedeceği kişilere, en az bir yıl süreyle kendi adlarına işletilmek üzere
bırakılmış olursa, malikin istemi üzerine Ulaştırma, Denizcilik ve Haberleşme
Bakanlığı, bırakma süresince, o ülke kanunları buna imkân sağlıyorsa geminin
yabancı bayrak çekmesine izin verebilir. Bu izin sona ermedikçe veya kanuni
sebeplerle geri alınmadıkça gemi Türk Bayrağı çekemez (TTK 941/1).

Türk gemisi olmayan bir gemi, ona Türk Bayrağı çekebilecek kişilere en az bir
yıl süreyle kendi adlarına işletilmek üzere bırakılmışsa, malikin rızası
alınmış olmak, Türk mevzuatının kaptan ve gemi zabitleri hakkındaki hükümlerine
uyulmak ve yabancı kanunda da bunu engelleyen bir hüküm bulunmamak şartıyla,
Ulaştırma, Denizcilik ve Haberleşme Bakanlığı geminin Türk Bayrağı çekmesine
izin verebilir. Şu kadar ki, izin alan kişi, her iki yılda bir, izin için
gerekli şartların varlığını sürdürdüğünü ispatlamakla yükümlüdür. Söz konusu
gemiler, Ulaştırma, Denizcilik ve Haberleşme Bakanlığınca tutulacak özel bir
sicile kaydolunur (TTK 941/2,3).

940 ıncı madde ile 941 inci maddenin ikinci fıkrasında yazılı şartlardan
birinin ortadan kalkmasıyla gemi Türk Bayrağı çekme hakkını kaybeder. Bu durum
gecikmeksizin Ulaştırma, Denizcilik ve Haberleşme Bakanlığına bildirilir.
Müsteşarlık en çok altı ay için daha geminin Türk Bayrağı çekmesine izin
verebilir (TTK 942).

Geminin Türk Bayrağını çekme hakkı, *gemi tasdiknamesi* ile ispat olunur. Gemi
tasdiknamesi gemi sicil kayıtlarının aynen ve tamamen yer aldığı bir belgedir.
Gemi tasdiknamesi alınmadıkça, Türk Bayrağını çekme hakkı kullanılamaz. Gemi
tasdiknamesi veya bunun sicil müdürlüğünce onaylanmış bir özeti veya bayrak
şahadetnamesi yolculuk sırasında devamlı olarak gemide bulundurulur.

Türkiye dışında bulunan bir gemi Türk Bayrağını çekme hakkını elde ederse,
geminin bulunduğu yerdeki Türk konsolosu tarafından Türk Bayrağını çekme
hakkına dair verilecek “bayrak şahadetnamesi” gemi tasdiknamesi yerine geçer.
Bayrak şahadetnamesi, düzenlendiği günden itibaren ancak bir yıl için
geçerlidir; yolculuk, mücbir sebep yüzünden uzadığı takdirde süre de uzar.

Türkiye’de yapılmış olup da 940 ıncı madde gereğince Türk Bayrağını çekme
hakkına sahip bulunmayan gemilere, Ulaştırma, Denizcilik ve Haberleşme
Bakanlığınca, teslim edilecekleri yere kadar geçerli olmak üzere bir bayrak
şahadetnamesi verilebilir.

941 inci maddenin ikinci fıkrası ile 942 nci maddede yazılı hâllerde, bayrak
şahadetnamesi, izin süresi için geçerli olmak üzere Ulaştırma, Denizcilik ve
Haberleşme Bakanlığınca düzenlenir.

Onsekiz gros tonilatodan küçük gemilerle sadece gezinti, spor, eğitim, öğretim
ve bilim amaçlarına tahsis edilmiş gemiler, gemi tasdiknamesine ve bayrak
şahadetnamesine ihtiyaç olmaksızın Türk Bayrağı çekebilirler.

=== TÜRK ULUSLARARASI GEMİ SİCİLİNE GÖRE

TUGS'a tescil için aranan koşullar gerçeklemiş ise, TUGS'a tescil ile birlikte
o gemi bayrak çekme hakkını kazanır. Hakkın kullanılması için TUGS gemi
tasdiknamesi gereklidir.

=== BAĞLAMA KÜTÜĞÜNE GÖRE

Bağlama kütüğüne kayıtlı gemiler TTK 940'a bağlı olmaksızın Türk bayrağı çeker.
Hakkın kullanılabilmesi içim *bağlama kütüğü ruhsatnamesi* gereklidir.

== GEMİ SİCİLLERİ

=== MİLLİ GEMİ SİCİLİ

==== TESCİL

Gemi siciline, 940 ıncı madde gereğince Türk Bayrağını çekme hakkına sahip
ticaret gemileri ile sadece gezinti, spor, eğitim, öğretim ve bilim amaçlarına
tahsis edilmiş gemiler ve yabancı bir devlet veya onun vatandaşları adına
Türkiye’de yapılmakta olan gemiler kaydolunur.

IMPORTANT: Onsekiz gros tonilatoda ve daha büyük her ticaret gemisinin maliki,
tescil isteminde bulunmak zorundadır. Meğer ki bu gemi TUGS'a kayıtlı olsun.

Türk gemisi olmayan gemilerle, yabancı bir gemi siciline kayıtlı bulunan Türk
gemileri, donanmaya bağlı harp gemileri, yardımcı gemiler ve Devlet, il özel
idaresi, belediye ve köy ile diğer kamu tüzel kişilerine ait münhasıran bir
kamu hizmetinin görülmesine özgülenmiş gemiler Türk Gemi Siciline tescil
olunamaz.

Gemi, bağlama limanının tabi olduğu sicil müdürlüğünce tescil olunur.

Bir geminin seferleri yabancı bir limandan veya bir kara kentinden yahut bizzat
gemiden yönetildiği takdirde, malik, gemisini dilediği yer siciline tescil
ettirebilir.

Malikin, Türkiye’de yerleşim yeri veya ticari işletmesi yoksa, bu Kanunda
yazılı hakları kullanmak ve görevleri yerine getirmek üzere, sicil müdürlüğüne
o bölgede oturan bir temsilci göstermesi gereklidir.

Hali hazırda on tane sicil müdürlüğü mevcuttur:

. İstanbul
. İzmir
. Çanakkale
. Antalya
. Mersin
. İskenderun
. Bandırma
. Trabzon
. Samsun
. Zonguldak

Gemi, ancak malikin veya maliklerinden birinin istemi üzerine gemi siciline
tescil olunur.

Tescil istemiyle birlikte aşağıdaki hususlar bildirilir:

.. Geminin adı.
.. Türü ve yapımında kullanılmış olan esas malzeme.
.. Bağlama limanı.
.. Belirlenmesi mümkünse, yapıldığı yer ve kızaktan indiği yıl.
.. Resmî ölçme sonuçları ve makine gücü.
.. Geminin maliki;

... Gerçek kişi ise, adı ve soyadı, T.C. kimlik numarası, varsa ticaret unvanı
ve kayıtlı bulunduğu ticaret sicili müdürlüğü ile sicil numarası.
... Ticaret şirketi ise, şirketin türü, ticaret unvanı ve tescil olunduğu
ticaret sicili müdürlüğü ile sicil numarası.
... Diğer tüzel kişilerden ise, adı ve merkezi.
... Donatma iştiraki ise, tacir sıfatına sahip olduğu takdirde ticaret unvanı
ile paydaş donatanların ad ve soyadları, varsa T.C. kimlik numarası ile gemi
paylarının miktarı ve varsa gemi müdürünün adı ve soyadı ve T.C. kimlik
numarası.

.. İktisap sebebi.
.. Türk Bayrağını çekme hakkına esas oluşturan sebepler.
.. Varsa temsilcinin adı, soyadı, TC kimlik numarası ve adresi.

==== GÖZETMEN MAHKEME

Siciller mahkeme gözetiminde tutulur. Söz konusu mahkeme o yerde deniz ticareti
işlerine bakmakla görevli Asliye Ticaret Mahkemesi varsa bu mahkeme, yoksa o
yer Asliye Ticaret Mahkemesi, bu da yoksa o yerde ticaret davalarına bakmakla
görevli Asliye Hukuk Mahkemesi'dir.

Sicil müdürlüğünün kararlarına karşı itirazda bulunulacak mercii gözetmen
mahkemedir. Sicil müdürlüğünün kararlarına karşı itiraz prosedürü için TTK 34
uygulanır.

[caption=""]
.TTK 34 - İtiraz
====
(1) İlgililer, tescil, değişiklik veya silinme istemleri ile ilgili olarak,
sicil müdürlüğünce verilecek kararlara karşı, tebliğlerinden itibaren sekiz gün
içinde, sicilin bulunduğu yerde ticari davalara bakmakla görevli asliye ticaret
mahkemesine dilekçe ile itiraz edebilirler.

(2) Bu itiraz mahkemece dosya üzerinden incelenerek karara bağlanır. Ancak,
sicil müdürünün kararı, üçüncü kişilerin sicilde kayıtlı bulunan hususlara
ilişkin menfaatlerine aykırı olduğu takdirde, itiraz edenle üçüncü kişi de
dinlenir. Bunlar mahkemeye gelmezlerse dosya üzerinden karar verilir.
====

MGS bakımından TMK 1007 uygulama alanı bulur ve devlet bu sicilin hatalı
tutulmasından doğan zararlardan sorumludur. Sorumluluk davasına gözetmen
mahkeme bakar.

==== TERKİN

Gemi, kurtarılamayacak şekilde batar veya tamir kabul etmez hâle gelir yahut
her ne suretle olursa olsun Türk Bayrağını çekme hakkını kaybederse, istem
üzerine sicilden kaydı silinir. Tescili isteğe bağlı olan gemilerin kaydı
malik veya maliklerinin istemi üzerine sicilden silinir.

Geminin tamir kabul etmez hâle gelmesi sebebiyle kaydının silinmesi
istendiğinde, sicil memuru, tescil edilmiş gemi ipoteği alacaklılarını
gerektiğinde 966 ncı madde de yazılı usule göre yapılacak ilan ile durumdan
haberdar ederek belirleyeceği uygun bir süre içinde itirazlarını bildirmeye
çağırır. Süresi içinde bildirilen itirazların yerinde görülmediğine dair
mahkemece verilen kararın kesinleşmesi üzerine geminin kaydı silinir.

Gemi, Türk Bayrağını çekme hakkını kaybederse, kaydı, ancak ipotek
alacaklılarının ve gemi sicilindeki kayıt ve belgelere göre ipotek üzerinde hak
sahibi olan üçüncü kişilerin onayı ile sicilden silinebilir. Kaydın silinmesi
istemi ile birlikte onay belgelenmemişse, geminin Türk Bayrağını çekme hakkını
kaybettiği gecikmeksizin gemi siciline kaydolunur. Bu kayıt, gemi üzerinde
tescil edilmiş gemi ipotekleri bulunmadıkça, geminin kaydının silinmesi
hükmündedir.

Tescili isteğe bağlı olan gemilere ait kayıtların sadece maliklerinin istemleri
üzerine silinebilmesi için ipotekli alacaklıların ve gemi sicilinin içeriğine
göre ipotek üzerinde hak sahibi olan üçüncü kişilerin buna onay vermeleri
şarttır.

Esaslı şartlarından birinin var olmaması sebebiyle tescili caiz olmayan bir
gemi tescil edilmiş olur veya 964 üncü maddenin üçüncü fıkrasında yazılı
hâllerden birinin ortaya çıktığı sicil müdürlüğüne bildirilmezse, 33 üncü madde
hükmü uygulanır. Şu kadar ki, durumun sicile kayıtlı diğer hak sahiplerine de
bildirilmesi gereklidir. Malik ve diğer hak sahiplerinin kimler olduğu veya
yerleşim yerleri belli değilse, silinmeye çağrı ve belirlenen süre, Türkiye
Ticaret Sicili Gazetesi ile uygun görülen diğer bir gazetede ve varsa şirketin
internet sitesinde ilan edilir ve ilan belgesi sicil müdürlüğü ve mahkeme
divanhanesine asılır.

Geminin kaydı ancak kaçınma ve itiraz sebeplerinin süresi içinde bildirilmemesi
veya bunların mahkemece yerinde görülmediğine dair verilen kararın kesinleşmesi
hâlinde sicilden silinebilir. Bir ipotekli alacaklı, gemi ipoteğinin hâla var
olduğunu ileri sürerek Türk Bayrağını çekme hakkını kaybetmiş olan bir geminin
sicilden silinmesine itiraz ederse, kayıt silinmeyip sadece geminin Türk
Bayrağını çekme hakkını kaybettiği tescil olunur.

Tescil edilmiş bir gemi hakkında yirmi yıldan beri hiçbir kayıt işlemi
yapılmamış ve Ulaştırma, Denizcilik ve Haberleşme Bakanlığından alınan bilgiye
göre de geminin artık var olmadığına veya denizcilikte kullanılamayacak hâle
geldiğine kanaat getirilmiş olursa, gemi üzerinde ipotek veya intifa hakkı
tescil edilmiş bulunmadığı takdirde, sicil memurunun önerisi üzerine mahkeme,
966 ncı maddede yazılı usule gerek kalmaksızın, gemi kaydının silinmesine karar
verir.

TIP: Milli Gemi Sicili'nde kayıtlı bir gemi Türkiye Uluslararası Gemi Sicili'ne
kaydedilecek olursa MGS'den terkin edilir.

==== SİCİL KAYDININ HÜKÜMLERİ

===== KARİNELER

Gemi sicilinde malik olarak kayıtlı bulunan kişi, geminin maliki sayılır.

Gemi sicilinde lehine bir gemi ipoteği veya ipotek üzerinde bir hak yahut bir
intifa hakkı tescil edilmiş olan kişi o hakkın sahibi sayılır.

Tescil olunmuş bir hak sicilden silinirse o hakkın artık var olmadığı kabul
edilir.

NOTE: Türk Medenî Kanununun 992 nci maddesinin ikinci fıkrası hükmü saklıdır.

===== SİCİLİN DÜZELTİLMESİ

Gemi sicilinin içeriği; mülkiyet, gemi ipoteği, ipotek üzerindeki bir hak,
intifa hakkı yahut 983 üncü maddenin birinci fıkrasının ikinci cümlesinde
yazılı türden bir tasarruf sınırlaması bakımından gerçek hukuki duruma uymadığı
takdirde, hakkı tescil edilmemiş veya yanlış tescil edilmiş yahut var olmayan
bir hakkın veya sınırlamanın tescili sonucunda hakkı ihlal edilmiş kişi,
değişiklik sonucunda hakkı ihlal edilecek olan kişiden kaydın değiştirilmesine
onay vermesini isteyebilir.

===== İTİRAZ

Yukarıda yazılı hâllerde gemi siciline, sicil kaydının doğru olmadığı hakkında
bir itiraz tescil olunabilir.

İtiraz, bir ihtiyati tedbir kararına yahut sicildeki kaydın değiştirilmesi
sonucunda hakkı zarar görecek olan kişinin onayına dayalı olarak sicile
geçirilir. İhtiyati tedbir kararının verilmesinde hakkın tehlikede olduğuna
dair yaklaşık ispat şartı aranmaz.

===== ŞERH

Bir gemi veya gemi ipoteği üzerinde bir hakkın kurulmasını veya kaldırılmasını
yahut böyle bir hakkın içeriği veya derecesinin değiştirilmesini isteyebilmek
hakkını teminat altına almak için gemi siciline şerh verilebilir. Gelecekte
doğacak veya şarta bağlı bir istem hakkının teminat altına alınması amacıyla
gemi siciline şerh verilmesi mümkündür.

Şerhten sonra gemi veya ipotek üzerinde yapılacak tasarruflar, şerh ile teminat
altına alınan hakkı ihlal ettiği ölçüde geçerli değildir. Tasarrufun cebrî icra
veya ihtiyati haciz yoluyla yahut iflas idaresi tarafından yapılması hâllerinde
de hüküm böyledir.

Şerh ile teminat altına alınan hakkın derecesini belirlemede şerh tarihi esas
tutulur.

Şerh, bir ihtiyati tedbir kararına yahut şerh sonucunda gemisi veya hakkı
sınırlanan kişinin onayına dayalı olarak verilir. İhtiyati tedbir kararının
verilmesinde hakkın tehlikede olduğuna dair yaklaşık ispat şartı aranmaz.

Mülkiyetin, gemi ipoteğinin veya ipotek üzerindeki hakkın yahut bir intifa
hakkının iktisabı, lehine şerh verilen kişiye karşı geçersiz olduğu takdirde,
şerh sahibi, şerh ile teminat altına alınan istem hakkının gerçekleşmesi için
gerekli olan tescile veya silinmeye onay vermesini iktisap edenden isteyebilir.

===== SİCİLE GÜVEN İLKESİ

Hukuki bir işlem ile bir geminin mülkiyetini, intifa hakkını gemi ipoteğini
veya ipotek üzerindeki bir hakkı iktisap eden kişi lehine gemi sicilinin
içeriği, bu haklarla ilgili olduğu ölçüde doğru sayılır; meğerki, iktisap eden
kişi kaydın doğru olmadığını bilmiş veya bilmesi gerekmiş olsun. Hak sahibinin
kayıtlı bir hak üzerindeki tasarruf yetkisi belli bir kişi lehine sınırlanmış
ise, bu sınırlama iktisap eden hakkında ancak gemi sicilinde yazılı olması veya
onun sicil kaydının doğru olmadığını bilmesi veya bilmesinin gerekmesi şartıyla
hüküm ifade eder.

Hakkın iktisabı için tescil şart olan hâllerde, kaydın doğru olmadığının
bilinmesi bakımından tescili istem tarihi asıldır.

Gemi sicilinde lehine bir hak tescil edilmiş olan bir kişiye bu hakkı sebebiyle
bir edimde bulunulması veya bu kişinin üçüncü bir kişi ile, sicile kayıtlı bir
hak üzerinde yukarıdakiler dışında bir tasarruf işlemi yapılması hâllerinde de
yukarıdaki hükümler uygulanır.

=== YAPI HALİNDEKİ GEMİLERE ÖZGÜ SİCİL

Yapı hâlindeki bir gemi, malikin istemi üzerine veya yapı üzerinde bir gemi
ipoteğinin kurulması yahut yapının ihtiyati ya da kesin haczi veya tersane
sahibinin gemi ipoteğinin kurulmasına yönelik istem hakkını teminat altına
almak amacıyla sicile şerh verilmesi söz konusu olduğu takdirde yapı hâlindeki
gemilere özgü sicile kaydolunur.

Yapı, malikinin veya kanuni ipotek hakkını tescil ettirmek isteyen tersane
sahibinin dilekçesi ile yapı hâlindeki gemilere özgü sicile kaydolunur.

İhtiyati veya icraî haciz kararı almış olan alacaklı da icra müdürünün yazısı
ile yapının sicile kaydını isteyebilir.

Yapı, yapım yerinin bağlı bulunduğu sicil müdürlüğünce tescil olunur. Yapı, bu
sicil müdürlüğünün yetki çevresi dışındaki diğer bir yere götürülse de aynı
sicil müdürlüğü yetkili kalır. Şu kadar ki, bu müdürlük tarafından yeni yapım
yerindeki sicil müdürlüğüne yapının kaydedilmiş olduğu bildirilir.

Yapının tamamlanması ile yapı sicilindeki kayıt terkin edilerek milli gemi
siciline aktarılır. Üzerinde bir ipotek kurulmuş ise ipoteğin derecesi
değişmeden aktarılır.

Yapının sicildeki kaydı;

.. Geminin tersane sahibi tarafından, yabancı ülkeye teslim edildiğinin
bildirilmesi,
.. Yapının maliki ile geminin yapıldığı tersane sahibinin, kaydın sicilden
silinmesini istemeleri,
.. Yapının harap olması,

hâllerinde silinir.

Yapı üzerinde bir ipotek bulunduğu takdirde, yukarıdaki (a) ve (b) bentlerinde
yazılı hâllerde, ipotekli alacaklının ve sicile kayıtlı bulunan diğer hak
sahiplerinin kaydın sicilden silinmesine onayları da gereklidir.

Yapının tamamlanarak geminin yabancı ülkeye teslim edildiğinin veya harap
olduğunun süresi içinde bildirilmemesi hâlinde 966 ncı maddedeki usul uyarınca
yapının kaydı resen sicilden silinir.

=== TÜRK ULUSLARARASI GEMİ SİCİLİ

*Gemi*: Kabotaj ve/veya kabotaj harici sularda ticari amaçla kullanılan her
türlü yük, yolcu ve açık deniz balıkçı gemileri ile özel maksatlı ve özel
yapılı gemi.

*Yat*: Yat tipinde inşa edilmiş, gezi ve spor amacıyla yararlanılan,
taşıyacakları yatçı sayısı otuzaltıyı geçmeyen, yük ve yolcu gemisi niteliğinde
olmayan, turizm şirketi envanterlerinde kayıtlı ve tonilato belgelerinde
"Ticari Yat" olarak belirtilen deniz aracı.

*Özel maksatlı ve özel yapılı gemi*: Tipleri ve evsafları Bakanlık tarafından
belirlenen, özel bir amaçla işletilen ve bu amaçla donatılan, yüzme özelliği
bulunan deniz aracı.

IMPORTANT: TUGS'a tescil bakımından esas önemli unsur ticari amaçla
kullanılmaktır.

Türk Uluslararası Gemi Siciline aşağıdaki gemiler ve yatlar talep üzerine
tescil edilir:

.. 4490 sayılı kanunun yürürlüğe girdiği tarihte (21/12/1999) Milli Gemi
Siciline kayıtlı bulunan ve yukarıdaki tanımlara uyan bütün gemiler ve yatlar.
.. Yurt içinde inşa edilen gemiler ve yatlar.
.. Yurt dışından ithal edilen 3.000 DWT'nin (yolcu gemileri ile özel maksatlı,
özel yapılı gemilerde ise 300 grostonun) üzerindeki gemiler.

Türkiye'de mukim Türk ve yabancı uyruklu gerçek kişiler ile Türkiye'de Türk
mevzuatına göre kurulmuş şirketlere ait gemiler ve yatlar Türk Uluslararası
Gemi Siciline tescil ettirilebilir.

Yurt dışından finansal kiralama yoluyla temin edilecek gemiler ve yatlar Türk
Uluslararası Gemi Sicilinin özel bir sütununa kaydolunur.

Türk Uluslararası Gemi Siciline tescil edilen gemiler ve yatlar Türk Bayrağı
çekerler.

=== BAĞLAMA KÜTÜĞÜ

Bağlama Kütüğü Uygulama Yönetmeliği'ne göre *gemi*, cinsi, tonilatosu ve
kullanma amacı ne olursa olsun, denizde kürekten başka aletle yola çıkabilen
her aracı ifade eder.

*Deniz aracı*, gemi dışında, denizde yüzebilen ve tahsis edildiği gayeye uygun
olarak kullanılan her türlü araç ve yapıyı ifade eder. *İç su aracı*, iç
sularda kullanılan ve gemi dışındaki her türlü tekne ve yapıyı ifade eder.

Bağlama kütüğüne;

.. 18 gros tonilatonun altında ve 2,5 metre ve üzerindeki; Milli Gemi Siciline
veya Türk Uluslararası Gemi Siciline tescil edilmemiş ticari gemi, deniz ve
içsu araçları,
.. Boyu 2,5 metre ve üzerindeki özel kullanıma mahsus gemi, deniz ve içsu
araçları,

zorunlu olarak kaydedilir.

Bağlama kütüğüne;

.. 6102 sayılı Türk Ticaret Kanununun bayrak çekme hükümlerine bağlı
olmaksızın; yabancı uyruklu olup oturma izni bulunan gerçek kişilere ait özel
kullanıma mahsus gemi, deniz ve içsu araçları,
.. Devlete ait olup temel kamu hizmetlerinde kullanılan gemi, deniz ve içsu
araçları,
.. 2,5 metrenin altındaki ticari ve özel gemi, deniz ve içsu araçları,
.. Gençlik ve Spor Bakanlığınca tescil edilmiş spor kulübü ve federasyonların
envanterinde kayıtlı olup da münhasıran spor faaliyetleri için kullanılan gemi,
deniz ve içsu araçları,

talep olması hâlinde kayıt edilir.

Bağlama kütüğü, her liman başkanlığında ve liman başkanlığının yetki alanında
bulunmayan iç sularda belediye başkanlıkları bünyesinde kurulur. Bağlama
kütüğünün iç sularda hangi belediye başkanlıkları bünyesinde tutulacağı
Bakanlık tarafından belirlenir.

Bağlama kütüğüne kayıtlı gemi, deniz ve içsu araçları Türk bayrağı çekmek
zorundadır. Gemi, deniz ve içsu aracının Türk Bayrağı çekme hakkı geçerli
ruhsatname ile ispat olunur. Bağlama kütüğüne kayıtlı ticari gemi, deniz ve
içsu araçları ile yabancılara ait özel kullanıma mahsus gemi, deniz ve içsu
araçları, 6102 sayılı Türk Ticaret Kanununun bayrak çekme ile ilgili
hükümlerine bağlı olmaksızın Türk Bayrağı çeker.

NOTE: Yargıtay 2014 yılında verdiği bir kararda bağlama kütüğüne kayıtlı
gemileri sicile kayıtlı olmayan gemi olarak tanımlamıştır. Dolayısıyla bağlama
kütüğü Yargıtay'a göre bir sicil değildir.

== GEMİ ÜZERİNDEKİ AYNİ HAKLAR

Deniz araçları üzerindeki ayni haklar *menşe ülke hukukuna* tabidir. Menşe ülke
deniz araçlarında ayni hakların tescil edildiği sicil yeri, bu sicil yeri yoksa
bağlama limanının olduğu yerdir.

Gemi, Türk gemi siciline kayıtlı ise Ticaret Kanununun gemiler üzerindeki ayni
haklara ilişkin hükümleri uygulanır. Sicile kayıtlı değilse Medeni Kanunun
taşınırlara ilişkin hükümleri uygulanır.

TIP: İnşası tamamlanmamış gemiye *yapı halindeki gemi* denir. Yapı halindeki gemi
yapı siciline kayıtlı ise bu yapı üzerindeki mülkiyet hakkının devri sicile
kayıtlı gemilerin mülkiyetinin devrine ilişkin hükümlere tabidir. Sicile
kayıtlı değilse devir Medeni Kanun hükümlerine göre yapılacaktır.

[NOTE]
====
Bağlama Kütüğüne kayıtlı gemiler üzerindeki mülkiyetin devri bakımından hangi
hükümler uygulanacaktır?

Bağlama Kütüğünün sicil olarak kabul edilip edilmeyeceği tartışmalıdır.
Öğretide ağırlıklı görüş bunun sicil olmadığı yönündedir. Zira mevzuatta
bağlama kütüğündeki kayıtların hukuki karine olmasından, kamu güveninin
korunacak olmasından bahsedilmemiştir. Yargıtay da bunun bir sicil olmadığını
savunmaktadır.

Dolayısıyla bağlama kütüğüne kayıtlı gemiler sicile kayıtlı olmayan gemiler
gibi Medeni Kanun hükümlerine tabi olacaktır.

Ancak Bağlama Kütüğü Uygulama Yönetmeliği bağlama kütüğüne kayıtlı bir geminin
mülkiyetinin devredilmesine ilişkin anlaşmanın liman başkanlığında veya mutat
bir durumda yapılmasını arayarak bir şekil şartı getirmiştir. Ağırlıklı görüş
bunun tasarruf işlemi açısından bir şekil şartı olduğudur.
====

=== MÜLKİYET

==== ASLEN İKTİSAP

Sahipsiz bir gemiyi sahiplenme hakkı sadece Devletindir. Sahipsiz gemi, sicil
kayıtlarından malikinin kim olduğu anlaşılamayan veya usulüne uygun olarak
mülkiyeti terk edilmiş olan gemidir. Devlet kendisini gemi siciline malik
olarak tescil ettirmek suretiyle gemi üzerindeki mülkiyeti iktisap eder.

==== DEVREN İKTİSAP

Sicile kayıtlı olmayan bir geminin mülkiyeti Medeni Kanun uyarınca zilyetliği
devri hükümleri (MK 763) ile devredilir.

Gemi veya payının devri hâlinde, taraflardan her biri, giderleri karşılamak
şartıyla, kendisine devre ilişkin resmî veya imzası noterce onaylı bir senet
verilmesini isteyebilir.

Gemi siciline kayıtlı olan bir geminin devri için, malik ile iktisap edenin,
mülkiyetin iktisap edene devri hususunda anlaşmaları ve geminin zilyetliğinin
geçirilmesi şarttır.

Mülkiyetin devrine ilişkin anlaşmanın yazılı şekilde yapılması ve imzaların
noterce onaylı olması gerekir. Bu anlaşma gemi sicil müdürlüğünde de
yapılabilir.

Ticaret Kanunu 11 inci maddenin üçüncü fıkrası hükmü saklıdır.

Taraflarca aksi kararlaştırılmış olmadıkça, iktisap eden, geminin mülkiyeti ile
birlikte, iktisap anında varolan ve devredene ait eklentinin mülkiyetini de
kazanır.

Devir sonucunda, devredene ait olmayan veya üçüncü kişilere ait haklarla
sınırlandırılmış bulunan eklenti de iktisap edenin zilyetliğine geçerse, Türk
Medenî Kanununun 763, 988, 989 ve 991 inci maddeleri uygulanır. İktisap edenin
iyiniyeti hususunda zilyetliği elde ettiği an esas alınır.

Gemi yolculukta bulunduğu sırada devredilirse, devredenle iktisap eden
arasındaki ilişkilerde bu yolculuğun kâr ve zararı, aksine sözleşme
bulunmadıkça iktisap edene aittir.

Sicile kayıtlı gemi payının mülkiyeti, malik ile iktisap edenin bu hususta
anlaşmaları ile devralana geçer. Anlaşmanın yazılı şekilde yapılması ve
imzaların noterce onaylanması şarttır. Bu anlaşma gemi sicil müdürlüğünde de
yapılabilir.

Donatma iştirakinde paydaş donatanların her biri, iştirak payını dilediği anda
diğer paydaşların onayı olmaksızın tamamen veya kısmen başkasına devredebilir.
Sicile kayıtlı gemi üzerindeki iştirak payının devri, gemi payının devri ve
sicile tescili ile olur.

Gemi payı veya iştirak payının devri sonucunda gemi Türk Bayrağı çekme hakkını
kaybedecekse, devir yalnız bütün paydaşların veya paydaş donatanların
onaylarıyla geçerli olur.

Gemi payı, gemi yolculukta bulunduğu sırada devredilirse, devrin kapsamı
Ticaret Kanunu 1002 nci maddenin üçüncü fıkrasına göre belirlenir.

==== ZAMANAŞIMI

===== OLAĞAN ZAMANAŞIMI

Sicile kayıtlı bir geminin maliki olmadığı hâlde, gemi siciline malik olarak
tescil edilmiş bulunan bir kişi, tescilin en az beş yıl sürmesi ve bu süre
içinde gemiyi davasız ve aralıksız bir şekilde asli zilyet sıfatıyla elinde
bulundurması şartıyla, geminin mülkiyetini iktisap eder. Bu süre, malik olmayan
kişinin sicile tescil edildiği tarihten itibaren işlemeye başlar. Sürenin
hesabı, kesilmesi ve durması, Türk Borçlar Kanununun alacak zamanaşımına
ilişkin hükümlerine tabidir. Gemi siciline kaydın doğru olmadığı yolunda bir
itirazın tescil edilmesi hâlinde itiraz kayıtlı olduğu sürece zamanaşımı
işlemez.

Zamanaşımı için öngörülen şartların gerçekleşmesiyle sicilde geminin maliki
olarak gözüken kişi onun mülkiyetini iktisap eder.

NOTE: Medeni Kanundaki düzenlemeden farklı olarak burada iyiniyet aranmaz.

===== OLAĞANÜSTÜ ZAMANAŞIMI

Sicile kaydı gerekirken kaydedilmemiş olan bir gemiyi en az on yıl süreyle
davasız ve aralıksız olarak asli zilyet sıfatıyla elinde bulunduran bir kişi,
geminin, sicile kendi malı olarak tescil edilmesini isteyebilir.

En az on yıl önce ölmüş veya gaipliğine karar verilmiş bir kişinin adına
kayıtlı bulunan ve hakkında on yıldan beri malikin onayına tabî bir husus
kaydedilmemiş olan bir gemiyi birinci fıkrada yazılı şartlarla elinde
bulunduran kişi de o geminin maliki olarak tescil edilmesini isteyebilir.
Zilyetlik süresinin hesabı, kesilmesi ve durması Türk Borçlar Kanununun alacak
zamanaşımına ilişkin hükümlerine tabidir.

Tescil ancak mahkeme kararıyla olur. Tescil davası, geminin kayıtlı olduğu veya
kaydedilmesi gereken sicil müdürlüğüne karşı açılır. Mahkeme, ilgilileri, en
fazla üç aylık bir süre belirleyerek itirazlarını bildirmeye tirajı ellibinin
üstünde olan ve yurt düzeyinde dağıtımı yapılan bir gazetede yapılacak ilanla
çağırır. İtiraz edilmez veya itiraz reddolunursa tescile karar verilir.

Tescile karar verilmeden önce, üçüncü bir kişi malik sıfatıyla tescil edilir
veya üçüncü kişinin mülkiyeti dolayısıyla sicile, gemi sicilinin doğru olmadığı
yolunda bir itiraz şerhi verilmiş olursa, tescil kararı üçüncü kişi hakkında
hüküm ifade etmez.

=== REHİN

Sicile kayıtlı olmayan gemilerin rehni Medeni Kanununun taşınır rehni
hükümlerine göre yapılacak ve zilyetliğin devri ile rehnedilecektir. Sicile
kayıtlı gemiler üzerinde yapılacak tek rehin türü ise ipotektir.

İpotek usulünün temel özelliği rehin konusu şeyin alacaklıya devredilmesine
gerek olmadan sicile tescil edilerek kurulmasıdır.

NOTE: Hem sicile kayıtlı hem de kayıtlı olmayan gemiler için gündeme
gelebilecek bir rehin hakkı *gemi alacaklısı* rehin hakkıdır. Gemi alacaklısı
hakkı, bütün gemilerde söz konusu olan ve kanuni bir rehindir. Kanun gereği
kendiliğinden doğduğu için ne tescile ne de zilyetliğin devrine ihtiyaç duyar.
Kural olarak hakkın doğumundan itibaren 1 yıl içerisinde takip yapılmalıdır.

=== GEMİ İPOTEĞİ

==== KURULMASI

Bir alacağı teminat altına almak için gemi üzerinde ipotek kurulabilir. Gemi
ipoteği alacaklıya, alacağını, geminin bedelinden alma yetkisini verir. Sicile
kayıtlı gemilerin sözleşmeye dayalı rehni sadece gemi ipoteği yolu ile
sağlanır. İleride doğabilecek veya şarta ya da kıymetli evraka bağlı bir alacak
için de ipotek kurulabilir.

IMPORTANT: Sicile kayıtlı bir geminin tamamı veya payı üzerinde kurulabilecek
tek akdi rehin türü ipotektir.

Alacaklıların gemi ipoteğinden doğan hakkı, sadece alacağa göre belirlenir.

Bir geminin payı ancak gemiye paylı mülkiyet esaslarına göre malik olan
paydaşlardan birinin payından ibaret olmak şartıyla gemi ipoteği ile
sınırlandırılabilir.

Bir geminin bütün payları bir malikin elinde bulunduğu sürece, ayrı ayrı paylar
üzerinde ayrı ayrı kişilere gemi ipoteği kurulamaz.

Gemi ipoteğinin kurulması için geminin maliki ile alacaklının gemi üzerinde
ipotek kurulması hususunda anlaşmaları ve ipoteğin gemi siciline tescil
edilmesi şarttır.

İpoteğin kurulmasına ilişkin sözleşmelerin yazılı şekilde yapılması ve
imzalarının noterce onaylanması gerekir. Bu anlaşma gemi sicil müdürlüğünde de
yapılabilir. Bu şekillerden birine uygun olarak yapılmadıkça ipoteğin
kurulmasına dair anlaşma geçerli olmaz.

Tescilden önce anlaşma Kanunun öngördüğü şekilde yapılmış veya malik tarafından
Gemi Sicili Nizamnamesi uyarınca alacaklıya kayda onay verdiği bildirilmiş ya
da sicil müdürlüğüne kayıt dilekçesi verilmiş olduğu takdirde, ilgililer
tescilden kaçınamazlar.

Malikin tasarruf ehliyetinin sonradan sınırlanması, sicile bildirilen kayda
onayını veya kayıt istemini geçersiz duruma getirmez.

Yabancı bir ülkede iktisap edilip, henüz Türk Gemi Sicili veya Türk
Uluslararası Gemi Siciline tescil edilmemiş olan gemilerde bayrak
şahadetnamesine şerh tescil hükmündedir. Geminin tescilinde bu gibi ipotekler
resen sicile geçirilir.

==== İPOTEĞİN DERECESİ

Gemi üzerindeki ipoteklerin dereceleri, Türk Medenî Kanununun taşınmaz rehni
hakkındaki hükümlerine göre belirlenir.

Bir ipotek hakkının derecesinin değiştirilmesi için ipotek hakkı sahibi ile
malik yazılı bir anlaşma yapmalı ve imzaları noter tarafından onaylanmalı ya da
anlaşma Gemi Sicil Müdürlüğünde yapılmalıdır.

==== İPOTEĞİN KAPSAMI

===== GEMİ, GEMİ PAYI, BÜTÜNLEYİCİ PARÇA, EKLENTİ, GEMİ YERİNE GEÇEN SATIŞ VEYA KAMULAŞTIRMA BEDELİ VE TAZMİNAT İSTEMLERİ

İpoteğin kapsamı hakkında Türk Medenî Kanununun 862 ve 863 üncü maddeleri
uygulanır.

Eklentiler normal bir işletmenin gereği olarak bu durumdan çıkarılır veya
alacaklı lehine el konulmadan önce devredilerek gemiden uzaklaştırılır ise,
ipotek artık bunları kapsamaz.

Bütünleyici parçalar, gemiden geçici bir amaç için olmamak şartıyla ayrılıp
uzaklaştırılırlarsa ipotek bunları kapsamaz; meğerki, uzaklaştırılmadan önce
alacaklı lehine gemiye el konulmuş olsun.

Kamulaştırılan geminin bedeli ve gemi malikinin geminin zıyaı veya hasarından
dolayı üçüncü şahıslara karşı sahip olduğu tazminat istemleri ipoteğin
kapsamındadır.

===== BİRLİKTE GEMİ İPOTEĞİNDE BİRDEN ÇOK GEMİ VEYA GEMİ PAYI

Bir alacak için birden çok gemi veya gemi payı ipotek edilmişse, bunlardan her
biri borcun tamamından sorumludur.

Alacaklı, her gemi veya pay ancak belirli bir kısımdan sorumlu olmak üzere
alacağını gemi veya paylar arasında paylaştırabilir. Paylaştırma, sicil
müdürlüğüne yapılacak beyan ve tescil ile gerçekleşir. Birlikte ipotek üzerinde
hak sahibi kişiler varsa onların da onayı gereklidir.

===== SİGORTA TAZMİNATI

Gemi ipoteğinin kapsamına giren hususlarla ilgili olarak malikin menfaatinin,
malik veya onun lehine bir başkası tarafından sigorta ettirilmiş olması
hâlinde, ipotek, sigorta tazminatını da kapsar.

İpotek, sigorta primlerini veya sigorta sözleşmesi gereğince sigortacıya
yapılması gereken başka ödemelerin yerine getirilmesi için alacaklı tarafından
harcanan paralarla bunların faizlerini de teminat altına alır.

Türk Medenî Kanununun rehnedilen alacak ve diğer haklara ilişkin hükümleri
burada da uygulanır; sigortacı, gemi siciline kayıtlı ipoteği bilmediğini ileri
süremez. Bununla beraber, sigortacı veya sigorta ettiren kişi, zararın meydana
geldiğini alacaklıya bildirmiş ve bildirimden itibaren iki haftalık bir süre
geçmişse, sigortacı, tazminatı sigortalıya ödemekle alacaklıya karşı da
sorumluluktan kurtulur. Bildirimin yapılması son derece zor ise bundan
kaçınılabilir. Bu takdirde süre, tazminatın muaccel olduğu tarihten itibaren
işlemeye başlar. Süre sona erinceye kadar alacaklı, sigortacıya karşı ödemeye
itiraz edebilir.

Sigortacı, geminin önceki durumuna getirilmesi veya gemi alacaklılarına
verilmesi amacıyla malike tazminat bedeline sayılmak üzere ödemede bulunmuş ve
bu amaçlara erişilmesi teminat altına alınmış ise, ödeme, ipotekli alacaklıya
karşı da geçerli olur.

Gemi önceki durumuna getirildiği veya eklenti olan yeni parçalar yerlerine
konulduğu takdirde, sigortacının ipotek alacaklılarına karşı olan sorumluluğu
sona erer. Malikin bir gemi alacaklısı hakkına temel oluşturan borçlarının
ödenmesi hâlinde, sigortacının malike yapacağı ödeme, ancak gemi alacaklısı
hakkının teminatını oluşturan unsurların rizikonun gerçekleşmesinden hemen
sonra taşıdıkları değer oranında sigortacıyı ipotekli alacaklıya karşı
sorumluluktan kurtarır.

==== İPOTEĞİN DEVRİ

İpotekle teminat altına alınmış olan alacağın devri ile gemi ipoteği de yeni
alacaklıya geçer.

Alacak ipotekten ve ipotek de alacaktan ayrı olarak devredilemez.

Alacağın devri için eski ve yeni alacaklının bu hususta yazılı şekilde
anlaşmaları ve devrin gemi siciline tescili şarttır.

Üst sınır ipoteğinde alacak, alacağın devrine ilişkin genel hükümlere göre de
devredilebilir. Bu takdirde gemi ipoteği alacak ile birlikte geçmez.

Emre veya hamile yazılı bir senede bağlanmış alacaklar, gemi ipoteği ile
teminat altına alınmışsa, alacağın devri bu alacakların bağlı oldukları
senetlerin devri hakkındaki hükümlere tabidir. Bu takdirde, gemi ipoteği de
alacak ile birlikte geçer.

İpotek ile teminat altına alınmış bir borcu ödemesi sebebiyle, malike veya onun
hukuki seleflerine rücu hakkına sahip olduğu oranda gemi ipoteği, gemi maliki
olmayan borçluya geçer.

==== İPOTEKLİ ALACAKLININ HAKLARI

NOTE: Sicile kayıtlı gemilerin cebri icra yoluyla satışında İcra İflas
Kanununun taşınmaz satışı hükümleri uygulanır.

Gemi veya tesisatının kötüleşmesi sonucu olarak ipoteğin sağladığı teminat
tehlikeye düşerse, alacaklı, tehlikeyi gidermesi için malike uygun bir süre
verebilir. Bu süre içinde tehlike giderilmezse, alacaklı derhâl ipoteği paraya
çevirmek hakkını elde eder. Alacak faizsiz olup henüz muacceliyet kazanmamışsa,
paranın alınması ile muacceliyet tarihleri arasındaki zamana ait kanuni faiz
indirilir.

Malikin gemiyi işletme tarzı sonucu olarak, ipoteğin sağladığı teminatı
tehlikeye düşürecek şekilde gemi veya tesisatının kötüleşmesinden veya ipotekli
alacaklının haklarının başkaca tehlikeye girmesinden kaygı duyulur ya da üçüncü
kişiler tarafından yapılacak bu gibi müdahaleye ve tahribata karşı malik
gerekli önlemleri almazsa, alacaklının istemi üzerine mahkeme;

.. Ticaret Kanunu 1353 üncü madde uyarınca geminin ihtiyaten haczine,
.. Gerekli görürse geminin, kaptandan başka bir yediemine bırakılmasına ve
.. Malikin ihtiyati haczin uygulanmasından başlayarak bir aylık süre içinde
gerekli önlemleri almasına, karar verir. Bu sürenin sonunda önlemlerin henüz
alınmadığı veya alınan önlemlerin yetersiz kaldığı anlaşılırsa mahkeme,
ipoteğin paraya çevrilmesi yoluyla ilamlı takip başlatmak üzere alacaklıya bir
aylık süre verir.

İpoteğin kapsamına giren eklentinin kötüleşmesi veya normal bir işletmenin
gereklerine aykırı olarak gemiden uzaklaştırılması hâli de geminin kötüleşmesi
hükmündedir.

==== İPOTEK TÜRLERİ

. *Üst sınır ipoteği*: Alacağın miktarı belirli değil veya değişken ise, gerçek
miktarı zamanında saptamak üzere, ipoteğin teminat altına alacağı alacak
miktarının üst sınırı belirlenerek gemi siciline tescil edilir; alacak faizli
ise, faizleri de üst sınır kapsamında sayılır.
. *Yabancı para ipoteği*: Yabancı para üzerinden gemi ipoteği kurulabilir. Bu
takdirde yabancı para veya Türk parası karşılıklarının hesabında hesap
günündeki Türkiye Cumhuriyet Merkez Bankasının döviz alış kuru esas alınır.
Rehin haklarının hangi yabancı para üzerinden kurulabileceği Hazine
Müsteşarlığınca belirlenir. Aynı derecede birden fazla para türü kullanılarak
gemi ipoteği kurulamaz.
. *Sabit kıymetli ipotek*: Vadesi geldiğinde Türk lirası ile ödenecek alacak
dövize veya altına sabitlenebilir. Vadesi geldiğinde döviz veya altının vade
tarihindeki Türk lirası cinsinden karşılığı ödenir.

==== YAPI İPOTEĞİ

Yapı hâlindeki gemiler üzerinde de ipotek kurulabilir.

Omurgasının konulduğu andan kızaktan indirilinceye kadar, görünebilecek bir
yerine ad ve numara konulmak suretiyle yapının açık ve sürekli bir şekilde
ayırt edilmesi gerçekleştirildiği andan itibaren yapı hâlindeki gemi üzerinde
ipotek kurulabilir.

Tamamlandığında onsekiz gros tonilatodan ufak olacak yapılar üzerinde ipotek
kurulamaz.

Yapı hâlindeki gemi üzerinde ipotek, yapı maliki ile alacaklının yapı üzerinde
ipotek kurulması hususunda anlaşmaları ve ipoteğin yapı hâlindeki gemilere özgü
sicile tescili ile kurulur. İpoteğin kurulmasına ilişkin anlaşmanın yazılı
şekilde yapılması ve imzalarının noterce onaylanması şarttır. Bu anlaşma gemi
sicil müdürlüğünde de yapılabilir.

Yapı hâlindeki gemi, yapımın her aşamasında ipoteğin kapsamındadır. Yapı
hâlindeki gemiler üzerindeki ipotek, Ticaret Kanunu 1020 nci maddede yazılı
şeylerle yapı malikinin mülkiyetine girmemiş olan kısımlar dışında, tersanede
bulunup yapımda kullanılacak olan ve bunun için işaretlenmiş bulunan kısımları
da kapsar.

Yapı hâlindeki gemiler üzerindeki ipotek, sigorta tazminatını ancak ipoteğin
kapsamına giren hususlar üzerindeki malikin menfaatinin malik veya onun lehine
bir başkası tarafından ayrıca sigorta ettirilmiş olması hâlinde kapsar.

Yapı üzerinde kurulan gemi ipoteği, yapımı tamamlandıktan sonra eski
derecesiyle gemi üzerinde kalır.

==== TERSANE SAHİBİNİN ALACAKLARI İÇİN KANUNİ İPOTEK

Tersane sahibi, geminin yapımı ve onarımından doğan alacakları için, o yapı
veya gemi üzerinde, bir ipoteğinin tescilini isteme hakkına sahiptir. Bu haktan
önceden feragat geçerli değildir.

IMPORTANT: Bu ipotek hakkı kendiliğinden doğmaz, kanun sadece tersane sahibini
talep hakkı vermiştir. İpotek için tescil kurucudur.

Bu ipoteğin kurulması hakkında Türk Medenî Kanununun 895 ilâ 897 nci maddeleri
uygulanır.

Gemi ipoteğinin kurulmasına yönelik istem hakkını teminat altına almak için,
gemi veya yapı siciline şerh verilebilir. Geminin yapımı veya onarımı henüz
tamamlanmamışsa, bedelin, tamamlanan işi karşılayan bir kısmı ve bedelin
kapsamında olmayan giderler için bir teminat ipoteğinin kurulması istenebilir.

=== İNTİFA HAKKI

Sicile kayıtlı gemiler üzerinde intifa hakkı kurulabilir.

İntifa hakkı, aksi kararlaştırılmadıkça, sahibine üzerinde kurulduğu gemiden
tam yararlanma yetkisini sağlar.

Akdî intifa hakkının kurulmasında Ticaret Kanununun 1015 inci madde hükmü
uygulanır.

Sicile kayıtlı gemi üzerindeki intifa hakkı Türk Medenî Kanununun taşınmazlar
üzerindeki intifa hakkı hükümlerine tabidir.

İntifa hakkı ile gemi ipotekleri arasındaki ilişkiler Türk Medenî Kanununun 869
uncu maddesi hükmüne tabidir. Aynı tarihle kaydedilmiş bulunan haklar aynı
derecededir. Gemi ipoteğinin derecelerinin değiştirilmesi ve ipoteğin malike
karşı alacaklıya sağladığı hakların zamanaşımına uğraması ile ilgili hükümler
burada da uygulanır.

== DONATAN

*Donatan*, gemisini menfaat sağlamak amacıyla suda kullanan gemi malikine
denir.

Kendisinin olmayan gemiyi menfaat sağlamak amacıyla suda kendi adına kullanan
kişiye ise *gemi işletme müteahhidi* denir. Gemi işletme müteahhidi, gemiyi
kullanmaktan kaynaklanan bütün haklara, borçlara, alacaklara sahiptir.

CAUTION: Bir gemiyi aynı anda bir kişi işletebilir. Geminin maliki donatan
sıfatını haiz ise orada gemi işletme müteahhidi yok demektir.

Kendisinin olmayan bir gemiyi menfaat sağlamak amacıyla suda kendi adına bizzat
veya kaptan aracılığıyla kullanan kişi, üçüncü kişilerle olan ilişkilerinde
donatan sayılır.

Malik, geminin işletilmesinden dolayı gemi alacaklısı sıfatıyla bir istemde
bulunan kişiyi, bu işletilme malike karşı haksız ve alacaklı da kötüniyet
sahibi olmadıkça, hakkını istemekten engelleyemez.

=== DONATANIN SORUMLULUĞU

Donatan, gemi adamlarının, zorunlu danışman kılavuzun veya isteğe bağlı
kılavuzun görevlerini yerine getirirken işledikleri kusur sonucunda üçüncü
kişilere verdiği zararlardan sorumludur.

“Gemi adamları”; kaptan, gemi zabitleri, tayfalar ve gemide çalıştırılan diğer
kişilerdir.

Kılavuz, iç sularda seyrederken gemiyi yönlendiren yerel denizcidir. Danışman
kılavuz, gemi kaptanına sadece danışmanlık hizmeti verir. Sevk ve idare
kılavuzu ise geminin idaresini devralır.

NOTE: Gemideki diğer gemi adamları da üçüncü kişidir. Üçüncü kişi gemiden
tamamen bağımsız olmak zorunda değildir.

Donatanın sorumluluğu kusursuz sorumluluktur. Öğretide donatanın sorumluluğunun
ek sorumluluk olduğu kabul edilmektedir. Gemi adamı veya kılavuzun kusurlu bir
eylemi ile bununla illiyet bağı içerisinde olan bir zarar meydana gelmesi
halinde gemi adamı veya kılavuza ek olarak donatan da sorumlu olacaktır. Ek
sorumluluk olmasının sonucu olarak gemi adamı veya kılavuz, kusurunun derecesi
ya da zarara uğrayan kişinin mütefarik kusuru yüzünden zarardan kısmen sorumlu
ise donatan da kısmen sourumlu olacaktır.

Ancak, donatan, yolculara ve yükle ilgili kişilere karşı, taşıyanın gemi
adamlarının kusurundan doğan sorumluluğuna ilişkin hükümlere göre sorumlu olur.

TIP: Taşıyan sıfatına sahip olabilmek için bir kişinin eşya taşıma taahhüdünde
bulunması yeterlidir.

Donatanın, Türkiye Cumhuriyetinin taraf olduğu sorumluluğun sınırlandırılmasına
ilişkin milletlerarası sözleşmelerden doğan sorumluluğunu sınırlandırma hakkı
saklıdır.

[NOTE]
====
Donatanın sorumluluğunu düzenleyen TTK 1062, gemi alacaklısı hakkının doğumuna
sebep olabilecek bir maddedir. Bu madde uyarınca donatanın sorumluluğu söz
konusu olduğunda eğer üçüncü kişinin bir bedensel zararı varsa gemi alacaklısı
hakkı doğmaktadır. Yine sözleşme dışı haksız fiilden kaynaklanan bir maddi
zarar söz konusu ise bu da tazminat alacaklısına gemi alacaklısı hakkı
vermektedir.
====

[TIP]
====
Adam çalıştıranın sorumluluğunu düzenleyen TBK 66 ile donatanın sorumluluğunu
düzenleyen TTK 1062 yan yana mı yer alır, yoksa birbirinin yerine mi geçer?

Doktrinde ağırlıklı olarak kabul edilen görüşe göre TTK 1062, TBK 66'nın yerine
getirilmiş özel bir hüküm değil, yanında yer alan bir düzenlemedir. Kişi
isterse TBK 66'ya isterse TTK 1062'ye dayanabilir.
====

=== SORUMLULUĞUN SINIRLANDIRILMASI

TTK, 1976 tarihli Londra Konvansiyonu'na doğrudan atıfta bulunarak sorumluluğun
sınırlandırıması hususunda hiçbir yabancılık unsuru bulunmayan olaylarda dahi
bu antlaşma hükümlerinin uygulanacağını düzenlemiştir.

TIP: Kanun koyucu ayrıca ileride Londra Konvansiyonu'nun yerine geçmek üzere
yeni bir antlaşma yapılırsa bu antlaşmanın kendiliğinden Türk Hukukunda da
geçerli olacağını düzenlemiştir.

Hakim re'sen sorumluluğu Konvansiyon'a göre sınırlayamaz. Sorumluluğuna gidilen
kişinin bunu ileri sürmesi gerekir.

Londra Konvansiyonu'nda sorumluluğun dayanağı ne olursa olsun bu sınırlama
sisteminin uygulanacağı hüküm altına alınmıştır.

Londra Konvansiyonu'na göre sorumluluğun sınırlandırılabilmesi için aşağıdaki
şartların gerçekleşmesi gerekir:

. Sorumluluğuna gidilen kişinin konvansiyonda sorumluluğu sınırlandırılabilecek
kişiler arasında sayılmış olması gerekir.

.. *Gemi maliki*

... _Malik_
... _Donatan_
... _İşleten_
... _Çarterer_
... _Yönetici_

.. *Kurtartma faaliyeti yürütenler*
.. *Yardımda bulunan kişiler*

... _Kaptan_
... _Gemi adamları_
... _Kurtaranın yardımcıları_

.. *Sorumluluk sigortacısı*

. İhtilaf konusu alacağın da sınırlandırılabilecek alacaklardan biri olması
gerekir.

.. *Geminin işletilmesi veya kurtarma faaliyeti ile doğrudan meydana gelebilecek
kişi veya eşya zararlarından doğan alacaklar*
.. *Sözleşme dışı hakların ihlalinden doğan diğer bütün zararlardan doğan
alacaklar*
.. *Eşya veya yolcu taşıma sözleşmesinin ifasında gecikmeden ileri gelen bütün
zararlardan doğan alacaklar*
.. *Yukarıdaki zararların azaltılması ya da doğmasının önlenmesi için üçüncü
kişilerin aldıkları tedbirlere dayanan alacaklar*

. İhtilaf konusu alacağın sınırlandırılamayacak alacaklardan biri olmaması
gerekir.

.. *Enkaz kaldırmadan doğan alacaklar*
+
TIP: 1976 Konvansiyonu bunu sorumluluğun sınırlandırılabileceği alacaklar
arasında saymış, ancak devletlerin bunu istisna edebileceğini düzenlemiştir.
TTK 1331 ile bu alacak bakımından sorumluluğun sınırlandırılamayacağı
düzenlenmiştir.
.. *Kurtarma alacağı*
.. *Müşterek avarya garame alacağı*
.. *Petrol Kirliliği Sözleşmesi anlamında bir petrol kirliliği zararından doğan
alacaklar*
.. *Nükleer zararlardan doğan alacaklar*
..  *Gemi maliki ile yardımda bulunanların çalıştırdığı kişilerin hizmet
sözleşmesinden doğan alacakları*

Donatan veya sorumluluğunu sınırlandırabilecek diğer kişiler, şahsi fiil ve
ihmalinden ileri gelen zarara kasten veya pervasızca bir hareketle ve
muhtemelen böyle bir zarar meydana geleceği bilinci ile sebebiyet verirse
sorumluluğunu sınırlama hakkını kaybedecektir.

CAUTION: Kaptanın zarara kasten veya pervasızca bir hareketle ve muhtemelen
zararın meydana geleceği bilinci ile sebebiyet vermesi halinde donatanın
sorumluluğunu sınırlandırma hakkı etkilenmez.

Sorumluluğu sınırlama hakkının kaybedilmesinde aşağıdaki kişilerin kusuru
dikkate alınacaktır:

.. Gerçek kişilerde, her bir gerçek kişinin kusuru.
.. Tüzel kişilerde, Türk Medenî Kanununun 50 nci maddesi uyarınca eylem ve
işleriyle tüzel kişiyi borç altına sokan organların kusuru ve organı oluşturan
kişilerin kusurları.
.. Adi şirketlerde şirket ortaklarının kusuru.
.. Donatma iştirakinde, paydaş donatanların ve gemi müdürünün kusuru.
.. Yukarıda sayılan kişileri, genel veya özel bir yetkiye dayanarak temsil eden
kişilerin kusuru. Örn. gemi yöneticisi.

Sorumluluğun sınırlanması talebi bir fon tesisi yoluyla yapılabileceği gibi fon
tesis edilmeden sadece sorumluluğun konvansiyon uyarınca sınırlandırılması
talebi ile de ileri sürülebilir.

1976 ve 1992 tarihli sözleşmeler uyarınca fon kurulması konusunda görevli
mahkeme, deniz ticareti işlerine bakmakla görevli asliye ticaret mahkemesi, bu
mahkemenin bulunmadığı yerlerde bu işle görevlendirilmiş asliye ticaret
mahkemesi, o da yoksa, fonun miktarına bakılmaksızın, bu işle görevlendirilmiş
asliye hukuk mahkemesidir.

1976 ve 1992 tarihli sözleşmeler uyarınca fon kurulması konusunda, bir Türk
Gemi Siciline kayıtlı olan gemilerde, o gemi sicilinin gözetimi altında
tutulduğu mahkeme, sicile kayıtlı olmayan Türk gemilerinde malikin yerleşim
yeri mahkemesi, yabancı gemilerde ise, deniz ticareti işlerine bakmakla görevli
İstanbul Asliye Ticaret Mahkemesi yetkilidir.

Sorumluluğun sınırlanabilmesi için bir fon kurulmuşsa sorumlu kişi aleyhine
aynı olaydan doğan tüm istemler için geçerlidir. Eğer birden fazla kişinin
sorumluluğuna gidiliyorsa fon hepsi için geçerli olacaktır.

Bir alacağın, 1976 veya 1992 tarihli sözleşmeler uyarınca kurulan fonlara
gireceği, fonun kurulduğu mahkeme tarafından kabul edildiği anda, o alacağa
ilişkin bütün ayni ve şahsî teminatlar sona erer. Bu ayni ve şahsî
teminatların, o alacağa sağladığı öncelikler, fon paylaştırmasında dikkate
alınmaz.

1976 veya 1992 tarihli sözleşmeler uyarınca kurulan fonlar, yalnız, haklarında
sınırlı sorumluluk ileri sürülebilecek olan alacakların ödenmesinde
kullanılabilir. Fon kurulması yoluyla sorumluluğunu sınırlayan kişinin diğer
alacaklıları, hiçbir şekilde bu fonlara başvuramaz. Fonların
paylaştırılmasından sonra bir bakiye kalırsa, fonu kuran kişinin diğer
alacaklıları, bu bakiyeyi takip edebilir.

== DENİZ KİRLİLİĞİ

=== PETROL KİRLİLİĞİ SÖZLEŞMESİ

TTK 1336 uyarınca Petrol Kirliliği Sözleşmesi, olayda yabancılık unsuru
bulunsun bulunmasın Türkiye'de meydana gelen bir olayda uygulama şartları
gerçekleşmişse doğrudan uygulanır.

Petrol Kirliliği Sözleşmesi'nin kapsamına petrol ve türevleri olan dayanaklı
hidrokarbon mineralleri taşımak için dizayn edilmiş, inşa edilmiş veya tadil
edilmiş gemiler, *tankerler*, girer.

Petrol Kirliliği Sözleşmesi'nin konusu bir tankerde yük olarak taşınan veya
yakıt tankında yakıt olarak taşınan petrol ve türevlerinin sebep olduğu
kirlilik zararı ve bu zararın önlenmesi için alınan tedbirlerin masraflarıdır.

TIP: Tankerden kaynaklanan petrol kirliliğinde her zaman Petrol Kirliliği
Sözleşmesi uygulanır.

Kirlenme zararı söz konusu ise, zararın taraf devletin kara sularında veya münhasır
ekonomik bölgelerinde meydana gelmiş olması gerekir. Ancak kirliliğin önlenmesi
için alınan tedbir açık denizde bile olsa masrafı istenebilir.

Sözleşme, sorumlu kişiyi yalnızca donatan olarak belirtmiştir. Geminin
mülkiyetinin sonradan el değiştirmesi sorumlu kişiyi değiştirmez. Zararın
meydana geldiği sırada donatan kimse sorumlu odur.

Kural yalnızca donatanın sorumlu olmasıdır ama zarara kasten veya pervasızca
bir hareketle ve muhtemelen böyle bir zararın meydana geleceği bilinci ile
hareket ederek neden olmuş başka kişiler varsa bunların da sorumluluğuna
gidilebilir.

Sözleşme uyarınca sorumluluk, kusursuz sorumluluktur. Donatanın sorumluluktan
kurtulabilmesi için nedensellik bağını kesen bir sebebin varlığı şarttır.
Sözleşmede sayılan sebepler:

. Savaş, mücbir sebep vb. haller
. Üçüncü kişinin kastı
. Seyir yardımcıları bakımından sorumlu idarenin buna ilişkin kusuru

TTK 1336 uyarınca Petrol Kirliliği Sözleşmesi'nin uygulanma şartları
gerçekleşmişse yalnızca ve yalnızca bu sözleşme uygulanır.

Sözleşmeden doğan sorumluluk 1976 Konvansiyonu gibi sınırlandırılmıştır. Ancak
zarara kasten veya pervasızca bir hareketle ve muhtemelen böyle bir zarar
meydana gelebileceği bilinci ile hareket ederek sebep olunmuşsa sorumluluğu
sınırlandırma hakkından yararlanılamaz.

Zarara uğrayan kişinin mütefarik kusuru varsa davaya bakan mahkeme tazminatı
indirebilir veya tamamen kaldırabilir.

Zarara iki tanker müşterek kusurlarıyla sebebiyet vermişse ve tankerlerin
zarara hangi oranda sebebiyet verdiği tespit edilemiyorsa müteselsilen sorumlu
olurlar.

Sözleşmeden doğan talepler zararın meydana geldiği tarihten itibaren *üç yıl*
ve her halükarda zarara neden olan olaydan itibaren *altı yıl* içerisinde ileri
sürülmelidir. Süreler hak düşürücüdür.

=== YAKIT KİRLİLİĞİ SÖZLEŞMESİ

Yakıt Kirliliği Sözleşmesi, olayda yabancılık unsuru bulunsun bulunmasın
Türkiye'de meydana gelen bir olayda uygulama şartları gerçekleşmişse doğrudan
uygulanır.

Sözleşmenin kapsamı, her türlü geminin, deniz aracının çalıştırılması veya
işletilmesi için kullanılan petrol ve türevlerinin neden olduğu kirlilik
zararlarıdır.

Sözleşme uyarınca sorumlu kişi donatan, kiracı, yönetici veya işleten olabilir.
Bunun dışında hükümleri Petrol Kirliliği Sözleşmesi ile aynıdır.

=== DENİZ KİRLİLİĞİ KANUNU

Kanunun kapsamına deniz kirliliği yaratan her türlü madde girer.

Kanun, tonaj bakımından ayrım yapılmaksızın her türlü gemiden kaynaklanan
zararlara uygulanır. Ayrıca kıyı tesisleri de kanun kapsamındadır.

Zararın tazmini ve koruyucu önlemlerin karşılanması konusunda yükümlülük
atfedilebilecek kişiler kanun kapsamındaki gemiler ile kıyı tesislerinin
sahipleri, işletenleri, kaptanları, idare edenleri, kiracıları, zilyetleri ve
garantörleridir.

Bu Kanun kapsamına giren gemi ve kıyı tesislerinin sorumlu tarafları, uygulama
alanlarında gemi ve kıyı tesislerinden kaynaklanan olay sonucu ortaya çıkan
kirlenmenin veya kirlenme tehlikesinin neden olduğu;

* temizleme masraflarını,
* koruyucu önlemlere ilişkin masrafları,
* canlı kaynaklar ve deniz yaşamına verilen zararları,
* bozulan çevrenin yeniden oluşturulması, toplanan atıkların taşınması ve
bertarafı için yapılacak masrafları,
* geçim için kullanılan doğal ve canlı kaynaklarda meydana gelen zararları,
* özel mallardaki zararları,
* şahısların yaralanması ve ölümünden kaynaklanan zararları,
* gelir kayıplarını,
* gelir ve kazanç kapasitelerine verilen zararları
* diğer kamu zararlarını

tazmin etmekle müteselsilen sorumludur.

İki veya daha fazla geminin karışmasıyla meydana gelen bir olayda ortaya çıkan
zarardan tüm gemilerin sorumlu tarafları müştereken ve müteselsilen sorumludur.

Gemi başına sorumlu taraf yükümlülüğünün toplamı ve sorumlu tarafa yüklenecek
azamî tazminat miktarı konusunda Türkiye'nin taraf olduğu uluslararası sözleşme
hükümleri saklıdır.

Bu Kanun kapsamındaki olaylar nedeniyle tazminat taleplerinde zamanaşımı
süresi, diğer kanunlarda daha uzun bir süre öngörülmedikçe, zararın öğrenildiği
ve sorumlu tarafın tespit edildiği tarihten itibaren beş yıl, her hâlde olayın
meydana geldiği tarihten veya olay, olaylar zincirinden meydana geliyorsa son
olayın meydana geldiği tarihten itibaren on yıldır. Zamanaşımı süresine ilişkin
olarak Türkiye'nin taraf olduğu uluslararası sözleşme hükümleri saklıdır.

NOTE: Petrolden doğan zararlarda ancak bir kıyı tesisinden, örneğin bir petrol
boru hattından petrol sızmışsa Deniz Kirliliği Kanunu uygulanabilir.

=== ÇEVRE KANUNU

Çevre Kanunu deniz kirliliğine özgü bir kanun değildir. Bütün ortamlarda
meydana gelebilecek kirlilik Çevre Kanununun kapsamındadır.

Çevre Kanununda kirlenmeden dolayı bir idari para cezası öngörülmüştür. Bir
olayda Petrol Kirliliği Sözleşmesi, Yakıt Kirliliği Sözleşmesi ya da Deniz
Kirliliği Kanunu uyarınca sorumluluk doğarsa Çevre Kanunu uyarınca idari para
cezası da kesilebilir.

Kanun uyarınca kirliliğe kim sebep olmuşsa sorumlu da odur. Kusursuz sorumluluk
söz konusudur. Ayrıca sorumluluğun sınırlandırılması da söz konusu değildir.

Çevreye verilen zararların tazminine ilişkin talepler zarar görenin zararı ve
tazminat yükümlüsünü öğrendiği tarihten itibaren beş yıl sonra zamanaşımına
uğrar.

== DONATMA İŞTİRAKİ

Birden çok kişinin paylı mülkiyet şeklinde malik oldukları bir gemiyi, menfaat
sağlamak amacıyla aralarında yapmış oldukları sözleşme gereğince, hepsi adına
ve hesabına suda kullanmaları hâlinde *donatma iştiraki* vardır.

Tek başına bir geminin maliki veya işletme hakkına sahip olan ticaret
şirketleri veya diğer tüzel kişiler hakkında donatma iştirakine ilişkin
hükümler uygulanmaz.

=== PAYDAŞ DONATAN

Donatma iştirakinde paylı mülkiyete sahip her bir donatanın adı **paydaş
donatan**dır. Bunların paylarına ise *iştirak payı* denir. İştirak payı
çekirdeğinde gemi mülkiyetindeki pay bulunan ve bunun yanında geminin
işletilmesi sebebiyle meydana çıkan zarara ve yarara katılma da bulunan bir
paydır.

Her bir paydaş donatan iştirakin borçlarından dolayı üçüncü kişilere karşı
şahsen sorumludur.

TTK 1062'de düzenlenmiş olan donatanın sorumluluğu, her bir paydaş donatan için
de geçerlidir.

=== TESCİLİ

Donatma iştirakinin yapılmasını izleyen onbeş gün içinde iştirak, ticaret ve
gemi sicillerine tescil edilir.

Ticaret ve gemi sicillerine;

.. Paydaş donatanların adları, yerleşim yerleri ve vatandaşlıkları,
.. İştirakin unvanı ve merkezi,
.. İştirakin konusu,
.. Her paydaş donatanın gemi payının miktarı,
.. İştiraki temsile yetkili kişilerin ad ve soyadları ile bunların yalnız
başlarına mı yoksa birlikte mi imza atmaya yetkili oldukları,

kaydedilir.

=== PAYDAŞ DONATANLAR ARASINDAKİ HUKUKİ İLİŞKİLER

Paydaş donatanlar arasındaki hukuki ilişkiler ile donatma iştirakinin temsili,
paydaşlar arasındaki sözleşme hükümlerine tabidir. Sözleşmede hüküm bulunmayan
durumlarda, aşağıdaki hükümler uygulanır.

==== OLAĞAN İŞLER

İştirakin işleri paydaş donatanların oy çoğunluğu ile verecekleri kararlara
göre yürütülür. Her paydaş donatanın sahip olduğu oy hakkı, onun gemideki payı
veya paylarının miktarına göre belirlenir. Kararın lehinde oy verenlerin, tüm
payların yarısından fazlasına sahip olmaları hâlinde oy çoğunluğu gerçekleşmiş
sayılır.

==== OLAĞANÜSTÜ İŞLER

Donatma iştiraki sözleşmesinin değiştirilmesine ilişkin veya bu sözleşmeye
aykırı ya da iştirakin amacına yabancı kararlar oybirliği ile alınır.

==== GEMİ MÜDÜRÜ

Donatma iştirakinin işlerinin görülmesi için oy çoğunluğu ile bir gemi müdürü
atanabilir. Paydaş donatanlardan olmayan bir gemi müdürünün atanması için
oybirliği şarttır.

Gemi müdürü, sözleşmenin feshinden doğan hakları saklı kalmak üzere, her zaman
oy çoğunluğuyla görevden alınabilir.

Gemi müdürünün atanması ve görevden alınması ticaret ve gemi sicillerine tescil
olunur.

Gemi müdürü, bu sıfatla iştirakin olağan işlerinin gerektirdiği bütün işlemleri
ve hukuki tasarrufları üçüncü kişilerle yapmaya ve bu işler dolayısıyla ödenen
paraları toplamaya yetkilidir. Gemi müdürünün temsil yetkisine, özellikle
geminin donatılmasına ve bakımına ilişkin işlem ve tasarruflar ile navlun
sözleşmelerinin yapılması ve geminin, navlunun, donatma giderlerinin ve
müşterek avaryadan doğan alacakların sigorta ettirilmesi dâhildir.

Kaptan, sadece gemi müdürünün emir ve talimatlarına uymakla yükümlü olup,
paydaş donatanlardan herhangi birinin vereceği talimata uymak zorunda değildir.

Gemi müdürü yapmaya yetkili olduğu işlerden doğan uyuşmazlıklar dolayısıyla
açılan davalarda ve girişilen takiplerde iştiraki temsile de yetkilidir.

Gemi müdürü, kendisine özel bir yetki verilmedikçe, iştirak veya paydaş
donatanlardan birinin veya birkaçının adına kambiyo taahhüdünde bulunamayacağı
veya ödünç para alamayacağı gibi gemi veya gemi payları üzerinde bunları satmak
veya rehnetmek suretiyle tasarrufta da bulunamaz.

Gemi müdürünün yönetme hakkı yukarıdaki hükümlere tabidir. Ancak, olağanüstü
tamirler veya kaptanın atanması ve görevden alınması için önceden donatma
iştirakinin kararının alınması gerekir.

Gemi müdürü, iştirak tarafından yetkilerinin kapsamına getirilen sınırlamalara
uymakla yükümlüdür. Bunun dışında, alınan kararlara göre hareket etmek ve bu
kararları uygulamak zorundadır.

Gemi müdürünün bu sıfatla kanuni yetkileri çerçevesinde yaptığı hukuki
işlemlerden doğan bütün hak ve borçlar iştirake aittir.

Gemi müdürünün kanuni temsil yetkisinin sınırlandırılması, donatma iştiraki
tarafından ancak işlemin yapıldığı anda bunu bilen üçüncü kişilere karşı ileri
sürülebilir.

Gemi müdürü, donatma iştirakinin işlerini yaparken tedbirli bir donatanın
özenini göstermek zorundadır.

Gemi müdürü, paydaş donatanlardan her birine, istemi üzerine, donatma
iştirakine ait işler hakkında bilgi vermek ve iştirake ait bütün defterlerle
belgeleri göstermek zorundadır.

Donatma iştirakinde gemi müdürünün hesap vermesine her zaman karar verilebilir.
Gemi müdürünün verdiği hesabın çoğunluk tarafından onaylanması ve gördüğü
işlerin uygun bulunması, bu karara karşı oy verenlerin itiraz haklarını
düşürmez.

==== KAZANCA VE ZARARA KATILMA

İştirakin kazancı ve zararı, paydaş donatanlara gemideki paylarına göre
dağıtılır. Kazanç ve zarar hesabı ile kazancın dağıtılması takvim yılı sonunda
yapılır.

==== GİDERLERE KATILMA

Paydaş donatanlardan her biri iştirakin giderlerine, özellikle geminin
donatılması ve tamiri giderlerine, gemideki payları oranında katılmak
zorundadır.

Paydaş donatanlardan biri kendisine düşen gider payını ödemez ve bu para diğer
paydaş donatanlar tarafından onun hesabına avans olarak verilirse, borçlu
paydaşın temerrüt faizi ödeme yükümlülüğü, avansların verildiği tarihten
itibaren başlar. Avansın ödenmesinin, borçlu paydaşa ait gemi payı veya payları
üzerinde, avans veren paydaş donatanlar bakımından doğurduğu sigortalanabilir
menfaatin sigorta ettirilmesi hâlinde, sigorta giderleri de borçlu paydaş
donatana ait olur.

==== PAYDAŞ DONATANLARIN ŞAHSINDE DEĞİŞİKLİK

Paydaş donatanlardan birinin şahsında meydana gelecek bir değişiklik, donatma
iştirakinin devamına engel olmaz.

Paydaş donatanlardan hiçbiri iştirakten çıkarılamaz.

=== PAYDAŞ DONATANLARIN SORUMLULUĞU

==== İŞTİRAKİN BORÇLARINDAN DOLAYI ÜÇÜNCÜ KİŞİLERE KARŞI SORUMLULUĞU

Deniz alacaklarından sorumluluğun sınırlandırılmasıyla ilgili hükümler saklı
kalmak üzere, paydaş donatanlar, iştirakin borçlarından dolayı üçüncü kişilere
karşı iştirak payları oranında şahsen sorumludurlar.

==== İŞTİRAK PAYININ DEVREDİLMİŞ OLMASI HÂLİNDE

İştirak payını devreden paydaş donatan, iktisap edenle birlikte devri diğer
donatanlara veya gemi müdürüne bildirmedikçe, onlarla olan ilişkilerinde paydaş
donatan sayılır ve bu bildirimden önce doğan bütün borçlardan dolayı onlara
karşı paydaş donatan sıfatıyla sorumlu olmakta devam eder. İştirak payını
iktisap eden kişi de iktisap anından itibaren diğer paydaş donatanlarla olan
ilişkilerinde paydaş donatan sıfatı ile sorumlu olur.

Donatma iştiraki sözleşmesi hükümleri ile iştirak tarafından verilen kararlar
ve girişilmiş işler, devredeni ne ölçüde bağlıyorsa, iktisap edeni de o ölçüde
bağlar. İktisap edenin tekeffül bakımından devredene karşı sahip olduğu haklar
saklı kalmak şartıyla, diğer paydaş donatanlar, devredenin paydaş donatan
sıfatıyla devrettiği payına ilişkin olmak üzere ona düşen borçları, iktisap
edene karşı da takas edebilirler.

Bu hükümler bir iştirak payının cebrî icra yolu ile iktisabı hâlinde de
uygulanır.

=== SONA ERMESİ

==== FESİH KARARI

Donatma iştiraki, çoğunluk kararı ile fesih olunabilir. Geminin devri
hakkındaki karar da iştirakin feshi kararı hükmündedir.

==== ÇIKMAK İSTEYEN ORTAĞIN FESİH İSTEMİ

Paydaş donatanlardan her biri, haklı bir sebebe dayanarak iştirakten çıkmasına
izin verilmesini isteyebilir. İştirakten çıkmasına izin verilmeyen paydaş
donatan, haklı sebeplere dayanarak mahkemeden iştirakin feshini isteyebilir.

Dürüstlük kuralına göre paydaş donatanın iştirakte kalmasını ondan
beklenilemeyecek derecede zorlaştıran olaylar haklı sebep sayılır. Sadece
çıkmak isteyen paydaş donatanın şahsını ilgilendiren ve diğer paydaş
donatanlardan hiçbiri için sözleşmeye aykırılık oluşturmayan olaylar, haklı
sebep olarak kabul edilemez.

Mahkeme haklı sebebi ispatlanmış görürse, davacının iştirak payına
bilirkişilerce biçilecek olan değerin diğer paydaş donatanlar tarafından ödenip
devralınması için onlara uygun bir süre verir. Her paydaş donatanın, davacı
paydaş donatanın payını, kendi payı oranında devralmak hakkı vardır. Mahkemece
verilen süre içinde davacı paydaş donatanın payı devralınmadığı takdirde,
mahkeme iştirakin feshine karar verir.

Bu hükümlerin paydaş donatanlar aleyhine değiştirilmesi sonucunu doğuran
sözleşme şartları geçersizdir.

==== İŞTİRAKİN İFLASI

Donatma iştiraki hakkında iflasın açılmasıyla da iştirak sona erer.

==== SONA ERMEYİ GEREKTİRMEYEN HALLER

Paydaş donatanlardan birinin ölümü veya iflası, donatma iştirakinin sona
ermesine sebep olmaz.

=== YETKİLİ MAHKEME

Paydaş donatanlar aleyhine bu sıfatları dolayısıyla diğer paydaş donatanlar
veya üçüncü kişiler tarafından herhangi bir alacaktan dolayı geminin bağlama
limanının bulunduğu yer mahkemesinde de dava açılabilir.

Davanın paydaş donatanlardan biri veya birkaçı aleyhine açılmış olması hâlinde
de aynı hüküm uygulanır.

== KAPTAN

Kaptan aslında bir gemi adamıdır. Ancak kanun, kaptanı gemi adamlarının
başında, geminin sevk ve idaresini sağlayan kişi olarak göstermiştir.

NOTE: Kaptan da bir gemi adamı olduğu için deniz iş hukuku bakımından diğer
gemi adamları gibi Deniz İş Kanunu'na tabidir.

Kaptan, bütün işlerinde, özellikle ifası kendisine düşen sözleşmelerin yerine
getirilmesinde tedbirli bir kaptan gibi hareket etmek zorundadır.

Kaptan, gemi zayi olsa bile, gerektiği sürece donatanın menfaatlerini korumakla
yükümlüdür.

=== SORUMLULUĞU

Kaptan, kusuruyla yol açtığı zararlardan, özellikle bu Kısım ile diğer
Kısımlarda belirtilen görevlerini yapmamasından doğacak zararlardan dolayı,
yolcular da dâhil, gemi ve eşyayla ilgili herkese karşı sorumludur.

Donatanın emrine uyması kaptanı sorumluluktan kurtarmaz.

Durumu bilerek kaptana emir vermiş olan donatan da sorumludur.

Kaptanın, Türkiye Cumhuriyetinin taraf olduğu sorumluluğun sınırlandırılmasına
ilişkin milletlerarası sözleşmelerden doğan sorumluluğunu sınırlandırma hakkı
saklıdır.

=== GÖREVLERİ

====  GEMİNİN DENİZE VE YOLA ELVERİŞLİ OLUP OLMADIĞINA DİKKAT ETME

Kaptan, yola çıkmadan önce geminin denize ve yola elverişli olmasına ve gemiye,
gemi adamlarına ve yüke ait belgelerin gemide bulunmasına dikkat etmek
zorundadır.

==== GEMİNİN YÜKLEMEYE VE BOŞALTMAYA ELVERİŞLİ OLUP OLMADIĞINA DİKKAT ETME

Kaptan, yükleme ve boşaltma araçlarının kullanılma amaçlarına uygun durumda
olmasına ve istifin, özel istifçiler tarafından yapılsa bile, denizcilikte
geçerli olan kurallara uygun bir şekilde gerçekleştirilmesine dikkat etmek
zorundadır.

Kaptan, denizcilikte geçerli olan kurallar uyarınca; geminin aşırı derecede
yüklenmemesine, gerekli safranın gemide bulunmasına ve geminin ambarlarının
taşınacak olan eşyayı kabule ve korumaya elverişli bir şekilde donatılmış
olmasına dikkat etmek zorundadır.

==== YABANCI MEVZUATA UYMA

Kaptan, yabancı bir ülkede bulunduğu sırada o ülke devletinin mevzuatına,
özellikle kolluk, vergi ve gümrük kurallarına uymamasından doğan zararları
tazmin ile yükümlüdür.

Kaptan, gemisine harp kaçağı niteliğine sahip olduğunu bildiği veya bilmesi
gereken eşyayı yüklemesi sebebiyle ortaya çıkan zararı da tazmin ile
yükümlüdür.

==== YOLA ÇIKMA

Kaptan, gemi kalkmaya hazır olunca, elverişli ilk fırsatta yola çıkmak
zorundadır.

Kaptan, hastalık veya diğer bir sebepten dolayı gemiyi yönetemeyecek durumda
olsa bile, geminin kalkmasını veya yolculuğun devamını, uygun görülemeyecek bir
şekilde geciktiremez. Böyle bir durumda kaptan, durumun gereklerine göre
donatandan talimat alması mümkünse, vakit geçirmeden ona engelleri bildirip
talimat gelinceye kadar gereken önlemleri almak; aksi takdirde yerine başka bir
kişiyi kaptan olarak bırakmak zorundadır. Kaptan, seçiminde kusurlu olmadıkça,
kendisine vekâlet eden kaptanın fiillerinden dolayı sorumlu tutulamaz.

==== GEMİDE HAZIR BULUNMA

Yükleme başladıktan boşaltma bitinceye kadar zorunlu bir sebep bulunmadıkça
kaptan, ikinci kaptanla birlikte aynı zamanda gemiden ayrılamaz. Kaptan
ayrılmak zorunda kalırsa, ayrılmadan önce zabitler veya tayfalar arasından
uygun birisini yerine vekil bırakmakla yükümlüdür.

Bu hüküm, geminin güvenli olmayan bir limanda veya demirleme yerinde bulunduğu
zamanda, yükleme başlamadan önce ve boşaltma bittikten sonra da uygulanır.

Kaptan, yakın bir tehlikenin var olması hâlinde veya gemi denizde bulunduğu
sırada, gemiden ayrılmasını haklı gösteren bir zorunluluk olmadıkça, gemide
kalmakla yükümlüdür.

=== GEMİ JURNALİ

Her gemide gemi jurnali denilen bir defter tutulur. Bu deftere her yolculukta
eşya veya safranın yüklenmeye başlanması anından itibaren geçecek belli başlı
olaylar yazılır.

Gemi jurnali, kaptanın gözetimi altında, ikinci kaptan tarafından ve onun
mazereti hâlinde bizzat kaptan veya kaptanın gözetimi altında olmak şartıyla
ehil bir gemi adamı tarafından tutulur.

Bir liman içinde yolculuk yapan küçük gemilerde jurnal tutmak yükümlülüğü
yoktur.

NOTE: Gemi jurnali, geminin özellikle üçüncü kişilere zarar vermesi halinde
kimin kusurlu olduğu, donatanın sorumluluğunun ne zaman başlayıp bittiği
hususlarında delil niteliği taşır.

=== DENİZ RAPORU

Kaptan, yolculuk sırasında gemiyi veya taşınan eşyayı ilgilendiren veya başkaca
bir maddi zarar doğurması muhtemel olan bir kaza meydana geldiğinde, gemi zayi
olsa bile, bir deniz raporu düzenlenmesini istemeye yetkili ve kendisinden
istendiği takdirde buna zorunludur. Deniz raporunun düzenlenmesini donatan veya
ilgisi olduğunu ispat eden herkes isteyebilir. Deniz raporunun, vakit
kaybetmeksizin aşağıda belirtilen yerlerden birinde düzenlenmesi istenebilir:

.. Varma limanında ve eğer varma limanı birden çok ise, kazadan sonra varılan
ilk limanda.
.. Gemi tamir edildiği veya eşya boşaltıldığı takdirde barınma limanında.
.. Yolculuk geminin batması yüzünden veya diğer bir sebepten varma limanına
ulaşmadan biter ise, kaptanın veya ona vekâlet eden kişinin uğradığı ilk
elverişli yerde.

Kaptan ölür veya deniz raporu düzenlettiremeyecek bir hâlde bulunursa, gemide
kaptandan sonra en yüksek rütbeli zabit tespit yaptırmak zorundadır.

Deniz raporu, Türkiye Cumhuriyeti sınırları içinde mahkemelerce düzenlenir.
Diğer yerlerde, Türk Bayraklı gemiler için yerel mevzuat hükümleri saklı kalmak
üzere Türk konsoloslukları, deniz raporu düzenler.

Yolculuğun önemli olayları, özellikle kazalar ve zararın önüne geçilmesi veya
azaltılması için alınan önlemler tam ve açık olarak mahkemece veya
konsoloslukça tespit edilir.

=== DONATANIN TEMSİLİ

Donatan, kaptanın onun adına hareket ettiğini bildirerek veya bildirmeyerek,
gemiyi sevk ve idare eden kişi sıfatıyla kanuni yetkileri dâhilinde yaptığı
hukuki işlemlerden dolayı üçüncü kişilere karşı hak iktisap eder ve borç altına
girer.

Kaptan, ifasını ayrıca üstlenmedikçe veya kanuni yetkilerini aşmadıkça, yapmış
olduğu işlemlerden dolayı şahsen borç altına girmez. Kaptanın 1088 ve 1089 uncu
maddelerden kaynaklanan sorumluluğu saklıdır.

==== GEMİ BAĞLAMA LİMANINDA BULUNDUĞU SIRADA

Gemi henüz bağlama limanında bulunduğu sırada kaptanın yapmış olduğu hukuki
işlemler donatanı bağlamaz; meğerki, kaptan kendisine ayrıca verilmiş özel bir
yetkiye dayanarak hareket etmiş veya borç, diğer bir özel borçlandırıcı
sebepten doğmuş olsun.

Kaptan bağlama limanında da gemi adamı tutmaya yetkilidir.

==== GEMİ BAĞLAMA LİMANI DIŞINDA BULUNDUĞU SIRADA

Gemi bağlama limanı dışında bulunduğu sırada kaptan, bu sıfatla, geminin
donatılmasına, yakıt ve kumanyasına, gemi adamlarına, geminin denize, yola ve
yüke elverişli bir hâlde tutulmasına ve genel olarak yolculuğun güvenli bir
şekilde sürdürülmesine ilişkin her türlü işlem ve tasarrufları üçüncü kişilerle
donatan adına yapmaya yetkilidir.

Taşıma sözleşmeleri yapmak ve görevlerine giren hususlarda dava açmak da
kaptanın yetkisi kapsamındadır.

Yabancı bayraklı gemilerde, geminin malikine veya kiracısına açılacak her türlü
dava veya takip, onlar hakkında geçerli olmak üzere kaptana da yöneltilebilir.

==== KREDİ İŞLEMLERİ

Kaptan, ancak gemiyi korumak veya yolculuğu yapmak için zorunluluk bulunması
hâlinde ve bu ihtiyaçların karşılanabilmesi için gerekli olan miktarda ödünç
para veya veresiye mal almaya ve benzeri kredi işlemlerini yapmaya yetkilidir.

Yukarıda kaptanın yapmaya yetkili olduğu belirtilen işlemlerin geçerliği, onun
seçtiği işlemin amaca uygun veya bu işlemle sağlanan para veya diğer şeylerin
fiilen geminin korunması veya yolculuk yapmak için kullanılmış olup olmamasına
bağlı değildir. Üçüncü kişi, kaptanın yetkisiz olduğunu veya sağlanan krediyi
başka bir amaçla kullanma niyetinin bulunduğunu biliyorsa yahut bunları
bilmemesi ağır bir ihmal oluşturuyorsa, kaptanın yaptığı işlem donatanı
bağlamaz.

Kaptanın kambiyo taahhütlerinden dolayı donatanın şahsen sorumlu tutulması, ona
donatan tarafından açık bir temsil yetkisi verilmiş bulunmasına bağlıdır.

==== TEMSİL YETKİSİNİN SINIRLANDIRILMASI

Kaptanın kanundan doğan temsil yetkisini sınırlandırmış olan donatan, bu
sınırlandırmalara kaptanın uymadığını, sadece bunları bilen kişilere karşı
ileri sürebilir.

==== HESAP VERME VE TALİMAT İSTEME

Kaptan; donatana geminin durumu, yolculuk sırasında meydana gelen olaylar,
yaptığı sözleşmeler ve açılan davalar hakkında düzenli şekilde bilgi vermekle
yükümlü olduğu gibi, şartlar elverdikçe bütün önemli işlerde, özellikle 1105
inci maddede yazılı durumlarda, yolculuğun değiştirilmesi veya kesilmesi
gerektiğinde ve olağanüstü tamirler ile alımlarda donatandan talimat istemek
zorundadır.

Kaptan, elinde donatana ait yeterli miktarda para bulunsa bile, olağanüstü
tamirleri ve alımları, ancak zorunluluk hâlinde yapabilir.

Kaptan, geminin bağlama limanına dönüşünde veya her isteyişinde donatana hesap
vermek zorundadır.

Kaptan; taşıtandan, yükletenden ve gönderilenden ödül veya tazminat gibi her ne
ad altında olursa olsun navlun dışında aldığı bütün paraları da donatanın
hesabına alacak yazmak zorundadır.

=== YÜKLE İLGİLİ OLANLARIN MENFAATLERİNİ KORUMA YÜKÜMLÜLÜĞÜ

Kaptan, yolculuk esnasında yükle ilgili olanların menfaati gereği eşyanın en
iyi şekilde korunması için mümkün olan özeni göstermekle yükümlüdür.

Kaptan, bir zararın önüne geçilmesi veya azaltılması için özel önlemlerin
alınması gerektiğinde, yükle ilgililerin menfaatlerini göz önünde bulundurmaya
ve mümkünse talimatlarını almaya ve durumun gereğine göre bu talimatları yerine
getirmeye zorunludur. Talimat alınması mümkün olmadığı takdirde, kaptan kendi
takdirine göre hareket eder; ancak yükle ilgili olanları, bu gibi durumlardan
ve alınan önlemlerden gecikmeksizin bilgilendirmek için üzerine düşeni yapar.

Kaptan, bu gibi durumlarda eşyayı tamamen veya kısmen boşaltmaya ve eşyanın
bozulması yüzünden veya diğer sebeplerden ileri gelebilecek büyük bir zararın
başka surette önüne geçilemeyeceği anlaşılıyorsa, eşyayı satmaya; korunması
yahut daha ileri götürülmesi için gereken parayı sağlamak için rehnetmeye
yetkilidir.

Kaptan, yükle ilgili olanların zamanında bizzat yapabilecek durumda olmamaları
koşuluyla, eşyanın zıyaından ve hasara uğramasından doğan istem haklarını,
mahkemelerde veya mahkeme dışında kendi adına kullanmaya yetkilidir.

== GEMİ KİRA SÖZLEŞMESİ

Gemi kirası sözleşmeleri esas olarak BARECOM standart gemi kirası sözleşmesi
şeklinde düzenlenir. Burada düzenlenmeyen hallerde veya istisnaen bu tip
sözleşme çerçevesinde akdedilmeyen sözleşmelerde TTK hükümleri uygulanır.

NOTE: TTK'de hüküm bulunmayan hallerde TBK'deki adi kira hükümleri uygulama
alanı bulur.

_Gemi kira sözleşmesi, kiraya verenin belirli bir süre için geminin
kullanılmasını, kira bedeli karşılığında, kiracıya bırakmayı üstlendiği bir
sözleşmedir._

Kira sözleşmesinin konusu sadece gemi ise çıplak gemi kirası (bareboat charter)
söz konusudur. Gemi yönetimini de içeren sözleşmelere ise _charter by demise_
denir.

_Kiraya verenin, gemi ile birlikte gemi adamlarını da kiracının emrine vermeyi
üstlenmesi, sözleşmenin niteliğini değiştirmez._ Gemi adamlarının kiracının
emrine verilmesinden kasıt, gemi adamları ile malik arasındaki hizmet
sözleşmelerinin kiracıya devri ya da bu sözleşmelere kiracının katılmasıdır.
Buna uygulamada *donatılmış kira sözleşmesi* denir.

_Gemi kira sözleşmesinin taraflarından her biri, giderini vermek koşuluyla,
sözleşme şartlarını içeren ve gemi kira çarter partisi olarak adlandırılan bir
gemi kira senedi düzenlenmesini ve kendisine verilmesini isteyebilir._

NOTE: Kiracı, gemi işletme müteahhidi sıfatını kazanacağından üçüncü kişilerle
olan ilişkilerinde donatan sayılır. Malikle olan ilişkisi ise kira sözleşmesine
ilişkin TTK hükümlerine tabidir.

Aksi kararlaştırılmış olmadıkça kiracının gemiyi başkasına kiralama hakkı
yoktur.

_Sözleşmede aksi kararlaştırılmadıkça, taraflar, gemi kira sözleşmelerinin Türk
Gemi Siciline veya Ulaştırma, Denizcilik ve Haberleşme Bakanlığı tarafından
tutulan özel sicile şerhini isteyebilirler. Bu şerh sonraki maliklere, kiracının
gemi kira sözleşmesindeki koşullar çerçevesinde, gemiyi kullanmasına izin vermek
zorunluluğu yükler._

TIP: TUGS'a tescilli geminin kiralanması halinde şerhin TUGS'a verilmesi
mümkündür.

CAUTION: Bakanlık tarafından tutulan özel sicile şerh imkanı kanunda
düzenlenmiştir. Ancak mülkiyet el değiştirdiği takdirde yabancı maliklere ileri
sürülmesi mümkün değildir.

=== KİRAYA VEREN

==== KİRAYA VERENİN BORÇLARI

Kiraya verenin temel borcu, belli bir süre geminin kullanımını kiracıya
bırakmaktır. Kiraya veren gemiyi, denize ve sözleşmede öngörülen amaca uygun
kullanmaya elverişli bir şekilde sözleşmede öngörülen yer ve tarihte kiracıya
teslim edecektir. Söz konusu teslim zilyetliğin devri ile olur.

NOTE: Zaman çarteri sözleşmesinde zilyetliğin devri yoktur.

Zilyetlik kiracıya devredildiği için kiracı, *gemi işletme müteahhidi* sıfatını
kazanır.

Sözleşmeden zilyetliğin devri için yer öngörülmemişse TBK'daki genel hükümlere
göre zilyetlik gemi nerede bulunuyorsa orada devredilir.

Zilyetlik devredilmeden kira borcu muaccel olmaz.

Teslim edilen gemi ayıplı ise iki ihtimal söz konusudur:

. *Önemli ve kısa sürede giderilemeyecek bir ayıp söz konusu ise* kiracı gemiyi
kabul etmek zorunda değildir. Gemiyi teslim almaktan kaçınarak borçlu temerrüdü
hükümlerine dayanabilir. Ayıp hükümlerinde de dayanabilir.
. *Önemli olmayan ve tamiri kısa sürecek bir ayıp* ya da *gizli ayıp* söz konusu
ise ve bu ayıp *geminin 24 saatten fazla kullanılamamasına sebep olursa* bu 24
saati aşan süre için kira ücreti işlemez.

Kiraya veren ile kiracı, gemi adamlarının da kiracının emrine bırakılması
hususunda anlaşmışlarsa kiraya verenin geminin zilyetliğini devretme borcu
yanında gemi adamlarının hizmet sözleşmelerini devretme borcu da bulunmaktadır.
Bu durumda, gemi adamlarının hizmet sözleşmelerinin doğan alacakları için kiraya
veren de kiracı ile birlikte müteselsilen sorumludur.

NOTE: Müteselsil sorumluluk için bir üst süre öngörülmemiştir. Dolayısıyla kira
sözleşmesi boyunca sorumluluk devam eder.

IMPORTANT: Kanunda hizmet sözleşmesinden doğan alacaklar için asıl borçlunun
kiracı olduğu düzenlenmiştir. Buna göre, kiraya veren gemi adamlarına bir ödeme
yaparsa kiracıya rücu edebilir.

==== KİRAYA VERENİN HAKLARI

Kiraya verenin temel hakkı, ücret alma hakkıdır. Kira ücretini temin etmek
üzere, kiraya verenin, kıymetli evrak üzerinde hapis hakkı, kiracının navlun ve
diğer alacakları üzerinde alacaklı def'ine sahip olduğu öngörülmüştür.

=== KİRACI

Kiracının temel borcu, kira bedelini ödemektir. Kira bedeli aksi
kararlaştırılmadıkça aylık ve peşin olarak ödenir.

Kiracı, gemiyi sözleşmede belirlenen tahsis amacına uygun şekilde kullanmak
zorundadır.

Kiracı, sefer bölgelerine ilişkin sınırlandırmalara riayet etmek zorundadır. Bu
sınırlandırma, sözleşmede öngörülmemiş olsa dahi; örneğin geminin sigorta
sözleşmesinde böyle bir sınırlama varsa, geminin sınıflama kuruluşu belgesinde
böyle bir sınırlama varsa, bu sınırlandırmalara kiracı riayet etmek zorundadır.

Kiracı, sözleşme bitiminde gemiyi, teslim aldığı haliyle geri verir. Kiracı,
gemide, normal bir kullanım sonucu meydana gelen eksiklik, değişiklik veya
aşınmadan sorumlu değildir.

Sözleşmenin bitiminde gemiyi iadede geciktiği takdirde kiracı, geciktiği sürenin
ilk onbeş günü için kira bedeli üzerinden ve sonraki günler için kira bedelinin
iki katı üzerinden hesaplanacak bir tazminatı ödemekle yükümlüdür. Kiraya veren
daha yüksek bir zarara uğradığını ispat ederse tazminat buna göre hesaplanır.

Gemi kira sözleşmesinden doğan alacaklar, alacağın muaccel olmasından itibaren 1
yıllık zamanaşımı süresine tabidir.

== ZAMAN ÇARTERİ SÖZLEŞMESİ

Zaman çarteri sözleşmesinde, tahsis eden, donatılmış bir geminin ticari
kullanımını belirli bir süre boyunca tahsis olunana bırakır. Tahsis olunan zaman
çarteri, tahsis eden ise donatandır. Teknik yönetim tahsis edende iken, ticari
yönetim tahsis olunandadır.

Zaman çarterinin unsurları:

. Ücret kararlaştırılmış olmalıdır.
. Belirli bir süre öngörülmüş olmalıdır.
. Donatılmış gemi
. Ticari kullanımı bırakma

Kaptan, tahsis olunanın geminin ticari yönetimine ilişkin olarak zaman çarteri
sözleşmesi hükümleri çerçevesinde kendisine verdiği bütün talimatlara uymak
zorundadır.

Tahsis eden, geminin teknik yönetimini üstlenir. Bu amaçla tahsis eden,
belirlenen gemiyi:

. Kararlaştırılan tarihte ve yerde hazır bulundurmak
. Sözleşme süresince gemiyi denize ve yola elverişli ve sözleşmede belirtilen
amaca uygun halde bulundurmak

il yükümlüdür.

IMPORTANT: Zaman çarteri sözleşmesinde zilyetlik devredilmez. Bu sebeple, tahsis
olunan, gemiyi kendi adına ve hesabına işletme hakkını kazanmaz ve dolayısıyla
gemi işletme müteahhidi değildir.

== NAVLUN SÖZLEŞMESİ

Navlun sözleşmesi, bir eşyanın gemiyle bir yerden bir yere taşınmasının
üstlenildiği sözleşmedir.

=== UNSURLARI

. *Eşya*: Taşınabilir her türlü maddi şey navlun sözleşmesine konu olabilir.
. *Taşımanın üstlenilmesi*: Bir taahhütte bulunulması yeterlidir.
. *Eşyanın deniz yoluyla taşınması*
. *Eşyanın, taşıyanın zilyetliğine bırakılması*
. *Navlun*: Deniz eşya taşınması karşılığında verilen ücrettir. Ücretsiz yapılan
taşıma, navlun sözleşmesi olarak nitelendirilemez.

=== TARAFLARI

==== TAŞIYAN

Bir kişi, bir başka kişiye karşı ücret karşılığında deniz yoluyla bir limandan
başka bir limana eşya taşımayı taahhüt ettiği anda, kanun gereği *taşıyan*
sıfatını kazanır. Bu taşımayı bizzat yerine getirip getirmemesi, taşıyan
sıfatının kazanılması bakımından bir farklılık yaratmaz.

TIP: Taşıyan, donatan veya gemi işletme müteahhidi değilse taşımayı
gerçekleştirmek için bir başkasıyla navlun sözleşmesi yapacaktır. Bu durumda
taşıma, *fiili taşıyan* tarafından gerçekleştirilir.

==== TAŞITAN

Navlunu ödeyecek olan kişi, **taşıtan**dır. Taşıtanın, yükün maliki olması şart
değildir.

=== İLGİLİLER

==== YÜKLETEN

*Yükleten*, eşyayı gemiye kadar getirip taşıyana teslim eden kişidir.

[TIP]
====
Genellikle, navlun sözleşmesinin arka planında bir deniz aşırı satış sözleşmesi
bulunur. Bu satış sözleşmesinin alıcıya ifa edilebilmesi için bir navlun
sözleşmesi akdedilir.

Örneğin *FOB (Free On Board)* "Eşya gemi bordasını geçtiği anda, nevi ve hasar
alıcıya intikal eder" kuralı çerçevesinde şekillenmiş bir satış tipidir. Ayrıca
malı taşıtmak için bir taşıyan bulmak ve navlunu ödemek yükümlülüğü alıcı
üzerindedir.
====

==== GÖNDERİLEN

*Gönderilen*, malın gönderildiği ve varma limanında malı teslim alma hakkına
sahip kişidir.

Malı teslim alma hakkı konşimentoya dayanabileceği gibi navlun sözleşmesine de
dayanabilir. Eğer navlun sözleşmesine dayanıyorsa ve gönderilen taşıtandan başka
bir kişi ise navlun sözleşmesi bir üçüncü kişi yararına sözleşme olacaktır.

CAUTION: Navlun sözleşmesinin tarafları taşıyan ve taşıtandır. Taraflar anlaşsa
bile navlunun gönderilen tarafından ödeneceğini kararlaştıramazlar, zira üçüncü
kişi aleyhine borç yüklenemez.

=== TÜRLERİ

==== YOLCULUK ÇARTERİ SÖZLEŞMESİ

Yolculuk çarteri sözleşmesinde, taşıyan, taşıma işini belli bir geminin tamamını
veya bir kısmını tahsis ederek gerçekleştirecektir. Tahsis, bu sözleşmenin
ayrıcı unsurudur.

==== KIRKAMBAR SÖZLEŞMESİ

Kırkambar sözleşmesinde tahsis unsuru yoktur. Burada sadece ayırt edilmiş bir
eşyanın navlun karşılığında bir yerden bir yere taşınması söz konusudur.

=== İFASI

==== TAŞIMANIN SÖZLEŞMEDE KARARLAŞTIRILAN GEMİ İLE YAPILMASI

Taşıyan sözleşme ile kararlaştırılan gemiden başka bir gemiye malları yüklerse
bundan doğacak zararlardan sorumlu olur. Ancak taşıyan, mallar kararlaştırılmış
gemiyi yüklenmiş olsaydı da bu zararın meydana geleceğini ispatlarsa
sorumluluktan kurtulabilir.

==== GEMİNİN YOLCULUĞA HAZIRLANMASI

Taşıyan, gemiyi, denize, yola ve yüke hazır olarak *yükleme limanında*
bulundurmak zorundadır.

.. _Denize elverişlilik_, geminin, gövdesi, genel donanımı, makinesi ve kazanı
itibariyle yolculuğun yapılacağı sudan ileri gelen (anormal tehlikeler hariç)
tehlikelere karşı koyabilecek durumda olmasıdır.
.. _Yola elverişlilik_, denize elverişli geminin, teşkilatı, yükleme durumu,
yakıtı, kumanyası, gemi adamlarının yeterliliği ve sayısı bakımından, (tamamıyla
anormal tehlikeler hariç) yapacağı yolculuğun tehlikelerine karşı koyabilmek
için gerekli niteliklere sahip bulunmasıdır.
.. _Yüke elverişlilik_, geminin, soğutma tesisatı da dahil olmak üzere, eşya
taşımada kullanılan kısımları eşyanın kabulüne, taşınmasına ve muhafazasına
elverişli olmasıdır.

==== EŞYANIN YÜKLENMESİ

Sözleşme, yükleme limanı düzenlemeleri ve bunlar yoksa yerel teamül ile aksi
öngörülmüş olmadıkça, eşyanın gemiye kadar taşıma gideri taşıtana, yükleme
gideri ise taşıyana aittir.

TIP: Eğer sözleşmede _FIO (Free in and out)_ unsuru varsa yükleme ve boşaltma
taşıyanın faaliyet sahasından, taşıtanın ve gönderilenin faaliyet sahasına
aktarılmış olur. _FIOS_ varsa sadece yükleme değil, istiflenmesi de taşıtana ait
olur. _FIOST_ varsa sabitleme de taşıtana ait olur.
 
Yükleme aşamasında sadece yükün kararlaştırılan zaman dilimi içinde gemiye
teslim edilmesi yeterli değildir. Ayrıca yükle ilgili belgelerin de taşıyana
teslim edilmesi gerekir.
 
NOTE: Yük nevi ve cinsi ile belirlenmişse, taşıtan, *aynı varma limanı için*
başka bir yük belirleme hakkına sahiptir. Taşıyan, durumu ağırlaşmadığı sürece
bunu kabul etmek zorundadır.

===== TAŞITAN VE YÜKLETENİN SORUMLULUĞU

Taşıtan ve yükleten, eşya hakkında taşıyana tam ve doğru beyanda bulunmakla
yükümlüdür. Bunlardan her biri, beyanlarının doğru olmamasından doğan zarardan
taşıyana karşı sorumludur. *Bu yüzden zarar gören diğer kişilere karşı ise ancak
kusurları varsa sorumlu olurlar.*

Taşıtan ve yükleten, *harp kaçağı veya ihracı, ithali veya transit olarak
geçirilmesi menedilmiş olan eşyayı yükler yahut yükleme sırasında mevzuata,
özellikle kolluk, vergi ve gümrük kurallarına aykırı hareket ederlerse, taşıyana
karşı sorumludur; bu yüzden zarar gören diğer kişilere karşı ise ancak kusurları
varsa sorumlu olurlar*. Kaptanın onayıyla hareket etmiş olmaları, taşıtan ve
yükleteni diğer kişilere karşı sorumluluktan kurtarmaz. Bunlar eşyanın el
konulmuş olduğunu ileri sürerek navlunu ödemekten kaçınamazlar. Eşya, gemiyi
veya içindeki diğer eşyayı tehlikeye sokarsa, kaptan, bunu karaya çıkarmaya veya
zorunluluk hâllerinde denize atmaya yetkilidir.

Kaptanın bilgisi olmaksızın gizlice gemiye eşya yükleyen kişi de bu yüzden
doğacak zararı tazmin etmekle yükümlüdür. Kaptan bu gibi eşyayı tekrar karaya
çıkarmaya ve gemiyi veya diğer eşyayı tehlikeye düşürürse gerektiğinde denize
atmaya yetkilidir. Kaptan eşyayı gemide tutarsa, yükleme yerinde ve yükleme
sırasında bu gibi yolculuk ve eşya için alınan en yüksek navlunun ödenmesi
gerekir.

Denizde can ve mal koruma hakkındaki mevzuata göre tehlikeli sayılan eşya
kaptanın bunlardan veya bunların tehlikeli cins veya niteliklerinden bilgisi
olmaksızın gemiye getirilirse, taşıtan veya yükleten, kendilerine bir kusur
isnat edilmese dahi bundan ileri gelen zararlardan sorumludur. Bu hâlde kaptan
eşyayı her zaman ve herhangi bir yerde gemiden çıkarmaya, imha etmeye veya başka
suretle zararsız hâle getirmeye yetkilidir. Kaptan, eşyanın tehlikeli cins veya
niteliğini bildiği hâlde, yüklemeye onay vermişse, eşya gemiyi veya diğer eşyayı
tehlikeye soktuğu takdirde aynı şekilde hareket etmeye yetkilidir. Bu hâlde de
taşıyan veya kaptan, zararı tazmin etmekle yükümlü değildir.

===== YÜKLEMEDE BEKLEME SÜRELERİ

Taşıyanın yüklemenin tamamlanması için kanunen beklemek zorunda olduğu süre
**starya süresi**dir. Kural olarak bu süre için taşıyan bir ücret talep edemez.
Ancak bunun aksi kararlaştırılabilir.

Starya süresi, taraflar ne zaman başlayacağını kararlaştırmamışsa, *hazırlık
ihbarı* ile başlar. Hazırlık ihbarı, geminin yükleme limanına gelip yerine
demirlediğinde taşıtana hazır olduğunu bildirmesidir. İşte starya süresi,
hazırlık ihbarının ulaşmasını takip eden gün işlemeye başlar.

Starya süresi, navlun sözleşmesinde açıkça belirlenmemişse, işçiler 24 saat
yükleme yapacakmış gibi düşünülerek hesaplanır.

Taraflar, yüklemenin starya süresinde bitmemesi ihtimaline karşı yedek bir süre
de belirleyebilir. Bu süreye *sürastarya süresi* denir. Sürastarya süresi,
taşıyanın, *sözleşmede kararlaştırılmışsa beklemek zorunda olduğu süredir*.
Taşıyan, sürastarya süresi kapsamında beklenen gün kadar *sürastarya ücreti*
alır. Sürastarya süresi, starya süresinin bitimini takip eden gün başlar.
Taraflar ne kadar süreceğini belirlememişse kanunen 10 gün olduğu kabul edilir.

Starya süresinin hesaplanmasında tatil, bayram vs. dikkate alınmaz.

Yükleme, taşıtanın faaliyet alanında ortaya çıkan bir engel yüzünden gecikmişse
süre durmaz. Taşıyanın faaliyet alanında ortaya çıkan bir engel yüzünden
gecikmişse ise durur. Her iki tarafın ortak alanında ortaya çıkan bir engel söz
konusuysa süre durur ancak taşıyana sürastarya ücreti ödenir.

Engel ortaya çıkmış ancak buna rağmen yükleme yapılmışsa süre durmaz.

Sürastarya süresi hiçbir şekilde durmaz. Bunun tek istisnası taşıyanın kusuru
sebebiyle yüklemeye engel olmasıdır.

NOTE: Yüklemenin, sözleşmede kararlaştırılan yükleme süresinden önce bitirilmesi
halinde, taşıyanın, kullanılmayan süre için taşıtana bir para ödemesi
öngörülebilir. Buna *hızlandırma primi* denir.

Yükleme süresi ve kararlaştırılmışsa sürastarya süresi bittiği halde *yükleme
henüz başlamamışsa* taşıyan;

.. Sözleşmeyi feshedilmiş sayabilir. Bunu yazılı olarak bildirip *fesih
tazminatı* talep edebilir.
.. Yüklemenin yapılması için beklemeye devam edebilir. Bu durumda navlunu alır,
sürastarya ücretini alır ve sürastarya süresini aşan bekleme sebebiyle meydana
gelen zararı varsa bunun tazminini talep edebilir.

Yükleme süresi ve kararlaştırılmış ise sürastarya süresi bittikten sonra,
taşıyan, yüklemenin tamamlanması için daha fazla beklemek zorunda değildir.
Taşıyan, taşıtanın talimatına dayanarak yükleme ve sürastarya süresinden sonra
beklemeye devam ederse, bu süre için yaptığı giderlerle bu yüzden uğradığı
zarara karşılık tazminat isteyebilir.

Yükleme süresi ve kararlaştırılmış ise sürastarya süresi bittikten sonra,
taşıyan, taşınması için kararlaştırılan eşyanın tamamı yüklenmiş olmasa bile,
*taşıtanın istemi üzerine* yola çıkmak zorundadır. Bu durumda taşıyan;

. Sözleşmede kararlaştırılmış navlunun tamamını,
+
NOTE: Kısmen yüklenmeyen eşyanın yerine başka bir sözleşme uyarınca eşya
taşınmışsa, bu eşya için alınacak navlun bundan düşülür.
. Doğmuş sürastarya ücretini,
. Eksik yükleme sebebiyle yapmak zorunda kaldığı giderleri ve uğradığı zararı,
. Alacakları, eksik yükleme sebebiyle kısmen veya tamamen teminatsız kalmışsa,
kendisine ek teminat gösterilmesini

isteyebilir.

Taşıyan, taşıtandan kendisine talimat verilmesini *yazılı olarak* isteyebilir.
Taşıtan buna rağmen sessiz kalırsa, taşıyan sözleşmeyi feshedilmiş sayıp fesih
tazminatı talep edebilir.

.Kırkambar sözleşmesine bekleme süresi
****
Kırkambar sözleşmesinde kanuni bekleme süresi yoktur. Taşıtan, taşıyanın çağrısı
üzerine, gecikmeden eşyayı yükletmek zorundadır. Taşıtan gecikirse taşıyan,
eşyanın teslimini beklemekle yükümlü değildir.

Yolculuk, eşya teslim alınmadan başlamış olsa bile, taşıtan tam navlunu ödemekle
yükümlüdür. Ancak taşıyanın teslim edilmiş olmayan eşya yerine yüklediği eşyanın
navlunu, tam navlundan indirilir.

Taşıyanın, geciken taşıtandan navlun isteyebilmesi için bunu yola çıkmadan önce
taşıtana yazılı olarak bildirmesi gerekir.
****

===== GÜVERTEDE TAŞIMA

Güvertede daha fazla zarara uğrama ihtimali olduğu için kural olarak taşıyan
eşyayı güvertede taşıyamaz. Taşımışsa bundan ileri gelen zararlardan sorumlu
olur.

Güvertede taşıma aşağıdaki hallerde yapılabilir:

. *Yükletenle* anlaşma yapılması
+
IMPORTANT: Navlun sözleşmesinde açıkça eşyanın ambarda taşınacağı düzenlenmişse,
taşıyan ile yükletenin malın güvertede taşınmasına dair yaptığı anlaşma,
taşıyanın taşıtana karşı sorumluluğunu ortadan kaldırmaz.
. Eşyanın güvertede taşınmasına yönelik bir *ticari teamül* bulunması
. Güvertede taşımanın *mevzuat gereği* zorunlu olması

Taşıyan, eşyanın güvertede taşınabileceğine dair yükletenle anlaşmışsa bunu
konşimentoya geçirmek zorundadır. Geçirmezse bu anlaşmayı ayrıca ispat etmek
zorundadır.

IMPORTANT: Taşıyan ile yükletenin anlaşması konişmentoya geçirilmemiş ve
konişmento ciro + teslim yoluyla üçüncü kişiye devredilmişse, taşıyan anlaşmayı
yazılı delille ispatlasa dahi eşyanın güvertede taşınmasından dolayı meydana
gelen üçüncü kişinin zararından sorumludur.

==== EŞYANIN BOŞALTILMASI

Eşyanın boşaltılması süreler vs. bakımından eşyanın yüklenmesi ile aynı şekilde
düzenlenmiştir.

Eşyanın boşaltılması bakımından özellik arz eden husus, navlun sözleşmesinin
ifası yükün boşaltma limanında gönderilene teslimi ile tamamlanacağından, yükün
teslim edilememesi halidir. Bu durumda taşıyan, TBK'daki alacaklı temerrüdü
hükümlerine dayanabilir ve malı umumi bir ambara tevdi edebilir ya da yükün
çabuk bozulacak olması sebebiyle açık artırma yoluyla satışını yapabilir. Bunun
için öncelikle gönderilene ihbar yapılmalıdır.

Gönderilene ihbar yapılamıyorsa, taşıtana yapılacak ihbar ile de alacaklı
temerrüdünün sonuçları uygulanabilir.

Tevdi işlemleri sırasında sürastarya süresi geçti ise sürastarya ücreti talep
edilebilir. Bu sürenin geçmesi sebebiyle uğranılan zarar varsa bunların tazmini
de talep edilebilir.

=== KONİŞMENTO

*Konişmento*, bir taşıma sözleşmesinin yapıldığını ispatlayan, eşyanın taşıyan
tarafından teslim alındığını veya gemiye yüklendiğini gösteren ve taşıyanın
eşyayı, ancak onun ibrazı karşılığında teslimle yükümlü olduğu senettir.

Eşya taşınmak üzere taşıyana teslim edilmiş ancak henüz gemiye yüklenmemişse ve
o aşamada bir konişmento düzenlenmişse buna *tesellüm konişmentosu* denir.
Tesellüm konişmentosu taşıyanın eşyayı taşımak üzere teslim aldığını gösterir.

Eşya gemiye yüklendikten sonra düzenlenen konişmentoya ise *yükleme
konişmentosu* denir.

NOTE: Tesellüm konişmentosuna geminin adı ve yükleme tarihi yazılırsa yükleme
konişmentosuna dönüşür.

Tesellüm konişmentosu *ifa olarak kabul edilmez*. Alıcı ancak yükleme
konişmentosunu ifa olarak kabul edecektir.

Konişmento *yükletenin talebi üzerine* taşıyan tarafından düzenlenir.

Konişmento, nama, hamile veya emre yazılı olarak düzenlenebilir.

CAUTION: Konişmentoda cironun teminat işlevi yoktur. Eşya zarar gördüğünde yük
ilgilisinin tek muhatabı taşıyandır.

Konişmentoda uyulması gereken şekil şartları konişmentonun düzenlendiği yer
hukukuna tabidir.

Konişmentonun içeriği bakımından olmazsa olmaz unsur yüke ilişkin bir kayıt
bulunmasıdır. Eşyanın cinsi, işareti ve miktarı açıkça belirtilmelidir.

Cins, işaret ve miktar bakımından taşıyan, yükletenin beyanını aynen
konişmentoya geçirecektir. Ancak bu kayıtlar karine işlevi gördüğünden, taşıyan
gerekçeli bir çekince koyabilir. Bu durumda kaydın karine işlevi olmaz.

NOTE: Yükleten, taşıyanın çekince koymaması karşılığında uğrayacağı zararı
karşılamayı taahhüt edebilir. Bu her halde gönderilene karşı geçersizdir. Sadece
taşıyan ve yükleten arasında sonuç doğurur.

Taşıyan eşyanın haricen belli olan durumunu da konişmentoya yazabilir. Aksi
takdirde eşyanın iyi durumda yüklendiğine dair bir karine oluşur.

Konişmentodan taşıyanın kim olduğu anlaşılamıyorsa donatan taşıyan sayılır.

Konişmentoda, navlunun gönderilen tarafından ödeneceği de kararlaştırılabilir.

* Konişmento taşıyanı ve göndereni belirler. Taşıyan ve gönderen arasındaki
ilişkiyi belirler.
* Konişmentonun meşru hamili eşyanın teslimini isteme hakkına sahip olduğundan
gönderileni belirlemiş olur.
* Taşıyan ve gönderilen arasındaki ilişkiyi belirler.
* Gemiye yüklenen eşyayı ispatlar. Eşyaya ilişkin kayıtlar karine teşkil eder ve
bu karinenin aksi iyiniyetli üçüncü kişiye karşı ispatlanamaz.

Kaptan, konişmentoyu ilk ibraz edene malı teslim ederek ifayı gerçekleştirir.

Kaptana aynı anda birden çok konişmento ibraz edilirse, mal umumi bir ambara
tevdi edilir ve uyuşmazlık mahkemece çözümlenir. Birden çok konişmento ibraz
edilerek farklı ayni haklar ileri sürülürse ortak ciranta bulunup cirp
zincirleri incelenerek kimin haklı olduğu bulunur.

NOTE: Konişmentoyu iyiniyetle teslim alan kimse ile eşyayı iyiniyetle teslim
alan kimse arasında uyuşmazlık çıkarsa eşyayı teslim alan tercih olunur.

Varma limanından önce yükleten eşyanın kendisine iadesini ister ya da ara bir
limanda yetkili hamil malın teslimini isterse zilyetliğin devri ancak tüm
nüshaların teslimi karşılığında gerçekleştirilebilir. Aksi takdirde taşıyanın
sorumluluğu sona ermez.

=== TAŞIYANIN SORUMLULUĞU

==== BAŞLANGIÇTAKİ ELVERİŞSİZLİKTEN SORUMLULUK

Her türlü navlun sözleşmesinde taşıyan, geminin *denize*, *yola* ve *yüke*
elverişli halde bulunmasını sağlamakla yükümlüdür.

.. _Denize elverişlilik_, geminin, gövdesi, genel donanımı, makinesi ve kazanı
itibariyle yolculuğun yapılacağı sudan ileri gelen (anormal tehlikeler hariç)
tehlikelere karşı koyabilecek durumda olmasıdır.
.. _Yola elverişlilik_, denize elverişli geminin, teşkilatı, yükleme durumu,
yakıtı, kumanyası, gemi adamlarının yeterliliği ve sayısı bakımından, (tamamıyla
anormal tehlikeler hariç) yapacağı yolculuğun tehlikelerine karşı koyabilmek
için gerekli niteliklere sahip bulunmasıdır.
.. _Yüke elverişlilik_, geminin, soğutma tesisatı da dahil olmak üzere, eşya
taşımada kullanılan kısımları eşyanın kabulüne, taşınmasına ve muhafazasına
elverişli olmasıdır.

Taşıyan, *yükle ilgili olanlara karşı* geminin denize, yola veya yüke
elverişli olmamasından doğan zararlardan sorumludur; meğer ki, tedbirli bir
taşıyanın harcamakla yükümlü olduğu dikkat ve özen gösterilmekle beraber,
*eksikliği yolculuğun başlangıcına kadar keşfe imkan bulunmamış olsun.*

Yolculuk başladıktan sonra ortaya çıkan elverişsizlik bu hüküm kapsamında
değildir. Sonradan ortaya çıkan elverişsizlikten doğan sorumluluk, zıya, hasar
ve geç teslimden doğan sorumluluk kapsamında değerlendirilir.

Taşıyanın sorumluluktan kurtulmak için tek imkanı, gerekli özeni gösterdiği
halde elverişsizliği keşfedememiş olduğunu ispatlamaktır. Elverişsizliğin
taşıyanın veya ona bağlı çalışanların kusurundan ileri gelmesi aranmaz.

NOTE: Yolculuğun başlama zamanı yüke göre belirlenecektir. Dolayısıyla ara bir
limanda gemiye alınmış yük için başlama zamanı ara liman olacaktır.

Taşıyanın sorumluluğuna gidilebilmesi için yük sahibinin yükünde meydana gelen
zararı, gemideki elverişsizliği ve elverişsizlik ile zarar arasındaki illiyet
bağını ispatlaması gerekir.

==== EŞYANIN ZIYA, HASAR YA DA GEÇ TESLİMİ

Eşyanın zıya, hasar veya geç teslimi sonucunda taşıyanın sorumluluğuna
gidilebilmek için:

. Eşya zıya veya hasar uğramış ya da geç teslim edilmiş olmalıdır.
+
*Zıya*, taşıyanın, eşyayı tamamen veya kısmen teslim etmek etmek gücünden
yoksun olmasıdır.
+
*Hasar*, eşyanın uğradığı nitelik değişikliği sonucunda sürekli ekonomik değer
kaybına uğramış olmasıdır.
+
*Geç teslim*, eşyanın, sözleşmede bir teslim zamanı öngörülmüşse bu zaman içinde
teslim edilmemesidir. Sözleşmede bir teslim zamanı öngörülmemişse somut olayın
koşullarına göre makul teslim süresi belirlenir ve buna göre geç teslim olup
olmadığı belirlenir.
+
NOTE: Teslim süresinin dolmasından itibaren *aralıksız 60 gün* geçer ve eşya
hala teslim edilmemiş olursa, eşya zayi olmuş sayılır.
. Zarara yol açan *olay*, eşya taşıyanın hakimiyetindeyken meydana gelmiş
olmalıdır. Hakimiyet (zilyetlik) eşyanın teslim alınması ile başlar ve teslim
edilmesi ile sona erer.
+
.Sorumluluğun başlaması
****
* Eşya doğrudan yükleten tarafından taşıyana teslim ediliyorsa sorumluluk bu
anda başlar.
* Eşya yükleten adına veya hesabına hareket eden birisinden teslim alınıyorsa
sorumluluk bu anda başlar.
* Yükleme limanında uygulanan düzenlemeler çerçevesinde eşyanın yükleme için
kendilerine teslimi zorunlu olan makam ya da üçüncü kişilerden teslim
alınıyorsa sorumluluk bu anda başlar.
****
+
.Sorumluluğun sona ermesi
****
* Eşya doğrudan gönderilene teslim ediliyorsa sorumluluk bu anda sona erer.
* Taşıyan boşaltma limanında eşyayı doğrudan gönderilene teslim edemiyorsa;
eşyanın liman idaresine teslimi söz konusu ise bu teslim ile sorumluluk sona
erer.
* Gönderilen eşyayı teslim almaktan kaçınırsa ve taşıyan alacaklı temerrüdü
hükümleri çerçevesinde eşyayı umumi bir ambara tevdi ederse tevdi zamanı ile
birlikte sorumluluk sona erer.
****
. Taşıyanın ve adamlarının kusursuzluğu ispatlanmamış olmalıdır.
+
Tazminat talep eden yükle ilgili kişi, taşıyanın veya adamlarının zarara
kusurlarıyla yol açtığını kanıtlamak zorunda değildir. Taşıyan sorumluluktan
kurtulmak için kendisinin ve adamlarının kusursuzluğunu ispatlayacaktır.

Taşıyanın veya adamlarının kusurunun diğer bir sebeple birlikte zıya, hasar
veya teslimdeki gecikmeye yol açması halinde, taşıyan, zıya, hasar ve
teslimdeki gecikmenin sadece belirtilen kusura bağlanabilen kısmından
sorumludur. *Böyle bir kısmi sorumluluk için bu hallerin söz konusu kusura
bağlanamayacak kısmının taşıyanca ispatı gerekir.*

=== TAŞIYANIN SORUMSUZLUK HALLERİ

==== TEKNİK KUSUR VE YANGIN

Zarar, *geminin sevkine* veya *başkaca teknik yönetimine* ilişkin bir hareketin
veya *yangının* sonucu olduğu takdirde, *taşıyan yalnız kendi kusurundan*
sorumludur. *Daha çok yükün menfaati gereği alınan önlemler, geminin teknik
yönetimine dahil sayılmaz.*

Tereddüt halinde zararın, teknik yönetimin sonucu olmadığı kabul edilir.

IMPORTANT: Başlangıçtaki elverişsizlik söz konusu ise taşıyan teknik kusur
savunmasına dayanamaz.

.Uluslararası Güvenli Yönetim Kodu
****
Denizde can ve mal güvenliğinin korunması, birtakım kazaların önlenmesi için
oluşturulmuş bir sistemdir. Bu sistem çerçevesinde acil durumlarda uygulanması
gereken prosedür ile birlikte alınması gereken önlemler de belirlenmiştir.

Bu çerçevede taşıyanın güvenli yönetim koduna uygun bir yönetim sistemi
oluşturup oluşturmadığı, sistem çerçevesinde uygulanması gereken kuralların
uygulanmasını sağlayıp sağlamadığı şahsi kusurunu gündeme getirir.
****

==== DENİZDE KURTARMA

Taşıyan, müşterek avarya hali hariç, *denizde can ve eşya kurtarmadan* veya
*kurtarma teşebbüsünden* ileri gelen zararlardan sorumlu değildir. Teşebbüs,
sadece eşya kurtarmaya yönelikse, aynı zamanda makul bir hareket tarzı
oluşturması gerekir.

==== EŞYANIN CİNSİNİN VEYA DEĞERİNİN KASTEN YANLIŞ BİLDİRİLMESİ

Yükle ilgili kişi, eşyanın *cinsi* veya *değeri* hakkında taşıyanı *kasten*
yanlış bilgilendirmiş ve bu bilgi denizde taşıma senedine geçmişse taşıyan
sorumluluktan kurtulur.

=== TAŞIYANIN KUSURSUZLUK VE UYGUN İLLİYET BAĞI KARİNELERİNDEN YARARLANDIĞI HALLER

Taşıyan, zararın kanunda sayılan hallerin birinden doğmuş olabileceğini ilk
bakışta ve ispat kuralları çerçevesinde ortaya koyduğu takdirde, lehine iki
karine oluşur:

. *Zararın gerçekten bu sebepten ileri geldiği karinesi*
. *Taşıyan ve adamlarının kusursuz olduğu karinesi*

IMPORTANT: Bunların ikisi de karinedir. Sadece ispat yükü yer değiştirir ve
aksini ispat yükle ilgiliye düşer.

.. *Denizin tehlike ve kazaları:* Örneğin yükün ıslanmış olması karşısında
taşıyan yolda karşılaşılan şiddetli ve öngörülemez fırtınayı öne sürebilir ve
yükün bu yüzden ıslanmış olabileceği savunmasını yapabilir. Kesin ispat
aranmadığından gemi jurnalinin ve meteoroloji raporlarının sunulması yeterli
olacaktır.
.. *Harp olayları, karışıklıklar, ayaklanmalar*
.. *Yükletenin fiil ve ihmalleri:* Örneğin taşıyan ambalajın yetersizliğini
ortaya koyabilir ya da yükün üzerine koyulan işaretlerin yetersizliğini ileri
sürebilir.
.. *Grev, lokavt ve diğer çalışma engelleri*
.. *Eşyanın kendine özgü doğal cinsi ve niteliği*

=== BİLDİRİM YÜKÜMLÜLÜĞÜ

Zıya veya hasarın *en geç eşyanın gönderilene teslimi sırasında* taşıyana
*yazılı* olarak bildirilmesi şarttır. Zıya veya hasar haricen belli değilse,
bildirimin eşyanın *gönderilene teslimi tarihinden itibaren* aralıksız olarak
hesaplanacak *üç gün* içinde gönderilmesi yeterlidir.

Süresi içinde yapılmayan bildirimin sonuçlarına gönderilen katlanır. Bu halde
ispat yükü yer değiştirir ve olayları aydınlatma yükümlülüğü bildirim yapmayan
gönderilene geçer. İspat yükü yer değiştirdiğinde taşıyan lehine iki karine
oluşur:

. *Eşyanın denizde taşıma senedinde olduğu gibi teslim edildiği*
. *Zararın taşıyanın sorumlu olmadığı bir sebepten ileri geldiği*

Eşyanın teslimindeki gecikmenin, gönderilen tarafından, onun *kendisine teslimi
tarihinden itibaren* aralıksız olarak hesaplanacak *altmış gün içinde* taşıyana
*yazılı* olarak bildirilmesi şarttır. Süresinde bildirim yapılmayan gecikme
zararları için tazminat ödenmez.

Eşya, fiili taşıyan tarafından teslim edilmişse, kendisine yapılan her bildirim
taşıyana yapılmış gibi hüküm ifade eder. Kaptan ve sorumlu gemi zabiti dahil
olmak üzere, taşıyan veya fiili taşıyan ad ve hesabına hareket eden her kişiye
yapılan bildirim, taşıyana veya fiili taşıyana yapılmış sayılır.

NOTE: Bildirim sonrasında tazminat talebi de 1 yıllık hak düşürücü süre
içerisinde ileri sürülmelidir.

=== TAŞIYAN VE ADAMLARININ AKİT DIŞI SORUMLULUĞU

Taşıyanın sorumluluktan kurtulması halleri ile sorumluluk sınırlandırılmasına
ilişkin hükümler, navlun sözleşmesine konu olan eşyanın zıya, hasar veya geç
teslimi yüzünden, taşıyan aleyhine, haksız fiile veya diğer bir sebebe
dayanılarak açılacak bütün davalarda uygulanır.

Böyle bir dava, taşıyanın adamlarından biri aleyhine açılırsa, *görevi ve
yetkisi sınırları içinde hareket ettiğini ispat etmek kaydıyla*, o da,
taşıyanın sorumluluktan kurtulması halleri ile sorumluluğu sınırlandırma
hakkından yararlanabilir.

Taşıyan ile onun adamlarından istenebilecek olan tazminat miktarlarının
*toplamı*, kanunda öngörülen sorumluluk sınırını aşamaz.
