:icons: font
:toc:
:toc-title: Medeni Usul II. Dönem

Yazılı yargılama usulünde yargılama beş aşamadan oluşmaktadır.

. *Dilekçeler teatisi*

.. Dava dilekçesi
.. Cevap dilekçesi
.. Cevaba cevap dilekçesi
.. 2. Cevap dilekçesi

. *Ön inceleme*
. *Tahkikat*
. *Sözlü yargılama*
. *Hüküm*

== DAVA ÇEŞİTLERİ

=== EDA DAVASI

[caption=""]
.Eda davası
====
*HMK 105*: (1) Eda davası yoluyla mahkemeden, davalının, bir şeyi vermeye veya
yapmaya yahut yapmamaya mahkûm edilmesi talep edilir.
====

Edaya mahkum eden karar, yani *eda ilamı* iki unsuru içermektedir: _Hukuki
ilişkinin tespiti_ ve _eda emri_. Bu iki unsurun birlikte olması durumunda eda
kararından söz edilir. Mahkemeden alınan ilam, davalının rızası ile yerine
getirilmez ise icra organları kanalı ile *ilamlı icra* yoluna başvurulabilir.

Eda davasının reddedilmesi halinde verilecek olan karar tespit davalarındaki
gibi bir tespit kararıdır.

=== TESPİT DAVASI

[caption=""]
.Tespit davası
====
*HMK 106*: (1) Tespit davası yoluyla, mahkemeden, bir hakkın veya hukuki
ilişkinin varlığının ya da yokluğunun yahut bir belgenin sahte olup olmadığının
belirlenmesi talep edilir.

(2) Tespit davası açanın, kanunlarda belirtilen istisnai durumlar dışında, bu
davayı açmakta hukuken korunmaya değer güncel bir yararı bulunmalıdır.

(3) Maddi vakıalar, tek başlarına tespit davasının konusunu oluşturamaz.
====

Tespit davaları, menfi ve müspet tespit davaları olarak ikiye ayrılmaktadır.
**Müspet tespit davası**nda bir hukuki ilişkinin varlığının tespiti talep
edilmektedir. **Menfi tespit davası**nda ise bir hukuki ilişkinin yokluğunun
tespiti talep edilmektedir.

[TIP]
====
Menfi tespit davaları ile müspet tespit davalarında zamanaşımının kesilmesi
birbirinden farklıdır.

Müspet tespit davalarında davacı bir hukuki ilişkinin varlığını iddia eder ve
bunun için dava açar. Dava açıldığı anda zamanaşımı kesilir.

Menfi tespit davalarında ise dava açıldığı anda zamanaşımı kesilmez. Davacı bir
hukuki ilişkinin yokluğunu iddia etmektedir. Davalı ise hukuki ilişkinin
varlığını ileri süren taraftır. Zamanaşımı davalının davada "böyle bir hukuki
ilişki var" dediği anda kesilir.
====

Tespit davası sonucunda verilen karara dayanarak bir eda davası açılabilir. Eda
davasına bakan hakim, tespit davasında verilen karar ile bağlıdır. Dolayısıyla
tespit davası, eda davasının öncüsü durumundadır.

IMPORTANT: Eda davası açılabilecek iken tespit davası açılamaz. Çünkü hukuki
yarar yoktur.

HMK 106/2 uyarınca *güncel hukuki yarar* ne zaman mevcut olabilir? Davacının
bir hakkı veya hukuki durumu halihazır bir tehlike ile ciddi bir şekilde tehdit
edilmiş olmalı ve bu tehdit sebebiyle davacının hukuki durumu belirsiz
olmalıdır.

=== İNŞAİ DAVA

[caption=""]
.İnşai dava
====
*HMK 108*: (1) İnşaî dava yoluyla, mahkemeden, yeni bir hukuki durum
yaratılması veya mevcut bir hukuki durumun içeriğinin değiştirilmesi yahut onun
ortadan kaldırılması talep edilir.

(2) Bir inşaî hakkın, dava yoluyla kullanılmasının zorunlu olduğu hâllerde,
inşaî dava açılır.

(3) Kanunlarda aksi belirtilmedikçe, inşaî hükümler, geçmişe etkili değildir.
====

İnşai davalar, inşai haklara dayanır. Her inşai hak dava ile kullanılmaz. İnşai
hakkın sahibi karşı tarafa yönelteceği tek taraflı irade beyanı ile hakkını
kullanabilir ve bunun sonuçları kendiliğinden doğar. Ancak bazen hakkın
niteliği gereği hakkın dava açılarak ileri sürülmesi gerekir. 

İnşai davada verilen hüküm kural olarak ileriye etkilidir. İstisnalara örnek
olarak soy bağının tespiti davasında, baba ile çocuk arasında soy bağının
bulunduğuna ilişkin karar verildiği anda bu husus geçmişe etkili sonuç
doğuracaktır.

İnşai dava sonucunda verilecek kararların infaz edilmesine gerek yoktur.
Örneğin bir boşanma davasında hakimin boşanmaya karar vermesi halinde boşanma
gerçekleşir. Ancak boşanmanın yanında nafakaya hükmedilmesi durumunda nafaka
kararı icrai bir karardır ve ilamlı icra ile tahsili mümkündür.

=== TERDİTLİ DAVA

[caption=""]
.Terditli dava
====
*HMK 111*: (1) Davacı, aynı davalıya karşı birden fazla talebini, aralarında
aslilik-ferîlik ilişkisi kurmak suretiyle, aynı dava dilekçesinde ileri
sürebilir. Bunun için, talepler arasında hukuki veya ekonomik bir bağlantının
bulunması şarttır.

(2) Mahkeme, davacının asli talebinin esastan reddine karar vermedikçe, fer’î
talebini inceleyemez ve hükme bağlayamaz.
====

Terditli dava, davacının taleplerinden birine asli, diğerine tali nitelik
kazandırmış olmasıdır. Bu nitelik eğer yargılamayı yürüten hakim tarafından
dava dilekçesinde tespit edilemezse dava HMK 110 uyarında davaların yığılması
olarak görülecektir.

Davayı yürütürken hakimin öncelikle asli nitelikteki talebin geçerli olup
olmadığını, asli nitelikteki talep hakkında karar verme kabiliyetinin bulunup
bulunmadığını tespit etmesi gerekir. Eğer asli nitelikteki talebe dair lehe
karar verme imkanı bulunmadığı tespit edilirse, tali nitelikteki talep ile
ilgili güncelleme ve karar aşaması gerçekleşecektir.

CAUTION: Asli nitelikteki talebe dair lehe karar verilmişse feri nitelikteki
talebe dair karar verilemez. Verilirse iade ve yeniden yargılama sebebidir.

Davacı, davasını dava dilekçesinde terditli dava olarak kurgulamamış olsa bile
daha sonra ıslah ile  terdit ilişkisi kurabilir. Dava dilekçesi ile terdit
ilişkisinin kurulması **kamilen ıslah**tır.

Terditli davada esas şart asli talebe ve feri talebe ilişkin sunulmuş vakıların
birbirleriyle çelişmemesidir.

TIP: Delil avansının belirlenmesinde taleplerden değeri yüksek olan esas alınır.

=== KISMİ DAVA

[caption=""]
.Kısmi dava
====
*HMK 109*: (1) Talep konusunun niteliği itibarıyla bölünebilir olduğu
durumlarda, sadece bir kısmı da dava yoluyla ileri sürülebilir.

(2) (Mülga: 1/4/2015-6644/4 md.)

(3) Dava açılırken, talep konusunun kalan kısmından açıkça feragat edilmiş
olması hâli dışında, kısmi dava açılması, talep konusunun geri kalan kısmından
feragat edildiği anlamına gelmez.
====

Davada ileri sürülmüş bedel kadar kısım açısından zamanaşımı kesilir. Kalan
kısım açısından işlemeye devam eder. Hak düşürücü süre açısından da aynısı
geçerlidir.

=== SEÇİMLİK DAVA

[caption=""]
.Seçimlik borç
====
*TBK 87*: Seçimlik borçlarda, hukuki ilişkiden ve işin özelliğinden aksi
anlaşılmadıkça, edimlerden birinin seçimi borçluya aittir.
====

[caption=""]
.Seçimlik dava
====
*HMK 112*: (1) Seçimlik borçlarda, seçim hakkı kendisine ait olan borçlu veya
üçüncü kişinin bu hakkı kullanmaktan kaçınması hâlinde, alacaklı seçimlik dava
açabilir.

(2) Seçimlik davada mahkeme, talebin hukuka uygun olduğu sonucuna varırsa,
seçimlik mahkûmiyet hükmü verir.

(3) Seçimlik mahkûmiyet hükmünü cebrî icraya koyan alacaklı, takibinin
konusunu, mahkûmiyet hükmünde yer alan edimlerden birine hasretmek zorundadır.
Ancak, bu durum, borçlunun, diğer edimi ifa etmek suretiyle borcundan kurtulma
hakkını ortadan kaldırmaz.
====

TBK 87'deki hal mevcutsa açılacak dava HMK 112 uyarınca seçimlik dava açılır.
Sözleşmede seçim alacaklıya bırakıldıysa seçimlik davanın açılmasında hukuki
yarar yoktur.

Taleplerin tümüne ilişkin ortak bir tahkikat yürütülür ve hepsi hakkında karar
verilir. Karar tüm edimlerin ifa edilmesi şeklinde olacaktır, bunlardan
herhangi birisinin ifa edilmesine hakim karar veremez. Dava lehine neticelenen
davacı bunu icraya koyarken hükme bağlanmış edimlerden birini tercih ederek
ilamlı icraya başlar.

Ancak aleyhine dava neticelenen davalı, hükümde aleyhine hükmedilmiş edimlerden
kendisi aleyhine takip başlatılmış olanı değil de bir başkasını ifa etmek
iktidarına sahip olduğunu söylerse o edimi ifa ederek borcundan kurtulabilir.
Bu seçim hakkı, icra emrinin içinde yer alır. Seçimlik dava özelinde verilmiş
kararlar uyarınca başlatılacak ilamlı icra takibinde icra emri bu hakkı
belirtir nitelikte olmak zorundadır.

=== BELİRSİZ ALACAK DAVASI

[caption=""]
.Belirsiz alacak ve tespit davası
====
*HMK 107*: (1) Davanın açıldığı tarihte alacağın miktarını yahut değerini tam
ve kesin olarak belirleyebilmesinin kendisinden beklenemeyeceği veya bunun
imkânsız olduğu hâllerde, alacaklı, hukuki ilişkiyi ve asgari bir miktar ya da
değeri belirtmek suretiyle belirsiz alacak davası açabilir.

(2) Karşı tarafın verdiği bilgi veya tahkikat sonucu alacağın miktarı veya
değerinin tam ve kesin olarak belirlenebilmesinin mümkün olduğu anda davacı,
iddianın genişletilmesi yasağına tabi olmaksızın davanın başında belirtmiş
olduğu talebini artırabilir.

(3) Ayrıca, kısmi eda davasının açılabildiği hâllerde, tespit davası da
açılabilir ve bu durumda hukuki yararın var olduğu kabul edilir.
====

Belirsiz alacak davası esasında bir kısmi davadır. Ancak sadece  *likit olmayan
alacaklar*, yani belirsiz alacaklar için açılabilir.

Belirsiz alacak davasında talep olarak dermeyan edilebilecek hususlar:

. *Para alacakları*: Ama para alacağı doğumu itibariyle belirlenebilir
nitelikte olmamalı, likit olmamalı, yani sözleşmeye dayanmamalıdır. Buna
ilişkin en tipik örnek haksız fiildir. Haksız fiilden kaynaklı tazminat
taleplerinde belirsiz alacak davası söz konusu olabilir.
. *TBK 50/2*: "_Uğranılan zararın miktarı tam olarak ispat edilemiyorsa hâkim,
olayların olağan akışını ve zarar görenin aldığı önlemleri göz önünde tutarak,
zararın miktarını hakkaniyete uygun olarak belirler._"

HMK 107/1'deki şartlar belirsiz alacak davasını açmak için gerekli şartlardır.
Yargıtay bunları belirsiz alacak davasının dava şartı gibi telakki etmekte ve
bunlar yoksa davanın reddedilmesi gerektiğini kabul etmektedir.

Dava sırasında alacağın miktarı belirlenebilir hale gelirse davacı dava
konusunun değerini ıslah olmaksızın, dilekçe ile talepte bulunarak artırabilir.

Yargıtay'a göre belirsiz alacak davasının açılmasıyla zamanaşımı kesilir, hak
düşürücü süre korunur. Ancak bu konuda müstakil bir içtihat da yoktur.

=== KARŞI DAVA

[caption=""]
.Karşı dava açılabilmesinin şartları
====
*HMK 132*: (1) Karşı dava açılabilmesi için;

.. Asıl davanın açılmış ve hâlen görülmekte olması,
.. Karşı davada ileri sürülecek olan talep ile asıl davada ileri sürülen talep
arasında takas veya mahsup ilişkisinin bulunması yahut bu davalar arasında
bağlantının mevcut olması, şarttır.

(2) Belirtilen bu şartlar gerçekleşmeden karşı dava açılacak olursa, mahkeme,
talep üzerine yahut resen, karşı davanın asıl davadan ayrılmasına; gerekiyorsa
dosyanın görevli mahkemeye gönderilmesine karar verir.

(3) Karşı davaya karşı, dava açılamaz.
====

[caption=""]
.Karşı davanın açılması ve süresi
====
*HMK 133*: (1) Karşı dava, cevap dilekçesiyle veya esasa cevap süresi içinde
ayrı bir dilekçe verilmek suretiyle açılır.

(2) Süresinden sonra karşı dava açılması hâlinde, mahkeme davaların ayrılmasına
karar verir.
====

[caption=""]
.Asıl davanın sona ermesi
====
*HMK 134*: (1) Asıl davanın herhangi bir sebeple sona ermesi, karşı davanın
görülüp karara bağlanmasına engel oluşturmaz.
====


== DAVANIN AÇILMASI

Davanın açılmasının bir takım sonuçları vardır. Dava açmak bir usuli işlem
olduğundan bu sonuçların doğması tarafların iradelerine bağlı değildir. Ancak
davanın açılmasının maddi hukuka dayanan bir takım sonuçlarının doğması için
salt davanın açılmış olması yetmez, aynı zamanda dava dilekçesinin karşı tarafa
tebliği gerekir.

Davanın açılmasının sonuçları ikiye ayrılır:

. *Maddi hukuka ilişkin sonuçlar*:

.. _Zamanaşımının kesilmesi_
.. _Hak düşürücü sürenin korunması_
.. _Şahıs varlığı haklarının malvarlığı haklarına dönüşmesi_
.. _Temerrüt_ (Davanın açılmış olması yetmez, tebliğ gerekir)
.. _İyiniyetin ortadan kalkması_ (Davanın açılmış olması yetmez, tebliğ gerekir)

. *Usul hukukuna ilişkin sonuçlar*:

.. _Mahkeme davayı inceleyip, bir karar vermek zorundadır._
.. _Derdestlik_
.. _İhtiyari tedbirin korunması_
.. _Davayı geri alma yasağı_

[caption=""]
.Davanın açılma zamanı
====
*HMK 118*: (1) Dava, dava dilekçesinin kaydedildiği tarihte açılmış sayılır.
Dava dilekçesine davalı sayısı kadar örnek eklenir.

(2) Dava dilekçesinin kaydına ilişkin usul ve esaslar yönetmelikte belirlenir.
====

CAUTION: Dava dilekçesi her zaman karşı taraftan bir fazla sayıda
hazırlanmalıdır. Zira bir tanesi dosyaya konulacak geri kalanlar da karşı
tarafa tebliğ edilecektir.

.Tevzi Bürosu
****
6 Ağustos 2015 tarihli yönetmelikte davanın açılması dava dilekçesinin tevzi
bürosuna verilmesiyle başlar denilmektedir. Tevzi bürosu davaların mahkemeler
arasında dağıtımını yapmaktadır. Dava dilekçesi tevzi bürosuna verildiğinde
davanın harca tabi olup olmadığına bakılır. Harca tabi bir dava söz konusu ise
harcın ve gider avansının ödenmesi; harca tabi olmayan bir dava söz konusu ise
sadece gider avansının ödenmesi talep edilecektir. Ödeme yapıldıktan sonra dava
dilekçesi kayda alınır. Dilekçenin kaydedildiği tarihte dava açılmış sayılır
(HMK 118).
****

[TIP]
====
Fiziki ortam haricinde UYAP üzerinden de dava açılabilir. Fiziki ortam ile UYAP
arasındaki en önemli fark tevzi bürosunda mesai saati bitimine kadar işlem
yapılabilirken UYAP'ta gece 00:00'a kadar işlem yapılabilir. Bu da zamanaşımı
bakımından önemli bir esastır.
====

Hakim, dosyayı alınca davaya ilişkin bir takım hususları belirten bir işlem
yapar, bir karar çıkartır. Buna *tensip zaptı* denir. Tensip zaptında ilk
olarak mahkemenin ismi, tarafların ismi, tarafların adresleri, hakim veya
hakimlerin ismi, zabıt katibinin ismi, davanın açıldığı tarih belirtilir.
Bunlardan sonra da bir takım tespitler yapılır:

. _Dava dilekçesinin bütün unsurları taşıyıp taşımadığı incelenir._
. _Dilekçeler teatisi süreci açıklanır._
. _Davanın konusu belirtilir._
. _Yargılama usulü belirtilir._
. _Harç konusunda bir eksiklik varsa belirtilir._
. _Delillerin dava ve cevap dilekçelerinde sunulması gerektiği, sunulmazsa en
geç ön inceleme aşamasında sunulabileceği belirtilir._

=== DAVA DİLEKÇESİ

[caption=""]
.Dava dilekçesinin içeriği
====
*HMK 119*: (1) Dava dilekçesinde aşağıdaki hususlar bulunur:

a) Mahkemenin adı. +
b) Davacı ile davalının adı, soyadı ve adresleri. +
c) Davacının Türkiye Cumhuriyeti kimlik numarası. +
ç) Varsa tarafların kanuni temsilcilerinin ve davacı vekilinin adı, soyadı ve
adresleri. +
d) Davanın konusu ve malvarlığı haklarına ilişkin davalarda, dava konusunun
değeri. +
e) Davacının iddiasının dayanağı olan bütün vakıaların sıra numarası altında
açık özetleri. +
f) İddia edilen her bir vakıanın hangi delillerle ispat edileceği. +
g) Dayanılan hukuki sebepler. +
ğ) Açık bir şekilde talep sonucu. +
h) Davacının, varsa kanuni temsilcisinin veya vekilinin imzası.

(2) Birinci fıkranın (a), (d), (e), (f) ve (g) bentleri dışında kalan
hususların eksik olması hâlinde, hâkim davacıya eksikliği tamamlaması için bir
haftalık kesin süre verir. Bu süre içinde eksikliğin tamamlanmaması hâlinde
dava açılmamış sayılır.
====

Bir dava dilekçesinin olmazsa olmaz unsurları üç tanedir. Bu unsurlar bir
davayı diğerinden ayırmaya yarar.

. *Taraflar*: 1086 sayılı kanun zamanında tarafta değişiklik ne ıslahla ne de
karşı tarafın rızasıyla hiç bir şekilde yapılamazdı. 6100 sayılı kanun ile
birlikte tarafta değişiklik imkanı getirilmiştir.
+
[caption=""]
.Tarafta iradi değişiklik
====
*HMK 124*: (1) Bir davada taraf değişikliği, ancak karşı tarafın açık rızası
ile mümkündür.

(2) Bu konuda kanunlarda yer alan özel hükümler saklıdır.

(3) Ancak, maddi bir hatadan kaynaklanan veya dürüstlük kuralına aykırı olmayan
taraf değişikliği talebi, karşı tarafın rızası aranmaksızın hâkim tarafından
kabul edilir.

(4) Dava dilekçesinde tarafın yanlış veya eksik gösterilmesi kabul edilebilir
bir yanılgıya dayanıyorsa, hâkim karşı tarafın rızasını aramaksızın taraf
değişikliği talebini kabul edebilir. Bu durumda hâkim, davanın tarafı olmaktan
çıkarılan ve aleyhine dava açılmasına sebebiyet vermeyen kişi lehine yargılama
giderlerine hükmeder.
====
+
[NOTE]
====
Yargıtay, bir kurumun tüzel kişiliği olmamasına rağmen dava açılmasına karşılık
davanın HMK 124 çerçevesinde aslında açılması gereken kişiye yönlendirilmesine
imkan tanımaktadır.

Yine aynı şekilde Yargıtay, ölmüş bir kişiye dava açılması halinde HMK 124/3-4
çerçevesşnde davanın mirasçılarına yönlendirilmesine de imkan tanımaktadır.
====
. *Dava konusu*: Dava konusu davanın hangi hususa ilişkin olduğudur (alacak
davası, tahliye davası vs.). Dava malvarlığına ilişkin ise ayrıca dava
konusunun değeri dava dilekçesinde gösterilmelidir. Harçların hesaplanması için
bu unsurun bulunması gerekir. Ancak HMK 119/2'de bu unsur dava dilekçesinde yer
almıyorsa ne olacağına ilişkin bir husus belirtilmemiştir.
+
[NOTE]
====
Bu konuda doktrinde çeşitli görüşler ileri sürülmüştür. Birinci görüş hakim
dava dilekçesine bakarak dava konusunu çıkartabilir demektedir. Bu sebeple
dilekçenin hemen reddedilmemesi gerekir. Gerekirse hakim davayı aydınlatma
görevi çerçevesinde taraflara açıklama yaptırmalıdır.

Diğer bir görüş ise kanundaki bu boşluğun bilinçli bir boşluk olduğu
yönündedir. Dava konusunun değeri zaruri bir unsurdur ve Harçlar Kanunu 30'a
göre bu boşluk doldurulur.
====
+
[caption=""]
.Noksan tesbit edilen değer üzerinden harcın ödenmesi
====
*Harçlar Kanunu 30*: Muhakeme sırasında tesbit olunan değerin, dava
dilekçesinde bildirilen değerden fazla olduğu anlaşılırsa, yalnız o celse için
muhakemeye devam olunur, takip eden celseye kadar noksan değer üzerinden peşin
karar ve ilam harcı tamamlanmadıkça davaya devam olunmaz. Hukuk Usulü
Muhakemeleri Kanununun 409 uncu maddesinde gösterilen süre içinde dosyanın
muameleye konulması, noksan olan harcın ödenmesine bağlıdır.
====
+
CAUTION: HUMK 409 artık HMK 150'dir.
+
. *Netice-i talep*: HMK 119/2'de sayılanların dışında olduğu için hakimin süre
verip tamamlatacağı bir unsurdur. Eğer netice-i talep eksikse hakim bu durumda
bir haftalık süre verir, o süre içerisinde eksik giderilmezse davanın açılmamış
sayılması sonucu doğar.

HMK 119'da dava dilekçesinin unsurları arasında "_Davacının iddiasının
dayanağı olan bütün vakıların sıra numarası altında açık özetleri_" da
sayılmaktadır. Buna *dava sebebi*, *dava temeli* denilmektedir. Dava temeli
hakkında iki teori ileri sürülmüştür.

Birincisi **ferdileşme teorisi**dir. Ferdileşme teorisi, vakaları yazmak önemli
değil, sadece hukuki sebebin yazılması yeterlidir demektedir. Hangi hukuki
ilişkiye dayanarak, hangi norma dayanarak davanın açıldığı belirtilir.

İkinci teori ise **vakalara dayandırma teorisi**dir. Bu teoriye göre vakaların
tek tek anlatılmalıdır. Dayanılan normun koşul vakası ile vakaların uyuştuğu
açıklanmalıdır.

[caption=""]
.Somutlaştırma yükü ve delillerin gösterilmesi
====
*HMK 194*: (1) Taraflar, dayandıkları vakıaları, ispata elverişli şekilde
somutlaştırmalıdırlar.
====

Vakıaların açıklanmaması durumunda ne olacağı kanunda düzenlenmemiştir. HMK
119/2 bunu süre verilip tamamlattırılacak haller arasında da saymamıştır.
Doktrinde bununla ilgili çeşitli görüşler öne sürülmüştür.

Birinci görüşe göre taraf vakıaları yazmadıysa sonucuna katlanır. Böylece
vakıaların yazılmaması halinde hakim davayı *usulden* reddecektir.

TIP: Hakimin usulden reddettiği dava daha sonra tekrar açılabilir.

İkinci görüşe (*kürsü görüşü*) göre ise dava dilekçesinde üç tane zorunlu unsur
vardır: *taraf*, *sebep* ve *netice-i talep*. Eğer HMK 119/2 zorunlu unsurlara
dair bir düzenleme ise bu durum da zorunlu unsur sayılmalı ve kıyasen HMK 119/2
uygulanmalıdır.

NOTE: Yargıyay da verdiği bazı kararlarda vakalar eksikse hakimin bir haftalık
kesin süre vermesi, o süre içerisinde tamamlanmadığı takdirde davanın açılmamış
sayılmasına karar vermesi gerektiğini söylemektedir.

Yukarıdaki açıklamalar dava dilekçesinde vakıların hiç yazılmamış olması
durumunda geçerlidir. Vakıların eksik yazılmış olması halinde bir görüşe göre
hakimin davayı aydınlatma görevi çerçevesinde eksik tamamlanır. Diğer bir görüş
ise HMK 119/2 uygulansın demektedir. Üçüncü bir görüş ise eksik yazan taraf
sonucuna katlanır ve sadece belirttiği şeyler üzerinden dava görülür
demektedir.

Dava dilekçesinin bir diğer unsuru "_İddia edilen her bir vakıanın hangi
delillerle ispat edileceği_"dir. Sadece delilleri göstermek yetmez, delillerin
vakıalarla eşleştirilmesi de gerekmektedir.

[caption=""]
.Somutlaştırma yükü ve delillerin gösterilmesi
====
*HMK 194*: (2) Tarafların, dayandıkları delilleri ve hangi delilin hangi
vakıanın ispatı için gösterildiğini açıkça belirtmeleri zorunludur.
====

Deliller gösterilmiş ancak eşleştirilmemiş ise bir görüşe göre (*kürsü görüşü*)
hakimin davayı aydınlatma görevi çerçevesinde eksik tamamlanır. Diğer bir
görüşe göre ise HMK 119/2 uygulanacaktır.

Kanun koyucu HMK 121'de davacı açısından belgelerin ne zaman sunulacağını
göstermiştir.

[caption=""]
.Belgelerin birlikte verilmesi
====
*HMK 121*: (1) Dava dilekçesinde gösterilen ve davacının elinde bulunan
belgelerin asıllarıyla birlikte harç ve vergiye tabi olmaksızın davalı
sayısından bir fazla düzenlenmiş örneklerinin veya sadece örneklerinin
dilekçeye eklenerek, mahkemeye verilmesi ve başka yerlerden getirtilecek belge
ve dosyalar için de bunların bulunabilmesini sağlayıcı açıklamanın dilekçede
yer alması zorunludur.
====

Davacı belgeleri hem dava dilekçesinde göstermeli hem de elinde
bulundurmalıdır. Belge davacının elinde değilse belgenin temin edilebilmesi
için gerekli açıklama dilekçeye eklenmelidir.

Dava dilekçesinde zikredilmiş belge mahkemeye sunulmamış ise ön inceleme
aşamasında hakim iki haftalık kesin süre vererek belgelerin sunulmasını veya
getirtilmesi için gerekli açıklamanın yapılmasını talep eder. Bu süre
içerisinde belge sunulmaz veya açıklamaya yapılmaz ise o delile dayanmaktan
vazgeçilmiş sayılır.

[caption=""]
.Ön inceleme duruşması
====
*HMK 140*: (5) Ön inceleme duruşmasında, taraflara dilekçelerinde
gösterdikleri, ancak henüz sunmadıkları belgeleri mahkemeye sunmaları veya
başka yerden getirtilecek belgelerin getirtilebilmesi amacıyla gereken
açıklamayı yapmaları için iki haftalık kesin süre verilir. Bu hususların
verilen kesin süre içinde tam olarak yerine getirilmemesi hâlinde, o delile
dayanmaktan vazgeçilmiş sayılmasına karar verilir.
====

NOTE: Yargıtay Hukuk Genel Kurulu'nun yakın tarihli bir kararında delil
göstermenin ancak dilekçeler teatisi aşamasında olabileceği kabul edilmektedir.
HMK 140/5 ancak gösterilmiş delil mahkemeye sunulmamış ise uygulama alanı
bulur.

Ancak kişiye hiçbir kusur atfedilemeyecek bir olay söz konusu ise HMK 145'te
sonradan delil göstermeye imkan tanınmıştır.

[caption=""]
.Sonradan delil gösterilmesi
====
*HMK 145*: (1) Taraflar, Kanunda belirtilen süreden sonra delil gösteremezler.
Ancak bir delilin sonradan ileri sürülmesi yargılamayı geciktirme amacı
taşımıyorsa veya süresinde ileri sürülememesi ilgili tarafın kusurundan
kaynaklanmıyorsa, mahkeme o delilin sonradan gösterilmesine izin verebilir.
====

=== CEVAP DİLEKÇESİ

[caption=""]
.Cevap dilekçesinin verilmesi
====
*HMK 126*: (1) Davalı, cevap dilekçesini, davanın açılmış olduğu mahkemeye
verir.

(2) Cevap dilekçesine davacı sayısı kadar örnek eklenir.

(3) Cevap dilekçesi, havale edildiği tarihte verilmiş sayılır.

(4) Cevap dilekçesinin örneği mahkeme tarafından davacıya tebliğ edilir.
====

Dava dilekçesinin karşı tarafa Tebligat Kanunu hükümleri çerçevesinde tebliğ
edildiği andan itibaren *iki hafta* içerisinde karşı taraf cevap dilekçesini
vermelidir.

[caption=""]
.Cevap dilekçesini verme süresi
====
*HMK 127*: (1) Cevap dilekçesini verme süresi, dava dilekçesinin davalıya
tebliğinden itibaren iki haftadır. Ancak, durum ve koşullara göre cevap
dilekçesinin bu süre içinde hazırlanmasının çok zor yahut imkânsız olduğu
durumlarda, yine bu süre zarfında mahkemeye başvuran davalıya, bir defaya
mahsus olmak ve bir ayı geçmemek üzere ek bir süre verilebilir. Ek cevap süresi
talebi hakkında verilen karar taraflara derhâl bildirilir.
====

Davalı, hakimden ek süre isteyebilir. Ancak bu ek süre ancak cevap dilekçesini
verme süresi içerisinde istenebilir. Hakimin vereceği süre bir ayı geçemez.
Uygulamada kabul edilen, ek süre verildiğine dair kararın tebliğinden itibaren
bir ayın başlayacağıdır.

[caption=""]
.Süresinde cevap dilekçesi verilmemesinin sonucu
====
*HMK 128*: (1) Süresi içinde cevap dilekçesi vermemiş olan davalı, davacının dava dilekçesinde ileri sürdüğü vakıaların
tamamını inkâr etmiş sayılır.
====

[caption=""]
.Cevap dilekçesinin içeriği
====
*HMK 129*: (1) Cevap dilekçesinde aşağıdaki hususlar bulunur:

a) Mahkemenin adı. +
b) Davacı ile davalının adı, soyadı ve adresleri; davalı yurt dışında ise
açılan dava ile ilgili işlemlere esas olmak üzere yurt içinde göstereceği bir
adres. +
c) Davalının Türkiye Cumhuriyeti kimlik numarası. +
ç) Varsa, tarafların kanuni temsilcilerinin ve davacı vekilinin adı, soyadı ve
adresleri. +
d) Davalının savunmasının dayanağı olan bütün vakıaların sıra numarası +
altında açık özetleri. +
e) Savunmanın dayanağı olarak ileri sürülen her bir vakıanın hangi delillerle
ispat edileceği. +
f) Dayanılan hukuki sebepler. +
g) Açık bir şekilde talep sonucu. +
ğ) Davalının veya varsa kanuni temsilcisinin yahut vekilinin imzası.

(2) 121 inci madde hükmü cevap dilekçesi hakkında da uygulanır.
====

[caption=""]
.Cevap dilekçesinde eksiklik bulunması
====
*HMK 130*: (1) 129 uncu maddenin birinci fıkrasının (a), (b), (c), (ç) ve (ğ)
bentlerinin cevap dilekçesinde eksik olması hâlinde, bunun giderilmesi için
hâkim tarafından bir haftalık süre verilir; eksikliğin bu süre zarfında da
giderilmemesi hâlinde cevap dilekçesi verilmemiş sayılır.
====

[caption=""]
.Cevap dilekçesi verilmesinin sonucu
====
*HMK 131*: (1) Cevap dilekçesinin verilmesinden sonra, cevap süresi dolmamış
olsa bile ilk itirazlar ileri sürülemez.
====

Cevap dilekçesinde davalı bir takım savunmalarda bulunacaktır. Bu savunmalar
esasa ilişkin ve usule ilişkin savunmalar olabilir. Usule ilişkin savunmalar
*ilk itirazlar* ve **dava şartları**dır. Esasa ilişkin savunmalar ise
*itirazlar* ve **defiler**dir.

NOTE: Defi ve itiraz arasında fark, dava dosyasında olması şartıyla davalı
dilekçede belirtmemiş olsa bile hakim *itirazı* re'sen dikkate alır. Ancak
defiler mutlaka taraf tarafından ileri sürülmelidir.

=== CEVABA CEVAP VE İKİNCİ CEVAP DİLEKÇESİ

[caption=""]
.Tarafların ikinci dilekçeleri
====
*HMK 136*: (1) Davacı, cevap dilekçesinin kendisine tebliğinden itibaren iki
hafta içinde cevaba cevap dilekçesi; davalı da davacının cevabının kendisine
tebliğinden itibaren iki hafta içinde ikinci cevap dilekçesi verebilir.

(2) Davacının cevaba cevap, davalının da ikinci cevap dilekçesi hakkında, dava
ve cevap dilekçelerine ilişkin hükümler, niteliğine aykırı düşmediği sürece
kıyasen uygulanır.
====

=== HARÇ VE AVANS ÖDENMESİ

Harca tabi bir dava söz konusu ise hem *harç* ödenecek hem de *gider avansı*
ödenecektir. Dava harca tabi değilse sadece gider avansı ödenecektir. Eğer
yargılamanın devamı sırasında eksik harç ortaya çıkarsa hakim yargılamanın
sonunu beklemez, bir sonraki duruşumaya kadar eksik kısmın ödenmesini talep
eder. Eğer ödenmezse dosyanın işlemden kaldırılması sonucu doğar.

[caption=""]
.Noksan tesbit edilen değer üzerinden harcın ödenmesi
====
*Harçlar Kanunu 30*: Muhakeme sırasında tesbit olunan değerin, dava
dilekçesinde bildirilen değerden fazla olduğu anlaşılırsa, yalnız o celse için
muhakemeye devam olunur, takip eden celseye kadar noksan değer üzerinden peşin
karar ve ilam harcı tamamlanmadıkça davaya devam olunmaz. Hukuk Usulü
Muhakemeleri Kanununun 409 uncu maddesinde gösterilen süre içinde dosyanın
muameleye konulması, noksan olan harcın ödenmesine bağlıdır.
====

=== İDDİA VE SAVUNMANIN GENİŞLETİLMESİ VEYA DEĞİŞTİRİLMESİ YASAĞI

[caption=""]
.İddia ve savunmanın genişletilmesi veya değiştirilmesi
====
*HMK 141*: (1) Taraflar, cevaba cevap ve ikinci cevap dilekçeleri ile
serbestçe; ön inceleme aşamasında ise ancak karşı tarafın açık muvafakati ile
iddia veya savunmalarını genişletebilir yahut değiştirebilirler. Ön inceleme
duruşmasına taraflardan biri mazeretsiz olarak gelmezse, gelen taraf onun
muvafakati aranmaksızın iddia veya savunmasını genişletebilir yahut
değiştirebilir. Ön inceleme aşamasının tamamlanmasından sonra iddia veya
savunma genişletilemez yahut değiştirilemez.

(2) İddia ve savunmanın genişletilip değiştirilmesi konusunda ıslah ve karşı
tarafın açık muvafakati hükümleri saklıdır.
====

İddia ve savunmanın genişletilmesi yasağı *dava sebebi ile ilgili vakıalar* ve
*netice-i talep* ile ilgili ortaya çıkabilir. Yasağın başladığı andan itibaren
yeni vakıalar getirmek, vakıaları değiştirmek yasaktır. Aynı şekilde netice-i
talebi değiştirmek veya artırmak da yasak kapsamındadır.

TIP: Netice-i talebin azaltılması yasak kapsamında değildir. Çoğun içinde az da
vardır.

Taraflar dava dilekçelerinde iddia ve savunmalarını istedikleri gibi değiştirip
geliştirebilirler. Ancak dilekçeler teatisi aşaması bittiği anda yasak başlar.

Ön inceleme aşamasında taraflar ancak karşı tarafın açık rızası ile iddia ve
savunmalarını değiştirip genişletebilirler. Taraflar usulüne uygun olarak davet
edilmiş olmalarına rağmen taraflardan biri mazeretsiz olarak ön inceleme
duruşmasına katılmazsa diğer taraf onun yokluğunda iddiasını ve savunmasını
değiştirip genişletebilir (HMK 141/1).

Ön inceleme aşamasından sonra iddia ve müdafaanın değiştirilmesi ve
genişletilmesi söz konusu olmaz. İstisnası ıslah ve açık rızadır.

İddia ve savunmanın genişletilmesi veya değiştirilmesi yasağının istisnası
sayılabilecek bir konu daha vardır: *Dava konusunun devri*.

[caption=""]
.Dava konusunun devri
====
*HMK 125*: (1) Davanın açılmasından sonra, davalı taraf, dava konusunu üçüncü
bir kişiye devrederse, davacı aşağıdaki yetkilerden birini kullanabilir:

.. İsterse, devreden tarafla olan davasından vazgeçerek, dava konusunu
devralmış olan kişiye karşı davaya devam eder. Bu takdirde davacı davayı
kazanırsa, dava konusunu devreden ve devralan yargılama giderlerinden
müteselsilen sorumlu olur.
.. İsterse, davasını devreden taraf hakkında tazminat davasına dönüştürür.

(2) Davanın açılmasından sonra, dava konusu davacı tarafından devredilecek
olursa, devralmış olan kişi, görülmekte olan davada davacı yerine geçer ve dava
kaldığı yerden itibaren devam eder.
====

NOTE: İradi olmayan devir şekillerinde de(örn. kamulaştırma, cebri icra) HMK
125 uygulanır.

HMK 125 söz konusu olduğunda Yargıtay kararlarına göre yeni davalı, eski
davalının yapmış olduğu işlemlerle bağlı olur. Yani eski davalı ıslah hakkını
kullanmış ise yeni davalı ıslah hakkını kullanamayacaktır.


=== TAKAS

Dava açıldığı zaman şartları mevcutsa takas ileri sürülebilir. Takasın şartları
alacakların aynı cinsten olması, ikisinin de muaccel olması ve takas hakkını
ortadan kaldıracak bir sözleşmenin yapılmamış olmasıdır. Takas beyanı karşı
tarafa vardığı anda sonuç doğurur.

[NOTE]
====
Takas işlemi maddi hukuka ilişkin bir işlem midir, yoksa usul hukukuna ilişkin
bir işlem midir?

Maddi hukuk işlemi olarak kabul edilirse dava içerisinde takas beyanında
bulunulduktan sonra davacı davasını geri alırsa takas işlemi geçerliliğini
koruyacaktır. Takas beyanı geçerliliğini koruduğundan alacak ileride dava
konusu yapılamaz. Maddi hukuk olarak kabul eden görüş bu nedenle çok
eleştirilmektedir.

Usul hukukuna ilişkin bir işlem olarak kabul edilen görüşe göre ise dava
içerisinde takas beyanı taraflar arasında bir işlem değil, hakime yöneltilmiş
bir işlemdir. Bu görüş de maddi hukuka ilişkin unsurları dikkate almadığı
gerekçesiyle eleştirilmektedir.

Üçüncü bir görüş ise Yargıtay'ın da kabul ettiği şekilde çifte karakterli bir
işlem olduğu yönündedir. Hem maddi hukuka hem de usul hukukuna ilişkin sonuçlar
doğurur. Dava içinde takas beyanınde bulunulduktan sonra dava geri alınır ya da
usuli bir sebeple kalkarsa takas işlemi de geçersiz sayılır.
====

Dava dışında takas yapılıp dava içerisinde ileri sürülürse bu bir
**itiraz**dır. Hakim bunu re'sen dikkate almak zorundadır. Takas beyanı ilk
defa mahkemede ileri sürülürse bu bir **defi**dir.

TIP: Takas karşı dava yoluyla da ileri sürülebilir.

== DAVALARIN YIĞILMASI

[caption=""]
.Davaların yığılması
====
*HMK 110*: (1) Davacı, aynı davalıya karşı olan, birbirinden bağımsız birden
fazla asli talebini, aynı dava dilekçesinde ileri sürebilir. Bunun için,
birlikte dava edilen taleplerin tamamının aynı yargı çeşidi içinde yer alması
ve taleplerin tümü bakımından ortak yetkili bir mahkemenin bulunması şarttır.
====

Hukuki sebeb birbirinden farklı olmasına rağmen tahkikat bir arada
görülebilecek niteliğe haizse *objektif dava yığılması*, HMK 110'daki
ifadesiyle *davaların yığılması* söz konusu olur.

Dava edilen talepler için ortak yetkili bir mahkeme bulunmalıdır. Taleplerden
birine ilişkin kesin yetkili bir mahkeme varsa objektif dava yığılması mümkün
değildir.

Talepler tahkikat aşaması ile bir arada incelenir. Her bir talep asli nitelikte
olduğundan her biri hakkında ayrı ayrı karar verilecektir.

TIP: Delil avansı bütün taleplerin değerlerinin toplamına göre belirlenir.

== ÖN İNCELEME

İlk derece mahkemesi hakimi tarafından dilekçeler teatisi aşamasının
tamamlandığına ilişkin bir ara karar verilmesi şarttır. Bu ara karar
verildikten sonra ön inceleme aşamasına geçilir.

[caption=""]
.Ön incelemenin kapsamı
====
*HMK 137*: (1) Dilekçelerin karşılıklı verilmesinden sonra ön inceleme yapılır.
Mahkeme ön incelemede; dava şartlarını ve ilk itirazları inceler, uyuşmazlık
konularını tam olarak belirler, hazırlık işlemleri ile tarafların delillerini
sunmaları ve delillerin toplanması için gereken işlemleri yapar, tarafların
üzerinde serbestçe tasarruf edebileceği davalarda onları sulhe veya
arabuluculuğa teşvik eder ve bu hususları tutanağa geçirir.
====

Ön inceleme aşamasında esasa ilişkin hiçbir karar verilmez. Sadece usul
hukukuna dair kararlar verilir. Dava şartlarının incelenmesi, ilk itirazların
incelenmesi usul hukukuna ilişkin kararlardır.

[caption=""]
.Dava şartları ve ilk itirazlar hakkında karar
====
*HMK 138*: (1) Mahkeme, öncelikle dava şartları ve ilk itirazlar hakkında dosya
üzerinden karar verir; gerektiği takdirde kararını vermeden önce, bu konuda
tarafları ön inceleme duruşmasında dinleyebilir.
====

Bazı durumlarda dava şartları ve ilk itirazlar üzerinde esasa dokunan bir
inceleme yapmak mecburiyeti doğabilir. Bu durumda bunlar bir ön sorun olarak
ele alınıp esasa ilişkin bir inceleme yapılabilir.

Ön inceleme aşamasında gerçekleşecek en önemli faaliyetlerden birisi
**uyuşmazlık noktalarının tespiti**dir. Tahkikat bunların ekseni etrafında
yürütülecektir. Hakim, davacı ve vekili, davalı ve vekili uyuşmazlık
noktalarını hep birlikte belirler. Tespit edilen noktalar **ön inceleme
tutanağı**na yazılacaktır. Bu tutanak geçerlilik şartı olarak davacı, davacı
vekili, davalı, davalı vekili ve hakimin imzasını taşımak zorundadır. Tahkikat
aşamasında yargılama bu tutanak doğrultusunda yürütülecek ve bunun dışında bir
çalışma gerçekleştirilmeyecektir. Ön inceleme aşaması bu tutanağın
imzalanmasıyla sona erer.

Hakim bu aşamada tarafları *sulhe ve arabuluculuğa teşvik* eder.

Ön inceleme aşamasında duruşma yapılması mecburiyeti vardır. Ön inceleme
aşamasında gerçekleşen duruşmaya ön duruşma denir. En az bir kez duruşma
yapılması gerekmektedir, birden fazla da yapılabilir.

TIP: Dava şartlarının yokluğu hakim tarafından dosyadan tespit edilmiş ise
duruşma yapmaya gerek yoktur. Dosya usulden reddedilecektir.

[caption=""]
.Ön inceleme duruşmasına davet
====
*HMK 139*: (1) Mahkeme, dilekçelerin karşılıklı verilmesinden ve yukarıdaki
maddelerde belirtilen incelemeyi tamamladıktan sonra, ön inceleme için bir
duruşma günü tespit ederek taraflara bildirir. Çıkarılacak davetiyede, duruşma
davetiyesine ve sonuçlarına ilişkin diğer hususlar yanında, taraflara sulh için
gerekli hazırlığı yapmaları, duruşmaya sadece taraflardan birinin gelmesi ve
yargılamaya devam etmek istemesi durumunda, gelmeyen tarafın yokluğunda yapılan
işlemlere itiraz edemeyeceği ve diğer tarafın, onun muvafakati olmadan iddia ve
savunmasını genişletebileceği yahut değiştirebileceği ayrıca ihtar edilir.
====

Tebligat Kanunu 9 uyarınca taraflar bir davet ile ön inceleme duruşmasına
çağrılmak zorundadırlar. *HMK 139 uyarınca bu tebligatta duruşmaya mazeretsiz
bir şekilde katılınmaması halinde karşı tarafın iddia ve savunmasını değiştirip
genişletebileceği ihtar edilir*. Ayrıca duruşmaya mazeretsiz olarak gelmemiş
taraf, karşı tarafın yaptığı işlemlere muhalefet de edemeyecektir.

[caption=""]
.İddia ve savunmanın genişletilmesi veya değiştirilmesi
====
*HMK 141*: (1) Taraflar, cevaba cevap ve ikinci cevap dilekçeleri ile
serbestçe; ön inceleme aşamasında ise ancak karşı tarafın açık muvafakati ile
iddia veya savunmalarını genişletebilir yahut değiştirebilirler. Ön inceleme
duruşmasına taraflardan biri mazeretsiz olarak gelmezse, gelen taraf onun
muvafakati aranmaksızın iddia veya savunmasını genişletebilir yahut
değiştirebilir. Ön inceleme aşamasının tamamlanmasından sonra iddia veya
savunma genişletilemez yahut değiştirilemez.

(2) İddia ve savunmanın genişletilip değiştirilmesi konusunda ıslah ve karşı
tarafın açık muvafakati hükümleri saklıdır.
====

[caption=""]
.Ön inceleme duruşması
====
*HMK 140*: (1) Hâkim, ön inceleme duruşmasında, dava şartları ve ilk itirazlar
hakkında karar verebilmek için gerekli görürse tarafları dinler; daha sonra,
tarafların iddia ve savunmaları çerçevesinde, anlaştıkları ve anlaşamadıkları
hususları tek tek tespit eder.

(2) Uyuşmazlık konularının tespitinden sonra hâkim, tarafları sulhe veya
arabuluculuğa teşvik eder; bu konuda sonuç alınacağı kanaatine varırsa, bir
defaya mahsus olmak üzere yeni bir duruşma günü tayin eder.

(3) Ön inceleme duruşmasının sonunda, tarafların sulh veya arabuluculuk
faaliyetinden bir sonuç alıp almadıkları, sonuç alamadıkları takdirde
anlaşamadıkları hususların nelerden ibaret olduğu tutanakla tespit edilir. Bu
tutanağın altı, duruşmada hazır bulunan taraflarca imzalanır. Tahkikat bu
tutanak esas alınmak suretiyle yürütülür.

(4) Ön inceleme tek duruşmada tamamlanır. Zorunlu olan hâllerde bir defaya
mahsus olmak üzere yeni bir duruşma günü tayin edilir.
====

IMPORTANT: 01.10.2011 tarihinden sonra açılmış olan davalarda ön inceleme
aşaması mutlak surette tüketilmek zorundadır. Ön inceleme aşaması tüketilmeden
bir hüküm tesis edilmiş ise Yargıtay nezdinde bozma nedeni, Bölge Adliye
Mahkemesi açısından ise HMK 358 uyarınca başka hiçbir işleme bağlı kalmaksızın
kararın kaldırılarak ilk derece mahkemesine iade sebebidir.

[caption=""]
.Süreler hakkında karar
====
*HMK 142*: (1) Ön inceleme duruşması tamamlandıktan sonra, hâkim tahkikata
başlamadan önce, hak düşürücü süreler ile zamanaşımı hakkındaki itiraz ve
def’ileri inceleyerek karara bağlar.
====

Hakim ön inceleme aşamasında hak düşürücü süre ve zamanaşımı definin varlığını
sadece tespit eder ve incelenmesi gerektiğini belirtir. Ön inceleme aşamasında
hak düşürücü süre ve zamanaşımı define dair kararın tesis edilebilmesi esasa
etki ettiği için mümkün değildir.

TIP: Esasa etki edecek hususlara dair kararın verilebilmesi açısından hukuk
mahkemesinde tahkikat aşaması periyodu kullanılmaktadır. Ön inceleme aşamasında
yargılamaya son verebilmek, ancak tarafların iradesi ile ya da hakimin usule
ilişkin bir kararı ile mümkündür. 

Hakim zamanaşımı ve hak düşürücü süreye dair kararını ön inceleme aşaması
bittikten hemen sonra ve tahkikat aşamasından önce verecektir. Taraflar
tahkikat duruşmasına çıktıkları anda zamanaşımı veya hak düşürücü süreye
ilişkin muhalefetin hakim tarafından bir karara bağlanmış olduğunu bilirler. Bu
hükme doğrudan tesis edecek bir **ara karar**dır. Bu karara karşı kanun yoluna
müracaat imkanı bulunmamaktadır. Hakim gerekçelendirerek hükmü tesis ederken,
HMK 142 uyarınca bu ara karadan rücu etmek imkanına sahiptir.

== ISLAH

====
*HMK 176*: (1) Taraflardan her biri, yapmış olduğu usul işlemlerini kısmen veya
tamamen ıslah edebilir.

(2) Aynı davada, taraflar ancak bir kez ıslah yoluna başvurabilir.
====

Islah, tarafların yapmış oldukları usuli işlemlerin yenilenmesi, düzeltilmesi
anlamına gelmektedir. Dolayısıyla ıslah işleminin gerçekleşebileceği hal,
sadece taraf usuli işlemlerine yöneliktir. Hakimin usuli işlemlerinin ıslah
edilebilmesi mümkün değildir. Yine tarafların karşılıklı yapmış oldukları usuli
işlemler (usul sözleşmeleri) ıslahın konusunu oluşturamaz. Çifte karakterli
usuli işlemler (kabul, sulh, feragat) ıslahın konusunu oluşturamaz. Sadece ve
sadece tek taraflı usuli işlemlerin ıslah edilebilmesi mümkündür.

Islah tek tarafın usul hukukuna ilişkin irade beyanı ile sonuç doğuran bir
işlemdir. Hasmın rızasına ya da hakimin kararına ihtiyaç yoktur.

Hakim sadece ıslah işleminin HMK 176 vd. hükümlere uygun bir şekilde
gerçekleşmiş olup olmadığını, yani şekle ilişkin hususu göz önüne alır. Eğer
şekil bakımında HMK 176 vd. hükümlere aykırılık söz konusu değilse tarafın
yapmış olduğu ıslah işlemi kapsamında yargılamayı yürütür.

NOTE: Davayı kamilen (tamamen) ıslah edebilme imkanı sadece davacıya
tanınmıştır.  Çünkü davadaki konuyu, netice-i talebi ve tarafları tespit etme
iradesi davacının iradesini terk edilmiştir.

[qanda]
Islah sureti ile davanın içerisinde yeni bir dava açılabilmesi mümkün müdür?::
    Dokrinde bazı görüşler buna imkan tanımakla birlikte Yargıtay ve ağırlıklı
    doktrin görüşü yeni bir talebin davacı tarafından ıslah ile dosyaya intikal
    ettirilmesini kabul etmemektedir. Aynı şekilde davalı da ıslah ile karşı dava
    ikame edemez.
Cevap dilekçesinin verilmemesi sonucu davalı davacının tüm iddialarını inkar etmiş sayılır. Davalı bu durumu ıslah edebilir mi?::
    Yargıtay'a göre cevap dilekçesi vermemenin sonucu ile davalı bağlıdır, bu
    usuli işlem ıslah edilebilecek nitelikte bir usuli işlem değildir.
    Yargıtay'a göre mevcut gerçekleşmiş bir işlem olacak ki ıslah edilebilmesi
    mümkün olsun, şeklen yapılmamış bir işlemin ıslahı mümkün değildir.
HMK 123 (davanın geri alınması) ıslah sureti ile söz konusu olabilir mi?::
    HMK 123 konusunda Yargıtay ile doktrin ittifak halindedir. HMK 123 sonucunu
    doğuracak nitelikte bir ıslah işlemi gerçekleştirilemez.

[caption=""]
.Islahın zamanı ve şekli
====
*HMK 177*: (1) Islah, tahkikatın sona ermesine kadar yapılabilir.

(2) Islah, sözlü veya yazılı olarak yapılabilir. Karşı taraf duruşmada hazır
değilse veya ıslah talebi duruşma dışında yapılıyorsa, bu yazılı talep veya
tutanak örneği, haber vermek amacıyla karşı tarafa bildirilir.
====

Tahkikatın sona ermesi bir ara karar ile belirlenmektedir. Tahkikat
neticelendikten sonra ıslah işleminin yapılabilmesi mümkün değildir.

[qanda]
Temyiz aşamasında ilk derece mahkemesi kararı bozuldu. İlk derece mahkemesine dönmüş dosyada ıslah işlemi yapılması mümkün müdür?::
    1948 tarihli bir içtihadı birleştirme kararına göre bozma kararından sonra
    ıslah yapılamaz.
İstinaf incelemesi yapılıp ilk derece mahkemesi kararı kaldırıldı. Islah mümkün müdür?::
    İstinaf incelmesi temyiz incelemesi olmadığından mümkündür.

Islah işlemi, davacı veya davacı vekili, davalı veya davalı vekili tarafından
yazılı veya sözlü olarak gerçekleştirilebilir. Taraf hangi tek taraflı usuli
işlemi ıslah etmek istiyorsa bunu belirtecek ve gereken harç ve masrafı
yatıracaktır. Ardından bir hafta içerisinde o tek taraflı usuli işlemi yeniden
gerçekleştirecektir. Bunların hepsi bir arada da yapılabilir.

IMPORTANT: Islah edilen işlem sanki ilk kez yapılıyormuş gibi eski usuli
işlemin içinde yer alan vakıalar tekrar edilerek yapılmalıdır.

Islah dilekçesinin mutlaka hasma tebliğ edilmesi şartı vardır. Çünkü hasım veya
hasım vekili, hukuki dinlenilme hakkının doğal bir sonucu olarak ıslah
işleminin HMK 176 vd. hükümlerine uygun olup olmadığını denetleme imkanına
sahip olmalıdır. Karşı tarafa tebliğ edilmeden hüküm verilirse bunun mevcut
karara etkisi Yargıtay açısından bozma, istinaf açısından iadedir.

TIP: Kısmen ıslahta özel yetki aranmaz, kamilen ıslahta ise taraf vekilinin
özel olarak yetkilendirilmiş olması gerekir.

[caption=""]
.Islah sebebiyle ortaya çıkan yargılama giderleri ve karşı tarafın zararının ödenmesi
====
*HMK 178*: (1) Islah eden taraf, ıslah sebebiyle geçersiz hâle gelen işlemler
için yapılan yargılama giderleri ile karşı tarafın uğradığı ve uğrayabileceği
zararları karşılamak üzere hâkimin takdir edeceği teminatı, bir hafta içinde,
mahkeme veznesine yatırmak zorundadır. Aksi hâlde, ıslah yapılmamış sayılır.

(2) Karşı tarafın zararının kesin olarak tespit edilmesinden sonra, mahkeme
veznesine yatırılan miktar eksikse tamamlattırılır, fazla ise iade edilir.
====

NOTE: Islah ardından görevli mahkeme değişebilir. Çünkü mevcut bir davanın
içerisine yeni bir konu adapte edilmektedir. Bu durumda verilmesi gereken karar
görevsizlik kararıdır.

Islah edilemeyecek usuli işlemler:

. Tanık listesi değiştirilemez, ikinci bir tanık listesi verilemez.
. Islah yolu ile taraf değiştirilemez.
. İlk itiraz ıslah ile ileri sürülemez.
. Çifte karakterli usuli işlemlerin ıslahı söz konusu olamaz.

Islah edilmiş olan usuli işlem her ne ise o usuli işlem hakim tarafından atık
dikkate alınmayacaktır. Islah geçerli ise, ıslah edilmiş usuli işlem gerekçeli
kararda atıf olarak değerlendirilemez. Esasa ilişkin hüküm tesis edilirken
hiçbir şekilde vakıa olarak ya da vakıayı destekleyen beyan olarak göz önüne
alınmaması gerekir. Aksi istinaf sebebidir, bozma sebebidir.

Talebi artırmak ancak ıslah ile mümkündür. Ancak azaltmak için ne ıslaha, ne
hasmın onayına, ne de hakimin kararına ihtiyaç vardır. Davanın tarafı talep
ettiğinin daha altında bir talebi yargılamanın her safhasında -örneğin kısmi
feragat kapsamında- talep etme imkanına sahiptir.

Tarafların dilekçelerinde ya da tutanağa yansımış beyanlarında yer alan maddi
hataları düzeltebilmek için ıslah işlemine gerek yoktur. HMK 183 çerçevesinde
bu hatalar düzeltilir.

[caption=""]
.Maddi hataların düzeltilmesi
====
*HMK 183*: (1) Tarafların veya mahkemenin dava dosyasında bulunan belgelerdeki
açık yazı ve hesap hataları, karar verilinceye kadar düzeltilebilir.
Taraflardan birinin yazı veya hesap hatasını düzeltmesi sonucu yargılama
uzamışsa, yargılama giderlerinin belirlenmesinde bu durum da dikkate alınır.
====

NOTE: Doktrinde bir görüşe göre esasen ıslah edilmesi gerek olmayan bir usuli
işlem ıslah ile düzeltilmişse hakim bu durumu değerlendirip tarafın ıslah
hakkını kendisine iade etmelidir. Esasen ıslah gerektirmeyen bir durum olmasına
rağmen, ıslah edilmişse ıslah yapılmamış sayılmalıdır.

TIP: Re'sen araştırma ilkesinin geçerli olduğu davalarda ıslaha gerek yoktur.

[caption=""]
.Davanın tamamen ıslahı
====
*HMK 180*: (1) Davasını tamamen ıslah ettiğini bildiren taraf, bu bildirimden
itibaren bir hafta içinde yeni bir dava dilekçesi vermek zorundadır. Aksi
hâlde, ıslah hakkı kullanılmış sayılır ve ıslah hiç yapılmamış gibi davaya
devam edilir.
====

Dava tamamen ıslah edildikten sonra eski davanın yerine kaim olmuş yeni bir
dava vardır. Dolayısıyla istisnalar hariç olmak üzere ıslah edilmiş davadaki
işlemler bertaraf olur.

Yenilenmiş olan davada, ilk davanın açıldığı tarih itibariyle muhafaza edilmiş
hak düşürücü süre ve kesilmiş olan zamanaşımı süresi bu tesirini korumaya devam
eder.

Tamamen ıslah konusu olabilecek hususlar:

. Dava türünün değiştirilmesi
. Dava konusunun değiştirilmesi

İlk yapılmış ön incelemeden farklılık arz eden bir husus yeni dava dilekçesi
ile doğmuş ise bu durumda ön inceleme aşaması yinelenmelidir. Yeni dava
bakımından eski davadaki ön inceleme yeterliyse doğrudan tahkikata
atlanacaktır. Aksi usul ekonomisine aykırıdır.

Tamamen ıslah gerçekleştikten sonra hasmın iki hususa karşı savunma ileri
sürmesi mümkündür:

* Tamamen ıslah iradesinin HMK 176 vd. hükümlerine göre geçersiz olduğu
* Yeni sunulmuş dava dilekçesine karşı esasa ve usule ilişkin savunmalar

[caption=""]
.Kısmen ıslah
====
*HMK 181*: (1) Kısmen ıslaha başvuran tarafa, ıslah ettiği usul işlemini
yapması için bir haftalık süre verilir. Bu süre içinde ıslah edilen işlem
yapılmazsa, ıslah hiç yapılmamış gibi davaya devam edilir.
====

CAUTION: HMK 180 ve HMK 181 arasında bir haftalık sürenin başlama anı
bakımından fark vardır. HMK 180'e göre tamamen ıslah iradesinin
bildirilmesinden itibaren bir hafta içerisinde yeni dava dilekçesi verilmek
zorundadır. HMK 181'e göre ise bir haftalık süreyi hakim vermektedir.
Dolayısıyla sürenin başlangıcı hakimin süreyi verdiğinin tarafa bildirilmesi
anıdır.

Dava dilekçesinde ya da cevap dilekçesinde ya da replik dilekçesinde ya da
düplik dilekçesinde hiç bahis konusu edilmemiş konunun dosyaya ıslah sureti ile
intikal ettirilebilmesi mümkün değildir. Bunun istisnası **terditli dava**dır.
Kısmen ıslah ile mevcut dava terditli davaya dönüştürülebilir.

[caption=""]
.Islahın etkisi
====
*HMK 179*: (1) Islah, bunu yapan tarafın teşmil edeceği noktadan itibaren,
bütün usul işlemlerinin yapılmamış sayılması sonucunu doğurur.

(2) Ancak ikrar, tanık ifadeleri, bilirkişi rapor ve beyanları, keşif ve
isticvap tutanakları, yerine getirilmiş olan veya henüz yerine getirilmemiş
olmakla beraber, karşı tarafın yerine getireceğini ıslahtan önce bildirmiş
olması koşuluyla, yeminin teklifi, reddi veya iadesi ıslah ile geçersiz
kılınamaz.

(3) Şu kadar ki, ıslahtan sonra yapılacak tahkikat sonucuna göre, bu işlemlerin
göz önünde tutulması gerekmiyorsa, bunlar da yapılmamış sayılır.
====

Islah işlemi gerçekleştikten sonra ıslah edilen işlemden sonra yapılmış bütün
usuli işlemler yapılmamış sayılacaktır. Tamamen ıslahta dosyadaki tüm işlemler
yok hükmündedir. Kısmen ıslahta ise taraf, hangi noktadan itibaren kısmen ıslah
sonucunun doğmasını talep etmekte ise bunu ıslah iradesine belirtmelidir ki
ıslah etmiş olduğu usuli işlemin ardından gerçekleşen hangi usuli işlemler
hakim tarafından dikkate alınmayacak tespit edilebilsin.

HMK 179/2'deki işlemler (ikrar, tanık ifadeleri, bilirkişi raporlar, keşif ve
isticvap tutanakları) hiçbir halde ıslahtan etkilenmez. Bu işlemler kamu
düzeninden kabul edilmektedir. Dolayısıyla HMK 179/2'de yer alan usuli
işlemlerin aksine bir hüküm verildiyse bozma veya iade sonucunu doğurabilir.

[NOTE]
====
HMK 179/2'deki usuli işlemler dava tamamen ıslah edildikten sonra itibar
görmesi gerekmeyen usuli işlemler haline gelmişse ne olacaktır?

Hakim gerekçeli kararında yine bunlara atıf yapacaktır ancak ıslah nedeniyle
inceleme lüzumu görülmediğini belirtecektir.
====

== TAHKİKAT

Davacının ve davalının dilekçeler teatisi aşamasında ileri sürdükleri iddia ve
savunmaya ilişkin vakıa ve delillerin gerçekliğinin ve geçerliliğin talep
konusu hakkında hükme varabilmek için araştırılması safhası, tahkikat
aşamasıdır.

[caption=""]
.Tahkikatın konusu
====
*HMK 143*: (1) Tarafların davada ileri sürdükleri bütün iddia ve savunmalar
birlikte incelenir.

(2) Hâkim, muhakemeyi basitleştirmek veya kısaltmak için resen veya taraflardan
birinin talebi üzerine tahkikatın her aşamasında iddia veya savunmalardan
birinin veya bir kısmının diğerinden önce incelenmesine karar verebilir.
====

HMK 143/2 uyarınca hakim kendi insiyatifi ile bazı vakıaların, hadiselerin, ön
sorunların diğer vakıa incelemelerinden öne çekilmesine karar verebilir. Bu
usule aykırılık teşkil eden bir durum değildir.

[caption=""]
.Tarafların dinlenilmesi
====
*HMK 144*: (1) Tahkikat aşamasında mahkeme, her iki tarafı usulüne uygun olarak
davet edip, davada ileri sürülen vakıalar hakkında dinleyebilir.

(2) Mahkemenin, dinlenilmek üzere mahkemeye gelmeleri için iki tarafa vereceği
süre iki haftadan az olamaz. Bu süre, gerektiğinde, mahkemece resen veya iki
taraftan birinin talebi üzerine uzatılabileceği gibi kısaltılabilir.
====

Mutlak surette tahkikat yapılması gereği kanun tarafından getirilmemiştir.
Ancak tahkikat yapılıyorsa HMK 144'e göre duruşma yapılmak zorundadır. Duruşma
tahkikatın olmazsa olmazıdır.

[caption=""]
.Sonradan delil gösterilmesi
====
*HMK 145*: (1) Taraflar, Kanunda belirtilen süreden sonra delil gösteremezler.
Ancak bir delilin sonradan ileri sürülmesi yargılamayı geciktirme amacı
taşımıyorsa veya süresinde ileri sürülememesi ilgili tarafın kusurundan
kaynaklanmıyorsa, mahkeme o delilin sonradan gösterilmesine izin verebilir.
====

[caption=""]
.Mevcut delillerle davanın aydınlanması
====
*HMK 146*: (1) Mahkeme, taraflarca gösterilmiş olan delillerin incelenmesinden
sonra, davanın muhakeme ve hüküm için yeterli derecede aydınlandığını anlarsa,
tahkikatın bittiğini kendilerine bildirir.
====

HMK 146 uyarınca sunulmuş ve belirtilmiş olan delillerde birlikte davanın hüküm
verilebilecek nitelikte olduğu hakim tarafından takdir edilirse tahkikata lüzum
yoktur.

[caption=""]
.Tarafların duruşmaya daveti
====
*HMK 147*: (1) Taraflar, ön inceleme aşamasının tamamlanmasından sonra tahkikat
için duruşmaya davet edilir.

(2) Taraflara gönderilecek davetiyede, belirlenen gün ve saatte geçerli bir
özrü olmadan mahkemede hazır bulunmadıkları takdirde, duruşmaya yokluklarında
devam edileceği ve yapılan işlemlere itiraz edemeyecekleri bildirilir.
====

Tarafların ön inceleme aşamasındaki ön duruşma haricinde bir duruşma davetiyesi
ile duruşmaya mutlaka davet edilmesi gerekmektedir. HMK 147/2 uyarınca
duruşmaya katılmamış olmanın sonuçları da taraflara bildirilmelidir. Eğer bu
niteliğe haiz olmayan duruşma davetiyesi gönderilmişse HMK 147/2'deki sonuç
doğmaz

[caption=""]
.Mahkemenin çalışma zamanı
====
*HMK 148*: (1) Mahkemeler, resmî çalışma gün ve saatlerinde görev yaparlar.
Ancak, zorunluluk veya gecikmesinde zarar olan hâllerde, keşif, delillerin
tespiti ve günlük duruşma listesinde yazılı işler gibi işlemlerin, resmî tatil
günlerinde veya çalışma saatlerinin dışında da yapılmasına karar verilebilir.
====

[caption=""]
.Ses ve görüntü nakledilmesi yoluyla duruşma icrası
====
*HMK 149*: (1) Mahkeme, tarafların rızası olmak şartıyla, kendilerinin veya
vekillerinin, aynı anda ses ve görüntü nakledilmesi yoluyla bulundukları yerden
duruşmaya katılmalarına ve usul işlemleri yapabilmelerine izin verebilir.

(2) Tarafların rızası olmak kaydıyla, mahkeme; tanığın, bilirkişinin, uzmanın
veya bir tarafın dinlenilmesi esnasında başka bir yerde bulunmalarına izin
verebilir. Dinleme, ses ve görüntü olarak aynı anda duruşma salonuna
nakledilir.
====

Hakim kendiliğinden HMK 149'un gerçekleşmesine karar veremez. Taraf ya da taraf
vekillerinin rızalarına istinaden bunun gerçekleşebilmesi mümkün olacaktır.

HMK 150, tarafların ya da bir tarafın duruşmaya gelmemesi halinde hangi sonuca
varılacağını düzenlemektedir.

[caption=""]
.Tarafların duruşmaya gelmemesi, sonuçları ve davanın açılmamış sayılması
====
*HMK 150*: (1) Usulüne uygun şekilde davet edilmiş olan taraflar, duruşmaya
gelmedikleri veya gelip de davayı takip etmeyeceklerini bildirdikleri takdirde
dosyanın işlemden kaldırılmasına karar verilir.

(2) Usulüne uygun şekilde davet edilmiş olan taraflardan biri duruşmaya gelir,
diğeri gelmezse, gelen tarafın talebi üzerine, yargılamaya gelmeyen tarafın
yokluğunda devam edilir veya dosya işlemden kaldırılır. Geçerli bir özrü
olmaksızın duruşmaya gelmeyen taraf, yokluğunda yapılan işlemlere itiraz
edemez.

(3) Duruşma gününün belli edilmesi için tarafların başvurması gereken hâllerde
gün tespit ettirilmemişse, son işlem tarihinden başlayarak bir ay geçmekle
dosya işlemden kaldırılır.

(4) Dosyası işlemden kaldırılmış olan dava, işlemden kaldırıldığı tarihten
başlayarak üç ay içinde taraflardan birinin dilekçe ile başvurusu üzerine
yenilenebilir. Yenileme dilekçesi, duruşma gün, saat ve yeri ile birlikte
taraflara tebliğ edilir. Dosyanın işlemden kaldırıldığı tarihten başlayarak bir
ay geçtikten sonra yenileme talebinde bulunulursa, yeniden harç alınır, bu harç
yenileyen tarafça ödenir ve karşı tarafa yüklenemez. Bu şekilde harç verilerek
yenilenen dava, eski davanın devamı sayılır.

(5) İşlemden kaldırıldığı tarihten başlayarak üç ay içinde yenilenmeyen
davalar, sürenin dolduğu gün itibarıyla açılmamış sayılır ve mahkemece
kendiliğinden karar verilerek kayıt kapatılır.

(6) İşlemden kaldırılmasına karar verilmiş ve sonradan yenilenmiş olan dava,
ilk yenilenmeden sonra bir defadan fazla takipsiz bırakılamaz. Aksi hâlde dava
açılmamış sayılır.

(7) Hangi sebeple olursa olsun açılmamış sayılan davadaki talep dahi vaki
olmamış sayılır.
====

HMK 150/1 uyarınca re'sen araştırma ilkesinin geçerli olmadığı davalarda
taraflar duruşmaya gelmediyse hakim dosyayı işlemden kaldırabilir. Taraflar
duruşmaya gelmekle birlikte davayı takip etmeyeceklerini bildirdikleri takdirde
dosya yine işlemden kalkar.

Taraflardan birinin duruşmaya gelmesi halinde duruşmaya gelmiş olan taraf
dosyanın işlemden kaldırılmasını talep ederse dosya işlemden kalkacaktır (HMK
150/2).

Dosyanın işlemden kaldırılması üzerine taraflar üç ay içinde yenileme dilekçesi
vererek davanın görülmeye devam etmesini sağlayabilirler (HMK 150/4). Bu üç
ayın ilk ayında yenileme dilekçesi verilirse harç ödenmez, bir ay geçtikten
sonra yenileme harcı ödenmesi gerekir.

Dosya işlemden kaldırıldıktan itibaren üç ay içerisinde yenileme dilekçesi
verilmez ise dava açılmamış sayılır (HMK 150/5). Davanın açılmamış sayılmasına
ilişkin kararın neticesinde davanın açılmasına bağlanan sonuçların hepsi
kendiliğinden ortadan kalkar.

Yazılı yargılama usulünde ilk yenileme dilekçesinden sonra dosya bir daha
takipsiz bırakılırsa bir daha yenileme dilekçesi verilemez (HMK 150/6).

CAUTION: HMK 150 emredici bir düzenlemedir, hakimin riayet etme zorunluluğu
vardır. HMK 150 uyarınca dosyanın işlemden kaldırılmasını gerektiren bir hal
vaki olmuş ancak hakim dosyanın işlemden kaldırılmasına ilişkin bir karar
vermemişse bu usule aykırılık dolayısıyla ilk derece mahkemesinin kararına
tesir edecek bir haldir. Hakim HMK 150'ye ilişkin yapmış olduğu geçmiş tarihli
hatayı yargılama süresince telafi edebilir.

Duruşma bir usuli işlemdir ve duruşmayı ispat için kullanılacak yegane delil
**tutanak**tır. Tutanağın özelliği de HMK 154'te belirtilmiştir.

[caption=""]
.Tutanak
====
*HMK 154*: (1) Hâkim, tahkikat ve yargılama işlemlerinin icrasıyla, iki tarafın
ve diğer ilgililerin sözlü açıklamalarını, gerekirse özet olarak zabıt kâtibi
aracılığıyla tutanağa kaydettirir.

(2) Taraflar veya diğer ilgililer sözlü açıklamalarını hâkimin izniyle doğrudan
da tutanağa yazdırabilir.

(3) Aşağıdaki hususlar mutlak olarak tutanağa yazılır:

.. Mahkemenin adı, duruşmanın açıldığı yer, gün ve saat.
.. Hâkim, zabıt kâtibi, hazır bulunan taraflar ve varsa vekilleri, kanuni
temsilcileri, fer’î müdahil ve tercümanın ad ve soyadları.
.. Yargılamanın aleni ya da gizli yapıldığı.
.. Beyanda bulunana okunmak ve imzası alınmak kaydıyla ikrar, yeminin edası,
davanın geri alınmasına muvafakat, davadan feragat, davayı kabule ilişkin
beyanlar ve sulh müzakereleri ile sonucu.
.. Beyanda bulunana okunmak kaydıyla taraf, tanık, bilirkişi veya uzman kişi
beyanı.
.. Duruşma dışında yapılan işlemlerin özeti.
.. Tarafların sundukları belgelerin neler olduğu.
.. Tarafların soruşturmaya ilişkin istekleri ile diğer kanunların tutanağa
yazılmasını emrettiği konular.
.. Ara kararları ve hükmün sonucu.
.. Karar veya hükmün açıklanma biçimi.

(4) Tutanakta sözü edilen veya dosyaya konduğu belirtilen belgeler de tutanağın
eki sayılır.

(5) Tahkikat ve yargılama sırasında yapılan işlemler teknik araçlarla kayda
alınırsa, bu durum bir tutanakla tespit olunur.
====

[caption=""]
.Tutanağın imzalanması ve imza atamayanların durumu
====
*HMK 155*: (1) Tutanak, hâkim ve zabıt kâtibi tarafından derhâl imzalanır.

(2) Tutanağa imza atamayacak durumda olan kimsenin parmak izi alınır, bunun
hangi parmağa ait olduğu belirtilir. Ancak elinde parmak bulunmayanlar, imza
yerine mühür veya özel işaret kullanabilirler.
====

[caption=""]
.Tutanağın ispat gücü
====
*HMK 156*: (1) Ön inceleme, tahkikat ve yargılama işlemleri, ancak tutanakla
ispat olunabilir.
====

TIP: Tutanak TMK 7/2 uyarınca resmi evraktır. HMK 201 uyarınca resmi evrakın
aksinin ispatı yazılı delil ile mümkündür.

Duruşmada yapılanlar, gerçekleşenler duruşma tutanağına yansıdığı ölçüde hükme
esas alınacaktır. Tutanak hazırlandığı esnada hem taraf veya taraf vekili kendi
beyanlarının, hem hasım veya hasım vekilinin beyanlarının hem de hakimin
beyanlarının tutanağa uygun bir şekilde yanısıyıp yansımadığını tetkik etmekle
mükelleftir. Uygun şekilde yansımaz ise müdahele edilecek an o andır. Daha
sonra bunun tashihi mümkün değildir.

WARNING: Tutanağın aksinin ispatı ile tashihi farklı şeylerdir. Tutanakta
gerçekleştiği belirtilen bir hususun gerçekleşmediği yazılı delil ile
ispatlanabilirken tarafın beyanının yanlış geçirilmesi sonradan ispat edilemez.
Ancak o an müdahale edilebilir.

Duruşmaya katılan taraf ya da taraf vekilleri HMK 152 haricinde hasma ya da
onun vekiline doğrudan spru yöneltemez. Soru ancak hakim aracılığı ile
yöneltilebilir. HMK 152 bunun istisnasıdır.

[caption=""]
.Soru yöneltme
====
*HMK 152*: (1) Duruşmaya katılan taraf vekilleri; tanıklara, bilirkişilere ve
duruşmaya çağrılan diğer kişilere, duruşma disiplinine uygun olarak doğrudan
soru yöneltebilirler. Taraflar ise hâkim aracılığıyla soru sorabilirler.
Yöneltilen soruya itiraz edildiğinde, sorunun yöneltilmesinin gerekip
gerekmediğine hâkim karar verir.

(2) Toplu mahkemelerde, hâkimlerden her biri, birinci fıkrada belirtilen
kişilere soru sorabilir.
====

Eğer HMK 152'den istifade etme imkanı taraf vekiline verildiyse zabıt katibi
artık taraf vekilinin katibidir. HMK 154/2 çerçevesinde taraf vekilinin beyanı,
bilirkişinin veya tarafın beyanı doğrudan tutanağa yansıtılacaktır.

[caption=""]
.Dosyanın taraflar ve ilgililerce incelenmesi
====
*HMK 161*: (1) Zabıt kâtibinin gözetimi altında taraflar veya fer’î müdahil,
dava dosyasını inceleyebilir. Dava ile ilgili olanlar da bunu ispatlamak kaydı
ve hâkimin izniyle dosyayı inceleyebilir.

(2) Gizli olarak saklanmasına karar verilen belge ve tutanakların
incelenebilmesi hâkimin açık iznine bağlıdır.
====

Bir avukat ilgili olduğunu beyan ederek bir dosyayı inceleyebilir. Ama bir
gerçek kişi ilgisini ispat edip bunu tutanağa geçirtmek zorundadır.

== ÖN SORUN (MESELE-İ MAKADDİME)

Her bir davanın içinde birden fazla ön sorun mevzu bahis olabilir. Hakimin
öncelikli görevi bu ön sorunları çözüme kavuşturmak ve hükme doğru
ilerlemektir.

[caption=""]
.Ön sorunun ileri sürülmesi
====
*HMK 163*: (1) Yargılama sırasında, davaya ilişkin bir ön sorun ortaya çıkarsa,
ilgili taraf, bunu dilekçe vermek suretiyle yahut duruşma sırasında sözlü
olarak ileri sürebilir.
====

HMK 163 özelinde bir ön sorun hakim tarafından re'sen tespit edilmiş veya
taraflarca ileri sürülmüş ise hakimin önceliği ön sorunun çözülmesidir.

Ön sorun mahiyetindeki bir talep dosyaya intikal ettirilmişse bu talebin
mutlaka hasma da tebliğ edilmesi gerekir. Böylece hasım da ön soruna dair
iddiasını ya da savunmasını ortaya koyabilir. Bu olmaksızın ön soruna dair
incelemenin yapılması mümkün değildir.

IMPORTANT: Hakimin dosyanın münderecatından re'sen tespit edebileceği hususlar
tebliğ edilmeden incelenebilir.

HMK 163'te ön sorunları ileri sürülmesi bir usule bağlanmıştır. Ön sorunların
ileri sürülmesi yazılı ya da sözlü olarak yapılabilir.

Ön sorunun çözümüne ilişkin HMK 19, HMK 211 gibi özel olarak hasredilmiş bir
prosedür yoksa tahkikat benzeri bir faaliyet yürütülüp ön sorun çözülecek ve
HMK 164 uygulanacaktır.

[caption=""]
.Ön sorunun incelenmesi
====
*HMK 164*: (1) Hâkim, taraflardan birinin ileri sürdüğü ön sorunu incelemeye
değer bulursa, belirleyeceği süre içinde, varsa delilleriyle birlikte cevabını
bildirmesi için diğer tarafa tefhim veya tebliğ eder.

(2) Ön sorun hakkında iki taraf arasında uyuşmazlık varsa, hâkim gerekirse
tarafları davet edip dinledikten sonra kararını verir.

(3) Hâkim, ön sorun hakkındaki kararını taraflara tefhim veya tebliğ eder.
====

Tarafların ileri sürdüğü ön sorunun incelenip incelenmeyeceği konusunda hakimin
takdir hakkı vardır. Hakim tarafın ileri sürdüğü ön sorunu incelemeyi
reddetmişse taraf esasa ilişin hüküm ile birlikte bunu istinaf sebebi
yapabilir.

Ön soruna ilişkin verilmiş ara karardan rücu imkanı vardır.

Ön soruna ilişkin incelemenin hüküm aşamasına terk edilmiş olması da usule
aykırıdır. Çünkü hakim hükme gelene kadar ön sorun mahiyetindeki ihtilafı
çözmek ile mükelleftir. Burada *nispi temyiz sebebi* denilen hükme tesir edip
etmeme de Yargıtay tarafından bir kriter olarak kabul edilmektedir.

== BEKLETİCİ SORUN (MESELE-İ MÜSTEHİRE)

[caption=""]
.Bekletici sorun
====
*HMK 165*: (1) Bir davada hüküm verilebilmesi, başka bir davaya, idari makamın
tespitine yahut dava konusuyla ilgili bir hukuki ilişkinin mevcut olup
olmadığına kısmen veya tamamen bağlı ise mahkemece o davanın sonuçlanmasına
veya idari makamın kararına kadar yargılama bekletilebilir.

(2) Bir davanın incelenmesi ve sonuçlandırılması başka bir davanın veya idari
makamın çözümüne bağlı ise mahkeme, ilgili tarafa görevli mahkemeye veya idari
makama başvurması için uygun bir süre verir. Bu süre içinde görevli mahkemeye
veya idari makama başvurulmadığı takdirde, ilgili taraf bu husustaki
iddiasından vazgeçmiş sayılarak esas dava hakkında karar verilir.
====

Bekletici mesele yapılacak olan başka bir mahkemedeki dava ya da idari makam
huzurundaki talep sonucunda verilecek karar ile hüküm arasında bağlantı
olduğunu bekletici mesele yapmak isteyen taraf belirtecek ve ispat edecektir.

Zorunlu bekletici mesele halleri vardır:

. *Anayasa mahkemesine müracaat*
. *Uyuşmazlık mahkemesine müracaat*
. *İcra İflas Kanunu 68/4*: Miras bırakana ait bir alacak sebebi ile takip
edilen borçlunun terekenin borca batık olduğunu ileri sürmesi üzerine terekenin
borca btık mı tespiti için borçluya uygun süre verilmesi

== İSPAT

Tahkikat aşamasında tarafların dilekçeler teatisinde sunmuş oldukları dava
temelini oluşturan vakıalar değerlendirilir. İddia babındaki vakıaların ve
savunma babındaki iddiaların geçerliliğinin bulunup bulunmadığı ispat faaliyeti
ile belirlenir.

Yargıtay ve doktrinde son yıllarda *soyut vakıa* kavramı kullanılmaktadır.
Tarafların iddia ve savunmaları soyut vakıa, yani norm ile örtüştüğü ölçüde
değerlendirilir.

[caption=""]
.İspatın konusu
====
*HMK 187*: (1) İspatın konusunu tarafların üzerinde anlaşamadıkları ve
uyuşmazlığın çözümünde etkili olabilecek çekişmeli vakıalar oluşturur ve bu
vakıaların ispatı için delil gösterilir.

(2) Herkesçe bilinen vakıalarla, ikrar edilmiş vakıalar çekişmeli sayılmaz.
====

HMK'da kabul edilen teori **vakılara dayandırma teorisi**dir. Hem davacı hem
davalı iddia ve savunmalarını vakıalar açısından ele alarak dosyaya intikal
ettirme mükellefiyeti altındadır. Dolayısıyla her bir vakıanın ispatı açısından
delil ayrıca belirtilmelidir. Bunun doğruluğunun, geçerliliğinin incelenmesi
ispat faaliyetidir.

IMPORTANT: İspat faaliyeti yürütülürken kullanılacak enstürman delildir.

Sadece aşağıdaki özellikleri taşıyan vakıların ispatı söz konusudur:

. Uyuşmazlığın çözümünde etkili olacak
. Tarafların üzerinde anlaşamamış olduğu
. Çekişmeli

Hakim ilgili ihtilafa tesir edecek nitelikte dosyada yer almayan bir vakıayı
değerlendirmeye alamaz, ispat faaliyetine konu edemez.

=== İKRAR

[caption=""]
.İkrar
====
*HMK 188*: (1) Tarafların veya vekillerinin mahkeme önünde ikrar ettikleri
vakıalar, çekişmeli olmaktan çıkar ve ispatı gerekmez.

(2) Maddi bir hatadan kaynaklanmadıkça ikrardan dönülemez.

(3) Sulh görüşmeleri sırasında yapılan ikrar tarafları bağlamaz.
====

İkrar yönündeki irade beyanı ile davanın taraflarından biri hasmının sunmuş
olduğu vakıayı ispat külfetini bertaraf etmektedir. Ayrıca ispat açısından bir
delil dermeyan etmiş olsa dahi ilgili delilin tahkikat aşamasında incelenme
zarureti de ortadan kalkar.

Taraf vekilleri ikrar yönündeki beyanlarını dermayan ederlerken özel bir
yetkiyle donanmış olmak zorunda değillerdir.

HMK 188'in genel kabulü mahkeme içi bir ikrara yöneliktir. Mahkeme içi ikrar
iki şekilde olabilir:

. Sunulacak dilekçelerle
. Şifahi nitelikte

Şifahi nitelikte bir irade beyanının ikrar olarak değerlendirilebilmesi için
mutlaka HMK 154'te geçen tutanak düzenlemesine tabi olması gerekir. Tutanağa
bağlanmamış bir irade beyanının geçerli olması söz konusu olmayacaktır. İrade
beyanını ortaya koyan taraf ya da taraf vekilinin mutlak surette ilgili
tutanağın altını da imzalaması gerekmektedir.

Bir beyanın yorum ile ikrar olarak değerlendirilmesi söz konusu olamaz. İkrar
açıkça, hasmın hangi vakıasını hedef alınarak beyan edildiği belirli şekilde
yapılmalıdır.

İkrar hakimi bağlar. İkrarın varlığına rağmen hakim re'sen ikrar edilmiş olan
vakıanın ispatı açısından bir faaliyette bulunamaz. Aksi istinaf sebebidir,
bozma sebebidir.

Yetkisiz, görevsiz mahkemede ikrar beyanında bulunması halinde görevli ve
yetkili mahkemede bu ikrar beyanı geçerli olacaktır.

Mahkeme dışı ikrar bakımından yapılan ikrar ek bir delille ispat edilmek
durumundadır. Aksi takdirde hakim tarafından dikkate alınmaz.

Dört tür ikrar vardır:

. *Basit ikrar*: Taraflardan birinin hasmın ileri sürmüş olduğu vakıayı
gerçekliğini ve geçerliliğini teyit etmiş olmasıdır.
. *Bağlantılı bileşik ikrar*: Taraflardan biri hasmının ileri sürmüş olduğu
vakıayı teyit etmekle birlikte o vakıaya tesir edecek nitelikte yeni bir vakıa
ileri sürmektedir.
+
Örneğin davacı "borç verdim" diyor. Davalı ise "borç aldım ama ödedim" diyor.
Bu durumda bağlantılı bileşik ikrar bölünür. Davalının "borç aldım" demesi ile
bununla ilgili vakıanın ispat külfeti ortadan kalkar. "Aldım ama ödedim"
demesiyle birlikte artık ödediğini ispat etmesi gerekir.
. *Bağlantısız bileşik ikrar*: İki vakıa arasındaki bağlantı somut değildir.
Davacı "borç verdim" diyor. Davalı ise "borç aldım ama takas ettik" diyor. Bu
durumda da ikrar bölünür.
. *Vasıflı ikrar*: Karşı tarafın ileri sürdüğü vakıanın varlığı kabul edilmekle
birlikte hukuki niteliğinin ileri sürülenden farklı olduğu bildirilir.

İkrardan dönmek ancak hasmın rızasıyla mümkündür. Islah yapılamaz.

==== KARİNELER

Karineler, ispat yükünü bertaraf eden nitelikte değildir. Karineyi dermeyan
eden tarafın ispat yükümlülüğü sürmektedir. Ancak bu yükümlülük daraltmış bir
yükümlülüktür. Karineyi dermeyan eden taraf sadece karinenin temelini teşkil
eden vakıanın gerçekleştiğini ispat edecektir.

[caption=""]
.İspat yükü
====
*HMK 190*: (2) Kanuni bir karineye dayanan taraf, sadece karinenin temelini
oluşturan vakıaya ilişkin ispat yükü altındadır. Kanunda öngörülen istisnalar
dışında, karşı taraf, kanuni karinenin aksini ispat edebilir.
====

Aksi ispat edilebilecek nitelikte olan karinelere *adi karine*, aksinin ispatı
caiz olmayan karinelere *kanuni karine* denir.

TIP: Kesin kanuni karinenin aksi ispatlanamazsa da, taraf kendisi aleyhine
ileri sürülmüş vakıada unsurun kendi üzerine tecelli etmediğini ileri
sürebilir.

=== İSPAT HAKKI

[caption=""]
.İspat hakkı
====
*HMK 189*: (1) Taraflar, kanunda belirtilen süre ve usule uygun olarak ispat
hakkına sahiptir.

(2) Hukuka aykırı olarak elde edilmiş olan deliller, mahkeme tarafından bir
vakıanın ispatında dikkate alınamaz.

(3) Kanunun belirli delillerle ispatını emrettiği hususlar, başka delillerle
ispat olunamaz.

(4) Bir vakıanın ispatı için gösterilen delilin caiz olup olmadığına mahkemece
karar verilir.
====

İspat hakkının üç tane unsuru vardır:

. Usule uygun delil
. İddia ve savunma hakkının kullanılabilmesi
. Hukuki dinlenilme hakkı (HMK 27)

İspat hakkının yargılamayı yürüyten hakim tarafından taraflara tanınmış olması
esastır. Tanınmamış olmasu usuli muhakemeye riayet edilmemesi sebebiyle istinaf
sebebidir, temyiz sebebidir.

Hakim HMK 189/4 uyarınca delilin HMK 189/2 ve 189/3'e uygunluğunu re'sen
denetler ve bir karar verir.

CAUTION: HMK 198'de düzenlenen delillerin değerlendirilmesi farklı, HMK 189
uyarınca delilin caiz olup olmadığı farklı değerlendirilir. HMK 189'deki
faaliyet dosya üzerinden yürütülürken, HMK 198'de hakim tahkikat yapacaktır.

=== İSPAT TÜRLERİ

==== Karşı ispat - Asıl ispat

*Asıl ispat*, tarafın kendi iddiası hakimde aleyhine iddiada bulunan taraf
nezdinde kanaat oluşturma faaliyetidir. *Karşı ispat* ise iddia edilen vakıanın
ispatı için ispat yükü taşıyan tarafın yapması gereken ve uygulanacak normun
koşul vakıasını karşılayan somut vakıaların ispatını karşılık karşı tarafça
yapılan ispat faaliyetidir.

[caption=""]
.Karşı ispat 
====
*HMK 191*: (1) Diğer taraf, ispat yükünü taşıyan tarafın iddiasının doğru
olmadığı hakkında delil sunabilir. Karşı ispat faaliyeti için delil sunan
taraf, ispat yükünü üzerine almış sayılmaz.
====

==== Tam ispat - Yaklaşık ispat

*Tam ispat*, iddia olunan vakıanın doğruluğu hakkında tereddüde yer vermeyecek
şekilde hakimin iknasıdır. *Yaklaşık ispat* ise hakikate yakın bir şekilde
ilgili vakıanın ispatı açısından kullanılabilecek delillerin dosyaya
sunulmasıdır.

=== SOMUTLAŞTIRMA YÜKÜ

Taraflar dayandıkları vakıaları ispata elverişli bir biçimde
somutlaştırmalıdırlar. Bu yükümlülük dilekçeler teatisi aşamasında başlar.
Belirsiz, çelişkili nitelikte vakıalar dilekçeye yazılmamalıdır.

[caption=""]
.Somutlaştırma yükü ve delillerin gösterilmesi 
====
*HMK 194*: (1) Taraflar, dayandıkları vakıaları, ispata elverişli şekilde
somutlaştırmalıdırlar.

(2) Tarafların, dayandıkları delilleri ve hangi delilin hangi vakıanın ispatı
için gösterildiğini açıkça belirtmeleri zorunludur.
====


HMK 194'e riayet edilmemesi durumunda hakim HMK 144 uyarınca tarafları
dinleyerek iddia ettikleri vakıalarla ilgili izahat isteyebilir. Bunun dışında
bir müeyyidesi yoktur. Hakim aydınlatma görevi çerçevesinde dosyayı anlamaya
çalışmalıdır. Yargıtay'ın kabulü de bu yöndedir.

=== İDDİA YÜKÜ

Taraflar davadaki maddi soruna ilişkin hukuk normunun aradığı koşul vakıalara
karşılık gelen somut vakıaların varlığını mahkemeye bildirme yükümü altındadır.
Bu vakıalara dayandırma teorisinin doğal bir sonucudur.

=== BAŞKA YERDEN GETİRTİLECEK DELİLLER

[caption=""]
.Başka yerden getirtilecek deliller
====
*HMK 195*: (1) Tarafların ellerinde bulunmayan ve incelenmesine karar verilen
delillerin getirtilmesi için, mahkemece ilgili resmî makam ve mercilerle üçüncü
kişilere bu husus bildirilir. Mahkemeye getirtilmesi mümkün olmayan deliller,
bulunduğu yerde incelenebilir veya dinlenebilir.
====

HMK 195'te düzenlenmiş faaliyet müzekkere ile olur. İlgili idari merci ya da
gerçek kişiden bir belge talep etmek mevzu bahis olduğunda davanın tarafları
bunu yargılamayı yürüten mahkemeden talep ederler, mahkeme müzekkere yoluyla
gerçek veya tüzel kişiye iletir. HMK 195'e üçüncü kişinin riayet etmemesi cezai
müeyyide sonucunu doğurur.

Getirtilecek delil ile ilgili açıklama mutlaka dilekçeler teatisi aşamasında
dilekçeye dermayan edilmiş olmalıdır. Aksi takdirde HMK 195 uygulanamaz.

=== İSTİNABE

[caption=""]
.Delillerin incelenmesi ve istinabe 
====
*HMK 197*: (1) Kanunda belirtilen hâller dışında, deliller davaya bakan mahkeme
huzurunda, mümkün olduğu kadar birlikte ve aynı duruşmada incelenir. Zorunlu
hâllerde, bazı delillerin incelenmesi başka bir duruşmaya bırakılabilir.

(2) Başka yerde bulunan ve mahkemeye getirilemeyen deliller, o yerde istinabe
yoluyla toplanabilir.

(3) Delillerin incelenmesi veya beyanların dinlenmesi sırasında taraflar,
istinabe olunan mahkemede hazır bulunabilir ve delillerle ilgili açıklama
haklarını kullanabilirler. Bu hususu sağlamak için, taraflara incelemenin
yapılacağı tarih ve yer bildirilir. Bu davet üzerine taraflar istinabe olunan
mahkemede hazır bulunmasalar dahi deliller incelenir veya beyanlar dinlenir.
====

IMPORTANT: İstinabe olunan bir mahkemede delilin incelenmesi söz konusu ise bu
faaliyetin davanın tarafların gün, saat ve yer olarak davetiye yoluyla tebliğ
edilmesi esastır. Aksi takdirde hukuki dinlenilme hakkına aykırılık meydana
gelir.

=== DELİLDEN VAZGEÇME

[caption=""]
.Delilden vazgeçme
====
*HMK 196*: (1) Delil gösteren taraf, karşı tarafın açık izni olmadıkça, o
delile dayanmaktan vazgeçemez.
====

=== DELİLLERİN DEĞERLENDİRİLMESİ

[caption=""]
.Delillerin değerlendirilmesi
====
*HMK 198*: (1) Kanuni istisnalar dışında hâkim delilleri serbestçe
değerlendirir.
====

Kesin delille ispat zorunluluğunun olduğu haller HMK 198'in istisnasıdır. Kesin
delille ispatı gereken bir vakıanın ispatı için kesin nitelikte bir delil ileri
sürülmüş ve bu delilin HMK 189 uyarınca caiz olduğuna karar verilmiş ise hakim
bu delil ile bağlıdır.

=== İSPAT YÜKÜ VE DELİL İKAME YÜKÜ

*Vakıadan kendi lehine sonuç çıkaran taraf ispat yükü altındadır*. İspat yükü,
vakıanın ispatsız kalmasının sonuçlarına kimin katlanacağını düzenler.

İspat yükünün iki unsuru vardır:

. *Objektif ispat yükü*: Bir vakıayı dermeyan eden taraf ilgili vakıayı ispat
için faaliyet gösterir.
. *Subjektif ispat yükü*: İspatı sağlayabilmek için delil ikame yükümlülüğünü
ifade eder.

Delil ikame yükü, vakıanın ispatı için gerekli delili kimin sunacağını
belirler. Delil ikame yükü kural olarak ispat ile yükümlü tarafa düşer.

Ancak taraflardan biri vakıanın ispatı için gerekli delilin hasımda
olduğunu ileri sürerse hasım bu delili mahkemeye sunmak zorundadır. Sunmaktan
kaçınması halinde taraf iddiasını ispatlamış sayılır. Bu durumda delil ikame
yükü ispat ile yükümlü tarafta değil, hasımdadır.

NOTE: Hakim, ispat yükünün ve delil ikame yükünün hangi tarafa düştüğünü
prensip olarak söyleyemez. Ancak bir vakıanın ispatsız kalması halinde hakim
ispat yükünün kime düştüğünü tespit eder.

Genel kabule göre taraflar ispat yükünün kime ait olacağına dair sözleşme
yapabilirler.

=== İSPAT ÖLÇÜSÜ

Kanun koyucu prensip olarak tam ispat ölçüsünü aramıştır. Yani hakim, bir
vakıaya ilişkin hüküm kurabilmek için mahiyeti hakkında tam olarak ikna
olmalıdır. Muhtemel görmekle birlikte tam ikna olmadığı hallerde ise yaklaşık
ispat derecesi söz konusudur.

Zayıf ihtimal durumunda hiçbir şekilde buna dayanılarak karar verilemez. Ancak
yaklaşık ispatın yeterli görüldüğü bazı durumlar vardır. Her halükarda kanunda
yaklaşık ispata dair açık bir düzenleme bulunmalıdır.

== DELİL

*Delil, ispat aracıdır*. Delilden söz edebilmek için üç vasfı taşıması gerekir:

. Vakıayı yansıtmaya mahiyeti itibariyle elverişli olmalıdır.
. Akla ve bilime uygun olmalıdır.
. Hukuka uygun olarak elde edilmiş olmalıdır.

Delillere ilişkin olarak iki sistem söz konusudur:

. *Serbest delil sistemi*: Yukarıdaki vasıfları barındıran her türlü ispat
aracı delil olarak kullanılabilir.
. *Kanuni delil sistemi*: Vakıanın ispatında sadece kanunun belirlediği
deliller kullanılabilir.

=== HUKUKA AYKIRI YOLLA ELDE EDİLMİŞ DELİL

HMK 189/2 uyarınca hukuka aykırı yolla elde edilmiş delil mahkeme tarafından
bir vakıanın ispatında kullanılamaz.

NOTE: Hukuka uygun yollarla elde edilebilecek hiçbir delilin olmadığı ve tek
delilin hukuka aykırı yollarla elde edilmiş olduğu durumda ihlalin ağırlığına
bakılır. O delile ulaşırken gerçekleştirilen ihlal ile bu delilin kullanılması
suretiyle korunacak olan menfaat arasında mukayese yapılır.

*Eğer hukuka uygun bir delil mevcutsa, hiçbir şekilde hukuka aykırı delil
kullanılamaz.*

=== KESİN DELİLLER

Kesin deliller mahkemeye sunulduğu takdirde hakim HMK 189 uyarınca caiz
olduğuna kanaat getirdikten sonra bunların aksine karar veremez. *Hakim caiz
kesin delil ile bağlıdır*.

==== SENET

Senetin tanımı kanunda yapılmamıştır. Öğreti ve kararlar ışığında şöyle bir
tanım yapılabilir: _Senet, bir vakıanın doğruluğu hakkında tam bir bilgi ihtiva
eden, aleyhine kullanılacağı kişinin imzasını taşıyan yazılı ve fiziki bir
cisim halinde bulunan belgedir._

. *Senet yazılı olmalıdır.*
. *Senedin bir fiziki varlığı olmalıdır.*
. *Senet ilişkili olduğu vakıa hakkında tam bir bilgi ihtiva etmelidir.*
+
[CAUTION]
====
*Kambiyo senedi usul hukuku bakımından bir senet değildir!*

Kambiyo senedi asıl borç ilişkisi dikkate alınarak ancak aradaki illik bağı
koparılarak düzenlenir ve asıl borç ilişkisinden bağımsız ayrı bir kambiyo
ilişkisi kurulur. Kambiyo senedinde para borcunun hangi sebeple lehtara
ödeneceğine dair bir bilgi kural olarak bulunmaz.
====
. *Senet üzerinde aleyhine kullanılacak kişinin imzası bulunmalıdır.*

Senetler, düzenlenmesine resmi bir makamın katılıp katılmamasına göre ikiye
ayrılır:

. *Adi senet*: Düzenlenmesine hiçbir resmi makamın katılmadığı senetlerdir.
Kesin delile ispatı gereken vakıalar bakımından adi senet yeterlidir.
+
[caption=""]
.Adi senetlerin ispat gücü
====
*HMK 205*: (1) Mahkeme huzurunda ikrar olunan veya mahkemece inkâr edenden
sadır olduğu kabul edilen adi senetler, aksi ispat edilmedikçe kesin delil
sayılırlar.

(2) Usulüne göre güvenli elektronik imza ile oluşturulan elektronik veriler,
senet hükmündedir.

(3) Hâkim, mahkemeye delil olarak sunulan elektronik imzalı belgenin, güvenli
elektronik imza ile oluşturulmuş olup olmadığını resen inceler.
====
+
Bir adi senedin ispat aracı olarak kullanılmak istendiği bir davada, bu senedin
aleyhine kullanılacağı kişi senedin sahte olduğunu ileri sürerse, bu iddia bir
ön sorun olarak incelenir. Kanun sahtelik iddiasının nasıl inceleneceği
hususunda bir sıralama öngörmüştür.
+
[caption=""]
.Sahtelik incelemesi
====
*HMK 211*: (1) Bir belgenin sahteliğinin iddia edilmesi durumunda, bu hususta
karşı tarafın açıklamaları da dikkate alınarak, aşağıdaki sıra ile inceleme
yapılarak öncelikle karar verilir:

.. Hâkim, yazı veya imzayı inkâr eden tarafı isticvap ettikten sonra bir kanaat
edinememişse, huzurda bu kişiye yazı yazdırıp imza attırmak suretiyle elde
ettiği belge ve diğer delilleri değerlendirir. Hâkim, sahtelik konusunda başka
bir incelemeye gerek duymadan karar verebilecek durumda ise gerekçesini açıkça
belirtmek suretiyle, senedin sahteliği hakkında bir karar verir. İsticvap için
mahkemeye davet edilen taraf, belirtilen günde hazır bulunmadığı takdirde,
inkâr etmiş olduğu belgedeki yazı veya imzayı ikrar etmiş sayılır; bu husus
kendisine çıkartılacak davetiyede ayrıca ihtar edilir.
.. (a) bendi hükmüne göre yaptığı incelemeye rağmen, hâkimde sahtelik konusunda
kesin bir kanaat oluşmamışsa, bilirkişi incelemesine karar verir. Bilirkişi
incelemesinden önce, mevcutsa, o tarafa ait olan karşılaştırma yapmaya
elverişli yazı ve imzalar, ilgili yerlerden getirtilir. Bilirkişi, bu yazı ve
imzalarla, o mahkemede elde edilen yazı ve imzaları esas alarak inceleme yapar.
Bilirkişi, inceleme için gerekli görürse, kendi huzurunda tarafın yeniden yazı
yazması veya imza atmasını mahkemeden talep edebilir.
====
+
CAUTION: Sahtelik her türlü delille ispatlanabilir.
+
HMK 211 yerine sahtelik iddiasını ileri süren taraf bunun için bir dava da
açabilir. Bu dava hukuki niteliği itibariyle bir tespit davasıdır.
+
[caption=""]
.Yazı veya imza inkârı
====
*HMK 208*: (1) Taraflardan biri, kendisi tarafından düzenlendiği iddia edilen
bir belgedeki yazı veya imzayı inkâr etmek isterse, sahtelik iddiasında
bulunmalıdır; aksi hâlde belge, aleyhine delil olarak kullanılır.

(2) Bir belgenin sahteliği iddia edildiğinde, belgenin mahkemeye verildiği
tarih yazılıp mühürlenerek, saklanması için mahkemece gerekli tedbirler alınır.

(3) Bir belgenin sahteliğini iddia eden kimse, bunu aynı mahkemede ön sorun
şeklinde ileri sürebileceği gibi, bu konuda ayrı bir dava da açabilir.
====
+
Adi seneden ilişkin bir sahtelik iddiası ileri sürülürse, bu sahtelik iddiası
giderilmedikçe o senede dayanarak hüküm kurulması mümkün değildir.
+
[caption=""]
.Yazı veya imza inkârının sonucu
====
*HMK 209*: (1) Adi bir senetteki yazı veya imza inkâr edildiğinde, bu konuda
bir karar verilinceye kadar, o senet herhangi bir işleme esas alınamaz.
====
+
[caption=""]
.Sahtelik hakkında hukuk ve ceza mahkemesi kararlarının etkisi
====
*HMK 214*: (1) Belgenin sahte olmadığına dair hukuk mahkemesince verilen karar
kesinleştikten sonra, söz konusu belge hakkında ceza mahkemesinde de sahtelik
iddiası dinlenmez.

(2) Ceza mahkemesince belgeyi düzenleyen hakkında ceza verilmesine yer olmadığı
ya da beraat kararı verilmiş olması, hukuk mahkemesinin belgenin sahteliğini
incelemesini engellemez.
====
. *Resmi senet*: Düzenlenmesine bir resmi makamın katıldığı senetlerdir. Bu
resmi makam kanun tarafından kendisine söz konusu senedi düzenleme yetkisi
verilmiş makam olmalıdır. Kural olarak noterler resmiyet kazandırılması açıkça
başka bir makama bırakılmamış bütün işlemlere resmiyet kazandırmakla
görevlidirler.
+
Noterler senedi düzenleme ve taraflar tarafından düzenlenmiş senedi onaylama
olmak üzere iki tip işlem yapar. *Düzenleme biçimindeki resmi senetlerin
sahteliği ispatlanmadıkça aksi ispatlanamaz.* Onaylama biçimindeki resmi
senetlerin ise sahteliği de aksi de ispatlanabilir.
+
Resmi senedin sahteliği ileri sürülse de sahteliği ispatlanan dek bu senede
dayanmak mümkündür.
+
[caption=""]
.Yazı veya imza inkârının sonucu
====
*HMK 209*: (2) Resmî senetlerdeki yazı veya imza inkâr edildiğinde, senetteki
yazı veya imzanın sahteliği, ancak mahkeme kararıyla sabit olursa, bu senet
herhangi bir işleme esas alınamaz.
====
+
Düzenlenmesine resmi bir makamın katıldığı resmi senedin sahtelik iddiası
mutlaka ayrı bir dava ile ileri sürülmelidir.
+
[caption=""]
.Yazı veya imza inkârı
====
*HMK 208*: (4) Resmî bir senetteki yazı veya imzayı inkâr eden tarafın bu
iddiası, ancak ilgili evraka resmiyet kazandıran kişiyi de taraf göstererek
açacağı ayrı bir davada incelenip karara bağlanabilir. Asıl davaya bakan hâkim,
gerekirse bu konuda imza veya yazıyı inkâr eden tarafa, dava açması için iki
haftalık kesin bir süre verir.
====

IMPORTANT: Adi senet ile resmi senet arasında ispat gücü bakımından hiçbir fark
yoktur!

==== SENETLE İSPAT ZORUNLULUĞU

Senetle ispat, kesin delille ispat ifadesiyle eşanlamlıdır. Senetle ispatın
zorunlu olduğu hallerde delil olarak senet yerine diğer kesin deliller de
kullanılabilir.

[caption=""]
.Senetle ispat zorunluluğu
====
*HMK 200*: (1) Bir hakkın doğumu, düşürülmesi, devri, değiştirilmesi,
yenilenmesi, ertelenmesi, ikrarı ve itfası amacıyla yapılan hukuki işlemlerin,
yapıldıkları zamanki miktar veya değerleri ikibinbeşyüz Türk Lirasını geçtiği
takdirde senetle ispat olunması gerekir. Bu hukuki işlemlerin miktar veya
değeri ödeme veya borçtan kurtarma gibi bir nedenle ikibinbeşyüz Türk
Lirasından aşağı düşse bile senetsiz ispat olunamaz.

(2) Bu madde uyarınca senetle ispatı gereken hususlarda birinci fıkradaki
düzenleme hatırlatılarak karşı tarafın açık muvafakati hâlinde tanık
dinlenebilir.
====

HMK 200 ile senetle ispat zorunluluğu sadece **hukuki işlemler** ile
sınırlandırılmıştır. Buna göre kurulduğu andaki değeri 2500 TL'yi geçen hukuki
işlemlerin ispatı kesin delil ile yapılmak zorundadır. Ortada bir haksız fiil,
sebepsiz zenginleşme vs. varsa senetle ispat zorunluluğu söz konusu
olmayacaktır.

[caption=""]
.Senede karşı tanıkla ispat yasağı
====
*HMK 201*: (1) Senede bağlı her çeşit iddiaya karşı ileri sürülen ve senedin
hüküm ve kuvvetini ortadan kaldıracak veya azaltacak nitelikte bulunan hukuki
işlemler ikibinbeşyüz Türk Lirasından az bir miktara ait olsa bile tanıkla
ispat olunamaz.
====

HMK 201'e göre bir tarafın kesin delille ispatladığı bir vakıanın aksini hasmı
da ancak kesin delil ile ispatlayabilir.

IMPORTANT: Bir vakıa ile ilgili senetle ispat HMK 200 veya 201 uyarınca zorunlu
ise hakim bunu re'sen gözetmek zorundadır. Ancak bu zorunluluk hasmın
muvafakati ile aşılabildiği için *senetle ispat kuralı kamu düzenine ilişkin
değildir*.

Kurulduğu andaki değeri 2500 TL'yi geçmek kaydıyla senetle ispatı gereken
hukuki işlemler:

* İnançlı işlem
* Şufa hakkından feragat
* Sözleşmenin varlığı
* Muvazaa (taraflar bakımından senetle ispat zorunlu, üçüncü kişiler için değil)
* Sözleşme bedelinin ödenmiş olması
* Sözleşmenin rıza ile feshedilmiş olduğu
* Malın ne miktar için kararlaştırılmış olduğu

Yargıtay aşağıdaki örneklerin hukuki işlem değil hukuki fiil oldukları
gerekçesiyle kesin delille ispatının zorunlu olmadığını kabul etmektedir:

* Ayıp ihbarının uygun süre içerisinde yapılıp yapılmadığı
* Temerrüt ihtarının yapılıp yapılmadığı
* Zilyetliğin devri
* Vekaletin kötüye kullanılıp kullanılmadığı

==== KESİN DELİLLE İSPAT KURALININ İSTİSNALARI

Kesin delille ispatın beş tane istisnası olduğu kabul edilir:

. *Delil başlangıcı*: Senetle ispatın zorunlu olduğu hallerde sadece delil
başlangıcı yeterli değildir. Delil başlangıcı ancak takdiri bir delil ile
desteklendiği takdirde kesin delil yerine geçer.
+
[caption=""]
.Delil başlangıcı
====
*HMK 202*: (1) Senetle ispat zorunluluğu bulunan hâllerde delil başlangıcı
bulunursa tanık dinlenebilir.

(2) Delil başlangıcı, iddia konusu hukuki işlemin tamamen ispatına yeterli
olmamakla birlikte, söz konusu hukuki işlemi muhtemel gösteren ve kendisine
karşı ileri sürülen kimse veya temsilcisi tarafından verilmiş veya gönderilmiş
belgedir.
====
+
Delil başlangıcı her halükarda bir belgedir. Ancak bu belge tarafa hasım veya
onun temsilcisi tarafından verilmiş olmalı ve ispatı gereken vakıayı tam olarak
ispatlamasa da muhtemel göstermelidir.
+
TIP: Bütün unsurları taşıyan bir senedin fotoğrafı bir delil başlangıcıdır.
. *Senet alınmasında manevi imkansızlık halleri*: Bazı hallerde senet
alınmasında manevi imkansızlık bulunduğu kabul edilir.
+
[caption=""]
.Senetle ispat zorunluluğunun istisnaları
====
*HMK 203*: (1) Aşağıdaki hâllerde tanık dinlenebilir:

.. *Altsoy ve üstsoy, kardeşler, eşler, kayınbaba, kaynana ile gelin ve damat
arasındaki işlemler.*
.. *İşin niteliğine ve tarafların durumlarına göre, senede bağlanmaması teamül
olarak yerleşmiş bulunan hukuki işlemler.*
.. Yangın, deniz kazası, deprem gibi senet alınmasında imkânsızlık veya
olağanüstü güçlük bulunan hâllerde yapılan işlemler.
.. Hukuki işlemlerde irade bozukluğu ile aşırı yararlanma iddiaları.
.. Hukuki işlemlere ve senetlere karşı üçüncü kişilerin muvazaa iddiaları.
.. Bir senedin sahibi elinde beklenmeyen bir olay veya zorlayıcı bir nedenle
yahut usulüne göre teslim edilen bir memur elinde veya noterlikte herhangi bir
şekilde kaybolduğu kanısını kuvvetlendirecek delil veya emarelerin bulunması
hâli.
====
+
Kanun koyucu (a) bendindeki belirlemeyi sınırlı olarak yapmıştır; genişletmeye
imkan yoktur. Ancak (b) bendi genişletmeye müsaittir.
+
TIP: HMK 203'ün (a) ve (b) bentleri sadece HMK 200'ün istisnasıdır. Örneğin bir baba
oğluna borç para verirken senet almışsa çocuk da parayı iade ederken makbuz
almalıdır.
. *Senet alınmasında maddi imkansızlık halleri*: Bazı hallerde senet
alınmasında maddi imkansızlık bulunduğu kabul edilir.
+
[caption=""]
.Senetle ispat zorunluluğunun istisnaları
====
*HMK 203*: (1) Aşağıdaki hâllerde tanık dinlenebilir:

.. Altsoy ve üstsoy, kardeşler, eşler, kayınbaba, kaynana ile gelin ve damat
arasındaki işlemler.
.. İşin niteliğine ve tarafların durumlarına göre, senede bağlanmaması teamül
olarak yerleşmiş bulunan hukuki işlemler.
.. *Yangın, deniz kazası, deprem gibi senet alınmasında imkânsızlık veya
olağanüstü güçlük bulunan hâllerde yapılan işlemler.*
.. *Hukuki işlemlerde irade bozukluğu ile aşırı yararlanma iddiaları.*
.. *Hukuki işlemlere ve senetlere karşı üçüncü kişilerin muvazaa iddiaları.*
.. Bir senedin sahibi elinde beklenmeyen bir olay veya zorlayıcı bir nedenle
yahut usulüne göre teslim edilen bir memur elinde veya noterlikte herhangi bir
şekilde kaybolduğu kanısını kuvvetlendirecek delil veya emarelerin bulunması
hâli.
====
+
HMK 203'ün (c), (d) ve (e) bentleri hem HMK 200'ün hem de 201'in
istisnalarıdır.
. *Senedin kaybolması*: HMK 203/f'de düzenlenmiştir. Hem HMK 200'ün hem de HMK
201'in istinasıdır.
. *Delil sözleşmesi*: Taraflar aralarında yapacakları bir sözleşme ile senetle
ispat zorunluluğunu kaldırabilir ya da senetle ispatı zorunlu olmayan bir vakıa
için kesin delille ispat zorunluluğu getirebilirler.
+
[caption=""]
.Delil sözleşmesi
====
*HMK 193*: (1) Taraflar yazılı olarak veya mahkeme önünde tutanağa geçirilecek
imzalı beyanlarıyla kanunda belirli delillerle ispatı öngörülen vakıaların
başka delil veya delillerle ispatını kararlaştırabilecekleri gibi; belirli
delillerle ispatı öngörülmeyen vakıaların da sadece belirli delil veya
delillerle ispatını kabul edebilirler.

(2) Taraflardan birinin ispat hakkının kullanımını imkânsız kılan veya
fevkalade güçleştiren delil sözleşmeleri geçersizdir.
====

==== SENEDİN İBRAZI

[caption=""]
.Mahkemece belge aslının istenmesi ve geri verilmesi
====
*HMK 216*: (1) Belgenin sadece örneğinin mahkemeye verildiği durumlarda,
mahkeme kendiliğinden veya taraflardan birinin talebi üzerine belgenin aslının
verilmesini de isteyebilir.

(2) Belgenin aslını elinde bulunduran taraf, üçüncü kişi veya resmî makamlar,
istenmesi hâlinde bunu mahkemeye vermek zorundadır.

(3) Mahkeme, belge aslının verilmesi durumunda, belgenin saklanması için
gerekli tedbirleri alır veya istendiğinde tekrar verilmek üzere belgeyi ibraz
edene geri verebilir.

(4) Taraflardan biri elindeki belgenin aslını mahkemeye verirse, bu belgenin
geri verilmesini talep edebilir. Bu takdirde hâkim, belgenin aslının verilip
verilmeyeceğine karar verir. Geri verilmesine karar verildiğinde, aslına uygun
olduğu mahkeme mührü ve yazı işleri müdürünün imzasıyla onanmış örneği dosyaya
konur.
====

[caption=""]
.Belge aslının ibrazı usulü
====
*HMK 217*: (1) Bir kişi veya kurumun elinde bulunup mahkemeye teslim edilmesi
gereken belgenin aslı istendiğinde, kişi veya kurumun bulunduğu ya da belgenin
teslim edileceği yerdeki asliye mahkemesi tarafından örneği onaylanarak aslı
mahkemeye gönderilir yahut teslim edilir.

(2) Mahkemece onaylanmış belge örneği, aslı gibi hüküm ifade eder.
====

[caption=""]
.Belgenin yerinde incelenmesi
====
*HMK 218*: (1) Mahkemeye getirilmesi zor veya sakıncalı olan belgeler, hâkim
veya görevlendireceği bilirkişi tarafından yerinde incelenir ya da bu
belgelerin mahkemeye sunulmuş örnekleri asıllarıyla karşılaştırılır. İnceleme
sonunda bir tutanak düzenlenir ve gerekli görülürse uygun teknik araçlarla
belgenin aslı kaydedilir.

(2) Mahkemenin bu yöndeki emrinin yerine getirilmesine haklı bir sebep
olmaksızın engel olunması hâlinde hâkim tarafından, engel olan kişi hakkında
sebep olduğu giderlere ve beşyüz Türk Lirasından beşbin Türk Lirasına kadar
disiplin para cezasına hükmolunur. Gerektiğinde zor kullanılmasına da karar
verilebilir.
====

[caption=""]
.Tarafların belgeleri ibrazı zorunluluğu
====
*HMK 219*: (1) Taraflar, kendilerinin veya karşı tarafın delil olarak
dayandıkları ve ellerinde bulunan tüm belgeleri mahkemeye ibraz etmek
zorundadırlar. Elektronik belgeler ise belgenin çıktısı alınarak ve talep
edildiğinde incelemeye elverişli şekilde elektronik ortama kaydedilerek
mahkemeye ibraz edilir.

(2) Ticari defterler gibi devamlı kullanılan belgelerin sadece ilgili
kısımlarının onaylı örnekleri mahkemeye ibraz edilebilir.
====

[caption=""]
.Tarafın belgeyi ibraz etmemesi
====
*HMK 220*: (1) İbrazı istenen belgenin, ileri sürülen hususun ispatı için
zorunlu ve bu isteğin kanuna uygun olduğuna mahkemece kanaat getirildiği ve
karşı taraf da bu belgenin elinde olduğunu ikrar ettiği veya ileri sürülen
talep üzerine sükut ettiği yahut belgenin var olduğu resmî bir kayıtla
anlaşıldığı veya başka bir belgede ikrar olunduğu takdirde, mahkeme bu belgenin
ibrazı için kesin bir süre verir.

(2) Mahkemece, ibrazı istenen belgenin elinde bulunduğunu inkâr eden tarafa,
böyle bir belgenin elinde bulunmadığına, özenle aradığı hâlde bulamadığına ve
nerede olduğunu da bilmediğine ilişkin yemin teklif edilir.

(3) Belgeyi ibraz etmesine karar verilen taraf, kendisine verilen sürede
belgeyi ibraz etmez ve aynı sürede, delilleriyle birlikte ibraz etmemesi
hakkında kabul edilebilir bir mazeret göstermez ya da belgenin elinde
bulunduğunu inkâr eder ve teklif edilen yemini kabul veya icra etmezse,
mahkeme, duruma göre belgenin içeriği konusunda diğer tarafın beyanını kabul
edebilir.
====

[caption=""]
.Üçüncü kişinin belgeyi ibraz etmemesi
====
*HMK 221*: (1) Mahkeme, üçüncü kişi veya kurumun elinde bulunan bir belgenin
taraflarca ileri sürülen hususun ispatı için zorunlu olduğuna karar verirse, bu
belgenin ibrazını emreder.

(2) Belgeyi ibraz etmesine karar verilen herkes, elindeki belgeyi ibraz etmek;
belgeyi ibraz edememesi hâlinde ise bunun sebebini delilleri ile birlikte
açıklamak zorundadır. Mahkeme yapılan açıklamayı yeterli görmezse, bu kimseyi
tanık olarak dinleyebilir.

(3) Belgeyi ibraz zorunda olanlar, tanıklıktan çekinmeye ilişkin hükümlere
göre, belgeyi ibrazdan veya bu konudaki tanıklıktan çekinebilirler. Belgeyi
ibraz veya bu konuda tanıklık yapmak zorunda olanlar hakkında, tanıklara
ilişkin hükümler uygulanır.
====

==== TİCARİ DEFTERLER

[caption=""]
.Ticari defterlerin ibrazı ve delil olması
====
*HMK 222*: (1) Mahkeme, ticari davalarda tarafların ticari defterlerinin
ibrazına kendiliğinden veya taraflardan birinin talebi üzerine karar verebilir.

(2) Ticari defterlerin, ticari davalarda delil olarak kabul edilebilmesi için,
kanuna göre eksiksiz ve usulüne uygun olarak tutulmuş, açılış ve kapanış
onayları yaptırılmış ve defter kayıtlarının birbirini doğrulamış olması
şarttır.

(3) İkinci fıkrada belirtilen şartlara uygun olarak tutulan ticari defter
kayıtlarının sahibi ve halefleri lehine delil olarak kabul edilebilmesi için,
diğer tarafın aynı şartlara uygun olarak tutulmuş ticari defterlerindeki
kayıtların bunlara aykırı olmaması veya ilgili hususta hiç bir kayıt içermemesi
yahut defter kayıtlarının aksinin senet veya diğer kesin delillerle
ispatlanmamış olması gerekir. Bu şartlara uygun olarak tutulan defterlerdeki
sahibi lehine ve aleyhine olan kayıtlar birbirinden ayrılamaz.

(4) Açılış veya kapanış onayları bulunmayan ve içerdiği kayıtlar birbirini
doğrulamayan ticari defter kayıtları, sahibi aleyhine delil olur.

(5) Taraflardan biri tacir olmasa dahi, tacir olan diğer tarafın ticari
defterlerindeki kayıtları kabul edeceğini belirtir; ancak, karşı taraf
defterlerini ibrazdan kaçınırsa, ibrazı talep eden taraf iddiasını ispat etmiş
sayılır.
====

Ticari defterin sahibi lehine delil olması için:

* Davanın iki tarafı tacir olmalıdır.
* Uyuşmazlık iki tarafın ticari işletmesi ile ilgili olmalıdır.
* Kullanılacak defter Ticaret Kanunu'nda yer alan ticari defterlerden
olmalıdır.
* Defter eksiksiz ve usule uygun olmalıdır.
* Hasmin ticari defter kayıtlarının buna uygun olması gerekir.

==== YEMİN

*Yemin*, bir vakıaya ilişkin ispat yükü kendisine düşen tarafın bunu karşı
taraftan kutsal saydığı değerler üzerine yemin edip vakıa ile ilgili
bildiklerini açıklamasını talep ederek ispatlamak istemesidir.

Kullanılabilecek başka bir delil olsa bile yemin deliline başvurulabilir.
Usulüne uygun olarak yemin deliline müracaat edilir ve yerine getirilirse yemin
kesin delil teşkil eder.

[caption=""]
.Yeminin konusu
====
*HMK 225*: (1) Yeminin konusu, davanın çözümü bakımından önem taşıyan,
çekişmeli olan ve kişinin kendisinden kaynaklanan vakıalardır. Bir kimsenin bir
hususu bilmesi onun kendisinden kaynaklanan vakıa sayılır.
====

[caption=""]
.Yemine konu olamayacak vakıalar
====
*HMK 226*: (1) Aşağıdaki hususlar yemine konu olamaz:

.. Tarafların üzerinde serbestçe tasarruf edemeyeceği vakıalar.
.. Bir işlemin geçerliliği için, kanunen iki tarafın irade açıklamalarının
yeterli görülmediği hâller.
 . Yemin edecek kimsenin namus ve onurunu etkileyecek veya onu ceza
 soruşturması ya da kovuşturması ile karşı karşıya bırakacak vakıalar.
====

[caption=""]
.Yemini yerine getirecek kimseler
====
*HMK 232*: (1) Yemin, tarafa teklif olunur ve tarafça eda yahut iade olunur.

(2) Taraflardan biri tüzel kişi yahut ergin olmayan veya kısıtlı bir kimse ise
onlar adına yapılmış bir işleme ilişkin vakıanın ispatı için yemin, tüzel
kişiyi temsile yetkili kişi veya organ yahut kanuni mümessil tarafından eda ya
da iade olunabilir.

(3) Ergin olmayan veya kısıtlı kimselere bizzat dava hakkı tanınan hâllerde,
ikinci fıkra hükmü uygulanmaz.
====

NOTE: Yakın tarihli bir içtihadı birleştirme kararına göre: "_Bir vakıanın
ispatına yönelik olarak açıkça yemin deliline dayanılmamışsa hakim, ilgili
taraf vakıa ispatsız kaldığında yemin delilini hatırlatmak zorunda değildir._"

HMK 74'e göre dava vekil aracılığıyla yürütülüyorsa yemin deliline müracaat
için özel yetki verilmesi şarttır.

[caption=""]
.Davaya vekâlette özel yetki verilmesini gerektiren hâller
====
*HMK 74*: (1) Açıkça yetki verilmemiş ise vekil; sulh olamaz, hâkimi
reddedemez, davanın tamamını ıslah edemez, *yemin teklif edemez, yemini kabul,
iade veya reddedemez,* başkasını tevkil edemez, haczi kaldıramaz, müvekkilinin
iflasını isteyemez, tahkim ve hakem sözleşmesi yapamaz, konkordato veya sermaye
şirketleri ve kooperatiflerin uzlaşma yoluyla yeniden yapılandırılması
teklifinde bulunamaz ve bunlara muvafakat veremez, alternatif uyuşmazlık çözüm
yollarına başvuramaz, davadan veya kanun yollarından feragat edemez, karşı
tarafı ibra ve davasını kabul edemez, yargılamanın iadesi yoluna gidemez,
hâkimlerin fiilleri sebebiyle Devlet aleyhine tazminat davası açamaz, hangileri
hakkında yetki verildiği açıklanmadıkça kişiye sıkı sıkıya bağlı haklarla
ilgili davaları açamaz ve takip edemez.
====

[caption=""]
.Yemin teklifi
====
*HMK 227*: (1) Uyuşmazlık konusu vakıanın ispatı için yeminden başka delili
olduğunu beyan etmiş olan taraf dahi yemin teklif edebilir.

(2) Yemin teklif olunan kimse, yemini edaya hazır olduğunu bildirdikten sonra,
diğer taraf teklifinden vazgeçerek başka bir delile dayanamaz ve yeni bir delil
de gösteremez.
====

[caption=""]
.Yemine davet
====
*HMK 228*: (1) Yemin teklif edilen kimse, duruşmada bizzat hazır bulunmadığı
takdirde, kendisine yemin için bir davetiye çıkarılır.

(2) Yemin davetiyesine, yemine konu hususlar hakkında sorulacak sorular ile
geçerli bir özrü olmaksızın yemin için tayin olunan gün ve saatte mahkemeye
bizzat gelmediği veya gelip de yemini iade etmediği yahut yemini eda etmekten
kaçındığı takdirde, yemin konusu vakıaları ikrar etmiş sayılacağı yazılır.
====

[caption=""]
.Yemin etmemenin sonuçları
====
*HMK 229*: (1) Yemin için davet edilen kimse, tayin edilen gün ve saatte
mahkemede geçerli bir özrü olmaksızın bizzat hazır bulunmaz yahut hazır bulunup
da yemini iade etmez ya da yemini eda etmekten kaçınırsa yemin konusu vakıaları
ikrar etmiş sayılır.

(2) Kendisine yemin iade olunan kimse, yemin etmekten kaçınırsa yemin konusu
vakıa ispat edilememiş sayılır.
====

[caption=""]
.Yeminin şekli
====
*HMK 233*: (1) Yemin, mahkeme huzurunda eda olunur.

(2) Hâkim, yeminin icrasından önce yemin edecek kimseye, hangi konuda yemin
edeceğini açıklar, yeminin anlam ve önemini anlatır ve yalan yere yemin etmesi
hâlinde cezalandırılacağı hususunda dikkatini çeker.

(3) Yemin edecek kimse, yemin konusunun yeterli açıklıkta olmadığını ileri
sürerse; hâkim, karşı tarafın görüşünü aldıktan sonra derhâl bu konuda kararını
verir.

(4) Sonra "Size sorulan sorular hakkında, gerçeğe uygun cevap vereceğinize ve
hiçbir şey saklamayacağınıza namusunuz, şerefiniz ve kutsal saydığınız bütün
inanç ve değerler üzerine yemin eder misiniz?" diye sorar. O kimse de "Bana
sorulan sorular hakkında gerçeğe uygun cevap vereceğime ve hiçbir şey
saklamayacağıma namusum, şerefim ve kutsal saydığım bütün inanç ve değerlerim
üzerine yemin ediyorum." demekle yemin eda edilmiş sayılır.

(5) Yemin eda edilirken, hâkim de dâhil olmak üzere hazır bulunan herkes ayağa
kalkar.
====

[caption=""]
.Yemin konusunun açıklattırılması
====
*HMK 237*: (1) Hâkim, eksik olan noktaları tamamlamak veya açık olmayan
hususları aydınlatmak için yeminin konusu ile bağlantılı gördüğü soruları yemin
eden kimseye sorabilir.
====

[caption=""]
.Yemin tutanağının düzenlenmesi
====
*HMK 238*: (1) Hâkim, yemin eden kimsenin beyanını dinleyip tutanağa geçirir ve
yazılanları yüksek sesle huzurunda okur; beyanında ısrar edip etmediğini sorar
ve verilen cevabı tutanağa kaydeder.
====

Yemin tutanağı düzenlendikten sonra yemin kendi aleyhine olan tarafın
yapabileceği tek şey yalan yere yemin iddiasıyla bir ceza soruşturması
başlatmaktır. Ceza yargılamasında kişinin yalan yere yemin ettiği
ispatlanabilirse hukuk yargılaması yenilenecektir. Ancak ceza davası hukuk
davası için bekletici mesele yapılamaz.

[caption=""]
.Yalan yere yemin iddiası
====
*HMK 239*: (1) Yemin eda edildikten sonra, yalan yere yemin nedeniyle açılan
ceza davası, esas dava bakımından bekletici sorun yapılamaz.
====

HMK 375, yalan yere yemin suçundan ceza mahkemesindeki mahkumiyet kararına
dayanarak hukuk mahkemesinde verilen kararın bozulabilmesi için ceza
mahkemesinde verilen kararın kesin yahut yazılı delile dayanmış olmasını
aramaktadır. Ceza mahkemesinde tanıkla ispat edilmesi durumunda, hukuk
davasında verilen karar geçerliliğini korur.

[caption=""]
.Ölüm veya fiil ehliyetinin kaybı
====
*HMK 231*: (1) Yemin edecek taraf gerçek kişi olup, yeminden evvel ölür veya
fiil ehliyetini kaybederse yemin teklif edilmemiş sayılır.
====

==== KESİN HÜKÜM

Taraflar ve vakıalar aynı ise ve aynı dava konusu daha önce karara bağlanmış
ise onun yeniden mahkeme önüne getirilmesine HMK 114 engeldir. Ancak tarafları
ve dava sebebi aynı ama dava konusunun farklı olduğu hallerde ilk davada
verilen karar ikinci dava için kesin hüküm oluşturmaz. Böyle bir durumda ortak
vakıalar bakımından ilk davada verilen hüküm kesin delil teşkil eder.

*Tarafları ve dava sebebi aynı olan hukuki ilişkide daha önce verilen karar,
ikinci kez aynı hukuki ilişki ve aynı taraflar arasında açılan davada ortak
vakıalar bakımından kesin hüküm oluşturmuyorsa kesin delil oluşturur.*

[NOTE]
====
Vakıalar aynı olmakla birlikte tarafların farklı olduğu davalardan ilkinde
verilen ve kesinleşen hüküm ikinci davada -ortak vakıalar bakımından- kesin
delil teşkil eder mi?

Yargıtay'a göre ilk davada verilen karar bir kenara bırakılamaz. Bu karar
ikinci dava için kesin delil olmasa da **güçlü delil**dir. Aksi ispatlanmadıkça
ilk davada verilen karar, tarafların farklı olduğu ikinci davada aynı hukuki
ilişkiden kaynaklanan bu vakıaya ilişkin dikkate alınmak durumundadır.

Doktrinde Yargıtay'ın bu görüşü sert bir şekilde eleştirilmektedir. Doktrinde
göre ilk davada verilen karar hiçbir şekilde ikinci davada kullanılamaz. Zira
ikinci davanın tarafı ilk davada taraf değildir ve dolayısıyla ilk davada
verilen karara hiçbir şekilde etki etme imkanı yoktur. Bu kararın delil olarak
kullanılması hukuki dinlenilme hakkının ihlalidir.
====

=== TAKDİRİ DELİLLER

==== BELGE

[caption=""]
.Belge
====
*HMK 199*: (1) Uyuşmazlık konusu vakıaları ispata elverişli yazılı veya basılı
metin, senet, çizim, plan, kroki, fotoğraf, film, görüntü veya ses kaydı gibi
veriler ile elektronik ortamdaki veriler ve bunlara benzer bilgi taşıyıcıları
bu Kanuna göre belgedir.
====

==== TANIK

*Tanık*, uyuşmazlığın çözümü bakımından önem taşıyan bir vakıa hakkında duyu
organlarıyla edindiği bilgiyi daha sonra mahkemeye sözlü olarak aktaran
kişidir.

[caption=""]
.Tanık gösterme şekli
====
*HMK 240*: (1) Davada taraf olmayan kişiler tanık olarak gösterilebilir.

(2) Tanık gösteren taraf, tanık dinletmek istediği vakıayı ve dinlenilmesi
istenen tanıkların adı ve soyadı ile tebliğe elverişli adreslerini içeren
listeyi mahkemeye sunar. Bu listede gösterilmemiş olan kimseler tanık olarak
dinlenemez ve ikinci bir liste verilemez.

(3) Tanık listesinde adres gösterilmemiş veya gösterilen adreste tanık
bulunamamışsa, tarafa adres göstermesi için, işin niteliğine uygun kesin süre
verilir. Bu süre içinde adres gösterilmez veya gösterilen yeni adres de doğru
değilse, bu tanığın dinlenilmesinden vazgeçilmiş sayılır.
====

Taraf olmadığı sürece ayırt etme gücü olan herkes tanık olabilir. Herhangi bir
yasaklılık hali söz konusu değildir. Ancak tanığın tarafla ilişkisi, kişisel
özellikleri hakimin takdiri açısından önemlidir.

TIP: İhtiyari dava arkadaşları birbirlerine tanıklık yapabilirler. Yine feri
müdahil, tarafın avukatı tanık olabilir. Ancak yasal temsilci tanık olamaz.

Bir tüzel kişi, kendi bünyesinde, özellikle yönetim organını oluşturan kişileri
tanık olarak gösteremez. Böyle bir kişi tanık olarak gösterilmiş ise istinaf
sebebidir. HMK 240/1 emredici bir düzenlemedir.

Tanık deliline müracaat için bu mutlaka dilekçelerde belirtilmelidir. Dilekçede
sadece ilgili vakıanın tanık ile ispat edileceğini belirtmek yeterlidir.
Tahkikat aşamasında hakim ilgili vakıanın ispat zamanı geldiğinde taraftan
tanık listesini vermesini isteyecektir. HMK 204/2 uyarınca *aynı vakıa hakkında
sadece bir tane tanık listesi verilebilir*.

Tanık sayısında bir sınırlama yoktur.

[caption=""]
.Tanıklardan bir kısmının dinlenilmesiyle yetinilmesi
====
*HMK 241*: (1) Mahkeme, gösterilen tanıklardan bir kısmının tanıklığı ile ispat
edilmek istenen husus hakkında yeter derecede bilgi edindiği takdirde, geri
kalanların dinlenilmemesine karar verebilir.
====

Tanık, duruşma tarihinden en az bir hafta önce meşruhatlı davetiye ile davet
edilmelidir. Bu süreye riayet edilmemesi istinaf sebebidir.

Meşruhatlı davetiyede;

.. Tanığın adı, soyadı ve açık adresi,
.. Tarafların ad ve soyadları,
.. Tanıklık yapacağı konu,
.. Hazır bulunması gereken yer, gün ve saat,
.. Gelmemesinin veya gelmesine rağmen tanıklıktan ya da yemin etmekten
çekinmesinin hukuki ve cezai sonuçları

bulunur.

[caption=""]
.Tanığın davet edilmesi
====
*HMK 243*: (1) Tanık davetiye ile çağrılır. Ancak, davetiye gönderilmeden
taraflarca hazır bulundurulan tanık da dinlenir.  Şu kadar ki, tanık listesi
için kesin süre verildiği ve dinlenme gününün belirlendiği hâllerde, liste
verilmemiş olsa dahi taraf, o duruşmada hazır bulundurursa tanıklar dinlenir.

(2) Davetiyenin duruşma gününden en az bir hafta önce tebliğ edilmiş olması
gerekir. Acele hâllerde tanığın daha önce gelmesine karar verilebilir.

(3) Tanığı davet, gerektiğinde telefon, faks, elektronik posta gibi araçlardan
yararlanılmak suretiyle de yapılabilir. Ancak, davete rağmen gelmemeye bağlanan
sonuçlar, bu durumda uygulanmaz.
====

[caption=""]
.Çağrıya uyma zorunluluğu
====
*HMK 245*: (1) Kanunda gösterilen hükümler saklı kalmak üzere, tanıklık için
çağrılan herkes gelmek zorundadır. Usulüne uygun olarak çağrıldığı hâlde
mazeret bildirmeksizin gelmeyen tanık zorla getirtilir, gelmemesinin sebep
olduğu giderlere ve beşyüz Türk Lirasına kadar disiplin para cezasına
hükmolunur. Zorla getirtilen tanık, evvelce gelmemesini haklı gösterecek
sebepleri sonradan bildirirse, aleyhine hükmedilen giderler ve disiplin para
cezası kaldırılır.
====

Tanık mutlaka hakim huzurunda dinlenmelidir. Bu doğrudanlık ilkesinin
gereğidir. İstisnaen gerekli görülürse tanığa soru kağıdı gönderilerek bunları
yazılı cevaplaması da talep edilebilr. Gerekli halin varlığı taraf tarafından
ispat edilebileceği gibi hakim de re'sen takdir edebilir.

[caption=""]
.Tanığa soru kâğıdı gönderilmesi
====
*HMK 246*: (1) Hâkim gerekli görülen hâllerde, sözlü olarak dinlenmesi yerine,
belirlenecek süre içinde cevaplarını yazılı olarak bildirmesi için tanığa soru
kâğıdı gönderilmesine karar verebilir. Bu şekilde işlem yapılması, tanığın
vereceği cevabın hükme yeterli olup olmadığı hususunu hâkimin takdir etmesine
engel olamaz. Hâkim, verilen yazılı cevapların yetersiz olması hâlinde, tanığı
dinlemek üzere davet edebilir.
====

Tanık olarak çağrılmış kişinin HMK 245'teki müeyyideden kurtulabilmesi için
kanunda açıkça sayılmış çekinme hallerinden biri gerçekleşmelidir.

[caption=""]
.Tanıklıktan çekinme hakkı
====
*HMK 247*: (1) Kanunda açıkça belirtilmiş olan hâllerde, tanık olarak çağrılmış
bulunan kimse, tanıklık yapmaktan çekinebilir.

(2) Kişisel nedenlerle tanıklıktan çekinme sebeplerinin varlığı hâlinde, hâkim
tanık olarak çağrılmış kimsenin çekinme hakkı bulunduğunu önceden hatırlatır.
====

Çekinme halleri sınırlı sayıdadır. HMK 248, 249 ve 250 dışında bir sebeple
tanıklıktan çekinilemez.

[caption=""]
.Kişisel nedenlerle tanıklıktan çekinme
====
*HMK 248*: (1) Aşağıdaki kimseler tanıklıktan çekinebilirler:

.. İki taraftan birinin nişanlısı.
.. Evlilik bağı ortadan kalkmış olsa dahi iki taraftan birinin eşi.
.. Kendisi veya eşinin altsoy veya üstsoyu.
.. Taraflardan biri ile arasında evlatlık bağı bulunanlar.
.. Üçüncü derece de dâhil olmak üzere kan veya kendisini oluşturan evlilik bağı
ortadan kalkmış olsa dahi kayın hısımları.
.. Koruyucu aile ve onların çocukları ile koruma altına alınan çocuk.
====

[caption=""]
.Sır nedeniyle tanıklıktan çekinme
====
*HMK 249*: (1) Kanun gereği sır olarak korunması gereken bilgiler hakkında
tanıklığına başvurulacak kimseler, bu hususlar hakkında tanıklıktan
çekinebilirler. Ancak, 19/3/1969 tarihli ve 1136 sayılı Avukatlık Kanunu hükmü
saklı kalmak üzere sır sahibi tarafından sırrın açıklanmasına izin verildiği
takdirde, bu kimseler tanıklıktan çekinemezler.
====

[caption=""]
.Menfaat ihlali tehlikesi nedeniyle tanıklıktan çekinme
====
*HMK 250*: (1) Aşağıdaki hâllerde tanıklıktan çekinilebilir:

.. Tanığın beyanı kendisine veya 248 inci maddede yazılı kimselerden birine
doğrudan doğruya maddi bir zarar verecekse.
.. Tanığın beyanı kendisinin veya 248 inci maddede yazılı kimselerden birinin
şeref veya itibarını ihlal edecek ya da ceza soruşturmasına veya kovuşturmasına
sebep olacaksa.
.. Tanığın beyanı, meslek veya sanatına ait olan sırların ortaya çıkmasına
sebebiyet verecekse.
====

[caption=""]
.Tanıklıktan çekinme hakkının istisnaları
====
*HMK 251*: (1) 248 ve 249 uncu maddeler ile 250 nci maddenin (a) bendindeki
hâllerde;

.. Bir hukuki işlemin yapılması sırasında tanık olarak bulundurulmuş olan kimse
o işlemin esası ve içeriği hakkında,
.. Aile bireylerinin doğum, ölüm veya evlenmelerinden kaynaklanan olaylar
hakkında,
.. Aile bireyleri arasında, ailevi ilişkilerden kaynaklanan mali uyuşmazlıklara
ilişkin vakıalar hakkında,
.. Taraflardan birinin hukuki selefi veya temsilcisi olarak kendisinin yaptığı
işler hakkında, tanıklıktan çekinilemez.
====

Tanıklıktan çekinecek kişi en geç duruşma günü ve saatinde huzurda bulunup
tanıklıktan çekinme sebebini ve bunu ispata yarayacak herhangi bir delili
sunmalıdır. Bu mahkemece bir ön sorun olarak incelenir.

[caption=""]
.Çekinme sebeplerinin bildirilmesi ve incelenmesi
====
*HMK 252*: (1) Tanıklıktan çekinen kimse, çekinme sebebini ve bu sebebi haklı
gösterecek delilini, dinleneceği günden önce yazılı veya davet edildiği
duruşmada sözlü olarak bildirmek zorundadır.

(2) Çekinme sebeplerini ve bunun dayanaklarını önceden bildirmiş olan tanık
belli günde mahkemeye gelmek zorunda değildir.

(3) Mahkeme, duruşmada bulunan tarafları dinledikten sonra tanıklıktan
çekinmenin haklı olup olmadığına karar verir.
====

Tanık dinleneceği husus ile ilgili aydınlatılmalıdır. Buna riayet edilmemesi
tanık delilinin dikkate alınmasını engeller. Buna riayet edilmeden oluşturulmuş
tanık deliline dayanarak karar verilmiş ise istinaf sebebidir.

[caption=""]
.Tanığın bilgilendirilmesi
====
*HMK 260*: (1) Tanık dinlenmeden önce hakkında tanıklık yapacağı olayla ilgili
olarak, hâkim tarafından kendisine bilgi verilir ve tanıklık edeceği konulara
ilişkin bildiklerini söylemesi istenir.
====

==== İSTİCVAP

====
*HMK 169*: (1) Mahkeme, kendiliğinden veya talep üzerine taraflardan her
birinin isticvabına karar verebilir.

(2) İsticvap, davanın temelini oluşturan vakıalar ve onunla ilişkisi bulunan
hususlar hakkında olur.
====

İsticvap hakimin usuli işlemidir. Tarafların talebi ile ya da re'sen
taraflardan birinin isticvapına karar verebilir.

Hakim re'sen isticvapa karar verirse hangi vakıaların isticvap faaliyetine konu
teşkil edeceğini bir ara kararda belirtmelidir.

İsticvap, davanın taraflarından ikrar yönünde irade beyanı almak amacıyla
yapılır. Bu faaliyet duruşma esnasında ve tahkikat aşamasında gerçekleşebilir.
Hakim doğrudan tarafla muhatap olacaktır, taraf vekilinin isticvapı mümkün
değildir.

Tüzel kişinin isticvapı mümkündür. Tüzel kişiyi temsil edecek kişi isticvap
olunur.

[caption=""]
.İsticvap olunacak kişilerin belirlenmesi
====
*HMK 170*: (1) Tüzel kişiler adına, temsil yetkisine sahip kimseler isticvap
olunur.

(2) Ergin olmayan veya kısıtlı bir kimse adına yapılmış bir işleme ilişkin
olarak, o kişinin kanuni mümessili isticvap olunur.

(3) Ergin olmayan veya kısıtlı kimselere bizzat dava hakkı tanınan hâllerde,
ikinci fıkra hükmü uygulanmaz.
====

İsticvap olunacak kişiye davetiye gönderilme şartı vardır. Davetiyede isticvapa
çağrıldığı duruşmaya gelmez ve mazeret bildirmezse kendisine sorulacak
vakıaları ikrar etmiş sayılacağı bildirilmelidir. Bu şekilde meşruhatlı bir
davetiye gönderilmezse ikrar sonucu doğmaz.

[caption=""]
.İsticvap olunacak tarafın davet edilmesi
====
*HMK 171*: (1) İsticvabına karar verilen kimseye bizzat davetiye gönderilir ve
belirlenen gün ve saatte isticvap olunmak üzere hazır bulunması gerektiği
belirtilir. Davetiyede, ayrıca, isticvap konusu vakıalar gösterilir; ilgili
tarafın geçerli bir özrü olmaksızın gelmediği veya gelip de sorulara cevap
vermediği takdirde, isticvap konusu vakıaları ikrar etmiş sayılacağı ihtarı da
yapılır.

(2) Çağrılan taraf özürsüz olarak gelmediği veya gelip de soruları cevapsız
bıraktığı takdirde, mahkemece sorulan vakıalar ikrar edilmiş sayılır.
====

[caption=""]
.Bizzat isticvap olunma
====
*HMK 172*: (1) İsticvap olunacak kimsenin bizzat gelmesi gereklidir. Ancak,
isticvap olunacak kişi, mahkemenin bulunduğu il dışında oturuyor ve bulunduğu
yerde aynı anda ses ve görüntü nakledilmesi yolu ile isticvap olunması mümkün
değil ise istinabe yolu ile isticvap olunur.

(2) İsticvap olunacak kimse hastalık, engellilik veya benzeri sebeplerle
mahkemeye bizzat gelemeyecek durumda ise bulunduğu yerde isticvap olunur.
====

[caption=""]
.Kıyasen uygulanacak hükümler
====
*HMK 175*: (1) Tanıklığa ilişkin 249, 250, 259 ilâ 263 üncü madde hükümleri
niteliğine aykırı düşmediği sürece isticvapta da uygulanır.
====

==== BİLİRKİŞİ

Kanun tarafından getirilmiş bilirkişiye müracaat zorunluluğu olan davalar
dışındaki davalarda bilirkişi raporu bir takdiri delildir. Dolayısıyla herhangi
bir vakıanın ya da hukuki ilişkinin varlığı, yokluğu ya da geçerliliği
açısından bilirkişiye müracaat edilmiş ve bilirkişinin sözlü veya yazılı görüşü
alınmışsa hakim buna dayanarak karar tesis edebilir.

[caption=""]
.Bilirkişiye başvurulmasını gerektiren hâller
====
*HMK 266*: (1) Mahkeme, çözümü hukuk dışında, özel veya teknik bilgiyi
gerektiren hâllerde, taraflardan birinin talebi üzerine yahut kendiliğinden,
bilirkişinin oy ve görüşünün alınmasına karar verir. Hâkimlik mesleğinin
gerektirdiği genel ve hukuki bilgiyle çözümlenmesi mümkün olan konularda
bilirkişiye başvurulamaz.
====

[caption=""]
.Bilirkişi sayısının belirlenmesi
====
*HMK 267*: (1) Mahkeme, bilirkişi olarak, yalnızca bir kişiyi
görevlendirebilir. Ancak, gerekçesi açıkça gösterilmek suretiyle, tek sayıda,
birden fazla kişiden oluşacak bir kurulun bilirkişi olarak görevlendirilmesi de
mümkündür.
====

[caption=""]
.Bilirkişilerin görevlendirilmesi
====
*HMK 268*: (1) Bilirkişiler, yargı çevresinde yer aldığı bölge adliye mahkemesi
adli yargı adalet komisyonları tarafından, her yıl düzenlenecek olan listelerde
yer alan kişiler arasından görevlendirilirler. Listelerde bilgisine
başvurulacak uzmanlık dalında bilirkişinin bulunmaması hâlinde, diğer bölge
adliye mahkemelerinde oluşturulmuş listelerden, burada da yoksa liste dışından
bilirkişi görevlendirilebilir.

(2) Kanunların görüş bildirmekle yükümlü kıldığı kişi ve kuruluşlara
görevlendirildikleri konularda bilirkişi olarak öncelikle başvurulur. Ancak,
kamu görevlilerine, bağlı bulundukları kurumlarla ilgili dava ve işlerde,
bilirkişi olarak görev verilemez.

(3) Bilirkişi listelerinin düzenlenmesine, güncellenmesine ve listede kendisine
yer verilmiş olanların liste dışına çıkartılmasına ilişkin esas ve usuller,
ilgili bakanlıkların da görüşü alınmak suretiyle, Adalet Bakanlığınca
hazırlanacak olan yönetmelikte gösterilir.
====

Bilirkişi, dosyayı mahkemede de inceleyebilir, dosya kendisine teslim de
edilebilir. Ayrıca dava konusunun veya kendisine müracaat edilen hususun
bulunduğu yerde de inceleme yapabilir.

Hakim bilirkişinin hangi görevi yapmakla mesul olduğunu bildirmek zorundadır.
Bilirkişi ancak kendisine tebliğ edilmiş görev kapsamında bir rapor
hazırlayabilir.

[caption=""]
.Bilirkişilik görevinin kapsamı
====
*HMK 269*: (1) Bilirkişilik görevi, mahkemece yapılan davete uyup tayin edilen
gün ve saatte mahkemede hazır bulunmayı, yemin etmeyi ve bilgisine başvurulan
konuda süresinde oy ve görüşünü mahkemeye bildirmeyi kapsar.

(2) Geçerli bir özrü olmaksızın mahkemece yapılan davete uyup, tayin edilen gün
ve saatte mahkemede hazır bulunmayan yahut mahkemeye gelip de yemin etmekten
veya süresinde oy ve görüş bildirmekten kaçınan bilirkişiler hakkında,
tanıklığa ilişkin disiplin hükümleri uygulanır.
====

[caption=""]
.Bilirkişinin görev alanının belirlenmesi
====
*HMK 273*: (1) Mahkeme, tarafların da görüşünü almak suretiyle bilirkişinin
görevlendirilmesine ilişkin kararında, aşağıda belirtilen hususlara yer vermek
zorundadır:

.. İnceleme konusunun bütün sınırlarıyla ve açıkça belirlenmesi.
.. Bilirkişinin cevaplaması gereken sorular.
.. Raporun verilme süresi.

(2) Bilirkişiye, görevlendirme yazısının ekinde, inceleyeceği şeyler, dizi
pusulasına bağlı olarak ve gerekiyorsa mühürlü bir biçimde teslim edilir;
ayrıca bu husus tutanakta gösterilir.
====

Bilirkişilik yapmakla yükümlü olanlar HMK 270'te sayılmıştır. Bu kişiler ancak
tanıklıktan çekinme sebeplerine veya mahkemece kabul edilebilecek diğer bir
sebebe dayanarak bilirkişilik yapmaktan kaçınabilirler.

. Resmi bilirkişiler ile HMK 268'teki listede yer almış olanlar
. Bilgisine başvurulacak konuyu bilmeksizin, meslek veya zanaatlarını icra
etmesine olanak bulunmayanlar
. Bilgisine başvurulacak konu hakkında, meslek veya sanat icrasına resmen
yetkili kılınmış olanlar

Bilirkişilik yapmaktan yasaklılık ve ret, hakimin yasaklılığı ve reddiyle bir
tutulmuştur. Dolayısıyla HMK 34 ve 36 kapsamında bilirkişinin yasaklılığı ve
reddi söz konusu olur.

[caption=""]
.Bilirkişinin görevini yapmaktan yasaklı olması ve reddi
====
*HMK 272*: (1) Hâkimler hakkındaki yasaklılık ve ret sebepleriyle ilgili
kurallar, bilirkişiler bakımından da uygulanır.  Ancak, bilirkişinin, aynı dava
veya işte daha önceden tanık olarak dinlenmiş bulunması, bir ret sebebi teşkil
etmez.

(2) Hâkimler hakkındaki yasaklılık sebeplerinden biri, bilirkişinin şahsında
gerçekleşmişse, mahkeme, hüküm verilinceye kadar, her zaman bilirkişiyi resen
görevden alabileceği gibi, bilirkişi de mahkemeden, görevden alınma talebinde
bulunabilir.

(3) Ret sebeplerinden birinin bilirkişinin şahsında gerçekleşmesi hâlinde
taraflar, bilirkişinin reddini talep edebileceği gibi, bilirkişi de kendisini
reddedebilir. Ret talebi veya bilirkişinin kendisini reddetmesinin, ret
sebebinin öğrenilmesinden itibaren en geç bir hafta içinde yapılmış olması
şarttır. Ret sebeplerinin ispatı için, yemin teklif edilemez.

(4) Görevden alınma, ret ve bilirkişinin kendisini reddetmesine yönelik talep,
bilirkişiyi görevlendiren mahkemece dosya üzerinden incelenir ve karara
bağlanır. Kabule ilişkin kararlar kesindir. Redde ilişkin kararlara karşı ise
ancak esas hakkındaki kararla birlikte kanun yoluna başvurulabilir.
====

[caption=""]
.Bilirkişinin yetkileri
====
*HMK 278*: (1) Bilirkişi, görevini, mahkemenin sevk ve idaresi altında yürütür.

(2) Bilirkişi, görev alanı veya sınırları hakkında tereddüde düşerse, bu
tereddüdünün giderilmesini, her zaman mahkemeden isteyebilir.

(3) Bilirkişi, incelemesini gerçekleştirirken ihtiyaç duyarsa, mahkemenin de
uygun bulması kaydıyla, tarafların bilgisine başvurabilir. Taraflardan birinin
bilgisine başvurulacağı hâllerde, mahkemece bilirkişiye taraflardan biri
bulunmaksızın diğerinin dinlenemeyeceği hususu önceden hatırlatılır.

(4) Bilirkişinin oy ve görüşünü açıklayabilmesi için bir şey üzerinde inceleme
yapması zorunlu ise mahkeme kararı ile gerekli incelemeyi yapabilir. Bu işlemin
icrası sırasında taraflar da hazır bulunabilir.
====

Bilirkişi raporunu hazırlayıp mahkemeye sunduktan sonra bu tarihten itibaren 2
hafta içerisinde rapora itiraz edilebilir. İtiraz, raporun tamamına dair
olabileceği gibi bir kısmına dair de olabilir. İtiraz edilmemesi durumunda
rapordaki hususlar ikrar edilmiş sayılır ve hasım açısından usuli müktesep hak
doğar.

Rapora itiraz edilmesinin ardından üç ihtimal vardır:

. Dosya yeni bir bilirkişiye veya bilirkişi heyetine verilir.
. İlk raporu yazan bilirkişi itirazlar doğrultusunda raporunu tamamlayabilir.
. İlk raporu yazan bilirkişi raporu hakkında açıklama yapabilir.

Bilirkişinin raporu hazırlarken hakimin hukuki sorumluluğuna benzer bir hukuki
sorumluluğu vardır. Bilirkişinin kasten veya ağır ihmal suretiyle düzenlediği
gerçeğe aykırı rapor yüzünden zarara uğramış kişiler uğradıkları zararın
tazmini için Devlete karşı tazminat davası açarlar. Devlet ödediği tazminat
için bilirkişiye rücu edecektir.

[caption=""]
.Bilirkişinin hukuki sorumluluğu
====
*HMK 285*: (1) Bilirkişinin kasten veya ağır ihmal suretiyle düzenlemiş olduğu
gerçeğe aykırı raporun, mahkemece hükme esas alınması sebebiyle zarar görmüş
olanlar, bu zararın tazmini için Devlete karşı tazminat davası açabilirler.

(2) Devlet, ödediği tazminat için sorumlu bilirkişiye rücu eder.
====

==== KEŞİF

Keşfe tarafların talebi üzerine veya hakim tarafından re'sen karar verilebilir.
Taraflar keşif talebini sözlü yargılama aşamasına kadar hakime iletebilirler.
Hakim ise dava boyunca her zaman keşfe karar verebilir.

[caption=""]
.Keşif kararı
====
*HMK 288*: (1) Hâkim, uyuşmazlık konusu hakkında bizzat duyu organları
yardımıyla bulunduğu yerde veya mahkemede inceleme yaparak bilgi sahibi olmak
amacıyla keşif yapılmasına karar verebilir. Hâkim gerektiğinde bilirkişi
yardımına başvurur.

(2) Keşif kararı, mahkemece, sözlü yargılamaya kadar taraflardan birinin talebi
üzerine veya resen alınır.
====

Keşif, hakim ve katip ile gerçekleştirilir. İkisinin de keşif esnasında hazır
bulunması şarttır. Taraf veya taraf vekillerinin keşif anında, keşif mahalinde
bulunmaları gerekli değildir.

Keşif konusu şey eğer mahkemenin yargı çevresi dışında ise istinabe olunması
mümkündür.

[caption=""]
.Keşfe yetkili mahkeme
====
*HMK 289*: (1) Keşif, davaya bakan mahkemece icra edilir. Keşif konusu,
mahkemenin yargı çevresi dışında ise inceleme istinabe suretiyle yapılır.

(2) Keşif konusu, büyükşehir belediye sınırları içerisinde ise inceleme, davaya
bakan mahkeme tarafından da yerine getirilebilir.
====

IMPORTANT: Keşif zorunluluğu ortaya çıkarsa aynı hakim, daha önce aynı
kapsamında yapılmış dahi olsa daha önce yaptığı keşifteki tespitleri
kullanamaz.

== TAHKİKATIN SONA ERMESİ

Hakim, mevcut delil analizi ve duruşmalar neticesinde ihtilafın bir şüpheye
mahal kalmayacak şekilde aydınlandığına kanaat getirirse tahkikatın
tamamlanmasına yönelik bir tasarrufta bulunabilir. Bu husus taraflara tefhim
olunur. Tahkikatın bittiğine ilişkin kararın tefhim olmaması usule aykırıdır.
Eski söyleyiş ile bozma, şimdiki söyleyiş ile istinaf sebebidir.

NOTE: *Tefhim*: Kararın hakim tarafından tarafların yüzüne karşı okunması

[caption=""]
.Tahkikatın sona ermesi
====
*HMK 184*: (1) Hâkim, tarafların iddia ve savunmalarıyla toplanan delilleri
inceledikten sonra, duruşmada hazır bulunan taraflara tahkikatın tümü hakkında
açıklama yapabilmeleri için söz verir.

(2) Mahkeme tarafların tahkikatın tümü hakkındaki açıklamalarından sonra,
tahkikatı gerektiren bir husus kalmadığını görürse, tahkikatın bittiğini
taraflara tefhim eder.
====

Tahkikatın bitiminden sonra, sözlü yargılama ve hüküm için tayin olacak gün ve
saatin davetiye marifetiyle taraflara tebliğ edilmesi gerekir. Sözlü yargılama
için müstakil bir duruşma yapılması zorunludur.

[caption=""]
.Sözlü yargılama
====
*HMK 186*: (1) Mahkeme, tahkikatın bitiminden sonra, sözlü yargılama ve hüküm
için tayin olacak gün ve saatte mahkemede hazır bulunmalarını sağlamak amacıyla
iki tarafı davet eder. Taraflara çıkartılacak olan davetiyede, belirlenen gün
ve saatte mahkemede hazır bulunmadıkları takdirde yokluklarında hüküm
verileceği hususu bildirilir.

(2) Sözlü yargılamada mahkeme, taraflara son sözlerini sorar ve hükmünü verir.
====

TIP: Hüküm okunurken, herkes ayağa kalkmalıdır. Buna riayet edilmemesi istinaf
sebebidir.

== HÜKÜM

[caption=""]
.Hüküm, hükmün verilmesi ve tefhimi
====
*HMK 294*: (1) Mahkeme, usule veya esasa ilişkin bir nihai kararla davayı sona
erdirir. Yargılama sonunda uyuşmazlığın esası hakkında verilen nihai karar,
hükümdür.

(2) Hüküm, yargılamanın sona erdiği duruşmada verilir ve tefhim olunur.

(3) Hükmün tefhimi, her hâlde hüküm sonucunun duruşma tutanağına geçirilerek
okunması suretiyle olur.

(4) Zorunlu nedenlerle sadece hüküm sonucunun tefhim edildiği hâllerde,
gerekçeli kararın tefhim tarihinden başlayarak bir ay içinde yazılması gerekir.

(5) Hükmün tefhimini, duruşmada bulunanlar ayakta dinler.

(6) Hükme ilişkin hususlar, niteliğine aykırı düşmedikçe, usule ilişkin nihai
kararlar hakkında da uygulanır.
====

Hakim, önüne gelmiş uyuşmazlık hakkında bir karar vermek mecburiyetindedir. Üç
tip karar vardır:

. *Ara karar*: Yargılamanın devamını sağlayan, hakim tarafından yargılamanın
her aşamasında tesis edilebilen, usuli müktesep hak doğmamış olması şartıyla
rücu edilme kabiliyeti olan, bazı istisnalar haricinde hakkında kanun yoluna
başvurulma imkanı olmayan karar türüdür.
. *Nihai karar*: Yargılamayı usuli bir sebeple sona erdiren karar türüdür.
. *Hüküm*: Yargılamanın esasına ilişkin verilmiş karardır.

CAUTION: Hüküm ile sona ermiş bir yargılamaya konu edilmiş ihtilafın yeniden
yargılama konusu yapılması mümkün değildir. Ancak yargılama nihai karar ile
sona ermiş ise usuli eksiklik giderildikten sonra, zamanaşımı ve hak düşürücü
süreler de geçmemiş ise, ihtilaf yeniden yargılama konusu yapılabilir.

Sözlü yargılama aşamasında hakimin taraflara tefhim ettiği hüküm, **kısa
karar**dır. Hakimin bunu 1 ay içerisinde gerekçelendirmesi gerekmektedir. Bu
süre disiplinel bir süredir. Emredici bir hüküm değildir. *Gerekçeli karar*,
taraflara tebliğ edilecektir. 

Gerekçeli karar, tefhim edilen kısa karar ile çelişemez. Aksi takdirde bu bir
istinaf sebebidir. Bu durumda Bölge Adliye Mahkemesi Hukuk Dairesi, ilk derece
mahkemesinin vermiş olduğu kararlardan birisini dikkate alarak kısa kararı
gerekçelendirip esas kararmışçasına karara bağlayabilir.

NOTE: Kısa karar ile gerekçeli karar arasında çelişki olması halinde, karar
kanun yoluna başvurma süresinin hareketsiz geçirilmesi suretiyle kesinleşmiş
olsa dahi kanun yoluna başvurma imkanı vardır. Kısa karar ile gerekçeli karar
arasında çelişki olması yargılamanın iadesi sebebidir.

Mahkeme kararını verirken davacının talebi ve davalının savunmasını gözönüne
alacaktır. Bu karar verilirken iki taraf açısından da talepta bulunulmamış bir
husus karara bağlanabilir. İki tarafın da üzerine borç yükleyen sözleşmelerde
iki taraf da hüküm ile birlikte edaya mahkum edilebilir.

CAUTION: Hüküm verilirken davanın açıldığı tarih itibariyle doğmuş haklar
kapsamında hüküm verilmesi gerekir. Daha sonra doğmuş haklar için aynı davada
karar verilmesi mümkün değildir.

[caption=""]
.Hükmün kapsamı
====
*HMK 297*: (1) Hüküm “Türk Milleti Adına” verilir ve bu ibareden sonra
aşağıdaki hususları kapsar:

.. Hükmü veren mahkeme ile hâkim veya hâkimlerin ve zabıt kâtibinin ad ve
soyadları ile sicil numaraları, mahkeme çeşitli sıfatlarla görev yapıyorsa
hükmün hangi sıfatla verildiğini.
.. Tarafların ve davaya katılanların kimlikleri ile Türkiye Cumhuriyeti kimlik
numarası, varsa kanuni temsilci ve vekillerinin ad ve soyadları ile
adreslerini.
.. Tarafların iddia ve savunmalarının özetini, anlaştıkları ve anlaşamadıkları
hususları, çekişmeli vakıalar hakkında toplanan delilleri, delillerin
tartışılması ve değerlendirilmesini, sabit görülen vakıalarla bunlardan
çıkarılan sonuç ve hukuki sebepleri.
.. Hüküm sonucu, yargılama giderleri ile taraflardan alınan avansın harcanmayan
kısmının iadesi, varsa kanun yolları ve süresini.
 . Hükmün verildiği tarih ve hâkim veya hâkimlerin ve zabıt kâtibinin imzalarını.
.. Gerekçeli kararın yazıldığı tarihi.

(2) Hükmün sonuç kısmında, gerekçeye ait herhangi bir söz tekrar edilmeksizin,
taleplerden her biri hakkında verilen hükümle, taraflara yüklenen borç ve
tanınan hakların, sıra numarası altında; açık, şüphe ve tereddüt uyandırmayacak
şekilde gösterilmesi gereklidir.
====

Taraf, kendisi lehine ya da aleyhine verilmiş olan karar hukuki menfaatini
ihlal ediyorsa, yapılan yargılamada hasmın ya da hakimin hangi usuli işlemi bu
menfaat ihlaline sebep teşkil etmiş ise onu istinaf sebebi olarak ileri
sürecektir. İstinaf sebebinin bulunacağı birinci adres gerekçeli karardır.
Gerekçeli kararın HMK 297/1-c bendindeki unsurlara sahip olması gerekir.

Hüküm verildikten sonra iki tane tesir meydana gelir:

. *Olumlu tesir*: Hakim hükmü verdikten sonra artık bununla bağlıdır. Hakimin
ara karar veya kısa karar ile vermiş olduğu karar kendisini bağlar. Bu noktadan
sonra dava bu minvalde hükme bağlanmak zorundadır.
. *Olumsuz tesir*: Yargılamayı yürüten hakimin neticelendirmiş olduğu ihtilafla
ilgili yeniden yargılamama yapılamaması ve dava neticelendikten sonra
yargılamayı yürüten hakimin bu dava ile ilgili herhangi bir usuli işlem tesis
edememesidir.

=== KESİN HÜKÜM

[caption=""]
.Kesin hüküm
====
*HMK 303*: (1) Bir davaya ait şeklî anlamda kesinleşmiş olan hükmün, diğer bir
davada maddi anlamda kesin hüküm oluşturabilmesi için, her iki davanın
taraflarının, dava sebeplerinin ve ilk davanın hüküm fıkrası ile ikinci davaya
ait talep sonucunun aynı olması gerekir.

(2) Bir hüküm, davada veya karşılık davada ileri sürülen taleplerden, sadece
hükme bağlanmış olanlar hakkında kesin hüküm teşkil eder.

(3) Kesin hüküm, tarafların küllî halefleri hakkında da geçerlidir.

(4) Bir dava dolayısıyla ortaya çıkan kesin hüküm, o hükmün kesinleşmesinden
sonra dava konusu şeyin mülkiyetini tarafların birisinden devralan yahut dava
konusu şey üzerinde sınırlı bir ayni hak veya fer’î zilyetlik kazanan kişiler
hakkında da geçerlidir.  Ancak, Türk Medenî Kanununun iyiniyetle mal edinmeye
ait hükümleri saklıdır.

(5) Müteselsil borçlulardan biri veya birkaçı ile alacaklı arasında yahut
müteselsil alacaklılardan biri veya birkaçı ile borçlu arasında oluşan kesin
hüküm, diğerleri hakkında geçerli değildir.
====

İlk derece mahkemesinin verdiği kararın istinafa müracaat kabiliyetine mazhar
olabilmesine ilişkin kanunda ayrıca ve açıkça bir düzenleme varsa kesinleşme
açısından istinaf prosedürünün tamamlanması ya da istinaf yoluna müracaat için
gereken sürenin başvuru yapılmadan geçirilmesi gerekir.

Bazı durumlarda ise ilk derece mahkemesinin verdiği karar verildiği an
itibariyle kesinleşir. Bu durumlar:

. Hükme karşı kanun yolundan feragat edilmesi
. Hükme karşı kanun yoluna müracaatın ilk derece mahkemesi tarafından
reddedilmesi

İlk derece mahkemesinin kararı kesinleşince şekli ve maddi anlamda kesin hüküm
tesiri ortaya çıkar. Şekli anlamda kesin hüküm tesiri, ilk derece mahkemesi
hakiminin veya başka bir merciin o karar hakkın tasarrufta bulunamamasıdır. Bir
ihtilaf şekli anlamda kesin hüküm ile karara bağlanınca aynı ihtilafa ilişkin
olarak yeniden bir davanın görülmesi mümkün değildir. Bu *maddi anlamda kesin
hüküm* tesiridir.

Kanun yolu tüketilmeden kesinleşmiş hüküm ile kanun yolu prosedürünün
tamamlanması suretiyle kesinleşmiş hüküm arasında maddi anlamda kesin hüküm
tesiri açısından hiçbir fark yoktur.

Bir ihtilafla ilgili yargılamanın kesin hüküm ile neticelenmiş olması bir dava
şartıdır (HMK 114/1) ve yargılamanın her aşamasında ileri sürülebilir.

=== HÜKMÜN TASHİHİ (DÜZELTİLMESİ)

[caption=""]
.Hükmün tashihi
====
*HMK 304*: (1) Hükümdeki yazı ve hesap hataları ile diğer benzeri açık hatalar,
mahkemece resen veya taraflardan birinin talebi üzerine düzeltilebilir. Hüküm
tebliğ edilmişse hâkim, tarafları dinlemeden hatayı düzeltemez. Davet üzerine
taraflar gelmezse, dosya üzerinde inceleme yapılarak karar verilebilir.

(2) Tashih kararı verildiği takdirde, düzeltilen hususlarla ilgili karar,
mahkemede bulunan nüshalar ile verilmiş olan suretlerin altına veya bunlara
eklenecek ayrı bir kâğıda yazılır, imzalanır ve mühürlenir.
====

Hüküm verilmeden hükmün tashihi söz konusu olmaz. Hüküm doğmadan önce ilk
derece mahkemesinin yaptığı tek taraflı usuli işlemlerde hataların düzeltilmesi
için HMK 183'de yer alan maddi hataların düzeltilmesi kurumuna müracaat edilir.

Hükmün tashihini hakim re'sen gerçekleştirebileceği gibi tarafların talebi
üzerine de gerçekleştirebilir.

Eğer ilk derece mahkemesinin hükmü taraflara tebliğ edilmişse, hükmün tashihi
ancak taraflar dinlendikten sonra gerçekleştirilebilir.

=== HÜKMÜN TAVZİHİ (AÇIKLANMASI)

[caption=""]
.Hükmün tavzihi
====
*HMK 305*: (1) Hüküm yeterince açık değilse veya icrasında tereddüt uyandırıyor
yahut birbirine aykırı fıkralar içeriyorsa, icrası tamamlanıncaya kadar
taraflardan her biri hükmün açıklanmasını veya tereddüt ya da aykırılığın
giderilmesini isteyebilir.

(2) Hüküm fıkrasında taraflara tanınan haklar ve yüklenen borçlar, tavzih yolu
ile sınırlandırılamaz, genişletilemez ve değiştirilemez.
====

İlamı icra etmek için icra dairesine müracaat edildiğinde icra dairesi müdürü,
kendisine sunulmuş ilam gerekçesi ve hüküm kısmını değerlendirdiğinde icra
açısından müphem bir durum olduğunu görürse taraflardan ilk derece mahkemesi
kararının tavzihini talep edebilir. Tavzih yetkisi sadece kararı veren
mahkemeye aittir.

[caption=""]
.Tavzih talebi ve usulü
====
*HMK 306*: (1) Tavzih, dilekçeye tarafların sayısı kadar nüsha eklenmek
suretiyle hükmü veren mahkemeden istenebilir.  Dilekçenin bir nüshası, cevap
süresi mahkemece belirlenerek karşı tarafa tebliğ edilir. Cevap, tavzih
talebinde bulunan tarafa tebliğ olunur.

(2) Mahkeme, cevap verilmemiş olsa bile dosya üzerinde inceleme yaparak karar
verir; ancak gerekli görürse iki tarafı sözlü açıklamalarını yapabilmeleri için
davet edebilir.

(3) Mahkeme tavzih talebini yerinde gördüğü takdirde 304 üncü madde uyarınca
işlem yapar.
====

Tavzih yoluyla genişletme, değiştirme ya da sınırlama yoluna müracaat edilmesi,
bu yönde bir tasarrufta bulunulması mümkün değildir.

Hakim re'sen tavzih yapamaz.

Hasmın tavzih talebinin mutlaka tarafa tebliğ edilmesi gerekir.

=== YARGILAMA GİDERLERİ

[caption=""]
.Yargılama giderlerinden sorumluluk
====
*HMK 326*: (1) Kanunda yazılı hâller dışında, yargılama giderlerinin, aleyhine
hüküm verilen taraftan alınmasına karar verilir.

(2) Davada iki taraftan her biri kısmen haklı çıkarsa, mahkeme, yargılama
giderlerini tarafların haklılık oranına göre paylaştırır.

(3) Aleyhine hüküm verilenler birden fazla ise mahkeme yargılama giderlerini,
bunlar arasında paylaştırabileceği gibi, müteselsilen sorumlu tutulmalarına da
karar verebilir.
====

Yargılama giderleri:

. Harçlar

.. Başvurma harcı
.. İlam harcı
.. Celse harcı

. HMK 323'teki masraflar

.. Tanık, bilirkişi, keşif gibi deliller için yatırılan masraflar
.. Geçici hukuki korumalar için yapılan masraflar
.. Tebligat masrafları

. Vekalet ücreti

Yargılama giderlerine ancak yargılama esasa ilişkin bir karar ile son bulmuşsa
hükmedilebilir. Nihai kararla son bulan yargılamada yargılama giderlerine
hükmedilemez.

== KANUN YOLLARI

*Kanun yolu*, mahkemelerce verilen nihai kararların yanlış, hatalı veya eksik
oldukları gerekçesiyle ve düzeltilmeleri talebiyle bir üst derecede bulunan
mahkemeye başvurulmasıdır.

Bir kurumun kanun yolu kurumu olarak değerlendirilebilmesi için iki kriter
vardır:

. *Aktarıcı etki*: İncelemeyi yapacak olan merciin aynı mercii olmamasını
ifade eder.
. *Erteleyici etki*: Kanun yoluna müracaat edildiğinde ilk merciin verdiği
kararın kesinleşmesinin inceleme sonuna kadar ertelenmesini ifade eder.

An itibariyle kanun yolu denetimi hem 1086 sayılı HUMK hem de 6100 sayılı
HMK'ya göre yapılmaktadır. 20.07.2016 tarihinden önce ilk derece mahkemesinin
vermiş olduğu karara karşı kanun yoluna müracaat edilecekse 1086 sayılı HUMK'a
göre temyiz sistemi geçerli olacaktır.

====
*HMK GEÇİCİ MADDE 3*: (1) Bölge adliye mahkemelerinin, 26/9/2004 tarihli ve
5235 sayılı Adli Yargı İlk Derece Mahkemeleri ile Bölge Adliye Mahkemelerinin
Kuruluş, Görev ve Yetkileri Hakkında Kanunun geçici 2 nci maddesi uyarınca
Resmî Gazete’de ilan edilecek göreve başlama tarihine kadar, 1086 sayılı
Kanunun temyize ilişkin yürürlükteki hükümlerinin uygulanmasına devam olunur.

(2) Bölge adliye mahkemelerinin göreve başlama tarihinden önce verilen kararlar
hakkında, kesinleşinceye kadar 1086 sayılı Kanunun 26/9/2004 tarihli ve 5236
sayılı Kanunla yapılan değişiklikten önceki 427 ilâ 454 üncü madde hükümlerinin
uygulanmasına devam olunur. Bu kararlara ilişkin dosyalar bölge adliye
mahkemelerine gönderilemez.

(3) Bu Kanunda bölge adliye mahkemelerine görev verilen hallerde bu
mahkemelerin göreve başlama tarihine kadar 1086 sayılı Kanunun bu Kanuna aykırı
olmayan hükümleri uygulanır.
====

*Derecattan geçerek kesinleşme*: Kanun yollarına başvurulup buradaki
incelemenin sona ermesinden sonra kararın kesinleşmesidir.

=== 1086 SAYILI HMUK'A GÖRE KANUN YOLU DENETİMİ

1086 sayılı kanuna bakıldığında kanun yolu sisteminde 3 tane kurum vardır:

. Temyiz
. Karar düzeltme
. Yargılamanın iadesi

==== TEMYİZ

1086 sayılı kanuna göre temyize müracaat için gerekli şartlar:

. _İlk derece mahkemesinin vermiş olduğu bir karar olmalıdır_. 
+
Aşağıdaki kararlar temyize konu olabilir:

.. Yargıtay Hukuk Dairesinin ilk derece mahkemesi sıfatıyla vermiş olduğu
kararlar
.. İlk derece mahkemesinin vermiş olduğu nihai kararlar
.. İlk derece mahkemesinin esasa ilişkin vermiş olduğu kararlar
.. İlk derece mahkemesinin davanın konusuz kalmasına ilişkin vermiş olduğu
kararlar

+
CAUTION: 1086 sayılı kanunda ara kararlar *istisnasız* bir şekilde temyize konu
olamazlar.
. _Davadaki müddeabihin değeri belli bir değerin üzerinde olmalıdır_.
+
Bu sınır örneğin asliye hukuk mahkemesi için 2190 TL, icra mahkemesi için 6310
TL'dir.
. _Temyize müracaat uyulması gereken süre içinde yapılmış olmalıdır_.
+
Her hukuk mahkemesi için temyize başvurma süresi kendi kanununda
düzenlenmiştir. Dolayısıyla tek tip bir süre söz konusu değildir.
+
Örneğin asliye hukuk mahkemesinin kararlarına karşı temyiz süresi tebliğden
itibaren 45 gündür. Sulh hukuk mahkemesinin kararlarına karşı bu süre 8 gündür.
Asliye ticaret mahkemesinde bazı hallerde 10, bazı hallerde ise 15 gündür.
+
Temyize müracaat süresi bazı hallerde tefhimden itibaren başlar. Örneğin iş
mahkemesinde bu süre 8 gündür ve tefhimden itibaren başlar.
. _Temyize müracaat için hukuki yarar gereklidir_.
+
Hukuki yararın tespitinde iki tane teori vardır:

.. *Maddi teori*: Temyize müracaat eden, temyiz incelemesinde ilk derece
mahkemesinin verdiği karardan daha lehine bir sonuç alacağını düşünüyorsa
temyize müracaat etmekte hukuki yararı vardır.
.. *Şekli teori*: Davacının veya davalının cevap dilekçesindeki netice-i talep
kısımları ile ilk derece mahkemesinin vermiş olduğu karardaki hüküm fıkrası
mukayese edilir. Bunlar birebir örtüşüyorsa temyize müracaatta hukuki yarar
yoktur, azıcık bile örtüşmüyorsa hukuki yarar var kabul edilir.

Sadece davanın tarafları temyize müracaat edebilir. Davanın tarafları haricinde
davaya intikal etmiş olan üçüncü kişilerin müstakilen davayı temyize
götürebilmesi mümkün değildir.

Fer'i müdahil taraf değil, taraf yardımcısıdır. Yanında katıldığı taraf temyize
müracaat etmişse fer'i müdahil onun yanında faaliyet gösterebilir. Ancak
müstakilen davayı temyize götürmesi mümkün değildir. Bunun istisnaları vardır:

. Hükümde doğrudan fer'i müdahile tesir edecek nitelike lehine veya aleyhine
bir karar tesis edilmiş ise temyize müracaat edebilir.
. Fer'i müdahil olma talebi ara kararla reddedilmişse hüküm ile birlikte
temyize müracaat edebilir.

Asli müdahil zaten taraftır. Asli müdahil olarak intikal ettiği davadaki davacı
ve davalıyı hasım kılarak yeni bir dava ikame ettiğinden dolayı, kendisi
aleyhine veya lehine verilmiş olan kararı -hukuki yararı bulunmak şartıyla-
temyize götürme imkanı vardır.

İhtiyari dava arkadaşlığında her bir dava arkadaşı kadar dava olduğu için
müstakile temyize müracaat edebilme imkanına sahiptirler. Şekli anlamda zaruri
dava arkadaşlığında temyize müracaat için dava arkadaşlarının tümünün ortak
iradesi gerekir. Maddi anlamda zaruri dava arkadaşlağında ise dava
arkadaşlarından sadece birisi temyize müracaat etmişse, diğer dava arkadaşları
bu temyiz müracaatından müspet ya da menfi etkilenirler.

Temyize müracaat eden taraf temyiz sebebini göstermemiş olsa bile temyiz
geçerlidir. Temyiz iradesi için şu üç şart yeterlidir:

. Temyizde bulunanın kim olduğu
. Hangi kararın temyiz edildiği
. İmza

Temyize müracaat mutlaka yazılı dilekçe ile yapılır. Yazılı dilekçe temyiz
konusu edilecek kararı vermiş olan ilk derece mahkemesine verilir. İlk derece
mahkemesine temyiz dilekçesi sunulduğu zaman ilk derece mahkemesi temyiz
şartlarının bulunup bulunmadığını denetlemekle mükelleftir. Temyiz şartları
için şunlara bakılır:

. Temyize matuf bir karar mı değil mi?
. Temyiz süresi içinde yapılmış mı?
. Temyiz harç ve giderleri yatırılmış mı?

Bu üç şarttan birine ilişkin olarak temyiz talebinin reddine karar verirse bu
niteliği itibariyle bir nihai karardır. Nihai karar olduğu için de müstakilen
temyize tabidir. Bu kararın temyizi için uyulması gereken süre tüm hukuk
mahkemeleri için 7 gündür.

İlk derece mahkemesi temyiz talebini kabul ederse dosya Yargıtay'a gider.
Temyiz dilekçesi hasma tebliğ edilir. Hasım temyiz dilekçesinin tebliğinden
itibaren 10 gün içerisinde temyize cevap dilekçesi verebilir.

Temyiz yoluna müracaat etmemiş taraf, hasmı tarafından temyize başvurulmuş ve
kendisine temyiz dilekçesi tebliğ edilmişse temyize müracaat etme hakkından
istifade edebilir. Buna *katılmalı temyiz* denir.

İlk derece mahkemesinin kararının temyiz edilmesi kararın icrasına engel
değildir. İlgili taraf kararı alıp ilamlı icra olarak takibe başlayabilir.
Ancak şu kararlar bu imkan dahilinde değildir:

. Aile hukukuna dair kararlar
. Taşınmaza ve buna ilişkin ayni haklara dair kararlar

===== BOZMA SEBEPLERİ

. *Maddi hukuka ilişkin sebepler*

.. Kanunun hakim tarafından yanlış uygulanmış olması
.. Sözleşmenin hakim tarafından yanlış uygulanmış olması
.. Vakıanın ispatı için sunulmuş delilin hakim tarafından hatalı
değerlendirilmiş olması

. *Şekli hukuka ilişkin sebepler*

.. Görevli olmayan bir mahkemenin davaya bakması
.. Tarafları ve sebebi aynı olan bir dava hakkında tarafları ve sebebi aynı
olan başka bir dava için verilmiş bir karar ile çelişen karar verilmesi
.. İlk derece mahkemesinin uygulaması gereken bir usul kuralını uygulamamış
veya hatalı uygulamış olması
+
Bu bir nisbi bozma sebebidir. Usul kuralına aykırılık hükme tesir etmişse bir
bozma sebebidir, ancak tesir etmemişse bozma sebebi değildir.
.. Hukuka uygun olaran sunulmuş delilin, yargılamayı yürüten hakim tarafından
kanundan kaynaklanmayan bir sebebe istinaden reddedilmiş olması

HUMK'taki bozma sebepleri sınırlı sayıdadır. Eğer Yargıtay, bir ilk derece
mahkemesinin kararını bozuyorsa yukarıda sayılmış olan 6 bentteki sebeplerden
biri mevcut olmalıdır. Bunlar haricinde bir sebebe dayanarak karar bozulamaz.

===== TEMYİZ İNCELEMESİ

Yargıtay Hukuk Dairesine dosya intikal ettikten sonra bir ön inceleme yapılır.
Bu ön incelemeyi tetkik hakimi yapar. Tetkik hakimi, ilk derece mahkemesinin
hakiminin yaptığı gibi, şunlara bakacaktır:

. Temyize götürülebilecek bir karar mı?
. Temyiz süresinde mi yapılmış?
. Temyiz harcı yatırılmış mı?

Temyiz incelemesi dosya üzerinden yapılır. İstisnaen bazı durumlarda talep
üzerine duruşma yapılabilir.

NOTE: Görevsizlik, yetkisizlik, hakimin reddi, davanın birleştirilmesi gibi
kararlara karşı temyize gidilmişse dava dosya üzerinden incelenir, duruşma
hiçbir şekilde yapılmaz.

TIP: İlk derece mahkemelerinin vermiş olduğu kararların kısmen temyizi
mümkündür. Yeter ki temyiz edilen kısım açıkça ve ayrıca dilekçenin içinde
belirtilmiş olsun. Eğer temyiz edilen  kısım açıkça ve ayrıca belirtilmemişse
hükmün tamamının temyiz edildiği kabul edilecektir. Kısmi temyiz durumunda
temyiz edilmemiş kısım için hüküm kesinleşir.

===== ALEYHE BOZMA VE ALEYHE HÜKÜM VERME YASAĞI

Bir hükmün davanın taraflarından sadece birisi tarafından temyiz edildiği
durumlarda Yargıtay, temyiz edilmiş olan hükmü temyiz eden tarafın aleyhine
sonuç doğuracak şekilde bozamaz.

Aleyhe bozma yasağının istisnaları:

. Kamu düzeninin ihlali
. Dava şartlarının ihlali

Taraflardan sadece biri temyiz yoluna başvurmuşsa ve Yargıtay temyiz eden
tarafın lehine olarak kararı bozarsa, bozma kararına uyan mahkeme de artık
temyiz eden tarafın aleyhine bir hüküm veremez.

===== BOZMA KARARI

Yargıtay Hukuk Dairesi ilk derece mahkemesinin kararını bozar ve bu bozma
kararı ilk derece mahkemesine karar düzeltmenin ardından veya karar düzeltmeye
hiç müracaat edilmeden intikal ederse ilk derece mahkemesi iki karar verebilir:
Bozma kararına uyma veya direnme.

Uyma kararı niteliği itibariyle bir ara karardır. Uyma kararının ardından bir
tahkikat yapılacaktır. Ayrıca uyma kararının verildiği an itibariyle bozulmuş
olan ilk derece kararının icra kabiliyeti ortadan kalkmış olacaktır.

İlk derece mahkemesi Yargıtay'ın bozma kararına karşı direnme kararı da
verebilir. Bu karar niteliği itibariyle bir nihai karardır ve buna karşı da
temyize gidilebilir.

TIP: 1086 sayılı kanuna göre direnme kararına karşı temyiz yoluna müracaat
edildiğinde temyiz incelemesi yapacak mercii hukuk genel kuruludur. Ancak
6100 sayılı HMK'nın geçici 4. maddesi uyarınca direnme kararının temyizen
inceleneceği mercii kararı veren hukuk dairesidir.

===== USULİ MÜKTESEP HAK

Mahkeme veya tarafların bir usuli işlemi ile taraflardan biri için bir hak
doğmuş ve bu hakka uyulması zorunlu ise *usuli müktesep hak* söz konusudur.

En önemli usuli müktesep hak örneği Yargıtay'ın bozma kararıdır. Yargıtay, ilk
derece mahkemesinin kararını bozup ilk derece mahkesine gönderdikten sonra ilk
derece mahkemesi bozma kararına uyma kararı verirse artık bu karardan rücu
edemez. Çünkü uyma kararını verdiği anda bozma kararı kimin lehine ise onun
için usuli müktesep hak doğmuş olur.

İlk derece mahkemesinin uyma kararından sonra verdiği karar temyize
gönderilirse Yargıtay ilk verdiği bozma kararı ile bağlıdır. İlk verdiği bozma
kararı kimin lehine ise onun için usuli müktesep hak oluşmuştur.

Yargıtay, ilk derece mahkemesinin vermiş olduğu kararın sadece bir kısmın
bozmuş ise bozmadığı kısım mahkeme tarafından dokunulamayacak kısımdır. Çünkü
bozmadığı kısım usuli müktesep hak teşkil eder.

TIP: Usuli müktesep hakkın uygulanamayacağı yerler vardır. Örnek olarak; ilk
derece mahkemesi bozma kararına uyma kararı verdikten sonra kanun değişmiş ve
lehine bozma kararı verilen kişinin aleyhine bir düzenleme getirilmiş ise usuli
müktesep hak uygulanmaz. Aynı şey içtihadı birleştirme kararları için de
geçerlidir.

==== KARAR DÜZELTME

Yargıtay'ın temyiz incelemesi sonucunda verdiği bozma, onama ve düzelterek
onama kararlarına ve temyiz ön incelemesi sonucunda verdiği ret kararına karşı
karar düzeltme yoluna gidilebilir.

Bunun için iki sınırlama getirilmiştir:

. Sulh mahkemesinin vermiş olduğu kararların temyiz incelemesi sonucunda
verilen kararlara karşı karar düzeltme yoluna başvurulamaz. Ancak aşağıdaki
davalar bundan hariç tutulmuştur:

.. Tahliye davaları
.. Kira alacağı davaları
.. Kat mülkiyetinden doğan davalar

. Müddeabihin değeri 13.900 TL'den az olan alacak, taşınır ve taşınmaz davaları
için ilk derece mahkemesinin vermiş olduğu kararların temyiz incelemesi
sonucunda verilecek kararlara karşı karar düzeltme yoluna başvurulamaz.
+
NOTE: Buradaki miktarsal değer talebin kabul edilmeyen kısmıdır. Örneğin
40.000 TL'lik bir alacak davasında 10.000 TL'lik talep kabul edilmiş ise
40.000 - 10.0000 = 30.0000 TL, 13.900 TL'den fazla olduğu için karar
düzeltmeye başvurulabilir.

Aynı Yargıtay kararı birden fazla kere karar düzeltmeye taşınamaz.

Aşağıdaki sebeplerle karar düzeltme yoluna gidilebilir:

. Temyiz itirazlarının cevapsız bırakılmış olması
. Yargıtay kararında birbirine aykırı fıkralar bulunması
. Yargıtay incelemesi sırasında hükmün esasını etkileyen belgelerde bir hile
veya sahteliğin ortaya çıkması
. Yargıtay kararının usul ve kanuna aykırı bulunması

Eğer itiraz sebebi, esası etkilemeyen bir sebepse karar düzeltme talebi direkt
olarak reddedilir.

TIP: 20 Temmuz 2016'dan sonra bir ilk derece mahkemesinin vermiş olduğu karara
dair temyiz incelemesinde verilmiş karara karşı karar düzeltme yoluna
gidilemez. *20 Temmuz 2016'dan sonra karar düzeltme yoktur!*

Yargıtay Hukuk Dairesinin tefhim veya tebliğinden itibaren on beş günlük süre
karar düzeltmeye müracaat süresidir. Bu süre hak düşürücü süredir. Burada da
katılma yoluyla başvuru mümkündür.

==== YARGILAMANIN İADESİ

1086 sayılı kanun uyarınca temyiz ve karar düzeltme **olağan kanun yolu**dur.
Yargılamanın iadesi ise **olağanüstü kanun yolu**dur.

Normalde maddi anlamda kesinleşmiş bir ilk derece mahkemesi kararına karşı
herhangi bir merciiye başvuru şansı yoktur. Ancak önemli usul hukuku
kurallarına aykırılık halinde yargılamanın iadesi yoluna müracaat edilebilir.

Yargılamanın iadesi sebepleri kanunda sınırlı olarak sayılmıştır:

. Mahkemenin kanuna uygun olarak teşekkül etmemiş olması
. Davaya bakması yasak olan yahut hakkındaki ret talebi, merciince kesin olarak
kabul edilen hakimin karar vermiş veya karara katılmış olması
. Vekil veya temsilci olmayan kimselerin huzuruyla dava görülmüş ve karara
bağlanmış olması
. Yargılama sırasında, aleyhine hüküm verilen tarafın elinde olmayan nedenlerle
elde edilemeyen bir belgenin, kararın verilmesinden sonra ele geçirilmiş olması
. Karara esas alınan senedin sahteliğine karar verilmiş veya senedin sahte
olduğunun mahkeme veya resmi makam önünde ikrar edilmiş olması
. İfadesi karara esas alınan tanığın, karardan sonra yalan tanıklık yaptığının
sabit olması
. Bilirkişi veya tercümanın, hükme esas alınan husus hakkında kasten gerçeğe
aykırı beyanda bulunduğunun sabit olması
. Lehine karar verilen tarafın, karara esas alınan yemini yalan yere ettiğinin,
ikrar veya yazılı delille sabit olması
. Karara esas alınan bir hükmün, kesinleşmiş başka bir hükümle ortadan kalkmış
olması
. Lehine karar verilen tarafın, karara tesir eden hileli bir davranışta
bulunmuş olması
. Bir dava sonunda verilen hükmün kesinleşmesinden sonra tarafları, konusu ve
sebebi aynı olan ikinci davada, öncekine aykırı bir hüküm verilmiş ve bu hükmün
kesinleşmiş olması
. Kararın, İnsan Haklarını ve Ana Hürriyetleri Korumaya Dair Sözleşmenin veya
protokollerin ihlali suretiyle verildiğinin, Avrupa İnsan Hakları Mahkemesinin
kesinleşmiş kararıyla tespit edilmiş olması

Yargılamanın iadesini isteme süresi bakımından kanun koyucu yargılamanın iadesi
sebebine ilişkin hususun öğrenilmesinden itibaren 3 aylık ve her halükarda
hükmün kesinleşmesinden itibaren 10 yıllık süreler belirlemiştir. Yargıtay'a
göre yargılamanın iadesi sebebine ilişkin husus hükmün kesinleşmesinden önce
öğrenilmişse 3 aylık süre hükmün kesinleşmesinden itibaren başlayacaktır.

Yargılamanın iadesi incelemesinde yargılama vekil ya da temsilci olmayan kişi
huzurunda yapılmışsa ya da iki tane çelişen kesin hüküm varsa hüküm iptal
edilir. Diğer sebepler varsa yeniden yargılama yapılıp, yeni bir karar
verilecektir.

=== 6100 SAYILI HMK'YA GÖRE KANUN YOLU DENETİMİ

6100 sayılı HMK'ya göre kanun yolu denetiminde üç kurum vardır:

. İstinaf
. Temyiz
. Yargılamanın yenilenmesi

==== İSTİNAF

Bölge adliye mahkemesindeki istinaf incelemesi, ilk derece mahkemeleri
tarafından verilmiş kararlardaki hem hukuk hem de vakıa boyutundaki
yanlışlıkların düzeltilmesi için elverişlidir.

[caption=""]
.İstinaf yoluna başvurulabilen kararlar
====
*HMK 341*: (1) İlk derece mahkemelerinden verilen nihai kararlar ile ihtiyati
tedbir, ihtiyati haciz taleplerinin reddi ve bu taleplerin kabulü hâlinde,
itiraz üzerine verilecek kararlara karşı istinaf yoluna başvurulabilir.

(2) Miktar veya değeri üç bin Türk Lirasını geçmeyen malvarlığı davalarına
ilişkin kararlar kesindir. Ancak manevi tazminat davalarında verilen kararlara
karşı, miktar veya değere bakılmaksızın istinaf yoluna başvurulabilir.

(3) Alacağın bir kısmının dava edilmiş olması durumunda üç bin Türk Liralık
kesinlik sınırı alacağın tamamına göre belirlenir.

(4) Alacağın tamamının dava edilmiş olması durumunda, kararda asıl talebinin
kabul edilmeyen bölümü üç bin Türk Lirasını geçmeyen taraf, istinaf yoluna
başvuramaz.

(5) İlk derece mahkemelerinin diğer kanunlarda temyiz edilebileceği veya
haklarında Yargıtaya başvurulabileceği belirtilmiş olup da bölge adliye
mahkemelerinin görev alanına giren dava ve işlere ilişkin nihai kararlarına
karşı, bölge adliye mahkemelerine başvurulabilir.
====

NOTE: Dönemsel edimler ihtiva eden bir karara karşı kanun yolu sınırını
belirlerken yıllık toplam miktar esas alınacaktır.

İstinafa prensip olaraka sadece taraflar gidebilir. Dolayısıyla fer'i müdahil
ilk derecede verilen karara karşı istinaf yoluna gidemez. Ancak fer'i müdahile
yönelik olarak doğrudan doğruya bür hüküm verilmişse fer'i müdahil de kendi
adına kanun yoluna müracaat edebilecektir. Bunun dışında fer'i müdahil anacak
yanında katıldığı taraf adına müracaat edebilir. Yanında katıldığı taraf açıkça
açıkça karşı koymadığı sürece onun adına kanun yoluna gidebilir.

IMPORTANT: Kanun yoluna başvurabilmek için hukuki yararın bulunması gerekir.

Kanun yoluna müracaat imkanı bulunmayan yahut süre geçtiği için başvuramayan
taraf, diğer tarafın kanun yolu başvurusuna ilişkin cevap dilekçesi vermek
suretiyle kendi istinaf sebeplerini ileri sürebilir. Buna *katılma yoluyla
kanun yoluna müracaat* denir. 

CAUTION: Kendi başınan istinafa yoluna müracaat etmiş taraf, bu yoldan feragat
ederse katılma yoluyla müracaat geçersiz hale gelir.

İstinafa müracaat dilekçe ile yapılır. 

[caption=""]
.İstinaf dilekçesi
====
*HMK 342*: (1) İstinaf yoluna başvurma, dilekçeyle yapılır ve dilekçeye, karşı
tarafın sayısı kadar örnek eklenir.

(2) İstinaf dilekçesinde aşağıdaki hususlar bulunur:

.. Başvuran ile karşı tarafın davadaki sıfatları, adı, soyadı, Türkiye
Cumhuriyeti kimlik numarası ve adresleri.
.. Varsa kanuni temsilci ve vekillerinin adı, soyadı ve adresleri.
.. Kararın hangi mahkemeden verilmiş olduğu ve tarihi ile sayısı.
.. Kararın başvurana tebliğ edildiği tarih.
.. Kararın özeti.
.. Başvuru sebepleri ve gerekçesi.
.. Talep sonucu.
.. Başvuranın veya varsa kanuni temsilci yahut vekilinin imzası.

(3) İstinaf dilekçesi, başvuranın kimliği ve imzasıyla, başvurulan kararı
yeteri kadar belli edecek kayıtları taşıması durumunda diğer hususlar bulunmasa
bile reddolunmayıp, 355 inci madde çerçevesinde gerekli inceleme yapılır.
====

İstinaf dilekçesinde ileri sürülmeyen bir husus -temyizden farklı olarak- dava
dosyasından anlaşılsa bile hiçbir şekilde dikkate alınamaz. Ancak HMK 355
uyarınca, kamu düzenine dair hususlar re'sen incelenir.

[caption=""]
.İncelemenin kapsamı
====
*HMK 355*: (1) İnceleme, istinaf dilekçesinde belirtilen sebeplerle sınırlı
olarak yapılır. Ancak, bölge adliye mahkemesi kamu düzenine aykırılık gördüğü
takdirde bunu resen gözetir.
====

İstinaf incelemesi iki aşamadan oluşur:

. *Ön inceleme*

.. _İncelemenin başka bir dairece yapılması gerektiği_
+
Re'sen ilgili daireye gönderilir.
.. _Kararın kesin olduğu_
+
Başvuru reddedilir.
.. _Başvurunun süresi içinde yapılmadığı_
+
Başvuru reddedilir.
.. _Başvuru şartlarının yerine getirilmediği_
+
Başvuru reddedilir.
.. _Başvuru şartlarının veya gerekçesinin hiç gösterilmediği_
+
HMK 355 çerçevesinde inceleme yapılır.

. *Esas inceleme*: Kural olarak duruşmalı şekilde yapılır. İlk dereceye ilişkin
hükümler bölge adliye mahkemesindeki duruşma için de uygulanır. Tarafların
duruşmaya gelmesi esastır. Ancak gelmemeleri durumunda HMK 150 (dosyanın
işlemden kaldırılması) uygulanmaz, dosyanın mevcut durumuna göre karar verilir.

İstinaf incelemesinde bazı hususlar dosya üzerinde incelenir.

[caption=""]
.Duruşma yapılmadan verilecek kararlar
====
*HMK 353*: (1) Ön inceleme sonunda dosyada eksiklik bulunmadığı anlaşılırsa;

.. Aşağıdaki durumlarda bölge adliye mahkemesi, esası incelemeden kararın
kaldırılmasına ve davanın yeniden görülmesi için dosyanın kararı veren
mahkemeye veya kendi yargı çevresinde uygun göreceği başka bir yer mahkemesine
ya da görevli ve yetkili mahkemeye gönderilmesine duruşma yapmadan kesin olarak
karar verir:

. Davaya bakması yasak olan hâkimin karar vermiş olması.
. İleri sürülen haklı ret talebine rağmen reddedilen hâkimin davaya bakmış
olması.
. Mahkemenin görevli ve yetkili olmasına rağmen görevsizlik veya yetkisizlik
kararı vermiş olması veya mahkemenin görevli ya da yetkili olmamasına rağmen
davaya bakmış bulunması veyahut mahkemenin bölge adliye mahkemesinin yargı
çevresi dışında kalması.
. Diğer dava şartlarına aykırılık bulunması.
. Mahkemece usule aykırı olarak davanın veya karşı davanın açılmamış
sayılmasına, davaların birleştirilmesine veya ayrılmasına, merci tayinine karar
verilmiş olması.
. Mahkemece, tarafların davanın esasıyla ilgili olarak gösterdikleri delillerin
hiçbiri toplanmadan veya gösterilen deliller hiç değerlendirilmeden karar
verilmiş olması.

.. Aşağıdaki durumlarda davanın esasıyla ilgili olarak;

. İncelenen mahkeme kararının usul veya esas yönünden hukuka uygun olduğu
anlaşıldığı takdirde başvurunun esastan reddine,
. Yargılamada eksiklik bulunmamakla beraber, kanunun olaya uygulanmasında hata
edilip de yeniden yargılama yapılmasına ihtiyaç duyulmadığı takdirde veya
kararın gerekçesinde hata edilmiş ise düzelterek yeniden esas hakkında,
. Yargılamada bulunan eksiklikler duruşma yapılmaksızın tamamlanacak nitelikte
ise bunların tamamlanmasından sonra yeniden esas hakkında,

duruşma yapılmadan karar verilir.
====

İstinafta yapılamayacak tahkikat işlemleri şunlardır:

. Karşı dava
. Davaya müdahale
. Davanın ıslahı
. HMK 166/1 saklı kalmak üzere davaların birleştirilmesi
. Re'sen göz önünde tutulacaklar dışında ilk derece mahkemesinde ileri
sürülmeyen bir iddia ve savunmanın ileri sürülmesi
. Yeni delillere dayanmak
+
Ancak aşağıdaki hallerde yeni delil sunulabilir:

.. İlk derece mahkemesinde usulüne uygun olarak gösterildiği halde incelenmeden
reddedilen deliller
.. Bir mücbir sebep sonucu gösterilmesine olanak bulunmayan deliller

Bölge adliye mahkemesi yapacağı inceleme neticesinde aşağıdaki kararlardan
birini vererek tahkikatı sona erdirir:

. *İstinaf başvurusunun reddi*

.. HMK 353/1-b'de düzenlenen ilk derece kararının usule ve esasa uygun olarak
verilmesi sebebiyle
.. HMK 352'ye göre istinafa başvuru şartları yerine getirilmemişse

. *İlk derece mahkemesi kararının kaldırılarak dosyanın görevli ve yetkili
mahkemeye gönderilmesi*
+
HMK 353/1-a bendinde düzenlenen 6 durumdan biri gerçekleşmişse bu karar
verilir.
. *İlk derece mahkemesi kararının kaldırılarak kısmen yahut tamamen davanın
kabulü*
. *İlk derece mahkemesi kararının kaldırılarak kısmen yahut tamamen davanın
reddi*

==== TEMYİZ

[caption=""]
.Temyiz edilebilen kararlar
====
*HMK 361*: (1) Bölge adliye mahkemesi hukuk dairelerinden verilen temyizi kabil
nihai kararlar ile hakem kararlarının iptali talebi üzerine verilen kararlara
karşı tebliğ tarihinden itibaren bir ay içinde temyiz yoluna başvurulabilir.

(2) Davada haklı çıkmış olan taraf da hukuki yararı bulunmak şartıyla temyiz
yoluna başvurabilir.
====

6100 sayılı HMK'ya göre temyiz incelemesi sadece hukuk açısından, yani usul
yahut maddi hukuk açısından uygulanması gereken kuralların doğru şekilde tespit
edilmiş ve uygulanmış olup olmadığının incelenmesine ayrılmış bir kurumdur.

Temyize sadece bölge adliye mahkemesinin kararlarına karşı gidilebileceği için
artık tek bir süre vardır. *Bu süre 1 aydır ve hiçbir istisnası yoktur*.

[caption=""]
.Temyiz edilemeyen kararlar
====
*HMK 362*: (1) Bölge adliye mahkemelerinin aşağıdaki kararları hakkında temyiz
yoluna başvurulamaz:

.. Miktar veya değeri kırk bin Türk Lirasını (bu tutar dâhil) geçmeyen davalara
ilişkin kararlar. 
.. 4 üncü maddede gösterilen davalar ile (23/6/1965 tarihli ve 634 sayılı Kat
Mülkiyeti Kanunundan doğup taşınmazın aynına ilişkin olan davalar hariç) özel
kanunlarda sulh hukuk mahkemesinin görevine girdiği belirtilen davalarla ilgili
kararlar.
.. Yargı çevresi içinde bulunan ilk derece mahkemeleri arasındaki yetki ve
görev uyuşmazlıklarını çözmek için verilen kararlar ile merci tayinine ilişkin
kararlar.
.. Çekişmesiz yargı işlerinde verilen kararlar.
.. Soybağına ilişkin sonuçlar doğuran davalar hariç olmak üzere, nüfus
kayıtlarının düzeltilmesine ilişkin davalarla ilgili kararlar.
.. Yargı çevresi içindeki ilk derece mahkemeleri hâkimlerinin davayı görmeye
hukuki veya fiilî engellerinin çıkması hâlinde, davanın o yargı çevresi
içindeki başka bir mahkemeye nakline ilişkin kararlar.
.. Geçici hukuki korumalar hakkında verilen kararlar.

(2) Birinci fıkranın (a) bendindeki kararlarda alacağın bir kısmının dava
edilmiş olması durumunda, kırk bin Türk Liralık kesinlik sınırı alacağın
tamamına göre belirlenir. Alacağın tamamının dava edilmiş olması hâlinde,
kararda asıl talebinin kabul edilmeyen bölümü kırk bin Türk Lirasını geçmeyen
tarafın temyiz hakkı yoktur. Ancak, karşı taraf temyiz yoluna başvurduğu
takdirde, diğer taraf da düzenleyeceği cevap dilekçesiyle kararı temyiz
edebilir.
====

===== BOZMA

*Temyiz (bozma) sebepleri*:

. Hukukun veya taraflar arasındaki sözleşmenin yanlış uygulanmış olması
. Dava şartlarına aykırılık bulunması
. Taraflardan birisinin davasını ispat için dayandığı delillerin kanuni bir
sebep olmaksızın kabul edilmemiş olması
. Karara etki eden bir yargılama hatası veya eksikliklerinin bulunması

TIP: Yargılamanın yenilenmesi sebepleri de karar henüz kesinleşmemişse bozma
sebebi olabilir.

Yukarıdaki sebeplerden bir tanesi söz konusu ise Yargıtay bozma kararı
verecektir. Bozma kararından sonra dosya kural olarak bölge adliye mahkemesine
gelecektir. Bunun üzerine bölge adliye mahkemesi iki tür karar verebilir: Uyma
veya direnme.

[caption=""]
.Bozmaya uyma veya direnme
====
*HMK 373*: (1) Yargıtay ilgili dairesinin tamamen veya kısmen bozma kararı,
başvurunun bölge adliye mahkemesi tarafından esastan reddi kararına ilişkin ise
bölge adliye mahkemesi kararı kaldırılarak dosya, kararı veren ilk derece
mahkemesine veya uygun görülecek diğer bir ilk derece mahkemesine, kararın bir
örneği de bölge adliye mahkemesine gönderilir.

(2) Bölge adliye mahkemesinin düzelterek veya yeniden esas hakkında verdiği
karar Yargıtayca tamamen veya kısmen bozulduğu takdirde dosya, kararı veren
bölge adliye mahkemesi veya uygun görülen diğer bir bölge adliye mahkemesine
gönderilir.

(3) Bölge adliye mahkemesi, 344 üncü madde uyarınca peşin alınmış olan gideri
kullanmak suretiyle, kendiliğinden tarafları duruşmaya davet edip dinledikten
sonra Yargıtayın bozma kararına uyulup uyulmayacağına karar verir.

(4) Yargıtayın bozma kararı üzerine ilk derece mahkemesince bozmaya uygun
olarak karar verildiği takdirde, bu karara karşı temyiz yoluna başvurulabilir.

(5) İlk derece mahkemesi veya bölge adliye mahkemesi kararında direnirse, bu
kararın temyiz edilmesi durumunda inceleme, kararına direnilen dairece yapılır.
Direnme kararı öncelikle incelenir. Daire, direnme kararını yerinde görürse
kararını düzeltir; görmezse dosyayı Yargıtay Hukuk Genel Kuruluna gönderir. (2)

(6) Davanın esastan reddi veya kabulünü içeren bozmaya uyularak tesis olunan
kararın önceki bozmayı ortadan kaldıracak şekilde yeniden bozulması üzerine alt
mahkemece verilen kararın temyiz incelemesi, her hâlde Yargıtay Hukuk Genel
Kurulunca yapılır.

(7) Hukuk Genel Kurulunun verdiği karara uymak zorunludur.
====

====== UYMA KARARI

Uyma kararı taraflar dinlenmeden verilebilecek bir karar değildir. Her
halükarda bölge adliye mahkemesi bir duruşma yapmalıdır. *Taraflardan her ikisi
de bozma kararına uyulmasını talep ederse mahkeme direnme kararı veremez*. Uyma
kararından sonra bölge adliye mahkemesi, bozma gerekçesi çerçevesinde bir
tahkikat incelemesi yapacak ve yeni bir karar verecektir.

Uyma kararından sonra verilen yeni karara karşı da temyize başvurulabilir.
Yargıtay ikinci temyiz incelemesinde ilk bozma kararı ile çelişen bir karar
veremez.

====
*HMK 373*: (6) Davanın esastan reddi veya kabulünü içeren bozmaya uyularak
tesis olunan kararın önceki bozmayı ortadan kaldıracak şekilde yeniden
bozulması üzerine alt mahkemece verilen kararın temyiz incelemesi, her hâlde
Yargıtay Hukuk Genel Kurulunca yapılır.
====

*HMK 373/6'nın açıklaması:* Örneğin, bölge adliye mahkemesi bir karar verdi ve
Yargıtay hukuk dairesi de bunu "kanuni faiz değil, reeskont faizi uygulanması
gerekirdi" diyerek bozdu. Dosya tekrar bölge adliye mahkemesine geldi ve bölge
adliye mahkemesi reeskont faizi uygulayarak tekrar karar verdi. Bu karara kaşı
tekrar temyize gidildi ve karar yine Yargıtay hukuk dairesine geldi. Yargıtay
hukuk dairesi bu defa da "avans faizi uygulanması gerekirdi" diyerek kararı
bozdu. Normalde usuli müktesep hakka ilişki içtihadı birleştirme kararına göre
bozmaması gerekir. Dosya tekrar bölge adliye mahkemesine geldi ve bölge adliye
mahkemesi avans faizi uygulayarak yeni bir karar verdi. Bu karar de temyiz
edildiğinde bunun temyiz inceleme mercii artık Yargıtay Hukuk Genel Kurulu
olacaktır.

====== DİRENME KARARI

Eğer taraflardan birisi bozma kararına direnirse, bölge adliye mahkemesi de
kendi kararının doğru olduğunu düşünüyorsa bozma kararına direnebilir. Hiçbir
tahkikat işlemi yapılmaz ve önceki verdiği karar bozma kararıyla ortadan
kaldırıldığı için aynı karar birebir yeniden yazılarak yeni bir karar verilir.

====
*HMK 373*: (5) İlk derece mahkemesi veya bölge adliye mahkemesi kararında
direnirse, bu kararın temyiz edilmesi durumunda inceleme, kararına direnilen
dairece yapılır. Direnme kararı öncelikle incelenir. Daire, direnme kararını
yerinde görürse kararını düzeltir; görmezse dosyayı Yargıtay Hukuk Genel
Kuruluna gönderir.
====

====== EYLEMLİ UYMA

Örneğin; 

Yargıtay hukuk dairesi, "Bu ihale çerçevesinde ortaya çıkan uyuşmazlıkta doğru
karar verilebilmesi için bakanlıktan ihale birim fiyatlarının alınması
gerekirdi" diyerek bölge adliye mahkemesinin verdiği kararı bozdu. Dosya bölge
adliye mahkemesine geldi. Bölge adliye mahkemesi bakanlıktan ihale birim
fiyatını sordu ve aldığı cevap neticesinde kararına değiştirilmesi gereken bir
şey olmadığını gördü ve aynı kararı verdi. Dolayısıyla direnme kararı vermiş
oldu.

Aslında bu adı itibariyle bir direnme kararı olsa da bir uyma kararıdır. Zira
bölge adliye mahkemesi kararı Yargıtay'ın göstermiş olduğu yöntemi uygulayarak
vermiştir. Dolayısıyla bu bir direnme kararı olmadığından bunun temyiz
incelemesi yine ilgili hukuk dairesi tarafından yapılacak. Hukuk dairesi kararı
beğenirse kendisi onayacak, beğenmezse de kendisi bozacak. Yani *beğenmezse
Yargıtay Hukuk Genel Kurulu'na göndermeyecek*.

===== SIÇRAMA YOLUYLA TEMYİZ

====
*HMK 373*: (1) Yargıtay ilgili dairesinin tamamen veya kısmen bozma kararı,
başvurunun bölge adliye mahkemesi tarafından esastan reddi kararına ilişkin ise
bölge adliye mahkemesi kararı kaldırılarak dosya, kararı veren ilk derece
mahkemesine veya uygun görülecek diğer bir ilk derece mahkemesine, kararın bir
örneği de bölge adliye mahkemesine gönderilir.
====

Kural olarak bölge adliye mahkemesinin kararı temyiz edilir ve Yargıtay
tarafından bozma kararı verilirse dosya tekrar bölge adliye mahkemesi önüne
gelir.

Ancak bölge adliye mahkemesi, ilk derece mahkemesi kararının usul veya esas
yönünde hukuka uygun bulunması sebebiyle başvurunun esastan reddine karar
vermiş ve bu karar temyiz edilmişse, Yargıtay hukuk dairesi bu kararı bozduğu
zaman dosya ilk derece mahkemesine gönderilir. Zira burada bölge adliye
mahkemesi karara etki etmemiştir, bozulan karar ilk derece mahkemesinin verdiği
karardır. İlk derece mahkemesinin verdiği yeni karara karşı kanun yolu olarak
istinafa değil, temyiz yoluna başvurulur. Buna da *sıçrama yoluyla temyiz*
denir.

== İHTİYATİ TEDBİR

*İhtiyati tedbir*, kesin hükme kadar davacı veya davalının, dava konusu ile
ilgili olarak hukuki durumlarında ortaya çıkabilecek zararlara karşı
öngörülmüş, geçici nitelikte, geniş yahut sınırlı hukuki himayedir.

Geçici hukuki himaye tedbirlerinden ihtiyati tedbir, uyuşmazlık konusu hak
veya şeyle ilgili olarak tatbik edilenidir. İhtiyati tedbirin konusu uyuşmazlık
konusunun bizatihi kendisidir.

IMPORTANT: PARA ALACAĞINDAN DOLAYI *İHTİYATİ HACİZ* İSTENİR!

[caption=""]
.İhtiyati tedbirin şartları
====
*HMK 389*: (1) Mevcut durumda meydana gelebilecek bir değişme nedeniyle hakkın
elde edilmesinin önemli ölçüde zorlaşacağından ya da tamamen imkânsız hâle
geleceğinden veya gecikme sebebiyle bir sakıncanın yahut ciddi bir zararın
doğacağından endişe edilmesi hâllerinde, uyuşmazlık konusu hakkında ihtiyati
tedbir kararı verilebilir.

(2) Birinci fıkra hükmü niteliğine uygun düştüğü ölçüde çekişmesiz yargı
işlerinde de uygulanır.
====

*Şartları*:

. İhtiyati tedbir yalnızca uyuşmazlık konusu hak veya şey hakkında verilebilir. 
. İhtiyati tedbir bir sebebe dayanmalıdır.
. İhtiyati tedbir talep eden taraf, davanın esası yönünden haklılığını yaklaşık
olarak ispat etmelidir.

[caption=""]
.İhtiyati tedbir talebi
====
*HMK 390*: (1) İhtiyati tedbir, dava açılmadan önce, esas hakkında görevli ve
yetkili olan mahkemeden; dava açıldıktan sonra ise ancak asıl davanın görüldüğü
mahkemeden talep edilir.

(2) Talep edenin haklarının derhâl korunmasında zorunluluk bulunan hâllerde,
hâkim karşı tarafı dinlemeden de tedbire karar verebilir.

(3) Tedbir talep eden taraf, dilekçesinde dayandığı ihtiyati tedbir sebebini ve
türünü açıkça belirtmek ve davanın esası yönünden kendisinin haklılığını
yaklaşık olarak ispat etmek zorundadır.
====

Asıl yargılama bakımından hangi usul uygulanırsa uygulansın tedbir talebi her
halükarda basit usule göre incelenecektir.

Tedbir talebinin mahkemeye yöneltilmesinden sonra mahkeme çoğunlukla dosya
üzerinden, bazen de duruma göre duruşma yaparak tedbir talebinin kabulüne veya
reddine ilişkin bir karar verir.

Karşı taraf dinlenmeksizin de tedbire karar verilebilir.

Mahkeme ihtiyati tedbir talebini kabul edecek olursa, kararında ihtiyati
tebdirin ne olduğunu ve bu kararın nasıl, ne şekilde ve kim tarafından
uygulanacağını belirtmelidir. Mahkeme kararın ne olduğunu ve sınırlarını
kendisi belirleyecektir. Zira tedbir kararını uygulayacak olan icra memuruna
veya mahkemenin yazı işleri müdürüne ancak bu çerçevede bir yetki verilecektir.

Kanun koyucu, lehine tedbire karar verilen kişinin davada haksız çıkması ve
bundan dolayı aleyhine tedbir kararı verilmiş kişinin bir zarara uğraması
ihtimali için özel olarak bir tazminat davası düzenlemiştir. O tazminat
davasının güvencesi olmak üzere de daha tedbir kararı alınırken bir teminat
verilmesini öngörmüştür.

Her durumda teminat verilmesi gerekmez:

. Tedbir talebi resmi belgeye dayanıyorsa
. Tedbir talebi kesin delile dayanıyorsa
. Durum ve koşullar gerektiriyorsa
. Adil yardımdan yararlanılıyorsa

[caption=""]
.Tazminat
====
*HMK 399*: (1) Lehine ihtiyati tedbir kararı verilen taraf, ihtiyati tedbir
talebinde bulunduğu anda haksız olduğu anlaşılır yahut tedbir kararı
kendiliğinden kalkar ya da itiraz üzerine kaldırılır ise haksız ihtiyati tedbir
nedeniyle uğranılan zararı tazminle yükümlüdür.

(2) Haksız ihtiyati tedbirden kaynaklanan tazminat davası, esas hakkındaki
davanın karara bağlandığı mahkemede açılır.

(3) Tazminat davası açma hakkı, hükmün kesinleşmesinden veya ihtiyati tedbir
kararının kalkmasından itibaren, bir yıl geçmesiyle zamanaşımına uğrar.
====

Tedbir talebini alan mahkeme önce tedbir yargılamasını yapar. Tedbirin
şartlarının mevcut olup olmadığını inceler. Bu incelemeyi tamamladıktan sonra
tedbire karar verilmesi gerektiğine kanaat getirirse tedbirin teminatlı mı
teminatsız mı olacağına karar verir. Eğer tedbirin teminatlı olarak verilmesi
gerektiğine karar verirse tedbir kararını bu şartla verir. Bu durumda tedbir
kararı verilmiştir ama tedbir kararını mahkemeden alıp icra ettirebilmek için
teminatı yatırmak gerekir.

İhtiyati tedbir kararı geçici bir karardır. Maddi anlamda bir kesin hüküm
oluşturmaz. Ancak prensip olarak da kesin bir karardır. Geçici ama uygulaması
kabildir. Bu karar aksi belirtilmedikçe nihai kararın kesinleşmesine kadar
devam edecektir.

IMPORTANT: Tedbir kararının verilmesinden itibaren 1 hafta içinde uygulanması
istenmelidir. Eğer tedbir talebi bu süre içinde yapılmazsa tedbir kararı
kendiliğinden kalkacaktır.

Tedbir kararını prensip olarak icra dairesi uygulayacaktır. Ancak bazı tedbir
türlerinde mahkemenin yazı işleri müdürü tedbiri doğrudan uygulayabilir.

*İhtiyati tedbiri tamamlayan merasim*, özellikle tedbir talebinin davadan önce
istendiği ve mahkemenin de tedbire dava açılmadan önce karar verdiği hallerde
söz konusu olur.

[caption=""]
.İhtiyati tedbiri tamamlayan işlemler
====
*HMK 397*: (1) İhtiyati tedbir kararı dava açılmasından önce verilmişse, tedbir
talep eden, bu kararın uygulanmasını talep ettiği tarihten itibaren iki hafta
içinde esas hakkındaki davasını açmak ve dava açtığına ilişkin evrakı, kararı
uygulayan memura ibrazla dosyaya koydurtmak ve karşılığında bir belge almak
zorundadır. Aksi hâlde tedbir kendiliğinden kalkar.

(2) İhtiyati tedbir kararının etkisi, aksi belirtilmediği takdirde, nihai
kararın kesinleşmesine kadar devam eder.

(3) Tedbir kalkmış veya kaldırılmış ise bu husus ilgili yerlere bildirilir.

(4) İhtiyati tedbir dosyası, asıl dava dosyasının eki sayılır.
====

İhtiyati tedbir kararının verildiği andan itibaren 1 hafta içerisinde
uygulanması talep edilmelidir. Tedbirin uygulanmasının talep edildiği tarihten
itibaren 2 hafta içerisinde de asıl dava açılmalıdır. Ayrıca asıl davanın
açıldığına dair belge, tedbiri uygulayan icra dairesine veya mahkemenin yazı
işlerine verilmelidir. Aksi takdirde tedbir kendiliğinden kalkar.

İhtiyati tedbir kararı verilirken dinlenmemiş olan taraf, tedbir kararına
itiraz edebilir. Ancak taraf dinlenmişse, tedbir aleyhine bile olsa itiraz
hakkını kullanamaz.

[caption=""]
.İhtiyati tedbir kararına karşı itiraz
====
*HMK 394*: (1) Karşı taraf dinlenmeden verilmiş olan ihtiyati tedbir
kararlarına itiraz edilebilir. Aksine karar verilmedikçe, itiraz icrayı
durdurmaz.

(2) İhtiyati tedbirin uygulanması sırasında karşı taraf hazır bulunuyorsa,
tedbirin uygulanmasından itibaren; hazır bulunmuyorsa tedbirin uygulanmasına
ilişkin tutanağın tebliğinden itibaren bir hafta içinde, ihtiyati tedbirin
şartlarına, mahkemenin yetkisine ve teminata ilişkin olarak, kararı veren
mahkemeye itiraz edebilir.

(3) İhtiyati tedbir kararının uygulanması sebebiyle menfaati açıkça ihlal
edilen üçüncü kişiler de ihtiyati tedbiri öğrenmelerinden itibaren bir hafta
içinde ihtiyati tedbirin şartlarına ve teminata itiraz edebilirler.

(4) İtiraz dilekçeyle yapılır. İtiraz eden, itiraz sebeplerini açıkça göstermek
ve itirazının dayanağı olan tüm delilleri dilekçesine eklemek zorundadır.
Mahkeme, ilgilileri dinlemek üzere davet eder; gelmedikleri takdirde dosya
üzerinden inceleme yaparak kararını verir. İtiraz üzerine mahkeme, tedbir
kararını değiştirebilir veya kaldırabilir.

(5) İtiraz hakkında verilen karara karşı, kanun yoluna başvurulabilir. Bu
başvuru öncelikle incelenir ve kesin olarak karara bağlanır. Kanun yoluna
başvurulmuş olması, tedbirin uygulanmasını durdurmaz.
====

İhtiyati tedbir kararının kabulüne karşı kanun yoluna ancak itiraz üzerine
verilen karara karşı başvurulabilir. Ancak ihtiyati tedbir kararı baştan
reddedildiyse kanun yoluna direkt başvurulabilir.

Aleyhine tebdir kararı verilmiş kişi mahkemeyi ikna etmek suretiyle başka bir
teminat göstererek tedbiri kaldırabilir. Bu karara karşı kanun yoluna müracaat
imkanı yoktur.

== TAHKİM

*Tahkim*, uyuşmazlığın kanunun gösterdiği ya da kanun gereğince uyuşmazlığın
taraflarının belirlediği hakemler tarafından çözülmesi kurumudur.

Tahkimde hakemler eliyle verilen kararlar her halükarda yargı denetimine tabi
tutulduğu için, yargı yetkisinin hakimler eliyle kullanılacağını düzenleyen
Anayasa hükmüne aykırılık oluşturmaz.

Tahkim zorunlu veya ihtiyari olabilir:

. *Zorunlu tahkim*: Taraflar söz konusu uyuşmazlığı isteseler bile mahkeme
önüne getiremezler. Kanunun öngördüğü kişi ya da organlara müracaat zorunludur.

.. Zorunlu Tahkim Kanunu'na göre iki kamu kurumu arasında özel hukuka dair bir
uyuşmazlık çıkması durumunda o yerdeki en kıdemli asliye hukuk hakimi hakem
olarak bu uyuşmazlığa bakar.
.. Tüketicinin Korunması Hakkında Kanun'a göre 3.000 TL'nin altındaki
uyuşmazlıklar için tüketici hakem heyetine başvurulur.

. *İhtiyari tahkim*: Taraflar, üzerinde serbestçe tasarruf edebilecekleri
uyuşmazlıklar hakkında, kendi aralarında anlaşarak söz konusu uyuşmazlığı
kendilerinin belirleyeceği hakem veya hakemler aracılığıyla çözmeyi
kararlaştırabilirler.
+
Tahkim anlaşması, ayrı bir sözleşme ile yapılabileceği gibi sözleşmenin içinde
bir şart olarak da yapılabilir.

Hakemlerin nasıl seçileceğini prensip olarak taraflar belirler. Hakemlerin
hukukçu olması şart değildir. Sadece HMK tahkimine göre birden fazla hakem söz
konusuysa üçüncü hakemin hukukçu olması şartı vardır.

İki tip tahkim vardır:

. *Ad-hoc tahkim*: Her bir uyuşmazlık için tarafların yapmış olduğu tahkim
sözleşmesi çerçevesinde hakem heyeti kurulmasıdır.
. *Kurumsal tahkim*: Uyuşmazlıkların tahkim yoluyla çözülmesi amacıyla kurulmuş
müesseseler vardır.

=== TAHKİM SÖZLEŞMESİ

[caption=""]
.Tahkim sözleşmesinin tanımı ve şekli
====
*HMK 412*: (1) Tahkim sözleşmesi, tarafların, sözleşme veya sözleşme dışı bir
hukuki ilişkiden doğmuş veya doğabilecek uyuşmazlıkların tamamı veya bir
kısmının çözümünün hakem veya hakem kuruluna bırakılması hususunda yaptıkları
anlaşmadır.

(2) Tahkim sözleşmesi, taraflar arasındaki sözleşmenin bir şartı veya ayrı bir
sözleşme şeklinde yapılabilir.

(3) Tahkim sözleşmesi yazılı şekilde yapılır. Yazılı şekil şartının yerine
getirilmiş sayılması için, tahkim sözleşmesinin taraflarca imzalanmış yazılı
bir belgeye veya taraflar arasında teati edilen mektup, telgraf, teleks, faks
gibi bir iletişim aracına veya elektronik ortama geçirilmiş olması ya da dava
dilekçesinde yazılı bir tahkim sözleşmesinin varlığının iddia edilmesine
davalının verdiği cevap dilekçesinde itiraz edilmemiş olması yeterlidir. Asıl
sözleşmenin bir parçası hâline getirilmek amacıyla tahkim şartı içeren bir
belgeye yollama yapılması hâlinde de tahkim sözleşmesi yapılmış sayılır.

(4) Tahkim sözleşmesine karşı, asıl sözleşmenin geçerli olmadığı veya tahkim
sözleşmesinin henüz doğmamış olan bir uyuşmazlığa ilişkin olduğu itirazında
bulunulamaz.

(5) Yargılama sırasında tarafların tahkim yoluna başvurma konusunda anlaşmaları
hâlinde, dava dosyası mahkemece ilgili hakem veya hakem kuruluna gönderilir.
====

Tahkim sözleşmesi yazılı olarak yapılmalıdır. Dava dilekçesinde yazılı bir
tahkim sözleşmesinin varlığının iddia edilmesine davalının cevap dilekçesinde
itiraz etmemiş olması da yeterlidir.

Tahkim sözleşmesinin geçerli olabilmesi için uyuşmazlığın belirli veya
belirlenebilir olması gerekir. Ayrıca uyuşmazlığın özel hukuktan kaynaklanması
ve tarafların üzerinde serbestçe tasarruf etme yetkisinin olması gerekir.

NOTE: Yargıtay uygulamasına göre taşınmazın aynına ilişkin uyuşmazlıklarda
ihtiyari tahkime izin verilmemektedir.

=== HAKEMLERİN SEÇİMİ VE HAKEM SÖZLEŞMESİ

Hakemlerin nasıl seçileceğini taraflar belirleyeceklerdir. Taraflar bunu
kendileri yapabilecekleri gibi üçüncü bir kişiye yahut kuruma da
bırakabilirler.

Hakem sayısıı bir kişi olabileceği gibi, tek sayıda olmak üzere birden fazla
kişi de olabilir. Eğer birden fazla kişi hakem olacaksa kanun birinin 5 yıl
veya daha fazla kıdeme sahip hukukçu olmasını arıyor.

Tahkim sözleşmesi çerçevesinde uyuşmazlığı çözecek olan hakemlerle taraflar
arasında yapılacak sözleşmeye hakem sözleşmesi denir. Kabul edilen görüş bunun
bir vekalet sözleşmesi olduğudur.

=== DAVANIN AÇILDIĞI TARİH

Eğer sözleşmeye göre hakemlerin seçimi iki tarafa bağlıysa davacının hakemini
seçip kendi hakemini seçmesini diğer tarafa bildirdiği tarih itibariyle dava
açılmış olur. Dolayısıyla bu tarihte zamanaşımı kesilir.

Eğer hakemi bir kurum seçecekse, kuruma başvurulduğu andan itibaren dava
açılmış sayılır.

=== YARGILAMA USULÜ

Yargılama usulü taraflarca belirlenir. Dolayısıyla HMK uygulanmak zorunda
değildir. Eğer taraflar bir belirleme yapmamışlarsa hakem heyeti kendince bir
usul belirleyebilir. Ancak hakem heyetinin kendi belirlediği yargılama usulüne
uymamış olması hakemlerin kararının iptali için yeterli değildir; yeter ki
hukuki dinlenilme hakkı ihlal edilmemiş olsun.

=== SÜRE

Tahkim süresi 1 yıldır. Bu 1 yıllık süre hakem heyetinin ilk toplantı
tarihinden itibaren başlar.

Süre, tarafların anlaşmasıyla veya mahkeme kararıyla uzatılabilir. Süresi
içinde karar verilmemesi bir iptal sebebidir.

=== İPTAL DAVASI

Hakemler, uyuşmazlığın çözümü için her türlü yargılama işlemini yapabilirler.
Fakat kamu gücünün kullanılmasını gerektiren işlemleri yapamazlar. Örneğin
yemin verdiremezler. Bu tip işler için mahkemeden yardım istenir.

Hakemler uyuşmazlığın çözümü için bir karar vermek zorundadır. Bu karara karşı
HMK 439'da belirtilmiş sebeplerde iptal davası açılabilir.

[caption=""]
.İptal davası
====
*HMK 439*: (1) Hakem kararına karşı yalnızca iptal davası açılabilir. İptal
davası, tahkim yerindeki mahkemede açılır; öncelikle ve ivedilikle görülür.

(2) 

.. Tahkim sözleşmesinin taraflarından birinin ehliyetsiz ya da tahkim
sözleşmesinin geçersiz olduğu,
.. Hakem veya hakem kurulunun seçiminde, sözleşmede belirlenen veya bu Kısımda
öngörülen usule uyulmadığı,
.. Kararın, tahkim süresi içinde verilmediği,
.. Hakem veya hakem kurulunun, hukuka aykırı olarak yetkili veya yetkisiz
olduğuna karar verdiği,
.. Hakem veya hakem kurulunun, tahkim sözleşmesi dışında kalan bir konuda karar
verdiği veya talebin tamamı hakkında karar vermediği ya da yetkisini aştığı,
.. Tahkim yargılamasının, usul açısından sözleşmede veya bu yönde bir sözleşme
bulunmaması hâlinde, bu Kısımda yer alan hükümlere uygun olarak yürütülmediği
ve bu durumun kararın esasına etkili olduğu,
.. Tarafların eşitliği ilkesi ve hukuki dinlenilme hakkına riayet edilmediği,
.. Hakem veya hakem kurulu kararına konu uyuşmazlığın Türk hukukuna göre
tahkime elverişli olmadığı,
.. Kararın kamu düzenine aykırı olduğu,

tespit edilirse, hakem kararları iptal edilebilir.

(3) Hakem veya hakem kurulunun, tahkim sözleşmesi dışında kalan bir konuda
karar verdiği iddiasıyla açılan iptal davasında, tahkim sözleşmesi kapsamında
olan konuların, tahkim sözleşmesi kapsamında olmayan konulardan ayrılması
mümkün olduğu takdirde, hakem kararının sadece tahkim sözleşmesi kapsamında
olmayan konuları içeren bölümü iptal edilebilir.

(4) İptal davası, bir ay içinde açılabilir. Bu süre, hakem kararının veya
tavzih, düzeltme ya da tamamlama kararının taraflara bildirildiği tarihten
itibaren işlemeye başlar. Hakem kararına karşı iptal davası açılması kararın
icrasını durdurmaz. Ancak taraflardan birinin talebi üzerine hükmolunan para
veya eşyanın değerini karşılayacak bir teminat gösterilmek şartı ile kararın
icrası durdurulabilir.

(5) İptal talebi, davaya bakan mahkeme aksine karar vermedikçe, dosya üzerinden
incelenerek karara bağlanır.

(6) İptal davası hakkında verilen kararlara karşı temyiz yoluna başvurulabilir.
Temyiz incelemesi, bu maddede yer alan iptal sebepleriyle sınırlı olarak,
öncelikle ve ivedilikle karara bağlanır. Temyiz, kararın icrasını durdurmaz.

(7) İptal davasının kabulü hâlinde, kabul kararı temyiz edilmezse veya ikinci
fıkranın (b), (d), (e), (f) ve (g) bentlerindeki hâllerin varlığı sebebiyle
kabulü hâlinde, taraflar aksini kararlaştırmamışlarsa hakemleri ve tahkim
süresini yeniden belirleyebilirler.  Taraflar isterlerse eski hakemleri tayin
edebilirler.
====

Hakem heyetinin kararına karşı sadece HMK 439'daki sebeplerle iptal davası
açılabilir. İptal kararından sonra verilen kararlara karşı kanun yoluna
gidilebilir.
