:icons: font

== MEDENİ USUL

* Yargı işlemi iki ölçüte göre belirlenir. Bunlar birbirinin alternatifi değil,
  tamamlayıcısıdır.

. *Organik ölçüt*: Mahkemenin yaptığı tüm işlemler yargılama işlemi olarak
  değerlendirilir. Buradaki temel ölçüt, talebin yöneldiği mercii niteliğidir.
  Eğer bu mercii, yargı işlemini üstlenen mercii, yani mahkeme ise o işlem
  yargılama işlemi olarak değerlendirilir ve bu işlem neticesinde doğacak sonuç
  yargı işleminden doğan bir sonuç olarak kabul edilir.
. *Maddi ölçüt*: Yargılama işlemini üstlenmiş mahkemeler tarafından soyut hukuk
  kurallarının somut ihtilafa uygulanmasıdır.

* Yargılama esnasında, davacı (lehine hukuki koruman talep eden) iddia eder,
  iddianın usuli işlemi dava dilekçesidir. Davalı savunma yapar, usuli işlemi
  cevap dilekçesidir. Hakim ise tez (davacının iddiası) ve antiteze (davalının
  cevabı) dayanarak sentez yapar, usuli işlemi hüküm vermektir.

* *Lex fori* ilkesine göre, yargılama yapan hakim, muhakeme hukuku hükümleri
  açısından her zaman kendi hukukunu uygulayarak hükme varır. Tarafların
  yabancı olması, ihtilafın yabancı menşeinde olmasının hiçbir önemi yoktur. 
+
Tarafların arasındaki ihtilafta tatbik edilecek maddi hukuk hükümlerinde eğer
yabancı bir hukuk kaynağı belirlenmiş ise bu durumda hakim lex fori ilkesine
göre kendi usul hukukunu uygular ana esasa ilişkin kararını verirken, yani
*altlama* faaliyetini gerçekleştirirken yabancı maddi hukuk hükümlerinden
istifade etmek zorundadır. Zira artık tarafların tasarrufuna tabi bir saha söz
konusudur.
+
Yine yabancı hukukun tatbik edileceğini kararlaştırmış olan tarafların
aralarındaki sözleşmesel ilişkide yabancı hukuk menşei deliller, belgeler
sunmaları ya da bu nitelikte iddiaları ortaya koymaları da mümkündür. *_Locus
Legit Actum_* ilkesine göre kullanılacak delillerin yabancı hukuka uygun bir
şekilde düzenlenmiş olması halinde lex fori ilkesine göre uygulamayı
gerçekleştiren hakimi bağlayacaktır.
+
[NOTE]
====
Yabancı iki kişinin dava ehliyeti ya da taraf ehliyetine ilişkin tespitler HMK
çerçevesinde mi yoksa tarafların tabi olduğu devletteki düzenlemeye göre mi
yapılmalıdır? Davanın tarafı olan gerçek kişi tabiatında bulunduğu devlette
rüştünü ispatlamış ve fiil ehliyetine sahip ama Türk hukukuna göre mümeyyiz
değil ise Türk mahkemesi hangi hükmü tatbik edecektir?  

_Kürsü ve Yargıtay'a göre_ bu durumda kişinin tabi olduğu devletin hukuku esas
alınır ve fiil ehliyeti varmış gibi kabul edilir. Ancak hakim kişinin fiil
ehliyetine sahip olduğu kabul edildiğinde hak kaybına uğrayacağına takdir
ederse Türk hukukunu uygular.  
====

* Davanın açılması ardından şekli hukuka dair hükümlerde gerçekleşmiş olan
  değişiklikler, hangi aşamadaysa doğrudan yargılama tesir eder. *Tek istisna
  tamamlanmış olan işlemlerdir*. Bir işlemin usul hukuku açısından tamamlanmış
  olup olmadığını tespit etmek usuli işlemin niteliğine göre farklılık arz
  eder.
+
[caption=""]
.Zaman bakımından uygulanma
====
*HMK 448*: Bu Kanun hükümleri, tamamlanmış işlemleri etkilememek kaydıyla
derhâl uygulanır.
====
+
CAUTION: Bir ihtilafın esasına uygulanacak hukuk kuralları ihtilafın
gerçekleştiği tarih esas alınarak bulunur. İhtilafın çözüme kavuşabilmesi için
dava açıldığında davada uygulanacak şekli hukuk kuralları davanın açıldığı
tarih göz önüne alınarak tespit edilir.
+
NOTE: 2010 yılında 1086 sayılı kanuna uygun şekilde yetki sözleşmesi yapılmış
ise 2016 yılında açılacak davada bu sözleşmenin bir etkisi olacak mıdır? _Kürsü
ve Yargıtay'ın görüşüne göre_ usul hukukuna ilişkin işlemler ve sözleşmeler
alan kriterine göre tespit edilir. Sonuç almayı hedeflediği alan yargılama
hukuku ise yargılama hukukunda sonuç almayı hedeflediği an geçerli şekli hukuka
dair hükümler geçmişte yapılmış olsa dahi o işlem veya sözleşmeye birebir
tatbik edilir.

* Yargılama faaliyetini yürütürken hakim ve davanın tarafları genel hükümlere
  göre hareket eder ve ondan doğacak boşlukları yargılama ait ilkeler ile
  doldurur. Şekli hukuka dair hükümlerin sınırları nettir, bu yüzden *yorum ve
  kıyasa müsait değildir*. Ancak kanunun izin verdiği hallerde kıyas
  yapılabilir.

<<<

=== Uyuşmazlık Mahkemesi

* Hukuk mahkemesi önünde görülen bir yargılama esasında idari yargılamanın
  görev alanına girdiği iddiası varsa, bu *yargı yolu itirazıdır*. Uyuşmazlık
  mahkemesi ağırlıklı olarak idari yargı ile adli yargı arasında doğabilecek
  yargı yolu ihtilaflarının çözümü ile ilgilenir. 

. *Olumsuz görev uyuşmazlığı*: Adli, idari ve askeri mercilerden en az ikisinin;
  tarafları, konusu ve sebebi aynı olan davada kendilerini görevsiz görmeleri
  ve bu noktada verilmiş olan kararların kesinleşmiş olması gerekir.  
+
====
*Uyuşmazlık Mahkemesi Kanunu 14*: (1) Olumsuz görev uyuşmazlığının bulunduğunun
ileri sürülebilmesi için adli, idari veya askeri yargı mercilerinden en az
ikisinin tarafları, konusu ve sebebi aynı olan davada kendilerini görevsiz
görmeleri ve bu yolda verdikleri kararların kesin veya kesinleşmiş olması
gerekir.

(2) Bu uyuşmazlığın giderilmesi istemi, ancak davanın taraflarınca ve ceza
davalarında ise ayrıca ilgili makamlarca ileri sürülebilir.
====
+
====
*Uyuşmazlık Mahkemesi Kanunu 15*: Olumsuz görev uyuşmazlıklarında dava
dosyaları, son görevsizlik kararını veren yargı merciince, bu kararın
kesinleşmesinden sonra, ceza davalarında doğrudan doğruya diğer davalarda ise
taraflardan birinin istemi üzerine, ilk görevsizlik kararını veren yargı
merciine ait dava dosyası da temin edilerek Uyuşmazlık Mahkemesine gönderilir
ve görevli yargı merciinin belirlenmesi istenir.
====
. *Olumlu görev uyuşmazlığı*: Tarafları, konusu ve sebebi aynı olan bir davada
  hem hukuk mahkemesi hem de idari mahkeme kendini görevli görmektedir. Burada
  da uyuşmazlığın giderilmesini taraflar talep edecektir. Davanın açıldığı
  tarihe göre, daha sonra dava açılmış mercii huzurunda bir müracatta
  bulunularak dosyaların uyuşmazlık mahkemesine gönderilmesi talep edilecektir.
+
====
*Uyuşmazlık Mahkemesi Kanunu 17/1*: Olumlu görev uyuşmazlığı;adli, idari ve
askeri yargıya bağlı ayrı iki yargı merciine açılan ve tarafları, konusu ve
sebebi aynı olan davalarda bu yargı mercilerinin her ikisinin kendilerini
görevli sayan kararlar vermiş olmaları, görev kararlarına karşı itiraz yolunun
açık olduğu ceza davalarında bu kararların kesinleşmiş bulunması durumunda
meydana gelir.  
==== 
. *Olumlu görev uyuşmazlığı çıkarma*: Yargı merciinde görevli Cumhuriyet
  savcısı re'sen uyuşmazlık mahkemesine müracaat ederek uyuşmazlık çıkarabilir.
+
====
*Uyuşmazlık Mahkemesi Kanunu 10*: (1) Görev uyuşmazlığı çıkarma; adli, idari ve
askeri bir yargı merciinde açılmış olan davada ileri sürülen görev itirazının
reddi üzerine ilgili Başsavcı veya Başkanunsözcüsü tarafından görev konusunun
incelenmesinin Uyuşmazlık Mahkemesinden istenmesidir.

(2) Yetkili Başsavcı veya Başkanunsözcüsünün Uyuşmazlık Mahkemesinden istekte
bulunabilmesi için, görev itirazının, hukuk mahkemelerinde en geç birinci
oturumda, ceza mahkemelerinde delillerin ikamesine başlamadan önce; idari yargı
yerlerinde de dilekçe ve savunma evresi tamamlanmadan yapılmış olması ve yargı
yerlerinin de kendilerinin görevli olduklarına karar vermiş bulunmaları
şarttır.

(3) Görev itirazının yargı merciince yerinde görülerek görevsizlik kararı
verilmesi halinde, görev konusunun Uyuşmazlık Mahkemesince incelenebilmesi,
temyizen bu kararın bozulmuş ve yargı merciince de bozmaya uyularak görevli
olduğuna karar verilmiş bulunmasına bağlıdır.

(4) Uyuşmazlık çıkarma isteminde bulunmaya yetkili makam; reddedilen
görevsizlik itirazı adli yargı yararına ileri sürülmüş ise Cumhuriyet
Başsavcısı, idari yargı yararına ileri sürülmüş ise Danıştay Başkanunsözcüsü,
askeri ceza yargısı yararına ileri sürülmüş ise Askeri Yargıtay Başsavcısı,
Askeri İdari Yargı yararına ileri sürülmüş ise bu mahkemenin
Başkanunsözcüsüdür.

(5) Görev itirazının reddine ilişkin karara karşı itiraz yolunun açık bulunduğu
ceza davalarında ret kararı kesinleşmeden uyuşmazlık çıkarma istenemez. 
====
. *Temyiz incelemesi yapan merciin başvurusu*: Yargıtay hukuk dairesi önüne
  gelmiş olan ihtilafta, muhalefet olsun veya olmasın, esasen idari yargının
  görevine girdiğini görmüş ya da buna ihtimal vermişse kararı bozmayıp
  davayı doğrudan Uyuşmazlık Mahkemesine gönderebilir.
+
====
*Uyuşmazlık Mahkemesi Kanunu 20*: Daha önce Uyuşmazlık Mahkemesince yargı
mercii belirtilmemiş olan bir davada temyiz incelemesi yapan yüksek mahkeme,
davanın, davaya bakan mahkemenin görevi dışında olduğu kanısına varırsa,
incelediği kararı bozacak yerde, incelemeyi erteleyerek yargı merciinin
belirtilmesi için Uyuşmazlık Mahkemesine başvurmaya karar verebilir.  
====
+
====
*Uyuşmazlık Mahkemesi Kanunu 18*: (1) Uyuşmazlık Mahkemesine başvurulduğu resmi
yazı ile kendisine bildirilen yargı mercii, görev konusunda Uyuşmazlık
Mahkemesince bir karar verilinceye kadar davanın görülmesini geri bırakır. Bu
takdirde zamanaşımı süreleriyle öbür kanuni veya hakim tarafından verilen
süreler, işin yeniden incelenmesine başlanacağı güne kadar durur.

(2) Şu kadar ki, Uyuşmazlık Mahkemesine başvurulduğunu bildiren yazının
alındığı günden başlamak üzere altı ay içinde bu Mahkemenin kararı gelmezse
yargı mercii davayı görmeye devam eder. Ancak, esas hakkında son kararı
vermeden Uyuşmazlık Mahkemesinin kararı gelirse yargı mercii bu karara uymak
zorundadır.

(3) Uyuşmazlık çıkarılacağı bildirilerek yargı merciinden davaya bakmanın
ertelenmesi istenemez.

(4) (Ek fıkra: 23/7/2008 – 5791/8 md.) 12, 13 ve 17 nci maddelerde yazılı
sürelerin bitmesi çalışmaya ara verme zamanına rastlarsa bu süreler, çalışmaya
ara vermenin sona erdiği günü izleyen tarihten itibaren yedi gün uzamış
sayılır.
====
+
TIP: Mahkemeler tarafından verilmiş geçici hukuki koruma tedbirleri muhafaza
olunur, dosyanın Uyuşmazlık Mahkemesine intikali sebebiyle geçerliliğini
yitirmez.
+
====
*Uyuşmazlık Mahkemesi Kanunu 34*: Uyuşmazlık Mahkemesinde karar bağlanacak
işler için verilecek dilekçeler, layihalar, yazılar veya belgelerden,
mahkemenin işlemlerinden, kararlarından veya mahkemece yahut mahkemeden
istenilecek belge veya karar örneklerinden herhangi bir vergi veya harç
alınmaz.
====

* Aynı konu, aynı sebebe ilişkin, taraflardan en az biri aynı olan kararlar
  arasında çelişki varsa ve bu çelişkiden dolayı hakkın yerine getirilmesi
  mümkün olmuyorsa *hüküm uyuşmazlığı* vardır. Bu durumda uyuşmazlık
  mahkemesine taraflar tarafından müracaat edilerek hangi hükmün esas alınması
  gerektiğine dair bir karar verilir ve verilecek karar kesindir.

<<<

=== Hukuk mahkemeleri

====
*5235 sayılı kanun 4*: Hukuk mahkemeleri, sulh hukuk ve asliye hukuk
mahkemeleri ile özel kanunlarla kurulan diğer hukuk mahkemeleridir.
====

. _Genel mahkemeler_

.. *Asliye Hukuk Mahkemesi*
+
====
*HMK 2*: (1) Dava konusunun değer ve miktarına bakılmaksızın malvarlığı
haklarına ilişkin davalarla, şahıs varlığına ilişkin davalarda görevli mahkeme,
aksine bir düzenleme bulunmadıkça asliye hukuk mahkemesidir.

(2) Bu Kanunda ve diğer kanunlarda aksine düzenleme bulunmadıkça, asliye hukuk
mahkemesi diğer dava ve işler bakımından da görevlidir.
====
+
====
*5235 sayılı kanun 6/2*: Asliye hukuk mahkemeleri, sulh hukuk mahkemelerinin
görevleri dışında kalan ve özel hukuk ilişkilerinden doğan her türlü dava ve
işler ile kanunların verdiği diğer dava ve işlere bakar.
====
+
Asliye hukuk mahkemesinin yargılama usulü, temel yargılama usulü olan yazılı
yargılama usulüdür. 
+
WARNING: Asliye hukuk ile sulh hukuk arasındaki ayrım *görev ayrımıdır*.
.. *Sulh Hukuk Mahkemesi*
+
====
*HMK 4*: (1) Sulh hukuk mahkemeleri, dava konusunun değer veya tutarına
bakılmaksızın;

a) Kiralanan taşınmazların, 9/6/1932 tarihli ve 2004 sayılı İcra ve İflas
Kanununa göre ilamsız icra yoluyla tahliyesine ilişkin hükümler ayrık olmak
üzere, kira ilişkisinden doğan alacak davaları da dâhil olmak üzere tüm
uyuşmazlıkları konu alan davalar ile bu davalara karşı açılan davaları,

b) Taşınır ve taşınmaz mal veya hakkın paylaştırılmasına ve ortaklığın
giderilmesine ilişkin davaları,

c) Taşınır ve taşınmaz mallarda, sadece zilyetliğin korunmasına yönelik olan
davaları,

ç) Bu Kanun ile diğer kanunların, sulh hukuk mahkemesi veya sulh hukuk hâkimini
görevlendirdiği davaları, görürler.
====
+
.Kira sözleşmesinden doğan davalar
****
Kira sözleşmesinden doğan alacak davası, tahliye davası, kira bedelinin tespiti
devası, uyarlama davası; bunların tamamında görevli mahkeme sulh hukuk
mahkemesidir.
 
NOTE: Kiracı kirayı vermediğinde, kiraya veren kira bedelini tahsil etmek için
icra dairesine müracaat edecektir. Kiraya verenin başlattığı icra takibinde bir
itiraz olursa bu itirazın çözüm mercii sulh hukuk mahkemesidir.
 
Kira sözleşmesinden doğan alacak iddiasına ilişkin alacağın teminat altına
alınması için ihtiyati tedbir talebinde bulunulması sulh hukuk mahkemesine
yapılacaktır.
 
TIP: Bir taşınmazı kullanmakta olan kişiyle, o taşınmazın maliki arasında kira
sözleşmesi yoksa açılacak dava müdahelenin meni davasıdır ve asliye hukuk
mahkemesinde açılır.
 
İcra İflas Kanunu 269 ve devam eden hükümleri uyarınca kira parasının tahsili,
kiralanan yerin tahliyesi, tahliye taahhüdünün ifası şeklinde bir talep icra
dairesine sunulmuş ve bu talep sonucunda takip prosedürü başlatılmış ise
buradaki görevli mahkeme esasen icra mahkemesidir.
 
Kira sözleşmesinin geçersizliği durumunda görevli mahkeme asliye hukuk
mahkemesi olacaktır.
****
+
Çekişmesiz yargıya ilişkin işlerde görevli mahkeme HMK 382 ve HMK 383 uyarınca
sulh hukuk mahkemesidir.
+
Henüz bir dava açılmadan, istikbalde açılacak bir davada kullanılma ihtimalinin
olduğu düşünülen bir delilin muhafazasının sağlanmasına ilişkin geçici hukuki
koruma tedbirleri HMK 401 ve devamında düzenlenmiştir. Bu konuda da görevli
mahkeme sulh hukuk mahkemesidir.
+
Sulh hukuk mahkemesinde basit yargılama usulü uygulanır.
. _Özel mahkemeler_

.. *İş Mahkemesi*
+
Eğer iş mahkemesi, davanın taraflarının ya da davanın konusu olan hakkın İş
Kanunu'nun 8. maddesine tekabül ettiğini tespit ederse davayı görür. Aksi halde
davayı usulden reddetmelidir.
+
====
*İK 8/1*: İş sözleşmesi, bir tarafın (işçi) bağımlı olarak iş görmeyi, diğer
tarafın (işveren) da ücret ödemeyi üstlenmesinden oluşan sözleşmedir. İş
sözleşmesi, Kanunda aksi belirtilmedikçe, özel bir şekle tâbi değildir.
====
+
NOTE: Hukuk Genel Kurulu'nun 27.02.2013 tarihli kararına göre "_iş
sözleşmesinin sona ermesinin ardından rekabet yasağına aykırılık halinde
açılacak dava tarafların sıfatına bakılmaksızın mutlak ticari davadır_". Haksız
rekabete ilişkin düzenleme Ticaret Kanunu'nda olduğu için buna ilişkin
yargılamanın yapılacağı mahkeme de, bu hususa aykırılık sebebiyle tazminata
hükmedecek mahkeme de asliye ticaret mahkemesidir.
+
====
*İş Mahkemeleri Kanunu 5*: İş mahkemelerinde açılacak her dava, açıldığı
tarihte dava olunanın Türk Medeni Kanunu gereğince ikametgahı sayılan yer
mahkemesinde bakılabileceği gibi, işçinin işini yaptığı işyeri için yetkili
mahkemede de bakılabilir.  Bunlara aykırı sözleşme muteber sayılmaz.
====
+
Bu hükümde yetki kesin yetki kuralıdır. Dolayısıyla bu maddeye aykırı bir yerde
dava açılmışsa dava reddedilecektir.
+
[NOTE]
====
*Karşı dava*, davalının davacıya herhangi bir yer mahkemesinde açtığı davadır.
Karşı davanın özelliği, davalının cevap dilekçesi verme süresi içinde
davacısına aynı mahkeme yönünde karşı bir dava açması ve iki davanın birlikte
görülmesidir.

*İş davaları karşı dava olarak açılamaz*. İş davasına ilişkin özel bir
mahkeme tahsis edilmiş olup cevap dilekçesi babında ya da cevap dilekçesini
tahkim eden nitelikte bir karşı davanın ikamesi iş hukukundan kaynaklanan
davalar için kabul edilmiştir. 

*Ama karşı dava iş mahkemesinde açılabilir*. İşçi, işverene karşı ücretler
ödenmediğinden, sigorta primi yatırılmadığından vs. dolayı bir dava açmış
olabilir. Sadece bu halde, iş mahkemesi önünde İş Kanunu'Ndan kaynaklanan karşı
davalar açılabilir. Ama başka bir özel mahkemede iş mahkemesinin görev alanına
giren bir davanın karşı dava olarak açılması mümkün değildir.
====
+
İş Mahkemeleri Kanununun 7. maddesinde şifahi yargılama usulü yazıyor olsa
bile, şifahi yargılama usulü ilga edildiğinden, bunun yerine basit yargılama
usulünün uygulanması gerekir. 
+
====
*HMK 447*: (1) Diğer kanunların sözlü yahut seri yargılama usulüne atıf yaptığı
hâllerde, bu Kanunun basit yargılama usulü ile ilgili hükümleri uygulanır.
====
+
İş mahkemesinde karar yüze karşı verilmişse, istinafa başvuru süresi kararın
taraflara tefhimi; tarafların yokluğunda verilmiş ise, başvuru süresi kararın
taraflara tebliğinden itibaren 8 gündür.
+
====
*İş Mahkemeleri Kanunu 8/2*: İstinaf yoluna başvurma süresi, karar yüze karşı
verilmişse nihaî kararın taraflara tefhimi, yokluklarında verilmiş ise tebliği
tarihinden itibaren sekiz gündür.
====
+
İş mahkemesinde bin lira ve altında kararlar kesindir, istinafa taşınamaz.
Bölge adliye mahkemesi hukuk dairesi, bir iş mahkemesinden kendisine intikal
etmiş olan verdiği ihtilafta verdiği kararın değeri beşbin liranın altındaysa
bölge adliye mahkemesinin verdiği karar kesindir. Beşbin lirayı aşarsa bu
durumda Yargıtay'a gidilebilir.
+
Basit yargılama usulü olmasına rağmen, iş mahkemesinde mutlak suretle tahkikat
duruşması yapılması gerekir. Burada yapılması gereken mahkemenin duruşmayı
tertip edip taraflara tebliğ etmesidir. Tarafların gelip gelmemesi kendi
inisiyatifleridir.
+
İş mahkemesinde görülecek davalar ivedilik arz etmesinden dolayı, adli tatilde
görülecek işlerden biridir.
.. *Kadastro Mahkemesi*
+
*Kadastral faaliyet*, arazi ölçümü yapılıp arazi üzerindeki hak sahiplerinin
tapuya tescil edilmesidir. Bu faaliyetten doğan ihtilafların görüleceği mahkeme
kadastro mahkemesidir. Bu ihtilaf herkes tarafından ileri sürülebilir.
+
Kadastro mahkemesi re'sen araştırma ilkesiyle ihtilafı çözer. Devlet gibi,
devletin yaptığı işlemi üstlenerek, davacının lehine ya da aleyhine mutlaka
çözüme kavuşturmak zorundadır. Bunu yaparken de kendisine müracaat eden kişinin
sorumluluğuna bağlı değildir.
+
Kadastro mahkemesindenki davalar kanunda ivedi iş sayılmıştır, adli tatilde
görülmeye devam eder. 
+
Kadastro mahkemesinden verilmiş olan kararların icrası icra dairesinden
istenmez. Kadastro mahkemesi yaptığı tespitten sonra tapuda kendisi talepte
bulunur.
.. *Asliye Ticaret Mahkemesi*
+
Asliye ticaret mahkemesi nezdinde görülecek bir davanın konusunun değeri eğer
üçyüzbin liranın üzerindeyse mutlak suretle davanın heyet halinde görülmesi
gerekmektedir; bunun haricindeki davalar tek hakimle görülecektir.
+
CAUTION: İflas hukukundan doğan davaların tamamı heyet halinde görülmesi
gereken davalardır. Dolayısıyla üçyüzbin lira sınırı aranmaz.
+
TIP: Tahkim yargılaması sonucunda verilen karara karşı temyiz mümkün değilken,
iptal davası mümkündür ve iptal davası asliye ticaret mahkemesinin görev
alanına girer.
+
.Asliye Ticaret Mahkemesinin Görev Alanına Giren Davalar
****
. TTK 4 ve TTK 5'te düzenlenen mutlak ticari davalar ve nispi ticari davalar
. İcra İflas Kanunu'nun 154. maddesi iflas davalarının görüleceği mercii olarak
  asliye ticaret mahkemesini işaret etmiştir.
. Sigorta hukukundan kaynaklanan davalar
. İki tarafı ticari işletme olan nispi ticari davalar
****
.. *Aile Mahkemesi*
+
CAUTION: Vesayet aile mahkemesinin görev alanında değildir. Anayasa Mahkemesi
kararıyla vesayet aile mahkemesinin görevinden çıkarılmıştır. Vesayette görevli
mahkeme sulh hukuk mahkemesi, denetim makamı asliye ticare mahkemesidir.
+
WARNING: Aile mahkemesinde eşler arasındaki her dava görülmez; burada önemli
olan davanın tarafları değil, davanın konusunun aile hukukundan kaynaklanıyor
olmasıdır.
+
Aile mahkemesine atanacak hakimlerin; evli ve çocuk sahibi, otuz yaşını
doldurmuş kişiler olmaları gerekir (Aile Mahkemesinin Kuruluşuna Dair Kanun
madde 3).
+
Her aile mahkemesine birer psikolog, pedagog ve sosyal çalışmacı atanır ve
hakimler bu uzmanlardan görüş alarak karar verir ve bu uzmanlar kararın
icrasını takip eder. Burada uzmanların, kararın şekli anlamda geçerliliğine bir
etkisi yoktur. Yani hükümde uzmanların imzasının bulunmaması kararın geçersiz
olduğu anlamına gelmez. Sadece uzmanların görüşünün alınması ve bu görüşlere
uyulması zorunludur. Bu sebepten uzmanların görüşü alınmadan verilen karar
istinafa taşınıp iptal ettirilebilir.
+
Yargılama usulü yazılı yargılamadır.
.. *İcra Mahkemesi*
+
[caption=""]
.İcra Mahkemesinin İşlevleri
****
. Kendi yargı çevresinde bulunan icra dairelerindeki icra takiplerinin
  kendisine intikal etmiş _itiraz ve şikayetleri çözüme bağlar_.
. Kendisine bağlı olan icra dairelerinde 3 aylık dönemlerde _gözetim ve denetim
  yapar_.
+
TIP: Bir mahkemenin başka bir mercii denetim ve gözetim yetkisi sadece icra
mahkemesinde vardır.
. İcra mahkemelerinin cebri özelliği vardır. İcra İflas Kanunu'nda düzenlenen
  cezai hükümlere dayanarak suç gerçekleşmiş ise _ceza kararını tesis eder_.
  Bunlardan en önemlisi, borçlu üzerindeki hapisle tazyik yöntemi ile
  alacaklının alacağını en kısa sürede alması hedeflenir.
****
+
İcra mahkemesinde sıkı şekil şartları yoktur, örneğin duruşma yapma mecburiyeti
dahi yoktur. Özellikle şikayet talepleri dosya üzerinden incelenerek hüküm
verilir; çünkü icra mahkemesinin amacı icra takibi başlatan alacaklının
alacağını en kısa sürede ve en az masrafla elde etmesidir. Bundan dolayı
yapılan incelemeden sonra verilen karar kesin hüküm teşkil etmez ve ihtilaf
hukuk hayatından bertaraf edilmediğinden dolayı taraflar aynı ihtilafı genel
bir mahkemede yeniden dava konusu yapabilirler.
+
[NOTE]
====
Bunun iki istisnası vardır:

. Mahcuz mala istihkak davası
. İadenin feshi davası

Bu davalara ilişkin verilen kararlar kesin hüküm teşkil eder. Çünkü bu
davalarda İcra İflas Kanunu gereği genel mahkemedeki gibi usul şartları
uygulanır.
====
+
İcra mahkemesinin en kısa sürede ve en az masrafla yargılamayı sonuçlandırması
için basit yargılama usulü uygulanır. 
+
İcra mahkemesi bulunmayan bir yerde, asliye hukuk mahkemesi icra mahkemesinin
görevini üstlenir.
.. *Tüketici Mahkemesi*
+
Tüketici mahkemeleri 6502 sayılı Tüketicinin Korunması Hakkında Kanun ile
kurulmuş; görev ve yetkileri de bu kanunda düzenlenir. 
+
İhtilaf; eser, taşıma, simsarlık, sigorta, vekalet, bankacılık ve benzeri
sözleşmelerden veya tarafların tüketici saikiyle hareket etmesiyle doğmuşsa
görevli mahkeme kesin olarak tüketici mahkemesidir.
+
NOTE: Tacir eğer satım sözleşmesi ile ofisine bir bilgisayar alırsa ve sözleşme
ile ilgili bir ihtilaf doğarsa bu ihtilaf ticari işletmeyi ilgilendirdiği için
asliye ticaret mahkemesi görevlidir; ancak tacir evine bilgisayar almış olsaydı
bunu tacir sıfatıyla değil tüketici sıfatıyla yaptığından görevli mahkeme
tüketici mahkemesi olur.
+
Belirli değerin altında olan uyuşmazlıklarda tüketici hakem heyetlerine
başvurmak zorunludur. Bu parasal sınır her yıl takvim başında belirlenir. 2016
yılı için; 0-2320 TL arasına İlçe Hakem Heyeti, 2320-3480 Tl arasına İl
Tüketici Hakem Heyeti, 3480 TL'nin üstündeki uyuşmazlıklarda tüketici
mahkemesine başvurulur. 3480 liranın altında olan uyuşmazlıklarda tüketici
mahkemesine başvurulması halinde dava reddedilir.
+
Tüketici hakemi tahkim yargılamasına benzer bir inceleme yapar. Verilen
kararlar berli bir değerin altında ise kesin hükümdür; belirli bir değerin
üstünde ise karar kesin hüküm teşkil etmez ve 15 gün içinde tüketici
mahkemesine itiraz edilebilir.
+
Tüketici mahkemelerinde kesin yetki kuralı benimsenmemiştir, yetkili mahkeme
tüketicinin bulunduğu yer ya da tüketicinin işyerinin bulunduğu yer merciidir.
+
Tüketici mahkemeleri nezdinde, Bakanlık, tüketiciler ve tüketici örgütleri
tarafından açılan davalar Harçlar Kanunu'nda düzenlenen harçlardan muaftır.
Davanın davacı aleyhine sonuçlanması durumunda, hükmedilen vekalet ücreti
Bakanlıkça karşılanır. Davanın davalı aleyhine sonuçlanması durumunda,
bilirkişi ücreti davalıdan tahsil olunarak bütçeye gelir kaydedilir.
+
Tükeitici mahkemelerinde basit yargılama usulü uygulanır.
+
Tüketici hakem heyetinin verdiği kararlar tarafları bağlar ve ilam
niteliğindedir. Bu kararlar icra dairesi vasıtasıyla uygulattırılabilir.
+
TIP: Tüketici dernekleri, doğrudan alakası olmayan bir konuda genel olarak
tüketiciyi ilgilendiren ve kanuna aykırı bir durum doğma tehlikesi olan
hallerin önlenmesine ilişkin dava açabilirler. Bu davalarda, davacı verilen
kararın yayımlanmasını talep edebilir. Bu sayede karar tüm tüketicilere etki
eder.
.. *Fikri ve Sınai Haklar Mahkemesi*
+
Fikri ve sınai haklar mahkemesinin görevleri ilgili 5486 sayılı kanunda ve
Kanun Hükmünde Kararnameler ile düzenlenmiştir. Endüstriyel tasarımın
korunması, patent haklarının korunması, markaların korunması hakkında KHK'larda
düzenlenen tedbir niteliğindeki kararlar fikri ve sınai haklar mahkemesi
tarafından verilmektedir.

<<<

=== HAKİM

.Hakimlik Teminatı
****
* Hakimler, yaş haddi ve maluliyet hali dışında kendileri istemedikçe emekliye
  sevk olunamazlar.
* Hakimler, kadronun daraltılması veya kaldırılması sebeplerine dayansa bile
  maaş ve ödeneklerinden yoksun kılınamazlar.
* Hakimler istekleri dışında savcılık sınıfına nakledilemezler.
* HSYK Kanunu'na göre, hakimlere disiplin cezası verilmesi veya görevden
  uzaklaştırılmaları hakkında HSYK karar verir.
****

* *Hakimin yasaklılığını gerektiren durumlar*, HMK 34'te sınırlı olarak
  sayılmıştır. Bu hallerin varlığı halinde hakim, taraflar talep etmeseler bile
  kendiliğinden çekilmek zorundadır.
+
====
*HMK 34*: (1) Hâkim, aşağıdaki hâllerde davaya bakamaz; talep olmasa bile
çekinmek zorundadır:

a) Kendisine ait olan veya doğrudan doğruya ya da dolayısıyla ilgili olduğu
davada.

b) Aralarında evlilik bağı kalksa bile eşinin davasında.

c) Kendisi veya eşinin altsoy veya üstsoyunun davasında.

ç) Kendisi ile arasında evlatlık bağı bulunanın davasında.

d) Üçüncü derece de dâhil olmak üzere kan veya kendisini oluşturan evlilik bağı
kalksa dahi kayın hısımlığı bulunanların davasında.

e) Nişanlısının davasında.

f) İki taraftan birinin vekili, vasisi, kayyımı veya yasal danışmanı sıfatıyla
hareket ettiği davada.
====
+
TIP: Hakim ile tarafların avukatı arasında yakınlık bulunması bir yasak hali
olarak kabul edilmemiştir. Ancak böyle bir yasak avukat açısından, Avukatlık
Kanunu'nda düzenlenmiştir. Avukatlık Kanunu madde 13'e göre, hakimin eşi ikinci
dereceye kadar hısımlarından olan avukat, o hakimin baktığı dava ve işlerde
avukatlık yapamaz. Dolayısıyla böyle bir durumda çekinmesi gereken, hakim değil
avukattır.
+
Hakimin yasaklılığı kamu düzenine ilişkindir ve taraflar bu konuda anlaşamaz,
bununla ilgili bir düzenleme yapamazlar.
+
====
*HMK 35*: (1) Çekinme kararına karşı üst mahkemeye başvurulabilir. Yasaklama
sebebinin doğduğu tarihten itibaren, o hâkimin huzuru ile yapılan bütün
işlemler, üst mahkemenin kararı ile iptal olunabilir. Hüküm ve kararlar ise
herhâlde iptal olunur. Bu durumda, hâkim yargılama giderlerine mahkûm
edilebilir.

(2) Çekinme kararının ilk derece mahkemesi hâkimince verildiği hâllerde,
başvuru üzerine bölge adliye mahkemesinin vereceği karar kesindir.
====
+
Yasaklılık hali kamu düzeninden olduğu için, yargılama sürerken ileri
sürülmemiş olsa ve yargılama bittikten sonra fark edilmiş olsa dahi
yargılamanın iadesi yapılır.

* *Hakimin reddi* sebepleri kanunda sınırlı olarak sayılmamıştır. Aksine
  hakimin tarafsızlığından şüpheyi gerektirecek bir sebep bulunması halinde
  hakimin reddi talep edilebilir.
+
====
*HMK 36*: (1) Hâkimin tarafsızlığından şüpheyi gerektiren önemli bir sebebin
bulunması hâlinde, taraflardan biri hâkimi reddedebileceği gibi hâkim de bizzat
çekilebilir. Özellikle aşağıdaki hâllerde, hâkimin reddi sebebinin varlığı
kabul edilir:

a) Davada, iki taraftan birine öğüt vermiş ya da yol göstermiş olması.

b) Davada, iki taraftan birine veya üçüncü kişiye kanunen gerekmediği hâlde
görüşünü açıklamış olması.

c) Davada, tanık veya bilirkişi olarak dinlenmiş veya hâkim ya da hakem
sıfatıyla hareket etmiş olması.

ç) Davanın, dördüncü derece de dâhil yansoy hısımlarına ait olması.

d) Dava esnasında, iki taraftan birisi ile davası veya aralarında bir düşmanlık
bulunması.
====
+
Hakimin reddinde taraflar hakimin reddini talep edebilir veya hakim bizzat
kendisi de davadan çekilebilir. Ancak taraflar ileri sürmediyse ve hakim
kendiliğinden çekilmediyse karar bozulma teşkil etmez.
+
Hakimin kendini reddetmesi bir süreye bağlı değilken, tarafların hakimi
reddetmesi süreye tabidir.
+
====
*HMK 38*: (1) Hâkimin reddi sebebini bilen tarafın, ret talebini en geç ilk
duruşmada ileri sürmesi gerekir. Taraf, ret sebebini davaya bakıldığı sırada
öğrenmiş ise en geç öğrenmeden sonraki ilk duruşmada, yeni bir işlem yapılmadan
önce bu talebini hemen bildirmek zorundadır. Belirtilen sürede yapılmayan ret
talebi dinlenmez.

(2) Hâkimin reddi, dilekçeyle talep edilir. Bu dilekçede, ret talebinin
dayandığı sebepler ile delil veya emarelerin açıkça gösterilmesi ve varsa
belgelerin eklenmesi gerekir.

(3) Hâkimin reddi dilekçesi, reddi istenen hâkimin mensup olduğu mahkemeye
verilir.

(4) Ret talebi geri alınamaz.

(5) Hâkimi reddeden taraf, dilekçesini karşı tarafa tebliğ ettirir. Karşı taraf
bir hafta içinde cevap verebilir. Bu süre geçtikten sonra yazı işleri müdürü
tarafından ret dilekçesi, varsa karşı tarafın cevabı ve ekleri, dosya ile
birlikte reddi istenen hâkime verilir.  Hâkim bir hafta içinde dosyayı inceler
ve ret sebeplerinin kanuna uygun olup olmadığı hakkındaki düşüncesini yazı ile
bildirerek, dosyayı hemen merciine gönderilmek üzere yazı işleri müdürüne
verir.

(6) Ret sebebi sabit olmasa bile, merci bunu muhtemel görürse, ret talebini
kabul edebilir.

(7) Ret sebepleri hakkında yemin teklif olunamaz.

(8) Hâkimi çekilmeye davet, hâkimin reddi hükmündedir.

(9) Bu kararlar aleyhine ancak hükümle birlikte kanun yollarına başvurulabilir.
====
+
NOTE: Hakimin reddi talebi geri alınamaz.
+
Vekilin hakimin reddi talebinde bulunabilmesi için özel yetkisi bulunması
gerekir.
+
****
Hakimin reddi talebi üzerinde, tek hakimli mahkemelerde hakim kendi başına;
heyet halinde çalışan mahkemelerde heyet ile birlikte hakim bir ön inceleme
yapar. Bu ön inceleme aşamasında hakim ret istemini 3 sebepten geri
çevirebilir:

. Ret isteği zamanında yapılmamışsa
. Ret sebebi veya inandırıcı delil gösterilmemişse
. Ret isteminin davayı uzatmak amacıyla yapıldığı açıkça anlaşılıyorsa

Bu hallerde, ret talebi, toplu mahkemelerde reddedilen hakimin müzakereye
katılmasıyla; tek hakimli mahkemelerde ise hakimin kendisi tarafından geri
çevrilir. Bu ret talebinin geri çevrilmesine dair karara karşı direkt kanun
yoluna gidilemez. *Ancak kesin hükümle beraber kanun yoluna müracaat
mümkündür*.
****
+
Hakimin reddi talebi ön incelemeden geçtikten sonra; reddi istenen hakim
katılmaksızın mensup olduğu mahkemece incelenir. Eğer reddedilen hakim
olmaksızın o mahkeme toplanamıyor ya da mahkeme tek hakimden oluşuyor ise ret
talebini o yerdeki asliye hukuk mahkemesi ya da onun hakimi inceler.
+
Ret talebini inceleyen mercii davayı dosya üzerinden inceleyebilir; duruşma
yapmasına gerek yoktur.
+
CAUTION: Ret talebini inceleyen mercii tarafsızlığa kesin kanaat getirmesine
gerek yoktur; hakimin tarafsızlığına şüphe duyması yeterlidir.
+
Ret talebinde ret sebeplerinden dolayı hakimin yemin etmesi istenemez. Ç
nkü yemin bir hukuki ihtilafın taraflarını ilgilendirir ve karşı tarafa teklif
edilir; ancak hakim burada bir taraf değildir.
+
Taraflar, daha önce hakkındaki ret talebi mercii tarafından reddedilen hakimin,
aynı talep ve sebeple reddini isterse yargılamayı uzatma amacı taşıdığı
sebebiyle talep direkt ön incelemede reddedilir. Bu ikinci talep hakimin davaya
bakmasına engel oluşturmaz ve eğer kişinin kötü niyetle yaptığı anlaşılırsa ve
esas yönünden talebi kabul edilmediyse, kişi disiplin cezasına çarptırılır.
Disiplin para cezası hiçbir seçenek yaptırıma çevrilemez. 
+
Reddi talep edilen hakim, merci tarafından karar verilinceye kadar hiçbir işlem
yapamaz, davaya bakamaz. Ancak eğer gecikmesinde sakınca bulunan işler varsa
bunları yapabilir.
+
*İstinaf yolu, değeri 1500 TL ve üzeri davalar için açıktır*. Yani, bu değerin
üzerindeki davalarda hakimin reddi istendiğinde, ret talebini inceleyen merciin
kararına karşı istinafa gidilebilir ve istinafın kararı kesindir. Ancak dava
1500 liranın altındaysa bu dava için istinaf yolu kapalıdır ve bu sebeple
hakimin reddi talebini inceleyen merciin kararına karşı istinaf yoluna
gidilemez, merciin kararı kesindir. İstinaf mahkemesi hakimine karşı, esas
hüküm bakımından temyiz yolu açıksa Yargıtay'a gidilebilir.

* Hakimlerin üç tip sorumluluğu vardır:

. *Disiplin sorumluluğu*
. *Cezai sorumluluk*
. *Hukuki sorumluluk*

* Hakimlerin hukuki sorumluluğunda birinci derecede sorumluluğu devlet
  üstlenmiştir. Dolayısıyla hakimin sorumluluğundan dolayı mağdur olan kişi
  davayı devlete karşı açacaktır. Burada zarar gören kişinin zararının eksiksiz
  olarak karşılanması amaçlanmaktadır. Ancak devletin tazminata mahkum olması
  halinde hakim bizzat sorumlu olur ve devlet ödediği tazminat nedeniyle hakime
  bir yıl içerisinde rücu eder.
+
Devlete karşı açılan davada hakime davanın açıldığı ihtar edilir. İhtar olunan
hakim söz konusu davaya _fer'i müdahil_ olarak intikal eder ve devletin yanında
yer alır. Hakimin, fer'i müdahil olarak davaya katılması devletin hüküm
verilebilmesi için onun beyanlarını tahkim eder nitelikte beyan ve bilgi
sunmakla müteşekkil olmasıdır. Verilen karar fer'i müdahile doğrudan tesir
etmez, çünkü davanın tarafı değildir.
+
HMK 46'daki sınırlı olarak sayılmış sebepler haricinde hakimin hukuki
sorumluluğundan dolayı tazminat davası açılamaz.
+
====
*HMK 46*: (1) Hâkimlerin yargılama faaliyetinden dolayı aşağıdaki sebeplere
dayanılarak Devlet aleyhine tazminat davası açılabilir:

a) Kayırma veya taraf tutma yahut taraflardan birine olan kin veya düşmanlık
sebebiyle hukuka aykırı bir hüküm veya karar verilmiş olması.

b) Sağlanan veya vaat edilen bir menfaat sebebiyle kanuna aykırı bir hüküm veya
karar verilmiş olması.

c) Farklı bir anlam yüklenemeyecek kadar açık ve kesin bir kanun hükmüne aykırı
karar veya hüküm verilmiş olması.

ç) Duruşma tutanağında mevcut olmayan bir sebebe dayanılarak hüküm verilmiş
olması.

d) Duruşma tutanakları ile hüküm veya kararların değiştirilmiş yahut tahrif
edilmiş veya söylenmeyen bir sözün hüküm ya da karara etkili olacak şekilde
söylenmiş gibi gösterilmiş ve buna dayanılarak hüküm verilmiş olması.

e) Hakkın yerine getirilmesinden kaçınılmış olması.
====
+
HMK 46'daki sebepler bağlamında hakimin hukuki sorumluluğunun doğabilmesi için
tespit edilmesi gereken üç ana unsur vardır: *kast*, *kanuna açıkça aykırı
karar, işlem ya da eylem ve *görevi savsaklama*. Bu üç unsurdan birinin
bulunması yeterlidir.
+
Hakimin sorumluluğu sebeplerinden birisi gerçekleştiğinde, bu karardan
etkilenen herkes tazminat davası açabilir. Yani, hakimin hukuki sorumluluğuna
ilişkin tazminat davası açmak için davada taraf olmak zorunlu değildir. Ancak
her halde, ispat yükü tazminat talebinde bulunan kişidedir.
+
HMK 46'da sayılan sebepler temyiz veya istinaf sebebi yapılmamış olmasına
rağmen hakimin hukuki sorumluluğunda kullanılıp tazminat talep edilebilir.
+
Devletin sorumlu hakime karşı açacağı rücu davası, tazminat davasını karara
bağlamış olan mahkemede görülür.
+
Sorumluluk davası, davacı lehine sonuçlanırsa, Devlet davacının maddi ve manevi
tüm zararlarını ve yargılama giderlerini karşılar. Ancak davacı davayı
kaybederse, beşyüz Türk lirasından beşbin Türk lirasına kadar disiplin para
cezasına mahkum edilir. Davanın usulden reddi halinde disiplin para cezasına
hükmedilmez.

<<<

=== GÖREV

* 6100 sayılı Hukuk Muhakemeleri Kanunu 1 Ekim 2011 tarihinde yürürlüğe girdiği
  için, bu tarihten önce açılmış olan davalarda göreve ilişkin hem 1086 sayılı
  HUMK ve 6100 sayılı HMK gözönüne alınmalıdır.
+
1086 sayılı HUMK'a göre göreve ilişkin tespit davanın değeri esas alınarak
yapılmaktaydı. Bu sebeple dava dilekçesinde davanın değeri miktarı belirtilmek
zorundaydı. Ancak 6100 sayılı HMK'da böyle bir ölçüt olmadığı için; faiz, icra
tazminatı ve giderler gibi değerlerin dava dilekçesinde belirtilmesinin göreve
ilişkin herhangi bir belirleyici yanı yoktur. 
+
====
*HMK Geçici Madde 1*: (1) Bu Kanunun yargı yolu ve göreve ilişkin hükümleri,
Kanunun yürürlüğe girmesinden önceki tarihte açılmış olan davalarda uygulanmaz.

(2) Bu Kanunun, senetle ispat, istinaf ve temyiz ile temyizde duruşma
yapılmasına ilişkin parasal sınırlarla ilgili hükümleri Kanunun yürürlüğe
girmesinden önceki tarihte açılmış olan dava ve işlerde uygulanmaz.
====
+
[TIP]
====
Kanun yoluna müracaat şartının gerçekleşmiş olduğunu belirlemek ve ispat
sınırını doğru tayin edebilmek için açısından müddeabihin isabetli bir şekilde
belirlenmesi gerekir.

Uygulamada, müddeabihin değerinin belirlenmesinde, faiz, icra tazminatı ve
diğer giderlerin dava dilekçesinde belirtilmesi zorunludur. Ancak bu anlamda
bir kanuni düzenleme yoktur. Kanun yoluna müracaatta ve ispat sınırını
belirlemede bunlar anapara üzerine eklenerek hesaplanmaz; anapara alacağı esas
alınır ve dava konusu üzerine gerçekleşecek usuli işlemler tespit edilir.
====
+
====
*HUMK 2*: (1) Müddeabih para ise mahkemenin vazifesini tayinde miktarı esas
ittihaz olunur.

(2) Müddeabih başka bir şey olup da iki taraf kıymetinde uzlaşmazlarsa kıymeti
davanın ikame edildiği mahkeme tarafından takdir ve tayin olunur.
====
+
Sunulan dilekçenin geçerliliğini tespitte Harçlar Kanunu 16/3'e bakılmalıdır;
dolayısıyla müddeabih değeri görev açısından olmasa da dava dilekçesinin
geçerliliği açısından önem teşkil eder ve dilekçede gösterilmesi gerekir.
Gösterilmemesi halinde ise kesin süre verilir ve bu süre içerisinde
gösterilmesi istenir.
+
====
*Harçlar Kanunu 16/3*: Değer tayini mümkün olan hallerde dava dilekçelerinde
değer gösterilmesi mecburidir. Gösterilmemişse davacıya tesbit
ettirilir. Tesbitten kaçınma halinde, dava dilekçesi muameleye konmaz.
====
+
Dava dilekçesinde gösterilmiş olan değerin, değerinden az veya çok gösterilmiş
olması halinde, hakim tarafından, eksik harcın ikmali ya da fazla yatırılmış
harcı iadesi yönünde karar tesis edilebilir.
+
====
*Harçlar Kanunu 30*: Muhakeme sırasında tesbit olunan değerin, dava
dilekçesinde bildirilen değerden fazla olduğu anlaşılırsa, yalnız o celse için
muhakemeye devam olunur, takip eden celseye kadar noksan değer üzerinden peşin
karar ve ilam harcı tamamlanmadıkça davaya devam olunmaz. Hukuk Usulü
Muhakemeleri Kanununun 409 uncu maddesinde gösterilen süre içinde dosyanın
muameleye konulması, noksan olan harcın ödenmesine bağlıdır.
====
+
Eğer müddeabihin değeri, dava dilekçesinde olması gerekenden az gösterilmişse
ve bu dava dilekçesi ilk duruşma aşamalarından sonra tespit edilmiş ise, tespit
edildiği anda eksik harcın yatırılması talep edilir. Buna riayet edilmez ise
dava açılmamış sayılır ve dosya işlemden kaldırılır.


[NOTE]
====
Hakimin hukuki sorumluluğunda görevli mahkeme, hakimin mensup olduğu mahkemede
esas karar temyize taşındığında hangi hukuk dairesinde görülecekse orasıdır.
Peki eğer hakim, usuli bir yanlış yapıp görevli olmadığı halde kendini görevli
addederek davayı yürütürse sorumluluk davasında da görevsiz mahkemenin temyiz
yeri mi görevli olur?

_Kürsüye göre_, HMK 47'deki hukuk dairesi görevlidir şeklindeki tespit görevli
mahkemeyi tespitte yeterli ve geçerlidir. Eğer hakkında sorumluluk davası
açılan hakim usuli bir hata yaptıysa bu ilgili hukuk dairesinde tespit
edilebilir ve hukuk dairesi ilk derece mahkemesini ve kendisini görevsiz
kılabilir. Sonuç olarak ilgili uyuşmazlık başka bir hukuk dairesinde görülür.
====

* Bir davanın içinde birden fazla dava konusu var ise *objektif dava yığılması*
  söz konusudur. Objektif dava yığılması değer açısından önemli olsa da görev
  açısından önem teşkil etmez. Buna ilişkin hangi mahkemenin görevli olacağı
  Yargıtay kararları esas alınarak yapılır.
+
NOTE: Trafik kazasına ilişkin bir davada; haksız fiil sorumluluğu, istihdam
edenin sorumluluğu ve sigorta sorumluluğu vardır. Dolayısıyla bir dava, birçok
talep vardır. Bu davanın görüleceği yer Yargıtay tarafından, usul ekonomisi
uyarınca asliye ticaret olarak belirlenmiştir.

* *Terditli davalarda*, davacının asli ve yan olmak üzere iki talebi vardır ve bu
  iki talebini de sunduktan sonra yargılama yürütülmeye başlar. 1086 sayılı
  kanun döneminde Yargıtay, hangi talebin değeri yüksek ise ona göre görevli
  mahkeme belirlenir diyordu.

* Görevsizlik iddiası, yargılamanın her aşamasında ileri sürülebilir. Ancak
  göreve ilişkin bir aykırılık iddiası olmadan hüküm verilmiş ise ve bu karar
  istinafa taşındığında göreve aykırılık tespit etmemişse, ilk yargılama yapan
  mahkemenin kararı bozulmaz. Yargılamanın iadesi, görevsiz mahkemenin verdiği
  ve kesin hüküm teşkil eden kararlar aleyhine uygulanmaz.

* Görevsizlik ve yetkisizlik kararına karşı yapılacak işlemler HMK 20, 21, 22
  ve 23'te düzenlenmiştir.
+
====
*HMK 20*: (1) Görevsizlik veya yetkisizlik kararı verilmesi hâlinde,
taraflardan birinin, bu karar verildiği anda kesin ise bu tarihten, süresi
içinde kanun yoluna başvurulmayarak kesinleşmiş ise kararın kesinleştiği
tarihten; kanun yoluna başvurulmuşsa bu başvurunun reddi kararının tebliğ
tarihinden itibaren iki hafta içinde kararı veren mahkemeye başvurarak, dava
dosyasının görevli ya da yetkili mahkemeye gönderilmesini talep etmesi gerekir.
Aksi takdirde, bu mahkemece davanın açılmamış sayılmasına karar verilir.

(2) Dosya kendisine gönderilen mahkeme, kendiliğinden taraflara davetiye
gönderir.
====
+
****
Görevsizliğe ilişkin nihai kararlara karşı iki ihtimal vardır.

. Müracaat süresi içinde kanun yoluna gidilebilir. İstinafın kararı bağlayıcı
  özelliktedir.
. Kanun yoluna müracaat süresi içinde, kanun yoluna gidilmemiş ise dava dosyası
  davanın tarafınca görevsizlik kararında belirtilen görevli mahkemeye
  gönderilir.

Eğer, bu iki ihtimal de gerçekleştirilmez ise dava açılmamış sayılır. Böyle bir
durumda, görevsizlik kararı verilen mahkemede ileri sürülen haklar yeniden dava
konusu yapılabilir. Burada görevsizlik kararı esasa ilişkin değil, *nihai
karardır*. Nihai kararlar usule ilişkindir ve kesin hüküm teşkil etmezler.
Dolayısıyla nihai karardaki usuli eksiklik giderildikten sonra yeniden dava
konusu edilebilirler. Önemli olan hak düşürücü süre ve zamanaşımına riayet
edilmesidir.
****
+
Görevsizlik kararının ardından dava görevli mahkemede görülmeye yeniden
başlanır. Görevli mahkeme taraflara davetiye gönderecektir. Görevsiz
addedilen mahkemedeki bütün usuli işlemler iptal edilmeyebilir; görevli mahkeme
hakimi önceki davanın usuli işlemlerinin birkaçını ya da tamamını geçerli
sayabilir.
+
====
*HMK 21*: (1) Aşağıdaki hâllerde, davaya bakacak mahkemenin tayini için yargı
yeri belirlenmesi yoluna başvurulur:

a) Davaya bakmakla görevli ve yetkili mahkemenin davaya bakmasına herhangi bir
engel çıkarsa.

b) İki mahkeme arasında yargı çevrelerinin sınırlarının belirlenmesi konusunda
bir tereddüt ortaya çıkarsa.

c) İki mahkeme de görevsizlik kararı verir ve bu kararlar kanun yoluna
başvurulmaksızın kesinleşirse.

ç) Kesin yetki hâllerinde, iki mahkeme de yetkisizlik kararı verir ve bu
kararlar kanun yoluna başvurulmaksızın kesinleşirse.
====
+
Görevsizlik kararı veren mahkeme, görevli mahkemeyi tespit etmek zorundadır.
Ancak görevli mahkeme olduğu tespit edilen mahkeme bu kararla bağlı değildir ve
kendisine intikal ettirilmiş olan davada yeniden görevsizlik kararı verebilir.
Bu halde HMK 21 uygulanır ve yargı yolunun tayini için Yargıtay hukuk dairesine
başvurulur.
+
====
*HMK 22*: (1) Yetkili mahkemenin bir davaya bakmasına herhangi bir engel
bulunduğu yahut iki mahkeme arasında yargı çevrelerinin sınırlarının
belirlenmesinde tereddüt ortaya çıktığı takdirde, yetkili mahkemenin tayininde,
ilk derece mahkemeleri için bölge adliye mahkemelerine, bölge adliye
mahkemeleri için Yargıtaya başvurulur.

(2) İki mahkemenin aynı dava hakkında göreve veya yetkiye ilişkin olarak
verdikleri kararlar kanun yoluna başvurulmaksızın kesinleştiği takdirde,
görevli veya yetkili mahkeme, ilgisine göre bölge adliye mahkemesince veya
Yargıtayca belirlenir.
====
+
====
*HMK 23*: (1) Yargı yerinin belirlenmesine ilişkin inceleme dosya üzerinden
yapılabilir.

(2) Bölge adliye mahkemesince veya Yargıtayca verilen yargı yeri belirlenmesi
ile kanun yolu incelemesi sonucunda kesinleşen göreve veya yetkiye ilişkin
kararlar, davaya ondan sonra bakacak mahkemeyi bağlar.
====
+
====
*HMK 331/2*: Görevsizlik, yetkisizlik veya gönderme kararından sonra davaya bir
başka mahkemede devam edilmesi hâlinde, yargılama giderlerine o mahkeme
hükmeder. Görevsizlik, yetkisizlik veya gönderme kararından sonra davaya bir
başka mahkemede devam edilmemiş ise talep üzerine davanın açıldığı mahkeme
dosya üzerinden bu durumu tespit ile davacıyı yargılama giderlerini ödemeye
mahkûm eder.  
====

<<<

=== YETKİ

* Mahkemeyi sınırlandıran iki husus vardır: Görev ve yargı çevresi, yani yetki.
  Türkiye Cumhuriyeti Devleti yargı çevrelerine bölünmüştür ve bu yargı
  çevrelerinin her birinin içindeki mahkemeler kendi yargı çevre sınırları
  içindeki yargılama faaliyetini yürütmeye yetkilidir.

* Yetkili mahkemeyi tespit ederken, *kesin yetkili mahkemeler* ve *kesin
  olmayan yetkili mahkemeler* olarak ayrıma gidilir.
+
Bir mahkemenin kesin yetkili olduğu durumlarda bu durum kamu düzeninden
kaynaklanır. Yani görevde olduğu gibi emredicidir, re'sen değerlendirilir ve
tarafların iradesine bırakılmaz.
+
Mahkemenin kesin yetkili olmadığı hallerde ise davacı, davasını istediği bir
yer mahkemesinde açar; açılmış olan bu davaya karşı, davalı cevap dilekçesinde
ilk itiraz olarak yetki itirazını ileri sürmezse söz konusu mahkeme yetkiyi
kazanır. Çünkü bu hallerde taraflar arasında zımni bir yetki sözleşmesi
yapılmış olur.

* Çekişmesiz yargı işlerinde yetki HMK 384'te düzenlenmiştir.
+
====
*HMK 384*: Kanunda aksine hüküm bulunmadıkça, çekişmesiz yargı işleri için
talepte bulunan kişinin veya ilgililerden birinin oturduğu yer mahkemesi
yetkilidir.
====

====
*HMK 6*: (1) Genel yetkili mahkeme, davalı gerçek veya tüzel kişinin davanın
açıldığı tarihteki yerleşim yeri mahkemesidir.

(2) Yerleşim yeri, 22/11/2001 tarihli ve 4721 sayılı Türk Medenî Kanunu
hükümlerine göre belirlenir.
====

* Tüzel kişilerin yerleşim yeri; 

** vakıflar için vakıf senedinde,
** dernekler için tüzükte,
** anonim şirketler esas sözleşmesinde düzenlenir.

* Gerçek kişilerin yerleşim yeri için MERNİS (Merkezi Nüfus İdaresi Sistemi)
  kaydına bakılır. Davalının MERNİS kaydı bulunmadığı durumlarda, davacının
  davalı kişiye ilişkin yaptığı yerleşim yeri tespitine dayanarak yetkili
  mahkemeyi belirlemesi mümkündür.
+
Davacının davalının adresini farklı bir yer olarak tespit etmesi durumunda,
tebligatın davalıya tespiti için; davacı veya davalı vekili mahkemeden
davalının yerleşim yerini talep eder ve davalının yerleşim yeri tespitini
mahkeme yapar. 
+
Mahkemenin tebliğ yükümlülüğü vardır ve davalının MERNİS kaydındaki adresine
tebligat yollanır. MERNİS kaydında davalının adresi bulunmuyorsa, ilanen tebliğ
yapılır.
+
Davanın derdest olması için, davacının davalının yerleşim yerini doğru tespit
etme yükümlülüğü yoktur. Hak düşürücü süreler nedeniyle davacının hak kaybı
yaşamaması için dava bir an önce açılıp mahkeme yetkilendirilmelidir.
+
Davalının dava açıldıktan sonra yerleşim yerini değiştirmesi sadece tebligata
tesir eder; mahkemenin yetkisine bir etkisi olmaz.

* Bir dava tek bir davalıya karşı değil, birden çok kişiye açılmış olabilir.
  Davalıların her birinin farklı yerleşim yerlerinin olması durumunda yetki HMK
  7'de düzenlenmiştir.
+
====
*HMK 7*: (1) Davalı birden fazla ise dava, bunlardan birinin yerleşim yeri
mahkemesinde açılabilir. Ancak, dava sebebine göre kanunda, davalıların tamamı
hakkında ortak yetkiyi taşıyan bir mahkeme belirtilmişse, davaya o yer
mahkemesinde bakılır.

(2) Birden fazla davalının bulunduğu hâllerde, davanın, davalılardan birini
sırf kendi yerleşim yeri mahkemesinden başka bir mahkemeye getirmek amacıyla
açıldığı, deliller veya belirtilerle anlaşılırsa, mahkeme, ilgili davalının
itirazı üzerine, onun hakkındaki davayı ayırarak yetkisizlik kararı verir.
====

* Davalı, esas yerleşim yeri dışındaki bir yeri geçici olarak yerleşim yeri
  kabul etmişse, davanın muhtemel süresine göre yetkili mahkeme değişiklik
  gösterebilir. Davalı, geçici olarak bulunduğu yer mahkemesinde davanın daha
  uzun süreceğini işaret ederek yetki itirazında bulunabileceği gibi, bunun
  aksi de mümkündür.
+
====
*HMK 8*: Memur, işçi, öğrenci, asker gibi, bir yerde geçici olarak oturanlara
karşı açılacak alacak veya taşınır mal davaları için, orada bulunmaları uzunca
bir süre devam edebilecekse, bulundukları yer mahkemesi de yetkilidir.
====

* HMK 10 uyarınca sözleşmenin ifa yeri mahkemesi de yetkilidir.
+
====
*HMK 10*: Sözleşmeden doğan davalar, sözleşmenin ifa edileceği yer mahkemesinde
de açılabilir.
====
+
Sözleşmenin ifa edileceği yer ya taraflar tarafından belirlenir ya da taraflar
belirlememişse TBK 89'a göre belirlenir.
+
====
*TBK 89*: (1) Borcun ifa yeri, tarafların açık veya örtülü iradelerine göre
belirlenir. Aksine bir anlaşma yoksa, aşağıdaki hükümler uygulanır;

1. Para borçları, alacaklının ödeme zamanındaki yerleşim yerinde,

2. Parça borçları, sözleşmenin kurulduğu sırada borç konusunun bulunduğu yerde,

3. Bunların dışındaki bütün borçlar, doğumları sırasında borçlunun yerleşim
   yerinde, ifa edilir.

Alacaklının yerleşim yerinde ifası gereken bir borcun doğumundan sonra
alacaklının yerleşim yerini değiştirmesi sebebiyle ifa önemli ölçüde
güçleşmişse borç, alacaklının önceki yerleşim yerinde ifa edilebilir.
====
+
HMK 10'da yer alan düzenleme tali bir düzenlemedir ve HMK 6'ya ek bir
alternatif sunar. Burada tercih davacıya aittir, isterse davalının yerinde (HMK
6), isterse sözleşmenin ifa yerinde (HMK 10), isterse de yetkisiz mahkemede
davayı açabilir.
+
Yetki sözleşmeleri sadece tacirler ve tüzel kişiler arasında yapılabilirken
borçlar hukuku sözleşmelerinde irade serbestisi ilkesi geçerlidir. Dolayısıyla
taraflar sözleşmede ifa yerini serbestçe belirleyebilirler ve yapacakları bu
maddi hukuktaki düzenleme ile doğrudan usul hukukuna tesir edebilirler. Yani
sözleşmede ifa yerini belirleyerek doğrudan yetki sözleşmesi yapmış sayılırlar.
*HMK 10, HMK 17'yi aşmak için önemli bir hükümdür*.
+
[NOTE]
====
Sözleşme feshedilmişse, sözleşmenin ifa yerinden hareketle yetkili mahkeme
belirlenebilir mi?

Maddi hukuk perspektifi ile açıklanmak gerekir. Fesih iradesinin sözleşmenin
diğer tarafına tebliği anından sonuçları doğar. Sözleşmenin feshedilmiş olması
sebebiyle uğranılan zararların giderilmesi talebiyle dava açıldığında, dava
dilekçesinde fesih kabul edildiğinden yetkili mahkeme sözleşmenin ifa yeri
üzerinden belirlenemez. Ancak sözleşmenin feshinin haksızlığına yönelik bir
dava açıldığında, sözleşmenin geçerliliği iddia edildiğinden sözleşmenin ifa
yeri mahkemesinde dava açılabilir.
====

* Haksız fiilden doğan davalarda yetkiye dair HMK 16'da yer alan düzenleme
  seçimlik yetki kuralıdır. 
+
====
*HMK 16*: Haksız fiilden doğan davalarda, haksız fiilin işlendiği veya zararın
meydana geldiği yahut gelme ihtimalinin bulunduğu yer ya da zarar görenin
yerleşim yeri mahkemesi de yetkilidir.
====
+
[caption=""]
.HMK 16'da düzenlenmiş yetki alternatifleri
****
. Haksız fiilin işlendiği yer mahkemesi
. Zararın meydana geldiği yer mahkemesi
. Zararın meydana gelme ihtimalinin bulunduğu yer mahkemesi
. Zarar görenin yerleşim yer mahkemesi
****
+
Haksız fiilden dolayı birden çok kişinin sorumlu olması durumunda davalı
tarafta birden fazla kişi söz konusu olacaktır. Bu durumda HMK 16'da düzenlenen
yetki kuralı kesin yetki kuralı olmadığı için HMK 16'ya ek olarak HMK 7'de
belirtilen yetkili mahkemede de dava açılabilir.

* *İhtiyati haciz* ve *ihtiyai tedbir* kavramları farklı kavramlardır. İhtiyati
haciz sadece para borcuna ilişkin olarak talep edilebilecek hukuki korumadır ve
şartları İİK 257'de belirtilmiştir. 
+
====
*İİK 257*: (1) Rehinle temin edilmemiş ve vadesi gelmiş bir para borcunun
alacaklısı, borçlunun yedinde veya üçüncü şahısta olan taşınır ve taşınmaz
mallarını ve alacaklariyle diğer haklarını ihtiyaten haczettirebilir. 

(2) Vadesi gelmemiş borçtan dolayı yalnız aşağıdaki hallerde ihtiyati haciz
istenebilir:

1 – Borçlunun muayyen yerleşim yeri yoksa;

2 – Borçlu taahhütlerinden kurtulmak maksadiyle mallarını gizlemeğe, kaçırmağa
  veya kendisi kaçmağa hazırlanır yahut kaçar ya da bu maksatla alacaklının
  haklarını ihlâl eden hileli işlemlerde bulunursa; 

(3) Bu suretle ihtiyati haciz konulursa borç yalnız borçlu hakkında muacceliyet
kesbeder.
====
+
Vadesi gelmiş, rehinle temin edilmemiş bir para alacağı söz konusu ise ve bu
para alacağının borçlusunun kaçma ihtimali var veya mallarını normal halin
dışında devretmeye, tüketmeye başlamış ise ihtiyati haciz talebinde bulunulması
mümkündür.
+
İhtiyati haciz kararını verecek yetkili mahkeme:

.. Davalı, yani kaçma ihtimali bulunan veya mallarını anormal şekilde elden
çıkarmaya başlayan borçlunun, bulunduğu yer mahkemesi
.. HMK 10 uyarınca sözleşmenin ifa edileceği yer mahkemesi

* *Yetki sözleşmesi* açık veya zımni olarak yapılabilir. HMK 17 açık yetki
  sözleşmesini düzenlemiştir. İki tarafın da kamu tüzel kişisi veya tacir
  olmadan yapılmış yetki sözleşmeleri 6100 sayılı kanunun kabulünden itibaren
  (1 Eylül 2011) hükümsüzdür.
+
====
*HMK 17*: Tacirler veya kamu tüzel kişileri, aralarında doğmuş veya doğabilecek
bir uyuşmazlık hakkında, bir veya birden fazla mahkemeyi sözleşmeyle yetkili
kılabilirler. Taraflarca aksi kararlaştırılmadıkça dava sadece sözleşmeyle
belirlenen bu mahkemelerde açılır.
====
+
[NOTE]
====
1 Ekim 2011'den önce yapılmış olan sözleşmelerde yer alan yetki şartı ya da
bağımsız yetki sözleşmelerinin akıbeti ne olacaktır?

*Bir usuli hüküm veya işlem hangi an yargılamaya tesir edecekse, tesir ettiği
tarih itibariyle geçerli olan şekli hukuk hükümleri göz önüne alınmalıdır.*
Dolayısıyla, 1 Ekim 2011 yılından önce 1086 sayılı HUMK'a göre yapılmış yetki
sözleşmesi, uygulanacağı anda geçerli olan kanundaki yetki sözleşmesine tamamen
aykırılık teşkil ediyor ise o yetki sözleşmesinin kullanılabilmesi mümkün
değildir. 
====
+
Yetki sözleşmesi taraflar arasındaki tüm ihtilafları kapsamaz; genele şamil bir
sözleşme yapılamaz. Bu sebeple mevcut ya da ihtimal dahilindeki uyuşmazlığın
belirtilmesi gerekir.
+
Yetki sözleşmesi yapılabilmesi için, sözleşme konusu edilen ihtilaf hakkında
kanunda kesin yetkili mahkemenin düzenlenmemiş olması gerekir. Kanunun kesin
yetkili mahkemeyi belirttiği durumlarda o uyuşmazlık hakkında yetki sözleşmesi
yapılamaz. 
+
Yetki sözleşmesinin geçerliliği için yazılı olması şarttır. 
+
*Müspet (olumlu) yetki sözleşmesi*, tarafların bir veya birden fazla mahkemeyi
yetkili kıldığı sözleşmelerdir. *Menfi (olumsuz) yetki sözleşmesi* ise
tarafların ilgili uyuşmazlığın hangi yerlerde açılamayacağına dair yaptıkları
sözleşmedir. Menfi yetki sözleşmelerinde geriye kalan tüm mahkemeler yetkili
değildir; hangi mahkemelerin yetkili olduğu HMK ve ilgili kanunlara bakılarak
belirlenir.
+
*Münhasır yetki sözleşmesi* ile yekilendirilen mahkeme kesin yetkili
mahkemeymiş gibi sınırlanmış olur ve dolayısıyla yetkilendirilen mahkemenin
dışında bir mahkemede davanın açılması durumunda davanın her aşamasında, dava
şartlarından olan kesin yetki şartının yokluğu iddiasıyla yetki itirazı ileri
sürülebilir. Bu itiraz sonucunda davanın reddedilmesi gerekir.
+
[NOTE]
====
İlgili sözleşmenin içinde yetkiye dair bir şart var ise *halef*, bu yetki
şartından nasıl etkilenir?

Bu konuda iki görüş vardır:

. Halef maddi hukuk hükümlerinde olduğu gibi usul hukuku açısından da
halefiyetten doğan tüm yetkilere haizdir. Dolayısıyla yetki sözleşmesi onun
üzerinde doğrudan tesire sahiptir.
. Bir usul sözleşmesi hangi an itibariyle kullanılacak ise usuli sözleşmenin
kullanımından istifade edecek olan taraf, ilgili usuli işlemle sözleşmeye dair
düzenlemeye riayet etmelidir. Halef, ancak yetki sözleşmesinde bulunabilecek
taraflardan birisi niteliğine sahipse sözleşme ile bağlı olacaktır.
====
+
TIP: Sözleşmede yer alan kefil, ilgili sözleşmede yetki şartı yer alsa bile
bundan etkilenmez. Zira usuli sözleşmede, usuli işlemler açısından kefil söz
konusu değildir.
+
Tacir, her halükarda, her durumda bir yetki sözleşmesinin tarafı olamaz.
Ancak ticari faaliyetini ilgilendiren işlemlerle ilgili yetki sözleşmesi yapma
imkanına sahiptir.
+
Zaruri dava arkadaşlığının olduğu hallerde, zaruri dava arkadaşlarının her
birinin yetki sözleşmesinde taraf olmaları mecburidir. Biri dahi taraf değilse,
yetki sözleşmesinde belirtilmiş olan yerde dava açılamaz.

* Taşınmaz aynından doğan davalarda yetki kesin olarak taşınmazın bulunduğu yer
mahkemesidir.
+
====
*HMK 12*: (1) Taşınmaz üzerindeki ayni hakka ilişkin veya ayni hak sahipliğinde
değişikliğe yol açabilecek davalar ile taşınmazın zilyetliğine yahut alıkoyma
hakkına ilişkin davalarda, taşınmazın bulunduğu yer mahkemesi kesin yetkilidir.

(2) İrtifak haklarına ilişkin davalar, üzerinde irtifak hakkı kurulan
taşınmazın bulunduğu yer mahkemesinde açılır.

(3) Bu davalar, birden fazla taşınmaza ilişkinse, taşınmazlardan birinin
bulunduğu yerde, diğerleri hakkında da açılabilir.
====
+
Şahsi haklara ilişkin davalar, bunlar taşınmazla alakalı olsa dahi taşınmazın
aynından doğan dava olarak nitelendirilmez.
+
Davanın sonucunda verilecek karar, tapu sicilinde değişikliğe yol açacak ise o
dava taşınmazın aynına ilişkin kabul edilir ve HMK 12'deki kesin yetki kuralı
söz konusu olur. 
+
TIP: Şahsi hak olmasına rağmen, kira sözleşmesinin tapuya tesciline ilişkin
talep var ise kesin yetki kuralı vardır. Yine tapuda yer alan kira sözleşmesine
ilişkin şerhin kaldırılmasına ilişkin bir talep var ise dava yine taşınmazın
aynına ilişkin kabul edilir.

[caption=""]
.Yetki itirazı
****

====
*HMK 19*: (1) Yetkinin kesin olduğu davalarda, mahkeme yetkili olup olmadığını,
davanın sonuna kadar kendiliğinden araştırmak zorundadır; taraflar da
mahkemenin yetkisiz olduğunu her zaman ileri sürebilir.

(2) Yetkinin kesin olmadığı davalarda, yetki itirazının, cevap dilekçesinde
ileri sürülmesi gerekir. Yetki itirazında bulunan taraf, yetkili mahkemeyi;
birden fazla yetkili mahkeme varsa seçtiği mahkemeyi bildirir. Aksi takdirde
yetki itirazı dikkate alınmaz.

(3) Mahkeme, yetkisizlik kararında yetkili mahkemeyi de gösterir.

(4) Yetkinin kesin olmadığı davalarda, davalı, süresi içinde ve usulüne uygun
olarak yetki itirazında bulunmazsa, davanın açıldığı mahkeme yetkili hâle
gelir.  
====

* Kesin yetkiye ilişkin itiraz taraflar tarafından davanın her aşamasında ileri
sürülebilir.
* Kesin yetkiye aykırılık davanın her aşamasında yargılamayı yürüten hakim
tarafından değerlendirilir. Kesin yetki usule ilişkin bir dava şartıdır (HMK
114). 
* Yetkisizlik kararını veren mahkeme, yetkili yer mahkemesine atıf yapar. Atıf
yapılan mahkeme bu yetkisizlik kararı ile bağlı değildir.
* İlk itirazın yetki açısından geçerli olabilmesi için yetkili bir yer
mahkemesinin yetki itirazı ile birlikte belirtilmesi şarttır. 
* İlk itiraz olarak yetki itirazında bulunulmaması halinde yetkisiz yer
mahkemesi yetki kazanır.
****

* HMK 20'de görevsizlik kararı sonrası yapılacak işlemler ile yetkisizlik
kararı sonrası yapılacak işlemler aynı kapsamda gösterilmiştir.

. Yetkisizlik kararı nihai bir karardır, dolayısıyla kanun yoluna tabi
değildir. Eğer davanın esasına ilişkin olarak kanun yoluna müracaat imkanı yok
ise, yani karar verildiği an itibariyle kesin ise, bu durumda yetkisizlik
kararında belirtilen mahkemeye dosya iki hafta içinde intikal ettirilmek
zorundadır.
+
İlk derece mahkemesinin verdiği kararın kesin olup olmadığı müddeabihin
değerine göre tespit edilir. Davanın değeri *binbeşyüz TL'nin altında* ise
istinaf yoluna başvuru imkanı yoktur, dolayısıyla karar kesindir.
+
====
*HMK 341/2*: Miktar veya değeri binbeşyüz Türk Lirasını geçmeyen malvarlığı
davalarına ilişkin kararlar kesindir.
====
+
TIP: Kişiler hukukuna, aile hukukuna dair davalarda kanun yoluna müracaat esas
olduğu için söz konusu davalara dair ilk derece mahkemesinin vermiş olduğu
kararın verildiği an itibariyle kesin olması söz konusu değildir.

. Dava esasen kanun yoluna tabi ise, kanun yoluna ilişkin süre kanun yoluna
gidilmededen tamamlanırsa karar kesinleşmiş olur. Kanun yoluna başvurma süresi
iki haftadır ve bu süre ilk derece mahkemesinin vermiş olduğu kararı davacı
veya davalıya tebliğinden itibaren işlemeye başlar. Karar, kanun yoluna süresi
içinde bşavurulmadığından kesinleşmiş ise kesinleştiği andan itibaren iki hafta
içerisinde yetkisizlik kararından atıf yapılan yetkili mahkemeye dosya intikal
ettirilmelidir.

. Kanun yoluna müracaat imkanı var ve süresi içerisinde kanun yoluna müracaat
edilmiş ise, Bölge Adliye Mahkemesi Hukuk Dairesi'nin yetkiye ilişkin kararı
beklenecektir.

* Görevsizlik, yetkisizlik kararı esasa ilişkin olmadığı için yargılamaya devam
edilecek mahkeme yargılama giderlerine de hükmedecektir.

*  Yetkisizlik kararını veren mahkeme, kendiliğinden dosyayı yetki
atfettiği mahkemeye tevdi etmez. Süresi içinde dosyanın yetki atfedilen
mahkemeye gönderilmesi talep edilmez ise  dava açılmamış sayılır. Süresi
içerisinde müracaatta bulunulmuş ise yetkisizlik kararı verildiğinde yargılama
hangi aşamada ise o aşamadan itibaren kalanların tüketilmesi için taraflara
tebligat gönderilir.

* Her mahkeme kendi yargı çevresi içerisinde sınırlı olarak usuli işlemler
yapma imkanına sahiptir. Eğer bir mahkeme kendi yargı çevresi dışında usuli
işlem yapma ihtiyacı duyarsa, ilgili yargı çevresinde bulunan mahkemeden talep
etmek zorundadır. Buna *istinabe* adı verilir.
+
İstinabe için mutlaka istinabe olunan mahkemeye bir tebligat gitmelidir. Buna
*müzekkere* denilmektedir. Müzekkere ile birlikte istinabe olunan yer
mahkemesine hangi işlemin hangi dosya ile ilgili olarak yapılması istendiği net
bir şekilde belirtilmelidir.
+
İstinabe talebine muhatap olan mahkeme bu doğrultuda işlem yapmaya mecburdur.
Yapmaması halinde hakimin hukuki sorumluluğu doğar. 

* Bölge adliye mahkemesi hukuk dairesi de kendi yargı çevresi dışındaki bir
işlemin gerçekleştirilmesi noktasında istinabe talebinde bulunmalıdır. 
+
[NOTE]
====
İstinabe sureti ile müracaat olunmuş ilk derece mahkemesi hakimi, bölge adliye
mahkemesine tebliğ edilen dosya ile ilgili kararı veren hakim ise ne olur?

İlk derece mahkemesi nihai karar ya da esasa ilişkin bir karar verdikten sonra,
özellikle kanun yoluna müracaat edilmiş ise, kanun yolu neticesinde verilen
karar olmaksızın yeniden o dosya ilgili bir işlem yapamaz.

Burada istinabe olunan hakim, aleyhine kanun yoluna başvurulan kararı tesis
eden hakimdir. Burada istinabenin mümkün olup olmadığına HMK 354 cevap
vermemektedir. 

****
*HMK 354*: (1) Bölge adliye mahkemesi hukuk dairesince inceleme, davanın
özelliğine göre heyetçe veya görevlendirilecek bir üye tarafından yapılır.

(2) İnceleme sırasında gereken hâllerde başka bir bölge adliye mahkemesi veya
ilk derece mahkemesi istinabe edilebilir.
****

_Kürsüye göre_, burada istinabe mümkün değildir. İlgili işlemin
gerçekleştirilebilmesi için başka bir hakim bulunmalıdır. 1959 tarihli İçtihadı
Birleştirme Kararına göre o yargı çevresinde birden fazla aynı derece hakim var
ise bu hakimlerden biri eliyle istinabenin gerçekleştirilmesi gerekir.
Dolayısıyla aleyhine kanun yoluna müracaat eidlmiş kararı tesis eden hakim
istinabe suretiyle dahi olsa o dosyada herhangi bir işlem yapamaz. 
====

* Dava açılırken davaya ilişkin HMK 120 kapsamında bir avans zaten dosyaya
yatırılmaktadır. Bu avans yetersiz kalırsa istinabe olunan yer mahkemesi de
kendisinden talep edilen işlemin gerçekleştirilmesi açısından gereken masrafı
davanın ilgilisinden harçlar kanunu uyarınca talep edebilir. Harçlar Kanunu
madde 35 uyarınca bu masraf süresi içerisinde yatırılmamış ise o işlemin
yapılmasından vazgeçilmiş sayılır. Dosya yeniden istinabe eden mahkemeye tevdi
edilir.

CAUTION: Davanın esası, konusu vurgulanarak yetki tespit edilmiş ise, yani
kesin yetki kuralı varsa o davada istinabeye müracaat imkanı yoktur. Kesin
yetkinin geçerli olduğu davalar özellikle davanın konusunun tereke, taşınmaz
veya iflas olması halidir. Bu tip davalarda bir tanığın dinlenmesi açısından ya
da isticvap faaliyeti açısından istinabe mecburiyeti doğarsa usul hukuku
uyarınca hakimin istinabeye müracaat mecburiyetini dava dosyasında ayrıca
belirtmesi gerekir. 

* *Naip hakim*, toplu mahkemelerde söz konusu olan bir işlemdir. Hukukumuzda
toplu mahkeme olarak sayılabilecek üç mahkeme vardır: Asliye Ticaret Mahkemesi,
Bölge Adliye Mahkemesi Hukuk Dairesi, Yargıtay Hukuk Dairesi. Yargıtay Hukuk
Dairesinde tahkikak gerçekleşmediğinden naip hakim söz konusu olmamaktadır.
+
Naip tayin edilmiş hakim, görevlendirilmiş olduğu işlemlerde yargısal faaliyeti
yürütmekle yükümlüdür. En sık karşılaşılan, tahkikaktı gerçekleştirmek,
tahkikat incelemesini yapmak, tanık dinlemek, keşfe gitmek gibi kendisine
hasredilen işlemler naip hakim eli ile gerçekleştirilmektedir. 
+
Naip hakimin atanması için, heyette bulunan hakimlerin karar vermesi gerekir.
Bu karara istinaden kendisine tebliğ olunmuş naip hakim usuli işlemi
gerçekleştirme külfeti altına girer ve onun tarafından bu işlemin yapılması
esastır.

<<<

=== USULİ İŞLEM

* Dava, açılmasından tamamlanmasına kadar usuli işlemler silsilesinden oluşur.
Davacının dava dilekçesini hazırlaması, davalının cevap dilekçesini vermesi,
dilekçeler teatisi aşamasının tamamlandığına dair yargılamayı yürüten hakimin
ara karar tesisi, ön inceleme aşamasında tarafların yaptığı her işlem, bu
silsilenin içinde gerçekleşecek usuli işlemlere örnektir.
+
[caption=""]
.Usuli işleme dair görüşler
****
. *Dar anlamda usuli işlem görüşü*: Şekli hukuka ilişkin mevzuat esas
alınmalıdır, usuli işlem niteliğinde bir işlem tesis edilmemiş ise bu işlem
usuli işlem değildir. Usuli işlem ancak dava derdestliği kazandıktan sonra
yapılabilir.
. *Geniş anlamda usuli işlem görüşü*: _Kürsünün görüşüdür_. Tarafın ya da
tarafların yaptıkları işlemler, yargılamaya tesir etmeyi amaçlıyor ise o işlem
usuli işlemdir. Dolayısıyla taraflar yargılamaya başlamadan önce de usuli işlem
yapabilirler.
****
+
====
*HUMK 82*: (1) Esaslı merasime riayet edilmeksizin yapılan usule mütaallik
muameleler bu bapta menfaati bulunan kimsenin davayı takipten evvel talebi
sebkederse iptal olunur.

(2) Umumi intizamı veya muamelei usuliyenin istihdaf ettiği maksadı temin
mülahazasiyle vazolunan ahkam esaslı merasimden addolunur.

(3) Esaslı olmıyan merasime riayet edilmezse bu bapta menfaati olan kimsenin
davayı takipten evvel talebi sebkederse tashih veya ikmal olunur.
====
+
HUMK 82/1'de; kamu düzenine uygun olarak yapılmamış, usule ilişkin bir işlem
varsa, o işlemden menfaati menfi yönde etkilenmiş kişi davayı takip etmeden
talep ederse ilgili işlem iptal olunur, denilmektedir.
+
HUMK 82/2'ye göre, bir usuli işlemin geçerliliği açısından şekil şartları
kanunda düzenlenmemiş olsa dahi ilgili usuli işlemin kanuna konmuş olması
yargılamanın sıhhati ve kamu düzeni karakteri içeriyorsa HUMK 82/1'deki usul
uygulanacaktır.  Örneğin isticvap, içtinap, pasif kalma.
+
HUMK 82/3'e göre ise, kamu düzeni karakterine sahip olmayan bir şekil kuralı
var ise ve buna riayet edilmemişse davayı takipten önce talep ederse ilgili
işlem düzeltilecek veya tamamlanacaktır.
+
NOTE: Dava dilekçesinde dava konusunun değeri bulunması gereken esaslı bir
unsur değildir. Dolayısıyla bulunmaması dava dilekçesinin iptalini gerektirmez.
Ancak dava konusunun değerinin dava dilekçesinde bulunmaması nedeniyle
yatırılacak harç, ilgili kararın istinafa taşınıp taşınamaması, istinaf
ardından temyize taşınıp taşınamaması, ispat rejimi gibi kurumların tespiti
mümkün olmaz. Bu sebeple dava konusunun değeri doğrudan yargılamaya tesir eder.
Buradaki eksiklik HUMK 82/3 uyarınca düzeltilmesi veya tamamlanmalıdır. Bu
durum muhatap davalının cevap dilekçesi ile ileri sürmesi gereken ilk husustur.
+
Hukuki işlem ile usuli işlem birbirinden farklıdır. Hukuki işlemler, usuli
işlemlerin içinde yer alabilir. Ancak bu durum usuli işlemin karakterine etki
etmez. 
+
NOTE: Dava dilekçesi sahih ise dava dilekçesinin içinde yer alan maddi hukuka
dair hukuki işlem geçerlidir. HUMK 82 uyarınca dava dilekçesi iptal olunursa,
dilekçenin içinde yer alan hukuki işlem de bertaraf olur.
+
WARNING: İstikbalde doğacak bir usuli hakkın, taraflar tarafından sulhle veya
feragat ile ya da kabul ile bertaraf edilmesi mümkün değildir.
+
Hukuki işlemde iradenin sonucunu taraf talep eder. O irade neticesinde
gerçekleşecek sonuç, irade ile beraber tamamlanır. Oysa usuli işlemin
sonuçları, HMK da yer alsın ya da almasın, taraf veya tarafların iradesi
haricinde sadece kanun tarafından belirlenmiş alanda doğar.
+
Usuli işlemin şekle tabi tutulmasının sebebi, hasmın savunma imkanını
korumaktır. Davalının, davacı tarafından gerçekleştirilen, hakim tarafından
gerçekleştirilen usuli işlemlere dair muhalefitini sağlıklı, isabetli bir şekil
yapmasını sağlayabilmektir.
+
Hakim yaptığı usuli işlemlerin hepsini dava dosyasına sirayet ettirmek
zorundadır. Hakimin yaptığı usuli işlemin hangi kapsamda olduğu ve o kapsamda
hangi sonuçların doğacağı ara kararda, tutanakta ya da nihai kararda
belirtilmiş olan hususlarda sınırlıdır. Sözlü beyan hakim tarafından hiçbir
nitelikte bağlayıcı değildir. Davacının da davalının da ancak dilekçelerine ve
tutanağa sirayet eden beyanları yargılamaya tesire haizdir.
+
Her bir usuli işlemin fiilen yapılması, gerçekleştirilmesi ya da
gerçekleştirilmemesi ayrı sonuçlar doğuracaktır.
+
[NOTE]
====
Davalıya dava dilekçesinin tebliğinden sonra:

. Davaya cevap dilekçesi ile cevap verebilir.
. Davayı kabul edebilir.
. Süresi içerisinde cevap dilekçesini mahkemeye sunmayabilir. 

Cevap dilekçesinin mahkemeye sunulmaması da bir usuli işlemdir. Çekinme sureti
ile, pasif kalma ile bir usuli işlem gerçekleştirilir. Davaya cevap vermeme
işleminin sonucu davacının iddialarının tümünü inkardır.
====

* Davayı açmak ile maddi hukukta doğacak sonuçlardan ilki, dava konusu olan
talebe dair zamanaşımının kesilmiş olmasıdır.
+
====
*TBK 157*: (1) Bir dava veya def’i yoluyla kesilmiş olan zamanaşımı, dava
süresince tarafların yargılamaya ilişkin her işleminden veya hâkimin her
kararından sonra yeniden işlemeye başlar.

(2) Zamanaşımı, icra takibiyle kesilmişse, alacağın takibine ilişkin her
işlemden sonra yeniden işlemeye başlar.

(3) Zamanaşımı, iflas masasına başvurma sebebiyle kesilmişse, iflasa ilişkin
hükümlere göre alacağın yeniden istenmesi imkânının doğumundan itibaren yeniden
işlemeye başlar.
====
+
Davacının her işlemi, davalının her işlemi, hakimin her işlemi, dava konusuna
ilişkin zamanaşımı süresini keser.
+
Benzer bir durum icra hukukunda da mevcuttur. İcra takibine konu edilmiş para
borcunun zamanaşımı, icra dosyasının içerisinde yapılacak işlemler marifeti ile
sürekli kesilir.
+
[NOTE]
====
Çekte zamanaşımı süresi 3 yıldır. Çekten doğan para alacağının tahsiline
ilişkin icra yolu ile takibe başlandığında, takip talebi hazırlanıp icra
dairesine verilir. Bunun üzerine de icra dairesi ödeme emrini hazırlar ve bunu
borçluya tebliğ eder. Zamanaşımı bu işlemlerden hangisinde kesilir?

Bu çekten doğan alacak hakkı asliye ticaret mahkemesinde dava konusu edilseydi,
dava dilekçesinin mahkemeye sunulması ile zamanaşımı kesilmiş olacaktı.

İcra dosyasında ise taraf işlemleri ve takip işlemleri olarak ayrıma gidilir.
Zamanaşımını kesen işlemler icra müdürünün veya icra memurunun yaptığı
işlemler, yani takip işlemleridir.
====

* HMK 307 vd. yer alan işlemler, *çifte karakterli usuli işlemlerdir*. Bu
nitelikteki işlemlerin için aynı zamanda maddi hukuk işlemleri de vardır.
+
[caption=""]
.Çifte karakterli usuli işlemler
****
. *Feragat* (HMK 307): Davacı, davalı aleyhine ileri sürdüğü hakkı bertaraf
eder. Dava kendi aleyhine neticelenir.
. *Kabul* (HMK 308): Davalı, dava konusunu kabul etmekle birlikte hakkı
varlığını, hakkın sonucunun kendi üzerinde tesiri bulunduğuna icazet eder ve
dava neticelenir. 
. *Sulh* (HMK 313): Tarafların arasındaki, tarafların tasarrufuna bırakılmış
olan ihtilafa dair sözleşme yapılır ve bu sözleşmeye göre ihtilaf tasfiye
edilerek dava neticelenir.
****
+
Çifte karakterli usuli işlemlerin geçerlilik şartına riayet edilmemesi halinde
gösterilecek muhalefet HUMK 82'de düzenlenmiştir. Sadece usul hukukuna dair
usuli işlemlerin geçerlilik şartları, eğer geçerlilik şartlarına riayet
edilmemişse iptal kabiliyeti ya da tashis kabiliyeti kanunda düzenlenmiştir.
+
TIP: İçerisinde maddi hukuk, yani hakkı taşıyan çifte karakterli usuli işlemler
üzerinde irade sakatlığı olabilir. Davayı neticelendirmeyi amaçlarken aynı
zamanda hakkı da bertaraf ettiği için davacı ya da davalı irade bozukluğu ile
meydana gelmiş bir sonucu doğurabilir. Dolayısıyla kabul, sulh, feragat gibi
çifte karakterli usuli işlemlerin iptali müstakil bir dava yolu ile talep
edilebilir.

* Usuli işlemin şarta bağlanması mümkün değildir. Çifte karakterli usuli
işlemlerde buna imkan tanıyan bazı haller vardır. Ancak tek taraflı usuli
işlemlerde, taraf ve hakimin usuli işlemlerinin şarta tabi kılınması mümkün
değildir. 

[NOTE]
====
Bir muhalefet, örneğin yetki itirazı, davalı tarafından ileri sürülmüş ise,
yargılamayı yürüten hakimin davalının talebini reddetmesiyle yargılama bir
sonraki aşamaya geçer. Yetki itirazı bir ön sorundur ve bunun reddi bir ara
karardır.

Bahsi geçen yetki muhalefetine dair hakim tarafından verilmiş ret kararı,
yargılamanın ilerleyen safhalarında tarafları ve hakimi bağlayacak mıdır? Ara
karardan rücu mümkün müdür?

TIP: Yargıtay kendi huzuruna gelmiş bir dosyada bozma kararı vermiş ise, ilk
derece mahkemesi de bozma kararına uymuş ise, bozma kararına uyduktan sonra
yapacağı uygulamanın sınırı bozma kararındaki gerekçe ile bağlı olmasıdır.
Bozma kararının gerekçesinde yer almayan hususlar usuli kazanılmış hak olarak
değerlendirilebilir.

Üst merciin incelemesi, bozması söz konusu olmadan usuli kazanılmış hak ara
kararlar bakımından hangi noktada ortaya çıkar?

Maddi mesele ilgili ara kararda yapılan tespitlerden rücu imkanı yoktur.
Örneğin bir delil sunulmuş ve delilin incelenmesi tamamlanmış ise, artık o
delilin esasen vakıanın ispatı için kullanılamayacağına dair karar verilemez.

Buna karşılık usul hukukuna dair verilmiş olan ara kararlardan rücu imkanı
vardır. Yetkisizlik itirazını inceleyen hakim, yetkili olduğunu görürse
yargılamaya devam eder. Davanın ilerleyen safhalarında aslında o davada kesin
yetkili mahkeme olduğu ispat edilirse yetkisizlik iddiasına ilişkin yargılama
kapsamında ilk derece mahkemesi hakiminin rücu etmesi mümkündür.

Geçici hukuki korumalara (ihtiyati tedbir, delil tespiti vs.) ilişkin ara
kararlara karşı kanun yoluna gitme imkanı vardır. Bunlar dışındaki ara
kararlara karşı ise kanun yoluna gidilemez.  
====

* Hakimin yapacağı usuli işlemlere dair kanundaki süreler geçersizlik sonucunu
doğuracak mahiyette değil, disiplineldir. Tarafların yapacağı usuli işlemlere
ilişkin kanundaki süreler ise ilgili işlemin yapılma imkanını ortadan kaldırıcı
niteliktedir.

* Herhangi bir usuli işlemin zımni olarak gerçekleştirilmesi ya da
gerçekleştirilmiş olmasının kabulü mümkün değildir. Dosyada bulunmayan ya da
tarafa tebliğ edilmeyen usuli işem sonuç doğurmaz, yargılamaya tesir etmez.

.Feragat
****
* Tarafların tasarrufuna terk edilmiş olmayan dava konuları için feragat
iradesi ileri sürülebilmesi, sürülmüşse iradenin sonuç doğurabilmesi mümkün
değildir. 
+
[caption=""]
.Cumhuriyet savcısının davada yer alması
====
*HMK 70/3*: Cumhuriyet savcısının yer aldığı dava ve işler üzerinde taraflar
serbestçe tasarruf edemezler.
====

* Davanın tamamından feragat mecburiyeti yoktur, kısmi feragat da mümkündür.

* Birbiri ile karıştırılan üç kurum:

. *Feragat* (HMK 307)
. *Davanın geri alınması* (HMK 123): Davacı hüküm kesinleşinceye kadar ancak
davalının açık rızası ile davayı geri alabilir. Geri alınmış olan dava yeniden
açılabilir.
. *Davayı müracaatta bırakma* (HMK 150): Tahkikat aşamasında davacı usulüne
uygun olarak davet edilmiş olduğu duruşmaya mazaretsiz olarak katılmazsa,
davalının beyanına tabi olarak hakim tarafından dosya işlemden kaldırılır.
Dosya işlemden kaldırıldıktan sonra üç ay içerisinde davacı yenileme dilekçesi
vermezse dava açılmamış sayılır.

* Feragat iradesinin, ilk derecesi mahkemesi yargılaması sırasında ilk derece
mahkemesine, istinaf sırasında bölge adliye mahkemesi hukuk dairesine, Yargıtay
aşamasında ise Yargıtay hukuk dairesine yazılı olarak sunulması şarttır. 
+
İlk derece mahkemesi veya bölge adliye mahkemesi hukuk dairesine feragat
iradesinin intikali ardından yapılacak tek inceleme feragat beyanının HMK'daki
kurallara riayet edilerek yapılıp yapılmadığıdır. Bunlara bakıldıktan sonra
davalı lehine karar verilecektir.
+
Yargıtay aşamasında feragat beyanı verilirse, Yargıtay Hukuk Dairesi'nin
vereceği karar bozmadır. Bozma kararından sonra dosya yeniden ilk derece
mahkemesine intikal eder. İlk derece mahkemesi vaka mahkemesi olduğu için
feragat kapsamında davalı lehine karar verir ve davayı neticelendirir. 
****

[NOTE]
====
Haciz tutanağında yer alan feragat beyanının mahkemeyi bağlayıcı etkisi var
mıdır?

Haciz sırasında borçlu dava hakkından feragat ettiğini beyan ettiyse, bu
borçlunun takip konusu olan borçun bertaraf olduğunu kabul ettiği sonucunu
doğurur. 

İcra tutanağında bu yöndeki bir beyanın dava açma hakkını ortadan
kaldırmayacağı Yargıtay tarafından kabul edilmektedir. Çünkü icra dairesi
nezdinde görülen bir yargılama faaliyeti yoktur. *Derdest dava esnasında davaya
sirayet etmemiş olan feragat beyanı itibar görmeyecektir*.
====

* Davacı, feragat yönündeki irade beyanında bir irade sakatlığının olduğunu
iddia ederse bunu dava konusu edecektir. Görevli ve yetkili mahkeme,
yargılamaya yürüten mahkeme esasa ilişkin kararını, yani hükmünü henüz vermemiş
ise aynı mahkeme veya başka bir görevli ve yetkili mahkeme de açılabilir.

* *Sulh sözleşmesi* çifte karaketerli bir usuli işlemdir. Dolayısıyla dava
konusu olan hakka tesir ettiği gibi davaya da tesir eder. 
+
Derdest bir dava söz konusu değilken yapılmış bir sulh sözleşmesi sadece ve
sadece maddi hukuka ilişkin bir sözleşmedir. Dolayısıyla hakka tesir eder. 
+
İstikbalde açılacak bir davaya matuf nitelikte bir sulh sözleşmesi
yapılabilmesi de mümkün değildir.
+
Derdest bir dava içinde yapılmış sulh sözleşmesi, başka bir işleme gerek
kalmaksızın davayı sona erdirir. Ancak bu hakimin sulh sözleşmesini hiçbir
şekilde incelemeyeceği anlamına gelmez. Hakim sulh sözleşmesinin HMK 313 vd.
hükümlerine uygun nitelikte olup olmadığını değerlendirmek zorundadır.
+
Yargılamayı yürüten hakim, HMK 313 vd. hükümlerinden hariç olmak üzere derdest
davanın taraflarının, sulh olunabilecek nitelikte bir dava konusunu ihtiva edip
etmediğini öncelikle değerlendirecektir. Bu değerlendirme sıhhatli ise HMK 313
vd. hükümlerine göre sulh sözleşmesini inceler.
+
[caption=""]
.Sulh
====
*HMK 313*: (1) Sulh, görülmekte olan bir davada, tarafların aralarındaki
uyuşmazlığı kısmen veya tamamen sona erdirmek amacıyla, mahkeme huzurunda
yapmış oldukları bir sözleşmedir.

(2) Sulh, ancak tarafların üzerinde serbestçe tasarruf edebilecekleri
uyuşmazlıkları konu alan davalarda yapılabilir.

(3) Dava konusunun dışında kalan hususlar da sulhun kapsamına dâhil edilebilir.

(4) Sulh, şarta bağlı olarak da yapılabilir.
====
+
Sulh sözleşmesi geçerli ise dava sona erer. Sulh sözleşmesi hüküm ile beraber
tesvik edilir (belgelendirilir). Hükmün gerekçesi sulh sözleşmesidir.
+
Feragat ve kabulden farklı olarak şarta bağlı sulh sözleşmesi yapılabileceği
kabul edilmiştir.
+
Dava konusu edilmemiş olan ancak dava tarafları arasında ihtilaflı konular da
HMK 313/3 uyarınca sulh sözleşmesine konu teşkil edebilir.
+
[caption=""]
.Sulhun zamanı
====
*HMK 314*: (1) Sulh, hüküm kesinleşinceye kadar her zaman yapılabilir.
====
+
İstinaf aşamasında da, Yargıtay aşamasında da sulh sözleşmesi yapılabilir.
+
[caption=""]
.Sulhun etkisi
====
*HMK 315*: (1) Sulh, ilgili bulunduğu davayı sona erdirir ve kesin hüküm gibi
hukuki sonuç doğurur. Mahkeme, taraflar sulhe göre karar verilmesini
isterlerse, sulh sözleşmesine göre; sulhe göre karar verilmesini istemezlerse,
karar verilmesine yer olmadığına karar verir.

(2) İrade bozukluğu ya da aşırı yararlanma hâllerinde sulhun iptali
istenebilir.
====

<<<

=== SÜRELER

* Mahkemeler resmi çalışma gün ve saatlerinde görevlendirilmiştir.
+
[caption=""]
.Mahkemenin çalışma zamanı
====
*HMK 149*: Mahkemeler, resmî çalışma gün ve saatlerinde görev yaparlar. Ancak,
zorunluluk veya gecikmesinde zarar olan hâllerde, keşif, delillerin tespiti ve
günlük duruşma listesinde yazılı işler gibi işlemlerin, resmî tatil günlerinde
veya çalışma saatlerinin dışında da yapılmasına karar verilebilir. 
====
+
Delil tespiti, geçici hukuki himaye tedbiridir. Delillerin korunmasını amaçlar.

* Adli tatil 20 Temmuz'da başlar 31 Ağustos'da biter. Adli tatil her yıl aynı
süreler arasında yapılmaktadır. 
+
Adli tatil usule ilişkin bir süreçtir. Maddi hukuka ilişkin süreler için etkisi
yoktur.
+
[caption=""]
.Adli tatilde görülecek dava ve işler
====
*HMK 103*: (1) Adli tatilde, ancak aşağıdaki dava ve işler görülür:

a) İhtiyati tedbir, ihtiyati haciz ve delillerin tespiti gibi geçici hukuki
koruma, deniz raporlarının alınması ve dispeçci atanması talepleri ile bunlara
karşı yapılacak itirazlar ve diğer başvurular hakkında karar verilmesi.

b) Her çeşit nafaka davaları ile soybağı, velayet ve vesayete ilişkin dava ya
da işler.

c) Nüfus kayıtlarının düzeltilmesi işleri ve davaları.

ç) Hizmet akdi veya iş sözleşmesi sebebiyle işçilerin açtıkları davalar.

d) Ticari defterlerin kaybından dolayı kayıp belgesi verilmesi talepleri ile
kıymetli evrakın kaybından doğan iptal işleri.

e) İflas ve konkordato ile sermaye şirketleri ve kooperatiflerin uzlaşma
suretiyle yeniden yapılandırılmasına ilişkin işler ve davalar.

f) Adli tatilde yapılmasına karar verilen keşifler.

g) Tahkim hükümlerine göre, mahkemenin görev alanına giren dava ve işler.

ğ) Çekişmesiz yargı işleri.

h) Kanunlarda ivedi olduğu belirtilen veya taraflardan birinin talebi üzerine,
mahkemece ivedi görülmesine karar verilen dava ve işler.

(2) Tarafların anlaşması hâlinde veya dava bir tarafın yokluğunda görülmekte
ise hazır olan tarafın talebi üzerine, yukarıdaki iş ve davalara bakılması,
adli tatilden sonraya bırakılabilir.

(3) Adli tatilde, yukarıdaki fıkralarda gösterilenler dışında kalan dava ve
işlerle ilgili olarak verilen dava, karşı dava, istinaf ve temyiz dilekçeleri
ile bunlara karşı verilen cevap dilekçelerinin ve dosyası işlemden kaldırılan
davaları yenileme dilekçelerinin alınması, ilam verilmesi, her türlü tebligat,
dosyanın başka bir mahkemeye, bölge adliye mahkemesine veya Yargıtaya
gönderilmesi işlemleri de yapılır.

(4) Bu madde hükümleri, bölge adliye mahkemeleri ile Yargıtay incelemelerinde
de uygulanır.
==== 
+
Kanunda çözümü ivedi olarak belirtilen işler de adli tatilde görülmektedir.
Ayrıca taraflardan birinin talebi üzerine mahkeme uygun görürse o iş dahi adli
tatilde görülebilir.
+
Her ne kadar bir iş adli tatilde görülmüyor olsa bile adli tatilde o işle
ilişkili olarak her türlü dilekçe ve o dilekçelere karşı dilekçe verilebilir.
Adli tatilde tebligat da yapılır.
+
Adli tatilde süreler işler. Ancak süre adli tatilin içinde son bulursa, süre
adli tatilin bittiği günden 1 hafta sonrasına uzar.

* Kural olarak kanunun belirlediği süreler kesindir. Ayrıca hakim de bir süreyi
belirlerken sürenin kesin olmasına karar verebilir.
+
Yargıtay, hakim kesin süreyi belirlerken, hukuki dinlenilme hakkını ortadan
kaldıracak bir şekilde süre vermemesi gerekir, demektedir.
+
Hakim kesin süreler müdahale edemez. Kanunun belirttiği süre içerisinde işlem
yapılmamışsa, kanunun bağladığı özel sonuç doğar, kanun özel bir sonuç
bağlamamışsa o işlemi yapma hakkı ortadan kalkar.
+
Hakimin belirlediği süre kural olarak takdiri süredir. Ancak hakim, bir sürenin
kesin olmasını da belirleyebilir. Yargıtay bu konuda bazı kıstaslar koymuştur.
+
****
. Hakim sürenin kesin olduğunu belirtmelidir.
. O süre içerisinde hangi işlemlerin yapılması gerektiğini belirtmelidir.
. Bir takım giderler varsa o giderlerin yatırılması gerektiğini belirtmelidir.
. Belirlediği süre içerisinde işlemin yapılmaması halinde doğacak hukuki
sonuçları belirtmelidir.
****
+
Hakimin verdiği takdiri sürelere uyulmaması halinde, hakim ikinci bir süre
verebilir. Ancak ikinci verilen süren kesin süredir. Hatta Yargıtay, bu sürenin
kesin süre olduğunun belirtilmesine gerek dahi olmadığını ifade etmiştir.

* Süreler net olarak belirlendiyse tebliğ tarihi ya da tefhim tarihi hesaba
katılmaz. Örneğin, 21.11.2016 tarihinde tebliği ile verilen 7 günlük süre
28.11.2016 tarihinde sona erer. 
+
Hesap yaparken tatil günleri de hesaba katılır. Son gün tatile denk gelirse,
tatili takip eden ilk iş gününün mesai saatinde süre sona erer.

* Kesin süre kaçırıldığı takdirde kanun koyucu, eğer bu kaçırma sebebi haklı bir
sebebe dayanıyorsa kaçırılan süre için eski hale iade imkanı sunmuştur. Bunun
için kesin sürenin varlığı, kesin sürenin elde olmayan sebeğle kaçırılması ve
kesin süre içerisinde yapılması gereken işlem ile ulaşmak istenen sonuca başka
bir yolla ulaşılamamasını şarttır. 
+
Eski hale iadede, hükmün icrası ya da yargılamanın ertelenmesi gerekmez. İlk
derece mahkemesinde ve bölge adliye mahkemesinde başvuru ön sorun gibi
incelenir. Eski hale iade başvurusu kabul edildiğinde yapılmış bazı işlemler
iptal olunmak gerekir. Ancak dava süresince yapılan her işlem iptal edilemez.
+
[caption=""]
.Islahın etkisi
====
*HMK 179/2*: Ancak ikrar, tanık ifadeleri, bilirkişi rapor ve beyanları, keşif
ve isticvap tutanakları, yerine getirilmiş olan veya henüz yerine getirilmemiş
olmakla beraber, karşı tarafın yerine getireceğini ıslahtan önce bildirmiş
olması koşuluyla, yeminin teklifi, reddi veya iadesi ıslah ile geçersiz
kılınamaz.  
====

<<<

=== TARAFLAR

* HMK 382 vd. düzenlenen çekişmesiz yargı işleri bir kenara bırakılacak olursa
kalan tüm hukuk yargılamasına iki taraf prensibi geçerlidir. Davada bir davalı
ve davacı bulunması bir dava şartıdır (HMK 114) ve bu durum gerek davanın
tarafları gerekse yargılamayı yürüten hakim tarafından yargılama süresince
gözönünde bulundurulmalıdır.

* Hukuk hakimi bir ihtilafı çözmek için hakkın korunmasını, hakkın tesis
edilmesini veya tespitini talep eden bir beyana ihtiyaç duyar. Dolayısıyla
hakim ancak davacının dava dilekçesini vermesiyle yargılamaya başlayabilir.

* Hakkın kendisine teslimini, hakkın korunmasını, bir işlemin tespit edilmesini
talep eden taraf, yani davacı aynı zamanda kendisine karşı bir hasım da
konumlandırmak zorundadır. Dolayısıyla yargılamada davalıyı tespit eden
davacının iradesidir.

* Dava dilekçesinin zorunlu unsurlarından birisi, davacının kendisini ve
davalıyı tanımlamasıdır. Davalı ve davacı hem dava dilekçesinin zaruri unsuru
(HMK 119) hem de dava şartıdır (HMK 114). 

* *Şekli taraf teorisi*, davacının dava dilekçesi işleminde kendisini davacı
olarak belirlemesi ve davanın karşı tarafı olarak bir gerçek veya tüzel kişiyi
konumlandırması ile tarafların tespit edildiğini kabul eder. 
+
*Maddi taraf teorisi* ise, dava konusu edilmiş olan maddi hukuk işleminin
taraflarının kim olduğu üzerinden tarafların tespitini yapmaktadır.
+
Maddi taraf teorisine ilişkin birinci eleştiri; ihtilaf konusu edilmiş maddi
hukuk işleminin analizi tamamlanmadan tarafın tespiti isabetli bir şekilde
mümkün olamayacaktır. İkinci eleştiri ise; maddi hukuk ilişkisinde taraf
olmayan kişilerinde bazı durumlarda dava açma hakkı vardır. Bir hukuki
ilişkinin tarafı olmayan üçüncü bir kişi, ilgili hukuki işlemden menfaati
olduğundan dolayı dava açma hakkına sahiptir.
+
_Kürsüye göre_ maddi taraf teorisi şekli taraf teorisi içinde eritilmelidir.
Maddi taraf teorisi hepten reddedilmesi gereken bir teori değildir. Maddi taraf
teorisi davada sıfata tekabül eden bir teoridir. Sıfat bir dava şartı değildir.
Usule ilişkin değil, maddi hukuka ilişkin bir konudur. 

* HMK 70, Cumhuriyet Savcısının davada yer alabileceği istisnai halleri
düzenlemiştir. Bu haller genel değil ancak kişiler ve aile hukukunda söz konusu
olabilir.
+
[caption=""]
.Cumhuriyet savcısının davada yer alması
====
*HMK 70*:  (1) Cumhuriyet savcısı, kanunda açıkça öngörülen hâllerde, hukuk
davası açar veya açılmış olan hukuk davasında taraf olarak yer alır.

(2) Cumhuriyet savcısı, resmî dairenin bildirimine rağmen dava açmaz ise ihbar
eden resmî daire, Cumhuriyet savcısının yargı çevresinde görev yaptığı ağır
ceza merkezine en yakın kıdemli asliye hukuk mahkemesi hâkimine itiraz
edebilir. Bu hususta 4/12/2004 tarihli ve 5271 sayılı Ceza Muhakemesi Kanununun
172 ve 173 üncü maddeleri kıyasen uygulanır.

(3) Cumhuriyet savcısının yer aldığı dava ve işler üzerinde taraflar serbestçe
tasarruf edemezler.
====
+
CAUTION: Burada Cumhuriyet Savcısı bir gerçek kişidir. Sadece HMK 70'de verilen
yetki ile bu davayı açma hakkın sahiptir. Dava açıldıktan sonra hukuk
yargılamasında normal bir gerçek kişi ya da normal bir tüzel kişileri hangi
işlemleri yapacaksa Cumhuriyet Savcısı da aynı işlemleri yapacaktır. CMK'daki
yetkilerle donatılmış bir yargılama prosedürü söz konusu değildir.
+
Cumhuriyet Savcısının taraf olduğu davalarda sulh, feragat, kabul gibi
yargılamayı taraf iradesiyle sona erdirecek bir işlem gerçekleştirilemez.
Cumhuriyet Savcısı tarafından dava açılmışsa davanın hakimin vereceği karar ile
tarafların iradesinden bağımsız olarak neticelenme mecburiyeti vardır.

* Hakkının korunmasını talep eden kişi, dava dilekçesi verme anından itibaren
davada davacı olarak konumlanır. Davacının verdiği dava dilekçesi, dilekçede
davalı olarak gösterilen kişiye geçerli bir şekilde tebliğ edildiği an bu kişi
davalı olarak konumlanır.

* HMK 50, *taraf ehliyetini* hak ehliyetine (MK 8, MK 48) atıf yaparak
tanımlamıştır.
+
[caption=""]
.Taraf ehliyeti
====
*HMK 50*: (1) Medenî haklardan yararlanma ehliyetine sahip olan, davada taraf
ehliyetine de sahiptir.
====
+
Hak ehliyetinin başladığı an tespit edilirken sağ ve tam olmak şartı kabul
edilir. Bununla beraber _kürsüye göre_ cenin de davada taraf olabilir. Cenin
davada taraf ise, kanuni temsilcisi yani annesi tarafından temsil edilecektir.
+
Davacı tarafta tüzel kişi var ise MK 47'ye uygun olmalıdır. Her tüzel kişilik
için doğum anı birbirinden farklıdır. Tüzel kişinin doğumu için gerekli
işlemler yapılmadan dava açılırsa ve özellikle tüzel kişi davacı tarafta ise
dava şartının gerçekleşmemiş olması sebebi ile davanın usulden reddi gerekir.
Tüzel kişi kuruluşuyla ilgii belgeleri davayı açarken mahkemeye sunmak
mecburiyetindedir.

* Ölüye karşı dava açılamaz, dava şartı yokluğundan dava reddedilir. Çünkü
davanın açılma tarihinden önce hak ehliyeti / taraf ehliyeti kalkmıştır ve HMK
50'yi sağlayan nitelikte bir davalı yoktur.

* _Kürsüye göre_ şirket tasfiye haline girmişse şirketi tsfiye memurları
yönetir. Bu demektir ki davanın tarafı olan şirket tasfiye aşamasında olsa dahi
bu durum yargılamaya taraf ehliyeti konusunda tesir etmez, yargılama devam
eder.
+
Fakat dava neticelendikten sonra davacı, tasfiye edilmiş bir şirketteki
talebini mahkeme kanalı ile elde etmek üzere bir dava açarsa bu durumda
açılacak olan davada öncelikle yapılması gereken husus tasfiyesi tamamlanmış
olan şirketin ilgili davaya münhasır olmak üzere ihya edilmesidir. Davacının
ihya edilmiş, canlandırılmış olan şirkete dava açabilmesi mümkündür. 
+
*Bu Yargıtay tarafındanda kabul edilmiş bir yöntemdir.*

* Taraf değişikliği için karşı tarafın açık rızası şarttır.
+
[caption=""]
.Tarafta iradî değişiklik
====
*HMK 124*:  (1) Bir davada taraf değişikliği, ancak karşı tarafın açık rızası
ile mümkündür.

(2) Bu konuda kanunlarda yer alan özel hükümler saklıdır.

(3) Ancak, maddi bir hatadan kaynaklanan veya dürüstlük kuralına aykırı olmayan
taraf değişikliği talebi, karşı tarafın rızası aranmaksızın hâkim tarafından
kabul edilir.
====
+
Dava dilekçesi, ıslahla revize edilebilse de ıslah tarafa tesir etmez.
+
Dava dilekçesinin içinde yer alan vakalar, davalı olarak belirlenmiş kişinin
esasen o davada davalı olmaması gerektiğini ortaya koyabilecek nitelikte ise
hakim HMK 124/3 uyarınca davacının yapmış olduğu talebi kabul edip tarafı
değiştirebilir. Ancak özensizlik, dikkatsizlik, bilgisizlik ve yanılma gibi
sebeplerle davalı farklı konumlandırılmışsa HMK 124/3'ten yararlanılamaz.
+
Bununla birlikte Yargıtay hata, yanılma gibi hallerde dahi HMK 124/3'ten
yararlanılabileceğini kabul etmektedir. _Kürsü bu görüşe iştirak etmemektedir_.

* Dava açıldıktan sonra ölüm varsa, gerçek kişiler açısından özel olarak HMK 55
düzenlenmiştir.
+
[caption=""]
.Dava sırasında taraflardan birinin ölümü
====
*HMK 55*: (1) Taraflardan birinin ölümü hâlinde, mirasçılar mirası kabul veya
reddetmemişse, bu hususta kanunla belirlenen süreler geçinceye kadar dava
ertelenir. Bununla beraber hâkim, gecikmesinde sakınca bulunan hâllerde, talep
üzerine davayı takip için kayyım atanmasına karar verebilir.
====
+
Derdest davada taraflardan biri öldüyse bu dava üç ay için uzayacaktır. Çünkü
reddedilip reddedilmeyeceği o üç aylık hak düşürücü süreye tabidir. Üç ay
içerisinde mirasın reddine ilişkin bir dava açılmamışsa HMK 55 gereğince
mirasçılar davanın tarafı yerine ikame olunur. Tüm mirasçılar mecburi dava
arkadaşı olurlar.
+
Üç ayın başlangıcı mirasçılardan birinin beyanına tabidir. Bu öğrenme beyanı
her türlü delille ispat edilebilir bir husustur.
+
Şahsa sıkı sıkıya bağlı bir haktan kaynaklanan davada tarafın ölümü halinde
yargılama sona erer. MK 606 ve 607 devreye girmez. 

* Yargıtay kararlarına ve doktrine göre adi şirket bir davada taraf olarak yer
alamaz. Dolayısıyla adi şirketin borçlu ya da alacaklı olması söz konusuysa ve
bu bir dava vasıtasıyla talep edilecekse mutlaka adi şirketi oluşturan
ortakların davada taraf olarak bir arada bulunmaları gerekir. Mecburi dava
arkadaşlığı rejimine tabidirler.

* TTK 445, 446 ve 448'de bir anonim şirketinde alınmış kararı kim, hangi süre
içerisinde ne şekilde iptal ettirebilir ve kimin davacı olabileceği
düzenlenmektedir.
+
[caption=""]
.İptal sebepleri
====
*TTK 445*: (1) 446 ncı maddede belirtilen kişiler, kanun veya esas sözleşme
hükümlerine ve özellikle dürüstlük kuralına aykırı olan genel kurul kararları
aleyhine, karar tarihinden itibaren üç ay içinde, şirket merkezinin bulunduğu
yerdeki asliye ticaret mahkemesinde iptal davası açabilirler.
====
+
[caption=""]
.İptal davası açabilecek kişiler
====
*TTK 446*: 

.. Toplantıda hazır bulunup da karara olumsuz oy veren ve bu muhalefetini
tutanağa geçirten,
.. Toplantıda hazır bulunsun veya bulunmasın, olumsuz oy kullanmış olsun ya da
olmasın; çağrının usulüne göre yapılmadığını, gündemin gereği gibi ilan
edilmediğini, genel kurula katılma yetkisi bulunmayan kişilerin veya
temsilcilerinin toplantıya katılıp oy kullandıklarını, genel kurula katılmasına
ve oy kullanmasına haksız olarak izin verilmediğini ve yukarıda sayılan
aykırılıkların genel kurul kararının alınmasında etkili olduğunu ileri süren
pay sahipleri,
.. Yönetim kurulu,
.. Kararların yerine getirilmesi, kişisel sorumluluğuna sebep olacaksa yönetim
kurulu üyelerinden her biri, iptal davası açabilir.
====
+
[caption=""]
.İlan, teminat ve kanun yolu
====
*TTK 448*: (1) Yönetim kurulu iptal veya butlan davasının açıldığını ve duruşma
gününü usulüne uygun olarak ilan eder ve şirketin internet sitesine koyar.

(2) İptal davasında üç aylık hak düşüren sürenin sona ermesinden önce duruşmaya
başlanamaz. Birden fazla iptal davası açıldığı takdirde davalar birleştirilerek
görülür.

(3) Mahkeme, şirketin istemi üzerine muhtemel zararlarına karşı davacıların
teminat göstermesine karar verebilir. Teminatın nitelik ve miktarını mahkeme
belirler.
====
+
Kural olarak davanın tarafları farklı olmalıdır. Bir kişi kendisine dava
açamaz.
+
TTK 445, 446 ve 448 ile anonim şirketin yönetim kurulu yine aynı anonim
şirketin genel kurulunun almış olduğu karara karşı iptal davası açabilecektir.
Dolayısıyla aynı tüzel kişinin iki organın davacı ve davalı olarak taraf olması
söz konusudur.
+
Buradaki taraf kavramı HMK 50 uyarınca taraf ehliyetinden değil HMK 53 uyarınca
dava takip yetkisinden faydalanarak izah edilir.
+
[caption=""]
.Dava takip yetkisi
====
*HMK 53*: (1) Dava takip yetkisi, talep sonucu hakkında hüküm alabilme
yetkisidir. Bu yetki, kanunda belirtilen istisnai durumlar dışında, maddi
hukuktaki tasarruf yetkisine göre tayin edilir.
====
+
Dava takip yetkisi ihtilaf konusu olan maddi hukuk ilişkisinin esasen tarafı
olmayan bir üçüncü kişiye davayı ikame etme imkanı tanır. 
+
WARNING: Aynı tüzel kişinin iki şubesi birbirine karşı dava açamaz. Bu ayniyet
hususunun çiğnenmesi anlamına gelir.

* Ölmüş kişiye dava açılamamasının istisnaları:

. Kadastro mahkemelerinde ölmüş kişilere karşı özellikle tespit davaları
açılabilir.
. Ortaklığın giderilmesi davası açılabilir.

+
Bu iki istisna haricinde, ölmüş kişiye karşı açılmış dava görülmüş ve
neticelenmiş olsa dahi verilmiş hüküm mirasçılara tesir etmez, yok hükmündedir.

* Tüzel kişilik kazanılmadan yargılamaya dair gerçekleştirilmiş işlemler
askıdadır. Tüzel kişilik kazanıldıktan sonra eğer icazet verilirse ilgil usuli
işlemler sıhhat kazanır.

* HMK 51'de dava ehliyetini düzenlemektedir. *Dava ehliyeti*, medeni hakları
kullanma ehliyetine, yani fiil ehliyetine göre belirlenir. Fiil ehliyeti
bakımından gerçek kişiler için MK 9, tüzel kişiler için MK 49 geçerlidir.
+
Dava ehliyeti de dava şartlarından birisidir. Taraf ehliyeti ve dava
ehliyetinden birisi yoksa davanın usulden reddi gerekir.

* MK 407'de hem taraf ehliyetine hem de dava ehliyetin sahip olmasına
rağmen davada taraf olamayacak bir gerçek kişi düzenlenmiştir.
+
[caption=""]
.Özgürlüğü bağlayıcı ceza
====
*MK 407*: (1) Bir yıl veya daha uzun süreli özgürlüğü bağlayıcı bir cezaya
mahkûm olan her ergin kısıtlanır.

(2) Cezayı yerine getirmekle görevli makam, böyle bir hükümlünün cezasını
çekmeye başladığını, kendisine vasi atanmak üzere hemen yetkili vesayet
makamına bildirmekle yükümlüdür.
====

* HMK 52 uyarınca fiil ehliyeti olmayanlar kanuni temsilcileri tarafından tüzel
kişiler de organları tarafından temsil edilecektir.
+
[caption=""]
.Davada kanuni temsil
====
*HMK 52*: (1) Medenî hakları kullanma ehliyetine sahip olmayanlar davada kanuni
temsilcileri, tüzel kişiler ise yetkili organları tarafından temsil edilir.
====
+
Kanuni temsilci, bu niteliğe haiz olduğunu ispat eden belgeleri sunmadan hiçbir
işlem yapamayacaktır.

* *Davacı sıfatı*, dava konusu hakkın sahibi kim onu belirtmektedir. *Davalı
sıfatı* ise dava konusu hakkın yükümlüsü kim onu belirtir. Sıfat, maddi
hukuktan kaynaklanan ihtilafla ilgili o ihtilafın maddi hukuk ilişkisi ile
bağlantının bulunup bulunmamasına ilişkin bir husustur. Sıfatın tespiti ancak
hüküm ile beraber mümkün olur. Bundan dolayı sıfat bir dava şartı değildir.
+
Sıfata muhalefet, davacı olmak değil davacının alacaklı olmasıdır. Buna ilişkin
muhalefet usule ilişkin bir muhalefet çerçevesinde gerçekleştirilemeyeceği için
esasa ilişkin muhalefet kapsamında, savunma kapsamında değerlendirilir. Yani
esasa ilişkin, maddi hukuka dair itiraz ya da itirazlar vasıtasıyla sıfata
muhalefet edilebilecektir. Ayrıca bu esasa ilişkin bir itiraz olması
dolayısıyla yargılamayı yürüten hakim tarafından re'sen gözönüne alınacak bir
durumdur.
+
Taraf ve dava ehliyetinin yokluğu sebebiyle dava reddilmişse bu ret kararı usule
ilişkin bir karardır, nihai karardır. Bu durumda maktu vekalet ücretine ve ona
göre bir yargılama giderine hükmedilmesi gerekir.
+
Sıfatın olmadığından bir ret varsa bu esasa ilişkin bir karardır. Esasa ilişkin
karar olduğundan nisbi vekalet ücreti söz konusu olur.
+
Sıfata ilişkin doktrinde ve Yargıtay kararlarında kullanılan iki kavram *aktif
husumet ehliyeti* ve *pasif husumet ehliyetidir*. Davacı tarafta aktif husumet
ehliyeti olmalı, davalı tarafta da pasif husumet ehliyeti olmalıdır. 
+
Sıfat yokluğundan dolayı davanın reddedilebilmesi için davanın taraflarının bu
duruma dair itirazlarını sunması gerekir. Bu esasa ilişkin bir savunma
sebebidir. Hakimin durumu re'sen gözönüne alabilmesi için dosyanın kapsamından
anlaşılabiliyor olması gerekir.
+
[caption=""]
.Dürüstlük kuralına aykırılık sebebiyle yargılama giderlerinden sorumluluk
====
*HMK 327/2*: Bir kişi davada sıfatı olmadığı hâlde, davacıyı, davalı sıfatı
kendisine aitmiş gibi yanıltıp, kendisine karşı dava açılmasına sebebiyet
verirse, davanın sıfat yokluğu nedeniyle reddi hâlinde, davalı yararına
yargılama giderlerine hükmedilemez.
====
+
[NOTE]
====
....

   (A)                           (B)
ALACAKLI   +--------------->   BORÇLU

    +
    |
    |
    +------------>    (C)
                     TEMLİK
                     ALACAKLISI

....

A, alacağını C'ye temlik etmesine rağmen B'ye karşı alacak davası açmıştır.
B'nin, A ile C arasındaki işlemden haberi yoktur. Dava A lehine
neticelenmiştir. C bundan etkilenir mi?

****
*TBK 186*: Borçlu, alacağın devredildiği, devreden veya devralan tarafından
kendisine bildirilmemişse, önceki alacaklıya; alacak birkaç kez devredilmişse,
son devralan yerine önceki devralanlardan birine iyiniyetle ifada bulunarak
borcundan kurtulur.
****

Burada dava ve taraf ehliyeti olmasına rağmen sıfat yoktur. Bu dava görünüşte
geçerli bir davadır. Bu temlik dosyaya yansımışsa yargılamada gözönüne alınır,
yansımamışsa yargılama neticelenir.

A ile B arasında sonuçlanan dava kesin hükümdür. İlamlı icra neticesinde B,
A'ya ödeme yaparsa C'nin istikbalde kendisine karşı açtığı davada TBK 186'dan
yararlanabilir. C artık davayı A'ya karşı açmak zorunda kalacaktır. Ödeme
yapılmazsa C, B'ye karşı açtığı davada bu hükmü delil olarak kullanabilir. 
====

<<<

=== DAVA ARKADAŞLIĞI

* HMK 57, *ihtiyari dava arkadaşlığı* için üç halden bahsetmektedir. Bu üç
sebep haricinde bu rejimi tespit etmeye yarayan bir kriter yoktur. Yargıtay
tarafından da doktrinde tarafından da kabul edildiği üzere bu üç sebebi
genişletme imkanı yoktur.
+
[caption=""]
.İhtiyari dava arkadaşlığı
====
*HMK 57*: (1) Birden çok kişi, aşağıdaki hâllerde birlikte dava açabilecekleri
gibi aleyhlerine de birlikte dava açılabilir:

.. Davacılar veya davalılar arasında dava konusu olan hak veya borcun,
elbirliği ile mülkiyet dışındaki bir sebeple ortak olması.
.. Ortak bir işlemle hepsinin yararına bir hak doğmuş olması veya kendilerinin
bu şekilde yükümlülük altına girmeleri.
.. Davaların temelini oluşturan vakıaların ve hukuki sebeplerin aynı veya
birbirine benzer olması.
====
+
CAUTION: HMK 57'nin (c) bendinde yer alan "_vakıaların ve hukuki sebeplerin_"
ifadesindeki "_ve_" bağlacı _kürsüye_ ve Yargıtay'a göre yanlıştır, "_veya_"
olması gerekir. İkisinin birden bulunması değil, vakıaların benzeşmesi ya da
hukuki sebeplerin benzeşmesi, ihtiyari dava arkadaşlığının kurulabilmesi için
yeterlidir.
+
İhtiyari dava arkadaşlığının sonuçları HMK 58'de düzenlenmiştir.
+
[caption=""]
.İhtiyari dava arkadaşlarının davadaki durumu
====
*HMK 58*: (1) İhtiyari dava arkadaşlığında, davalar birbirinden bağımsızdır.
Dava arkadaşlarından her biri, diğerinden bağımsız olarak hareket eder.
====
+
....

                 +----------> DAVALI (D) +-----+
                 |  DAVA 1                     |
                 |                             |    İHTİYARİ
DAVACI (A) +----------------> DAVALI (E)       +->    DAVA
                 |  DAVA 2                     |   ARKADAŞLIĞI
                 |                             |
                 +----------> DAVALI (F) +-----+
                    DAVA 3
....
+
İhtiyari dava arkadaşlığında davalı ya da davacı sayısınca dava vardır. Buna
*davaların istiklali* prensibi denilmektedir. Dolayısıyla ihtiyari dava
arkadaşları birbirlerinin davalarına fer'i müdahil ya da asli müdahil olabilir.
Her bir davalı açısından verilecek karar birbirinden farklı olabilir. Her
birinin kanun yoluna müracaatı birbirinden farklı tarihlerde olabilir. Her biri
kanun yolu neticesinde farklı sonuçlarla karşılaşabilir.
+
Davacı her bir davalı için farklı sorumluluk halleri olduğunu tek bir dava
dilekçesinde belirtecek ve aynı mahkemede birden fazla dava açılmış olacaktır.
+
TBK 163 ve 169, HMK 57'nin (a) bendine örnek teşkil eder.
+
[caption=""]
.Borçluların sorumluluğu
====
*TBK 163*: (1) Alacaklı, borcun tamamının veya bir kısmının ifasını, dilerse
borçluların hepsinden, dilerse yalnız birinden isteyebilir.

(2) Borçluların sorumluluğu, borcun tamamı ödeninceye kadar devam eder.
====
+
[caption=""]
.Müteselsil alacaklılık
====
*TBK 169*: (1) Müteselsil alacaklılık, borçlunun, alacaklılardan her birine
borcun tamamını isteme hakkını tanıdığı veya kanunun belirlediği durumlarda
doğar.

(2) Borçlu, alacaklılardan birine yaptığı ifayla, bütün alacaklılara karşı
borcundan kurtulmuş olur.

(3) Alacaklılardan birinin icraya veya mahkemeye başvurmuş olduğu kendisine
bildirilmedikçe, borçlu onlardan dilediği birine ifada bulunabilir.

(4) Aksi kararlaştırılmadıkça veya alacaklılar arasındaki hukuki ilişkinin
niteliğinden anlaşılmadıkça, alacaklılardan her birinin edim üzerindeki hakları
eşittir.

(5) Kendisine düşen paydan fazlasını elde eden alacaklı, bu fazlalığı payını
alamamış olan diğer alacaklılara ödemekle yükümlüdür.
====
+
CAUTION: Hakim ihtiyari dava arkadaşlığı ya da mecburi dava arkadaşlığı
rejiminin bulunması gerektiğine kanaat getirirse bu konuda bir ara karar
verebilir. Sebebe istinaden bir gerekçe belirtirse *ihsas-ı rey* söz konusu
olur ve hakimin reddine sebebiyet verir.
+
[NOTE]
====

....

   (A)                           (B)
ALACAKLI   +--------------->   BORÇLU

    +
    |
    |
    +------------>    (C)
                     TEMLİK
                     ALACAKLISI

....

A, B'ye 100.000 TL'lik alacak davası açmış ve davanın görüldüğü sırada da
alacağını C'ye temlik etmiştir. Bu durumda HMK 125/2 uyarınca C, davada A'nın
yerine geçer ve dava kaldığı yerden devam eder. 

****
*HMK 125/2*: Davanın açılmasından sonra, dava konusu davacı tarafından
devredilecek olursa, devralmış olan kişi, görülmekte olan davada davacı yerine
geçer ve dava kaldığı yerden itibaren devam eder.
****

A, alacağın 50.000 TL'sini C'ye temlik etmiş ise HMK 125/2 uyarınca ihtiyari
dava arkadaşlığı söz konusu olacaktır.

Bu durumda davalı B'nin savunma alanı genişler. C'nin kendisi aleyhine bir
karar almasını engellemek için temlik sözleşmesinin geçersiz olduğu ileri
sürebilir. Bunu dilekçeler teatisi geçtikten sonra dahi yapabilir.
====
+
Ortaklar, üçüncü kişilere karşı borçlarından müteselsilen sorumludurlar. Bu
durumda da ihtiyari dava arkadaşlığı vardır.
+
[caption=""]
====
*TBK 638/3*: Ortaklar, birlikte veya bir temsilci aracılığı ile, bir üçüncü
kişiye karşı, ortaklık ilişkisi çerçevesinde üstlendikleri borçlardan, aksi
kararlaştırılmamışsa müteselsilen sorumlu olurlar.
====
+
Mirasçılar tereke borçlarından müteselsilen sorumludurlar. Bu durumda da
ihtiyari dava arkadaşlığı vardır.
+
[caption=""]
.Mirasçıların sorumluluğu
====
*MK 641*: Mirasçılar, tereke borçlarından müteselsilen sorumludurlar.
====
+
TIP: Borç bölünebilen nitelikte ise ihtiyarı, bölünemeyen nitelikte ise zaruri
dava arkadaşlığı söz konusudur.
+
HMK 57'nin (b) bendine örnek:
+
....

   A ve B      KİRA SÖZLEŞMESİ      C
             +----------------->
Kiraya veren                      Kiracı

....
+
C'nin kiraya verene karşı açacağı herhangi bir davada A ile B arasında zaruri
dava arkadaşlığı söz konusu olacaktır.
+
....


      A        KİRA SÖZLEŞMESİ    C ve D
             +----------------->
Kiraya veren                      Kiracı

....
+
Kira bedeli, bölünebilen nitelikte bir borç olduğundan kiracıya karşı açılacak
davada C ve D ihtiyari dava arkadaşları olacaktır.
+
MK 364, HMK 57'nin (c) bendine bir örnektir.
+
[caption=""]
.Nafaka yükümlüleri
====
*MK 364*: (1) Herkes, yardım etmediği takdirde yoksulluğa düşecek olan üstsoyu
ve altsoyu ile kardeşlerine nafaka vermekle yükümlüdür.

(2) Kardeşlerin nafaka yükümlülükleri, refah içinde bulunmalarına bağlıdır.

(3) Eş ile ana ve babanın bakım borçlarına ilişkin hükümler saklıdır.
====
+
HMK 57'ye uyulmadan birden fazla kişiye davalı gösterilerek dava açılmışsa,
hakimin vermesi gereken karar *tefrik kararıdır*. Tefrik kararı ile
davalılardan birine karşı açılmış olan dava devam eder. İkinci davanın tefrik
kararında gösterilmiş yer mahkemesinde devamı için davacının süresi işlemeye
başlar.
+
İhtiyari dava arkadaşlığında ortak yetkili ve ortak görevli mahkemenin nasıl
belirleneceği konusunda Yargıtay'ın kullandığı bazı kriterler vardır. İhtiyari
dava arkadaşlığına dair hükümlere riayet edilerek dava açılmışsa eğer ikisi de
genel mahkeme ise tefrik kararı verilmemelidir. Biri genel mahkeme biri özel
mahkeme ise Yargıtay davanın özel mahkemede görüleceğini söylemektedir.
_Kürsüye göre_ ise tefrik kararı verilmelidir.

* HMK 59'da *mecburi dava arkadaşlığı* düzenlenmiştir. Mecburi dava
arkadaşlarının birlikte dava açma mecburiyetleri, aleyhlerine birlikte dava
açılması zorunluluğu, yargılama esnasında birlikte hareket etme zorunlulukları
mecburi dava arkadaşlığını ihtiyari dava arkadaşlığından ayıran özelliklerdir.
+
[caption=""]
.Mecburi dava arkadaşlığı
====
*HMK 59*: (1) Maddi hukuka göre, bir hakkın birden fazla kimse tarafından
birlikte kullanılması veya birden fazla kimseye karşı birlikte ileri sürülmesi
ve tamamı hakkında tek hüküm verilmesi gereken hâllerde, mecburi dava
arkadaşlığı vardır.
====
+
Zaruri dava arkadaşlığının tespiti ile ihtiyari dava arkadaşlığının tespiti
arasında bir fark yoktur. Esas fark HMK 58 ile HMK 60 arasındadır.
+
[caption=""]
.Mecburi dava arkadaşlarının davadaki durumu
====
*HMK 60*: (1) Mecburi dava arkadaşları, ancak birlikte dava açabilir veya
aleyhlerine de birlikte dava açılabilir. Bu tür dava arkadaşlığında, dava
arkadaşları birlikte hareket etmek zorundadır. Ancak, duruşmaya gelmiş olan
dava arkadaşlarının yapmış oldukları usul işlemleri, usulüne uygun olarak davet
edildiği hâlde duruşmaya gelmemiş olan dava arkadaşları bakımından da hüküm
ifade eder.
====
+
HMK 60'a göre davaların istiklali prensibi bulunmamaktadır. Burada her bir
davacı ya da davalı kadar dava yoktur, dava tektir. Dava sonucunda hepsi için
tek hüküm verilecek, gidilebiliyorsa kanun yoluna hep birlikte gidilecektir.
+
Elbirliği mülkiyetine tabi bir mülkiyet varsa bu mülkiyete tabi malla ilgili
açılacak davada malikler aktif tarafta bulunacaklarsa birlikte dava dilekçesi
düzenlenmeli, aleyhlerine dava açılacaksa her biri davalı olarak
gösterilmelidir. Eğer bunlardan biri dahi eksikse davanın akıbeti için hakim
HMK 119/2 uyarınca kesin bir süre verecek ve bu süre içerisinde eksiklik
giderilmezse dava dava şartının eksikliği sebebiyle usulden reddedilecektir.
+
Zaruri dava arkadaşları hepsinin iradesini temsil edecek bir temsilci
atayabilirler. 
+
Usulüne uygun olarak davet edildiği halde duruşmaya gelmemiş olan dava
arkadaşları bakımından duruşmada yapılan işlemler hüküm ifade eder. _Kürsü_
aksi görüştedir. Dolayısıyla duruşmalara gelmeyerek yargılamanın devamını
engelleyici nitelikte, içtinap suretiyle bir tasarrufta bulunulması engellenmiş
olmaktadır.
+
Adi kefalet halinde de zaruri dava arkadaşlığı söz konusu olacaktır.
+
Mirasçıların açacağı davalarda ya da mirasçılara karşı açılacak davalarda
zaruri dava arkadaşlığı söz konusudur. Ancak Yargıtay'a göre mirasçıların
birbirlerine karşı açacakları davalarda mecburi dava arkadaşlığı söz konusu
olmayacaktır.
+
Paylı mülkiyette ortaklığın giderilmesi davasında davayı açan paydaşın
karşısındaki diğer paydaşlar için zaruri dava arkadaşlığı söz konusudur.
+
Elbirliği mülkiyeti kural olarak zaruri dava arkadaşlığına götürür. Ancak MK
702/4 acil durumda koruma amaçlı olarak tek bir malikin dahi dava
açacabileceğini düzenler. Bu davanın sonuçları diğer maliklere haberleri olsun
ya da olmasın tesir eder.
+
TIP: Elbirliği mülkiyetine tabi bir gayrimenkulü maliklerden biri kiralamışsa,
kira sözleşmesine bir aykırılık halinde kiracıya karşı açacağı davada mecburi
dava arkadaşlığı söz konusu olmayacaktır. Keza kiracının açacağı davada da dava
sadece kiraya veren malike karşı açılacaktır.
+
Tasarrufun iptali davasında da borçlu ile üçüncü kişi arasında mecburi dava
arkadaşlığı vardır.
+
Soybağının reddi davasında anne ile çocuk arasında mecburi dava arkadaşlığı
vardır.

<<<

=== DAVAYA MÜDAHALE

* Kural olarak davanın tarafları davacı ve davalıdır. Yargılamada üçüncü bir
taraf yoktur ve yargılama sonunda sadece bu iki taraf hakkında karar verilir.
Ancak bazı hallerde davanın sonunda verilen kararın üçüncü kişilere etki
edebilmesi söz konusudur. Bu gibi hallerde dava sonunda verilecek olan hükümden
etkilenecek üçüncü kişi kendi yararını korumak için davaya müdahil olabilir.
+
Dava dışındaki üçüncü kişinin davaya katılması iki şekilde olabilir:

. Fer'i müdahale
. Asli müdahale

* Taraflardan biri dava sonunda verilen hükümle zarar görecek ve bu zararın
tazmini için üçüncü kişiye rücu edebilecekse bu rücu talebiyle karşı karşıya
kalma ihtimali olan üçüncü kişi davaya *fer'i müdahil* olarak katılıp rücu
imkanı olan tarafın yanında yer alır ve onun kazanması için çalışır. Zira bu
durumda hukuki menfaati vardır.
+
[caption=""]
.İhbar ve şartları
====
*HMK 61*: (1) Taraflardan biri davayı kaybettiği takdirde, üçüncü kişiye veya
üçüncü kişinin kendisine rücu edeceğini düşünüyorsa, tahkikat sonuçlanıncaya
kadar davayı üçüncü kişiye ihbar edebilir.

(2) Dava kendisine ihbar edilen kişinin de aynı şartlarda bir başkasına ihbarda
bulunması mümkündür ve bu şekilde ihbar tevali ettirilebilir.
====
+
[caption=""]
.İhbarın şekli
====
*HMK 62*: (1) İhbar yazılı olarak yapılır; ihbar sebebinin gerekçeleriyle
birlikte açıklanması ve yargılamanın hangi aşamada bulunduğunun belirtilmesi
gerekir.

(2) Davanın ihbarı sebebiyle yargılama bir başka güne bırakılamaz ve ihbarın
tevali etmesi gibi zorunlu olan durumlar dışında süre verilemez.
====
+
[caption=""]
.İhbarda bulunulan kişinin durumu
====
*HMK 63*: (1) Dava kendisine ihbar edilen kişi, davayı kazanmasında hukuki
yararı olan taraf yanında davaya katılabilir.
====
+
Dava kendisine ihbar edilen kişi, *davayı kazanmasında hukuki yararı olan
taraf* yanında yer alabilir. Dolayısıyla, kim ihbar ediyorsa onun yanında
katılmak zorunluluğu yoktur. Yani ihbar edilen kişi, kendisine davayı ihbar
edenin karşı tarafının yanında da davaya katılabilir. Önemli olan kendi hukuki
yararını gözetmesidir.
+
[caption=""]
.İhbarın etkisi
====
*HMK 64*: (1) İhbar edilen davada verilen hükmün ihbar eden kişiye etkisi
hakkında 69 uncu maddenin ikinci fıkrası hükmü kıyasen uygulanır.
====
+
[caption=""]
.Fer’î müdahale
====
*HMK 66*: (1) Üçüncü kişi, davayı kazanmasında hukuki yararı bulunan taraf
yanında ve ona yardımcı olmak amacıyla, tahkikat sona erinceye kadar, fer’î
müdahil olarak davada yer alabilir.
====
+
[caption=""]
.Fer’î müdahale talebi ve incelenmesi
====
*HMK 67*: (1) Müdahale talebinde bulunan üçüncü kişi, yanında katılmak istediği
tarafı, müdahale sebebini ve bunun dayanaklarını belirten bir dilekçeyle
mahkemeye başvurur.

(2) Müdahale dilekçesi, davanın taraflarına tebliğ edilir. Mahkeme, gerekirse
taraflarla birlikte üçüncü kişiyi de dinlemek üzere davet eder, gelmeseler
dahi müdahale talebi hakkında karar verir.
====
+
[caption=""]
.Fer’î müdahilin durumu
====
*HMK 68*: (1) Müdahale talebinin kabulü hâlinde müdahil, davayı ancak bulunduğu
noktadan itibaren takip edebilir. Müdahil, yanında katıldığı tarafın yararına
olan iddia veya savunma vasıtalarını ileri sürebilir; onun işlem ve
açıklamalarına aykırı olmayan her türlü usul işlemlerini yapabilir.

(2) Mahkeme, katıldığı noktadan itibaren, taraflara bildirilen işlemleri
müdahile de tebliğ eder. 
====
+
Fer'i müdahil yanında katıldığı kişi aleyhine işlem yapamaz. Fer'i müdahilin
yaptığı bir işleme yanında katıldığı kişi itiraz ederse, işlem geçersiz olur.
+
Fer'i müdahilin katıldığı andan itibaren taraflara bildirilecek her işlem fer'i
müdahile de tebliğ edilmezse, müdahilin hukuki dinlenilme hakkı ihlal edilmiş
olur.
+
[caption=""]
.Fer’î müdahalenin etkisi
====
*HMK 69*: (1) Müdahilin de yer aldığı asıl davada hüküm, taraflar hakkında
verilir.

(2) Fer’î müdahilin, tarafla rücu ilişkisinde, asıl davadaki uyuşmazlık
hakkında yanlış karar verildiği iddiası dinlenilmez.  Ancak, müdahil, zamanında
ihbar yapılmadığı için davaya geç katıldığını veya yanında katıldığı tarafın
iddia ve savunma imkânlarını kullanmasını engellediğini ya da kendisince
bilinmeyen iddia ve savunma imkânlarının, tarafın ağır kusuru sebebiyle
kullanılamadığını belirterek, yanında katıldığı tarafın yargılamayı hatalı
yürüttüğünü ileri sürebilir.
====
+
Mahkeme, fer'i müdahil hakkında bir hüküm tesis edemez. Çünkü fer'i müdahil
davanın tarafı değildir. Ancak hakim, es kaza böyle bir karar vermişse, fer'i
müdahil bu karara karşı kanun yoluna başvurabilir.

* Bir yargılamanın konusu olan hak veya şey üzerinde hak iddia eden üçüncü
kişi, davaya *asli müdahil* olarak katılabilir.
+
[caption=""]
.Asli müdahale
====
*HMK 66*: (1) Bir yargılamanın konusu olan hak veya şey üzerinde kısmen ya da
tamamen hak iddia eden üçüncü kişi, hüküm verilinceye kadar bu durumu ileri
sürerek, yargılamanın taraflarına karşı aynı mahkemede dava açabilir.

(2) Asli müdahale davası ile asıl yargılama birlikte yürütülür ve karara
bağlanır.
====
+
Fer'i müdahalede, davanın sonucundan etkilenecek bir kişi vardır ve bu kişi o
davada bir tarafın yardımcısı olarak ortaya çıkmaktadır.
+
Asli müdahalede ise, bir kişi direkt olarak dava konusu hak veya şey üzerinde
bir iddia ile ortaya çıkmaktadır. Asli müdahil, aynı mahkemede asıl
yargılamanın taraflarını davalı olarak göstererek dava açar ve iki dava
birlikte yürütülür. Bu durumda davalı taraflar arasında *mecburi dava
arkadaşlığı* vardır. Buradaki şekli mecburi dava arkadaşlığıdır.
+
NOTE: Çekişmesiz yargıda fer'i müdahale olmaz ancak asli müdahale olabilir.
Asli müdahale, çekişmesiz yargıyı çekişmeli hale getirir.
+
Asli müdahilin davası ayrı ve bağımsız bir davadır. Dolayısıyla yargılama
giderleri asli müdahil tarafından ödenir. 
+
TIP: Asli müdahale talebi yapılması zorunlu olan bir şey değildir. Asli
müdahale yerine, görevli ve yetkili bir mahkemede dava da açılabilir. Bu
durumda ilk derece mahkemesi, iki ayrı dava olduğu için yargılamayı birlikte
yürütecek ve bir karara varacaktır. Ama bu birlikte yürütme bakımından
tahkikatın ortak olmasına gerek yoktur. Önce birisine bakılıp karar verildikten
sonra diğeri incelenir ve sonuçta iki dava için ayrı ayrı hüküm verir.
+
Fer'i müdahale, tahkikatın sonuna kadar; asli müdahale ise, hüküm verilene
kadar yapılabilir.

* Bazı hallerde davanın ihbarı zorunludur. Örneğin HMK 48'te hakimin hukuki
sorumluluğuna ilişkin devlete karşı açılan tazminat davasında, davanın hakime
ihbarı zorunluluğu getirilmiştir. 

* Davanın ihbarının yazılı yapılması gerekir. Bu bakımdan mahkeme kanalı ile ya
da haricen ihbar yapılması önemli değildir. 

* İhbarda, ihbarın gerekçesi ve yargının hangi aşamada olduğu belirtilmelidir.

* *İhbarın tevali*, ihbar edenin ihbar edilmesidir. Özellikle kambiyo
ilişkisinde söz konusu olur. Cirantaya yapılan ihbar, ciranta tarafından kendi
cirantasına yapılır. Normalde sadece ihbar söz konusu oldu diye duruşma
ertelenmez. Ancak ihbarın tevali söz konusu olması halinde, hakim yargılamanın
ertelenmesine karar verebilir.

<<<

=== DAVALARIN BİRLEŞTİRİLMESİ VE AYRILMASI

* Aralarında bağlantı bulunan davalar *birleştirilebilir*.
+
[caption=""]
.Davaların birleştirilmesi
====
*HMK 166*: (1) Aynı yargı çevresinde yer alan aynı düzey ve sıfattaki hukuk
mahkemelerinde açılmış davalar, aralarında bağlantı bulunması durumunda,
davanın her aşamasında, talep üzerine veya kendiliğinden ilk davanın açıldığı
mahkemede birleştirilebilir. Birleştirme kararı, ikinci davanın açıldığı
mahkemece verilir ve bu karar, diğer mahkemeyi bağlar.

(2) Davalar, ayrı yargı çevrelerinde yer alan aynı düzey ve sıfattaki hukuk
mahkemelerinde açılmış ise bağlantı sebebiyle birleştirme ikinci davanın
açıldığı mahkemeden talep edilebilir. Birinci davanın açıldığı mahkeme, talebin
kabulü ile davaların birleştirilmesine ilişkin kararın kesinleşmesinden
itibaren, bununla bağlıdır.

(3) Birleştirme kararı, derhâl ilk davanın açıldığı mahkemeye bildirilir.

(4) Davaların aynı veya birbirine benzer sebeplerden doğması ya da biri
hakkında verilecek hükmün diğerini etkileyecek nitelikte bulunması durumunda,
bağlantı var sayılır.

(5) İstinaf incelemesi ayrı dairelerde yapılması gereken davaların da bu madde
hükmüne göre birleştirilmesine karar verilebilir.  Bu hâlde istinaf incelemesi,
birleştirilen davalarda uyuşmazlığı doğuran asıl hukuki ilişkiye ait kararı
inceleyen bölge adliye mahkemesi dairesinde yapılır.
====
+
HMK 166/4'e göre davaların birleştirilmesini gerektiren bağlantı; davaların
aynı veya benzer sebeplerden doğması ya da biri hakkında verilecek hükmün
diğeri etkileyecek olmasıdır.
+
Burada yine iki ayrı dava vardır ancak bu davalar birlikte yürütülmektedir.
+
CAUTION: Ancak *aynı* Bölge Adliye Mahkemesinin *farklı* Hukuk Daireleri
arasındaki davalar birleştirilebilir. Asıl hukuki ilişkiye ait kararı inceleyen
Hukuk Dairesi hangisi ise dosya orada birleştirilir.
+
Davaların birleştirilmesinin en tipik örneği ihtiyari dava ortaklığında ortaya
çıkar. Bu sebeple, ihtiyari dava ortaklığına ilişkin bir sebep varsa davalar
arasında bağlantı olduğu kabul edilir.
+
Birleştirme kararını, ikinci davanın açıldığı mahkeme verir. Eğer aynı yargı
çevresi ve aynı sıfattaki iki mahkeme söz konusuysa hakim bu kararı re'sen de
verebilir, talep üzerine de verebilir. İlk davanın açıldığı mahkeme bu karar
ile bağlıdır. Birleştirme kararına karşı ancak esas hükümle kanun yoluna
müracaat edilebilir.
+
NOTE: Esas hükümle birlikte birleştirme kararı kanun yoluna taşınsa bile, eğer
esasa ilişkin karar doğruysa sadece birleştirme kararının hatalı olması
dolayısıyla Bölge Adliye Mahkemesi tarafından kararın kaldırılması kararı
verilemez. Aynı şekilde Yargıtay da Bölge Adliye Mahkemesinin kararına karşı
bozma kararı veremez.
+
Mahkemeler farklı yargı çevresinde ise ancak talep üzerine birleştirme kararı
verilebilir. Bu talep yargılamanın sonuna kadar dilekçe ile veya yargılama
sırasında sözlü olarak tutanağa geçirilmek suretiyle yapılabilir. 
+
Farklı yargı çevresindeki bir mahkemede görülen davayı etkileyecek bir dava
varsa, taraflar bunu talep etmediği sürece hakim re'sen birleştirme kararı
veremez. Taraflar birleştirmeyi öneremez, önerirse bu bir hakimin reddi
sebebidir. Böyle bir davanın varlığına farkeden hakim, taraflar bunu talep
etmezse diğer mahkemenin kararını bekleyebilir. Bu durumda bir *bekletici
sorun* vardır.
+
Talep gerçekleşirse ikinci mahkeme, ilk mahkemeden dava hakkında bilgi alarak
aralarında bir bağlantı olup olmadığını inceler ve bağlantı olduğuna kanaat
getirirse birleştirme kararı verir.
+
CAUTION: Aynı yargı çevresi içindeki birleştirme kararından farklı olarak,
farklı yargı çevresindeki ikinci mahkemenin birleştirme kararı kesinleştiğinde
bu karara karşı kanun yoluna müracaat edilebilir. Zira ikinci mahkeme,
birleştirme kararını vermekle dosyadan el çekmiş olmaktadır.

* Aralarında bağlantı olsa dahi, davaların yürütülmesinde problem varsa
davaların *ayrılmasına* karar verilebilir. Hatta birleştirme kararı verilmiş
davalar bile ayrılabilir.
+
[caption=""]
.Davaların ayrılması
====
*HMK 167*: (1) Mahkeme, yargılamanın iyi bir şekilde yürütülmesini sağlamak
için, birlikte açılmış veya sonradan birleştirilmiş davaların ayrılmasına,
davanın her aşamasında, talep üzerine veya kendiliğinden karar verebilir. Bu
durumda mahkeme, ayrılmasına karar verilen davalara bakmaya devam eder.
====
+
Ayrılma kararı davanın sonuna kadar her aşamasında talep üzerine veya re'sen
verilebilir.
+
Ayrılma kararı ile birlikte davalar yine aynı mahkemede görülür.
+
Ayrılma kararı bir ara karardır ve dolayısıyla kanun yoluna ancak esas hükümle
birlikte başvurulabilir. Bu ayırma kararı hatalı olsa bile esasa ilişkin karar
doğruysa kaldırma kararı verilemez.

<<<

=== DAVA ŞARTLARI VE İLK İTİRAZLAR

* *Dava şartları*, usule ilişkin hükümlerdir. Dolayısıyla davanın her
aşamasında bulunması gerekir. Bu şartlardan birinin dahi olmaması, davanın
usule ilişkin kararla neticelenmesine neden olur. Yani bir *nihai karar* ile
dava reddedilir. Davanın başından sonuna kadar bu şartlar, dava dosyası
kapsamında tespit kabiliyetine sahip olmalıdır. Hakim bunu re'sen yargılamanın
her aşamasında gözönüne alır. Dolayısıyla dava şartları muhalefete binaen
incelenecek hallerden değil, hakimin vazifesidir.
+
WARNING: DAVA ŞARTLARI YARGILAMANIN HER AŞAMASINDA YER ALMALIDIR. DOLAYISIYLA
YARGILAMANIN HER AŞAMASINDA YARGILAMANIN TARAFLARI BAKIMINDAN İLERİ
SÜRÜLEBİLİR.
+
[caption=""]
.Dava şartları
====
*HMK 114*: (1) Dava şartları şunlardır:

.. Türk mahkemelerinin yargı hakkının bulunması.
.. Yargı yolunun caiz olması.
.. Mahkemenin görevli olması.
.. Yetkinin kesin olduğu hâllerde, mahkemenin yetkili bulunması.
.. Tarafların, taraf ve dava ehliyetine sahip olmaları; kanuni temsilin söz
konusu olduğu hâllerde, temsilcinin gerekli niteliğe sahip bulunması.
.. Dava takip yetkisine sahip olunması.
.. Vekil aracılığıyla takip edilen davalarda, vekilin davaya vekâlet ehliyetine
sahip olması ve usulüne uygun düzenlenmiş bir vekâletnamesinin bulunması.
.. Davacının yatırması gereken gider avansının yatırılmış olması.
.. Teminat gösterilmesine ilişkin kararın gereğinin yerine getirilmesi.
.. Davacının, dava açmakta hukuki yararının bulunması.
.. Aynı davanın, daha önceden açılmış ve hâlen görülmekte olmaması.
.. Aynı davanın, daha önceden kesin hükme bağlanmamış olması.

(2) Diğer kanunlarda yer alan dava şartlarına ilişkin hükümler saklıdır.
====
+
Doktrinde genel olarak kabul edilen sıralamaya göre; önce mahkemeye ilişkin
dava şartlarına, sonra tarafa ilişkin dava şartlarına, sonra da dava konusuna
ilişkin dava şartlarına bakılmalıdır.
+
[caption=""]
.Dava şartlarının incelenmesi
====
*HMK 115*: (1) Mahkeme, dava şartlarının mevcut olup olmadığını, davanın her
aşamasında kendiliğinden araştırır. Taraflar da dava şartı noksanlığını her
zaman ileri sürebilirler.

(2) Mahkeme, dava şartı noksanlığını tespit ederse davanın usulden reddine
karar verir. Ancak, dava şartı noksanlığının giderilmesi mümkün ise bunun
tamamlanması için kesin süre verir. Bu süre içinde dava şartı noksanlığı
giderilmemişse davayı dava şartı yokluğu sebebiyle usulden reddeder.

(3) Dava şartı noksanlığı, mahkemece, davanın esasına girilmesinden önce fark
edilmemiş, taraflarca ileri sürülmemiş ve fakat hüküm anında bu noksanlık
giderilmişse, başlangıçtaki dava şartı noksanlığından ötürü, dava usulden
reddedilemez.
====
+
Dava şartındaki eksiklik giderilebilecek nitelikteyse, yargılamayı yürüten
hakim davayı reddetmemeli ilgili dava şartını ihmal edecek olan dava tarafına
kesin bir süre vermelidir. Eğer bu kesin süre içinde dava şartı yerine
getirilmezse, dava usulden reddedilir. Ancak bu imkan mahkemeye ilişkin dava
şartlarının noksanlığında kullanılamaz. Zira buradaki eksiklik giderilebilecek
bir eksiklik değildir.
+
CAUTION: Dava şartlarını değiştirecek, bunları ortadan kaldıracak mahiyette
sözleşme yapılamaz. Yapılmışsa bu sözleşme hükümsüzdür.

* *İlk itirazlar*, davalı tarafından *cevap dilekçesinde* ileri sürülebilecek
usule ilişkin muhalefetlerdir.
+
====
*HMK 116*: (1) İlk itirazlar aşağıdakilerden ibarettir:

.. Kesin yetki kuralının bulunmadığı hâllerde yetki itirazı.
.. Uyuşmazlığın tahkim yoluyla çözümlenmesi gerektiği itirazı.
.. İş bölümü itirazı.
====
+
Kesin yetki kuralına aykırı bir yargılama faaliyeti yürütülmekteyse bu bir dava
şartı ihlalidir. Dolayısıyla bu hususa dair muhalefet, savunma, iddia davanın
her aşamasında ileri sürülebilir. Hakim de yargılamanın her aşamasında, bu
hususu gözönüne alıp davanın usulden reddine karar verebilir.
+
Kesin yetkinin bulunmadığı hallerde ise, yetkiye muhalefet sadece cevap
dilekçesi ile birlikte davalı tarafından yapılacaktır. Kesin yetki olmayan
hallerde yetkiye ilişkin itiraz cevap dilekçesi ile ileri sürülmemişse artık
yetkisiz mahkeme yetki kazanır. 
+
Mevcut ya da ileride söz konusu olabilecek bir ihtilafın çözümü için taraflar
tahkim anlaşması yapabilirler. Her ihtilaf tahkim anlaşmasına uygun değildir.
Tarafların üzerinde serbestçe tasarruf edebilecekleri ihtilaflar tahkim
sözleşmesine uygundur. Eğer tahkim anlaşmasının varlığına rağmen davacı, bir
dava dilekçesi ile dava ikame etmişse davalı, tahkim itirazını ilk itiraz
olarak ileri sürmek zorundadır. Sürmemişse, bundan sonra tahkim anlaşmasını
ileri süremez.
+
[WARNING]
====
Cevap dilekçesi, dava dilekçesinin davalıya tebliğinden itibaren *iki hafta
içinde* verilmelidir. Davalı cevap dilekçesini verdikten sonra daha süresi olsa
dahi ek bir dilekçe ile ilk itirazlarını ileri süremez.

Zira ilk itirazlar süreye değil, işleme tabi tutulmuştur ve bu işlem cevap
dilekçesidir. Cevap dilekçesi ile ileri sürülmeyen ilk itirazlar dikkate
alınmaz.
====
+
[caption=""]
.İleri sürülmesi ve incelenmesi
====
*HMK 117*: (1) İlk itirazların hepsi cevap dilekçesinde ileri sürülmek
zorundadır; aksi hâlde dinlenemez.

(2) İlk itirazlar, dava şartlarından sonra incelenir.

(3) İlk itirazlar, ön sorunlar gibi incelenir ve karara bağlanır.
====
+
İlk itirazlar ön sorun gibi incelenecektir. Ön sorun olarak incelenirken küçük
bir dava şeklinde incelenir. Dolayısıyla ilk itiraz diğer hasım tarafından
münakaşa konusu edilmişse yargılamayı yürüten hakim bu hususa ilişkin müstakil
bir duruşma düzenleyebilir. Bu duruşma kapsamında tarafları dinleyip, iddia ve
delillerini dosyaya intikal ettirebilir ve sonunda bir karar verir.

[NOTE]
====
Hakim dava şartlarını incelerken dosya kapsamı ile bağlı mıdır değil midir?
Hakim, eğer dava şartlarına ilişkin bir eksiklik tespit etmişse ama bu
eksikliği araştırma anlamında elindeki dosya yeterli değil ise, haricen belge
isteme ve delil toplama imkanına sahip midir?

Bazı yazarlara göre hakim dosyada delillendiremiyorsa, o zaman dava şartlarının
yokluğunu gözönüne almış olmasına rağmen delili bulunmadığından reddedilecektir
veya dava şartı varmış gibi devam edilecektir.

Bazı yazarlara göre ise, dava şartları kamu düzenindendir. Kamu düzenine
ilişkin bu eksikliğin giderilmesi bakımından kanun hakimin elini kısıtlayamaz,
sınırlayamaz. 

Yargıtay'ın her iki yönde de kararları vardır.
====

<<<

=== YARGILAMAYA HAKİM OLAN İLKELER

* HMK 24 vd. *yargılamaya hakim olan ilkeler* düzenlenmiştir. Her bir usuli
işlemin, her bir yargılama faaliyetinin bu ilkeler kapsamında gerçekleşmesi
zorunludur.

* Taraf yoksa hakim de yoktur. Hakim bir ihtilafın varlığını tespit edip,
durumdan vazife çıkararak ilgili ihtilafı çözüme kavuşturmak açısından bir
faaliyet gösteremez. Bu *tasarruf ilkesinin* doğal bir yansımasıdır.
+
[caption=""]
.Tasarruf ilkesi
====
*HMK 24*: (1) Hâkim, iki taraftan birinin talebi olmaksızın, kendiliğinden bir
davayı inceleyemez ve karara bağlayamaz.
====
+
Cumhuriyet Savcısı'nın müdahil olabileceği davalar haricinde kimse hakkını
talep etmeye zorlanamaz.
+
====
*HMK 24*: (2) Kanunda açıkça belirtilmedikçe, hiç kimse kendi lehine olan
davayı açmaya veya hakkını talep etmeye zorlanamaz.
====
+
Davanın açılmasından neticelenmesine kadar dava konusu olan hak üzerinde davalı
tarafın tasarruf yetkisi devam etmektedir.
+
====
*HMK 24*: (3) Tarafların üzerinde serbestçe tasarruf edebilecekleri dava konusu
hakkında, dava açıldıktan sonra da tasarruf yetkisi devam eder.
====
+
HMK 123 *Davanın geri alınması*, HMK 307 *Feragat*, HMK 308 *Davayı kabul*, HMK
349 *Başvurma hakkından feragat* tasarruf yetkisinin doğal yansımalarıdır.

* Vakaya isnat edici delilin haricen hakim tarafından tespit edilme
mükellefiyeti bulunmamaktadır. *Taraflarca getirilme ilkesi* uyarınca dava
malzemesi davacı, davalı veya vekilleri tarafından intikal ettirilir.
+
[caption=""]
.Taraflarca getirilme ilkesi
====
*HMK 25*: (1) Kanunda öngörülen istisnalar dışında, hâkim, iki taraftan birinin
söylemediği şeyi veya vakıaları kendiliğinden dikkate alamaz ve onları
hatırlatabilecek davranışlarda dahi bulunamaz.

(2) Kanunla belirtilen durumlar dışında, hâkim, kendiliğinden delil toplayamaz.
====
+
İddia ya da savunma açısından hakim, başka bir vaka ya da vakaların, o vakaya
isnat olunacak delillerin dosyaya getirilmesini taraflardan talep edemez,
kendisi böyle bir faaliyette bulunamaz.

* Hem davacının dava dilekçesinde yer alan hem de davalının cevap dilekçesinde
yer alan netice-i talepte belirtilen miktar be ise hakim bunun üzerinden karar
vermekle mükelleftir. Bu *taleple bağlılık ilkesidir*.
+
[caption=""]
.Taleple bağlılık ilkesi
====
*HMK 26*: (1) Hâkim, tarafların talep sonuçlarıyla bağlıdır; ondan fazlasına
veya başka bir şeye karar veremez. Duruma göre, talep sonucundan daha azına
karar verebilir.

(2) Hâkimin, tarafların talebiyle bağlı olmadığına ilişkin kanun hükümleri
saklıdır.
====
+
Taleple bağlılık ilkesi, sadece meblağ bazında değil, talep edilen hukuki işlem
özelinde de mevzu bahis olabilir. Tartışma konusu yapılmayan hukuki işlem
gözönüne alınmaz. Ancak tartışma konusu yapılmış hukuki işlem değerlendirilip
bunun kısmen iptali, kısmen geçersizliği, kısmen icra kabiliyeti olduğuna
yönelik karar verilebilir.

* *Hukuki dinlenilme hakkı*, savunma hakkının doğal bir yansımasıdır.
Yargılamanın her aşamasında her iki taraf açısından gerçekleşmesi gereken bir
ilkedir.
+
[caption=""]
.Hukuki dinlenilme hakkı
====
*HMK 27*: (1) Davanın tarafları, müdahiller ve yargılamanın diğer ilgilileri,
kendi hakları ile bağlantılı olarak hukuki dinlenilme hakkına sahiptirler.

(2) Bu hak;

.. Yargılama ile ilgili olarak bilgi sahibi olunmasını,
.. Açıklama ve ispat hakkını,
.. Mahkemenin, açıklamaları dikkate alarak değerlendirmesini ve kararların
somut ve açık olarak gerekçelendirilmesini, içerir.
====
+
Taraf vekilleri de hukuki dinlenilme hakkından aynen tarafmışçasına istifade
ederler. 
+
Hukuki dinlenilme hakkına riayet edilmemesi istinaf tarafından kararın
kaldırılması ile sonuçlanır.

* Dosyanın tarafları ve taraf vekilleri, dosya kapsamındaki bilgi ve belgeleri
her zaman inceleme hakkına sahiptirler. Bu *aleniyet ilkesinin* doğal bir
sonucudur.
+
[caption=""]
.Aleniyet ilkesi
====
*HMK 28*: (1) Duruşma ve kararların bildirilmesi alenidir.

(2) Duruşmaların bir kısmının veya tamamının gizli olarak yapılmasına ancak
genel ahlâkın veya kamu güvenliğinin kesin olarak gerekli kıldığı hâllerde,
taraflardan birinin talebi üzerine yahut resen mahkemece karar verilebilir.

(3) Tarafların gizlilik talebi ön sorunlar hakkındaki hükümler çerçevesinde
gizli duruşmada incelenir ve karara bağlanır.  Hâkim, bu kararının
gerekçelerini, esas hakkındaki kararı ile birlikte açıklar.

(4) Hâkim, gizli yargılama işlemleri sırasında hazır bulunanları o yargılamayla
ilgili edindikleri bilgileri açıklamamaları hususunda uyarır ve 26/9/2004
tarihli ve 5237 sayılı Türk Ceza Kanununun gizliliğin ihlaline ilişkin hükmünün
uygulanacağını ihtar ederek bu hususu tutanağa geçirir.
====
+
Aleniyet ilkesi çerçevesinde duruşmaların aleni olması ve hükmün aleni olarak
verilmesi esastır. Bunun istisnası gizlilik kararıdır. Haksız bir şekilde
gizlilik kararı verilmişse, buna muhalefet ancak nihai karar ile yapılabilir.
Esasla birlikte eğer gizlilik kararının aleniyet ilkesine aykırı bir şekilde
bertaraf edildiği sonucuna varılmışsa bağımsız bir bozma kararı verilecektir.

* *Doğruyu söyleme yükümlülüğü*, taraf menfaati ile orantılı bir şekilde ifade
edilmiştir. Davanın tarafları, aleyhlerine olan hususları belirtmek zorunda
değildir. Bunu yapmaması doğruyu söyleme yükümlülüğüne riayet etmediği anlamına
gelmez. Bu taraf açısından da vekili açısından da geçerlidir.
+
[caption=""]
.Dürüst davranma ve doğruyu söyleme yükümlülüğü
====
*TBK 29*: (1) Taraflar, dürüstlük kuralına uygun davranmak zorundadırlar.

(2) Taraflar, davanın dayanağı olan vakıalara ilişkin açıklamalarını gerçeğe
uygun bir biçimde yapmakla yükümlüdürler.
====
+
Taraflar menfaatlerine olan hususları ileri sürerken bunları gerçeğe uygun
olarak ifade etmek zorundadırlar. Gerçeğe uygun beyanda bulunulmazsa bu beyan,
vaka ya da delil dikkate alınmaz.

* *Usul ekonomisi* ilkesi ile ilgili üç tane kriter vardır: Süre, düzenli
yürütülme ve gereksiz gider. Yargılamanın bunlara riayet edilerek yürütülmesi
gerekir.
+
[caption=""]
.Usul ekonomisi ilkesi
====
*HMK 30*: (1) Hâkim, yargılamanın makul süre içinde ve düzenli bir biçimde
yürütülmesini ve gereksiz gider yapılmamasını sağlamakla yükümlüdür.
====
+
Bir davanın kendi başına uzun sürmesi usul ekonomisine aykırı değildir. Tarafın
ya da hakimin kasten yargılamayı uzatmaya yönelik davranışları usul ekonomisine
aykırıdır.

* Hakim *davayı aydınlatma ödevi* uyarınca, tarafların sunduğu vakıanın
değerlendirilmesi kapsamında yetersizlik hissederse, bizzat tarafa (avukatı
değil) soru sorabilir, açıklama yapmasını isteyebilir, delil göstermesini
isteyebilir.
+
[caption=""]
.Hâkimin davayı aydınlatma ödevi
====
*HMK 31*: (1) Hâkim, uyuşmazlığın aydınlatılmasının zorunlu kıldığı durumlarda,
maddi veya hukuki açıdan belirsiz yahut çelişkili gördüğü hususlar hakkında,
taraflara açıklama yaptırabilir; soru sorabilir; delil gösterilmesini
isteyebilir.
====
+
[caption=""]
.Ön inceleme duruşması
====
*HMK 140*: (5) Ön inceleme duruşmasında, taraflara dilekçelerinde
gösterdikleri, ancak henüz sunmadıkları belgeleri mahkemeye sunmaları veya
başka yerden getirtilecek belgelerin getirtilebilmesi amacıyla gereken
açıklamayı yapmaları için iki haftalık kesin süre verilir. Bu hususların
verilen kesin süre içinde tam olarak yerine getirilmemesi hâlinde, o delile
dayanmaktan vazgeçilmiş sayılmasına karar verilir.
====
+
Davacı ve davalının ikinci dilekçelerini vermelerinden sonra iddia ve
savunmanın genişletilmesi ve değiştirilmesi yasağı başlar. Buna *teksif ilkesi*
denir. Bunun bir istisnası HMK 145 uyarınca sonradan delil gösterilmesidir.
+
[caption=""]
.Sonradan delil gösterilmesi
====
*HMK 145*: (1) Taraflar, Kanunda belirtilen süreden sonra delil gösteremezler.
Ancak bir delilin sonradan ileri sürülmesi yargılamayı geciktirme amacı
taşımıyorsa veya süresinde ileri sürülememesi ilgili tarafın kusurundan
kaynaklanmıyorsa, mahkeme o delilin sonradan gösterilmesine izin verebilir.
====
+
Hakimin davayı aydınlatma ödevi uyarınca yapılması talep edilen açıklamalar
yapılmaz, davete riayet edilmezse tarafın o delili dayandırdığı vaka, esasa
ilişkin hüküm tesis edilirken gözönüne alınmaz.

* Hakim, *yargılamanın sevk ve idaresinde* tek yetkilidir.
+
[caption=""]
.Yargılamanın sevk ve idaresi
====
*HMK 32*: (1) Yargılamayı, hâkim sevk ve idare eder; yargılama düzeninin
bozulmaması için gerekli her türlü tedbiri alır.

(2) Okunamayan veya uygunsuz yahut ilgisiz olan dilekçenin yeniden düzenlenmesi
için uygun bir süre verilir ve bu dilekçe dosyada kalır. Verilen süre içinde
yeni bir dilekçe düzenlenmezse, tekrar süre verilemez.
====

* Hakim *şekli hukuku re'sen uygular*. Ayrıca hükmü tesis ederken, ihtilafı
çözüme kavuştururken hangi kanunda yer alan hükmün esas alınacağı da hakime
bırakılmıştır. 
+
[caption=""]
.Hukukun uygulanması
====
*HMK 33*: (1) Hâkim, Türk hukukunu resen uygular.
====
+
Taleple bağlılık, norm tespitinde söz konusu değildir. Hakim hiç bahsi
geçmeyen bir normu tespit edip onun üzerine kararını kurabilir.

TIP: Hakim yargılama giderlerine hükmedecekse tarafların talebi ile bağlı
olmadan resen araştırma ilkesi ile karar verir. Bu bakımdan tarafın talebinin
çok üstüne ya da çok altında bir karar verebilme imkanı vardır. Tarafın
sunmadığı, hiç söz konusu etmediği hususlarla ilgili dahi yargılama giderlerine
hükmedebilir.

* *Doğrudanlık ilkesi* uyarınca, deliller davaya bakan mahkeme huzurunda,
mümkün olduğu kadar birlikte ve aynı duruşmada incelenir.
+
[caption=""]
.Delillerin incelenmesi ve istinabe
====
*HMK 197*: (1) Kanunda belirtilen hâller dışında, deliller davaya bakan mahkeme
huzurunda, mümkün olduğu kadar birlikte ve aynı duruşmada incelenir. Zorunlu
hâllerde, bazı delillerin incelenmesi başka bir duruşmaya bırakılabilir.

(2) Başka yerde bulunan ve mahkemeye getirilemeyen deliller, o yerde istinabe
yoluyla toplanabilir.

(3) Delillerin incelenmesi veya beyanların dinlenmesi sırasında taraflar,
istinabe olunan mahkemede hazır bulunabilir ve delillerle ilgili açıklama
haklarını kullanabilirler. Bu hususu sağlamak için, taraflara incelemenin
yapılacağı tarih ve yer bildirilir. Bu davet üzerine taraflar istinabe olunan
mahkemede hazır bulunmasalar dahi deliller incelenir veya beyanlar dinlenir.
====
+
Yargılamayı yürüten hakim, önündeki dosyaya sunulmuş delillere doğrudan temas
etmek zorundadır.
