= RÖNESANS, HÜMANİZM VE REFORM: Aklın ve Bireyin Yükselişi
Ege Güneş <egegunes@gmail.com>

Feodal üretim biçimi 11. yüzyıldan itibaren çözülmeye ya da dönüşme belirtileri
göstermeye başladı. 13. yüzyıldan itibaren kültürel yaşamda, sanat alanında
verilen ürünler, yığınlar arasında bir tür iletişim aracı olarak farklı yaşam
biçimlerinin yansıtılmasına olanak verdi. 1500'de doruğuna ulaşan, klasik Yunan
ve Roma düşüncesinin yeniden canlandırılması/Rönesans ile, yeni ufuklar açıldı.
Bu, insanın ve aklın yüceltilmesi, evrenin merkezine Tanrı yerine bireyin
yerleştirilmesi süreciydi.

== a. Reform Süreci ve Etkileri

1350-1650 yılları arasında Avrupa'da yoğun bir savaş dönemi yaşanmıştır.
Köylüler/serfler ile derebeyler/senyörler arasındaki savaşlar *köylü savaşları*
denilen sürece yol açmıştır. İkinci çatışma, giderek güçlenen kentte yaşayan
halk ile derebeyleri arasında açığa çıkmıştır. Bir diğeri, ulusal ölçekteki
hanedan mensupları ile İmparator ve Papa arasındaki mücadeledir. Dördüncüsü,
dinde reform yanlıları ile papa arasındaki savaş olmuştur ve nihayet krallarla
krallar arasında da savaş yaşanmıştır.

Reform süreci, Rönesans'ın dünyevi düzlemdeki arayışına karşılık uhrevi
düzlemde yer alan, dinsel bir revizyon girişimi idi. Vicdan ve inanç özgürlüğü
savunusu öne çıkmış değildi, doğrudan hoşgörü de Reformcuların asıl
ilgilendikleri konu değildi; Katolik Kilisesine karşı Kutsal Kitap otoritesi
vurgulanıyordu. Ancak bu süreç kaçınılmaz olarak Kilise otoritesinin
çatlamasına neden olmuştur ve *bireyin kendi başına karar verebilmesi hakkı*,
bireyin ufkunu genişletmiştir; vicdan özgürlüğü diğer özgürlüklerin, dinsel
çoğulculuk da siyasal çoğulculuğun önünü açtı. Özgürlüklerin tanınması ile
iktidarın sınırı ve zorba yönetime karşı direnme konularının ve bağlantılı
olarak da siyasal sözleşme görüşünün tartışılması olanağı doğdu.

1500'lü yıllarda dinsel alanda görülen Reform süreciyle, bir yandan mülkiyet ve
gelirde Kilise aleyhine el değiştirme ve yeni bir paylaşım gerçekleşmiş, öte
yanda eleştirel anlayış güç kazanmaya başlamıştır. Katolik-Protestan
çatışması, özünde dinsel iktidarın kaynağı sorununa dayanıyordu. Ortaçağın,
*feodal erk*-Kilise işbirliği ile ürettiği/yorumladığı ve dayattığı kurallar,
yükselen kentli tüccar-zanaatkar sınıfının beklenti ve davranışlarını
karşılayamadığı için gözden geçirilmeye muhtaçtı; dinsel ve etik değerlerin
yeniden yorumlanarak üretilmesi gereksinimi vardı.

=== i. Luther, Calvin ve Müntzer

==== 1. Martin Luther

Luther tanrının insan aklının ötesinde bir varlık olduğunu söyler ve bu sebple
tanrı ile insan arasında aracı bulunmaz ve insanı kurtuluşa erdirecek şey
yalnızca imanıdır der. İncil'in yerel dillere çevrilmesini istemiştir.
Kilisenin egemenliğinden kurtulunması için insanların incili anlaması
gerekiyordu ve bireylerin ancak incili okuyup anlayarak kurtuluşa
erebileceklerini savunuyordu.

Luther 1520'de yazdığı ve Protestanların, Katolik Kilisesinden ayrılmalarının
resmi ilanı olarak değerlendirilen "*_Alman Ulusu Soylularına Konuşma_*"sında,
Katolik Kilisesinin ve Papalığın, vergi, katkı ve diğer adlar altında
zenginliklere el koyduğunu, kendiliğinden kardinaller yaratıp bunları zengin
ettiğini, ve bu yolla Tanrıya olan hizmeti tahrip ettiğini belirttikten sonra;
çok ağır bir ifade ile, bu yapılanların Almanlar bakımından sonucunun söz
konusu hırsızlıktan mustarip olmaktan ve Papa tarafından Alman malvarlıklarının
tahrip edilmesinden başka bir şey olmadığını ileri sürmektedir.

Luther, Almanya imparatorlarının ve prenslerinin uzun yıllar boyunca, Papanın
_annates_ adlı vergiyi toplamasına izin verdiğini ve bu ödemelerin Papalığın
bir fon oluşturarak, Hristiyanlığı korumak amacıyla, Türklere ve kafirlere
karşı savaşmak üzere verildiğini hatırlatmaktadır. Yüzyıldan fazla bir süreden
beri toplanan bu paralar, şimdi Roma'daki makamların ve ilgililerin giderlerini
karşılamak için verilen düzenli vergiler haline gelmiştir. Bundan hareket
ederek Luther, yapılması gereken şeyin, Roma'ya _annates_ vergisi ödemeye
derhal son verilmesi olduğunu savunmaktadır.

Luther'in ileri sürdüğü görüşe göre, çıkarılacak bir imparatorluk yasası ile,
bundan böyle atamalarda Roma'dan onay alınmasından vazgeçilmelidir; kralı
kutsayan bir psikopos olarak yapacağının dışında Papanın İmparator üzerinde
hiçbir gücü bulunmamalıdır; papazların yalnız yaşamaları yönündeki zorlamadan
vazgeçilerek bir eşi ve çocukları olmasına izin verilmelidir.

Luther, köylüler önce kilise topraklarına saldırdığından, köylü ayaklanmalarını
desteklemiştir. Ancak köylüler soyluların topraklarına da saldırmaya başlayınca
köylülerin öldürülmesi gerektiğini savunmuştur. Luther kiliseyi dünyevi
iktidardan ayırarak egemenin krallık olduğunu dile getirmiştir. Hatta dünyevi
iktidarı kilisenin üzerine koymuştur. Kralın iktidarının tanrıdan geldiğini ve
krala karşı gelmenin tanrıya karşı gelmekle eş değer olduğunu söylemiştir.
Dolayısıyla dünyevi iktidara mutlak suretle boyun eğilmesi gerektiğini öne
sürmüş ve dünyevi iktidarı köylü ayaklanmalarına karşı yüceltmiştir.

==== 2. Jean Calvin

Calvin doğal bir düzen içerisinde yaşadığımızı ve bu düzeni kuranın tanrı
olduğunu, bu sebeple insan bu düzene itaat etmeli diyerek dünyevi iktidarı
yüceltmiştir. Peki, tanrının sözünden çıkarsa yönetici ne olur? Sadece tanrının
sözünden çıktığını hatırlatabiliriz. 

Luther, kurumsal bir kilise yapısına karşıydı. Calvin de böyle bir kiliseye
karşıdır fakat kilisenin var olması gerektiğini de söyler. Dünyevi ve ruhani
iktidarı birbirinden ayırır fakat dünyevi iktidarın ruhani iktidardan
kaynaklandığını da söyler.

Calvin, baskıya karşı direnme hakkını dinsel temelde en geniş anlamda
temellendiren adamların başında gelir. Calvin'den sonra 16. ve 17. yüzyıllarda
bu etkisini Nantes'de göreceğiz. Burdan Locke ve Hobbes'a sonra ise hukuk
metinlerine geçecektir. Bu yönüyle Calvin diğer reformistlerden ayrılır.

==== 3. Thomas Müntzer

Müntzer daha çok serflerin yanında yer alan bir reformisttir. Bu sebeple
Luther'e karşıydı ve köylülerle beraber hareket ediyordu. Neredeyse incile
karşı çıkarak daha çok insan aklına önem verilmesi gerektiğini savunmuştur.
Köylülerle birlikte paylaşımcı, eşitliğe dayanan bir düzen kurmaya çalışmıştır.

=== ii. Augsburg Dinsel Barışı (1555)

Lutheran prensler ve şehirlerin, kendi egemenlik alanlarında oturmakta
olanların dinlerini belirleme hakkı da dahil olmak üzere Katolik prenslerle tam
bir eşitliği temin etmeye yönelik ve Almanya'nın Katolik ve Protestan bölgeler
olarak ayrılmasını teyit eden 1555 tarihli "*_Augsburg Dinsel Barışı_*" din
özgürlüğü çerçevesinde insan hakları ile ilişkili olduğu gibi, bir anlaşma
niteliği taşıması nedeniyle de ayrıca önemlidir. 

Bu belgede, her bir prensin, kendisine tabi olanların dinlerini belirleme
yetkisini tanımakta; ama buna bitişik olarak, prensinkinden farklı dinsel
tercih kullanmak isteyenlerin ise, kendi seçecekleri bir başka yere göçmelerine
de izin vermektedir. Belge, Katolik ve Protestan mezhepler arasında yaşanan erk
mücadelesinin ürünü olarak açığa çıkmıştır. Dolayısıyla bu barış anlaşmasının
tarafları, bir yanda Roma İmparatorluğu ve Ferdinand, öte yanda ise prensler ve
Almanya içindeki tüm zümrelerdir.

=== iii. Nantes Fermanı (1598) ve Nantes Fermanının Geri Alınması (1685)

16'ncı yüzyılın ortalarına doğru, tahmini olarak 300 ile 400 bin kadar Fransız'ın,
Protestanlığın bir formu olan Kalvinizmi benimsemeleri olgusu ortaya çıktı. Bu
grubun, sayısal bakımdan çok büyük olmamakla birlikte, kral, soylular ve
burjuvalar arasında kayda değer ölçüde taraftar bulduğu için, etki ve ağırlığı
önem taşıyordu. Kısa süre sonra, özellikle İspanya'nın Katolik kralınca
desteklenen fanatik Fransız Katolik çevrelerin muhalefeti belirginleşti. 

16'ncı yüzyılın ikinci yarısının büyükçe bölümünde görülen din savaşları, on
binlerce kişinin ölmesine ve önemli maddi kayıplara yol açtı. 1598'de Fransa
Kralı IV.Henry, *Nantes Fermanını* çıkararak Protestan azınlığı yatıştıracak,
dolayısıyla ülkede süre giden din çatışmasına son vererek tacını da bu önemli
sorunun doğurduğu tehditten kurtaracak olan adımı attı. Bu ferman ile,
Protestanlar Katolikler karşısında tam bir eşitlik elde etmiş olmadılar; ancak
dinsel ve bazı diğer hakları elde ettiler. Bunlar arasında ibadet hakkı, yargı
ve maliye bürokrasisinde görev alabilme hakkı; Paris parlamentosunda
Protestanlar için ayrı bir bölüm ayrılması ve diğer bölgelerdeki yerel
parlamentolarda karma meclis sayılabilir.

1598 Nantes Fermanının sağladığı görece kolaylık ve ayrıcalıklar,
Protestanların daha çok iktidar talebi için de çeşitli hazırlıklar yapmaları
olanağı verdi ve izleyen dönem içinde monark ile çatışmaya girdiler. 1685
yılında Fransa Kralı XIV.Louis çıkardığı "*_Nantes Fermanının Hükümsüz
Kılınmasına Dair Ferman_*" ile, daha önce tanınan ayrıcalıkları ve hakları geri
aldı.

== b. Rönesans ve Etkileri

Leonardo Da Vinci (1452-1519) sanat ve teknik alanlarındaki gözlem ve
yaratılarıyla, Niccola Machiavelli (1469-1527), siyasetin doğasına, iktidarın
kullanılışına, bireysel özgürlüğün temellendirilişine ilişkin çözümlemesiyle,
bu sürece damgalarını vurmuşlardır. Yeni yaşama durumları, insana ilişkin
değerler, sanatsal ifade biçimleriyle de yaygınlaştı. Rönesans ile yeniden
başlayan bireyin yüceltilmesi, 1789 burjuva devrimi ile doruğa ulaşacaktı.

Bilimsel ve teknolojik ilerleme, matbaanın bulunuşu, kültürel yaşamda
belirleyici etkiler doğurdu. Reform sürecinin ilk yıllarında dini yayınlar daha
fazlaysa da, 1530'lardan sonra yükselen seküler/laik çıkarlara yönelik yayınlar
arttı.

Bilginin basılması, çoğaltılması ve dağıtılmasının daha ekonomik, kolay, hızlı
ve yaygın hale gelmesi okur-yazar oranında artışa da yol açtı. Bu süreci
besleyen bir başka gelişme, 14. ve 15. yüzyıllarda Avrupa'da monarklar,
prensler ve zengin tüccarlar tarafından yeni üniversitelerin kurulmasıdır.

Bilimsel düşüncenin gelişip serpilmesi, insanın kendisi, toplum ve nihayet doğa
üzerinde söz sahibi olmaya muktedir; bunları anlama, gerçekleştirme ve
dönüştürme gücüne sahip bir varlık olduğuna dair düşünceyi hem doğuruyor hem de
besliyordu. Eğer insan doğayı ve evreni kavrayabiliyor, en azından araştırıp
belli sonuçlara varabiliyor ise, yanlışlarını gördüğü, bizzat yaşadığı ve
mustarip olduğu mevcut toplumsal ve siyasal düzeni pekala değiştirebilir ve
düzeltebilirdi. Bu bireyin algılanmasında ve kavrayışında tarihi
değiştirebilecek denli önemli ve etkili bir dönüşümdü. En azından insanların bu
zamana dek olan bireysel yaşam deneyimleri ışığında hiç mümkün görünmeyen
bireysel refah, adalet ve mutluluk ve bunu yeşertecek hakkaniyetçi toplumsal ve
siyasal düzen, artık yakın gelecekte bir zorunluluktu.

Ekonomik yaşamda hareketlilik, kara Avrupa'sında dünya ticaretine açılma, Haçlı
Seferleri ile Doğu ile kurulan temas ve bunun ticari ve diğer alanlarda
yarattığı etkileşim, kentlerin yeniden canlanması ve yeni kentlerin kurulması,
zanaatın gelişmeye başlaması, göçler ve nüfusun artması, mevcut ekonomik,
siyasal düzenden hoşnut olmayan ve bunun değiştirilmesi gereksinimi duyan
burjuva sınıfının doğmasına yol açacaktır.

Avrupa'da 11. yüzyıldan itibaren kentlerin gelişmeye başlaması, bu yerleşkeleri
çok sayıda insan için, bu arada oraya göçen köylüler için de, bir sığınak
haline getiriyordu. Kent, yasayla koruma altına alınmış bir *özgürlük* olarak
algılanmaya başladı; insanlar orada iş, ekmek, adalet ve barına
bulabiliyorlardı. Kentlerin gelişimi, diğer yandan da kendi yönetici sınıfının
belirginleşmeye başlamasına kapı araladı. Bu kentlerin statülerinin, imtiyaz
yahut dokunulmazlıklarının kraliyet fermanları ile tanınması, aynı zamanda
burada oturup da özellikle ticaretle uğraşan kesimin, kendi geleneksel ticaret
hukukunun kraliyet nezdinde tanınması sonucu doğuruyordu. Dolayısıyla kentler
sadece baskıdan kaçıp sığınılacak mekanlar değildi, aynı zamanda ticari
faaliyetin de serbestçe yapılacağı mekanlar yahut yerleşkeler özelliği
taşıyordu.

Özellikle 16. yüzyılla birlikte ticari ve sanayi gelişim kentlerde bir yandan
zengin yeni sınıfların doğmasına yol açarken, diğer yandan da kentte yerleşik
emekçi sınıfının ortaya çıkmasına neden oluyordu. Bireyler zengin olabiliyordu;
zengin olma ise siyasi iktidarı elde etme dürtüsünü kamçılıyordu. Süreç
kaçınılmaz biçimde zenginleşen burjuvalar ile emekçiler arasındaki sosyal
gerilimin tohumlarını da serpiyordu.

Yeniçağın biçimlenişinde, hukuksal-siyasal düşünce içinde merkezi sorun
oluşturan *siyasal erk*, bu terimi açıklamak ve tamamlamak üzere *egemenlik*,
şu özelliklere sahip olmalıydı: *Bölünmez*, *bütün* ve *sürekli*. Siyasal erk,
Machiavelli düşünüşünden farklı olarak, egemenin fiziksel varlığına bağımlı
değil, ondan bağımsızlaşarak süreklileşecekti. Jean Bodin'i özgün kılan da bu
idi.

Bu gelişmeler siyasal-hukuksal düşünüş ve düzende de yeni dönüşümlere yol açtı.
15. ve 16. yüzyıllarda, kilise iktidarının gerilemesiyle, ikici iktidar yapısı
da dönüşmeye başladı. Rönesansa ve Reforma ve düşünsel planda süre giden
gelişmeye karşın, 17. yüzyıl, uygulama alanında insan hak ve özgürlüklerinin
kurumsallaşmasının sağlama bağlandığı süreç olmak yerine, monarşik yönetimlerin
saltçılığının belirginleştiği evre olmuştur.

Aydınlanma düşüncesi, akılcılıktan, zenginleşmeden, doğaya daha çok egemen
olmaktan, ilerleme inancından, buna yol açan üretim ve ticaretten
beslenmekteydi. Dolayısıyla bu düşüncenin savunucuları, dönemin, ekonomik
yönden ilerici, gelişmelerle doğrudan ilgili sınıfları idi; yani, tüccarlar,
ekonomi alanında aydınlanmış toprak sahipleri, bankerler, okumuş orta sınıf
imalatçılar ve girişimcilerdi. 17. ve 18. yüzyıl, tüccar kesimin toplumsal
prestijinin en yüksek olduğu evre olmuştur. Antik çağ, ticari kazancı ahlak
açısından kuşkuyla karşılamıştı ve tüccarı hor görmüştü. Tüccarın saygın bir
statüye gelebilmesi _merkantilist_ evrede açığa çıkacaktı. Bu evrenin
düşünürleri ve yazarları da, ticareti ve taciri yücelten bir söylem
geliştirmişlerdi.

.Merkantilizm
====
Ortaçağ sonları (1500)-Sanayi devrimi (1800)

* Millerin refahı anaparanın miktarına bağlıdır.
* Yönetim ekonomide korumacı rol almalıdır.
* Dış satım desteklenmeli, dış alım sınırlandırmalıdır.
====

Aydınlanma ideolijisin iki ana merkezi, Franse ve İngiltere idi. Aydınlanmış
insan düşüncesine laik, akılcı ve ilerici bir bireycilik damgasını vurmaktaydı.
Bir yandan da, Kilisenin, toplumu bölen ve derecelendirerek sınıflandıran
düşünce kalıplarından sıyrılmak isteniyordu. Dolayısıyla, aydınlanma düşüncesi,
tüm insanların özgürlüğü, eşitliği ve kardeşliği sloganlarını benimseyecekti.
İlerleme düşüncesi, bireysel yeteneğin engellenmemesi gerektiği uslamlamasına
dayanıyordu. Kuramsal açıdan aydınlanma düşüncesi, sadece orta sınıfın değil,
tüm insanların özgürleştirilmesini hedefliyordu. Bu yönüyle düşünüldüğünde
aydınlanma düşüncesi ve devinimi, devrimci öze sahipti; çünkü, yürürlükteki
düzenin tasfiyesi amacını taşıyordu.

Feodal üretim biçiminin çözülmesi ve kapitalist üretici güçlerin gelişerek
kent-soylu/burjuva sınıfını oluşturması ile, *klasik hak ve özgürlükler* doğmuş
oldu. Kent soylular bakımından, toplumun geleneksel siyasal ve hukuksal
örgütlenişiş yetersizdi. Sorunun özü, yeni bir toplumsal yapı kurabilmek amacı
ile siyasal erki ele geçirmekti. Aslında, mutlak monarşi, feodal-yasal
birimleri ortadan kaldırıp ulusal devleti kurduğuna göre, tarihsel görevini de
tamamlamıştı. 

Siyasal erkin ele geçirilmesi deviniminin meşrulaştırılması ise, özgürlük ve
eşitlik kavramlarına dayanmayı zorunda kıldı.

Ortaçağın _Hristiyan Etikinden_, Yeniçağın _Ticaret Etikine_ geçiş, dönemin
temel karakteristiklerinden birisiydi. 

Özetle, bu evrede siyasal erki kullananlar, Ortaçağdaki *tanrısal iktidar*
temilciliklerinden soyunup, Yeniçağda *devletin* temsilciliğini üstlenmişlerdi.
Bu yeni açılımlarla, birey, Ortaçağdaki senyörlerle olan eşitsizlikçi güç
ilişkisi bağlarından kurtulmaya başlıyor ve birinin diğeri ile biçimsel olarak
aynılaştırıldığı, soyut ve kuşatıcı bir *topluma* ve bu yoldan da, ortak
istencin neticesi olduğu varsayılan *devlete* bağlanıyordu.

Bireyin yükselişi, bir yanda *doğal hukuk/doğal haklar*, öte yanda *toplum
sözleşmesi* kuramlarıyla, kendi dayanaklarını biçimlendirmekteydi. Birey,
artık, toplumsal ve siyasal yapıyı şekillendirebilecek bir güçtü. Bunun
kaçınılmaz sonucu ise, siyasal erki kullananın, sadece Tanrıya hesap vermekle
yetinemeyeceği ve yönetilenlere karşı da sorumlu olacağı yaklaşımı olmuştur.
