:icons: font
:toc:
:toc-title: MİRAS

== TÜRK MİRAS HUKUKU SİSTEMİNİN ÖZELLİKLERİ

* *Külli* geçişi benimsemiştir.
* Her ölen kişinin bir _halefi_ vardır. En son halde halef olarak devlet işaret
edilmiştir.
* Açık ya da zımni herhangi bir kabul iradesinin yöneltilmesi ya da herhangi
bir işlemin yapılması söz konusu olmayı _kural olarak_ miras kendiliğinden
intikal eder.
* Mirasın intikali ile birlikte mirasçılar arasında elbirliği ile mülkiyet
doğar.
* Mirasçıların miras bırakanın borçlarından şahsi ve müteselsil olarak
sorumluluğu vardır.
* Belli şahıslar için kanuni mirasçı sıfatı tanınmakta, ancak bunun yanın miras
bırakanın iradesine de belli bir oranda yer vermektedir.

== MİRAS HUKUKU KAVRAMLARI

* *Ölüm*: Kişiliğin, buna bağlı olarak da hak ve borç sahibi olma yeteneğinin
sona ermesidir. Ölüm mirasın açılma ve geçme anı olarak belirlenmiştir.
* *Miras bırakan*: Eski kanunda *muris* olarak geçmektedir.
* *Mirasçı*: Mirasa *külli* olarak sahip olan kişidir. İki tip mirasçı
olabilir:

. Yasal mirasçı
. İradi (atanmış/nasbedilmiş) mirasçı

+
Yasal mirasçı sıfatına sahip olmak için herhangi bir irade bildirimine gerek
yoktur. Ancak atanmış mirasçı murisin belirlediği mirasçıdır. Dolayısıyla
sıfatın kazanılması için bir irade bildirimine ihtiyaç duyar. İrade bildirimi
miras hukukunda sadece ve sadece *ölüme bağlı tasarruf* yoluyla olur.
* *Vasiyet alacaklısı (musaleh)*: Muris belirli bir malını ölüme bağlı tasarruf
yoluyla bir kimseye bırakmış olabilir. Bu kişi külli halef olanlara karşı bir
alacak hakkına haiz kılınmış olur ve vasiyet alacaklısı denilir.
+
CAUTION: Vasiyet alacaklısı mirasçı değildir! Mirasçılık ancak külli halefiyet
durumunda olur.
* *Tereke*: Ölenin mal, hak ve alacaklarının toplamını ifade eder. Terekede
sadece malvarlığı hakları bulunur. Keza malvarlığı hakkı olmasına rağmen
şahısla kaim olan haklar (intifa ve oturma hakkı) ölümle sona erer ve terekede
yer almaz.
* *Saklı (mahfuz) pay*: Kanunun sayma yöntemiyle belirlediği kanuni mirasçıların
terekeden almaları gereken payı ifade eder. Muris bu saklı payda tasarruf
yetkisine sahip değildir. Tasarruf ettiği takdirde sonradan iptale konu
olacaktır.
* *Ölüme bağlı tasarruf*: Miras hukukunda ölüme bağlı tasarruf ifadesi iki
anlamda hüküm ifade etmektedir:

. _Şekli anlamda ölüme bağlı tasarruf_

.. Vasiyetname
.. Miras sözleşmesi

. _Maddi anlamda ölüme bağlı tasarruf_: Şekli anlamda ölüme bağlı tasarruf ile
düzenlenen şeyler maddi anlamda ölüme bağlı tasarrufun konusudur.

== YASAL MİRASÇILAR

Türk miras hukuku sisteminde yasal mirasçıların belirlenmesi için *zümre esası*
uygulanmaktadır. Bu esasa göre belli zümreler yaratılarak ilk zümrede yer alanlar
mirasçı olarak belirlenir. İlk zümrede mirasçı olarak atanabilecek kimse yoksa
ikinci zümre mirasçı olur. İlk zümrenin mirasçılığı ikinci zümreye engel
olacaktır.

Zümrede yer alan herkes kendi zümresi açısından *zümre başı* sıfatını haiz
olacaktır. Zümre başı öldüğü takdirde halefiyet yine zümre içinde geçerli
olacaktır. Zümre başının halefi kendi altsoyudur. Zümre başının altsoyu mirasçı
sıfatını kazanmaz sadece zümre başının miras payını alır. Buna *kök içinde
halefiyet* denilmektedir.

=== 1. ZÜMRE: ALTSOY

Mirasbırakanın birinci derece mirasçıları, onun altsoyudur. Çocuklar eşit
olarak mirasçıdırlar.

Mirasbırakandan önce ölmüş olan çocukların yerini, her derecede halefiyet
yoluyla kendi altsoyları alır.

==== EVLİLİK DIŞI HISIMLAR

IMPORTANT: Mirasçılık için hukuki olarak soybağının varlığı şarttır.

Evlilik dışında doğmuş ve soybağı, tanıma veya hâkim hükmüyle kurulmuş olanlar,
baba yönünden evlilik içi hısımlar gibi mirasçı olurlar.

==== EVLATLIK

Evlâtlık ve altsoyu, evlât edinene kan hısımı gibi mirasçı olurlar. Evlâtlığın
kendi ailesindeki mirasçılığı da devam eder.

Evlât edinen ve hısımları, evlâtlığa mirasçı olmazlar.

CAUTION: Sadece ve sadece evlatlık ilişkisi kurulanlar arasında mirasçılık söz
konusu olur.

=== 2. ZÜMRE: ANA VE BABA

Altsoyu bulunmayan mirasbırakanın mirasçıları, ana ve babasıdır. Bunlar eşit
olarak mirasçıdırlar.

Mirasbırakandan önce ölmüş olan ana ve babanın yerlerini, her derecede
halefiyet yoluyla kendi altsoyları alır.

TIP: Anne ve babanın çocuğundan olan miras payı, kendi şahsına ait bir pay
olduğu için kişinin başka evliliğinden olan çocuklarının da o mirasta hak
sahibi olması mümkün olacaktır. Yani *kardeşlerin miras payı alması için aynı
evlilikten doğmuş olması şart değildir.*

Bir tarafta hiç mirasçı bulunmadığı takdirde, bütün miras diğer taraftaki
mirasçılara kalır.

=== 3. ZÜMRE: BÜYÜK ANNE VE BÜYÜK BABA

Altsoyu, ana ve babası ve onların altsoyu bulunmayan mirasbırakanın
mirasçıları, büyük ana ve büyük babalarıdır. Bunlar, eşit olarak mirasçıdırlar.

Mirasbırakandan önce ölmüş olan büyük ana ve büyük babaların yerlerini, her
derecede halefiyet yoluyla kendi altsoyları alır.

Ana veya baba tarafından olan büyük ana ve büyük babalardan biri altsoyu
bulunmaksızın mirasbırakandan önce ölmüşse, ona düşen pay aynı taraftaki
mirasçılara kalır.

Ana veya baba tarafından olan büyük ana ve büyük babaların ikisi de altsoyları
bulunmaksızın mirasbırakandan önce ölmüşlerse, bütün miras diğer taraftaki
mirasçılara kalır.

Sağ kalan eş varsa, büyük ana ve büyük babalardan birinin mirasbırakandan önce
ölmüş olması hâlinde, payı kendi çocuğuna; çocuğu yoksa o taraftaki büyük ana
ve büyük babaya; bir taraftaki büyük ana ve büyük babanın her ikisinin de ölmüş
olmaları hâlinde onların payları diğer tarafa geçer.

=== SAĞ KALAN EŞ

Sağ kalan eş, birlikte bulunduğu zümreye göre mirasbırakana aşağıdaki oranlarda
mirasçı olur:

. Mirasbırakanın altsoyu ile birlikte mirasçı olursa, mirasın dörtte biri,
. Mirasbırakanın ana ve baba zümresi ile birlikte mirasçı olursa, mirasın yarısı,
. Mirasbırakanın büyük ana ve büyük babaları ve onların çocukları ile birlikte
mirasçı olursa, mirasın dörtte üçü,
+
IMPORTANT: Eş, kuzenler ile mirasçı olursa mirasın tamamını alır.

bunlar da yoksa mirasın tamamı eşe kalır.

== ÖLÜME BAĞLI TASARRUFLAR

Ölüme bağlı tasarruf, *hüküm doğurması ölüme bağlanan* işlemdir. Ölüm bir
vadedir. Şart gibi hüküm doğursa da teknik anlamda bir şart değildir, zira
gerçekleşeceği kesindir.

Vasiyetname ve miras sözleşmesi dışında sağlıkta yapılan ve hükümlerini ölümle
doğuracak işlemler olabilir. Bu durumlarda TBK 290'daki "_Yerine getirilmesi
bağışlayanın ölümüne bağlı olan bağışlamada, vasiyete ilişkin hükümler
uygulanır_" hükmü kıyas yoluyla uygulanabilir.

Bir tasarrufun ölüme bağlı bir tasarruf mu yoksa sağlar arası bir tasarruf mu
olduğu konusunda kuşku doğarsa karine sağlar arası tasarruf olduğu yönündedir.

Ölüme bağlı tasarruf nitelendirmesi yapılırken temel ölçüt işlemin hukuki
sebebinin (_causa_) ölüm olup olmadığıdır.

== ŞEKLİ ANLAMDA ÖLÜME BAĞLI TASARRUFLAR

Şekli anlamda ölüme bağlı tasarruf *tip zorunluluğuna* tabidir. İki tane ölüme
baplı tasarruf şekli vardır: *Vasiyetname* ve *miras sözleşmesi*.

=== VASİYETNAME

Vasiyet yapabilmek için *ayırt etme gücüne sahip* ve *onbeş yaşını doldurmuş*
olmak gerekir.

CAUTION: "Vasiyet yapabilmek" ile kastedilen *vasiyetname* yapabilmektir.
Vasiyet ile vasiyetname farklı şeylerdir.

Kısıtlılar da ayırt etme gücüne sahip olmak ve 15 yaşını bitirmek koşuluyla
vasiyetname yapabilir. Bunun için kanuni temsilcinin izni gerekmemektedir.

Yaş şartı ve ayırt etme gücü ile beraber işlemin kurucu unsuru olarak hukuki
sebebi ölüm olan bir işlem yapma iradesi bulunmalıdır. Buna _animus testamanti_
denir.

Vasiyetname sıkı şekil kurallarına bağlı bir işlem olduğundan işlemin
yapılmasında bir sakatlık varsa sonradan verilen icazet şekle aykırılığı
gidermeyecektir.

Vasiyet, resmî şekilde veya mirasbırakanın el yazısı ile ya da sözlü olarak
yapılabilir.

==== EL YAZILI VASİYETNAME

El yazılı vasiyetnamenin yapıldığı yıl, ay ve gün gösterilerek başından sonuna
kadar mirasbırakanın el yazısıyla yazılmış ve imzalanmış olması zorunludur.

TIP: Tarih hata sonucu yanlış yazılmış ama metinden gerçek tarih
anlaşılabiliyor ise vasiyetname geçerli olacaktır.

İmzanın el yazılı olmasına ek olarak kişiliği de belirtmesi, o kişinin hep
attığı imzadan olması gerekir.

Mirasbırakan sonradan vasiyetnameye ekleme yapabilir. Eklemenin geçerli olması
için bunun da tarih taşıması ve imzalanması gereklidir.

El yazılı vasiyetnamein bir kısmı mirasbırakan tarafından çizildiyse geriye
kalan içerik kendi başına anlamlı ise geçerliliğini korur. Hepsinin çizilmesi
halinde vasiyetname geçersiz hale gelir.

Vasiyetname bir başkası tarafından çizilirse çizmenin başka biri tarafından
yapıldığının ispatı ile çizilen kısmın içeriğinin ispatı şartıyla vasiyetname
geçerliliğini korur.

El yazılı vasiyetname, saklanmak üzere açık veya kapalı olarak notere, sulh
hâkimine veya yetkili memura bırakılabilir.

Mirasbırakanın ölümünden sonra ele geçen vasiyetnamesinin, geçerli olup
olmadığına bakılmaksızın hemen sulh hâkimine teslim edilmesi zorunludur.

==== RESMİ VASİYETNAME

Resmî vasiyetname, iki tanığın katılmasıyla resmî memur tarafından düzenlenir.

Resmî memur, sulh hâkimi, noter veya kanunla kendisine bu yetki verilmiş diğer
bir görevli olabilir.

Mirasbırakan, arzularını resmî memura bildirir. Bunun üzerine memur,
vasiyetnameyi yazar veya yazdırır ve okuması için mirasbırakana verir.
Vasiyetname, mirasbırakan tarafından okunup imzalanır. Memur, vasiyetnameyi
tarih koyarak imzalar.

Vasiyetnameye tarih ve imza konulduktan hemen sonra mirasbırakan, vasiyetnameyi
okuduğunu, bunun son arzularını içerdiğini memurun huzurunda iki tanığa beyan
eder. Tanıklar, bu beyanın kendi önlerinde yapıldığını ve mirasbırakanı
tasarrufa ehil gördüklerini vasiyetnameye yazarak veya yazdırarak altını
imzalarlar. Vasiyetname içeriğinin tanıklara bildirilmesi zorunlu değildir.

Mirasbırakan vasiyetnameyi bizzat okuyamaz veya imzalayamazsa, memur
vasiyetnameyi iki tanığın önünde ona okur ve bunun üzerine mirasbırakan
vasiyetnamenin son arzularını içerdiğini beyan eder. Bu durumda tanıklar, hem
mirasbırakanın beyanının kendi önlerinde yapıldığını ve onu tasarrufa ehil
gördüklerini; hem vasiyetnamenin kendi önlerinde memur tarafından mirasbırakana
okunduğunu ve onun vasiyetnamenin son arzularını içerdiğini beyan ettiğini
vasiyetnameye yazarak veya yazdırarak altını imzalarlar.

IMPORTANT: Mirasbırakanın beyanı ile tanıkların şerhi safhalarının aynı anda
olması gereklidir. Buna *işlemde birlik* (_unitas act_) denir.

Fiil ehliyeti bulunmayanlar, bir ceza mahkemesi kararıyla kamu hizmetinden
yasaklılar, okur yazar olmayanlar, mirasbırakanın eşi, üstsoy ve altsoy kan
hısımları, kardeşleri ve bu kişilerin eşleri, resmî vasiyetnamenin
düzenlenmesine memur veya tanık olarak katılamazlar.

Resmî vasiyetnamenin düzenlenmesine katılan memura ve tanıklara, bunların
üstsoy ve altsoy kan hısımlarına, kardeşlerine ve bu kişilerin eşlerine o
vasiyetname ile kazandırmada bulunulamaz.

Resmî vasiyetnameyi düzenleyen memur, vasiyetnamenin aslını saklamakla
yükümlüdür.

==== SÖZLÜ VASİYETNAME

Mirasbırakan; yakın ölüm tehlikesi, ulaşımın kesilmesi, hastalık, savaş gibi
olağanüstü durumlar yüzünden resmî veya el yazılı vasiyetname yapamıyorsa,
sözlü vasiyet yoluna başvurabilir. Bunun için mirasbırakan, son arzularını iki
tanığa anlatır ve onlara bu beyanına uygun bir vasiyetname yazmaları veya
yazdırmaları görevini yükler.

Resmî vasiyetname düzenlenmesinde okur yazar olma koşulu dışında, tanıklara
ilişkin yasaklar, sözlü vasiyetteki tanıklar için de geçerlidir.

Mirasbırakan tarafından görevlendirilen tanıklardan biri, kendilerine beyan
edilen son arzuları, yer, yıl, ay ve günü de belirterek hemen yazar, bu belgeyi
imzalar ve diğer tanığa imzalatır. Yazılan belgeyi ikisi birlikte vakit
geçirmeksizin bir sulh veya asliye mahkemesine verirler ve mirasbırakanı
vasiyetname yapmaya ehil gördüklerini, onun son arzularını olağanüstü durum
içinde kendilerine anlattığını hâkime beyan ederler.

Mahkemenin sulh veya asliye hukuk mahkemesi olması fark etmemektedir.

NOTE: Yargıtay üç günlük bir süreyi makul bulurken 7 günlük sürenin geç
olduğuna karar vermiştir. Her halükarda somut olayın şartlarına göre
değerlendirme yapılmalıdır.

Tanıklar, daha önce bir belge düzenlemek yerine, vakit geçirmeksizin mahkemeye
başvurup yukarıdaki hususları beyan ederek mirasbırakanın son arzularını bir
tutanağa geçirtebilirler.

Sözlü vasiyet yoluna başvuran kimse askerlik hizmetinde bulunuyorsa, teğmen
veya daha yüksek rütbeli bir subay; Ülke sınırları dışında seyreden bir ulaşım
aracında bulunuyorsa, o aracın sorumlu yöneticisi; sağlık kurumlarında tedavi
edilmekteyse, sağlık kurumunun en yetkili yöneticisi hâkim yerine geçer.

TIP: Eski bir Yargıtay kararında İsviçre'deki bir mahkemeye giderek ölenin son
arzularını tutanak altına aldıran iki tanığın beyanı da mahkeme hükmü gibi
değerlendirilmiştir.

*Geçerlilik koşulları olmamasına rağmen hakim tarafından vasiyetname
düzenlenmişse bu ancak iptal davasına konu olabilecektir.*

Mirasbırakan için sonradan diğer şekillerde vasiyetname yapma olanağı doğarsa,
bu tarihin üzerinden bir ay geçince sözlü vasiyet hükümden düşer.

=== MİRAS SÖZLEŞMESİ

Miras sözleşmesi yapabilmek için *ayırt etme gücüne sahip* ve *ergin olmak*,
*kısıtlı bulunmamak* gerekir.

Miras sözleşmesinin geçerli olması için resmî vasiyetname şeklinde düzenlenmesi
gerekir.

Sözleşmenin tarafları, arzularını resmî memura aynı zamanda bildirirler ve
düzenlenen sözleşmeyi memurun ve iki tanığın önünde imzalarlar.

Ölüme bağlı tasarruf olduğundan taraflardan en az birinin ölüme bağlı
tasarrufta bulunması gerekir. Taraflardan ikisi de ölüme bağlı tasarrufta
bulunabilir ancak şart değildir.

Olumsuz miras sözleşmelerine *mirastan feragat sözleşmesi* denmektedir.
Mirastan feragat sözleşmelerinde ölüme bağlı tasarruf yapan mirasbırakandır.
Feragat eden, sağlıktaki bir haktan feragat ettiği için ölüme bağlı tasarruf
yapmamaktadır.

TIP: Miras sözleşmesinde sağlar arası tasarrufta bulunanlar için tam ehliyet
koşulu aranmaz.

Ölüme bağlı tasarruf yapma şahsa sıkı sıkıya bağlı hakkın kullanımıdır ve
dolayısıyla temsil yasağı vardır.

=== HÜKÜMDEN DÜŞME

==== GENEL SEBEPLER

. *Mirasbırakandan önce ölüm*
. *Bozucu şartın gerçekleşmesi*
. *Mirastan yoksunluk sebepleri*
. *Boşanma*
+
"_Boşanan eşler, bu sıfatla birbirlerinin yasal mirasçısı olamazlar ve
boşanmadan önce yapılmış olan ölüme bağlı tasarruflarla kendilerine sağlanan
hakları, aksi tasarruftan anlaşılmadıkça, kaybederler._"
+
"_Boşanma davası devam ederken, ölen eşin mirasçılarından birisinin davaya
devam etmesi ve diğer eşin kusurunun ispatlanması hâlinde de yukarıdaki fıkra
hükmü uygulanır._"
. *Evliliğin butlanı kararı*

==== VASİYETNAME İÇİN ÖZEL SEBEPLER

. *Mirasbırakanın fiili*

.. _Yeni vasiyetname_: Mirasbırakan, vasiyetname için kanunda öngörülen
şekillerden birine uymak suretiyle yeni bir vasiyetname yaparak önceki
vasiyetnameden her zaman dönebilir. Vasiyetnamenin tamamından veya bir
kısmından dönülebilir.
+
[TIP]
====
Dönülen vasiyetnameden dönülebilir mi?

Örneğin kişi vasiyetname ile evini birine bıraktı. İkinci bir vasiyetname ile
de birinci vasiyetnamesinden döndü. Üçüncü bir vasiyetname ile ikinci
vasiyetnamesinden dönerse birinci vasiyetname dirilecek midir?

*Baskın görüşe göre*, ikinci vasiyetnamede başka bir tasarruf yapılmamışsa
birinci vasiyetnamenin hüküm ifade edeceği kabul edilebilir. İkinci
vasiyetnamede başka tasarruflar varsa hepsinden dönülmüş olur.
====
.. _Yok etme_: Mirasbırakan, yok etmek suretiyle de vasiyetnameden
dönebilir.
.. _Sonraki tasarruflar_: Mirasbırakan, önceki vasiyetnamesini ortadan
kaldırmaksızın yeni bir vasiyetname yaparsa, kuşkuya yer bırakmayacak surette
önceki vasiyetnameyi tamamlamadıkça, sonraki vasiyetname onun yerini alır.
+
Belirli mal bırakma vasiyeti de, vasiyetnamede aksi belirtilmedikçe,
mirasbırakanın sonradan o mal üzerinde bu vasiyetle bağdaşmayan başka bir
tasarrufta bulunmasıyla ortadan kalkar.

. *Üçüncü kişinin fiili veya kaza*: Kaza sonucunda veya üçüncü kişinin
kusuruyla yok olan ve içeriğinin aynen ve tamamen belirlenmesine olanak
bulunmayan vasiyetname hükümsüz kalır. Tazminat isteme hakkı saklıdır.
+
Üçüncü kişi kusuruyla vasiyetnameyi yok etmiş ise ölüme bağlı tasarruf ile hak
kazanmasına engel olunan kişi malvarlığında meydana gelen zararı haksız fiil
hükümlerine dayanarak üçüncü kişiden talep edebilir. Bunun için haksız fiilden
sorumluluk şartlarının (fiilin hukuka aykırılığı, kusur, illiyet bağı vs.) yanı
sıra vasiyetnamedeki hakkın varlığının ispatı şarttır.
+
İçeriği aynen ve tamamen ispat edilebiliyorsa fiziki olarak elde bulunmayan
vasiyetnamenin dahi hüküm ifade etmesi sağlanabilir.
+
Örneğin fotoğraf ya da fotokopi ile vasiyetnamenin içeriği ispat edilebilir.
+
İçerik aynen ve tamamen ispat edilemese de tespi edilebilen içerik bağımsız ve
uygulanabilir bir tasarruf ifade ediyorsa bu kısmın geçerli olacağı doktrinde
kabul edilmektedir.
+
IMPORTANT: Vasiyetnameler her zaman ölüm ile hüküm doğurur. Sağlıkta
vasiyetnameler için işlem yapılmaz. Daha hüküm doğurmamış bir vasiyetnamenin
yok edilmesi zarara yol açmaz.

==== MİRAS SÖZLEŞMESİ İÇİN ÖZEL SEBEPLER

. *İkale sözleşmesi yapılması*: Miras sözleşmesi, tarafların yazılı
anlaşmasıyla her zaman ortadan kaldırılabilir.
. *İrade sakatlığının bulunması*: Mirasbırakanın yanılma, aldatma, korkutma
veya zorlama etkisi altında yaptığı ölüme bağlı tasarruf geçersizdir. Ancak,
mirasbırakan yanıldığını veya aldatıldığını öğrendiği ya da korkutma veya
zorlamanın etkisinden kurtulduğu günden başlayarak bir yıl içinde tasarruftan
dönmediği takdirde tasarruf geçerli sayılır.
+
Mirasbırakan henüz sona erdirme süresi dolmadan ölürse kalan süreyi mirasçıları
kullanabilir.
+
Ölüme bağlı tasarrufta kişinin veya şeyin belirtilmesinde açık yanılma hâlinde
mirasbırakanın gerçek arzusu kesin olarak tespit edilebilirse, tasarruf bu
arzuya göre düzeltilir.
. *Temerrüt hükümlerinin uygulanması*: Miras sözleşmesi gereğince sağlararası
edimleri isteme hakkı bulunan taraf, bu edimlerin sözleşmeye uygun olarak
yerine getirilmemesi veya güvenceye bağlanmaması hâlinde borçlar hukuku
kuralları uyarınca sözleşmeden dönebilir.
. *Hak sahibi olmaktan çıkarma*: Miras sözleşmesiyle mirasçı atanan veya
kendisine belirli mal bırakılan kişinin, mirasbırakana karşı miras
sözleşmesinin yapılmasından sonra mirasçılıktan çıkarma sebebi oluşturan
davranışta bulunduğu ortaya çıkarsa; mirasbırakan, miras sözleşmesini tek
taraflı olarak ortadan kaldırabilir.
+
Tek taraflı ortadan kaldırma, vasiyetnameler için kanunda öngörülen şekillerden
biriyle yapılır.
. *Sözleşmede dönme hakkının saklı tutulması*
. *Geçersizlik sebebi bulunması*
+
IMPORTANT: Eş, kuzenler ile mirasçı olursa mirasın tamamını alır.

== MADDİ ANLAMDA ÖLÜME BAĞLI TASARRUFLAR

Bir vasiyetnameye konu olan ölüme bağlı tasarruf tek taraflı olarak tasarrufa
konu olabilecek bir şey olmalıdır. Karşı tarafın rızasını almayı gerektiren
ölüme bağlı tasarruflar vasiyetname ile yapılamaz.

Mirastan feragat sözleşmesi, mirastan çıkarma sebepleri olmaksızın bir kanuni
mirasçının mirastan hak almamasını öngören bir hukuki işlemdir. Mutlaka miras
sözleşmesi ile yapılması gereken tek tasarruf mirastan feragat sözleşmesidir.

Mirastan feragat sözleşmesi dışında kalan her şey tek taraflı tasarrufa konu
olabilir ve dolayısıyla vasiyetnameye konu olabilir.

Miras sözleşmesi ile tek taraflı olan bütün ölüme bağlı tasarruflar
yapılabilir. Ancak niteliği gereği tek taraflı olan ölüme bağlı tasarruflar
miras sözleşmesinin tek taraflı içeriğini teşkil eder ve karşı tarafın iradesi
hiçbir rol oynamaz. Bu tasarruflar geçerlilik şartları açısından vasiyetname
gibi değerlendirilir.

=== KOŞUL VE YÜKLEME

Mirasbırakan, ölüme bağlı tasarruflarını koşullara veya yüklemelere
bağlayabilir. Tasarruf hüküm ve sonuçlarını doğurduğu andan itibaren, her
ilgili koşul veya yüklemenin yerine getirilmesini isteyebilir.

NOTE: Yükleme kural olarak kanuni mirasçılar içindir. Ancak kanuni mirasçılar
öldükten sonra onların mirasçılarına sirayet etmez.

Hukuka veya ahlâka aykırı koşullar ve yüklemeler, ilişkin bulundukları
tasarrufu geçersiz kılar.

Anlamsız veya yalnız başkalarını rahatsız edici nitelikte olan koşullar ve
yüklemeler yok sayılır.

IMPORTANT: Koşul bağımsız değildir, bir ölüme bağlı tasarrufa ihtiyaç duyar.
Buna karşılık yükleme bağımsızdır.

== MADDİ ANLAMDA ÖLÜME BAĞLI TASARRUF TÜRLERİ

=== MİRASÇI ATAMA

Mirasbırakan, mirasının tamamı veya belli bir oranı için bir veya birden çok
kişiyi mirasçı atayabilir.

Bir kişinin, mirasın tamamını veya belli bir oranını almasını içeren her
tasarruf, mirasçı atanması sayılır.

Kanuni mirasçılar için öngörülen bütün sonuçlar atanmış mirasçılar için de
uygulanır.

Atanmış mirasçı, mirası ölüm anında kendiliğinden kazanır. Mirasbırakanın ölümü
ile birlikte mal, hak ve borçlar külli olarak geçer.

Mirasçı atama gerçek kişiler için yapılabileceği gibi tüzel kişiler için de
yapılabilir.

Mirasbırakan, mirasçı olarak atadığı kişiyi, mutlaka kendisi seçmek zorundadır.
Zira ölüme bağlı tasarruf yapmak, şahsa bağlı hakkın kullanımıdır. Şahsa bağlı
haklarda temsil yürümez.

=== BELİRLİ MAL VEYA HAK VASİYETİ

Mirasbırakan, bir kimseye onu mirasçı atamaksızın belirli bir mal bırakma
yoluyla kazandırmada bulunabilir.

Belirli mal bırakma, ölüme bağlı tasarrufla bir kimseye terekedeki bir malın
mülkiyetinin veya terekenin tamamı ya da bir kısmı üzerinde intifa hakkının
kazandırılmasına yönelik olabileceği gibi; bir kimse lehine tereke değeri
üzerinden bir edimin yerine getirilmesinin, bir iradın bağlanmasının veya bir
kimsenin bir borçtan kurtarılmasının, mirasçılar veya belirli mal bırakılanlara
yükletilmesi suretiyle de olabilir.

Bırakılan belirli mal terekede bulunmadığı takdirde, tasarruftan aksi
anlaşılmadıkça, ölüme bağlı tasarrufu yerine getirmekle yükümlü olanlar borçtan
kurtulurlar.

Belirli mal veya hak bırakma halinde hak veya mal bırakılan kişi o hakka
mirasbırakanın ölümüyle kendiliğinden sahip olmaz. Tereke bütün olarak kanuni
mirasçılara geçer ve hak veya mal vasiyet edilmiş kişiler kanuni mirasçılara
ölüme bağlı tasarruftan doğan haklarını ileri sürerek ifasını talep eder.
Belirli mal veya hak bırakılan kişilerin sahip olduğu tek şey alacak hakkıdır.

==== BELİRLİ MAL VEYA HAK BIRAKMA ÇEŞİTLERİ

* *Mülkiyet vasiyeti:* Malın tüm kapsamı ile bırakılmasıdır. Mirasbırakan neyi
bıraktığını belirlemiş veya belirlenebilir kılmış olmalıdır.
* *İntifa hakkı vasiyeti:* Bir taşınmaz üzerinde intifa hakkı vasiyet
edildiğinde prosedür şu şekilde ilerleyecektir:

. Tereke mirasçılara geçer.
. Vasiyet alacaklısı intifa hakkını mirasçılara ileri sürer.
. Mirasçıların tescil talebi üzerine veya mirasçıların bunu ifa etmemesi
halinde açılacak dava sonucu alınan ile tapuya giden vasiyet alacaklısının
talebi üzerine intifa hakkı tescil edilir.

* *Tedarik vasiyeti:* Tereke üzerinde bir kimse lehine bir edimin yerine
getirilmesidir.
* *Alacak vasiyeti:* Mirasbırakan herhangi bir alacağını başkasına vasiyet
edebilir.
* *İbra vasiyeti:* Mirasbırakan, bir kimsenin bir borçtan kurtarılmasını
vasiyet edebilir.
* *İrat vasiyeti:* Kişinin terekesinden belli bir paranın belirli süreyle veya
süresiz olarak bir kişiye ödemesini ifade eder.

=== VAKIF KURMA

Mirasbırakan, terekesinin tasarruf edilebilir kısmının tamamını veya bir
bölümünü özgülemek suretiyle vakıf kurabilir.

Vakıf, ancak kanun hükümlerine uyulmak koşuluyla tüzel kişilik kazanır.

"_Vakıf kurma iradesi, resmî senetle veya ölüme bağlı tasarrufla açıklanır.
Vakıf, yerleşim yeri mahkemesi nezdinde tutulan sicile tescil ile tüzel kişilik
kazanır_."

IMPORTANT: Vakıf ölüme bağlı tasarruf ile kurulsa bile ölüm anında tüzel
kişilik kazanmaz.  Mirasbırakanın vakıf kurma iradesi ölüme bağlı tasarrufla
açıklandığı zaman, belirli kişilerin vakıf kurmak için gerekli işlemleri
yapması ve bunun sonucunda mirasbırakanın son yerleşim yeri asliye hukuk
mahkemesinde tescil ettirmesi gerekir. Vakıf ancak bu tescil ile tüzel kişilik
kazanır.

"_Mahkemeye başvurma, resmî senet düzenlenmiş ise vakfeden tarafından; vakıf
ölüme bağlı tasarrufa dayanıyorsa ilgililerin veya vasiyetnameyi açan sulh
hâkiminin bildirimi üzerine ya da Vakıflar Genel Müdürlüğünce re'sen yapılır._"

[NOTE]
====
Vakfın terekedeki malların mülkiyetini hangi anda kazanacağı doktrinde
tartışmalıdır.

*Cenin görüşüne göre*, vakıf kanuna uygun şekilde kurulup tüzel kişilik
kazandıktan sonra terekedeki mallar üzerinde mirasbırakanın ölümünden itibaren
hak kazanacaktır. Baskın görüş budur.

*Artmirasçı görüşüne göre*, vakıf malları tüzel kişilik kazandığı andan
itibaren kazanır. Bu ana kadar mallar üzerinde hak sahibi kanuni mirasçılardır.
Azınlıkta kalan bir görüştür.
====

Ölüme bağlı tasarrufla kurulan vakfın mirasbırakanın borçlarından sorumluluğu,
özgülenen mal ve haklarla sınırlıdır.

=== YEDEK MİRASÇI ATAMA

Mirasbırakan yaptığı ölüme bağlı tasarrufla başka bir kişiyi mirasçı olarak
atayabilir ya da ona belirli bir mal bırakabilir. Bu kişi herhangi bir sebeple
mirasa ehil olamazsa bu durumda söz konusu tasarruflar kural olarak yasal
mirasçılara döner. Bu kuralın istisnası **yedek mirasçı atama**dır.

Mirasbırakan, atadığı mirasçının kendisinden önce ölmesi veya mirası reddetmesi
hâlinde onun yerine geçmek üzere bir veya birden çok kişiyi yedek mirasçı
olarak atayabilir. Bu kural belirli mal bırakmada da uygulanır.

Yedek mirasçı birden fazla kişi de olabilir.

Yedek mirasçının mirası alabilmesi için murisin öldüğü anda hayatta olmasının
yeterli olduğu kabul edilmektedir.

[NOTE]
====
Muris yedek mirasçı atarken belirli bir sebep öngörmüş olabilir.

Örneğin mirasbırakan malvarlığının yarısını Y'ye bırakmış ve öldüğü anda Y de
*ölmüşse* malvarlığının yarısını C'nin almasını vasiyet etmiştir. Peki Y
ölmemiş de mirası reddetmişse ne olur?

Burada mirasbırakanın iradesine bakılmalıdır. Mirasbırakanın iradesi tam bir
yedek mirasçı atama mı yoksa sadece belli şartların gerçekleşmesi halinde yedek
mirasçı atama mı belirlenmelidir.
====

=== ARTMİRASÇI ATAMA

Mirasbırakan, ölüme bağlı tasarrufuyla önmirasçı atadığı kişiyi mirası
artmirasçıya devretmekle yükümlü kılabilir. Aynı yükümlülük artmirasçıya
yüklenemez. Bu kurallar belirli mal bırakmada da uygulanır.

TIP: Kural olarak bir kimsenin mirasçı olarak atanabilmesi için en azından
cenin olması gerekir. Fakat hiç doğmamış çocuk artmirasçı atama yoluyla mirasçı
olarak atanabilir.

Önmirasçı, mirası atanmış mirasçılar gibi kazanır. Önmirasçı, mirasa
artmirasçıya geçirme yükümlülüğü ile sahip olur.

Önmirasçı malları satamaz, bağışlayamaz, zarar verecek şekilde tasarruf edemez.

NOTE: Geciktirici şarta bağlı tasarruflar kendiliğinden artmirasçı atama
şeklindedir. Mirasbırakanın ölümünden itibaren malvarlığı yasal mirasçılara
geçmekte, şartın gerçekleşmesi ile birlikte artmirasçıya geçmektedir. Bu
artmirasçılık kanundan kaynaklanmaktadır.

Tasarrufta geçiş anı belirtilmemişse miras, önmirasçının ölümüyle artmirasçıya
geçer.

Tasarrufta geçiş anı gösterilmiş olup önmirasçının ölümünde bu an henüz
gelmemişse miras, güvence göstermeleri koşuluyla önmirasçının mirasçılarına
teslim edilir.

Mirasın artmirasçıya geçmesine herhangi bir sebeple olanak kalmadığı anda
miras, önmirasçıya; önmirasçı ölmüşse onun mirasçılarına kesin olarak kalır.

Önmirasçıya geçen mirasın sulh mahkemesince defteri tutulur.

Mirasbırakan açıkça bağışık tutmadıkça, mirasın önmirasçıya teslimi onun
güvence göstermesine bağlıdır.  Taşınmazlarda bu güvence, yeterli görüldüğü
takdirde mirası geçirme yükümlülüğünün tapu kütüğüne şerh verilmesiyle de
sağlanabilir.

Önmirasçı güvence göstermez veya artmirasçının beklenen haklarını tehlikeye
düşürürse, mirasın resmen yönetimine karar verilir.

Artmirasçı, mirası belirlenmiş olan geçiş anında sağ ise kazanır.

Artmirasçı geçiş anından önce ölmüşse, tasarrufta aksi öngörülmüş olmadıkça,
miras önmirasçıya kalır.

Önmirasçı mirasbırakanın ölümünde sağ değilse veya mirastan yoksun kalmışsa ya
da mirası reddederse, miras artmirasçıya geçer.

=== VASİYETİ TENFİZ MEMURU ATAMA

Mirasbırakan, vasiyetnameyle bir veya birden çok vasiyeti yerine getirme
görevlisi atayabilir.

[NOTE]
====
*Vasiyeti yerine getirme görevlisinin hukuki niteliği hususunda doktrinde
çeşitli görüşler vardır.*

* *1. görüş:* Vasiyeti yerine getirme görevlisi bir temsilci ve vekildir.
+
Bu görüşteki yazarlar da kendi içlerinde farklı görüşlere sahiptir.

** Bir kısım yazara göre vasiyeti yerine getirme görevlisi *mirasbırakanın*
temsilcisidir.
+
Bu görüşe karşı çıkan yazarlar ölü kimşenin temsil yetkisi olmaz demektedir.
** Bir kısım yazara göre *mirasçıların* temsilcisidir.
+
Bu görüşe karşı çıkan yazarlar mirasçıların vasiyeti yerine getirme görevlisini
azledemediğine dayanmaktadır.
** Bir kısım yazara göre vasiyeti yerine getirme görevlisi *miras
ortaklığının* temsilcisidir.
+
Bu görüşe karşı çıkan yazarlar miras ortaklığının tüzel kişiliği olmadığından
temsili de söz konusu olmaz demektedir.
* *2. görüş:* Burada bir _güvenilir kişi kurumu_ söz konusudur.
* *3. görüş:* Burada bir _sui genaris_ yani kendine özgü hukuki işlem söz
konusudur.
====

Vasiyeti yerine getirme görevlisinin, göreve başladığı sırada fiil ehliyetine
sahip olması gerekir.

Vasiyeti yerine getirme görevlisine sulh hâkimi tarafından bu görevi
bildirilir; bildirim tarihinden başlayarak onbeş gün içinde kabul edilmediği
sulh hâkimine bildirilmezse, görev kabul edilmiş sayılır.

Vasiyeti yerine getirme görevlisi hizmetinin karşılığında uygun bir ücret
isteyebilir.

Birden çok vasiyeti yerine getirme görevlisinin atanmış olması hâlinde,
tasarruftan veya işin niteliğinden aksi anlaşılmadıkça bunlar görevi birlikte
yürütürler.

Bunlardan biri görevi kabul etmez veya edemez ya da herhangi bir sebeple görevi
sona ererse, mirasbırakanın tasarrufundan aksi anlaşılmadıkça diğerleri göreve
devam eder.

Birden çok vasiyeti yerine getirme görevlisi birlikte hareket etmek üzere
atanmış olsa bile acele hâllerde her biri gerekli işlemleri yapabilir.

Mirasbırakan, tasarrufunda aksini öngörmüş veya sınırlı bir görev vermiş
olmadıkça vasiyeti yerine getirme görevlisi, mirasbırakanın son arzularının
yerine getirilmesi için gerekli bütün işlemleri yapmakla görevli ve yetkilidir.

Vasiyeti yerine getirme görevlisi, özellikle;

. Göreve başladıktan sonra gecikmeksizin terekedeki malların, hakların ve
borçların listesini düzenler. Liste düzenlenirken olanak varsa mirasçılar hazır
bulundurulur.
. Terekeyi yönetir ve yönetimin gerektirdiği ölçüde tereke mallarının
zilyetliğinin kendisine devrini ister.
. Tereke alacaklarını tahsil eder, borçlarını öder.
. Vasiyetleri yerine getirir.
+
NOTE: Normalde vasiyet alacaklıları alacaklarını mirasçılardan alır, ancak
vasiyeti yerine getirme görevlisi söz konusuysa alacaklarını ona karşı ileri
süreceklerdir.
. Terekenin paylaşılması için plân hazırlar.
. Tereke ile ilgili dava ve takiplerde miras ortaklığını temsil eder.
Mirasçılar tarafından açılmış davalardan görevi ile ilgili olanlara müdahil
olarak katılabilir.
. Açtığı veya aleyhine açılan davalar ile yapılan takipleri mirasçılara
bildirir.

NOTE: Bu hususlarda vasiyeti yerine getirme görevlisinin münhasır görevi söz
konusudur. Mirasçılar bu konuda görüş bildirebilir ancak kararı verecek olan
vasiyeti yerine getirme görevlisidir.

Mirasbırakan öldüğü anda terekesinde bulunan ve mirasçılara geçebilen tüm
malvarlığı üzerine mirasçılar kendiliğinden asli zilyet olurlar. Vasiyeti
yerine getirme görevlisi varsa mirasçılar dolaylı, asli zilyet olurken vasiyeti
yerine getirme görevlisi doğrudan, fer'i zilyet olur.

Tereke üzerinde yönetim yetkisinin kapsamına girdiği ölçüde vasiyeti yerine
getirme görevlisi hem aktif hem de pasif dava ehliyetine sahiptir. Bu dava
yetkisi kanundan kaynaklanmaktadır.

Terekedeki alacaklar bakımından vasiyeti yerine getirme görevlisi kendisi
davacı olabilir, bunu mirasçılar dava edemezler.

Terekenin borçlarından yasal ve varsa atanmış mirasçılar müteselsilen
sorumludur. Ama terekenin borçları bakımından alacaklılar ister vasiyeti yerine
getirme görevlisine dava açabilir isterse de mirasçılara dava açabilirler.
Ancak ikisi arasında fark vardır:

* Tereke alacaklısı vasiyeti yerine getirme görevlisine dava açarsa terekedeki
mallardan alacağını alabilir. Ancak terekedeki mallar yeterli değilse vasiyeti
yerine getirme görevlisinin sorumluluğuna gidemez. Dava mirasçılara karşı da
açılmadığı için onların kişisel sorumluluğuna da gidilemez.
* Alacaklı davayı mirasçılara açarsa mirasçılar vasiyeti yerine getirme
görevlisinden dolayı tereke üzerinde yetkili olmadıkları için terekedeki
mallara gidilemez. Sadece mirasçıların kişisel mallarına gidilebilir.

NOTE: Tereke alacaklısı için en uygun çözüm vasiyeti yerine getirme görevlisi
ile mirasçılara birlikte dava açmak olacaktır.

TIP: Tenkis davaları vasiyeti yerine getirme görevlisine karşı değil kendisine
tenkise tabi tasarruf yapılan mirasçıya karşı açılır.

Mirasbırakan taahhüt etmiş olmadıkça, terekeye dahil malların, vasiyeti yerine
getirme görevlisi tarafından devri veya bunlar üzerinde sınırlı aynî haklar
kurulması, sulh hâkiminin yetki vermesine bağlıdır. Hâkim, olanak bulunduğu
takdirde mirasçıları dinledikten sonra karar verir. Olağan giderleri
karşılayacak ölçüdeki tasarruflar için yetki almaya gerek yoktur.

Vasiyeti yerine getirme görevlisinin görevi, ölümü veya atanmasını geçersiz
kılan bir sebebin varlığı hâlinde kendiliğinden sona erer.

Vasiyeti yerine getirme görevlisi sulh hâkimine yapacağı bir beyanla görevinden
ayrılabilir. Görev uygunsuz bir zamanda bırakılamaz.

Vasiyeti yerine getirme görevlisi, görevinin yerine getirilmesinde sulh
hâkiminin denetimine tâbidir.  Hâkim, şikâyet üzerine veya re'sen gereken
önlemleri alır.

Vasiyeti yerine getirme görevlisinin yetersiz olduğu, görevini kötüye
kullandığı veya ağır ihmali tespit edilirse, sulh hâkimi tarafından görevine
son verilir. Bu karara karşı tebliğinden başlayarak onbeş gün içinde asliye
mahkemesine itiraz edilebilir. İtiraz üzerine verilen karar kesindir.

TIP: Mirasbırakanın son ikametgah yerindeki asliye ya da sulh hukuk mahkemesi
yetkilidir.

Vasiyeti yerine getirme görevlisi, görevini yerine getirirken özen göstermekle
yükümlüdür; ilgililere karşı bir vekil gibi sorumludur.

=== MİRASTAN FERAGAT SÖZLEŞMESİ

Mirasbırakan, bir mirasçısı ile karşılıksız veya bir karşılık sağlanarak
mirastan feragat sözleşmesi yapabilir.

Mirastan feragat sözleşmesi ile müstakbel mirasçı *beklenen bir hakkından*
vazgeçmektedir. Zira miras hakkı murisin ölümü ile doğar.

NOTE: Ölüme bağlı tasarruf olduğu için mirasbırakan bakımından bu sözleşmeyi
yapmak şahsa sıkı suretle bağlı bir haktır, temsilci vasıtasıyla yapılamaz.
Mirasçı bakımından sağlararası bir işlem olduğu için temsilci kullanılabilir.

Mirasbırakan saklı paylı mirasçısının saklı payını etkileyecek şekilde tasarruf
yapabilmek için onunla mirastan feragat sözleşmesi yapmalıdır.

Feragat eden, mirasçılık sıfatını kaybeder. Feragat tam olabileceği gibi kısmi
de olabilir.

Bir karşılık sağlanarak mirastan feragat, sözleşmede aksi öngörülmedikçe
feragat edenin altsoyu için de sonuç doğurur. Bu emredici bir hüküm değildir.
Dolayısıyla taraflar aksini kararlaştırmışsa sözleşme ivazlı da yapılmış olsa
altsoy mirasçı olabilir.

NOTE: Tarafların, ivazsız mirastan feragat sözleşmesinin altsoy için de sonuç
doğuracağına dair anlaşmalarının geçerli olup olmadığı doktrinde tartışmalıdır.
Bir görüşe göre ivazlıda nasıl yapılıyorsa aynı şekilde yapılabilir. Baskın
görüşe göre ise, altsoyun aleyhine bir sonuç doğurduğu ve kanunda açık
düzenleme olmadığı için yapılamaz.

Mirastan feragat sözleşmesi belli bir kişi lehine yapılmış olup bu kişinin
herhangi bir sebeple mirasçı olamaması hâlinde, feragat hükümden düşer.

Mirastan feragat sözleşmesi belli bir kişi lehine yapılmamışsa, en yakın ortak
kökün altsoyu lehine yapılmış sayılır ve bunların herhangi bir sebeple mirasçı
olamaması hâlinde, feragat yine hükümden düşer. Yani, mirasçı herhangi bir
kimse lehine mirastan feragat sözleşmesi yapmamışsa kendisi ile aynı zümrede
bulunan mirasçıların hepsi lehine feragat yapmış sayılır.

Mirasın açılması anında tereke, borçları karşılayamıyorsa ve borçlar mirasçılar
tarafından da ödenmiyorsa, feragat eden ve mirasçıları, alacaklılara karşı
feragat için ölümünden önceki beş yıl içinde mirasbırakandan almış oldukları
karşılıktan, mirasın açılması anındaki zenginleşmeleri tutarında sorumludurlar.

=== CEZAİ MİRASÇILIKTAN ÇIKARMA

Aşağıdaki durumlarda mirasbırakan, ölüme bağlı bir tasarrufla saklı paylı
mirasçısını mirasçılıktan çıkarabilir:

. Mirasçı, mirasbırakana veya mirasbırakanın yakınlarından birine karşı ağır
bir suç işlemişse,

.. Suç ceza hukuku anlamında bir suç olmalıdır.
.. Hakim suçun aile bağlarını koparması bakımından ağır olup olmadığına karar
verecektir.
.. Suçun kasten işlenmiş olması gerekir.
.. Suçu işleyen mirasçının ceza almasına gerek yoktur.
. Mirasçı, mirasbırakana veya mirasbırakanın ailesi üyelerine karşı aile
hukukundan doğan yükümlülüklerini önemli ölçüde yerine getirmemişse.

Mirasçılıktan çıkarma, mirasbırakan ancak buna ilişkin tasarrufunda çıkarma
sebebini belirtmişse geçerlidir.

Mirasçılıktan çıkarılan kimse itiraz ederse, belirtilen sebebin varlığını
ispat, çıkarmadan yararlanan mirasçıya veya vasiyet alacaklısına düşer.

Sebebin varlığı ispat edilememiş veya çıkarma sebebi tasarrufta belirtilmemişse
tasarruf, mirasçının saklı payı dışında yerine getirilir; ancak, mirasbırakan
bu tasarrufu çıkarma sebebi hakkında düştüğü açık bir yanılma yüzünden
yapmışsa, çıkarma geçersiz olur.

Mirasçılıktan çıkarılan kimse, mirastan pay alamayacağı gibi; tenkis davası da
açamaz.

Mirasbırakan başka türlü tasarrufta bulunmuş olmadıkça, mirasçılıktan çıkarılan
kimsenin miras payı, o kimse mirasbırakandan önce ölmüş gibi, mirasçılıktan
çıkarılanın varsa altsoyuna, yoksa mirasbırakanın yasal mirasçılarına kalır.

Mirasçılıktan çıkarılan kimsenin altsoyu, o kimse mirasbırakandan önce ölmüş
gibi saklı payını isteyebilir.

[NOTE]
====
*Mirastan çıkarılan kişi, mirasbırakan tarafından affedilirse bunun sonucu ne
olacaktır?*

* *1. görüş*: Mirasbırakan mirasçıyı affetmiş olsa da ancak hayattayken o ölüme
bağlı tasarrufu geri alarak sonuçlarını ortadan kaldırabilir.
* *2. görüş*: Kanunda boşluk vardır. Kanun koyucunun yoksunluk için düzenlediği
affetme hükmü kıyasen uygulanır. Ayrıca mirasbırakanın sağlığında mirasçıyı
affetmesi sebebin ortadan kalktığı anlamına gelir.
====

=== BORÇ ÖDEMEDEN ACİZ SEBEBİYLE MİRASÇILIKTAN ÇIKARMA

Mirasbırakan, hakkında borç ödemeden aciz belgesi bulunan altsoyunu, saklı
payının yarısı için mirasçılıktan çıkarabilir. Ancak, bu yarıyı mirasçılıktan
çıkarılanın doğmuş ve doğacak çocuklarına özgülemesi şarttır.

Miras açıldığı zaman borç ödemeden aciz belgesinin hükmü kalmamışsa veya
belgenin kapsadığı borç tutarı mirasçılıktan çıkarılanın miras payının yarısını
aşmıyorsa, mirasçılıktan çıkarılanın istemi üzerine çıkarma iptal olunur.

== ÖLÜME BAĞLI TASARRUFLARDA YORUM

Vasiyetname bakımından irade prensibi işler. Vasiyetnameler tek taraflı hukuki
işlemler olduğundan önemli olan mirasbırakanın ifadesidir.

Miras sözleşmeleri ise iki taraflı hukuki işlemlerdir. Dolayısıyla miras
sözleşmesine ilişkin ölüme bağlı tasarrufun yorumlanmasında güven prensibi söz
konusu olacaktır. Mirasbırakanın ifadelerinden gerçek iradesinin yanında karşı
tarafın dürüstlük kuralına göre ne anlaması gerekir, bu tespit edilerek
yorumlanır.

=== FAVOR TESTAMENTİ

_Bir ölüme bağlı tasarrufun içeriğinin farklı şekillerde yorumlanması mümkünse
tasarrufun sonuç doğurmasına imkan veren yorumlara öncelik tanınır._

[caption=""]
.Örnekler
====
*TMK 540/2:* "_Ölüme bağlı tasarrufta kişinin veya şeyin belirtilmesinde açık
yanılma hâlinde mirasbırakanın gerçek arzusu kesin olarak tespit edilebilirse,
tasarruf bu arzuya göre düzeltilir._"

*TMK 577/2:* "_Tüzel kişiliği bulunmayan bir topluluğa belli bir amaç için
yapılan kazandırmaları, o topluluk içindeki kişiler, mirasbırakan tarafından
belirlenen bu amacı gerçekleştirme kaydıyla birlikte edinmiş olurlar; amacın bu
yolla gerçekleştirilmesine olanak yoksa, yapılan kazandırma vakıf kurma
sayılır._"
====

=== KANUNİ MİRASIN GEÇİŞİ KURALLARINA BAĞLILIK

[caption=""]
.Örnekler
====
*TMK 560/2:* "_Yasal mirasçıların paylarına ilişkin olarak tasarrufta yer alan
kurallar, mirasbırakanın arzusunun başka türlü olduğu tasarruftan
anlaşılmadıkça, sadece paylaştırma kuralları sayılır._"

*TMK 647/3:* "_Aksini arzu ettiği tasarruftan anlaşılmadıkça, mirasbırakanın
tereke malını bir mirasçıya özgülemesi, vasiyet olmayıp sadece paylaştırma
kuralı sayılır._"
====

== ÖLÜME BAĞLI TASARRUFLARDA HÜKÜMSÜZLÜK

=== KANUN GEREĞİ KENDİLİĞİNDEN HÜKÜMSÜZ OLMA HALLERİ

* Evlilik birliği içerisinde eşler birbirlerine karşı ölüme bağlı tasarrufta
bulunmuşsa ve evlilik ölüm veya gaiplik dışında herhangi bir sebeple sona
ererse yapılan ölüme bağlı tasarruflar aksi anlaşılmadıkça kendiliğinden
hükümsüz olur.
* Mirasbırakan bir kişi lehine ölüme bağlı tasarruf yapmışsa, o kişinin
mirasbırakan öldüğü anda mirasa ehil olması gerekir. Aksi takdirde ölüme bağlı
tasarruf kendiliğinden hükümsüz olur.
* Lehine ölüme bağlı tasarruf yapılan kişinin mirastan yoksun olması halinde
ölüme bağlı tasarruf kendiliğinden hükümsüz olur.
* Ölüme bağlı tasarruf geciktirici şarta bağlı yapılmış ve bu şartın
gerçekleşmeyeceği kesin şekilde anlaşılıyorsa ölüme bağlı tasarruf
kendiliğinden hükümsüz olur.
* Ölüme bağlı tasarruf bozucu şarta bağlı olarak yapılmış ve bu şart
gerçekleşmişse ölüme bağlı tasarruf kendiliğinden hükümsüz olur.

=== İPTAL DAVASI İLE İLERİ SÜRÜLECEK HÜKÜMSÜZLÜK HALLERİ

Aşağıdaki sebeplerle ölüme bağlı bir tasarrufun iptali için dava açılabilir:

. Tasarruf mirasbırakanın tasarruf ehliyeti bulunmadığı bir sırada yapılmışsa,
. Tasarruf yanılma, aldatma, korkutma veya zorlama sonucunda yapılmışsa,

* *Yanılma:* Vasiyetnamelerin iptali bakımından mirasbırakanın her türlü hatası
iptal davasına sebebiyet verebilir. Miras sözleşmeleri ise tartışmalıdır.

** Bir görüşe göre kanun koyucu vasiyetnameler ile miras sözleşmeleri
bakımından bir ayrım yapmamıştır. Adi hata miras sözleşmelerinin iptali için
yeterlidir.
** Diğer bir görüşe göre miras sözleşmeleri iki taraflı hukuki işlem olduğundan
güven prensibi söz konusudur. Dolayısıyla ancak esaslı hata hallerinde iptal
edilebilir.

* *Hile:* Vasiyetnameler bakımından üçüncü kişinin hilesinin vasiyetnamenin
iptaline sebebiyet vermesi için lehine vasiyette bulunulan kişinin bunu bilip
bilmemesi aranmaz. Doktrinde bir görüşe göre ise miras sözleşmeleri bakımından
bu şarttır.
* *Korkutma ya da zorlama:* Mirasbırakanın yanılma, aldatma, korkutma veya
zorlama etkisi altında yaptığı ölüme bağlı tasarruf geçersizdir. Ancak,
mirasbırakan yanıldığını veya aldatıldığını öğrendiği ya da korkutma veya
zorlamanın etkisinden kurtulduğu günden başlayarak bir yıl içinde tasarruftan
dönmediği takdirde tasarruf geçerli sayılır.


. Tasarrufun içeriği, bağlandığı koşullar veya yüklemeler hukuka veya ahlâka
aykırı ise,
. Tasarruf kanunda öngörülen şekillere uyulmadan yapılmışsa.

İptal davası, tasarrufun iptal edilmesinde menfaati bulunan mirasçı veya
vasiyet alacaklısı tarafından açılabilir.

Dava, ölüme bağlı tasarrufun tamamının veya bir kısmının iptaline ilişkin
olabilir.

İptal davası, ölüme bağlı tasarrufla kendilerine, eşlerine veya hısımlarına
kazandırma yapılanların tasarrufun düzenlenmesine katılmalarının yol açtığı
sakatlığa dayandığı takdirde tasarrufun tamamı değil, yalnız bu kazandırmalar
iptal edilir.

İptal davası açma hakkı, davacının tasarrufu, iptal sebebini ve kendisinin hak
sahibi olduğunu öğrendiği tarihten başlayarak bir yıl ve her hâlde
vasiyetnamelerde açılma tarihinin, diğer tasarruflarda mirasın geçmesi
tarihinin üzerinden, iyiniyetli davalılara karşı on yıl, iyiniyetli olmayan
davalılara karşı yirmi yıl geçmekle düşer.

Hükümsüzlük, def"i yoluyla her zaman ileri sürülebilir.

[NOTE]
====
Miras sözleşmesinin hata, hile, tehdit nedeniyle sona erdirilmesinin ne
şekilde olacağı konusunda doktrinde çeşitli görüşler vardır.

. Bir yıllık sürede bir vasiyetname yapılması gerekir.
. Vasiyetname yapılmalı ayrıca karşı tarafa iptal beyanında bulunulmalıdır.
. Sadece iptal davası açması gerekir.
. Sadece karşı tarafa beyanda bulunması yeterlidir.
====

İptal davasıyla ölüme bağlı tasarruf iptal edildiğinde karar geriye etkilidir.

Mahkemenin iptal kararı sadece tarafları ilgilendirir, diğer kişilere etki
etmez.

== SAKLI PAYLI MİRASÇILAR

"_Mirasçı olarak altsoyu, ana ve babası veya eşi bulunan miras bırakan,
mirasının saklı paylar dışında kalan kısmında ölüme bağlı tasarrufta
bulunabilir. Bu mirasçılardan hiç biri yoksa, mirasbırakan mirasının tamamında
tasarruf edebilir._"

Mirasbırakan, saklı paylı mirasçısının saklı payına dokunamaz. Fakat
dokunduysa, yapılan işlem kendiliğinden geçersiz olmaz. Saklı payı ihlal edilen
mirasçı, tenkis davası açarak saklı payını alacak derecede tasarrufu
etkisizleştirebilir.

Kural olarak mirasbırakan ölüme bağlı tasarruf ile saklı paylı mirasçıların
saklı payına dokunamaz. Fakat mirasbırakan sağlararası işlem yaparak malları
üzerinde istediği gibi tasarruf edebilir. Buna rağmen belirli nitelikte
sağlararası işlemler tenkise tabidir.

TIP: Mirasbırakan sağlararası işlemle eşine evini satmış göstererek gerçekte
bağışlamış ise öncelikle muvazaa nedeniyle iptal davası açılacaktır. *Tenkis
davası açılırsa, mirasçı sadece saklı payını alır. Muvazaa nedeniyle iptal
davası açılırsa işlem iptal edildiği için mal terekeye döner ve mirasçı tüm
miras payını (yasal miras payını) alır.*

Saklı paylı mirasçılar:

. Altsoy (çocuk, torun, torunun torunu, evlatlık, evlatlığın altsoyu vs.)
. Anne baba
. Eş

NOTE: Zümrelerin hepsi aynı anda mirasçı olamaz. Örneğin altsoy varken anne
baba mirasçı olamaz. Fakat eş zümre mirasçısı olmadığı için her zümre ile
birlikte mirasçı olur.

Saklı paylı mirasçı varsa, saklı payların toplamı üzerinde mirasbırakan
tasarrufta bulunamaz. Bunun dışında kalan kısım, mirasbırakanın **tasarruf
nisabı**nı oluşturur.

Saklı pay oranları:

. Altsoy için yasal miras payının yarısı,
. Ana ve babadan her biri için yasal miras payının dörtte biri,
. Sağ kalan eş için, altsoy veya ana ve baba zümresiyle birlikte mirasçı olması
hâlinde yasal miras payının tamamı, diğer hâllerde yasal miras payının dörtte
üçü.

IMPORTANT: Saklı paylarda kök içi halefiyet kuralı işlemez.

== TEREKENİN PARASAL DEĞERİNİN HESAPLANMASI

Terekenin parasal değerinin hesaplanması için;

. Mirasbırakanın *tereke aktifleri* belirlenmelidir.
. Terekeden *çıkarılacak değerler* belirlenmelidir.
. Terekeye *eklenecek değerler* belirlenmelidir.

=== TEREKENİN AKTİFLERİ

Terekenin aktifi, mirasbırakanın ölümü anında, mirasbırakanın varlığının
aktifini oluşturan değerlerdir.

Mirasbırakan öldüğünde onunla sona eren haklar terekenin aktifine dahil edilmez.

Terekenin aktifinde yer alan alacak hakkının, sözleşmeden, haksız fiilden,
sebepsiz zenginleşmeden vs. kaynaklanması önemli değildir.

Manevi tazminatın mirasçılara geçmesi için mirasbırakanın ya talep etmiş olması
ya da davayı açmış olması gerekir.

NOTE: Evlilikte yasal mal rejimi, edinilmiş mallara katılma rejimidir. Edinilmiş
mallara katılma rejiminin sonra erme hallerinden biri ölümdür. Ölen eşin, sağ
kalan eşten artık paya katılma alacağı söz konusuysa bu değer terekenin aktifine
yazılır.

Terekenin aktifleri belirlenirken, mirasbırakanın ölümü günündeki duruma göre
hesaplanır.

=== ÇIKARILACAK DEĞERLER

Hesap yapılırken aşağıdaki kalemler terekeden indirilir:

. *Mirasbırakanın borçları*: Mirasbırakan öldükten sonra doğan borçlar kural
olarak terekeden çıkarılmaz, sağlığında mevcut borçlar çıkarılır. Bunun iki
istisnası vardır:
+
****
.. Mirasbırakan öldüğü için eğitimini bitirmeyen ya da engelli olan çocuklar
için uygun bir ödeme yapılır, bu miktar da borç olarak terekeden indirilir.
.. Çalışan 17 yaşındaki çocuk, gelirini babasına bırakmışsa, babası öldüğünde
bir miktar paranın tazminat olarak ödenmesi gerekir. Bu değer de terekeden
indirilir.
****
+
CAUTION: Vasiyet borçları çıkarılacak değerlere dahil değildir.
. *Cenaze giderleri*
. *Terekenin mühürlenmesi ve yazımı giderleri*
. *Mirasbırakan ile birlikte yaşayan ve onun tarafından bakılan kimselerin üç
aylık geçim giderleri*

.NET TEREKE = TEREKENİN AKTİFLERİ - ÇIKARILACAK DEĞERLER
****
****

=== EKLENECEK DEĞERLER

Net terekeye bazı değerler eklenerek *fiktif terekeye* ulaşılır. Net terekeye
eklenecek değerler:

. Mirasbırakanın *denkleştirmeye tabi* sağlararası ivazsız kazandırmaları
. Mirasbırakanın *tenkise tabi* sağlararası ivazsız kazandırmaları
. Bazı hayat sigortaları alım bedeli

=== DENKLEŞTİRMEYE TABİ İVAZSIZ KAZANDIRMALAR

Mirasbırakanın, sağlığında, *mirasçılarına* yapmış olduğu sağlararası ve ivazsız
kazandırmalar denkleştirmeye tabidir.

IMPORTANT: Üçüncü kişilere karşı sağlararası ivazsız kazandırmalar
denkleştirmeye tabi değildir. Denkleştirme ancak mirasçılar için söz konusu
olur.

Mirasbırakanın yaptığı sağlararası kazandırmalardan denkleştirmeye tabi olanlar:

.. Yasal mirasçılara, yasal miras paylarına mahsuben yapılmış karşılıksız
kazandırmalar
.. Mirasbırakan tarafından aksi belirtilmedikçe, mirasbırakanın sağlığında
altsoyuna yapmış olduğu çeyiz, kuruluş sermayesi, borçtan kurtarma gibi
kazandırmalar

Altsoy dışındaki mirasçılara yapılan karşılıksız kazandırmalar karine olarak
denkleştirmeye tabi değildir. Bunların denkleştirmeye tabi olması için
mirasbırakan tarafından açıkça denkleştirmeye tabi olduğu belirtilmelidir.
Altsoy bakımından ise tam tersi şekilde, mirasbırakan tarafından açıkça
belirtilmedikçe, yapılan karşılıksız kazandırmalar denkleştirmeye tabidir.

=== TENKİSE TABİ İVAZSIZ KAZANDIRMALAR

Mirasbırakanın sağlararası ivazsız kazandırmalarından tenkise tabi olanlar:

. *Denkleştirmeye tabi olması gerekirken bundan kurtulan kazandırmalar*

.. _Mirasbırakanın, mirasçılık sıfatını kaybeden yasal mirasçısına, miras payını
mahsuben yaptığı sağlararası kazandırmalar_
.. _Mirasbırakan tarafından denkleştirmeden muaf tutulduğu için denkleştirmesi
istenemeyen kazandırmalar_

. *Mirastan ivazlı feragat halinde mirasbırakanın mirasçıya hayatta iken ödediği
karşılık*

. *Bağışlayanın serbestçe dönme hakkını saklı tutarak yaptığı bağışlamalar ve
adet üzerine verilen hediyeler hariç olmak üzere, _mirasbırakanın ölümünden
önceki bir yıl içinde_ yapmış olduğu bağışlamalar*
+
Kazandırmanın tenkise tabi olup olmayacağına bakarken tasarruf işleminin
tarihine bakılır.
+
Bağışlama vaadi sözleşmesi yapıldıktan sonra tasarruf işlemi yapılmadan önce
mirasbırakanın ölmesi durumu tartışmalıdır. Bir görüşe göre bu da ölmeden bir
yıl önce yapılmış bağışlama gibi terekeye eklenir. *Kürsüye göre ise* burada
artık bir ölüme bağlı tasarruf söz konusudur. Mirasbırakan ölünce bağışlama sona
ermez, bağışlama yapılan kişiye karşı terekenin bir borcu söz konusudur. Bu
bağışlama bir ölüme bağlı tasarruf gibi işlem görür ve tüm ölüme bağlı
tasarruflar gibi tenkise tabidir.

. *Saklı payı etkisiz kılmak kaydıyla yapılan kazandırmalar*: Burada sadece
bağışlama değil, kazandırma söz konusu olduğundan bu kapsama satış, ölünceye
kadar bakma sözleşmesi, muvazaalı işlem vs. girebilir.
+
Saklı paylı mirasçıların saklı payına zarar verme kastı, mirasbırakanda olsa
yeterlidir. İşlemin karşı tarafının bunu bilmesine gerek yoktur. Mirasbırakan,
bu işlem sonucunda yasal mirasçıların saklı paylarını alamayacağını bilmelidir.
+
.Muris muvaazası
****
Mirasbırakanın sağlığında yaptığı muvazaalı işlem için tenkis davası mı açmak
gerekir, yoksa iptal davası mı açılmalıdır?

HMK hükümleri uyarınca muvazaa iddiası işlemin tarafları tarafından ileri
sürülüyorsa yazılı delille ispat edilmek zorundadır. Üçüncü kişiler ise işlemin
muvazaalı olduğunu her türlü delille ispat edebilir.

Muris muvazaasında, muvazaayı mirasçılar iddia edecektir. Mirasçılar da
mirasbırakanın külli halefleri olduğuna göre sözleşmenin tarafıdır ve
dolayısıyla üçüncü kişi değildir.

Yargıtay, bir içtihadı birleştirme kararında, saklı payı olsun olmasın her
mirasçının, muvazaalı işlemin iptalini dava edebileceğini kabul etmiştir.

Yine aynı içtihadı birleştirme kararında, mirasçıların miras hakkı ihlal
edildiğinden üçüncü kişi gibi her türlü delili kullanarak işlemin muvazaalı
olduğu ispatlanabilir denmiştir.

NOTE: Davayı tek bir mirasçı açarsa, kendi payı oranında düzeltme yapılır.

Başka bir içtihadı birleştirme kararında, saklı paylı mirasçı önce tenkis davası
açıp bu dava sonuçlandıktan sonra, muvazaa şartları varsa muvazaa davası da
açabilir denmiştir.
****

. *Mirasbırakanın hayattayken yapmış olduğu vakıf kurma işlemi*
. *Mirasbırakanın hayattayken kurduğu vakfa, _ölmeden önceki 1 yıl içinde_
özgülemiş olduğu malvarlığı değerleri*

=== BAZI HAYAT SİGORTALARI ALIM BEDELİ

Mirasbırakanın kendi ölümünde ödenmek üzere _üçüncü kişi lehine hayat sigortası
sözleşmesi yapması_ veya böyle bir kişiyi _sonradan lehtar olarak tayin etmesi_
ya da _sigortacıya karşı olan istem hakkını_ sağlararası veya ölüme bağlı
tasarrufla *karşılıksız* olarak üçüncü kişiye devretmesi halinde, *sigorta
alacağının mirasbırakanın ölümü zamanındaki satın alma değeri* terekeye eklenir.

.VARSAYIMSAL TEREKE = TEREKENİN AKTİFLERİ - ÇIKARILACAK DEĞERLER + EKLENECEK DEĞERLER
****
****

== TENKİS DAVASI

*Tenkis davası*, mirasbırakan, kanun koyucunun öngördüğünden daha fazla
tasarrufta bulunarak saklı paylı mirasçıların haklarını zedelemişse, saklı paylı
mirasçıların haklarını almalarını sağlayan davadır.

=== ŞARTLARI

Tenkis davası mirasçıların saklı paylarını ihlal eden *sağlararası* ve *ölüme
bağlı* tasarruflara karşı açılabilir.

Tenkis davası açılması için;

. *Kanuni mirasçının bulunması gerekir.*
. *Mirasbırakanın tasarruf oranını aşmış olması gerekir.*
. *Davacının saklı payını alamamış olması gerekir.*

Tenkis davası *geçerli bir işleme* karşı açılır. Geçerli bir işleme karşı
açıldığından *yenilik doğuran* bir davadır. Verilen karar da yenilik doğuran bir
karar olur ve yapılan geçerli bir kazandırmanın *saklı payı ihlal ettiği oranda*
geçmişe etkili olarak geçersizliğine karar verilir. Karar aynı zamanda bir eda
hükmünü de içerir.

=== DAVACI

Tenkis davası, mirasçılıktan doğan hakları koruyan bir davadır ve dolayısıyla
mirasçılık sıfatına bağlıdır. Aynı zamanda şahsa bağlı bir davadır.

Tenkis davası tüm mirasçıların aynı anda açacağı bir dava değildir. Her mirasçı
kendi saklı payını almak için dava açacaktır.

*Mirasçıların alacaklıları* ve *iflas masası* da tenkis davası açabilecektir.
Ancak doktrinde bunların önce mirasçıya başvurması ve bir süre vermesi, süre
sonunda tenkis davası açabileceği savunulmaktadır.

=== DAVALI

İster ölüme bağlı tasarrufla ister sağlararası tasarrufla *kazandırma lehtarı*
olan kişi davalı olacaktır. Bu kişi mirasçı ya da üçüncü kişi olabilir. Bu kişi
ölmüş ise mirasçılarına karşı dava açılabilir.

NOTE: Dava kural olarak tasarruf kime yapılmışsa ona karşı açılır ama istisnaen
kendisine mal devredilen üçüncü kişi kötü niyetliyse ve saklı pay kuralını
etkisizleştirmek amacıyla malı üçüncü kişiye devrederse o kişiye de dava
açılabilir.

=== DAVA AÇMA SÜRESİ

Tenkis davası her zaman *mirasbırakanın ölümünden sonra* açılır.

IMPORTANT: Tenkis davası bir yenilik doğuran dava olduğundan dava açma süresi
hak düşürücü süredir. Zamanaşımı değildir.

Tenkis davası açma hakkı, mirasçıların saklı paylarının zedelendiğini
öğrendikleri tarihten başlayarak *bir yıl* ve her halde vasiyetnamelerde açılma
tarihinin, diğer tasarruflarda mirasın açılması tarihinin üzerinden *on yıl*
geçmekle düşer.

TIP: Saklı payların ihlali, ölüme bağlı tasarrufun iptali ile söz konusu olmuşsa
dava açma süresi iptal kararının kesinleşmesiyle başlar.

=== TENKİS DEF'İ

Kanun koyucu tenkisi sadece dava olarak düzenlememiş, aynı zamanda def'i olarak
düzenlemiştir. Yani açılmış bir dava sırasında kanuni mirasçı, kendisinden
istenen bir malvarlığı unsuruna karşı tenkis hakkı olduğunu ileri sürebilir.

*Tenkis def'i hiçbir süreye bağlı değildir.*

Tenkis def'inden yararlanmak için;

. Mal ya da hakkın mirasçının elinde bulunması
. Karşı tarafın bu hak veya mal için mirasçıya dava açması

gerekir.

=== TENKİSTE SIRA

Tenkiste sıra probleminin gündeme gelmesi için tenkise tabi birden fazla ölüme
bağlı tasarruf ya da birden fazla sağlararası işlemin varlığı gerekir.

Tenkis, saklı pay tamamlanıncaya kadar, *önce ölüme bağlı tasarruflardan*; bu
yetmezse, en yeni tarihlisinden başlayarak sağlararası kazandırmalardan yapılır.

NOTE: Ölüme bağlı tasarruflar kural olarak hepsi aynı anda tenkis edilirken,
sağlararası kazandırmalar tarih itibariyle teker teker tenkis edilir.

Kamu tüzel kişileri ile kamuya yararlı dernek ve vakıflara yapılan ölüme bağlı
tasarruflar ve sağlararası kazandırmalar en son sırada tenkis edilir.

.Tenkis sırası
****
. Ölüme bağlı tasarruflar
. Sağlararası kazandırmalar
. Kamu tüzel kişileri ile kamuya yararlı dernek ve vakıflara yapılan ölüme
bağlı kazandırmalar
. Kamu tüzel kişileri ile kamuya yararlı dernek ve vakıflara yapılan tenkise
tabi sağlararası kazandırmalar
****

NOTE: Doktrinde bu sıranın emredici olduğu söylenmektedir. Mirasbırakan bu
sırayı yapmış olduğu ölüme bağlı tasarruflarla bozamaz.

=== ÖLÜME BAĞLI TASARRUFLARIN TENKİSİ

Tenkis, mirasbırakanın arzusunun başka türlü olduğu tasarruftan anlaşılmadıkça,
mirasçı ataması yoluyla veya diğer bir ölüme bağlı tasarrufla elde edilen
kazandırmaların *tamamında, orantılı* olarak yapılır.

Tenkis hesabı yapılırken dikkat edilmesi gereken en önemli husus, kazandırmanın
kime yapıldığıdır. Kazandırma üçüncü kişiye ya da saklı payı olmayan bir
mirasçıya yapılmışsa oran hesabı ve tenkis usulü farklıdır, saklı paylı
mirasçıya yapılmışsa farklıdır.

. Saklı payı olmayan mirasçı veya üçüncü kişiye yapılan tasarruflar:
+
.oran = saklı payı ihlal eden kısım / tüm ÖBT'ler toplamı
****
****
. Saklı paylı mirasçıya yapılan tasarruflar:
+
.oran = saklı payı aşan tasarruf miktarı x (saklı payı ihlal eden miktar toplamı / saklı paylar çıkarıldıktan sonra kalan tasarruf miktarı)
****
****
+
Saklı pay sahibi mirasçılara ölüme bağlı tasarrufla yapılan ve tasarruf
edilebilir kısmı aşan kazandırmaların *onların saklı paylarını aşan kımsı*
orantılı olarak tenkise tabi olur.
+
Tenkise tabi birden fazla ölüme bağlı tasarrufun bulunması halinde, saklı pay
sahibi mirasçıya yapılan kazandırmanın saklı payı aşan kısmı ile saklı pay
sahibi olmayan kimselere yapılan kazandırmalar orantılı olarak tenkis edilir.

IMPORTANT: Tenkis oranı belirlenirken saklı paylı mirasçıya yapılan tasarrufun
tamamı değil, saklı payı aşan kısmı dikkate alınır. Tenkis hesabı da saklı
paylar çıkarıldıktan sonraki tasarruflar üzerinden belirlenir.

=== SAĞLARARASI TASARRUFLARIN TENKİSİ

Sağlararası tasarruflarda en son tarihten başlayarak tenkis yapılır. En son
tarihli tasarrufun tümü, yetmediği takdirde bir önceki tasarrufun tümü tenkis
edilir.

CAUTION: Tenkis geçerli işlemlere uygulanan bir müeyyidedir. İhlali
karşılayacak miktara kadar tasarruf iptal edilir, kalan kısım geçerli olarak
kalır.

TIP: Eğer tarihi ispatlanamayan birden çok sağlararası tasarruf varsa doktrine
göre *hepsi orantılı olarak tenkise tabi tutulur*.

=== TENKİSTE BAZI ÖZEL DURUMLAR

==== BÖLÜNMEZ MAL VASİYETİNDE TENKİS

Değerinde azalma meydana gelmeksizin bölünmesine olanak bulunmayan belirli bir
mal vasiyeti tenkise tabi olursa, vasiyet alacaklısı, dilerse tenkisi gereken
kısmın değerini ödeyerek malın verilmesini, dilerse tasarruf edilebilir kısmın
değerini karşılayan parayı isteyebilir.

==== İNTİFA VE İRAT KAZANDIRMALARININ TENKİSİ

Öncelikle intifanın parasal değeri belirlenecektir. Ardından vasiyeti alan bu
parayı vererek hakka sahip olabilecektir.

==== İVAZLI MİRASTAN FERAGAT SÖZLEŞMELERİ

Saklı paylı mirasçılar, paylarını alamazsa mirastan feragat sözleşmesi
karşılığında alınan ivaz da tenkise konu olabilir.

CAUTION: İvazlı feragat eden mirasçının saklı payı da korunmuş olacağından
tenkis ancak saklı payı aşan kısım için söz konusu olur.

İvazı alarak mirastan feragat eden kişi, dilerse tankise tabi olan saklı payı
aşan kısmı verir, dilerse de ivazı tamamen vererek paylaşıma diğer mirasçılar
gibi katılır.

==== ARTMİRASÇI ATAMASINDA TENKİS

Eğer önmirasçı, kendisine yapılan kazandırmanın saklı payını karşılamadığını
düşünüyorsa tenkis isteme hakkı vardır.

==== YÜKLEMENİN TENKİSİ

Mirasçı, kendisine yapılan kazandırmanın tenkisi halinde yüklemenin de
tenkisini talep edebilir.

== DENKLEŞTİRME

Denkleştirme kurumu, *sağlıkta* kanuni mirasçılara yapılan karşılıksız
kazandırmaların vefat halinde terekeye dahil edilmesi ve kanuni mirasçılar
arasında *mirasbırakanın iradesi dışında* oluşacak bir eşitsizliğin
engellenmesidir.

Yapılan sağlararası kazandırma iade anındaki değeriyle terekeye girer.

Denkleştirme, mirasın paylaşılması sırasında *talep edilmesi* halinde devreye
girer. Denkleştirmeyi talep hakkı bir alacak hakkıdır.

Denkleştirme sadece kanuni mirasçılar için söz konusudur. Üçüncü kişilere
yapılan sağlararası kazandırmalar denkleştirmeye tabi değildir.

Kanuna göre miras paylaşımı sırasında her bir mirasçı, terekeyle ilgili
bilgileri dürüstçe vermelidir.

[%header,cols=2*]
.Denkleştirme ile tenkisin farkı
|===
|*Denkleştirme* |*Tenkis*

|Denkleştirme *kanuni miras payını* korur.
|Tenkis *saklı payı* korur.

|Tüm *kanuni mirasçılar* denkleştirme talep edebilir.
|Sadece *saklı paylı mirasçılar* tenkis talep edebilir.

|Denkleştirme kuralları *emredici değildir*.
|Tenkis kuralları *kısmi emredicidir*.

|Denkleştirme *sadece mirasçılar* arasında söz konusu olur.
|Tenkis mirasçılara ve *üçüncü kişilere* ileri sürülebilir.

|Denkleştirme *sadece sağlararası tasarruflar* için gündeme gelir.
|Tenkis hem sağlarası tasarruflar hem *ölüme bağlı tasarruflar* için gündeme gelir.

|Denkleştirme kazandırmanın *tamamen* terekeye dönmesini sağlar.
|Tenkis *ihlal oranında* iade sağlar.
|===

=== İADE YÜKÜMLÜLÜĞÜ

Yasal mirasçılar, mirasbırakandan miras paylarına mahsuben elde ettikleri
sağlararası karşılıksız kazandırmaları, denkleştirmeyi sağlamak için terekeye
geri vermekle birbirlerine karşı yükümlüdürler.

Mirasbırakanın çeyiz veya kuruluş sermayesi vermek ya da bir malvarlığını
devretmek veya borçtan kurtarmak ve benzerleri gibi karşılık almaksızın
altsoyuna yapmış olduğu kazandırmalar, aksi mirasbırakan tarafından açıkça
belirtilmiş olmadıkça, denkleştirmeye tabidir.

Olağan hediyeler ile evlenme sırasında yapılan geleneğe uygun giderler
denkleştirmeye tabi değildir.

Altsoy hısımlarının evlenmelerinde, alışılmış ölçüler içinde yapılan çeyiz
giderleri hakkında denkleştirmeye tabi tutmama arzusunun bulunduğu asıldır.

Yapılan kazandırma miras payını aştığı takdirde mirasçı, mirasbırakanın bunu
kendisine bırakmak istediğini ispat ederse, bu fazlalık denkleştirmeye tabi
olmaz. Diğer mirasçıların tenkise ilişkin hakları saklıdır.

==== ALTSOYUN İADE YÜKÜMLÜLÜĞÜ

Altsoyun yükümlülüğü kanundan doğan bir iade yükümlülüğüdür.

Kanuna göre, *karine olarak*, bir kişinin sağlığında altsoyunda yaptığı tüm
kazandırmalar denkleştirmeye tabidir. Altsoy karinenin aksini ispatlamak için
iki imkana sahiptir:

. Mirasbırakanın aksi yönde iradesini ispat etmek
. Mirasbırakanın sağlığında yaptığı kazandırmanın olağan hediye veya
evlendirme gideri olduğunu ispat etmek

==== ALTSOY DIŞINDAKİ KANUNİ MİRASÇILARIN İADE YÜKÜMLÜLÜĞÜ

Kanun, altsoy dışındaki kanuni mirasçıların iade mükellefiyetinin olmadığı
yönünde bir karine getirmektedir. *Altsoy dışındaki kanuni mirasçıların iade
mükellefiyeti sadece ve sadece mirasbırakanın iadesinden doğar*.

NOTE: Eş altsoy dışındaki mirasçı grubuna girer.

=== DENKLEŞTİRME ŞEKLİ

Geri vermekle yükümlü olan mirasçı, dilerse aldığını aynen geri verir; dilerse
payından fazla olsa bile değerini miras payına mahsup ettirir.

Mirasbırakanın bu kurala aykırı tasarrufları ve mirasçıların tenkise ilişkin
hakları saklıdır.

NOTE: Doktrine göre karma usül mümkün değildir.

=== EĞİTİM VE ÖĞRENİM GİDERLERİ

Çocukların eğitim ve öğrenimi için yapılan giderler sebebiyle geri verme
yükümlülüğü, mirasbırakanın aksini arzu ettiği ispat edilmedikçe, ancak
alışılmış ölçüleri aşan kısım için mevcuttur.

Eğitim ve öğrenimini tamamlamamış olan veya engelliliği bulunan çocuklara,
paylaşmada hakkaniyete uygun bir ödeme yapılır.

Çocuğa yapılacak ödeme, diğer kanuni mirasçıların miras payından indirim
yapılarak ödenir. Bu emredici bir hükümdür.

== MİRASIN GEÇMESİ

Ölüm anı gerçekleştiği anda mirasbırakanın terekesinde yer alan malvarlığı
değerleri *kül halinde* mirasçıların *iştirak* halinde mülkiyetine geçer.
İntikal, malvarlığı değerleri nerede ise orada gerçekleşir.

*Mirasın açıldığı yer*, terekeye dair ihtilafların çözüleceği yerdir. Terekeye
dair ihtilaflar, *mirasbırakanın yerleşim yeri* mahkemesinde çözülür*Mirasın
açıldığı yer*, terekeye dair ihtilafların çözüleceği yerdir. Terekeye dair
ihtilaflar, *mirasbırakanın yerleşim yeri* mahkemesinde çözülür.

Mirasçı olabilmek için;

. Mirasbırakan vefat ettiği ande hayatta olmak
. Mirasçılık ehliyetine (hak ehliyeti) sahip olmak
. Mirastan yoksun olmamak

gerekir.

=== MİRASTAN YOKSUNLUK

*Yoksunluk*, mirasçının, kanunun ifade ettiği gerekçeler kapsamında mirasa
layık görülmemesidir. *Kanunda aranan şartlar gerçekleşmişse, yoksunluk
kendiliğinden olur*.

Yoksunluk için kanunda sayılan fiillerin mirasbırakana karşı işlenmiş olması
gerekir. Mirasbırakanın bir yakınına karşı işlenmesi ancak mirastan çıkarma
sebebi olabilir.

*Yoksunluk afla ortadan kalkar.*

Sadece yasal mirasçılar değil, mirasçı olarak atanmış kişiler veya vasiyet
alacakları da mirastan yoksun olabilir.

Mirastan yoksunluk sebepleri:

. Mirasbırakanı kasten ve hukuka aykırı olarak öldüren veya öldürmeye teşebbüs
edenler
. Mirasbırakanı kasten ve hukuka aykırı olarak sürekli şekilde ölüme bağlı
tasarruf yapamayacak duruma getirenler
. Mirasbırakanın ölüme bağlı bir tasarruf yapmasını veya böyle bir tasarruftan
dönmesini aldatma, zorlama veya korkutma yoluyla sağlayanlar ve engelleyenler,
. Mirasbırakanın artık yeniden yapamayacağı bir durumda ve zamanda ölüme bağlı
tasarrufu kasten ve hukuka aykırı olarak ortadan kaldıranlar veya bozanlar

Yoksunluk kendiliğinden hüküm ifade eder ve kişi mirasbırakandan önce ölmüş
gibi kabul edilir.

=== MİRAS PAYININ DEVRİ

Mirasın açılmasından önce devirde, devralan kişi kesinlikle külli halef olmaz.
Sadece ölüm gerçekleştiğinde kendisine payını devreden kişiden bir alacak
hakkına sahip olur. Bu tür bir sözleşmenin yapılması için *mirasbırakanın bu
sözleşmeye katılması veya izin vermesi gerekir*.

Kişi miras payını bir *mirasçıya* devretmek isterse sözleşmenin *adi yazılı
şekilde* yapılması gerekir. Miras payını bir *üçüncü kişiye* devrediliyorsa
sözleşmenin *noterde düzenleme* şeklinde yapılması gerekir.

Miras payının devri mümkün iken *rehni mümkün değildir*. Rehin ayni bir haktır
ve ayni haklarda belirlilik ilkesi hakimdir. Miras payında ise devredilen şey
belli değildir.

=== KORUMA ÖNLEMLERİ

Mirasçılar düzgün şekilde tespit edilinceye kadar terekenin değer kaybına
uğramaması için birtakım koruma önlemleri alınabilir. Bu önlemi almaya yetkili
makam *mirasbırakanın son yerleşim yerindeki sulh hakimidir*. Ancak
mirasbırakan başka bir yerde öldüyse ve öldüğü yerde de malları varsa bu yerin
sulh hakimi de yerleşim yerindeki sulh hakimini haberdar ederek önlem almasını
talep edebilir veya kendi yetki alanındaki mallar için önlem alabilir.

Önlem talep üzerine alınmışsa ileride terekeden karşılanmak üzere talep
edenden, re'sen alınmışsa hazineden karşılanır.

==== DEFTER TUTMA

Defter tutma, hem terekedeki malların kayıt altına alınması hem de terekedeki
mallar üzerinde haklara etki edecek olan işlemlerin kayıt altına alınmasıdır.

Defter tutmaya aşağıdaki hallerde karar verilebilir:

* Mirasçılar arasında vesayet alınmış olan veya alınması gereken varsa
* Mirasçılardan biri uzun süreden beri bulunamıyorsa ve temsilcisi de yoksa
* Mirasçılardan veya ilgililerden biri, ölüm tarihinde başlayarak *bir ay
içinde* istemde bulunursa
+
Bu durumda hakimin takdir yetkisi yoktur.

==== TEREKENİN MÜHÜRLENMESİ

Yazımı yapılan tereke mallarından gerekenler *mühürlenir*. Mühürlenmeyen mallar
için uygun koruma önlemi alınmır. Mühür altına alma yazımdan önce de
yapılabilir.

Mühürleme, alacaklıların istemi üzerine yapılıyor ise güvence altına alınan
miktarla sınırlı bir mühürleme de yapılabilir. Ancak mirasçılar alacaklıya
güvence verirlerse o zaman mühürleme işlemine başvurulmaz.

==== TEREKENİN RESMEN YÖNETİLMESİ

Terekenin resmen yönetilmesi, terekenin *sulh hakimi* veya sulh hakiminin
görevlendirdiği bir kişi tarafından yönetilmesidir.

Terekenin resmen yönetilmesine aşağıdaki hallerde karar verilebilir:

* Mirasçılardan birinin uzun süreden beri bulunamaması ve temsilci de
bırakmaması halinde menfaati gerektiriyorsa
* Mirasta hak sahibi olduğunu ileri sürenlerden hiçbiri mirasçılık sıfatını
yeterince ispatlayamazsa veya bir mirasçı bulunup bulunmadığı şüpheli olursa
* Mirasçıların tamamı bilinmiyorsa

NOTE: Mirasbırakan öldükten sonra terekenin yönetilmesi için vasiyeti tenfiz
memuru atamışsa önemli bir engel bulunmadıkça terekenin bu kişi tarafından
yönetilmesi gerekir.

Yönetici, görevine giren konularda miras ortaklığının temsilcisidir.

Terekenin resmen yönetilmesine, niteliklerine uygun düştüğü ölçüde vesayete
ilişkin hükümler uygulanır.

==== MİRASÇILARA İLAN

Mirasbırakanın mirasçısı bulunup bulunmadığına dair kuşku varsa, uygun
araçlarla iki ayrı ilan yapılır ve son ilan tarihinden itibaren bir yıl içinde
başvuru olmazsa miras ya var olan mirasçılar arasında paylaştırılır ya da
mirasçı yoksa miras devlete geçer.

==== VASİYETE İLİŞKİN ÖNLEMLER

Mirasbırakan öldüğünde, kişinin elinde mirasbırakana ait bir vasiyetname varsa
bunu derhal mirasbırakanın son yerleşim yerindeki sulh hakimini tevdi
etmelidir. *Teslim için mirasçı olmak şart değildir*.

=== GAİPLİĞİN ETKİSİ

Kişi ölüm tehlikesi içinde kaybolduysa ya da kendisinden uzun süredir haber
alınmıyorsa gaiplik kararı alınmak suretiyle gaip kabul edilir. Gaiplik,
kararın alındığı tarihten değil, *kendisinden son haber alındığı günden veya
ölüm tehlikesi içinde kaybolma tarihinden itibaren hükümlerini doğurur.

Gaibin mirasçı olup olmadığını belirlemek için, mirasbırakanın ölüm tarihinde
hükümlerini doğurmuş bir gaiplik kararının olup olmadığına bakmak gerekir.

Kanun koyucu gaibin mirasının dağıtılması için güvence istenmesini öngörmüştür.
Bu güvence, gaip ortaya çıkarsa, mirasçılar terekeyi geri veremese bile gaibin
zor durumda kalmasını önlemek içindir. *Güvence olmasa bile, gaip geldiği andan
itibaren dağıtılan mirasın geri verilmesi gerekir.* Bu geri verme zilyetlik
kurallarına göre yapılır. *Mirasçı kötü niyetliyse gaip mirasın hepsini alır,
iyi niyetliyse sadece elinde kalan kısmı iadeyle yükümlüdür.*

Ölüm tehlikesi içinde kaybolan kişi için mirasçıları *5 yıl* için bir teminat
verecektir. Kişiden uzun süreden beri haber alınamıyorsa *15 yıl* için bir
teminat verilmelidir. Ancak kişinin *100 yaşına ulaşacağı süre* daha kısaysa bu
süre için teminat verilecektir. *Bu sürelerden sonra gaip gelirse miras yine
geri verilecektir, ancak artık teminatlardan yararlanamayacaktır*.

Gaip ortaya çıktıktan sonra mallarını zilyetlik kurallarına göre
isteyebilecektir. Mirasçı iyiniyetli ise miras sebebiyle istihkak davasındaki
10 yıllık süre uygulanır ancak kötüniyetli ise süre sınırlaması olmaksızın iade
talep edilebilir.

== MİRASÇILIK BELGESİ

Mirasçılık belgesi, kişinin mirasçılık sıfatını ispatlayan belgedir. Bu belge
sulh mahkemesi ve yeni düzenleme ile noterler tarafından verilir.

Atanmış mirasçılar ve vasiyet alacaklıları da mirasçılık belgesi talep
edebilir. Ancak bunların mirasçılık belgesi alabilmesi için öncelikle
vasiyetnamenin açılması gerekir. Ardından bir ay beklenir. Bu bir aylık süre
içinde mirasçılık belgesi verilmesine itiraz edilirse belge verilmez.

CAUTION: Mirasçılık belgesi, mirasçı olmayan kişiyi mirasçı yapmaz. Ancak bu
yönde bir karine oluşturur.
