== YABANCI

*Yabancı*, hiçbir devletin vatandaşlığını taşımayan veya bulunduğu devletin
vatandaşlığını taşımayan kişidir.

Anayasa'nın 16.maddesi "_Temel hak ve hürriyetler, yabancılar için,
milletlerarası hukuka uygun olarak kanunla sınırlanabilir._" demektedir.

== VATANSIZ

*Vatansız* kişilerin tanımı _Vatansız Kişilerin Hukuki Statüsüne İlişkin
Sözleşme_ ile yapılmıştır. Buna göre vatansız, "_herhangi bir devlet tarafından
kendi hukukuna göre vatandaş kabul edilmeyen kişidir._"

== MÜLTECİ

[caption=""]
.Mültecilerin Hukuki Statüsüne Dair Sözleşme
====
*Madde 2 -* [.line-through]#1 Ocak 1951'den önce# meydana gelen olaylar
sonucunda ve ırkı, dini, tabiiyeti, belli bir toplumsal gruba mensubiyeti veya
siyasi düşünceleri yüzünden, zulme uğrayacağından haklı sebeplerle korktuğu
için vatandaşı olduğu  ̧ülkenin dışında bulunan ve bu ülkenin korumasından
yararlanamayan, ya da söz konusu korku nedeniyle, yararlanmak istemeyen; yahut
tabiiyeti yoksa ve bu tür olaylar sonucu önceden yaşadığı ikamet ülkesinin
dışında bulunan, oraya dönemeyen veya söz konusu korku nedeniyle dönmek
istemeyen her şahsa uygulanacaktır.

Birden fazla tabiiyeti olan bir kişi hakkındaki "vatandaşı olduğu ülke"
ifadesi, tabiiyetini haiz olduğu ülkelerden her birini kasteder ve bir kişi,
haklı bir sebebe dayalı bir korku olmaksızın, vatandaşı olduğu ülkelerden
birinin korumasından yararlanmıyorsa, vatandaşı olduğu ülkenin korumasından
mahrum sayılmayacaktır.
====

[caption=""]
.6458 sayılı Yabancılar ve Uluslararası Koruma Kanunu
====
*Mülteci*

*MADDE 61 –* Avrupa ülkelerinde meydana gelen olaylar nedeniyle; ırkı, dini,
tabiiyeti, belli bir toplumsal gruba mensubiyeti veya siyasi düşüncelerinden
dolayı zulme uğrayacağından haklı sebeplerle korktuğu için vatandaşı olduğu
ülkenin dışında bulunan ve bu ülkenin korumasından yararlanamayan ya da söz
konusu korku nedeniyle yararlanmak istemeyen yabancıya veya bu tür olaylar
sonucu önceden yaşadığı ikamet ülkesinin dışında bulunan, oraya dönemeyen veya
söz konusu korku nedeniyle dönmek istemeyen vatansız kişiye statü belirleme
işlemleri sonrasında mülteci statüsü verilir.

*Şartlı mülteci*

*MADDE 62 –* Avrupa ülkeleri dışında meydana gelen olaylar sebebiyle; ırkı,
dini, tabiiyeti, belli bir toplumsal gruba mensubiyeti veya siyasi
düşüncelerinden dolayı zulme uğrayacağından haklı sebeplerle korktuğu için
vatandaşı olduğu ülkenin dışında bulunan ve bu ülkenin korumasından
yararlanamayan, ya da söz konusu korku nedeniyle yararlanmak istemeyen
yabancıya veya bu tür olaylar sonucu önceden yaşadığı ikamet ülkesinin dışında
bulunan, oraya dönemeyen veya söz konusu korku nedeniyle dönmek istemeyen
vatansız kişiye statü belirleme işlemleri sonrasında şartlı mülteci statüsü
verilir. Üçüncü ülkeye yerleştirilinceye kadar, şartlı mültecinin Türkiye’de
kalmasına izin verilir.
====
